### ISSUE TITLE
show correct docstring for wrapped function

### ISSUE THREAD

**Issue by wangchao1230** [microsoft/pylance-release#100]
## Environment data

-   Pylance language server: 2020.7.1 
-   OS and version: win 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.6 64bit

## Expected behaviour

![image](https://user-images.githubusercontent.com/47586720/87304912-2bb7bb80-c548-11ea-9e60-eb30d7fc07f8.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/47586720/87304872-19d61880-c548-11ea-8975-a33365633a42.png)

## Steps to reproduce

```python
from functools import wraps

def decorator(func):
    """ This is the decorator doc """
    @wraps(func)
    def wrapper(*args, **kwargs):
        """ This is the wrapper doc """
        return func(*args, **kwargs)
    return wrapper

@decorator
def some_func():
    """ This is the actual doc """
    return 1 + 1

some_func()
print(some_func.__name__)
print(some_func.__doc__)
```

**Comment by erictraut** [comment]
When you create a decorator, it replaces the function that it's decorating. Many decorators (like the one in your example) return the original function. This fact can be obscured to the type checker because of the way the they are annotated.

For a detailed explanation and the recommended fix, see [this issue](https://github.com/microsoft/pyright/issues/774). If you apply this fix within your code, the docstring of the original function will appear as you expect.

**Comment by wangchao1230** [comment]
Eric, thank you so much! 
That's exactly what I need. ❤️
