### ISSUE TITLE
Pylance syntax highlighting overrides user-defined color

### ISSUE THREAD

**Issue by m-beau** [microsoft/pylance-release#1000]
Hi,

Pylance semantic highlighting messes up the default theme syntax highlighting defined by the user, which is very annoying.

Adding
```
{
    "[python]": {
        "editor.semanticHighlighting.enabled": false
    }
}
```
to the settings.json file does not solve my problem.

## Environment data

-   Language Server version: 2021.2.4
-   OS and version: Mac OS Mojave 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.10

## Expected behaviour

Still have the user-defined colouring of selected text highlighting applied (`"editor.selectionHighlightBackground": "#000000"`).
Screenshot with IntelliSense (every `corr_type` instance is highlighted in black):
![image](https://user-images.githubusercontent.com/25953361/109402864-3dbc6200-7951-11eb-84c7-9c3d850406ee.png)

## Actual behaviour

When setting Pylance as language server (`"python.languageServer": "Pylance"`), Pylance colouring scheme takes over, overriding the user preferences.
Screenshot with Pylance (only some instances of `corr_type` are highlighted, in a faint hard to see light grey):
![image](https://user-images.githubusercontent.com/25953361/109402872-4e6cd800-7951-11eb-9358-3fbd4e2c49e1.png)

**Comment by jakebailey** [comment]
This isn't an override problem with semantic highlighting; the issue here is that Pylance provides an "occurrence highlighter" implementation to VS Code, which it uses to identify that one symbol is the same as another. In your first screenshot, `corr_type` is highlighted everywhere as it is using VS Code's "selection" highlighter. In the latter, VS Code calls Pylance to ask "give me the locations of all variables that are the same as this location", so it highlights those instead.

If you don't like Pylance's semantic occurrence highlighter, you can disable it with:

```json
"editor.occurrencesHighlight": false
```

Can you try adding this setting to see if your color setting then works?

But I would argue that it's likely a bug that VS Code isn't respecting your configuration (even if the setting says "selection" rather than "occurrence"). The semantic occurrence provider is much more useful than the selection method, so I'd rather not recommend disabling this feature to work around a VS Code quirk.

**Comment by jakebailey** [comment]
This issue hasn't been updated in over a month; closing. If you can try with that above setting we can revisit this (but I'm fairly certain that we need to be filing this on VS Code itself instead).
