### ISSUE TITLE
Incorrect inference of types as Literals causes problems with collections concatenation

### ISSUE THREAD

**Issue by ghost** [microsoft/pylance-release#1023]
## Environment data

-   Language Server version: 2021.3.0
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.2

## Expected behaviour

```python
foo: list[tuple[str, int]]
bar: dict[int, tuple[str, int]]
```

## Actual behaviour

Type of "foo" is unknown (reportUnknownVariableType)
Operator "+" not supported for types "list[tuple[Literal['a'], Literal[1]]]" and "list[tuple[Literal['b'], Literal[2]]]" (reportGeneralTypeIssues)
Type of "bar" is unknown (reportUnknownVariableType)
Operator "|" not supported for types "dict[int, tuple[Literal['a'], Literal[1]]]" and "dict[int, tuple[Literal['b'], Literal[2]]]" (reportGeneralTypeIssues)

## Code Snippet / Additional information

```python
foo = [("a", 1)] + [("b", 2)]
bar = {1: ("a", 1)} | {2: ("b", 2)}
```

**Comment by erictraut** [comment]
Pylance intentionally infers literal types for values inside of tuples. See [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#tuple-expressions) for details. This allows for better type checking and avoids a class of false positive errors.

The tradeoff with this approach is that you can run into cases like the sample above where additional type annotations are required.

Here's what you need to do to make this work:
```python
MyTuple = Tuple[str, int]

foo1: List[MyTuple] = [("a", 1)]
foo2 = foo1 + [("b", 2)]
bar1: Dict[int, MyTuple] = {1: ("a", 1)}
bar2 = bar1 | {2: ("b", 2)}
```

**Comment by helafumpek** [comment]
I checked the documentation link. Literally a paragraph above there is a counter-argument for this approach.
> When Pyright is performing type inference, it generally does not infer literal types. Consider the following example:
```python
# If Pyright inferred the type of var1 to be List[Literal[4]],
# any attempt to append a value other than 4 to this list would
# generate an error. Pyright therefore infers the broader
# type List[int].
var1 = [4]
```
So it has been acknowledged that narrow type inference for collection elements leads to problems. Shouldn't this principle take priority in this case?
```python
x = [("a", 1)]
x.append(("b", 2))
```
This is a very simple piece of code, and Pylance can't handle it right now.

**Comment by erictraut** [comment]
Lists and tuples are very different. The former are mutable, the latter are immutable. 

The inference rules have been very carefully thought out and tuned over time. There are tradeoffs for every decision related to inference. It has taken us a while to tune these rules so as to achieve the best set of tradeoffs, and it's unlikely that we will change them at this point.

You happen to be pointing out a specific example where these tradeoffs work against you, but please understand that if we were to make the change you're suggesting, we would have many more frustrated users pointing out other simple cases where it's not working as they would like.

**Comment by helafumpek** [comment]
I have no intention of trying to impose my view :-)
Literal is a very specific type, because it describes not only the type of a variable, but also its expected value. I can't be sure of course, but I'm fairly certain that when a server infer Literal for some variable, in the vast majority of cases it will have a way narrower range of possible values than the code author's intention. 
```python
class Foo:
    def __init__(self) -> None:
        self.bar = 1    # here it says (variable) bar: Literal[1]

foo = Foo()
foo.bar = 2    # and here it says (variable) bar: Literal[2]
```
My intuition would be to use the Literal type only where the author himself has explicitly defined it in the code. Or when a type is being inferred for a constant. Implicitly assuming that a variable is of type Literal for me seems to result most of the time in an incorrect type inference.

**Comment by helafumpek** [comment]
> So this is different than the question about how the type of a tuple expression should be inferred.
The basis is the same faulty assumption that Pylance should guess the VALUE of a variable. Because that's what the special type Literal is - a constraint on the set of possible values of a variable. Whether it is a single value or a tuple of values. I don't think anyone expects it to do that guessing. But it does. And it does it incorrectly most of the time. I got few more cases
I understand that this assumption was built into the server and it would now be a huge pain in the ass to change it. So I won't pursue the issue any further.
But the whole point of adding annotations in Python is to narrow down the type of the variable. Meanwhile, Pylance forces the programmer to do the opposite, to widen the type of a variable that the server has narrowed based not on the code it analyses, but on the arbitrary design choice.
```python
foo = [("a", 1), ("b", 2), ("c", 3)]
# (variable) foo: list[tuple[Literal['a'], Literal[1]] | tuple[Literal['b'], Literal[2]] | tuple[Literal['c'], Literal[3]]]
```
Sorry, but I don't see how this is considered more correct type inference, than `foo: list[tuple[str, int]]`.

**Comment by helafumpek** [comment]
This is how mypy infers static type of the same expression:
```python
x = [("a", 1), ("b", 2), ("c", 3)]
reveal_type(x)    # Revealed type is 'builtins.list[Tuple[builtins.str, builtins.int]]'
```
