### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by maitrey684** [microsoft/pylance-release#1028]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2021.3.0`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/4c/f2qsqzpd0034t37c2zs0j0k80000gp/T/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by savannahostrowski** [comment]
@maitrey684 Can you please attach the file/paste the logs referenced in this issue? We can't diagnose the issue without this info.

**Comment by tekumara** [comment]
Since the latest vscode upgrade this has been happening for me and I've noticed analysis by the language server is slow. 

See https://github.com/microsoft/vscode-python/issues/11924#issuecomment-794932090

**Comment by tekumara** [comment]
I'm still have this issue after uninstalling pylance, so I suspect it is vscode-python.

**Comment by jakebailey** [comment]
If you have a large number of interpreters, you may be seeing an issue there (similar to #1035), but this issue at least is of the type that includes a profile (if the reporter uploads it). If someone can provide it, then we have something to look at, otherwise we are only speculating. Our extension doesn't do much other than reading some configs and maybe donwloading an insiders update.

**Comment by jakebailey** [comment]
It's been over a month since we asked the original issue filer for that profile file; we really do need that to be able to figure out what the issue is here. If this happens again and we can get the file, then we can reopen this to take a look, but otherwise we can't really do anything without being able to reproduce it.
