### ISSUE TITLE
Fully qualified import statements cannot be resolved

### ISSUE THREAD

**Issue by BrunoBlanes** [microsoft/pylance-release#1067]
## Environment data
-   Pylance Type Checking Mode: `basic`
-   Language Server version: `2021.3.3-pre.1`
-   OS and version: `Windows 10 Pro Insider Preview Build 21322`
-   Python version (& distribution if applicable, e.g. Anaconda): `3.8.7 64-bit`

## Expected behaviour
I expected to be able to type in the following import statements in `patch_notes.py`:
```py
from patchnotesparser.templates.common import *
from patchnotesparser.dragon import Dragon
```

## Actual behaviour
I get the following error message and the imports don't get resolved:
```
Import "patchnotesparser.templates.common" could not be resolved Pylance(reportMissingImports)
```

## Additional information
If I do relative imports as follows, it works without any issues:
```py
from .templates.common import *
from .dragon import Dragon
```
### Folder structure
![image](https://user-images.githubusercontent.com/28227097/111638666-4fb75500-87d9-11eb-8944-06369e2c35c5.png)

**Comment by jakebailey** [comment]
You opened up the `patchnotesparser` folder itself; its parent directory is what needs to be opened.

Pylance treats the workspace as an import root, so it believes that you need to import `dragon`, or `templates.common`. If you open its parent directory, then we will see `patchnotesparser` and recognize that module.

**Comment by BrunoBlanes** [comment]
I'll give you some context here, this project is a Redbot cog, and even though your suggestion works in Pylance (I had tried that before) it does not load in Discord and I get the following error:
```py
Exception during loading of package
Traceback (most recent call last):
  File "c:\users\bruno\redenv\lib\site-packages\redbot\core\core_commands.py", line 169, in _load
    await bot.load_extension(spec)
  File "c:\users\bruno\redenv\lib\site-packages\redbot\core\bot.py", line 1296, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\bruno\source\repos\BrunoBlanes\Esports-wiki-cogs\patchnotesparser\__init__.py", line 1, in <module>
    from patchnotesparser_main import PatchNotesParser
ModuleNotFoundError: No module named 'patchnotesparser_main'
```
And here are the contents of `__init__.py`:
```py
from patchnotesparser_main import PatchNotesParser
from redbot.core.bot import Red


def setup(bot: Red) -> None:
    bot.add_cog(PatchNotesParser(bot))
```

So the above doesn't work, but both of the following do:
```py
from patchnotesparser.patchnotesparser_main import PatchNotesParser
```
```py
from .patchnotesparser_main import PatchNotesParser
```

**Comment by jakebailey** [comment]
That's the `__init__.py` from your example above? It's fine for an absolute import to be there, but when the code is run, it still needs to be in an environment where the parent directory of `patchnotesparser` is a search path (in `sys.path` at runtime). Python is very sensitive to how you run the code, and one behavior that you may be hitting is that when you run a file as a script, its directory is added as a search path, but otherwise this doesn't happen. If you (or the redbot system) is doing this, then the import would appear to work even though we can't know this will happen without extra indication.

Try sticking:

```python
import sys
print(sys.path)
```

To the top of that `__init__.py` and see what it says. I'm guessing you'll see "C:\Users\bruno\source\repos\BrunoBlanes\Esports-wiki-cogs" in it (which is the directory I'm suggesting you open as your workspace instead).

It still sounds to me like this is how it should work; the only way that absolute import would work is if its parent directory is a search path at runtime, and for the editor to understand that this needs to happen, the workspace root needs to be that parent folder (or some extraPaths trickery, but I don't think marking the parent directory of the workspace will work correctly).

**Comment by BrunoBlanes** [comment]
This is what it printed:
`['C:\\Users\\bruno\\redenv\\Scripts\\redbot.exe', 'C:\\Python38\\python38.zip', 'C:\\Python38\\DLLs', 'C:\\Python38\\lib', 'C:\\Python38', 'c:\\users\\bruno\\redenv', 'c:\\users\\bruno\\redenv\\lib\\site-packages', 'C:\\Users\\bruno\\AppData\\Local\\Red-DiscordBot\\Red-DiscordBot\\data\\Ezreal\\cogs\\Downloader\\lib']`

**Comment by BrunoBlanes** [comment]
By the way, that last path is where my bot installs its cogs.

**Comment by jakebailey** [comment]
I see, so the bot copies the folders into a `lib` directory, and that's the search path. At runtime, lib is the parent directory of the modules, and imports are rooted absolutely at that path, which is why it works at runtime. When editing, you're opening up the `patchnotesparser` folder and that's not the parent directory, so imports are behaving as though you had opened `cogs/Downloader/patchnotesparser`.

In your case `Esports-wiki-cogs` is effectively the "lib" directory, so I still think you should consider opening VS Code there instead of this specific subproject.

**Comment by BrunoBlanes** [comment]
Ahhh, so it is more of a "where I work from" kind of issue. That makes sense given the folder structure. It works when working from `Esport-wiki-cogs`. Thanks.

**Comment by jakebailey** [comment]
Precisely!
