### ISSUE TITLE
Find in Files's shortcut is broken

### ISSUE THREAD

**Issue by slorg1** [microsoft/pylance-release#1099]
## Environment data
Pylance: v2021.3.3
Python: 3.7
Eclipse Keymap: v0.12.0
Ubuntu 20.20

## Expected behaviour

`ctrl+H` should trigger the `Find in Files` functionality with anything highlighted prefilled in the search bar

## Actual behaviour

`ctrl+H` now opens the `Find in Files` without prefilling anything and only selects the "panel" (does not focus on the search bar).

I believe this stopped working a couple of weeks ago. It seems like a recent release broke it.

I tested with the VSCode shortcuts:
1. it seems now that in `Edit` the `Find in Files` is set to `ctrl+shift+F` (that is what I see in the menu 
![image](https://user-images.githubusercontent.com/5043518/112754224-12a54c80-8fa9-11eb-95eb-58d4819cc100.png)
)
2. if I use this set of keys for the shortcut after selecting some text: it tries to trigger formatting and I get `Black does not support the "Format Selection" command`
3. if I select some text and use the menu (`Edit`->`Find in Files`) then it works correctly

I also filed this issue with Eclipse Keybinding as I do not know where the issue comes from:: https://github.com/alphabotsec/vscode-eclipse-keybindings/issues/38

**Comment by jakebailey** [comment]
Pylance doesn't add any key combos; it just implements features in VS Code and thus uses whatever settings you have configured. Find-in-files is implemented by VS Code directly, not Pylance.

Are you certain that Pylance is the cause here? If you uninstall it, does this option work again? Are you certain VS Code or another extension didn't also update and could cause this issue?
