### ISSUE TITLE
Support for blob in `python.analysis.extraPaths` especially for pdm

### ISSUE THREAD

**Issue by ulwlu** [microsoft/pylance-release#1100]
- Support for blob in python analysis.

Hi, thank you very much for this great OSS.
I'm using [pdm](https://github.com/pdm-project/pdm), and this library puts the library in `{$project_root}/___pypackages__/3.9/lib` if you are using 3.9. So, I need to write below to resolve imports.
```json
  "python.autoComplete.extraPaths": ["__pypackages__/3.9/lib"],
  "python.analysis.extraPaths": ["__pypackages__/3.9/lib"],
```

However, I thought it would be more convenient if I can write like this.
```json
  "python.autoComplete.extraPaths": ["__pypackages__/*/lib"],
  "python.analysis.extraPaths": ["__pypackages__/*/lib"],
```

I believe it can achieve by fixing below, but it may be a big change. 
So I would like to know if this proposal is acceptable.

https://github.com/microsoft/pyright/blob/master/packages/pyright-internal/src/analyzer/importResolver.ts#L1436-L1471

**Comment by erictraut** [comment]
There is an open issue already for this feature request: https://github.com/microsoft/pylance-release/issues/973.

We haven't made a decision yet whether to support this feature. It's significantly more complex than it might seem at first glance, since we'd need to handle file watchers and updates when there are folder changes. If we do this, we'd also want to support full globs syntax including "**" and "?" for consistency with other places where we support globs in the code base.

**Comment by ulwlu** [comment]
Thank you for your reply, and sorry for duplicate.
I understand the current situation, and will watch for that issue.

closing because of duplicate.

**Comment by erictraut** [comment]
No worries about the duplicate. Thanks for trying to implement a solution.

You can watch for updates in the other issue.
