### ISSUE TITLE
Unhelpful PyLance tooltip while entering parameters to a function

### ISSUE THREAD

**Issue by jflam** [microsoft/pylance-release#1106]
## Environment data

-   Language Server version: 2021.3.3
-   OS and version: Win 10 Insiders 21349.1000
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.7 64 bit

## Expected behaviour

There are two things that I would like to see:

1. A helpful tooltip
2. A consistent way to dismiss the tooltip; my go-to way of doing this is ESC, but I use the vim extension and that kicks me out of insert mode each time. I have since learned from Savannah that SHIFT+ESC will also do this, but it seems to me like ESC is being passed through to the vim extension as well. I have no idea what the right behavior should be, which extension should handle ESC first, etc. 

## Actual behaviour

When I'm typing parameters into a function and I hit ENTER to proceed to enter the next parameter, PyLance places an unhelpful tooltip in an inconvenient place that obscures what I just typed. I often find that I would like to have context to what parameters I had typed before and this behavior causes me to dismiss PyLance right away every time:

![image](https://user-images.githubusercontent.com/8877/113061088-66a96000-9166-11eb-8f67-bffbdce565f9.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
We're unable to control where this tooltip appears; VS Code always places it above the cursor. You're hitting this because of the multi-line-ness of the call you're constructing. (Most times people write calls, they haven't typed a newline in the parens so it's above the call.)

The tooltip contents are due to the type annotation in the setuptools setup function, which can accept a big range of options; those could potentially be expanded to each of the different kwargs if they're stable enough to stick into typeshed. That type also affects completions for those kwargs; if they were present you'd see completions like `version=` and such as you're typing.

> A consistent way to dismiss the tooltip; my go-to way of doing this is ESC, but I use the vim extension and that kicks me out of insert mode each time. I have since learned from Savannah that SHIFT+ESC will also do this, but it seems to me like ESC is being passed through to the vim extension as well. I have no idea what the right behavior should be, which extension should handle ESC first, etc.

This is something that I think would need to be settled with VS Code and the vim extension; ESC is intended to be the thing that closes this, and if vim mode is overriding it then it sounds like they need to have some design for how they intend for signature helps to work.

**Comment by judej** [comment]
From the above response, the thing we can do is to improve the stub for setuptools. 

@jflam, for the ESC problem, a workaround would be to remap the ESC key in vim.

**Comment by jflam** [comment]
@jakebailey I would prefer that if I had dismissed previously using ESC that it would remember it for the duration of the time that I'm editing within that scope (or at least provide an option for that). The really annoying thing is when it re-appears each time I hit ENTER forcing me to dismiss it again.

@judej that sounds like what Apple was trying to say when the ESC key was on the touchbar on Macs :) I don't think it's realistic for people to remap ESC which is burned into so much muscle memory for vim acolytes for exiting insert mode. To be clear this is probably the most used key for vim users - they hit it **thousands of times a day**. 

In my case, I *never* use ESC in vim (I use CTRL+[ with CAPS LOCK mapped to CTRL for better ergo). But I don't expect everyone to be like me :)

**Comment by jakebailey** [comment]
> I would prefer that if I had dismissed previously using ESC that it would remember it for the duration of the time that I'm editing within that scope (or at least provide an option for that). The really annoying thing is when it re-appears each time I hit ENTER forcing me to dismiss it again.

VS Code and the LSP aren't able to implement that; we tell VS Code to show the signature help on 1) paren open and on 2) commas, because that's when 1) the signature info is shown for the first time (a new function call), and 2) on a comma it's a new parameter, which needs to be highlighted in the tooltip contextually. To get what you're looking for, the LSP and VS Code would need to be able to distinguish the two cases, as it seems like you don't want it to pop up again on a new parameter. However, I feel like you're only looking for this behavior because you don't want the tooltip at all, period (as it doesn't contain the info you want, and VS Code places it where you don't want it). I'm wondering if the stub were complete if you would notice this problem; we'd offer completions for parameters and not suggest ones that were already given, and the tooltip itself would list the potential choices.

Also, FWIW, VS Code lets you rebind the keys to close tooltips. You don't have to use ESC for that, but can use any other key. In the keyboard shortcut config:

![image](https://user-images.githubusercontent.com/5341706/113326362-688e3300-92ce-11eb-8799-08298db4d0a2.png)

Or, if you don't want signature help at all, that's toggleable with `"editor.parameterHints.enabled": false`.

**Comment by 392781** [comment]
Approaching the 1 year mark for this issue.  There still is no way of "delaying" let alone disabling Pylance docstring tooltips... 

It would be nice to _at least_ be able to place the tooltips _away_ from the code you're typing (lower or upper corners for instance).

**Comment by erictraut** [comment]
As mentioned above, pylance doesn't have any control over where the tooltip appears or provide a way to delay it. This is all dictated by the language server protocol (LSP) and VS Code.
