### ISSUE TITLE
Hint TypedDict key and value type when call using dict instead of in function

### ISSUE THREAD

**Issue by PASUNX** [microsoft/pylance-release#1122]
```python
from typing import TypedDict, Optional

User = TypedDict("User", {
    "name": str,
    "age": Optional[int]
}, total = False)

def register(user: User) -> None: ...

register(User()) # (*, name: str = ..., age: int | None = ...) -> None
register({}) # not hinting
```

**Comment by heejaechang** [comment]
this is what I am seeing

![image](https://user-images.githubusercontent.com/1333179/113607036-9be9fe00-95fd-11eb-87b1-013dec16e154.png)

**Comment by erictraut** [comment]
I think PASUNX is pointing out that signature help is provided when adding arguments for the `User()` constructor, but no comparable signature help is provided when typing a dictionary literal expression that conforms to a `User` type (i.e. when the insertion pointer is within the `{}` curly braces). This is a valid observation, but I don't see anything we can do about this because "signature help" applies only to call expressions, not to other expressions like dictionary literals. We could conceivably provide completion suggestions in this context, at least for the dictionary keys.

**Comment by jakebailey** [comment]
Yeah, which would be #654.

@PASUNX Can you be clearer about the behavior you're looking for? Is #654 what you're interested in; TypeDict literal completion?

**Comment by jakebailey** [comment]
I'm going to close this in favor of #654, in the absence of a response.
