### ISSUE TITLE
Unreachable code when checking Python version

### ISSUE THREAD

**Issue by circumspect** [microsoft/pylance-release#1124]
Hi,
I would like to check when a user is running an unsupported version of Python and if so, exit. The code I am using for this is as follows:
```python
if sys.version_info < (3, 6):
    sys.exit("Python versions below 3.6 are unsupported. Please install a newer version")
```
However, Pylance marks the line as unreachable, because my installed version is 3.9. Is there any way I can suppress the check for this line? I was unable to find anything in the diagnostic severity rules regarding unreachable code.

**Comment by erictraut** [comment]
There is no diagnostic severity control for this functionality because this isn't a diagnostic (an error, warning, etc.). Pylance is telling the client to display that code as "grayed out" to indicate that the code is unreachable given the current configuration. 

If you would like, you can override the version of Python used for the analysis. For example, you could ask Pylance to assume version "3.5" rather than using the version of the selected interpreter. This is done through the use of a pyrightconfig.json configuration file, as documented [here](https://github.com/microsoft/pyright/blob/master/docs/configuration.md). 

```
{
    "pythonVersion": "3.5"
}
```

**Comment by circumspect** [comment]
Okay, I see. Is this the same behavior as the `"self" is not accessed` indicator? That one also fails to be suppressed by the use of `# type: ignore` comments

**Comment by erictraut** [comment]
Yes, both the "unreachable code" and "unaccessed symbol" conditions make use of the "grayed out" visual effect in the client. However, the "unreachable code" is different in that the type analyzer won't analyze code that is unreachable. That code might, for example, make use of language features that are not supported in an older version of Python, hence the version check. [PEP 484](https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking), which defines type checker behaviors, dictates that type checkers should honor version checks in this manner.

**Comment by circumspect** [comment]
Okay, thanks for the clarification!
