### ISSUE TITLE
Parameter hint is not correct when using a dynamically created function.

### ISSUE THREAD

**Issue by thy09** [microsoft/pylance-release#117]
## Environment data

-   Language Server version: Pylance language server 2020.7.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3

## Expected behaviour

For a dynamically created function in VSCode jupyter notebook,
the correct type hints with provided signature is expected.
For example:
```
def create_function(f, sig, name):
    f = types.FunctionType(
        code=f.__code__,
        globals=f.__globals__,
        name=name,
        argdefs=f.__defaults__,
        closure=f.__closure__,
    )
    f.__signature__ = sig
    return f
signature = Signature([Parameter(name='str_param', kind=Parameter.KEYWORD_ONLY, annotation=str, default='123')])
g = create_function(lambda **kwargs: kwargs, sig=signature, name='g')
```
I use the above code to create the function g in one cell,
in the next cell, when I type `g(`, 
the expected hint is `(*, str_param: str = '123')`. 

## Actual behaviour

Actually the hint is `(*args, **kwargs) -> Any`
It seems that it is a general hint for all `FunctionType` variables.

**Comment by judej** [comment]
@thy09, this is an unusual pattern. Is this a common usage? I'm curious what the use case is. Since the language server does not query Jupyter for type info for dynamically generated functions, signature info will not be available.

**Comment by thy09** [comment]
Thanks for your reply!

Here is our use case:
We want to create a python function to set some configures with HTTP request, for example:
```
def configure(**kwargs):
    requests.post(CONFIGURE_URL, json=kwargs)
```
The configure options are fetched from another URL, so we want to make a new function with the parameters to make it intelligent. The full code might be:
```
def make_configure_function(configure_option_url, configure_name):
    params= requests.get(configure_option_url).json()
    signature = Signature([Parameter(**param) for param in params])
    return create_function(configure, signature, configure_name)

configure_a = make_configure_function(configure_option_url_a, 'configure_a')
help(configure_a)
```
In this case, if the parameters are `param1:int=1`, `param2: str='a'`, by calling `help`, we could get the following:
```
Help on function configure_a in module __main__:

configure_a(*, param1: int = 1, param2: str = 'a')
```

When I type `configure_a(par`, the following hint could be shown.
![image](https://user-images.githubusercontent.com/3871260/87621237-ea472c00-c752-11ea-8391-cdcdf6e235e6.png)
But when I type `configure_a(`, only the following hint is shown.
![image](https://user-images.githubusercontent.com/3871260/87621339-2bd7d700-c753-11ea-81d5-df246ad5a0d2.png)
I thought the implementation of above two kinds of hints are the same.

Do you mean that the first hint is not provided by language server? 
Is it possible to support this in the future?
Thanks a lot!

**Comment by jakebailey** [comment]
Pylance is a static analyzer and can only determine things from the code itself (and uses the type system as provided by `typing` and PEP 484). The function you're constructing has a signature that depends on the return value of an HTTP request, which is extremely dynamic. We wouldn't know what any given request is going to return, and if we could know that, I don't believe we could know how to construct function types like that via `types` and `inspect`.

The only reason this might work in a place like Jupyter is that there you're working with a real interpreter on live data; `help()` is going to give you the real signature because Python knows what it is by executing it.

Is there a practical reason to design an API like this? It seems a bit spooky to construct functions based on arbitrary request results.

I'm trying to figure out what part of this makes things "intelligent"; if the signatures are limited to some set, why not directly type out the annotated functions?

**Comment by thy09** [comment]
Thanks for your reply!
I realize that our requirement can only be satisfied by a dynamic analyzer, so it is hard for Pylance to do this.

Our scenario is that we are do something like `function as a service`.
There are several procedures:
1. Someone called A created a function `configure_a(param1:int=1, param2: str='a')` and registered this function to the cloud, the source code and the interfaces are stored in the cloud;
2. The consumer called B uses this function with the code like following:
```
# Use HTTP to get the interface and create the function with the interface
configure_a = get_function('configure_a')
help(configure_a)    # Show the interface of the function
# In this configure_a, we actually submit the parameters to the cloud, compute, then return the result.
result = configure_a(param1=xx, param2=xx)
```

Since the source code of the real function is stored in the cloud and will never be reached by the consumer, (it could even not be python code.)
The signature cannot be known before we get the interface of the function from the HTTP request.

**Comment by jakebailey** [comment]
This seems massively dynamic. I don't think this is going to be analyzable. I'm reading this as:

1. Call some API to get the signature of a function "in the cloud".
1. Produce a Python function that implements a call to that function via the API.
1. Call said function.

Feasibly, if you are expecting this sort of thing to be used, then there exists code which calls these functions, no? At that point, isn't the signature expected to be known because they know how to call it? Or is the expectation that nobody knows the signatures of functions until runtime? (At that point, all guarantees are off, and I lose sight of how this becomes usable...)

**Comment by thy09** [comment]
Thanks for your reply!

You are right, the signature is expected to be known.
According to the current design,
the signature could be known as the generated documentation provided by the function author,
the consumer could check the doc and type the required parameters in his code.

A possible solution is to generate the python function code with the signature before the consumer use this function.
But it is not that easy to do this since there might be a lot of registered functions.

Anyway, the key point is that Pylance is a static analyzer, the hint for dynamically generated function is impossible.
I'll close this issue.

Thanks again for your kind reply!

**Comment by luigiw** [comment]
Hello, our team has a similar ask. The difference is that we don’t need to make a HTTP call to get the function signature, we can get that from a local configuration file. Does this make the challenge easier? Can you share possible work arounds @thy09

**Comment by erictraut** [comment]
It would need to be in Python syntax, so if the "local configuration file" is a ".py" or ".pyi" file that uses normal Python syntax, then it would work. If it's in some other format, then Pylance will not understand it.
