### ISSUE TITLE
Pylance incorrectly identifying code as unreachable in Pytest test

### ISSUE THREAD

**Issue by pzelnip** [microsoft/pylance-release#1174]
## Environment data

-   Language Server version: v2021.4.1
-   OS and version: OSX Catalina (10.15.7)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.1 (from Pyenv)

## Expected behaviour

In this function I'd expect the final assert to be reachable (and it is, when I run the code it does hit that line), but Pylance is marking it as unreachable:

```
from unittest.mock import patch
import pytest

@patch('mylibrary.some_func')
def test_mock(mock_func):
    def foo():
        raise ValueError('lksfj')

    with pytest.raises(ValueError):
        foo()

    assert mock_func.called
```

## Actual behaviour

Pylance is marking the final assert (on `mock_func.called`) as unreachable:

![image](https://user-images.githubusercontent.com/414933/115442687-236f6980-a1c7-11eb-85cd-851c5a782097.png)

## Logs

Nothing related showing up in logs

## Code Snippet / Additional information

Again, this snippet reproduces the issue:

```python
from unittest.mock import patch
import pytest

@patch('mylibrary.some_func')
def test_mock(mock_func):
    def foo():
        raise ValueError('lksfj')

    with pytest.raises(ValueError):
        foo()

    assert mock_func.called
```

**Comment by jakebailey** [comment]
The `__exit__` method is declared as returning `bool`, so we should be able to understand that this context manager potentially catches exceptions:

![image](https://user-images.githubusercontent.com/5341706/115443885-b1981f80-a1c8-11eb-9cd6-b70df6438be5.png)

But, this may be that edge case where because `raises` is overloaded, our heuristic for this isn't powerful enough to go figure the behavior out (since it needs to know this info during code flow, which happens before overload matching). I can't find the previous issue where @erictraut described to compare cases (maybe it's exactly the same).

**Comment by erictraut** [comment]
I think this is the same case that was reported previously. 

If you recall, the type checker wasn't able to detect any cases where a context manager handled exceptions. This is very complex to handle because of a chicken-and-egg problem. The type checker needs to compute the code flow graph before it can evaluate the types of symbols within the code flow. The context manager expression (in this case `pytest.raises(ValueError)`) may affect the code flow graph depending on whether it catches exceptions, but we can't generally the type of that expression prior to calculating the code flow graph. I worked around this cyclical dependency by implementing some simple (but limited) type evaluation logic that is able to handle the common case where the context manager expression is a constructor call (i.e. the form `MyContextManager(<args>)`). This handles the most common cases (95%+), but there are still rare cases that it cannot handle. This is an example of one of those cases.

The good news is that the result is relatively innocuous — no false positive error, etc.

**Comment by erictraut** [comment]
One simple workaround in this particular case is to add a return type annotation to `foo`:
```python
    def foo() -> None:
        raise ValueError("lksfj")
```

**Comment by jakebailey** [comment]
It's been a month since we opened this and suggested a workaround (annotating the function being tested); I'm going to close this for now. We can reopen if the workaround isn't enough or there's a change.

(I'm a bit unsure how we could solve this chicken-and-egg problem overall...)

**Comment by KPilnacek** [comment]
Hello team,

I recently stumbled upon this issue even if the function has a return type annotation. Concretely
```python
from typing import NoReturn

    def foo() -> NoReturn:
        raise ValueError("lksfj")
```
As per [PEP484](https://peps.python.org/pep-0484/#the-noreturn-type), this annotation actually seems to be more appropriate for this kind of functions.

**Comment by KPilnacek** [comment]
Fixed by upgrading `pytest`. source: https://github.com/microsoft/pylance-release/issues/915
