### ISSUE TITLE
__reversed__() is not recognized in call to reversed()

### ISSUE THREAD

**Issue by nmay231** [microsoft/pylance-release#1177]
## Environment data

-   Language Server version: 2021.4.1
-   OS and version: Ubuntu 20.04
-   Python version: 3.8.6 installed via pyenv

## Description

Just as `len(object)` calls `object.__len__()`, `reversed(object)` calls `object.__reversed__()`.

Pylance correctly recognizes when a custom class has `__len__` that calling `len()` is valid. This is not the case with `__reversed__`.

## Expected behaviour

```python
class Class:
  def __len__(self):
    return 0
  def __reversed__(self):
    return []

len(Class())
reversed(Class())  # Expect no issues here
```

## Actual behaviour

```python
class Class:
  def __len__(self):
    return 0
  def __reversed__(self):
    return []

len(Class())  # This is still fine
reversed(Class())  # Pylance Error: No overloads for "reversed" match the provided arguments Argument types: (Class)
```

**Comment by erictraut** [comment]
I think pylance is doing the right thing in this case.

The `reversed` function is declared in `builtins.pyi`. It is an overloaded function defined as follows:
```python
@overload
def reversed(__sequence: Sequence[_T]) -> Iterator[_T]: ...
@overload
def reversed(__sequence: Reversible[_T]) -> Iterator[_T]: ...
```

`Sequence` is not a protocol class, and `Class` does not subclass from it, so the first overload does not apply in this situation. So the question is whether `Class` implements the `Reversible` protocol, which is defined as follows:

```python
class Reversible(Iterable[_T_co], Protocol[_T_co]):
    def __reversed__(self) -> Iterator[_T_co]: ...
```

The `__reversed__` method in `Class` returns a `list` instance, but `list` is not an `Iterator` because it provides no `__next__` method. For that reason, `Class` does not meet the requirements of the `Reversible` protocol.

The Python documentation indicates that `__reversed__` must return an iterator, so I think the `builtins.pyi` stub is correct, and I think pylance is correct in indicating that this is a type consistency error.

I confirmed that mypy (another Python type checker) also emits an error in this case.

**Comment by nmay231** [comment]
@erictraut Gotcha. I didn't realize type-checkers expect the class to inherit `Reversible` to call `reversed()` on it, since the code does run without it.

In short, the correct usage for my example would be:

```diff
+ from typing import Reversible

- class Class:
+ class Class(Reversible):
    def __reversed__(self):
      # The result must be an iterator
-     return []
+     return iter([])
```

Thanks for the clarification :+1:

**Comment by erictraut** [comment]
No, you don't need to inherit from Reversible explicitly. Protocol classes don't have that requirement. However, your class needs to conform to the `Reversible` protocol's interface. `Class` didn't conform to the `Reversible` protocol in two important ways:
1. The `__reversed__` method did not return an `Iterator`. (I see that you've corrected this in your updated code.)
2. `Reversible` also inherits from the `Iterable` protocol, which means that your class must also implement that protocol. That means it must also provide a `__next__` and `__iter__` method, which it does not.

**Comment by nmay231** [comment]
@erictraut Okay, got it now :smile:
