### ISSUE TITLE
Inconsistent behavior when using value of partially unknown type as generic argument

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1188]
## Environment data

-   Language Server version: 2021.4.2
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample Code

```python
from __future__ import annotations

from typing import TypeVar

T = TypeVar("T")

def f(x: list[T]) -> T:
    ...

a = []  # Type: `list[Unknown]`.
b = f(a)  # Type: `Unknown`.
b.xxx  # OK using basic checks.

c = f([])  # Type: `T@f`.
c.xxx  # Warning: Cannot access member `xxx` for type `object`.
```

## Expected behavior

Type of `c` is `Unknown`, just like type of `b`.

## Actual behavior

See comments in the sample code.

**Comment by erictraut** [comment]
I can understand why this looks inconsistent, but it is the correct (or at least intended) behavior.

In the first example, you're creating an empty list in a situation where the type checker has no context about how it will be used. It therefore infers that the type of `a` is `list[Unknown]`. This allows it to be used flexibly in subsequent statements. For example, you could push values onto the list even if they have various (heterogenous) types.

In the second example, you're creating an empty list in a situation where the type checker has additional context. It knows that the newly-created list is being assigned to a parameter of type `list[T]` where `T` is an unbound type variable. The type of this newly-created list is therefore inferred to be `list[T]`, and the type of `c` is therefore `T`. When `c` is used in the next statement, all we know about `c` is that it must be an `object` (since `T` is an unbound type variable), so the expression `c.xxx` is evaluated as though `c` is an `object` instance.

You can eliminate the type error by specifying a type annotation for `c`, like this:
```python
c: MyType = f([])
```

Note that mypy (another Python type checker) emits type errors for both cases, forcing you to provide type annotations for both `a` and `c`. Pylance can be a bit more permissive in cases like this because of its use of "Unknown".

**Comment by Azureblade3808** [comment]
I'm still not understanding the behavior here.

Is it true that some types displayed the same as `list[Unknown]` are internally different types?

Here is a modified example:
```python
from __future__ import annotations

from typing import TypeVar

T = TypeVar("T")

def create_list_of_unknown_elements() -> list:
    return []

def f(x: list[T]) -> T:
    return x[0]

a: list = create_list_of_unknown_elements()  # Type: `list[Unknown]`.
b = f(a)  # Type: `Unknown`.
b.xxx  # Type: `Unknown`.

c = create_list_of_unknown_elements()   # Type: `list[Unknown]`.
d = f(c)  # Type: `T@f`.
d.xxx  # Warning: Cannot access member `xxx` for type `object`.
```

It has passed mypy check (https://mypy-play.net/?mypy=latest&python=3.8&gist=ea89c6a7f0a08c7c3ccefb3e5a2edd8e), but still got warnings from pylance.

**Comment by Azureblade3808** [comment]
Here is one more example that passed mypy checks but failed pylance checks:
```python
from __future__ import annotations

from typing import Any, Generic, TypeVar

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)
T_contra = TypeVar("T_contra", contravariant=True)

###

class MyClass0(Generic[T]):
    ...
    
def my_func_0(x: MyClass0[T]) -> T:
    ...
    
a0: MyClass0[Any] = MyClass0()  # Type: `MyClass0[Any]`
b0 = my_func_0(a0)  # Type: `Any`
c0 = b0.xxx  # Type: `Any`

###

class MyClass1(Generic[T_co]):
    ...
    
def my_func_1(x: MyClass1[T]) -> T:
    ...
    
a1: MyClass1[Any] = MyClass1()  # Type: `MyClass1[Any]`
b1 = my_func_1(a1)  # Type: `Any`
c1 = b1.xxx  # Type: `Any`

###

class MyClass2(Generic[T_contra]):
    ...
    
def my_func_2(x: MyClass2[T]) -> T:
    ...
    
a2: MyClass2[Any] = MyClass2()  # Type: `MyClass2[Any]`
b2 = my_func_2(a2)  # Type: `T@my_func_2`
c2 = b2.xxx  # Warning: Cannot access ...
```
https://mypy-play.net/?mypy=latest&python=3.8&gist=69aa0216b8232966daf851ba7a76604b

**Comment by erictraut** [comment]
This is a bug. There are places where pyright needs to distinguish between two cases: 1) a generic type is specified with an explicit type argument that has an unknown type , and 2) a generic type is specified but omits one or more type arguments, meaning that they are implicitly unknown (e.g. `list` or `Sequence`). It does so internally through the use of a boolean field called `isTypeArgumentExplicit`. This boolean value isn't reflected in the textual form of the type, which is why you were seeing `list[Unknown]` in both cases. There was a bug where `isTypeArgumentExplicit` was being used incorrectly in one code path. This resulted in the inconsistent behavior in the sample above. This will be fixed in the next release. With the fix in place, no type errors are reported with this code.

Note that this is different from the first sample you provided in this bug report. As I previously explained, that behavior is intended, not a bug.

**Comment by Azureblade3808** [comment]
Thank you for explaining. By knowing which part my problem is, I can continue my work now.

Looking forward to the new version.

**Comment by Azureblade3808** [comment]
Thank you for explaining. By knowing which part my problem is, I can continue my work now.

Looking forward to the new version.
