### ISSUE TITLE
Typing error when type is a string

### ISSUE THREAD

**Issue by MalcolmMielle** [microsoft/pylance-release#1199]
Hi !

## Environment data

-   Language Server version: v2021.4.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Expected behaviour

The code I'm working on has a lot of method called has `def func(self, object: 'AnObject') -> Optional[Any]:`. Here there should be no error reported

## Actual behaviour

In those cases Pylance gives an error that 'AnObject' is unknown.

**Comment by erictraut** [comment]
`AnObject` is a type annotation. Because it's in quotes, it's interpreted as a forward-reference type annotation (see PEP 484 for details). The symbol `AnObject` must be defined somewhere in the module (or imported from another module). From the error you're seeing, I'm guessing that the symbol isn't defined anywhere in the file. Is that assumption correct?

**Comment by MalcolmMielle** [comment]
Yes that assumption is entirely correct. In my case, it is used to avoid circular dependencies.
