### ISSUE TITLE
Type guard not taken into account

### ISSUE THREAD

**Issue by MalcolmMielle** [microsoft/pylance-release#1202]
## Environment data

-   Language Server version: v2021.4.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Expected behaviour

Take the following snippet:
```
def fun(element_to_copy: Dict["ElType", Optional["ElType]]) -> ElType:
    if element_to_copy[self] is not None:
        return element_to_copy[self]
    more_code
```
No error should be returned.

## Actual behaviour

On the third line there is an error:

Expression of type "ElType| None" cannot be assigned to return type "ElType"
  Type "ElType| None" cannot be assigned to type "ElType"
    Type "None" cannot be assigned to type "ElType"

The error goes away if I use:

```
def fun(element_to_copy: Dict["ElType", Optional["ElType]]) -> ElType:
    el = element_to_copy[self]
    if el is not None:
        return el
    more_code
```

**Comment by erictraut** [comment]
This is expected behavior. Pyright (the type checker that underlies pylance) supports type narrowing for subscript expressions only if the subscript value is a constant numeric value (e.g. `element_to_copy[0]`). It does not perform narrowing when the subscript is a variable expression. Analyzing such expressions is too difficult because the value of such expression can change in ways that cannot be understood statically. Other Python type checkers (like mypy) also do not narrow types in this case. Nor do type checkers in other languages (like TypeScript).

If you are interested in which expression types are supported by pyright for type guards, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-guards).

The recommended workaround is to assign the value to a local variable whose value, as you've noted above. Type narrowing is safe to apply in this case.

**Comment by MalcolmMielle** [comment]
Thanks a lot for the detailed answer and the references! I'll check it out and change my code to take that into account.
