### ISSUE TITLE
sys.version_info comparison

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1223]
## Environment data

-   Language Server version: 2021.4.4-pre.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.0a7
-   python.analysis.typeCheckingMode: strict

## Expected behaviour
The `print` statement should be marked as unreachable.

## Actual behaviour
![Screen Shot 2021-05-03 at 01 50 38](https://user-images.githubusercontent.com/30130371/116831821-f8671b80-abb1-11eb-9305-4a00f1acf735.png)

## Code Snippet / Additional information

```python
import sys

if sys.version_info <= (3, 10):
    print("Hello World")
```
The output for Python `3.10.0a7` will be
```
```

--
Similar
```py
import sys

if sys.version_info > (3, 10):
    print("Hello World")
```
Should not be marked as unreachable, since the output is `Hello World`

**Comment by erictraut** [comment]
You should use `>=` or `<` for these tests. Using `<` or `>=` will produce unexpected results because of the way these versions are encoded and the way that static type checkers like pyright perform these comparisons. Pyright tracks only the major and minor version of the interpreter when evaluating expressions for the purpose of building the code flow graph.
