### ISSUE TITLE
Return type matching not detecting type correctly with TypeVar where a new object is created inside the annotated function

### ISSUE THREAD

**Issue by smeznaric** [microsoft/pylance-release#1234]
## Environment data

-   Language Server version: 2021.4.3
-   OS and version: CentOS Linux release 7.5.1804
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.3

## Code Snippet / Additional information

```python
from typing import TypeVar
import pandas as pd

DfOrSer = TypeVar("DfOrSer", pd.DataFrame, pd.Series)

def pandas_func(pd_obj: DfOrSer) -> DfOrSer:
    if isinstance(pd_obj, pd.Series):
        return pd.Series([1,2,3])
    else:
        assert isinstance(pd_obj, pd.DataFrame)
        return pd.DataFrame({"a": [1,2,3]})
```

## Expected behaviour

Nothing underlined

## Actual behaviour

Both `return pd.Series` and `return pd.DataFrame` lines are underlined, saying 
```
Expression of type "Series[Unknown]" cannot be assigned to return type "DfOrSer@pandas_func"
  Type "Series[Unknown]" cannot be assigned to type "DfOrSer@pandas_func"
```

**Comment by erictraut** [comment]
The current behavior is intended, although I think one could make the argument that it's incorrect. There's some ambiguity in the standard here.

PEP 484 implies that constrained TypeVars act differently than bound TypeVars in that "Subtypes of types constrained by a type variable should be treated as their respective explicitly listed base types in the context of the type variable." However, it doesn't say whether the implementation of a function that returns a constrained TypeVar for an input parameter and a return value must return the same subtype. For example, if I create a subclass of `pd.Series` and pass an instance of that subclass to `pandas_func`, should the implementation be expected to return an instance of my subclass? Or is it OK for it to return an instance of `pd.Series`?

PEP 484 is especially vague when it comes to generics. For example, if you pass an instance of `pd.Series[str]` as an input argument to `pandas_func`, is it legitimate for the function to return an instance of `pd.Series[int]`? PEP 484 isn't clear on this, but that would seem to be a problem. Mypy punts on this issue and always discards all type arguments. If you pass an argument of type `pd.Series[str]`, it indicates that the return type of the call is `pd.Series[Any]`, which seems wrong.

Changing the behavior of pyright to be more lax in this case is actually quite difficult because of the way it analyzes code in the presence of constrained TypeVars. I won't bore you with the details, but pyright is optimized for use as a language server, whereas mypy is a batch processing tool (not used for interactive editing). This led to certain architectural decisions in pyright that would make it difficult to match the behavior of mypy exactly in particular area. And as I said above, I'm not convinced that mypy's behavior is necessarily desirable.

Let me offer you a couple of alternative approaches here: overloads and casts.

```python
# DfOrSer is defined here as a union rather than a TypeVar
DfOrSer = Union[pd.DataFrame, pd.Series[Any]]

@overload
def pandas_func(pd_obj: pd.Series[Any]) -> pd.Series[int]: ...
@overload
def pandas_func(pd_obj: pd.DataFrame) -> pd.DataFrame: ...

def pandas_func(pd_obj: DfOrSer) -> DfOrSer:
    if isinstance(pd_obj, pd.Series):
        return pd.Series([1, 2, 3])
    else:
        assert isinstance(pd_obj, pd.DataFrame)
        return pd.DataFrame({"a": [1, 2, 3]})
```

```python
DfOrSer = TypeVar("DfOrSer", pd.DataFrame, pd.Series)

def pandas_func(pd_obj: DfOrSer) -> DfOrSer:
    if isinstance(pd_obj, pd.Series):
        return cast(DfOrSer, pd.Series([1, 2, 3]))
    else:
        assert isinstance(pd_obj, pd.DataFrame)
        return cast(DfOrSer, pd.DataFrame({"a": [1, 2, 3]}))
```
