### ISSUE TITLE
Wrong type of exponentiation with integer base and power

### ISSUE THREAD

**Issue by eternalphane** [microsoft/pylance-release#1259]
## Wrong type inference of integer raised to power of any integer other than literal `2`

<h3> Environment data </h3>

-   Language Server version: 2021.5.2-pre.1
-   OS and version: Windows 10
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.5 (pipenv)
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

```python
a = 10**1
b = 10**3
c = 10**int(2)
```
Type of both `a`, `b` and `c` should be inferred as `int`.

<h3> Actual behaviour </h3>

![image](https://user-images.githubusercontent.com/11267872/117678902-67f88e80-b1e2-11eb-84c6-1d9b3214449b.png)
![image](https://user-images.githubusercontent.com/11267872/117679030-81013f80-b1e2-11eb-9571-2841677da62d.png)
![image](https://user-images.githubusercontent.com/11267872/117679137-94140f80-b1e2-11eb-927a-be88926fa497.png)

**Comment by jakebailey** [comment]
The problem is that negative exponents make the result `float`, so in order to avoid having a return type of `__pow__` be `Union[int, float]`, [typeshed types this as `Any`](https://github.com/python/typeshed/issues/4352), which is more permissive. The type system can't really distinguish negative from positive integers.

I special cased the literal 2 to help with this (as that's the most common power), but you've made a bunch of snippets that aren't that special case: https://github.com/python/typeshed/pull/4473

**Comment by eternalphane** [comment]
> The type system can't really distinguish negative from positive integers.

True for the stubs, but since pylance is not simply a collection of stubs, is there any chance for the type checker to at least distinguish negative from positive literals?

**Comment by jakebailey** [comment]
Though, not in a particularly sensible way... https://mypy-play.net/?mypy=latest&python=3.9&gist=fc3a42659210f6c87a96f56ecf965a91

```python
from typing import Literal

def return_10() -> Literal[10]: return 10
def return_neg1() -> Literal[-1]: return -1

reveal_type(10**return_10())
reveal_type(10**return_neg1())
```

```
main.py:6: note: Revealed type is 'Any'
main.py:7: note: Revealed type is 'Any'
```

**Comment by erictraut** [comment]
I don't think we should special case this in the type checker. This is not the only place where the type system cannot describe the semantics of a call exactly, and adding special cases in the type checker is a slippery slope that we should not go down. The current solution (a return type of Any) is a good compromise because it eliminates false positives in this case.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
