### ISSUE TITLE
Message from Pylance that member cannot be accessed (Cryptodome)

### ISSUE THREAD

**Issue by kpg141260** [microsoft/pylance-release#1273]
## Environment data
-   Language Server version: 2021.5.2-pre.1 (pyright df8b6b3c)
-   OS and version: MacOS Big Sur Version 11.2.3
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

Pylance to resolve the calls to certain methods of Cryptodome do NOT report Error:
"Cannot access member "function/method for type "Ecbmode"
Firstly, pylance resolves the selected AES encryption mode wrongly -> it resolves to ecbmode, whereas the selected mode is MODE_GCM.
Secondly, the pyscript in question works perfectly fine when executed, so the error messages are clearly caused by pylance. 
The affected methods are:
 - encrypt_and_digest
 - nonce
 - decrypt_and_verify

## Actual behaviour
pylons produces the following errors:
Cannot access member "encrypt_and_digest" for type "EcbMode"
  Member "encrypt_and_digest" is unknown
Cannot access member "nonce" for type "EcbMode"
  Member "nonce" is unknown```
Cannot access member "decrypt_and_verify" for type "EcbMode"
  Member "decrypt_and_verify" is unknown
## Logs
```

## Code Snippet / Additional information
```python
import hash lib
from    base64 import b64encode, b64decode
from    Cryptodome.Random import get_random_bytes
from    Cryptodome.Cipher import AES

def encrypt (plain_text: str) -> dict:
          _aes_salt =  get_random_bytes(AES.block_size)
          private_key   = hashlib.scrypt (password='some secret password', salt=_aes_salt, n=2**14, r=8, p=1, dklen=32)
          _cipher = AES.new (private_key, AES.MODE_GCM)      
          _cipher_text, tag = _cipher.encrypt_and_digest(plain_text.encode('utf-8'))
          _cipher_dict =  {
              'ct':  b64encode(_cipher_text).decode('utf-8'),
              's':   b64encode(_aes_salt).decode('utf-8'),
              'n':   b64encode(_cipher.nonce).decode('utf-8'),
              't':   b64encode(tag).decode('utf-8')
         return _cipher_dict
```

**Comment by kpg141260** [comment]
Sorry forgot Python version -> it is 3.9.2 and also happens in version 3.9.4

**Comment by bschnurr** [comment]
Without loading up the code, my initial guess is that this is related to how the stub file for AES.pyi is written.

https://github.com/Legrandin/pycryptodome/blob/5dace638b70ac35bb5d9b565f3e75f7869c9d851/lib/Crypto/Cipher/AES.pyi#L31

instead of returning a union of types, try going to definition and rewrite locally using overloads for each mode
```
@overload
def new(key: Buffer,
        mode: EcbMode,
        iv : Buffer = ...,
        IV : Buffer = ...,
        nonce : Buffer = ...,
        segment_size : int = ...,
        mac_len : int = ...,
        assoc_len : int = ...,
        initial_value : Union[int, Buffer] = ...,
        counter : Dict = ...,
        use_aesni : bool = ...) -> EcbMode: ...

@overload
def new(key: Buffer,
        mode: CbcMode,
        iv : Buffer = ...,
        IV : Buffer = ...,
        nonce : Buffer = ...,
        segment_size : int = ...,
        mac_len : int = ...,
        assoc_len : int = ...,
        initial_value : Union[int, Buffer] = ...,
        counter : Dict = ...,
        use_aesni : bool = ...) -> CbcMode: ...
```

if that works log an issue with pycryptodome so that it gets updated. 
Thank you

**Comment by jakebailey** [comment]
This is an issue with the upstream stubs; returning unions like this is bound to cause issues for users that write code that expect it to be a specific type. See the guidance in the typeshed docs, for example: https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions

If want to assert that it has a specific type, you can do something like:

```python
mode = AES.new(...)
assert isinstance(GcmMode, mode)
```

Or if you are certain, you can use a `typing.cast` or a `# type: ignore` comment.

Otherwise, this behavior is expected when you're in a type checking mode; the stubs are written that way and this would need to be changed upstream.

**Comment by kpg141260** [comment]
That works, thank you.
