### ISSUE TITLE
Add Qualifier to Objects in Error Tooltips to Disambiguate Objects with the Same Name

### ISSUE THREAD

**Issue by savannahostrowski** [microsoft/pylance-release#1306]
## Environment data

-   Language Server version: 2021.5.2
-   OS and version: Windows
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Expected behaviour
It'd be nice to have a qualifier (e.g. class name) for objects in type error messages so that when there are incompatible types, it's easy to distinguish that different object are being compared.

## Actual behaviour

![image](https://user-images.githubusercontent.com/8949415/118734834-0b096380-b7f4-11eb-8753-2b2b1f011243.png)

## Logs
N/A 

## Code Snippet / Additional information
N/A

* I'm breaking my own rules and not filling out the template. 🙂  Please don't do this.

**Comment by erictraut** [comment]
I've changed the code to detect the case where the `X is incompatible with Y` diagnostic message is misleading because types X and Y have the same short name. When this occurs, the fully-qualified name will be used instead, like this:

![Screen Shot 2021-05-18 at 5 23 33 PM](https://user-images.githubusercontent.com/7040122/118739294-faf68180-b7fd-11eb-93e5-ab10b3d0158b.png)

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202153-19-may-2021
