### ISSUE TITLE
Disable 'attribute' is not accessed message for ABC classes

### ISSUE THREAD

**Issue by nikitawootten** [microsoft/pylance-release#132]
## Environment data

-   Language Server version: v2020.7.2
-   OS and version: Arch Linux
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3 within a virtual environment (venv)

## Expected behaviour

Pylance should ignore unused parameters inside ABC abstract methods.

## Actual behaviour

Pylance does not ignore these parameters, producing the tooltip `"<parameter>" is not accessed`.

## Logs

No relevant logs

## Code Snippet / Additional information

```python
from abc import ABC, abstractmethod

class SomeAbstractBaseClass(ABC):
    @abstractmethod
    def some_abstract_method(self, some_param):  # Pylance complains that "self" and "some_param" are not accessed
         """Implement me"""
```

**Comment by erictraut** [comment]
When you say "Pylance complains...", are you referring to the fact that it "grays out" those two unreferenced parameters? 

Pylance should never log a diagnostic (an error or warning that appears in the "Problems" panel) related to unused parameters, so if you're seeing such a diagnostic, please let us know.

If you're referring to the "grayed out" symbols, that's by design. It's not "complaining" but rather informing you using a subtle visual clue that these are unreferenced parameters. This is standard behavior for most language servers. If you don't like seeing grayed-out symbols, you can use the theming capabilities in VS Code to override the gray coloring so they appear like other text.

**Comment by nikitawootten** [comment]
Ah, my apologies, the problem was actually caused by another extension I had installed called "error lens" (`usernamehw.errorlens`). This extension incorrectly took the PyLance message and showed it as a problem.

Thank you!
