### ISSUE TITLE
Inconsistency in revealing type of a variable with a union type

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1344]
## Environment data

-   Language Server version: 2021.5.4-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample

```python
from __future__ import annotations

from typing import Any, Union

T = Union[str, float]

def get_any() -> Any:
    ...

x: T = get_any()

x  # Revealed type: "T"

a = 0

x  # Revealed type: "T"

# The condition can be any expression which references a named value,
# except for None, True or False.
if a:
    pass

x  # Revealed type: "str | float"
```

## Expected behavior

It doesn't seem to be quite a bug. I just want to know the cause of this inconsistency.

## Actual behavior

As described in comments.

**Comment by erictraut** [comment]
`T` is a type alias, so it is shorthand for `str | float`. When a union type that has a type alias name is combined with other types to create a new union, the type alias name is dropped. For example, `T | int` results in the type `str | float | int`. 

What's happening in this particular case is due to the way that pyright performs code flow analysis. It builds a "reverse code flow graph" where the nodes of the graph consist of assignment expressions, and the edges of the graph represent possible code paths, but in the reverse direction. When you want to know the type of `x` at a particular place in the code flow graph, it walks "up" the graph until it finds the last place the value `x` was assigned.

During the graph traversal, if it encounters a "fork", it traverses both branches and returns the union of the two. Let's look at the final `x` in your example. If we walk up the graph, we encounter a "fork" due to the if statement (either the "if" was true or false). It evaluates `x` along both paths. In both cases, the answer is `T`. It then unions `T` with `T` and determines that the answer is `str | float`. The `T` name is dropped in the process of creating this new union type.

That's probably more details than you wanted to know, but you asked... :)

I agree this looks inconsistent. I'll see if there's a straightforward and cheap way to retain the type alias name.

**Comment by Azureblade3808** [comment]
The logic is solid, so such inconsistency is not something I need to worry about.

Thank you for the explanation.
