### ISSUE TITLE
Using nonlocal causes variable type “Never”

### ISSUE THREAD

**Issue by phlibi** [microsoft/pylance-release#1355]
Hi everyone,

I'm seeing a strange behaviour of Pylance with some code. Consider the following minimal example:

```` lang-python
#!/usr/bin/env python3

from typing import Optional

def main():
    x: Optional[list] = None
    def f():
        nonlocal x
        x = [10]
    f()
    assert isinstance(x, list)
    y: int = x[0] + 3
    assert isinstance(y, int)
    print(y)

main()
````

The call to f() obviously sets the outer `x` to `[10]`. Hovering over `x` in the first `assert` statement (after the function call) shows `(variable) x: None`, which is ok. But after the `assert` statement, hovering over x shows `(variable) x: Never` instead of `x: list`. This causes both the syntax highlighting and auto completion to fail for `x`on all following lines, as Pylance obviously sees a variable that has kind of "no type". Typing `x.` does not even show object's builtin members like `x.__class__` or `x.__doc__`. Assigning `x` to another typed variable does not help. The first assert causes mypy to accept the code, while PyLint says `Value 'x' is unsubscriptable`, so there seems to be some disagreement between other tools as well. This is a bit annoying, as the code otherwise works fine.

Questions: Is this a bug in Pylance? Or even expected behaviour? Is there any way to force Pylance to see the correct type of `x`?

Tool versions:
```
$ code --version
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64
$ pylint --version
pylint 2.8.2
astroid 2.5.6
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
$ mypy --version
mypy 0.800
```
VSCode Python: v2021.5.842923320<br/>
VSCode Pylance: v2021.5.3

Note: Originally posted here: https://stackoverflow.com/q/67704387/1306747

Thank you and best regards,<br/>
Philipp

**Comment by erictraut** [comment]
Pyright (the type checker that underlies pylance) performs local code flow analysis to determine the types of symbols within a function. It is not able to understand mutations (side effects) generated by other execution flows (other functions, modules, etc.). In this case, you are calling another function `f`, which is mutating the value of (and the type of) `x`.

Dependence on such side-effects is generally considered a bad programming practice, as it makes the code flow less obvious to humans as well as tools.

A workaround is to avoid the use of `nonlocal` and modify `f` to return a new value, like this:

```python
    def f():
        x = [10]
        return x

    x = f()
```

**Comment by phlibi** [comment]
I totally agree that this is not very good practice. The example might have been a bit oversimplified. In fact, I came across the issue when writing a unit test for an object, which involves callback functions. To assert that the callback function actually gets called and that the correct arguments get passed, I put such a callback with the `nonlocal` statement inside the test function. Something like this:

````python
#!/usr/bin/env python3

from typing import Callable, List, Optional


class SomeType:
    def __init__(self, val: int):
        self.value = val


class C:
    callbacks: List[Callable[[SomeType], None]]

    def __init__(self):
        self.callbacks = []

    def foo(self, x: int) -> None:
        for cb in self.callbacks:
            cb(SomeType(x))


def test_func() -> None:
    cb_arg: Optional[SomeType] = None
    def callback(arg: SomeType) -> None:
        nonlocal cb_arg
        cb_arg = arg
    test_class = C()
    test_class.callbacks.append(callback)
    test_class.foo(42)
    assert isinstance(cb_arg, SomeType)
    assert cb_arg.value == 42   # No autocompletion here.
    #        ^--- Mouse hover shows "(variable) cb_arg: Never"


test_func()
````
In this case, it is not as easy to simply pass the argument back as a return value, since there could actually be multiple callbacks, so the results would need to be assembled into a list, etc. That's clearly not ideal, as it would pollute the actual implementation with test code. Of course, there would be other options to make it work, like defining `callback()` at the same level as `test_func()` and using a module-global variable (or an object member in the case of a unit test), but that would not be very nice either, as it spreads the test code and makes the test function less self-contained.

What I would like to see in Pyright is the same behaviour that is implemented in mypy. Any code following a line like
````python
assert isinstance(x, T)
````

can be absolutely sure that `x` is of type `T`, otherwise it would not be reached. Other constructs like

````python
if isinstance(x, T):
    # x is definitely of type T here.
    pass
# x could be of another type here.
````
could be supported as well. I suppose that Pyright actually comes to the conclusion that the line cannot be reached (think of the pseudo-type `Never`), but shouldn't it then also gray out the line `assert cb_arg.value == 42` as it does in

````python
if False:
    print('hello')   # Grayed out.
````
?

**Comment by erictraut** [comment]
Both pyright and mypy perform type narrowing for `assert` statements. However, there are some differences between the two, and I can defend pyright's behaviors in these cases.

The first difference is in how mypy handles the first assignment in `test_func`:
```python
cb_arg: Optional[SomeType] = None
reveal_type(cb_arg) # Mypy says "Optional[SomeType]", but pyright says "None"
```

Mypy's behavior here doesn't make sense to me because it is inconsistent with other mypy behavior. Consider this small change:
```python
cb_arg: Optional[SomeType]
cb_arg = None
reveal_type(cb_arg) # Now mypy says "None"
```

In other words, mypy is applying type narrowing on assignment in some cases but not in others. I've discussed this inconsistency in the typing-sig previously, and I think there was some agreement that mypy's behavior was inconsistent, but the mypy maintainers haven't yet removed this inconsistency.

Both mypy and pyright also perform type narrowing for `assert` statements. For example:
```python
def func(x: Union[int, str]):
    reveal_type(x) # Both mypy and pyright say "Union[int, str]"
    assert isinstance(x, str)
    reveal_type(x) # Both mypy and pyright say "str"
```

Here's your code with a few small changes, including the addition of some `reveal_type` calls:

```python
def test_func() -> None:
    cb_arg: Optional[SomeType]
    cb_arg = None
    reveal_type(cb_arg) # Both mypy and pyright say "None"

    def callback(arg: SomeType) -> None:
        nonlocal cb_arg
        cb_arg = arg

    reveal_type(cb_arg) # Both mypy and pyright say "None"

    test_class = C()
    test_class.callbacks.append(callback)
    test_class.foo(42)
    reveal_type(cb_arg) # Both mypy and pyright say "None"
    assert isinstance(cb_arg, SomeType)
    reveal_type(cb_arg) # Mypy says "None", but pyright says "Never"
```

Note that both mypy and pyright evaluate the same types up until the last line, when they diverge. I'm not quite sure why mypy thinks that the narrowed type should remain `None` here, since there is no overlap between the type `None` and `SomeType`. I don't think mypy has the notion of `Never`, so perhaps that's the explanation. I introduced `Never` when I wrote pyright — an idea that I stole from TypeScript.

If you want to override the type evaluated by the type checker, you can use the `cast` call, like this: ```cb_arg = cast(SomeType, cb_arg)```. That may be your best option in this case, since the way you're using `nonlocal` is violating assumptions made by both mypy and pyright.

You also asked about why code within a conditional block is determined to be unreachable in some cases. There are some expressions that need to be evaluated in an early phase of type checking (the "binding" phase, to use pyright's terminology). This includes conditional expressions like `True`, `False`, `Debug`, `TYPE_CHECKING`, `sys.version_info >= (3, 7)`, and `sys.platform == "win32"`. These are very special cases and are agreed upon by type checkers (and even called out in [PEP 484](https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking)) because these expressions need to be statically evaluated prior to any semantic analysis being performed. We need to evaluate these special expressions early because they affect the code flow graph, which needs to be built prior to performing semantic analysis passes.

So if you replace `if False` with `if 1 == 2`, you'll notice that the body of the function is no longer grayed out because the latter is not one of these special expression forms.

**Comment by phlibi** [comment]
Thank you for the thorough explanation. Now I understand much clearer what's going on and why. "Type narrowing" is an important indication; I wrongly assumed that `assert isinstance(x, T)` would force `x` to be of type `T` for the type checker, while that is not true and `x` will only be forced to `T` if `T` was a possibility already before. The mypy behaviour is indeed a bit weird and inconsistent.

Anyway, for me, the most important part was the mention of `cast`, which I wasn't aware of before. This allows me to force the typechecker's type to what it actually is after the assert statement.

I'll close this issue, as it can be easily worked around (if one is aware of `cast`) and extending Pyright's type inference to also analyze mutations would certainly be far too much effort for just this small benefit.

Thank you very much Eric.
