### ISSUE TITLE
What's the best practice to deal with function argument that can have multiple types

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pylance-release#1390]
Say that I have a function `sort_candidates()`. User is allowed to customize priority values for some candidates of his choice. To accomplish that, the `sort_candidates` function takes an optional  `priorities` argument.

The `priorities` argument can either take a mapping of (candidate, priority_value) pair, or an iterable of candidates. If a mapping is passed in, the candidates are assigned their corresponding priority_values. If an iterable is passed in, the candidates are assigned a default priority_value, say, 1.

Let's put these in code:

```python3
from collections.abc import Itearble, Mapping
from typing import Union

candidate_pool = from_some_where()

def sort_candidates(priorities: Union[Mapping[str, int], Iterable[str]] = ()) -> str:
    """
    Sort candidates based on their priority values.
    If the priority values tie, use the name to break the tie.
    """

    if isinstance(priorities, Iterable):
        priorities = {candidate: 1 for candidate in priorities}

    candidate_pool.sort(key = lambda cand: (prioritise.get(cand, 0), cand))
```

The code is done. And Pylance complains about that `Cannot access member "get" for type "Iterable[str]"` for the last line.

I wonder what kind of fix is considered the best practice to do here, so that Pylance could be happy, and the code won't become too ugly and hacky. Thanks in advance for any advice!

**Comment by erictraut** [comment]
A few observations about your code:

`Iterable` is a protocol class (a runtime-checkable protocol class), and all `Mapping` instances conform to that protocol, so the `isinstance` check will always be true.

That means your code will always execute `priorities = {candidate: 1 for candidate in priorities}`, so you might as well delete the `isinstance` check.

The type of `priorities` is annotated as `Union[Mapping[str, int], Iterable[str]]`. Pylance will narrow that type to just `Mapping` after the assignment `priorities = {candidate: 1 for candidate in priorities}`.

However, because you're using it within a lambda, which has a different execution lifetime from the rest of the function, its type within the lambda is not narrowed.

The best workaround is therefore to assign to a different local variable:

```python
def sort_candidates(priorities: Union[Mapping[str, int], Iterable[str]] = ()) -> str:
    """
    Sort candidates based on their priority values.
    If the priority values tie, use the name to break the tie.
    """

    priorities_dict = {candidate: 1 for candidate in priorities}

    candidate_pool.sort(key=lambda cand: (priorities_dict.get(cand, 0), cand))
```

Or if you'd like to retain the `isinstance` check but make sure that it runs only when necessary:
```python
def sort_candidates(priorities: Union[Mapping[str, int], Iterable[str]] = ()) -> str:
    """
    Sort candidates based on their priority values.
    If the priority values tie, use the name to break the tie.
    """

    if isinstance(priorities, Mapping):
        priorities_map = priorities
    else:
        priorities_map = {candidate: 1 for candidate in priorities}

    candidate_pool.sort(key=lambda cand: (priorities_map.get(cand, 0), cand))
```

**Comment by MapleCCC** [comment]
@erictraut Thank you for the kind reply and the informative explanation.

I must apologize that I accidentally made some typo when writing the issue description. The line of `isinstance` check should have been against `Mapping` not `Iterable`. It should have been `if not isinstance(Mapping)` instead of `if isinstance(Itearble)`.

Despite the typo I made, I believe your patient and detailed answer is very helpful and already good enough to solve my problem. I will use the "assign to a different local variable" approach you suggest to solve the type error here. Again, thank you very much for your kind help and patient reply!
