### ISSUE TITLE
When does Pylance couple the occurrences of an unbounded TypeVar that appear as argument of a function?

### ISSUE THREAD

**Issue by PatrickBourdon** [microsoft/pylance-release#1396]
Further are some `cook` examples.

I first thought that pylance would report `dish_1` as incorrect, but it isn't.
Actually, `cook_1` is equivalent to `cook_2` and `cook_3`: you can mix any type for the arguments `a` and `b` and it's ok.

I was expecting `cook_1` to behave like `cook_4`, i.e. that the two `_T` arguments would be "coupled" whatever the type. That is to say, just like in a mathematical equation, `x` can take any value but it is the same value for all of the occurrences within the equation. But it isn't the implemented behavior: both `_T` arguments are treated independently and the inferred output type is their union.

To couple the types of the argument, you have to either:
- provide a set of possible types: `_T = TypeVar('_T', Fruit, Vegetable)` - see `cook_4`
- bound by a super class: `_T = TypeVar('_T', bound=Food)`
So you need to know in advance those types or the super class.

However the typing behavior of the following `partition()` function is different:
- `_T` is used twice in the arguments of the function.
- `_T` is neither bound by a super class or by a fixed set of types.

Nevertheless pylance expects that the type of the `x` argument of the `lambda` function (first `_T` occurrence) to be the same as the type of the iterable element (second `_T` occurrence). 
They are not independent: they are expected coupled.
And this is the reasonable expected behavior: good!

I understand the difference comes from the `Callable` argument (with the contravariant behavior of its inputs), which is then processed differently.
I didn't find a PEP or a document that explains about this.
Could you give some clues or point to some web resources?

Regards,
Patrick Bourdon (Paris - France) 

## Code Snippet / Additional information
```python
from typing import cast, Any, TypeVar
from collections.abc import Callable, Iterable

class Food: ...
class Fruit(Food): ...
class Vegetable(Food): ...

_T = TypeVar('_T')
def cook_1(a: _T, b: _T) -> _T: 
    return cast(_T, object)
dish_1 = cook_1(Fruit(), Vegetable()) # dish_1 inferred type is "Fruit | Vegetable"

_T2 = TypeVar('_T2')
def cook_2(a: _T, b: _T2) -> Union[_T, _T2]:
    return cast(_T2, object)
dish_2 = cook_2(Fruit(), Vegetable()) # dish_2 inferred as "Fruit | Vegetable"

_T3 = TypeVar('_T3', bound=object)
def cook_3(a: _T3, b: _T3) -> _T3:
    return cast(_T3, object)
dish_3 = cook_3(Vegetable(), Fruit()) # dish_3 inferred as "Fruit | Vegetable"

_T4 = TypeVar('_T4', Fruit, Vegetable)
def cook_4(a: _T4, b: _T4) -> _T4:
    return cast(_T4, object)
dish_4 = cook_4(Vegetable(), Fruit()) # error: "Fruit" is incompatible with "Vegetable"

#--------------------------------------------------
def partition(predicate: Callable[[_T], bool], iterable: Iterable[_T]) -> tuple[list[_T], list[_T]]:
    """ Separate the wheat from the chaff. """
    _true: list[_T] = []
    _false: list[_T] = []
    for x in iterable:
        (_true if predicate(x) else _false).append(x)
    return (_true, _false)

predicate1 = lambda x: bool(x%3) # error reported: x is Unknown (as expected)
r1 = partition(lambda x: bool(x%3), range(10)) # correct: x inferred as 'int'
r2 = partition(lambda x: bool(x + '1'), range(10)) 
    # x is inferred 'int'
    # # error reported: "+" not supported between "int" and "Literal['1']"
r3 = partition(lambda x: bool(x + '1'), (str(x) for x in range(10))) # correct: x inferred as 'str'
```

**Comment by erictraut** [comment]
You are correct that the constraint solver must find a solution for `_T` that is consistent for all appearances of `_T` within the signature. For invariant and covariant type variables, it can do that by "widening" the type of `_T` to accommodate all of the arguments. (For contravariant type variables, it can do something similar by narrowing the type of `T`.)

There are two primary strategies one can use for widening. Mypy uses the "join" strategy where it finds a parent class that is common to the types. Quite often, this is `object`. Pyright uses the "union" strategy — i.e. it creates a union of the types. The union strategy is a much better approach in most cases (in my opinion). There are dozens of bugs in the mypy bug database reporting false positive errors because of the "join" widening strategy it employs, and pyright avoids those problems because it employs the "union" strategy instead.

```python
reveal_type(cook_1("hi", 1)) # Mypy says "object", pyright says "str | int"
```

The reason that `partition` is different is that `_T` is covariant when used with `Iterable`, but it's contravariant when used in `Callable[[_T], bool`. (All input parameters in a callable are implicitly contravariant.) That means the constraint solver has a "lower bound" constraint and an "upper bound" constraint that it needs to solve for. In other words, it needs to employ both narrowing and widening in an attempt to find some type for `_T` that satisfies all of the constraints. 

This is complicated by the fact that parameter types for lambdas cannot be annotated, so the type analyzer needs to infer their types from context. The analyzer needs to do multiple passes when matching argument types to parameter types as it gains more knowledge about the constraints. For example, with `r2 = partition(lambda x: bool(x + '1'), range(10))`, the first time it evaluates the lambda expression, it does not have enough information to determine the type of `x`. It is only once it evaluates the type of the second argument expression `range(10)` and attempts to assign that to parameter `iterable` that it can determine that `_T` has a lower bound of `int` (i.e. it cannot be narrowed more than `int`). Then when it performs a second pass, it can tell that `x` must be an `int`. Since it's contravariant in this context, it would normally be possible to narrow it further, but it cannot be narrowed in this case because `int` is already its lower bound.

In these complex cases that involve callbacks with lambdas and combinations of covariant and contravariant uses, there are some nondeterministic cases within the constraint solver that must be resolved using heuristics. Each type checker will implement different sets of heuristics, and I've spent a lot of time tuning the heuristics in pyright to accommodate as many cases as possible.

Most of the details above are not well documented in PEP 483 or 484, and it took me a long time to fully understand these rules.

If you're interested in the logic used within pyright's constraint solver, check out [this function](https://github.com/microsoft/pyright/blob/938fd6faacc06316d7b47d2a2ef0cb7cf0175ecf/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L20500).

**Comment by PatrickBourdon** [comment]
Thank your Eric, your answer fits my expectations.

The PEP specification is obviously not univoque, and allows for some implementations with different but compliant results.
pyright/pylance and mypy come with different solutions.

Your answer summarizes your (pyright) team design strategy: 
for each call to a function using a TypeVar type, say _T, in its signature, an internal solver analyses the types of the parameters to find a type for _T that matches all. 
The types of covariant/invariant (resp. contravariant) arguments are lower (resp. upper) constraints.
Also the programmer can force some constraints in the TypeVar declaration, using an explicit list or a bound.

Some complexity swears out here, resulting in the pointed "gargantuan" module. Hats off!
I hope (and assume) you've a bunch of commented unit tests about heuristics to avoid nightmares in the long run, due to the high regression risk when facing and tuning any new and unexpected use case.
