### ISSUE TITLE
Ignoring more than 1 parameters in overriden method seems to always produce an error in strict mode

### ISSUE THREAD

**Issue by PowerSnail** [microsoft/pylance-release#1399]
## Environment data

-   Language Server version: 2021.6.0  (strict mode)
-   OS and version: Linux, OpenSUSE Tumbleweed
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.4

## Expected behaviour

When a class overrides a method of its parent class, and wants to ignore more than 1 parameters with "*_", it should not produce an error of parameter count mismatch, since "*_" can represent an arbitrary number of parameters.

## Actual behaviour

If I use "*_" to capture all the parameters, I get a parameter count mismatch.

If I use "_" and "__" to represent each parameter, I have parameter name mismatch.

There seems to be no way of ignoring more than 1 parameters that produces no error in strict mode.

## Code Snippet / Additional information

```python

class A:
    def work(self, i: int, j: int):
        print(f"A: {i}, {j}")

class B(A):
    def work(self, *_):  # Parameter count mismatch
        print(f"B: Don't care about the parameters")

class C(A):
    def work(self, _, __):  # Parameter name mismatch
        print(f"C: Don't care about the parameters")

```

**Comment by erictraut** [comment]
I presume that you have enabled the `reportIncompatibleMethodOverride` diagnostic check. It is off by default in basic type checking mode.

The current behavior is intentional. Parameter names in Python are important (unless they are position-only) because callers can specify parameters by name. For this reason, an overridden method must retain the parameter names of the method is it overriding.

If you want to ignore this error, you can disable the `reportIncompatibleMethodOverride` diagnostic check within the source file or globally for your project.

**Comment by erictraut** [comment]
Here's an example of how the code would fail.

```python
def func(a: A):
    a.work(i=1, j=2)

func(A()) # This works
func(C()) # This results in a runtime error
```

When overriding a method in Python, it's important to faithfully honor the signature from the parent class.

Pylance does allow for compatible overrides, like this:

```python
class B(A):
    def work(self, i: int, j: int, x: int = 3):
        pass

class C(A):
    def work(self, i: int, j: int, *args: Any):
        pass
```

**Comment by PowerSnail** [comment]
Thanks for the explanation; I hadn't thought of that.
