### ISSUE TITLE
Function mapping with base and derived classes

### ISSUE THREAD

**Issue by kigawas** [microsoft/pylance-release#1433]
It is kind of related with #955 , but this is about `Mapping` rather than `Sequence`.

Say I have a function mapping like:
```python
from dataclasses import dataclass
from typing import Callable, Mapping


@dataclass
class A:
    a: int


class B(A):
    b: int


class C(A):
    c: int


def handle_b(b: B):
    return None


def handle_c(c: C):
    return None


HANDLER_CONFIG: Mapping[str, Callable[[A], None]] = {
    "b": handle_b,
    "c": handle_c,
}
```

Then it complains: `Expression of type "dict[str, (b: B) -> None | (c: C) -> None]" cannot be assigned to declared type "Mapping[str, (_p0: A) -> None]"`
![image](https://user-images.githubusercontent.com/4182346/121645799-931b1a00-cacf-11eb-890c-4a2de54f6877.png)

Apparently `(b: B) -> None | (c: C) -> None` is different from `(a: A) -> None`, but `(a: A) -> None` looks like more permissive. Since I added the type obviously, it should take the annotation type rather than the inferred type.

**Comment by erictraut** [comment]
Pyright is doing the right thing here. Mypy emits the same error in the same location.

The problem is that input parameters to `Callable` instances must be treated as contravariant. That means the types of the parameters must be supertypes, not subtypes. In your case, you're assigning callbacks whose parameters are subtypes (e.g. `B` is a subtype of `A`).

Let's simplify your code. This will help explain.

```python
def handle_b(b: B):
    print(b.b)

x: Callable[[A], None] = handle_b # Type Error

x(A(a=1)) # Crash!
```

In this case, you're saying that `x` is a callable that takes an input parameter of type `A`, but you're attempting to assign `handle_b` which requires an input parameter of type `B`. If someone tries to call `x` and passes it an instance of `A`, `handle_b` would crash because it's expecting an instance of `B`.
