### ISSUE TITLE
Undefined for global variable in nested function

### ISSUE THREAD

**Issue by memeplex** [microsoft/pylance-release#1439]
## Environment data

-   Language Server version: 2021.6.1
-   OS and version: macOS Big Sur
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

```python
def f():
    global x

    def g():
        print(x)
```

`x` in `print(x)` is defined so no error is reported.

## Actual behaviour

pylance shows a `reportUndefinedVariable` error.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by memeplex** [comment]
I'm closing this because I believe it was a misunderstanding of mine, the code where I first found it was deeply intertwined with other complex logic that may be causing the issue, and in the simple example I posted above definition is indeed missing so I now believe pylance is doing a global analysis for the entire module, not just local to the `f` function, hence correctly recognizing that `x` is undefined at the global scope.

**Comment by erictraut** [comment]
Is `x` being assigned anywhere in the module — either in the global scope or in a local scope where it is bound to the global scope using the `global x` statement? If it's assigned somewhere, pyright shouldn't emit an error. However, if it's not assigned anywhere, then I think it's appropriate to emit an error in this situation because it will result in a runtime exception if you access the contents of the variable without assigning it a value first.

**Comment by memeplex** [comment]
pylance doesn't emit any error if `x` is assigned either at the global scope or at `f` scope where it's declared as global, so I believe it's doing the right thing, Eric. After all it's an undefined, not undeclared, error.
