### ISSUE TITLE
`Optional[]` arguments are not properly checked in dictionaries

### ISSUE THREAD

**Issue by schperplata** [microsoft/pylance-release#1446]
Issue Type: <b>Bug</b>

Should Pylance be able to resolve such type hinting and `if`-ed validation?

Code:
```python
class Bar:
    def __init__(self) -> None:
        self.someValue = "42"


class MyData:
    def __init__(self, foo: str, bar: Optional[Bar]) -> None:
        self.foo = foo
        self.bar = bar


def func(bar: Bar):
    pass


def main(data: Dict[str, MyData], name: str):
    func(data[name].bar) # expecting error squiggles

    if data[name].bar is None:
        print("bar is None")
    else:
        func(data[name].bar) # shouldn't have 


def main2(data: List[MyData]):
    func(data[0].bar) # expecting error squiggles

    if data[0].bar is None:
        print("bar is None")
    else:
        func(data[0].bar)
```

VSC:
![image](https://user-images.githubusercontent.com/8736111/121870287-2e480580-cd03-11eb-81f8-cc911e9f3b9f.png)

Extension version: 2021.6.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.35GB free)|
|Process Argv|W:\\trunk\\BlueBox\\fitIDEA\\fitIDEA.code-workspace --crash-reporter-id d9d15ca2-a021-4dcd-a140-bb0adc228360|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
pythonvsuse255cf:30319632
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by erictraut** [comment]
This behavior is intended.

Type narrowing is not applied for expressions that include indexes unless the subscript is a string or integer literal value. It's generally not safe to apply type narrowing in this case because the value of the expression can change between the check and the usage, and it's very difficult (if not impossible) for a type checker to guarantee that it's still safe. Mypy (another popular Python type checker) makes the same assumption.

This explains why type narrowing is applied for `data[0].bar` but not for `data[name].bar`.

The recommended workaround is to use a temporary variable to fetch the value. This is not only type friendly but also results in faster runtime performance.

```python
    bar = data[name].bar
    if bar is None:
        print("bar is None")
    else:
        func(bar)
```
or

```python
    if (bar := data[name].bar) is None:
        print("bar is None")
    else:
        func(bar)
```

For more details about type narrowing in pyright (the type checker used within pylance), check out [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing).

**Comment by schperplata** [comment]
All clear, thanks.
