### ISSUE TITLE
Pylance incorrectly reports that module is not a known member of another module

### ISSUE THREAD

**Issue by ldorigo** [microsoft/pylance-release#1447]
Issue Type: <b>Bug</b>

Depending on how I import a module from Biopython, Pylance shows an error stating that a submodule is not a known member of the module:

```python
from Bio import Entrez

a : Entrez.Parser.ListElement #Doesn't work, "Parser" is not a known member of module"
#######################3

from Bio.Entrez import Parser

a : Parser.ListElement # Works
```

Here is the code for the relevant library: https://github.com/biopython/biopython/tree/master/Bio/Entrez

Extension version: 2021.6.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.895Z)
OS version: Linux x64 5.10.39-1-lts
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 4234)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.36GB (3.07GB free)|
|Process Argv|--crash-reporter-id 66ea3ec9-05eb-4edd-8d35-34bbe6c1aba1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma-i3|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE-i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by jakebailey** [comment]
Reading the code for `Entrez/__init__.py`, it doesn't actually explicitly export `Parser` as a variable (nor does it even reference it; if your first example isn't crashing at runtime, then it's relying on the side effect of another module loading it. We statically cannot assume that it's going to be there.

Is there example code that they show that this should be possible, or is this code you've written originally?

**Comment by ldorigo** [comment]
Hmm, I could have sworn that both example worked at runtime, but trying it now (on another environment) the first example indeed crashes at runtime. But it looks like you're right and I just still don't understand python imports... :-) you can close, sorry for the inconvenience.

**Comment by YannickAlex07** [comment]
@jakebailey I have a question regarding this problem and the package resolution. We are currently facing the exact same problem as described in this issue with the [apache_beam](https://github.com/apache/beam/tree/master/sdks/python) package and the `pvalue` submodule.

The following doesn't work:

```python
import apache_beam as beam

beam.pvalue.AsSingleton(...) # throws a "is not a known member of module" error
```

While the following does:

```python
from apache_beam import pvalue

pvalue.AsSingleton(...)
```

The apache_beam package does not export the `pvalue` module in its `__init__.py`, however the `pvalue` module is a single module file on the top level of the package. Shouldn't the first snippet work, because the top level `__init__.py` is not restricting top level imports with `__all__`? We are a little confused because python is executing our pipelines without any problems, only Pylance is 'confused' with the import.

If this is indeed the correct behaviour by Pylance, is there a PEP or something that goes into detail about this?

**Comment by jakebailey** [comment]
I'm assuming you're talking about the runtime behavior, correct?

In your first example, all it does is `import apache_beam`; it's not guaranteed that `apache_beam.pvalue` exists unless it's actually imported later, either explicitly to export (which Pylance will respect), or via a side effect of someone importing it and it happening to be in the symbol table for `apache_beam` (which Pylance will not attempt to figure out). That'd be why the first code crashes in some cases but not others.

The latter explicitly will do `import apache_beam; import apache_beam.pvalue`, so it'll all run.

**Comment by YannickAlex07** [comment]
@jakebailey Thank you very much for the quick answer! This cleared up our misunderstanding how the package resolution works!
