### ISSUE TITLE
Hovering prompts decorator's signature, instead of function's, for python-telegram-bot

### ISSUE THREAD

**Issue by ushuz** [microsoft/pylance-release#1470]
## Environment data

-   Language Server version: 2021.6.2
-   OS and version: macOS 11.4
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.9 (pyenv)

## Expected behaviour

Hover on referenced function, its actual signature pops up

## Actual behaviour

Instead, decorator's signature was prompted, as in screenshot

![image](https://user-images.githubusercontent.com/1430856/122634030-b37b4380-d090-11eb-8f64-25b4c666a844.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

I saw some posts on Stack Overflow saying that this kind of behaviour was already fixed. So I suppose it might have something to do with [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot)?

I'm using the latest version 13.6, which can be installed with pip

```
pip install python-telegram-bot
```

Here's a simple snippet to reproduce

```python
import telegram
bot = telegram.Bot()
bot.edit_message_text()
```

**Comment by judej** [comment]
thanks for the report. 

How is the `@log` defined? I suspect that the `@log` is overwriting the signature.

**Comment by ushuz** [comment]
@judej 

`@log` is defined here: https://github.com/python-telegram-bot/python-telegram-bot/blob/105f1ccdb5283f19c97c76a8234f8e61df88ce60/telegram/bot.py#L121-L134

```python
def log(  # skipcq: PY-D0003
    func: Callable[..., RT], *args: object, **kwargs: object  # pylint: disable=W0613
) -> Callable[..., RT]:
    logger = logging.getLogger(func.__module__)

    @functools.wraps(func)
    def decorator(*args: object, **kwargs: object) -> RT:  # pylint: disable=W0613
        logger.debug('Entering: %s', func.__name__)
        result = func(*args, **kwargs)
        logger.debug(result)
        logger.debug('Exiting: %s', func.__name__)
        return result

    return decorator
```

**Comment by jakebailey** [comment]
That explains it; they should really be using `ParamSpec` here. That `func` annotation throws away the parameter information as `...` in the parameter position of `Callable` means `*args, **kwargs`.

For example, this change made in typeshed last week to fix `contextmanager`: https://github.com/python/typeshed/commit/4581501c986041875ac129bd3067ea62a74bb5c5

**Comment by ushuz** [comment]
@jakebailey Thanks for the explanation. I guess I should report this back to the upstream. Please feel free to close this issue if it is no longer relevant to pylance.

**Comment by emjohnson20** [comment]
I have a similar issue being caused by the library ddtrace. They define the type of a decorator like so: 
![image](https://user-images.githubusercontent.com/87835122/126716516-117e42b5-edf8-45db-af3a-193addc2ebb7.png)

In order to get around it, I'm trying to mask their type in my code via 
![image](https://user-images.githubusercontent.com/87835122/126716649-09499d47-018d-470a-bb7a-4de32f337a2f.png)

This unmasks my function types but leaves me with a Pylance error on my `@trace` 
![image](https://user-images.githubusercontent.com/87835122/126716715-beb613bc-60d6-48d3-a23c-5c13e62f5fea.png)

Any recommendation while waiting for an upstream fix in the library would be appreciated.

**Comment by erictraut** [comment]
@emjohnson20, your annotation is incorrect for a decorator that is called as a function. Since `wrap` has parameters that can be specified as keywords and because it has default values, you cannot specify the type using a simple `Callable` annotation. You'd need to use a callback protocol. Something like this:

```python
from typing import Optional, Callable, Any, Protocol, TypeVar
from ddtrace import tracer

_T = TypeVar("_T", bound=Callable[..., Any])

class TraceWrap(Protocol):
    def __call__(
        self,
        name: Optional[str] = None,
        service: Optional[str] = None,
        resource: Optional[str] = None,
        span_type: Optional[str] = None,
    ) -> Callable[[_T], _T]:
        ...

trace: TraceWrap = tracer.wrap
```

**Comment by emjohnson20** [comment]
@erictraut This was working great until Pylance 2021.9.1. Is this a regression or an intentional change? i.e. should I open a bug for this?
Test code for repeating: 
`from typing import Optional, Callable, Any, Protocol, TypeVar
from ddtrace import tracer

_T = TypeVar("_T", bound=Callable[..., Any])


class TraceWrap(Protocol):
    def __call__(
        self,
        name: Optional[str] = None,
        service: Optional[str] = None,
        resource: Optional[str] = None,
        span_type: Optional[str] = None,
    ) -> Callable[[_T], _T]:
        ...


trace: TraceWrap = tracer.wrap


def foo(x: int) -> float:
    return float(x)


@trace(name='test')
def foo_wrapped(x: int) -> float:
    return float(x)


if __name__ == '__main__':
    bar = foo(1)
    bar = foo_wrapped(1)`

**Comment by erictraut** [comment]
What is the error you're seeing?

When I run your sample in basic type checking mode, I don't receive any error. When I run it in strict mode, I see an error "Type of wrap is unknown". That's because the `ddtrace` library is not providing a proper type annotation for the `tracer` symbol. By the rules documented in [this spec](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md), all symbols exported from a py.typed library must have declared types, and any symbols that do not will be treated as unknowns.

If I add a proper type annotation to the `tracer` symbol in `ddtrace/__init__.py`, I don't see any errors in your sample even when in strict type checking mode.

```python
tracer: Tracer = Tracer()
```

**Comment by emjohnson20** [comment]
The issue is that when inspecting the return type of `foo_wrapped(1)` and therefor the type of `bar`, it is now being masked by the wrapping function where previously the return type of float was detected. 
![image](https://user-images.githubusercontent.com/87835122/134721294-1430914a-bd21-453d-b21e-7348ddf7748c.png)

**Comment by erictraut** [comment]
I'm not able to repro what you're seeing. If I paste your example code above, I see the following:

![Screen Shot 2021-09-24 at 11 13 19 AM](https://user-images.githubusercontent.com/7040122/134721768-33a7a8e3-cf9c-44b2-91bb-a127e0c85f1b.png)

This is with the latest published version of `ddtrace` installed.

**Comment by emjohnson20** [comment]
Updating my ddtrace resolved it.

**Comment by jakebailey** [comment]
Oh, oops, this issue is not related to the above. Reopening.

**Comment by harshil21** [comment]
this has been fixed and merged upstream (https://github.com/python-telegram-bot/python-telegram-bot/pull/2686), so safe to close.

**Comment by ushuz** [comment]
@harshil21 Thanks for the follow-up, and again for the fix. I'm closing this issue.
