### ISSUE TITLE
reportMissingImports - yfinance

### ISSUE THREAD

**Issue by heneij** [microsoft/pylance-release#1477]
yfinance

https://pypi.org/project/yfinance/

--version : 2021.6.2
--OS : Windows 10

**Comment by judej** [comment]
Thanks for the report @heneij, could you please send us more information? Screenshot, logs, code sample? 

Could you please use [this guidance ](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md)

**Comment by gc250265** [comment]
@judej, all that guide says about this issue is:

> If you're getting a warning about an unresolved import, **first** ensure that the package is installed into your environment if it is a library (pip, pipenv, etc). If the warning is about importing your own code (and not a library), continue reading.

It actually never gives a **second** step.

I arrived to this page because I have a similar issue. I installed the [classification_models](https://github.com/qubvel/classification_models) library version 0.2.2, and run the following line from the example in that repo:

`from classification_models.keras import Classifiers`

Pylance shows the following error:

`Import "classification_models.keras" could not be resolved Pylance (reportMissingImports)`

If I try to import `classification_models` instead it doesn't have any issues. I just can't find information on how to solve this problem.

**Comment by jakebailey** [comment]
@gc250265 Please open a new bug so we can track that; your issue is likely unrelated to this one (which has effectively no information provided). At a glance of the library, I don't see anything that'd lead to that issue, so full logs as requested in our bug template would be useful.
