### ISSUE TITLE
Buggy autocomplete for relative local imports

### ISSUE THREAD

**Issue by maegul** [microsoft/pylance-release#1479]
**Describe the bug**
Autocomplete is providing incorrect options when importing from local directories with a relative import.

At first, only the already imported top-level import is listed as an option. Then, once the first character of any of the actual sub-directories or modules is typed, the autocomplete will refresh with appropriate options.  

The issue is that one cannot lazily rely on autocomplete for writing relative imports.

I'm using pyright in sublime text, but the issue is reproducible in VS Code.  See https://github.com/sublimelsp/LSP-pyright/issues/76#issue-926293590

See screenshots below for demonstration.

**To Reproduce**
![Screen Shot 2021-06-22 at 12 18 04 am](https://user-images.githubusercontent.com/13930443/122857702-3edc2980-d35c-11eb-80a7-a33d0ab86a97.png)

![Screen Shot 2021-06-22 at 12 18 33 am](https://user-images.githubusercontent.com/13930443/122857719-46033780-d35c-11eb-806a-4566fbee209f.png)

**Comment by erictraut** [comment]
I shouldn't have been so quick to assume this was a bug in the completion provider. It turned out to be a bug in pyright's parser. It tries to provide hints to the completion provider in certain error conditions. In this particular case, it wasn't providing the right hint that the partially-completed package name ended in a dot.

Thanks for reporting the problem. It will be fixed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.6.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202163-23-june-2021
