### ISSUE TITLE
Pandas DataFrame key flagged as undefined var

### ISSUE THREAD

**Issue by smq100** [microsoft/pylance-release#1507]
<h3> Environment data </h3>

-   Language Server version: 2021.6.3
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.0
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Pandas DataFrame key ('close' in capture below) should not be flagged as an unidentified variable

<h3> Actual behaviour </h3>

Pandas DataFrame key ('close' in capture below) is flagged as an unidentified variable

<h3> Logs </h3>

Python Language Server Log
```
[Info  - 7:01:42 AM] Pylance language server 2021.6.3 (pyright e66600b2) starting
[Info  - 7:01:42 AM] Server root directory: /Users/steve/.vscode/extensions/ms-python.vscode-pylance-2021.6.3/dist
[Info  - 7:01:42 AM] Background analysis(1) root directory: /Users/steve/.vscode/extensions/ms-python.vscode-pylance-2021.6.3/dist
[Info  - 7:01:42 AM] Background analysis(1) started
[Warn  - 7:01:42 AM] stubPath /Users/steve/Documents/Source Code/Personal/OptionAnalysis/typings is not a valid directory.

```

<h3> Code Snippet / Additional information </h3>

![image](https://user-images.githubusercontent.com/26316026/123796400-b6551000-d8aa-11eb-859c-66f5cb804339.png)

**Comment by jakebailey** [comment]
Do you have a simple repro we could look at?

This seems like a bug, potentially in our new dictionary key completion; `'close'` is not a variable and shouldn't have been evaluated as such.

**Comment by smq100** [comment]
The error occurs in this file (https://github.com/smq100/inish-optionanalysis/blob/main/learning/predict.py), line 76. The error seems to only occur in the function def test() and in no other places in the entire repo. Dictionary keys anywhere else are not an issue. 

Replacing the var _value with 'close' in line 76 and/or line 74 causes the error (I created the var _value to mute the pylance error)

**Comment by ysmu** [comment]
Piggybacking on this issue, I also noticed some problems with panda's stubs in the latest version (2021.6.3). Perfectly fine invocations like `pandas.Timestamp.min` and `pandas.Timedelta(minutes=3)` are getting flagged. I did a quick investigation and noticed that `pandas.Timestamp` and `pandas.Timedelta` no longer inherit from `datetime.datetime` and `datetime.timedelta` respectively. This is not an issue in in version 2021.6.2.

**Comment by jakebailey** [comment]
Please don't piggy back on issues, make new ones. Reusing issues for unrelated problems makes it very difficult for us to actually track work and get things closed.

The timestamp/timedelta changes were intended in https://github.com/microsoft/pylance-release/issues/779; AFAIK those classes don't actually inherit from datetime or timedelta, but please do make a new issue with a code example.

**Comment by jakebailey** [comment]
Oops, that's not the issue; the issue was identified internally.

**Comment by judej** [comment]
Is this still repro on the newer builds? We have had several bug fixes in related areas that might have resolved the problem.

**Comment by smq100** [comment]
Yes, the same issue is still present at the same code location.  Language server version is currently v2021.9.0

**Comment by jakebailey** [comment]
I've looked at your code, and this strikes me as suspect:

```python
self._data = pd.DataFrame
```

You're assigning `_data` with the `DataFrame` class itself. This doesn't break in the `prepare` function because you assign `_data` with an actual `DataFrame` instance, but `test` could feasibly be called before `prepare`, so the type we have for `_data` there is:

![image](https://user-images.githubusercontent.com/5341706/131899005-25b9d857-4e89-436e-ac95-7251768ed5e8.png)

It's likely we're showing this error because `'close'` does not exist on the `DataFrame` type itself (when accessed via the `[]`). I do feel like our message is wrong here, though, which could indicate a bug.

To fix this in your code, I think it'd be better if your `__init__` said `self._data = None` instead. If I do this, then the errors go away. (Though, I'd recommend sticking an `assert self._data is not None` at the top of `test` or something, but you don't have type checking enabled anyway.)

Minimized, I can reproduce this with:

```python
class A: ...

class B:
    def __init__(self):
        self._a = A
    
    def prepare(self):
        self._a = A()

    def test(self):
        print(self._a['close'])
```

@erictraut This seems to be a bug; without type checking enabled, the above says that `close` inside the quotes is undefined. Maybe it's because it's thinking it's subscripting a type, and is evaluating `close` expecting a type?

**Comment by smq100** [comment]
Good catch! 
setting self._data = pd.DataFrame() does indeed fix the issue at my end. 
Thanks very much for the informal code review and nice job.

**Comment by heejaechang** [comment]
this seems already fixed.
