### ISSUE TITLE
Add refactoring features like change in file, module and variable names

### ISSUE THREAD

**Issue by qb-tarushg** [microsoft/pylance-release#1510]
## Environment data

- VS Code version: XXX
- Extension version (available under the Extensions sidebar): XXX
- OS and version: XXX
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX 
- Relevant/affected Python packages and their versions: XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:
1. XXX

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
XXX
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`; turn on source maps to make any tracebacks be useful by running `Enable source map support for extension debugging`)

```
XXX
```

**Comment by jakebailey** [comment]
Just to explicitly list things here:

- We support variable renaming already (F2)
- Renaming modules/files, no, but that may be https://github.com/microsoft/pylance-release/issues/127.

**Comment by jakebailey** [comment]
I think I'm going to close this in favor of #127 (as noted above); we're working on it.

**Comment by tomc-goodrx** [comment]
@jakebailey FWIW I'm pretty sure #127 won't solve the thing I need right now (that PyCharm does). That is breaking the stuff (functions, consts, classes, etc) up in some file into a bunch of smaller files and renaming the references.

It's pretty similar conceptually to rename symbol, but since each other file in the workspace has some reference to the current module it's mostly about easily updating those.

Since #127 operates on a file level I don't think it will help with actual refactoring.
