### ISSUE TITLE
Module level import not recognized

### ISSUE THREAD

**Issue by CMLL** [microsoft/pylance-release#1512]
## Environment data

-   Language Server version: 2021.6.3
-   OS and version: KDE Neon
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

Importing an object from a file in the same module should be recognized.
Example:
I have this structure:
root/src/module_a/__init__.py
root/src/module_a/file_a.py
root/src/module_a/file_b.py

```
file_a:

class Object1:

file_b:
from file_a import Object1

class Object2
```

## Actual behaviour

the line `from file_a import Object1` says it can't find Object1, even though they are in the same module. This can get solved by adding  `root/src/module_a` to the extra_paths variable but I believe a simple import in the same module should be recognized without having to add any extra, otherwise the extra paths will be a huge list of extra paths.

**Comment by bschnurr** [comment]
I suggest using relative imports

`from .file_a import Object1`

or absolute

`from module_a.file_a import Object1`

**Comment by CMLL** [comment]
@bschnurr I've resorted to using absolute imports for now, but just for my edification, is there a benefit to using absolute or relative imports over the type I put in the description? Or is just a thing for the LS?

**Comment by erictraut** [comment]
Absolute imports rely on a list of import resolution paths configured in your Python interpreter. This list of paths can be specified through a variety of mechanisms including dynamic manipulation of `sys.path`, the `PYTHON_PATH` environment variable, and the working directory at the time the Python interpreter is invoked. Pylance does not know how you will eventually invoke the Python interpreter (e.g. which working directory or which environment variables). It assumes that you will use the root directory of your workspace as a working directory. If you plan to use a different working directory, specify other import resolution paths via `PYTHON_PATH`, or dynamically add paths by manipulating `sys.path` at runtime, you need to tell Pylance about those other directories using the `python.analysis.extraPaths` setting.

By comparison, relative imports are always resolved relative to the current file location, so they don't rely on import resolution paths.

From a maintenance standpoint, I find that using relative imports (at least within a module) is preferable because they don't rely on the vagaries and complexities of import resolution path configuration. Relative imports don't work outside of a traditional module (those defined by an `__init__.py` file), so they are not an option when used with namespace modules or simple scripts.

**Comment by jakebailey** [comment]
At the moment, this is working as expected, pending changes we make for #68 or #253, which are currently being worked on in various ways.
