### ISSUE TITLE
Incorrect hint, Escape sequence (backslash) not allowed in expression portion of f-string

### ISSUE THREAD

**Issue by edwardchenchen** [microsoft/pylance-release#1522]
Incorrect hint, Escape sequence (backslash) not allowed in expression portion of f-string

## Environment data

-   Language Server version: Pylance language server 2021.6.3 (pyright e66600b2) 
-   OS and version: Mac
-   Python version: 3.7/3.9.4
<img width="798" alt="Screen Shot 2021-07-05 at 12 27 58 am" src="https://user-images.githubusercontent.com/6397192/124388815-df045c00-dd27-11eb-8db2-bb29da0d4161.png">

```python
message = "Hi"
print(f"{message:\u3000>10}")
```
The above code is valid, as \u3000 is in the format part.
<img width="519" alt="Screen Shot 2021-07-05 at 12 32 24 am" src="https://user-images.githubusercontent.com/6397192/124388962-7a95cc80-dd28-11eb-95eb-a3e627034cdb.png">

**Comment by erictraut** [comment]
Thanks for the bug report. 

[PEP 498](https://www.python.org/dev/peps/pep-0498/#specification) is pretty unambiguous that backslashes are not allowed within an f-string expression.

> Backslashes may not appear anywhere within expressions. Comments, using the '#' character, are not allowed inside an expression.

It appears that the format specifier is exempted from this limitation. I've updated the logic in plyance accordingly. This eliminates the diagnostic (error) message. However, the textmate grammar that controls syntax coloring also makes the same assumption, so that portion of the f-string format specifier appears as red text. This is outside the control of pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202170-6-july-2021
