### ISSUE TITLE
Error when using TypeVar in type annotation for @property

### ISSUE THREAD

**Issue by vishwa-raj** [microsoft/pylance-release#1523]
<h3> Environment data </h3>

-   Language Server version: 2021.6.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet / Additional information </h3>

```python
from typing import TypeVar

TYPE_T = TypeVar('TYPE_T', int, float)


class Parent:
    @property
    def data(self) -> TYPE_T:
        return self._data

    @data.setter
    def data(self, value: TYPE_T):
        self._data = value

```

<h3> Expected behaviour </h3>

No error.

<h3> Actual behaviour </h3>

Using `TypeVar` for `property` type annotations shows error:

![image](https://user-images.githubusercontent.com/22815753/124433454-65548880-dd90-11eb-9ccf-a090aec3dfae.png)

In `getter` we get the error:

```
Expression of type "TYPE_T@data" cannot be assigned to return type "TYPE_T@data"
  Type "TYPE_T@data" cannot be assigned to type "TYPE_T@data"
```

In `setter` we get the error:
```
Property setter value type is not assignable to the getter return type
  Type "TYPE_T@data" cannot be assigned to type "TYPE_T@data"
```

**Comment by erictraut** [comment]
You are using type variables incorrectly in this example. A type variable needs a specific scope — either a class, a function or a type alias. In your case, you are not defining the type variable at the scope of your class, so it's being interpreted as a function-level type variable. But then you're storing the value in the class's `_data` instance variable. The type variables used in the getter and setter have nothing to do with each other; they are completely independent type variables because they each have their own scope.

To make this work, you should do one of the following:
1. Make the class generic so the type variable has meaning at the class scope.

```python
class Parent(Generic[TYPE_T]):
    @property
    def data(self) -> TYPE_T:
        return self._data

    @data.setter
    def data(self, value: TYPE_T):
        self._data = value
```

2. Use a union rather than a type variable. 

```python
TYPE_T = Union[int, float]

class Parent:
    @property
    def data(self) -> TYPE_T:
        return self._data

    @data.setter
    def data(self, value: TYPE_T):
        self._data = value
```

**Comment by vishwa-raj** [comment]
@erictraut I couldn't use 2. because of the reason stated in the other comment: https://github.com/microsoft/pylance-release/issues/1526#issuecomment-874197517

I fixed the code with 1.
There were other such properties as well so had to add different type variables for all of them and make the class generic for all of them.

Thanks for the solution.
