### ISSUE TITLE
Diagnostic check for instance variables that are not initialized in constructor

### ISSUE THREAD

**Issue by jtlapp** [microsoft/pylance-release#1552]
I don't know if this is a bug or a feature, but pylance reports no errors for the following code, while mypy helpfully reports `Cannot determine type of "children"`:

```
from __future__ import annotations
from typing import Optional

class Entry:
    def __init__(self, name: Optional[str]):
        self.name = name
        self.childrn: Optional[list[float]] = None

    def add_child(self, child: Entry) -> None:
        if self.children is None:  # mypy errors here
            self.children = ["str"]  # pylance is okay with this
        else:
            self.children.append("str")
```

This really is the kind of thing I'd expect a type checker to catch. I'd like to keep mypy turned off so I can use cyclic types. Am I misunderstanding something about pylance?

**Comment by erictraut** [comment]
You've misspelled `childrn` in the constructor, so `children` is a different instance variable that has no type annotation, and its type must be inferred. Pylance's type inference techniques are more sophisticated than mypy's. In this particular case, it's inferring the type of `self.children` to be `list[str]` because it is assigned that type.

**Comment by jtlapp** [comment]
Thank you. That explains it, and yet I hate this. I'll need to use mypy as well.

Is there a switch that makes pylance require all member variables be declared in `__init__`?

**Comment by erictraut** [comment]
The fact that mypy reported an error here is just by chance. It's not even reporting the correct error. The real error — the one that would be manifest at runtime — is that you're accessing an unbound instance variable. Mypy doesn't track unbound variables at all. Pylance does, but it can do so only within an execution context (e.g. within a function). It can't track execution flow across functions because function execution order cannot be determined statically. So you happen to get lucky here that mypy happens to be unable to infer the type, and it's emitting another false-positive error.

There is no switch that requires all member variables to be declared in `__init__`. I don't think that would be very useful in the vast majority of Python code bases. It's unfortunately idiomatic to create new instance variables in methods other than the constructor. I suppose we could consider adding such a check, but it would be useful only for those who want "super super strict mode".

**Comment by jtlapp** [comment]
I see. Thanks for the further explanation. I'd like to suggest that this feature would be useful to all those coming from statically-typed languages who expect this sort of behavior. Right now, pylance is the only reason I'm considering doing work in Python. I like type checking partly for its ability to find bugs such as these, and partly for its help with refactoring. In my case, I was actually refactoring code and discovered that changing the name of a member variable in `__init__` broke no type checking. This is my trial run, and I so love the Python syntax that I want it to work, but I'm not yet convinced that I can get sufficient type support in Python.

Put another way, such a switch would enable developers who prefer statically-typed languages to allow themselves to work with Python. It could bring many more devs into the Python fold.

**Comment by jtlapp** [comment]
Should I create a new post for a feature request, being more concise about the proposal?

**Comment by erictraut** [comment]
No need to create a new feature request. We can use this issue to track it. I'll change the title accordingly.

I think your idea has merit.

I think I'll prototype it and try it on some Python code bases that are more strictly typed. That will help inform how many false positives versus actual bugs it finds.

**Comment by jtlapp** [comment]
Thank you so much! I'm looking forward to trying it.

**Comment by erictraut** [comment]
Turns out we discussed this a few months ago. See this issue: https://github.com/microsoft/pyright/issues/1924. I dusted off the code that I had written when I explored that. As I mentioned in the other issue, this diagnostic isn't going to be useful for most Python code bases because there are too many legitimate cases where instance variables are not initialized in the constructor.

But this has now come up enough times (once in a mypy issue, once in a pyright issue and now in a pylance feature request) that I think it's worth including. I've added a new diagnostic check called "reportUninitializedInstanceVariable" that can be enabled optionally. It's off by default, even in strict mode.

**Comment by jakebailey** [comment]
> It's off by default, even in strict mode.

The commit has this the other way around, it seems: https://github.com/microsoft/pyright/commit/2156f2eb73ecf918dd75c787a2463420911b2b07#diff-7bc0b8aef76656a15cbcfa1c3ab7294cedf52638fdd62d83fd6e41be5a9dc498R533

(and other lines)

**Comment by erictraut** [comment]
Thanks for catching that. I think this happened during the rebase that I did immediately before pushing to the remote repo. 

 -Eric

**Comment by jtlapp** [comment]
@erictraut, I have your mods installed and working in a pyright extension, with pylance disabled. Thank you so much! I'll let you know if I encounter any issues.

**Comment by jakebailey** [comment]
Unless I'm mistaken, I think that this was implemented but not closed.
