### ISSUE TITLE
Feature Request: @lru_cache overriding a method not raising reportIncompatibleMethodOverride if args and return is correct

### ISSUE THREAD

**Issue by TheCatSaber** [microsoft/pylance-release#1580]
(This is a feature request as the current behaviour is technically correct).

Code example:

```python
from functools import lru_cache
class Factorial:
    def factorial(self, n: int) -> int:
        if n == 0 or n == 1:
            return 1
        else:
            return n * self.factorial(n - 1)


class FactorialLRUCache(Factorial):
    @lru_cache
    def factorial(self, n: int) -> int:
        return super().factorial(n)
```

Current behaviour (on strict typing):

Pylance underlines the whole function of `FactorialLRUCache.factorial`, saying that "factorial" overrides method of same name in class "Factorial" with incompatible type "_lru_cache_wrapper[int]"Pylance(reportIncompatibleMethodOverride).

Suggested behaviour:

Pylance is fine with this - there could be a setting to enable to fix this.

Use case:

Like here, comparing speed of function with and without caching.

**Comment by erictraut** [comment]
Because of the the way `@lru_cache` is defined in the typeshed stubs, pylance would have no way of knowing that the overloaded method is compatible with the original. Given the information provided, pylance is correct in flagging this as incompatible.

There is a possibility that the `lru_cache` method could be annotated in a better manner within the typeshed stub using PEP 612 (ParamSpec) support, but not all type checkers provide support for `ParamSpec` at this time.

The `reportIncompatibleMethodOverride` check is not on by default. You can choose to disable it for your project or on a per-file basis (using a `# pyright: reportIncompatibleMethodOverride=false` comment), or you can suppress that one instance of the error using `# type: ignore`.

**Comment by TheCatSaber** [comment]
I looking at PEP 612, it does seem like `lru_cache` could be annotated in this way. Guess we have to wait for 3.10.

I've used `# type: ignore` in my project. Up to you to decide what to do with this issue.

**Comment by jakebailey** [comment]
`lru_cache` is defined in typeshed in stubs, which are free to use newer features without waiting for Python releases. typeshed already uses `ParamSpec` in at least one place, `contextlib`.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
