### ISSUE TITLE
Dataclass type hints missing unless used as a decorator

### ISSUE THREAD

**Issue by unilatinary** [microsoft/pylance-release#1582]
<h3> Environment data </h3>

-   Language Server version: 2021.7.4
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.6.9
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic
<h3> Code example</h3>

```python
from dataclasses import dataclass

@dataclass
class A:
    a: str

A()  # Argument missing for parameter "a", as expected

...

class B:
    b: str
B = dataclass(B)

B()  # No squiggle for missing argument, no type annotations at all

# B.__anotations__ == {'b': str} as expected when evaluated, but not reported by Pylance on hover
```
This is unexpected behaviour as per PEP 3129 both forms ought to be identical

Below is my use-case, is there a work around?
```python
class CMeta(type):
    def __new__(*args):
        cls = type.__new__(*args)
        cls = dataclass(cls)
        return cls

class C(metaclass=CMeta):
    c: str

class D(C):
    d: str

D()  # Also missing type annotations
```

**Comment by erictraut** [comment]
This is intended behavior. You need to use `dataclass` as a decorator because it takes arguments that must be statically understood. Mypy (another Python type checker) has the same limitation.

The workaround is to use `dataclass` as a decorator as it was intended in PEP 557.

[This type checking extension](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md) may also be of interest to you.
