### ISSUE TITLE
No autocomplete suggestions inside braces in f-strings

### ISSUE THREAD

**Issue by ridho9** [microsoft/pylance-release#160]
## Environment data

-   Language Server version: 2020.7.3
-   OS and version: Arch Linux
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3

## Expected behaviour

You get usual autocompletion inside braces in f-string (e.g `f"{here}"`).

## Actual behaviour

No autocompletion.

**Comment by erictraut** [comment]
Thanks for the bug report.

I'm not able to repro the problem. Perhaps there are additional steps I need to do to repro?

![Screen Shot 2020-07-22 at 10 14 54 AM](https://user-images.githubusercontent.com/7040122/88207128-320efd00-cc04-11ea-8420-6ec9ab6d5563.png)

Note that auto-completions won't work if you have no closing brace because the text at that location would be considered part of a string literal, not a replacement expression. Perhaps that explains the behavior you're seeing?

![Screen Shot 2020-07-22 at 10 16 18 AM](https://user-images.githubusercontent.com/7040122/88207268-65ea2280-cc04-11ea-9ef4-3ee29342c9db.png)

**Comment by ridho9** [comment]
![image](https://user-images.githubusercontent.com/20168159/88209420-e3517980-cc7c-11ea-93f6-4b7cb708ee17.png)
![image](https://user-images.githubusercontent.com/20168159/88209440-eba9b480-cc7c-11ea-8130-27029f755a9b.png)

These are some screenshots of the issue.

**Comment by erictraut** [comment]
Could you confirm that Pylance is the selected language service? If you go to the Output tab and choose "Python Language Server", do you see a log statement at the top that says something like `Pylance language server 2020.7.3 (pyright 5004efe5) starting`?

I've tried to replicate your code, and it's working as expected for me.

![Screen Shot 2020-07-22 at 10 54 24 AM](https://user-images.githubusercontent.com/7040122/88210885-b6b04a00-cc09-11ea-99aa-87dacfa3ad88.png)

**Comment by ridho9** [comment]
After taking a look at `Python` extension output, it does try to load the Pylance, but fails because an exception that said something around the line of 
```
Error 2020-07-23 01:05:08: Failed to ensure language server is available, Class name = f, completed in 76ms, has a falsy return value, Arg 1: <Uri:/home/rid9/.config/Code - OSS/User/settings.json>, Return Value: undefined [Error: You may only use the Pylance extension with Visual Studio Code, Visual Studio or Xamarin Studio software
to help you develop and test your applications.
```
I'm using the open source build package of vscode that available on the archlinux repo (`community/code`). It might be the culprit?

**Comment by savannahostrowski** [comment]
Hey @ridho9 !

Thanks for reporting this. You're correct. The issue here is that Pylance is not designed to run on unofficial builds of VSCode. We're looking into making this more obvious and improving the error messaging.

**Comment by ridho9** [comment]
Ah I see, that's a shame then. Thanks for responding!
