### ISSUE TITLE
Function named constructor breaks linting.

### ISSUE THREAD

**Issue by bijij** [microsoft/pylance-release#1618]
Having a function named `constructor` seemingly breaks linting, is pylance thinking this is a keyword?

## Environment data

-   Language Server version: 2021.7.6
-   OS and version: Win 11
-   Python version (& distribution if applicable, e.g. Anaconda): N/A but 3.9

## Expected behaviour

Nothing would happen.

## Actual behaviour

![image](https://user-images.githubusercontent.com/8677174/127402982-30733586-73c9-4ba1-abe3-a0405f0e350c.png)

## Code Snippet / Additional information

```py
def constructor():
    ...
```

**Comment by jakebailey** [comment]
I can reproduce this; might be related to the recent parser change to disallow certain keywords as attribute changes, but those parts of the parser should have been separate.

**Comment by jakebailey** [comment]
The fix for keywords in attribute accesses exposed another bug.

https://github.com/microsoft/pyright/commit/d9a66af63ca56a02b4d9f1cbcc6f0d4973c35736#

The old code disallowed specific keywords, then converted the others to identifiers. Now, it bans all keywords, which revealed that the tokenizer was accessing an object with the string "constructor", which returns the JS object constructor, rather than failing. I'm preparing a fix.

**Comment by jakebailey** [comment]
We've just released a hotfix (2021.7.7) which should fix this. Thanks for the issue!
