### ISSUE TITLE
subtraction of numpy.ndarrays results in incorrect NoReturn type

### ISSUE THREAD

**Issue by bcolloran** [microsoft/pylance-release#1619]
<h3> Environment data </h3>

-   Language Server version: 2021.7.5
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.9.5, miniconda 4.10.3
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

In the following python file, only the function `fail()` should have a type error; the numpy ndarray type should be closed under `+, * ,  /, -`, and none of the other functions in the following code should have any errors:

```python
import numpy as np

def add() -> np.ndarray:
    a: np.ndarray = np.arange(10)
    b: np.ndarray = np.arange(10)
    return a + b

def mult() -> np.ndarray:
    a: np.ndarray = np.arange(10)
    b: np.ndarray = np.arange(10)
    return a * b

def div() -> np.ndarray:
    a: np.ndarray = np.arange(10)
    b: np.ndarray = np.arange(10)
    return a / b

def sub() -> np.ndarray:
    a: np.ndarray = np.arange(10)
    b: np.ndarray = np.arange(10)
    return a - b

def fail() -> np.ndarray:
    return 45
```

Running this file through mypy on the command line confirms this -- only one error:
```
np_subtraction_NoReturn.py:29: error: Incompatible return value type (got "int", expected "ndarray[Any, Any]")
Found 1 error in 1 file (checked 1 source file)
```

<h3> Actual behaviour </h3>

Subtracting two ndarrays gives a `NoReturn` with the following error:

```
Expression of type "NoReturn" cannot be assigned to return type "ndarray[Unknown, Unknown]"
  "NoReturn" is incompatible with "ndarray[Unknown, Unknown]"PylancereportGeneralTypeIssues
```
![image](https://user-images.githubusercontent.com/2380975/127402967-4724428c-46ba-4d5a-a812-de809c81a0f2.png)

hovering on `a-b`
![image](https://user-images.githubusercontent.com/2380975/127404754-e7ff720f-c39f-42bc-ba43-a94116b753bc.png)

**Comment by jakebailey** [comment]
What version of numpy are you using? More recent versions have type annotations, and type checking with older versions is very likely to behave poorly.

**Comment by bcolloran** [comment]
Hi @jakebailey, I'm on numpy 1.21.0 (latest on pypi is 1.21.1), so I think I should be up to date enough that that isn't the cause of the issue. And, as I mentioned, when I run this little script through mypy I don't get any error with subtraction, which also suggests to me that it's not a numpy version problem. Please let me know if you need any other info to investigate this!

**Comment by erictraut** [comment]
You are annotating the variables `a` and `b` with `np.ndarray`. `np.ndarray` is a generic type that takes two type arguments, but you are omitting both of them. By the rules of PEP 484, omitted type arguments are supposed to be interpreted as `Any`.

The type stub that ships with numpy contains the following overload for the `__sub__` method:
```python
    def __sub__(self: NDArray[Any], other: _NestedSequence[Union[str, bytes]]) -> NoReturn: ...
```

I'm not familiar enough with numpy to say why they have annotated the return type as `NoReturn` in this case. That looks suspect to me because it implies that the implementation either enters an infinite loop or always raises an exception in this case.

In any event, you can avoid the use of this overload if you avoid using `Any` for the type. You can do this by simply deleting the type annotations for `a` and `b`, since the type checker can properly infer the generic type in this case.

**Comment by jakebailey** [comment]
Incredibly, they really do have `NoReturn` for these operators on the first overload. We hit this because if we don't match an overload, we pick the first one, I think. I don't think that's what mypy does, but I haven't tested.

https://github.com/numpy/numpy/blob/2f782a2f1afa1b25ffacb3ca1ffdbbab0abc1504/numpy/__init__.pyi#L2270

**Comment by erictraut** [comment]
> We hit this because if we don't match an overload, we pick the first one, I think.

No, that's incorrect. We generally use the first overload that matches. (I say "generally" because it's a bit more complicated if some of the argument types are unions.) If no overloads match, we report an error. In this case, the first overload matches because of the `Any` type argument used in the argument.

**Comment by jakebailey** [comment]
Ah, my mistake.

I was thinking of this mypy behavior, where if you call an overloaded function and nothing matches, it gives you `Any`: https://mypy-play.net/?mypy=latest&python=3.10&gist=c2140e98625318f0005542193960c79c

(whereas we pick the first overload, which has always felt odd to me given it's usually the narrowest option)

**Comment by jakebailey** [comment]
These `NoReturn`s were added in https://github.com/numpy/numpy/pull/18128; I'm not really sure I understand why.

**Comment by erictraut** [comment]
> if you call an overloaded function and nothing matches, it gives you Any

Mypy generates an error if no overloaded functions match. 

You're probably thinking of this rule, which mypy implements but pyright doesn't:

> ...if multiple variants match due to an argument being of type Any, mypy will make the inferred type also be Any.

I've been reluctant to implement this because it adds complexity to the mental model and I think it will create more problems than it solves. In any case, it applies only when arguments contain `Any`, so the simple workaround is to provide proper types as input.

**Comment by jakebailey** [comment]
> You're probably thinking of this rule

Yes, I misspoke!

**Comment by bschnurr** [comment]
Looks fixed on latest numpy pre-release https://github.com/numpy/numpy/releases/tag/v1.22.0rc1
