### ISSUE TITLE
attrs factory parameter gives "Fields without default values cannot appear after fields with default values" error

### ISSUE THREAD

**Issue by craigholm** [microsoft/pylance-release#1627]
-   Language Server version: 2021.7.7
-   OS and version: Windows 10 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6 64-bit
-   attrs version: 21.2.0

With the attrs module, and a class where a field with a factory parameter follows one with a default value, Pylance reports "Fields without default values cannot appear after fields with default values."

According to the documentation for attrs, the factory parameter is syntactic sugar for default=attr.Factory.  The two classes defined below are equivalent, but Pylance flags C1.field2 as having the error. (https://www.attrs.org/en/stable/examples.html#defaults)

Mypy 0.910 does not report any errors in this code.

```python
from typing import Any

import attr

@attr.s(auto_attribs=True)
class C1:
    field1 : int = 0
    field2 : list[Any] = attr.ib(factory=list)

@attr.s(auto_attribs=True)
class C2:
    field1 : int = 0
    field2 : list[Any] = attr.ib(default=attr.Factory(list))
```

**Comment by erictraut** [comment]
This is expected behavior. Mypy has special knowledge about `attrs` built in. Pylance doesn't have special-case knowledge of any third-party libraries, and we don't plan to add any.

We have made some accommodations for attrs and pydantic through [this specification](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md), which we are looking to make part of the Python typing standard. But there are areas where `attrs` behavior differs from the built-in `dataclass`, and we are not able to accommodate all of these special behaviors. See [this section](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#attrs) for details. There are known workarounds for most of these limitations if you are interested in using attrs with pylance.

**Comment by jakebailey** [comment]
I know we don't necessarily want to add any library specific functionality if we can achieve it via proper typing spec improvements, but I think there is still work to be done to better support attrs as the current coverage doesn't always meet user expectations (and I don't think it's true that we have no plans to try and work on handling specific libs as a whole either).

This one in particular is a problem because the diagnostic is emitted regardless of the type checking level, so anyone using attrs with code that happens to fall the bucket of an unsupported usage ends up with a message that can't be dismissed except via `# type: ignore`, in addition to it functionally not working as expected (which is another problem that would have happened before transforms anyway).

**Comment by jakebailey** [comment]
@erictraut mentioned that this has been fixed for a while, and pasting the above code into my editor no longer shows the errors from the original issue, though it does seem to fail for a new reason:

![image](https://user-images.githubusercontent.com/5341706/131739712-73db514a-d3a9-4926-a860-5c123868a768.png)

**Comment by jakebailey** [comment]
Their overloads are:

```
    @overload
    def Factory(factory: Callable[[], _T]) -> _T: ...
    @overload
    def Factory(
        factory: Callable[[Any], _T],
        takes_self: Literal[True],
    ) -> _T: ...
    @overload
    def Factory(
        factory: Callable[[], _T],
        takes_self: Literal[False],
    ) -> _T: ...
```

I would have thought it would match the first one, since `list` is a callable that can take nothing and returns `list`. I can't reproduce it if I extract out `Factory`; I'll make a new issue.
