### ISSUE TITLE
"open" is not defined

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/pylance-release#1640]
I try to monkey patch `open`, but I got a `"open" is not defined` error with this code

```python
def open_stub(*args, **kwargs): ...

class A:
    def f(self):
        open_builtin = open
        open = open_stub
        ...
        open = open_builtin

```

![图片](https://user-images.githubusercontent.com/24759802/128022216-d4b0e2f6-6188-4102-ae7f-df93c7f7e4c8.png)

But this code has no error

```python
def open_stub(*args, **kwargs): ...

open_builtin = open
open = open_stub
...
open = open_builtin
```

## Environment data

-   Language Server version: 2021.7.7
-   OS and version: Win10 2004 x64
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9 from MS Store

## Logs

I think logs are not needed, unless you team can't reproduce.

**Comment by erictraut** [comment]
If you run these two pieces of code in the Python interpreter, the first one will generate a runtime exception if you call `f` because the method refers to a local symbol `open` prior to initializing it. That is consistent with the error Pylance is reporting to you. You can fix this by explicitly importing builtins or renaming `open` to some other symbol within the global scope.

```python
import builtins

class A:
    def f(self):
        open_builtin = builtins.open
```
```python
open_builtin = open

class A:
    def f(self):
        open = open_stub
```

In the second example, the code runs without an exception because you are in the global (module-level) scope, and `open` refers to the symbol provided by the builtins module.

**Comment by imba-tjd** [comment]
Thanks for filling me in! I understand now.
