### ISSUE TITLE
Support inline type annotations for any expression?

### ISSUE THREAD

**Issue by runapp** [microsoft/pylance-release#1648]
Recently I found it sometimes necessary to "hint" or "force" pylance to treat an expression as some type, to get correct IntelliSense suggestions. For simple cases, usually I can do that with a temporary variable like this:

```python
a:E = A.B.C.D()
a.X()
```

But sometimes type `E` is hard to write out, e.g. `C.D()` is some method defined in super-super-base class of `C`, and copying type annotation of the original method would not be so easy. Or I'm just to lazy to take apart a long chain call and insert some variables between them.

In #396 I see the suggestion to use typecasting. But it also brings some runtime overhead and (more important) also breaks the whole chain call experience. In #765 I found that adding stub classes can help if the original `A.B.C` has support for that, but not in common situations. I've also got the idea of writing `.pyi` files but it seems to be more complicated, and suits better for separate packages/modules rather than small code lines.

So which would be the optimal way for a non-intrusive, inline type annotation for an expression?

PS: If someone is interested in when the auto type inference is out of work, one example is in `tornado`, accessing a custom field of instanced `tornado.web.Application` in handlers. I don't know if there's a way to let the handlers know that its parent is of some specific `MyApplication` type, rather than the tornado one. Anyway to my mind it's always better to have the ability to annotate any expression, even if opted-out, to make writing Python the dynamic-type language easier.

**Comment by erictraut** [comment]
A type annotation is a way to declare the type of a parameter or variable. The job of a type checker is to verify that any value assigned to an annotated variable matches its declared type.

Expressions don't have type annotations because their types are determined by the rules of the type system. For example, with the expression `A.B.C.D()`, the types of `A`, `B`, `C`, and `D` are used to determine the resulting type of the expression.

In the example above, you are declaring that the type of the variable `a` must be an instance of class `E`. If you enable the type checker, it will emit an error if it determines that the type of `A.B.C.D()` is incompatible with `E`.

You can override the calculated type of an expression by using the `typing.cast` call. It has very low runtime overhead because it simply ignores the first argument (which corresponds to the type) and returns the second argument (which is the expression you are casting).

You may find [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md) useful to understand the core concepts associated with type annotations and the Python type system.

**Comment by runapp** [comment]
I know that the main purpose of PEP484 and some following PEPs is to allow static type-checker to do their work. But as I mentioned above IntelliSense needs the accurate type. In the following example, `self.application.conn` is marked as type `Any`, which is already the best place a dynamic type linter can achieve. However, IntelliSense just won't work.
 
I agree with you that `typing.case` is the official and "right" way to do what I want. But it will write like
```py
typing.cast(sqlite3.Connection, self.application.conn).execute("SELECT line FROM words")
```
which is a bit too long. And sometimes it's not so easy to determine the correct type of that variable. (Though we might add a feature to "Copy Type of Selected Variable" to make it easier?)

<details>
<summary> `test.py` : An example that IntelliSense is unable to give hint</summary>

```python
import sqlite3
import tornado.web


class MyApplication(tornado.web.Application):
    def __init__(self):
        tornado.web.Application.__init__(self, [('/', TestHandler)], debug=True)
        self.conn = sqlite3.connect("words.db")


class TestHandler(tornado.web.RequestHandler):
    def get(self):
        self.write('\n'.join(x[0] for x in self.application.conn.execute("SELECT line FROM words")))


def main():
    http_server = tornado.httpserver.HTTPServer(MyApplication())
    http_server.listen(8000, '127.0.0.1')
    tornado.ioloop.IOLoop.instance().start()


def initdb():
    c = sqlite3.connect("words.db")
    c.cursor().execute("CREATE TABLE IF NOT EXISTS words (line TEXT)")
    c.cursor().execute("INSERT INTO words (line) VALUES ('hello'),('world'),('!')")
    c.commit()
    c.close()


if __name__ == "__main__":
    main()
```

</details>

**Comment by jakebailey** [comment]
Type analysis and IntelliSense go hand in hand; the latter is using the information generated by the former, so I don't think this is a case where we're trying to tell IntelliSense one thing but it not participate in the type analysis.

If `self.application.conn` is Any, does `x: sqlite3.Connection = self.application.conn` not work? I would have expected it to be the new type and not give type errors because `Any` is assignable to anything, then you'd get the type you declared it as.

**Comment by jakebailey** [comment]
Looping back on this one (since it's been sitting in "waiting for user response" for a month); it occurs to me that all of the above assumes that `self.application` is of the more specific type `MyApplication`. You can actually just write:

```python
class TestHandler(tornado.web.RequestHandler):
    application: MyApplication
    def get(self):
        self.write('\n'.join(x[0] for x in self.application.conn.execute("SELECT line FROM words")))
```

This effectively narrows the type of the attribute down to the expected one; this passes type checking as `MyApplication` is assignable to `Application`, which is what `TestHandler.application` is typed to be. Doing this nets the following:

![image](https://user-images.githubusercontent.com/5341706/132417207-f1a5080c-1c80-414c-b70e-7ffdedd4052e.png)

No `cast` required.
