### ISSUE TITLE
No error on invalid `from` `import`

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/pylance-release#168]
Hi,

pylance doesn't show any error or warning when making erroneous `import`s in a `from` import` statement

Example
```python
from RealModule import NonExistent
```
No error will be shown for `NonExistent`...

Here is a screenshot of all types of imports with pylance underlining the erroneous imports with a yellow line.
![image](https://user-images.githubusercontent.com/41123800/88425616-a93bc100-cdbd-11ea-8ee3-7782c25a6a81.png)

OS: Ubuntu 20.04
Language Server: pylance
Pylance Version: 2020.7.3
VSCode Version: 1.47.2

## Edit.

I see now that if I set `"python.analysis.typeCheckingMode"` to `"basic"` (or `"strict"`) only then do I get the correct import errors as depicted in the following screenshot
![image](https://user-images.githubusercontent.com/41123800/88425938-40a11400-cdbe-11ea-94e3-94e26c24f95b.png)

**Comment by bschnurr** [comment]
I can't seem to repo on Pylance 2020.7.3 on windows. 
What version of Pylance are you running? You can verify Pylance is running correctly by checking out the output window under "Python Language Server".

**Comment by yankyhoffman** [comment]
Sorry I wasn't cleat in my post, I updated it with more details.

Also in my update I added what I found to fix the issue, however I still find it weird that it only showed errors on some of the erroneous imports and not on all.

**Comment by jakebailey** [comment]
The reason why this happens is because in the syntax `from foo import bar`, we know that `foo` has to be a module (and therefore can prove whether or not it exists or not), but we can't know if `bar` is supposed to be a module or a value inside of the module `foo`.

This means that if `bar` doesn't exist in `foo`, then from the type checker's point of view, it's a value with as unknown type, as it wasn't present when `foo` was accessed. We can't prove that `bar` was supposed to have been a module and squiggle it as such.

In the "off" type checking mode, we're trying to keep type checks to a minimum and lower the friction for users without much experience with type checkers. You can imagine a case where someone's using a library that's not properly typed (for example, numpy, which has many compiled functions we can't yet find) where these squiggles would be annoying or confusing in the "off" mode. If the user raises the level to "basic" or "strict", they are explicitly asking for type checking features, and they'll start to get warnings about potential problems.

Hopefully explains what's going on here.
