### ISSUE TITLE
Type check on list(Generator[]) with Union[]

### ISSUE THREAD

**Issue by esnahn** [microsoft/pylance-release#1689]
```
from typing import Union


def no_union(x: list[str]):
    pass


def with_union(x: list[Union[int, str]]):
    pass


g = ("what" + x for x in "abcde")
l = list(g)
no_union(l)
with_union(l)  # only error
with_union(list(l))

"""
Argument of type "list[str]" cannot be assigned to parameter "x" of type "list[int | str]" in function "with_union"
  TypeVar "_T@list" is invariant
    Type "str" cannot be assigned to type "int | str"
      "str" is incompatible with "int"
"""
```

In the code above, I failed to understand why `with_union(list(l))` works but `with_union(l)` doesn't, even though `l` is already a list, obviously.

**Comment by erictraut** [comment]
Lists are mutable containers, so you cannot pass a `list[str]` to a function that accepts a `list[int, str]` because that function might insert an `int` into the list and violate the original type. When you call `with_union` with a newly-constructed list, you are creating a copy of the original list, so there is no type violation.

If the functions `no_union` and `with_union` do not modify the contents of the list, you can annotate them to accept a `Sequence` rather than a `list`, and the type error will go away.

For more details about mutable and immutable containers, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#generic-types).
