### ISSUE TITLE
typechecking with Union should only need one match type not all

### ISSUE THREAD

**Issue by fenchu** [microsoft/pylance-release#1693]
## Environment data

-   Language Server version: v2021.8.1
-   OS and version: windows10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour
variable userid comes from:
```
def get_username_n_from_file(fname:str, n:int=0) -> Union[str, None]:
```
this can return `str|None`
but where this variable is used it needs to match `str|int`
should be enough with one type matching

```
mock_token = tools.passport.mock_logon_token(userid, duration=3600, facematch_level=7)
                                              ^^^^
```
because this is defined like:
```
def mock_logon_token(ssn:Union[int,str], duration:int=3600, facematch_level:int=7)->str:
```
It should be enough that one type matches aka str

I can work around it by allowing None on the parameter, but it defies the purpose :-)

## Actual behaviour

![variable-cant-be-null](https://user-images.githubusercontent.com/11349883/130061839-b025e6a0-64d1-4ca4-a267-8e86b1d75e0f.jpg)

**Comment by erictraut** [comment]
The behavior you're seeing is correct. You are attempting to assign a value of type `str | None` to a variable that is declared as `str | int`. All values of a union need to be compatible with the use. The type checker is telling you that if `get_username_n_from_file` returns a `None`, you will violate the type requirements of the `mock_logon_token` method. If this method is annotated correctly, then you have a bug in your code because it doesn't properly deal with this situation.

**Comment by fenchu** [comment]
typing.Union() means any of the type is accepted.

**Comment by erictraut** [comment]
When a value is assigned, there is both a source and a destination. For example, in the statement `a = b`, `b` is the source, and `a` is the destination. In the case of call expressions, the argument within the call expression is the source, and the parameter defined by the target function is the destination. 

When a destination has a union type, the source can be a subset of the destination type — any subset is accepted in that case. When a source has a union type, all subtypes must work.

For example, if you declare that `a` is type `int`, that means any attempt to assign a value that is not an `int` should result in a type violation error. If you attempt to assign a value `b` that is type `int | None`, that will violate the type system because `None` isn't assignable to `int`. Now, if you reverse those types and declare that `a` accepts `int | None`, it's fine to assign an `int` to it. It's also fine to assign a `None` to it.

I hope that helps clear up the confusion. If you want more details about how the union type is supposed to work, I recommend reading PEP 483 and 484.
