### ISSUE TITLE
Bug in Pylance's IntelliSense

### ISSUE THREAD

**Issue by Unknown273** [microsoft/pylance-release#1699]
Issue Type: <b>Bug</b>

I am a beginner to Python programming and recently started coding in Python with Visual Studio Code. Today, as I was learning about the Python's "json" package, I found a bug in the in the Pylance's IntelliSense. The "json" package has a method called "json.loads()" which parses the json code in to a Python dictionary. Since this dictionary is a object, the IntelliSense gives you hints about all the available methods and properties. But this didn't happened as expected for me. Here's my scenario, I had my json code as a string in variable called jsonCode and then paresed it and stored the resul with this line
"someData = json.load(jsonCode)"
Then, if do something like "someData." the IntelliSense doesn't give hints about the available functions or attributes.
However, if I change the value of "myData" to a hard coded Python dictionary, then it works and gives you the hints.
This is really troubling me in exploring Python with IntelliSense.
Please fix this issue as soon as possible.

Extension version: 2021.8.2
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (6.54GB free)|
|Process Argv|--crash-reporter-id 79477b55-3597-4aa7-bcd1-15326f638757|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
javagetstartedc:30351792
vsdyn420:30354109

```

</details>

**Comment by CodeCrazy-ywt** [comment]
No, the return type of method `loads` depends on the string passed into, for example:
```python
import json

json.loads('1')  # int
json.loads('1.0')  # float
json.loads('true')  # bool
json.loads('[1, 2, 3]')  # list
json.loads('{"1": 1, "2": 2, "3": 3}')  # dict
```

**Comment by Unknown273** [comment]
https://github.com/microsoft/pylance-release/issues/1699#issuecomment-902689503
Thank you very much for helping. Actually I learnt something new with your reply but, that's not my problem. I think I didn't describe the problem properly in the complain. Let me share the Code such that anyone can try it themselves.

Code: 
import Jason

jsonCode = '''
{
    "name": "Yusuf Kazi",
    "Hobbies": "Programming",
    "isABeginner": True
}
'''

**Comment by erictraut** [comment]
Pylance uses type information to inform completion suggestions (aka Intellisense). If you right click on the `loads` symbol and choose "Go To Declaration", you'll see the type information that Pylance is using in this case.

The `json` module is part of the Python standard library, and the type information for the standard library comes from the Python community — in particular, from the [typeshed github repo](https://github.com/python/typeshed).

In this particular case, the function `json.loads` is annotated with a return type of `Any`, which means that the return type cannot be determined statically. It's known only at runtime (when you run the code in the interpreter) because it varies depend on the input values.

If you happen to know the return type, you could use a type declaration like this:
```python
result: dict[str, Any] = json.loads(jsonCode)
# Pylance knows that `result` is a dict at this point
print(result.values)
```

By doing so, you are declaring that the variable named `result` has a dictionary type that is indexed by strings.

If you are using `json.loads` to parse arbitrary input (e.g. data read from a file), then your code should not assume the return type. It could be a dictionary, a list, a string, etc. In that case, you would need to perform dynamic (runtime) checks to determine its type.

```python
result = json.loads(jsonCode)
if isinstance(result, dict):
    # Pylance knows that `result` is a dict at this point
    print(result.values)
elif isinstance(result, list):
    # Pylance knows that `result` is a list at this point
    print(len(result))
```

**Comment by Unknown273** [comment]
https://github.com/microsoft/pylance-release/issues/1699#issuecomment-902818732

Ok
It works actually, 
But the answer is kinda difficult to wrap my head around it 😅
BTW, Thank you very much for your answer Mr. erictraut
