### ISSUE TITLE
Code is marked as unreachable, even though it isn't

### ISSUE THREAD

**Issue by VitorOriel** [microsoft/pylance-release#1701]
## Environment data

-   Language Server version: Pylance language server 2021.8.2
-   OS and version: Ubuntu 21.04 x64
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.5

## Expected behaviour

Code should not be marked as unreachable

## Actual behaviour

Code is marked as unreachable

## Code Snippet / Additional information

```python
class BaseReport(ABC):
    def write(self, results: List[Result]) -> NoReturn:
        self._header()
        self._results(results) # unreachable
        self._footer() # unreachable

    @abstractmethod
    def _header(self) -> NoReturn:
        pass

    @abstractmethod
    def _results(self, results: List[Result]) -> NoReturn:
        pass

    @abstractmethod
    def _footer(self) -> NoReturn:
        pass
```

**Comment by Questionsdenombres** [comment]
It seems that you are confusing "None" and "NoReturn".

If a function return type is "NoReturn", it doesn't mean that the function returns nothing (or None).
It means that it always raises an exception: hence the next line of code (if any) will never be reached unless the exception is catched by a try/exception.
The type checker understands that "self._header()" will raise an exception. Since it is not wrapped in a try/exception structure the next lines of code are understood to be unreachable.

The code will run perfectly but the typing is incorrect.
Solution: All of your methods should be typed as returning "None", not "NoReturn".

**Comment by VitorOriel** [comment]
> It seems that you are confusing "None" and "NoReturn".
> 
> If a function return type is "NoReturn", it doesn't mean that the function returns nothing (or None).
> It means that it always raises an exception: hence the next line of code (if any) will never be reached unless the exception is catched by a try/exception.
> The type checker understands that "self._header()" will raise an exception. Since it is not wrapped in a try/exception structure the next lines of code are understood to be unreachable.
> 
> The code will run perfectly but the typing is incorrect.
> Solution: All of your methods should be typed as returning "None", not "NoReturn".

Thanks so much for your reply! I'll fix it now.
