### ISSUE TITLE
auto imports from modules starting with capital are incorrectly placed above `__future__` imports

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pylance-release#1752]
![image](https://user-images.githubusercontent.com/57028336/131783778-e7ac6db3-02f6-4207-8c14-416b948219cd.png)
![image](https://user-images.githubusercontent.com/57028336/131783792-1106e720-f75f-4d5d-849c-dd133cd35eaa.png)
![image](https://user-images.githubusercontent.com/57028336/131783802-4b367a61-5bc6-43e5-8cc4-c0a3b66fc626.png)

**Comment by cdce8p** [comment]
Noticed this as well. The issue seems to  be two fold.
1. `__future__` imports are classified as `ImportType.Builtin`. This will lead to situations where other `builtin` modules are put in the same group when using `auto-import`. E.g., here for `dataclasses`. By default, `isort` would create separate sections for them: https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html
![Screen Shot 2021-09-10 at 11 23 36](https://user-images.githubusercontent.com/30130371/132832056-71c96673-82f8-4231-b835-9b0bc40f736a.png)
2. Any module is by default assigned to `ImportType.Builtin` even if it should be `ImportType.Local` or `ImportType.LocalRelative` instead. https://github.com/microsoft/pyright/blob/e804f324ee5dbd25fd37a258791b3fd944addecd/packages/pyright-internal/src/analyzer/importResolver.ts#L359-L361

**Comment by heejaechang** [comment]
@DetachHead I don't see it repro in the latest version. please re-open if it still happens with new repro.

**Comment by DetachHead** [comment]
yeah seems to be fixed now, thanks!
