### ISSUE TITLE
How to structure log without error - No parameter named "x"

### ISSUE THREAD

**Issue by markledwich2** [microsoft/pylance-release#1787]
I use the default python logger and provide structured parameters so that I can filter/search nicely in my logging system. 

However pylance reports problems that each of the parameters do not exist 
```python
log.info('hello {name}',  name='Mark')
```

Error shown:
`No parameter named "name"  (Pylance reportGeneralTypeIssues)`

Is there a way to avoid this without turning general type issues off?

**Comment by jakebailey** [comment]
The issue title and "error shown" don't align with the code sample; I'm assuming that the issue is that named parameter?

Assuming `log` is a `logging.Logger`, the stubs upstream in typeshed don't seem to indicate that they support arbitrary kwargs: https://github.com/python/typeshed/blob/master/stdlib/logging/__init__.pyi

Both `LoggerAdapter` and the top-level `info` function do have a `kwargs`, perhaps it was an oversight? The docs on `python.org` state that `kwargs` are supported.

**Comment by jakebailey** [comment]
The PR that changed it is https://github.com/python/typeshed/pull/5862, which claims that `Logger` doesn't support arbitrary keyword args, only the adapter.

**Comment by markledwich2** [comment]
Sorry, updated error to match code sample.  Arbitrary keywords currently work, i'm using a `seqlog`  logger which relies on them 
https://seqlog.readthedocs.io/en/latest/usage.html#overriding-the-root-logger

Is this a scenario they missed in that PR?

**Comment by jakebailey** [comment]
If I'm reading this correctly, this library patches the stdlib logger to add format string / kwargs support after the fact. That's an unfortunate bit of dynamic behavior; we assume that Logger is unmodified and its API matches the API declared in typeshed. I am a bit surprised this doesn't break other uses of the logger, given this changes the meaning of the strings.

It'd be more reasonable if this library instead gave a specific `SeqLogger` class or something to distinguish the APIs, not monkeypatch the standard library to behave differently...

**Comment by markledwich2** [comment]
OK, thanks for the information.
