### ISSUE TITLE
how to stub for WITHIN the module?

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#1788]
In #1785 I had a 2nd question where I though the issue would be connected but I begin to wonder there is another issue I was having trouble to grasp actually only with **"strict"** _Type Checking Mode_:

While it DOES work to have a `.pyi` stub file and have NO typing annotations in the `.py` (so things are py2/3 compatible) and then using your module: everything is nicely highlighted in the "user" module 👍🌈🤘 ...

When working INSIDE the "stubbed" module the type annotations from the stub are completely ignored?
Or am I doing something wrong?
How can I make this work? I mean you only need the annotations in ONE place right?

Again giving:
<details>
<summary>this example stub code</summary>

```py
import typing
import P4

def connect(workspace: str) -> P4.P4: ...

class Connection:
    _p4: typing.Optional[P4.P4] = ...
    _workspace: str = ...
    def __init__(self, workspace: str = ...) -> None: ...
    def __enter__(self) -> P4.P4: ...
    def __exit__(self, *args: typing.Any) -> None: ...

```
</details>

<details>
<summary>and this context class code</summary>

```py
import P4

def connect(workspace):
    p4 = P4.P4()
    p4.client = workspace
    return p4


class Connection(object):
    def __init__(self, workspace=None):
        self._workspace = workspace
        self._p4 = None

    def __enter__(self):
        self._p4 = connect(workspace=self._workspace)
        return self._p4

    def __exit__(self, *args):
        assert self._p4 is not None
        self._p4.disconnect()

```
</details>

I get highlights and declarations as `Unknown`. There are no highlights with "**basic**" Type Checking Mode but still the type is in fact not used (`No suggestions`).

![image](https://user-images.githubusercontent.com/218956/132596530-1e5cfe80-7d58-4afd-a50d-4cf93f630c9c.png)

**Comment by jakebailey** [comment]
It sounds like you're looking for #1238. Stub files don't propogate types back into their `.py` files.

In general, it's much preferred to just write the annotations in your `.py` file unless you have a really compelling reason not to (e.g. compiled code). Python 2 is defunct; I don't think it's worth the effort of maintaining a stub along side your code just for it, personally.

I'm going to close this as a dupe.

**Comment by erictraut** [comment]
A type stub is stand-in for a module, typically used in cases where the module is implemented in a language other than Python or in cases where the type information is being provided by someone other than the author of the module. A ".pyi" file is not applied to a ".py" file itself. Don't think of a type stub as a ".h" file in C++; rather, think of it like a ".d.ts" file in TypeScript.

If you are the author of a Python module and want to benefit from type checking within that module's implementation, you would use inline types rather than a separate companion stub file.

**Comment by ewerybody** [comment]
Thanks @erictraut ! Yeah but as I mentioned: We need our modules to be compatible to Python 2 AND 3 at the same time. Which is pretty doable! (but of course I'd also prefer to get rid of that requirement asap) 

On the other hand I find it pretty nice to **not** stuff the code with all that typing voodoo. It adds a LOT of noise and having it tucked away is a plus.

At the end this IS connected to #1785 as the type annotations from the stub do also not propagate into the member functions. Well I'll jump onto the #1238 issue then.

Thank you **both** for the in-depth explanations!!! 🙏 I can imagine its frustrating to do this over and over again.

**Comment by erictraut** [comment]
If you need to support older versions of Python, you have the option of using type comments rather than syntactic annotations.

```python
def foo(a, b):
    # type: (int, int) -> str
    return str(a + b)

c = [] # type: List[str]
```

One way to I like to think about type information is that it's like structured comments for your code that can be read not only by humans but also by tooling (linters, type checkers, IDEs, etc.). I've found that when people start to think about it from that perspective, they find that it's less objectionable to include it in the code. After all, it's hard to argue against better code comments. :)

**Comment by ewerybody** [comment]
Yeah True! We actually use this `:param type name: Description.` in the doc strings throughout our library. That once worked with other IDEs but it's deprecated or unused here right?
Is there a way to have a description along with **this** style of type comments?

**Comment by erictraut** [comment]
Docstrings make good documentation for humans, but they're almost never consistent, precise, or accurate enough for a tool to reason about them. Support for static type annotations was added to Python to address this limitation. If you use the `:param type name: Description` format, you can remove the `type` part from the docstring and move it to the code. I find that in most cases, the type by itself is sufficient in many cases to describe the parameter, so in our code base, we often omit the parameter-specific documentation in the docstring, at least for internal functions and methods.
