### ISSUE TITLE
basic Type Checking: generator in dict: No overloads for "__init__" ...

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#1790]
I'm on 1.60. And with the **Type Checking Mode** setting to **basic** and
writing a dictionary generator highlights with the message:

```
No overloads for "__init__" match the provided arguments
  Argument types: (Generator[list[str], None, None]) Pylance(reportGeneralTypeIssues)
(class) dict
```

Example code:
```py
line = 'NAME|a=2345|b=SDFdss sdfsdf|ignored|c=another'
parts = line.strip().split('|')
attrs = dict(p.split('=', 1) for p in parts if '=' in p) # < HERE
```

Is it because the length of the list cannot be determined? I mean this is working code. It even works with an empty string or only misses where there is no `=`

Given the proposed types I'm also unable to hack this into `builtins.pyi`. I know I shouldn't but well. I have no idea how that should look in there anyway :/

**Comment by erictraut** [comment]
The `builtins.pyi` type stub doesn't allow `Iterable[Iterable[str]]` to be passed as an input to the `dict` constructor. I don't know if this was an oversight or if it was intentional because it's not generally type safe. A type checker cannot determine that `Iterable[str]` always have a length >= 2, which is required in this case. 

From a type checking perspective, pylance is reporting the correct error here, so I don't think there's anything we can change to fix this.

I can think of a couple of workarounds:
1. You could report a bug in the [typeshed repo](https://github.com/python/typeshed) and see if the maintainers of `builtins.pyi` would be willing to entertain an update to the `dict` constructor overloads.
2. You could make a small change to your code to assist the type checker. 

Here's an example of a change that eliminates the error because it generates a sequence of tuples of size 2, and this is known to be safe for the `dict` constructor.
```python
attrs = dict(((x[0], x[1]) for p in parts if len(x := p.split("=", 1)) == 2))
```

**Comment by ewerybody** [comment]
Ah alright. I was thinking I was at the right spot because I read "Pylance" somewhere in the path of `builtins.pyi` ...
But yeah I'm sure they'd love the suggestion. :|  ..

Hacking this into the stub under `class dict` helps tho:
```py
    @overload
    def __init__(self, iterable: Iterable[Iterable[str]]) -> None: ...
```

I'll give it a try anyway. :)
