### ISSUE TITLE
How to stop Pylance to mark imports as can't be resolved

### ISSUE THREAD

**Issue by KickItLikeShika** [microsoft/pylance-release#1791]
How to stop pylance bothering about the imports and mark them as can't be resolved?
<img width="517" alt="Screen Shot 2021-09-09 at 2 18 01 PM" src="https://user-images.githubusercontent.com/54319724/132684431-9164cf67-2716-4228-8a2d-862bbb74fae2.png">
NOTE: Everything is working fine, and the packages are installed

**Comment by jakebailey** [comment]
If the code runs, then we should be able to resolve the imports.

You didn't fill out our bug template; we'd appreciate a full issue, instructions mirrored here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

I would also check the troubleshooting in general, which covers a number of ways that imports don't resolve. I would also verify that the packages that don't resolve are installed into the interpreter you've selected at the bottom left; it may not be the one you are using at your terminal.

**Comment by radoeka** [comment]
Having the same;



## Environment data



-   Language Server version: 2021.9.2
-   OS and version: openSUSE 15.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.13

## Expected behaviour

All modules are resolved.

## Actual behaviour

Module can't be resolved.  It shows reportMissingImports and linkes to:
https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules

![image](https://user-images.githubusercontent.com/2937666/133895608-ece9d504-ffbd-48e5-ad0b-ca183e98f385.png)

The code is stored in a python virtual environment.

```bash
python/hello1> pip show sqlmodel
Name: sqlmodel
Version: 0.0.4

python/hello1> which python3
~/.config/python/venv/sql/bin/python3
```

The code runs sucessfully

The python modules are installed in: ~/.config/python/venv/sql

I added this path as extra path to pylance:

![image](https://user-images.githubusercontent.com/2937666/133895743-acb266b9-663b-4417-9f58-2f7c7cf77184.png)

vscode is started from the virtual environment, and as such should have access to all the required environment variables.

**Comment by erictraut** [comment]
@radoeka, you likely don't have the correct interpret selected. Could you please fill out the bug template? It asks for logs, which are important to help diagnose issues like this.

**Comment by radoeka** [comment]
@erictraut I used the bug template, but left the logging part empty indeed. 

I set the logging to "Trace":

![image](https://user-images.githubusercontent.com/2937666/133897520-f8d39bc6-f631-4a04-8274-3c0286460781.png)

But I don't see any tracing anywhere.  Where to look for the tracing output?

**Comment by jakebailey** [comment]
The output is in the output window under the "Python Language Server" dropdown. You should be able to open it with the "focus output" command in the command palette, or in one of the top context menus.

**Comment by radoeka** [comment]
@jakebailey thanks for the directions.  It was still a challenge to find it, but in the end it worked out nicely.  

Find the log attached, [pylance.log](https://github.com/microsoft/pylance-release/files/7191264/pylance.log)  (I replaced my user name with 'user')

I hope that the log shines some more light on this.

The python binary to be used is the one in my virtual python environent: 
  /home/[user]/.config/python/venv/sql/bin/python3

However /usr/bin/python3 seems to be used.

Result with: Run python file from terminal:
![image](https://user-images.githubusercontent.com/2937666/133920667-6cb00a7b-096b-4588-a200-9f0aa2d7fa1d.png)

The environment variables that instruct python venv are available and set:
```bash
./snake-env
VIRTUAL_ENV = /home/<user>/.config/python/venv/sql
PATH = /home/<user>/.config/python/venv/sql/bin:/home/<user>/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin
```


For others that wonder where to find this information, two screenshots:

Command Pallette ([ctrl][shift][p]) or selection - command pallette:

![image](https://user-images.githubusercontent.com/2937666/133920437-0acb9138-91fe-40a0-99b3-62f3c334150a.png)

The output window:
![image](https://user-images.githubusercontent.com/2937666/133920455-4893ac4f-3e1a-4b2c-a1a0-ce3c7c7199d5.png)

**Comment by jakebailey** [comment]
Based on the above, it sounds like you don't have the right interpreter selected. At the bottom left, there should be a button to manage that; the terminal having a particular python doesn't imply that it's been selected

**Comment by radoeka** [comment]
@jakebailey terrific, that was it :1st_place_medal: 

Thanks for this!
