### ISSUE TITLE
first suggested auto import is invalid, doesn't take into account capitalization

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pylance-release#1816]
before:
![image](https://user-images.githubusercontent.com/57028336/133195202-b1e7e7ab-22ad-4682-a793-1a39335aa918.png)
after:
![image](https://user-images.githubusercontent.com/57028336/133195419-c45a5d36-d511-4a75-9f61-015856d684f6.png)
```py
class Foo(Enum):
    ...
```

**Comment by jakebailey** [comment]
This is currently working as intended, as we're trying to be helpful in offering similar terms, and `import enum` ends up being simpler than `from enum import Enum`, so we offer it first (assuming that the user will select the one they want). We don't know per-se which item is "valid", but it would likely be better to prefer exact matches.

**Comment by CodeCrazy-ywt** [comment]
However, `enum` is a module in the sample, which we **cannot** use here where we need to inherit from a module. I suggest that pylance to only show context-appropriate auto-import commands.

**Comment by CodeCrazy-ywt** [comment]
However, `enum` is a module in the sample, which we **cannot** use here where we need to inherit from a module. I suggest that pylance to only show context-appropriate auto-import commands.

**Comment by jakebailey** [comment]
See also #424 and #1557; auto-imports in general do not take any context into consideration.

**Comment by heejaechang** [comment]
we now put exact match (including upper/lower casing) at higher priority in add using list. so, the issue itself is fixed. 

but currently we don't have context aware-ness in completion so that part is still not done.

that being said, in this particular case, class A(__here) is type context where any type name can show up, so enum is valid name since user can write A(enum.Enum), so even if we improve features to context aware, enum will still show up since it is valid one to show.
