### ISSUE TITLE
Global import being ignored when importing parent or child module inside of a function

### ISSUE THREAD

**Issue by LanceaKing** [microsoft/pylance-release#1834]
<h3> Environment data </h3>

-   Language Server version: 2021.9.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.10
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

show syntax highlighting and hints of the global import.

<h3> Actual behaviour </h3>

import a child module inside of a function:

![image](https://user-images.githubusercontent.com/31365292/133892690-e7e78c1d-fd6e-40d7-ab0b-3883df833182.png)

import a parent module inside of a function:

![image](https://user-images.githubusercontent.com/31365292/133892738-dfa84d9a-c961-448e-8abf-b1ed4a520733.png)

<h3> Code Snippet / Additional information </h3>

```python
import librosa.display

def func():
    import librosa
    librosa.core.load()
    librosa.display.specshow()
```

```python
import librosa

def func():
    import librosa.display
    librosa.core.load()
    librosa.display.specshow()
```

**Comment by erictraut** [comment]
Python's import mechanism is complex and involves side effects in the form of global caching. That means the behavior of an import can depend on which imports were performed in the past within different scopes. 

Pylance does not attempt to model the temporal execution order of different scopes (doing so statically isn't possible), and it also doesn't attempt to model the temporal side effects of imports. If your program relies on these temporal side effects, it's likely to break in hard-to-debug ways if the import ordering changes, so it's reasonable to treat these as bugs.

With that background in mind, let's consider the code in your example.

When you import `librosa` within a scope, the symbol `librosa` is added to that scope's namespace, and the module loader populates the namespace of the `librosa` module. If you then import a submodule (e.g. `librosa.display`) within the same scope, a new symbol is not added to that scope's namespace because there's already a symbol called `librosa` within that namespace. However, you are guaranteeing that the module loader populates the `display` symbol within the `librosa` module's namespace. That makes it safe to access symbols within `librosa.display`.

Your samples involve two separate scopes — a module scope and a function scope. You are populating both scopes with a symbol `librosa`, but you are not importing the submodule in both cases. In your second sample, your code is relying on the temporal side effect that `librosa.display` was previously imported in another execution scope. So while this code will run, it's pretty dodgy, and the static analyzer is not able to able to guarantee the correct operation.

If you were to enable type checking mode, you'd see diagnostics that might help clarify what's happening here.

The best way to address this is to move both imports to the module level.

```python
import librosa
import librosa.display

def func():
    librosa.core.load()
    librosa.display.specshow()
```

If importing `librosa.display` is expensive and you want to defer its import until `func` is called, you can import both `librosa` and `librosa.display` within the function. If `librosa` was imported in another execution context in the past, importing it a second time within the function will have little or no runtime overhead, but it will eliminate the dependency on an implied temporal side effect.

```python
import librosa

# A use of librosa outside of function
print(librosa.version)

def func():
    import librosa
    import librosa.display
    
    librosa.core.load()
    librosa.display.specshow()
```
