### ISSUE TITLE
Pylance issue with autocomplete and popup information for ambiguous symbols

### ISSUE THREAD

**Issue by niander** [microsoft/pylance-release#1856]
<h3> Environment data </h3>

-   Language Server version: 2021.9.3-pre.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

_note: It may be easier to see the code sample below first_

I am not sure if Pylance does any runtime verification to disambiguate which class definition to use for autocomple and popup help. Nonetheless, I would expect to be able to at least see both definitions, select one, and then both popup and autocomple show me appropriate arguments.

<h3> Actual behaviour </h3>

While code navigation show me that there are two definitions for a class in two different files. When I try to call a method from a class (for instance the constructor `__init__`), it shows me help information and signature (and autocomplete for arguments) of just one.

In my case, the decision of which class is actually being used is in a try..catch for `SyntaxError` or `ImportError` (See code below).

<h3> Logs </h3>

_Not sure if any log would be relevant here, please let me know otherwise and I can add._

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

`models/__init__.py`
```python
try:
  from ._models_py3 import MyModel
except (SyntaxError, ImportError):
  from ._models import MyModel
```

MyModel in `_models_py3` has a `__init__` with different properties as arguments.
MyModel in `_models` has a `__init__` with one argument, `**kwargs`.

`run_my_code.py`
```python
import models
models.MyModel(
```
This shows me the MyModel definition from `_models.py` instead `_models_py3.py` even thought I am in Python 3 and in runtime that would be imported. I can't see both signatures in the popup not indicate to pylance while typing that I want help with autocompleting for the other definition instead.

**Comment by erictraut** [comment]
Pylance doesn't execute any Python code. It performs static analysis on the code. As such, it cannot predict dynamic behaviors like the one above. By default, it assumes that the last assignment "wins". In this case, that means it will use the `MyModel` definition from `._models` rather than from `._models_py3`.

You can use the `typing.TYPE_CHECKING` flag in a conditional to tell the static analyzer which version you would like it to assume. 

```python
if typing.TYPE_CHECKING:
  from ._models_py3 import MyModel
else:
    try:
        from ._models_py3 import MyModel
    except (SyntaxError, ImportError):
        from ._models import MyModel
```

or

```python
try:
    from ._models_py3 import MyModel
except (SyntaxError, ImportError):
    if not typing.TYPE_CHECKING:
        from ._models import MyModel
```

**Comment by niander** [comment]
Thank you for the clarification. While your suggestion seems appropriate, we don't always have the ability to alter the code we use. In this case, this is was auto generated by Autorest/Python.

Nonetheless, what about what I said in the expected behavior -- being able to select or indicate to pylance which definition I am using during autocomplete? Did it make any sense?

**Comment by jakebailey** [comment]
> Thank you for the clarification. While your suggestion seems appropriate, we don't always have the ability to alter the code we use. In this case, this is was auto generated by Autorest/Python.

I'm a bit confused by this point; if this is generated code you won't alter, then wouldn't that imply that you don't need auto-completion in the file, as you won't be editing it? Or are you seeing this carried through to another file?

(Another solution for this may be to have this code use `sys.version_info` to distinguish 2 from 3, maybe.)

> Nonetheless, what about what I said in the expected behavior -- being able to select or indicate to pylance which definition I am using during autocomplete? Did it make any sense?

If I'm understanding this correctly, you're trying to say that we should make it configurable which of the two declarations is the one that wins. That seems very specific to this case; in general, the code should be able to speak for itself.

**Comment by niander** [comment]
> I'm a bit confused by this point; if this is generated code you won't alter, then wouldn't that imply that you don't need auto-completion in the file, as you won't be editing it? Or are you seeing this carried through to another file?
> 
> (Another solution for this may be to have this code use `sys.version_info` to distinguish 2 from 3, maybe.)
> 

Well, the SDK is generated. But for the user, that is using the SDK and importing the models, it will still be showing autocomplete for wrong class definition in their code.

The `sys.version_info` seems interesting, does Pylance detect that?

> If I'm understanding this correctly, you're trying to say that we should make it configurable which of the two declarations is the one that wins. That seems very specific to this case; in general, the code should be able to speak for itself.

Not configurable but something like the code navigation. If I try to code navigate it will show me that here are two definitions for the class. However, when I start typing and open a parenthesis, I only see one definition that pylance selected arbitrarily.

What I am suggesting is that it would be cool to see during help pop-up or autocompletion that there are more than one definition and to be able to select from the pop-up which definition you are using right now. Then, autocomplete for that line of code will start suggesting arguments for the definition you selected. Alternatively, it would show to the user autocomplete options to all or a subset of possible definitions but in a way that they can differentiate.

**Comment by jakebailey** [comment]
All type checkers support `sys.version_info`, e.g.:

```python
import sys

if sys.version_info > (3,):
    from ._models_py3 import Model
else:
    from ._models import Model
```

![image](https://user-images.githubusercontent.com/5341706/134252075-58aed109-3517-4337-86b8-d3a6caff129d.png)

If you're in control of the SDK, this may be a better option than try/catching imports. But, `if TYPE_CHECKING` is also an option as well. The code I've written is subtly different, as the original code appears to do things like catching syntax errors, which means that old versions of Python 3 will run the code seemingly intended for Python 2.

I'm a bit confused because you said that you didn't have the ability to alter the code; if you're generating the code, you can have it emit the more-compatible code.

I will of course point out that Python 2 has been effectively dead for nearly 2 years now (even the Python extension is dropping it in their next release). Pylance and pyright have never supported Python 2 and we don't intend to. Best of all would to drop it and avoid these oddities, or write code that works for both, rather than having two nearly identical modules.

**Comment by niander** [comment]
> I'm a bit confused because you said that you didn't have the ability to alter the code; if you're generating the code, you can have it emit the more-compatible code.

Yes, my wording was confusing. I am sorry about that. I don't have the control over how the generation works but I can discuss options with the folks that have.

>I will of course point out that Python 2 has been effectively dead for nearly 2 years now (even the Python extension is dropping it in their next release). Pylance and pyright have never supported Python 2 and we don't intend to. Best of all would to drop it and avoid these oddities, or write code that works for both, rather than having two nearly identical modules.

I know, that is why I have first asked them if I could remove the generation of Python 2 models because our customers are only using Python 3. It is not configurable yet so I was wondering if this were a Pylance specific approach that could change. 

But, as you pointed out, using `sys.version_info` is more common and supported by type checkers. That is probably why such issue has never happened before with me while using other libraries that still support Python 2.

I should note however that up until now all Azure Management SDKs for Python are written like that. I am not sure about what others static python language analyzers do. Nevertheless, having a better experience with autocompletes for more than one definition while using autocompletion seems to be a good feature to have with Pylance.

_While writing this I wonder what happens when the static typing comes from a typeshed file and have @overloads_

**Comment by heejaechang** [comment]
@niander I am going to close this issue since there is nothing we, as static analyzer, can do. it must be done by code owner to use code constructs such as version_info that can be statically determined, any code that requires running code such as try/catch to know the result can't be used with a static analysis tool such as pylance.

...

typeshed also uses things like version_info to declare symbols for different versions/platforms. and assuming all arguments types are known statically, static analysis tool can figure out which overloads, a call expression is bound to.
