### ISSUE TITLE
Incorrect parsing Python r-string containing left parenthesis

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/pylance-release#1862]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-Intellicode-parsing-Python-r-s/1526869)._

---
The Intellicode parser seems to "introspect" Python r-strings, setting the semantics/coloring into a weird state when it sees a left parenthesis ("("). The code compiles and runs, but coloring through to the end of file is hosed. See attached screen shots for simple way to create and effects, also a work-around (which is only a slight kludge, but is a kludge).

Here is sample code that causes the problem:
    return r"""
        command: "create"i _WS "table"i _WS TABLE_NAME "(" REST_OF_LINE
        """

And a work-around:
    return r"""
        command: "create"i _WS "table"i _WS TABLE_NAME """ + '"("' + r""" REST_OF_LINE
        """

---
#### Feedback Bot on 9/12/2021, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jakebailey** [comment]
What is the issue here?

![image](https://user-images.githubusercontent.com/5341706/134432535-3b884e6d-3619-4c23-b517-8fa25603962f.png)

This looks correct.

**Comment by bschnurr** [comment]
the colour of the bracket inside `"("` was slightly different. looks like it doesn't happen in VSCode

**Comment by jakebailey** [comment]
Does VS even support semantic tokens? I thought not.

**Comment by judej** [comment]
The screenshot from VSCode above shows the raw string as two tokens - one 41 chars long and the other 14 or so. In your screen shot, though, it looks ok. Is there a difference in the way semantic tokens are handled in untrusted workspaces?

**Comment by jakebailey** [comment]
No, there should be no difference. Do you have a full snippet?

**Comment by judej** [comment]
What you have is the full snippet. I'm seeing the open paran in the middle of the string as a separate token.

![image](https://user-images.githubusercontent.com/547753/134436578-2e55a0a5-b70f-4a71-b9fb-31377ec67fbf.png)

**Comment by jakebailey** [comment]
Arguably, the solution here is to emit tokens for strings too (instead of leaving it to the client), but in this case, I'm pretty sure this is a theme problem.

In One Dark Pro:

![image](https://user-images.githubusercontent.com/5341706/134436750-74ad11b4-d46e-4d5d-9086-cbfc92f9f07c.png)

But, in the default dark theme:

![image](https://user-images.githubusercontent.com/5341706/134436772-75bc2696-289d-4c56-9051-97ce44d374c6.png)

**Comment by judej** [comment]
Shouldn't the entire raw string be 1 token?

**Comment by jakebailey** [comment]
Our semantic tokenizer doesn't emit tokens for everything; keywords and string literals are among those we don't emit. That means the editor falls back on whatever it does, e.g. here, VS Code's included TextMate profiles.

**Comment by int19h** [comment]
Turns out this isn't a bug at all, but rather by design. The Textmate Python grammar assumes that `r""` literals are mostly used for regex, and so it tries to highlight its contents as such; hence why the parentheses are of different color. If you put `(?#foo)` somewhere in the string, you'll see that it will be highlighted as a comment etc.

**Comment by jakebailey** [comment]
Yeah, I feel like this is just how it will be, unless we go so far as to semantically figure out which raw strings are and are not involved in use of a regex library, or something, which feels both difficult and less likely to be correct.
