### ISSUE TITLE
Function Prototype insertion where syntax unsupported, and confusing highlight information

### ISSUE THREAD

**Issue by makingglitches** [microsoft/pylance-release#1884]
In addition to the following error:

https://github.com/microsoft/pylance-release/issues/513

There is a linked error causing some strange behaviors.

Presently I am developing with tkinter and when I derive a class,  pylance ever so helpfully inserts the ancestor classes' constructor parameters into my code.

Causing errors like the above as well as inserting classes which it says are aliases for another type, which the python interpreter 3.9.6 rejects.

See attached.

Here it is an alias

![Screenshot from 2021-09-28 18-41-05](https://user-images.githubusercontent.com/53788764/135175813-5cbce791-1de5-4c3f-91e1-e306db4474bb.png)

Here it causes a fatal crash.

![Screenshot from 2021-09-28 18-41-15](https://user-images.githubusercontent.com/53788764/135175848-c3a90328-4c04-4d8a-9f01-67054df49a60.png)

**Comment by makingglitches** [comment]
Oh and by the way overall GREAT PROJECT !!!!! INDISPENSABLE !  The only changes I'd make to the vs code inclusions is I'd add venv like Pycharm, but your autocomplete is 1000x faster !

**Comment by jakebailey** [comment]
Currently, we copy the type annotations from the overriden function. In this case, the function is defined in a type stub, and the `_Color` type is only defined in the stub, not at runtime. When you run it, it crashes, since the type's not there.

Feasibly, you can work around this by doing `from __future__ import annotations`, or by wrapping `_Color` in quotes in the annotation. In both cases, the annotation won't be executed, so won't crash at runtime.

I'm not entirely certain how we can detect which types do and don't exist at runtime; it's certainly the case that things that are "private" probably don't exist at runtime, but sometimes they do.

**Comment by judej** [comment]
@makingglitches, I hope the work around stopped the crash. Closing this as won't fix since we can't detect the existence of symbols at runtime.
