### ISSUE TITLE
pyright docs: Explicitly document "reveal_type", "reveal_locals"

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/pylance-release#1916]
The pyright component of pylance supports magic `reveal_type` and `reveal_locals` functions; these functions are not explicitly documented.

It would seem as if mypy introduced `reveal_type` and `reveal_locals` as a de-facto standard in type-checking, documenting those at https://mypy.readthedocs.io/en/latest/common_issues.html?highlight=reveal_type#reveal-type (a quick search on python.org suggests that these functions are well-used, but not part of the Python language or the Python Standard Library)

Once you know about these functions (and TIL about them), it is possible to discover that they are also implemented in pyright, see https://github.com/microsoft/pyright/search?l=Markdown&q=reveal_type (or the pylance changelog).

What, IMHO, is missing, is explicit documentation, much like what mypy offers, to highlight the usefulness of these functions for adding typing annotations to Python code.

**Comment by shoffmeister** [comment]
My concern is rather about where the documentation is located :)

I'd have to indirectly discover these functions from their use in the pyright docs (see my github link above) - and then wonder why the docs I can find are on mypy.

I'd propose simply adding a paragraph (or section) on "Developing with Python type annotations", mentioning the IDE feature(s) and the source code pseudo-functions in the context of pylance / pyright. This is only about discoverability.

**Comment by erictraut** [comment]
The `reveal_type` call has been standardized and added to the `typing` module for Python 3.11. It is also now included in the latest version of `typing_extensions`. The documentation can be found [here](https://docs.python.org/3.11/library/typing.html#typing.reveal_type). There was also discussion of standardizing support for `reveal_locals`, but it was decided that this is rarely used and didn't merit inclusion in the `typing` module.

Since this is now standardized and documented as part of the Python stdlib, I think it's reasonable to close this issue.

**Comment by erictraut** [comment]
Is there anything left to do for this issue? Now that `reveal_type` is officially part of the `typing_extensions` library and is documented there, I think that fulfills the feature request.
