### ISSUE TITLE
Value is not accepted. Valid values: "Jedi", "Microsoft", "None"

### ISSUE THREAD

**Issue by mingtiandemeng** [microsoft/pylance-release#192]
I set it up according to the tutorial“ python.languageServer But I didn't find pyrance, and I said value is not accepted. Valid values: "Jedi", "Microsoft", "None"“

**Comment by Orionsg** [comment]
I get the same issue.

Moreover, I think it is confusing there is a new, separate language server for Python from Microsoft as an extension, since there is apparently already a language server built into the general Microsoft Python extension and one can choose between that one and Jedi. 

If Microsoft want to add a yet another language server then do so via the general Python extension and let it be setting based, which one to use through the `python.languageServer` setting. This way is just bad UX.

**Comment by wernerm** [comment]
> I set it up according to the tutorial“ python.languageServer But I didn't find pyrance, and I said value is not accepted. Valid values: "Jedi", "Microsoft", "None"“

Same issue here. 

After installing and enabling the Pylance extension, it is not available (does not appear in the list) in settings for Python language server.

The dialog asking to enable Pylance as language server, directly after installation, also failed to enable it.

Note: I'm using Python 3.8.5 64-bit as interpreter.

**Comment by dnzyt** [comment]
I have the same issue on mac and windows 10, I'm using the latest version of vscode.

**Comment by jakebailey** [comment]
See #16; the setting is not in the core extension in the stable build, but has been added to the insiders build. We released as a preview and full support for all of the different edge cases wasn't yet ready, but will be.

Publishing as an extension offers some pretty significant advantages (much faster updates by being separate from the core extension, able to ship things that would normally not be publishable, among other things), and we are working to smooth over the bumps, most of which will be gone in the next Python extension release or are "solved" in the insiders build.

@wernerm Your issue sounds different, as it fails to load rather than it just being about the setting being missing (which is known). If you click the button, it should change your setting and offer to reload. We'd appreciate a new info with the requested logs and system info.
