### ISSUE TITLE
No intellisense when trying to import my packages

### ISSUE THREAD

**Issue by jadeid91** [microsoft/pylance-release#1929]
## Environment data

-   VS Code version: 1.61.0
-   Extension version (available under the Extensions sidebar): v2021.10.1317843341
-   OS and version: Windows_NT x64 10.0.19043
-   Python version (& distribution if applicable, e.g. Anaconda): Python3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

intellisense shows when trying to import my python file

## Actual behaviour

intellisense shows only installed packages (like pandas)

## Steps to reproduce:
1. Create a folder called pandas_library
2. Create a file under that folder called pandas_functions.py
3. Create a file under the root folder called testing.py
4. try to import the file by typing "import pandas_library.pandas_functions"
Notice while typing that no intellisense shows
[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DanielNoord** [comment]
I'm actually experiencing similar problems.

I tested
```python
❯ mkdir module
❯ cd module
❯ echo "def test():
dquote>     print()" > module_function.py
❯ echo "from module.module_function import test" > __init__.py
❯ cd ..
❯ touch test_import.py
```
This does give me IntelliSense, but in another project I no longer get any for importing local modules.

---- 

I have not singled out an reproducible piece of code, but the project is https://github.com/DanielNoord/ProjectInventarisGezantschappen

I use `__init__,py` for all modules within the `python` folder there and did receive InteliSense at some point but it stopped working last week-ish. This can obviously have many causes and might be caused by my local dependencies/environment but I would be happy to provide any details necessary to bring this further.

![ezgif-7-71a25b84d2d2](https://user-images.githubusercontent.com/13665637/136859401-291c1bc6-7c7f-4233-81d1-d0a8bdaa116c.gif)

The gif shows that I don't get IntelliSense for importing the `data_parsing` module for a file in `./python`, but after writing it myself and importing a function the `show definition` option does take me into `./python/data_parsing`.

Output of `Python` is as follows:
```bash
~/.pyenv/versions/knir-3.9.6/bin/python -m pylint --disable=C0111 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/Documents/Geschiedenis/KNIR/python/test.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m pylint --disable=C0111 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/Documents/Geschiedenis/KNIR/python/test.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers ~/Documents/Geschiedenis/KNIR/python/test.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers ~/Documents/Geschiedenis/KNIR/python/test.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python ~/.vscode/extensions/ms-python.python-2021.10.1317843341/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir ~/Documents/Geschiedenis/KNIR -s --cache-clear
cwd: ~/Documents/Geschiedenis/KNIR
##########Linting Output - mypy##########
Success: no issues found in 1 source file
##########Linting Output - pylint##########
> ~/.pyenv/versions/knir-3.9.6/bin/python ~/.vscode/extensions/ms-python.python-2021.10.1317843341/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir ~/Documents/Geschiedenis/KNIR -s --cache-clear
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m pylint --disable=C0111 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /users/daniel/documents/geschiedenis/knir/python/data_parsing/create_full_name_string.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m pylint --disable=C0111 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /users/daniel/documents/geschiedenis/knir/python/data_parsing/create_full_name_string.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers /users/daniel/documents/geschiedenis/knir/python/data_parsing/create_full_name_string.py
cwd: ~/Documents/Geschiedenis/KNIR
> ~/.pyenv/versions/knir-3.9.6/bin/python -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers /users/daniel/documents/geschiedenis/knir/python/data_parsing/create_full_name_string.py
cwd: ~/Documents/Geschiedenis/KNIR
##########Linting Output - mypy##########
Success: no issues found in 1 source file
##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

Output of `Python Language Server` is as follows:
```bash
[Info  - 11:27:35 PM] Pylance language server 2021.10.0 (pyright d5878534) starting
[Info  - 11:27:35 PM] Server root directory: /Users/daniel/.vscode/extensions/ms-python.vscode-pylance-2021.10.0/dist
[Info  - 11:27:35 PM] Background analysis(1) root directory: /Users/daniel/.vscode/extensions/ms-python.vscode-pylance-2021.10.0/dist
[Info  - 11:27:35 PM] Background analysis(1) started
```

**Comment by jakebailey** [comment]
I'm a little confused because many parts of the gif are hinting that Pylance isn't beingt used at all; no semantic colorization is appearing, and the tooltip that appears in your completion/hover doesn't look like it came from Pylance at all (`create_full_name_string` shows up but is missing type info, something that we will definitely be showing).
