### ISSUE TITLE
Optional exist checking doesn't works properly for attribute inside an other block (an other function).

### ISSUE THREAD

**Issue by AiroPi** [microsoft/pylance-release#1950]
## Environment data

-   Language Server version: 2021.10.2-pre.1
-   OS and version: Windows 10 Familly v19041.1288
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.6

## Expected behaviour

When we check if an object attribute is not None, and after that we try to use this attribute (which is not None) inside an inner-function, PyRight should "remember" that this attribute is not None (like it does for normal variables).

## Actual behaviour

PyRight still consider it could be None.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
from typing import Optional


class Class:
    a: Optional[str]


def function(b: Class, c: Optional[str]):
    "test" + b.a  # Warning, but it's normal

    assert b.a is not None  # Here I use assert, but it is the same with a if -> return

    "test" + b.a  # No warning, it's normal

    def test():
        return "test" + b.a  # Warning, seems strange

    assert c is not None

    def test2():
        return "test" + c  # No warning, seems normal
```

**Comment by erictraut** [comment]
The type of a captured variable cannot be narrowed in the general case. That's because it could be assigned to a new value prior to the inner function being invoked.

Consider the following:
```python
def func():
    x: Optional[str] = ""

    def test():
        return x + "hi"

    x = None

    test()
```

Pylance does support type narrowing of captured variables in very restricted situations — when the expression is a simple name (as opposed to a member access expression or something more complex) and it can prove that the value of the symbol is not modified after the variable is captured. (Note: Other Python type checkers like mypy do not support even this case.)

Your example involves a member access expression (`b.a`), so the narrowed type is not retained within the scope of the inner function.

Here are a few suggestions:
1. You can move the assert within the inner function. This documents your assumption that the type of `b.a` is not assigned a value of `None` prior to the invocation of the inner function.

```python
def function(b: Class, c: Optional[str]):
    def test():
        assert b.a is not None
        return "test" + b.a
```

2. You can assign the value of the expression to another local variable that is captured by the inner function. This allows the type checker to validate that the value of the local variable is not modified after it is captured.

```python
def function(b: Class, c: Optional[str]):
    x = b.a
    assert x is not None

    def test():
        return "test" + x
```

**Comment by AiroPi** [comment]
Oh ok I see yes you're right, I did not think about that.
Thank you !
