### ISSUE TITLE
Unassigned callable Object check

### ISSUE THREAD

**Issue by xiangyu-xing** [microsoft/pylance-release#197]
I had some code like:
class A:
    def func(self):
         pass
a=A()
a.func # Grammatically correct, it is callable object
# but i mean a.func(), 
Because it is grammatically correct, it is difficult to find, Generally speaking, an unassigned callable object is meaningless. 
could check Unassigned callable Object, and give some prompt

**Comment by erictraut** [comment]
There are legitimate uses for the expression `a.func`, so Pylance can't always flag this as an error. It depends on how it is used.

Pylance can determine whether the use is correct if you enable its type checking capabilities. To do this, set the `python.analysis.typeCheckingMode` setting to "basic".

**Comment by erictraut** [comment]
Actually, even with type checking enabled, it wouldn't report a problem in the code sample above because the result is not assigned, therefore there is no type validation performed on the expression's type.

It may be worth adding a diagnostic rule specifically to detect and report this case, but I'd worry about generating false positives. In Python, attribute accesses can have side effects, so there are legitimate (but rare) uses for an unassigned expression of the form `a.func`.

**Comment by erictraut** [comment]
@xiangyu-xing, you might find [this new feature](https://github.com/microsoft/pyright/issues/1125) addresses your requirements. This new feature will appear in the next release of pylance.
