### ISSUE TITLE
Pylance server.bundle.js is detected as trojan

### ISSUE THREAD

**Issue by MosGeo** [microsoft/pylance-release#2045]
I am noting that the latest version of pylance (11/4/2021, 02:39:25) is being detected as trojan by Windows Defender. See below. Is this a known issue?

![image](https://user-images.githubusercontent.com/10503349/140638882-2e764e1e-8112-49f8-8019-f2e2af4085e5.png)

**Comment by jth184** [comment]
The same behaviour occurs with me. The operating system is Windows 11 Pro version 10.0.22000.

**Comment by judej** [comment]
Thanks for the report. We will investigate the issue.

**Comment by JamesHorvath** [comment]
Defender for Endpoint is alerting to Pylance 2022.1.1 being infected with Oneeva.
[\.vscode\extensions\ms-python.vscode-pylance-2022.1.1\dist\server.bundle.js]

**Comment by bschnurr** [comment]
Is this still happening on the latest 2022.2.4 release?

**Comment by MosGeo** [comment]
@bschnurr I will remove the whitelisting of the file and see if it is being detected again. I will get back to you.

**Comment by judej** [comment]
Have reported to the Defender team and they will update sigs. Thank you for the report.

**Comment by MrRogerTheShrubber** [comment]
> Defender for Endpoint is alerting to Pylance 2022.1.1 being infected with Oneeva. [.vscode\extensions\ms-python.vscode-pylance-2022.1.1\dist\server.bundle.js]

Lol I feel like I'm in a flying circus episode with @microsoft @python!

Hi guys! I was thinking to myself, and I reached the conclusion that public shaming bad projects with bad maintainers is a reasonable way to entice action.

So I'll tag some organizations in particularly egregious examples of bad behavior with the hopes that given enough eyeball, all bugs are shallow!

I sure hope that one day the guys at @google, @aws, or even @facebook, maybe @apple, that someone, will provide a great open source competitor so that we don't get locked into using the bad @microsoft @python extension as the python experience! 😢

Of I course I must mention the @eclipse @apache and @mozilla guys lest they get jealous! ❤️

**Comment by debonte** [comment]
@JonKast, please open a new issue.
