### ISSUE TITLE
Pylance flags type as unknown when returning self 

### ISSUE THREAD

**Issue by jms13** [microsoft/pylance-release#2049]
I try to annotate the method with class type when returning `self`.

![image](https://user-images.githubusercontent.com/11633324/140781054-7609ccf6-b052-4ee1-973d-0aa41199a582.png)

## Environment data

-   Language Server version: v2021.11.0
-   OS and version: Ubuntu 20.04.3 LTS
-   Python version: 3.8.10

## Expected behaviour

Pylance should not flag the class type when returning `self`.

## Actual behaviour

Pylance flags the type with `Declared return type is unknownPylancereportUnknownVariableType`

## Code Snippet / Additional information

```python
class X:
    def fun(self) -> X:
        return self
```

**Comment by erictraut** [comment]
Try running your sample code in the Python interpreter. You'll receive a runtime exception "NameError: name 'X' is not defined". That's because, by default, the Python interpreter evaluates the type annotation expression, and at the point where it interprets it, the class `X` has not yet been defined.

To work around this, you have two options:

1. Enclose the type annotation in quotes. PEP 484 allows annotations to refer to symbols declared later in the file by quoting them. 
2. Add `from __future__ import annotations` to the top of your source file. This tells the Python interpreter to defer the evaluation of the annotation expression, as if you had enclosed it in quotes.

**Comment by jms13** [comment]
Quotes work perfectly.

Thank you!

PS. I guess it was StackOverflow-type question. Sorry!
