### ISSUE TITLE
type aliased Annotated isnt displayed correctly in types

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pylance-release#2063]
<h3> Environment data </h3>

-   Language Server version: 2021.11.0
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): cpython 3.9.7
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Pylance should display the underlying type inside `typing.Annotated` but instead its showing the alias to the `Annotated`

```py
AnnotatedInt = Annotated[int, ()]

def test(arg: Optional[AnnotatedInt]):
    arg = arg or 1
    reveal_type(arg)  # should be revealed as `int`
```

<h3> Actual behaviour </h3>

![image](https://user-images.githubusercontent.com/39768508/141151676-ccbcf54c-cac7-49cd-ad59-0e981626418d.png)
![image](https://user-images.githubusercontent.com/39768508/141151829-7903cac9-974d-47a4-975e-0a72d28ad601.png)

**Comment by erictraut** [comment]
The current behavior is consistent with how other type aliases are displayed. Pylance uses the type alias name in place of the underlying type represented by the type alias when displaying hover text, signature help, and error messages. It "expands" the type alias to show the full type within a `reveal_type`. This behavior is based on feedback from many pylance users who told us that they wanted to see type aliases because they are more descriptive (and often shorter) than the underlying types they represent.

The expression `arg or 1` is evaluated to have the type `AnnotatedInt | Literal[1]`, which is what you see in the hover text. This expands to `int | Literal[1]` in the `reveal_type` output. Which of those two (the hover text or the `reveal_type` output) are you suggesting is incorrect?

Are you saying that you don't want `AnnotatedInt` to be treated as a type alias? Or that you don't want type aliases to be displayed in hover text?

**Comment by jaens** [comment]
Might be neither option: 

I am guessing the original poster is looking for `reveal_type()` to show `Annotated[int, ()] | Literal[1]` - ie. the `Annotated` wrapper being preserved in the final type.

**Comment by erictraut** [comment]
Yeah, I don't think that's what @Zomatree meant.

`Annotated` allows you to specify arbitrary value expressions for the type arguments after the first. They do not need to be legal type expressions, and they are not meant to be evaluated by a type checker. In the above example, `()` is not a valid type expression. For that reason, the type checker largely ignores these expressions other than validating that they are legal expressions.

**Comment by Zomatree** [comment]
I understand your reasoning behind this, closing.
