### ISSUE TITLE
Support showing docstrings for extension modules

### ISSUE THREAD

**Issue by segevfiner** [microsoft/pylance-release#2076]
Pylance currently does not show docstrings for extension modules even if they have type stubs. For example:

`spam.pyx`:
```cython
# cython: language_level=3str

def f() -> int:
    """This is f."""
    return 123
```

`spam.pyi`:
```python
def f() -> int: ...
```

Build with: `cythonize -i spam.pyx`, and then create some new Python file and then import and try to get completions for spam. You will see the function `f` but it won't show its docstring.

**Comment by judej** [comment]
Thanks for the report. Since this is a compiled module, the way to get the docstrings is to scrape the file. We don't do this for third party libs. However, since you have the docstrings, you could add the docstrings to the .pyi file and it should show up.

Please reopen if this does not work.
thanks

**Comment by segevfiner** [comment]
Yeah. But the thing is. Most/all extension modules don't maintain their doc string in their type stubs... Is there any module at all that does that...? Defining the doc strings in two different places is kind of a pain...
