### ISSUE TITLE
Incorrect type reported on hover with implicit optional parameter

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pylance-release#2091]
Code:
```py
def f(x: str = None):
    return x + "foo"
```
If you put a `reveal_type(x)` in the middle, it shows `str | None` correctly.
However, if you hover over `x`, you see just `str`. 
![image](https://user-images.githubusercontent.com/42166884/142681058-744fd83b-fb5e-4967-8bed-562af3778465.png)
Seems at least confusing to me.

**Comment by erictraut** [comment]
I agree this looks like a bug. I've created a corresponding issue in the pyright issue tracker.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.12.0, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2021120-2-december-2021)

**Comment by hadim** [comment]
I don't know whether I should open a new ticket or not but it seems like the `Optional` implicit type is not assigned anymore with `= None`. It affects all my source code since 1-2 weeks now (updated VSCode version).

See the below example:

```python
def hello_world(value: str = None):
    print(value)

hello_world()
```
![Screenshot from 2022-03-06 07-50-58](https://user-images.githubusercontent.com/528003/156924075-599b6995-e534-43cd-ad17-e61f61d55761.png)

The code also seems valid according to mypy:

```bash
$ mypy type_test.py 
Success: no issues found in 1 source file
```

**Comment by erictraut** [comment]
@hadim, this was an intentional change. About a year ago, PEP 484 was updated to recommend that type checkers do not use an implicit Optional by default. We decided to give users a bit of time before changing this default, but we did so recently. If you want the old (now deprecated) behavior, you can set `strictParameterNoneValue` to "false".

If you are actively maintaining your code base, I'd encourage you to start moving away from implicit Optional.

**Comment by hadim** [comment]
Thanks @erictraut. It makes sense and I'll switch my codebase to this practice from now on.

**Comment by malthe** [comment]
@erictraut actually it was apparently by 2018 that the [recommendation changed](https://github.com/python/peps/commit/0630155b47c27f25e66267d247f0205aa953f113).
