### ISSUE TITLE
Classmethod subclasses are not treated as classmethod would be

### ISSUE THREAD

**Issue by thesadru** [microsoft/pylance-release#2100]
## Environment data

- Language Server version: 2021.11.2
- OS and version: Windows 10
- Python version: 3.9.6

## Expected behavior

`classmethod` subclasses should be properly handled and the decorated method should be treated as if it were decorated with a plain `classmethod`.

## Actual behavior

Subclassing `classmethod` or creating a custom descriptor whose `__get__` returns a classmethod will always fail to be properly detected and will treat the method as if it were a normal method.

## Code Snippet / Additional information

```python
class register(classmethod):
    def __set_name__(self, owner, name):
        owner.__registered__ = self.__get__(None, owner)


class Foo:
    @register
    def a(cls):
        return cls()

    @classmethod
    def b(cls):
        return cls()

```
![image](https://user-images.githubusercontent.com/58166507/142889306-bd0e64cb-71d3-4cb9-8510-5a0ee5e8449d.png)
```
$ mypy test.py 
Success: no issues found in 1 source file
```

> I'm unsure as to whether this is a pyright issue or not. Hope this is the right place to report this bug.

**Comment by erictraut** [comment]
This is a core type checking issue, so it involves pyright. 

This is not something that can be easily addressed because of pyright's architecture. It needs to determine whether a method is a classmethod early in the analysis process, long before it's able to determine whether a symbol subclasses from another type. This is the first time I've seen any code subclass from `classmethod`. I didn't even know it was possible to do this.

I think the best I can do here is offer a (somewhat ugly) workaround:
```python
if TYPE_CHECKING:
    register = classmethod
else:
    class register(classmethod):
        def __set_name__(self, owner, name):
            owner.__registered__ = self.__get__(None, owner)
```

Another option, if you're willing and able to change your code, is to separate the `classmethod` functionality from the `register` functionality and apply the decorators separately. This would have the side benefit of making it more readable.

```python
    @register
    @classmethod
    def a(cls):
        return cls()
```

**Comment by thesadru** [comment]
I wanted to implement something similar to `pydantic.validator`, which assumes that the method will always be a classmethod. That one works reliably because you rarely, if ever, need to instantiate the class and rather only ever use its attributes. Here, however, I want to implement a sort of implicit constructor as a feature to my library (I swear it makes more sense in practice).

Currently, I have resorted to using `if TYPE_CHECKING` but that doesn't provide docstrings which is a pretty annoying problem.

**Comment by bschnurr** [comment]
Would modifying an instance of classmethod work? It solves the docstrings
```
register = classmethod()

def reg_set_name(self, owner, name):
    owner.__registered__ = self.__get__(None, owner)
register.__set_name__ = reg_set_name
```

**Comment by thesadru** [comment]
Doubt so, I wanted it to be a decorator since it's for a library and meant to be used on multiple methods.
