### ISSUE TITLE
PEP 660 support

### ISSUE THREAD

**Issue by nihilox** [microsoft/pylance-release#2114]
## Environment data

-   Language Server version: v2021.11.2
-   OS and version: Mac OS 12.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0

## Actual behavior

Resolved correctly with pylance disabled

## Code Snippet / Additional information

`foo.pth`
```
import _foo
```

`_foo.py`
```python
from editables.redirector import RedirectingFinder as F
F.install()
F.map_module('foo', '...')
```

**Comment by brettcannon** [comment]
Discussion about adding support in various editors has now been opened at https://discuss.python.org/t/pep-660-support-and-ides/13878 .

**Comment by gaborbernat** [comment]
How can the community help with this? Who would be able to sign off on a proposal to solve this? Which part of the code base would need to be impacted? Thanks!

**Comment by erictraut** [comment]
Which portion of this isn't working? Pyright (the type checker that pylance is built upon) already supports pth files, so I would think that this would already work.

It would be helpful if you could provide a specific example project, set of installation steps, and an indication of expected vs. observed behaviors for that project.

**Comment by erictraut** [comment]
Are you saying that the code is dynamically modifying the map module? Static analysis tools like linters, language servers, and type checkers (including pylance) do not execute the Python code. If the behavior is completely dynamic, then we probably won't be able to make PEP 660 work with pylance. Is there a way for pylance to statically find the editable install without executing any Python code?

**Comment by brettcannon** [comment]
> Are you saying that the code is dynamically modifying the map module?

It's dynamically adding the `foo` module as an editable install (e.g. settings things up so imports pull from the source code in the workspace and not somewhere in `site-packages`).

**Comment by erictraut** [comment]
If this is an entirely dynamic mechanism, that would be really unfortunate. We probably won't be able to support it in pylance then, and we'll need to recommend against anyone using it if they want to take advantage of any static analysis tools or language servers.

**Comment by gaborbernat** [comment]
Can we come up together with a mechanism that provides enough info for the IDE/language server on what's being done, that perhaps the backends can call? E.g. in this case we could say module x is available at path Y in a JSON file?

**Comment by brettcannon** [comment]
> If this is an entirely dynamic mechanism, that would be really unfortunate.

This mechanism is, yes.

https://peps.python.org/pep-0660/ outlines how to tell build tools the user wants an editable install, but it doesn't prescribe the solution. The one mentioned here is one possible approach, but it's also the one gaining traction.

As @gaborbernat mentioned while I was typing this, can the Pylance team and the packaging community collaborate on a solution that build tools can use in order to support editable installs but is defined in such a way you can process the information appropriately?

**Comment by erictraut** [comment]
The import resolution mechanism in Python is already incredibly complex and customizable. Do we really need yet another incompatible mechanism that the entire ecosystem needs to now implement? Why can't this mechanism make use of "pth" files so the location of the library is automatically added to the import resolution paths?

**Comment by gaborbernat** [comment]
> Why can't this mechanism make use of "pth" files so the location of the library is automatically added to the import resolution paths?

The big problem with pth files is that they are very strict and does not allow you to handle files generated during the build 🤔 What would be a good API for pylance, that could somehow handle files generated dynamically. To bring up an example imagine you have a JSON Schema and you're generating the python code from it during package build time via https://pydantic-docs.helpmanual.io/datamodel_code_generator

**Comment by erictraut** [comment]
A "pth" file can point to a directory, right? That doesn't sound very restrictive. Generated code files could be located within that directory.

An API isn't the answer because that implies code execution. What's needed here is a static mechanism that doesn't involve any code invocation.

A new JSON file with a well-defined file name and schema could work, but this would need to be standardized — preferably specified in a PEP — so all static analysis tools know about it. We are not interested in crafting a pylance-specific solution here because it's a problem that goes well beyond pylance.

I encourage you to think about leveraging existing mechanisms for statically specifying import resolution paths rather than inventing a new one. As I mentioned above, the Python import resolution mechanisms is already very complex and customizable. Adding yet another orthogonal mechanism on top of the long list of existing mechanisms is far from ideal.

**Comment by gaborbernat** [comment]
> A "pth" file can point to a directory, right? That doesn't sound very restrictive. Generated code files could be located within that directory.

The problem is that this would force the generation of the file upfront and not make it instead of a lazy operation. That was the initial appeal of using import hooks. We definitely overlooked the importance of static analysis tools support when PEP-660 was designed. That's why I'm reaching out though to see how and where can we improve it to make it possible.

> An API isn't the answer because that implies code execution. What's needed here is a static mechanism that doesn't involve any code invocation.

The packaging operation is code execution though, so in order for the DEV environment to replicate closely the real thing, it needs to imply some code execution somewhere... Though this does go against what static analysis tools would want I imagine.

> As I mentioned above, the Python import resolution mechanisms is already very complex and customizable. Adding yet another orthogonal mechanism on top of the long list of existing mechanisms is far from ideal.

I don't think we're investing anything new here. We're just using what the import system customization allows us to do.

**Comment by brettcannon** [comment]
> If PEP 660 is incomplete

[PEP 660](https://peps.python.org/pep-0660/) is complete and accepted. All it specifies is a hook for build tools to implement for when users request an editable install. How build tools choose to make editable installs work is entirely up to them. This issue is about one of the mechanisms being used by the community to implement PEP 660 support.

> A "pth" file can point to a directory, right? That doesn't sound very restrictive. Generated code files could be located within that directory.

An issue with `pth` files is they are too loose in what they expose for what most people want editable installs for. A frequent issue with setuptools, for instance, is people forget to include a file in their `MANIFEST.in` file, and so it gets left out when the project gets packaged. People then do an editable install with setuptools so they make sure they are only working against the files that will end up being distributed (I wouldn't be shocked if this is actually the motivation behind setuptools introducing the concept of editable installs). Setuptools supports editable installs by building the entire project and installing it. PEP 660 abstracted that into an API and standardized the concept for build tools of what an editable install is as each build tool has their own needs for an editable install (e.g. performance, etc.).

> A new JSON file with a well-defined file name and schema could work, but this would need to be standardized — preferably specified in a PEP — so all static analysis tools know about it.

Correct, which is what we are asking if you are interested in being involved with somehow?

> I encourage you to think about leveraging existing mechanisms for statically specifying import resolution paths rather than inventing a new one.

> I don't think we're investing anything new here. We're just using what the import system customization allows us to do.

Correct, there is nothing new here. The mechanism being used is part of the import system (and has [been around since Python 2.3](https://peps.python.org/pep-0302/)).

**Comment by erictraut** [comment]
> [PEP 660](https://peps.python.org/pep-0660/) is complete and accepted

It may be accepted, but it sounds to me like it's incomplete in that it didn't identify and address all of the requirements for a full solution.

> which is what we are asking if you are interested in being involved with somehow

I'd be happy to participate in a typing-sig discussion on the topic — and provide feedback on a draft PEP.

> there is nothing new here

You're proposing to create a new JSON file or something like that. That's what I was referring to when I said "something new". There are multiple existing mechanisms in place to tell static analysis tools about import resolution paths. It would be best to leverage one of those existing mechanisms rather than invent a new one (like a JSON file) that requires every existing static analysis tool to add more complexity.

**Comment by pfmoore** [comment]
> It may be accepted, but it sounds to me like it's incomplete in that it didn't identify and address all of the requirements for a full solution.

It's certainly true that the discussion on editable installs didn't cover static analysis. None of the participants flagged that as a relevant point (but then again, static analysis has never been part of the discussion for *any* packaging standard, so I'm not clear why this one is any different). As PEP delegate, it's not something I particularly considered because I knew that PEP 660 could be used to replicate the existing approach, so it would definitely be possible to use it to provide at least as good an approach as the legacy mechanism offered - which was the minimal level of acceptability for any proposal.

PEP 600 simply specifies a runtime hook that installers can use to request a build backend provides an installable wheel that implements the "editable install". This can be done exactly the same way as setuptools implemented editable installs in the past, by installing a `.pth` file pointing to the source directory. That should be no better or worse for static analysis than the old approach was.

The issue here is that *backend developers* wanted to move away from `.pth` files, to something "better" (I use quotes mainly because there was never a real consensus on what that "better" solution would look like). So any discussion on static analysis support needs to involve the build backend developers, as PEP 660 itself says nothing about what mechanism a build backend should use for editable installs.

The other piece of the picture here is that I implemented a library, `editables`, which offers support for *both* the old `.pth` mechanism, *and* an import hook based approach, which (as has been noted in this thread) uses dynamic changes to the import machinery - totally supported Python functionality, but yes, likely to not play at all well with static type checkers. But it's the consumers of the library (build backends) that choose which mechanism to use. I don't actually have any information on which approach is preferred by backends - or even whether backends are using `editables` rather than just writing their own code (it's not particularly hard to get the `.pth` approach correct, so there's no immediate need for a library if that's all you want to do).

I don't really have an opinion here. Maybe build backends should be encouraged to use static checker friendly mechanisms like `.pth` files? Maybe backends should support options to let the user choose at install time which mechanism to use? Both of these approaches are supported by PEP 660 and the `editables` library.

**Comment by brettcannon** [comment]
> `editables`, which offers support for _both_ the old `.pth` mechanism, _and_ an import hook based approach

> Maybe build backends should be encouraged to use static checker friendly mechanisms like `.pth` files? Maybe backends should support options to let the user choose at install time which mechanism to use? Both of these approaches are supported by PEP 660 and the `editables` library.

We can either wait and see how big of a concern this becomes or simply make sure build backends are aware of the trade-offs with either approach and they choose whichever fits their needs the best.

**Comment by erictraut** [comment]
> If pyright or another tool saw such a comment in the module they were inspecting

That would be new mechanism that all static analysis tools, linters, and language servers would need to know about. I encourage you to look for a solution that doesn't require expensive modifications throughout the Python tooling ecosystem. Most of these tools already know about pth files and symlinks. They also know about the `sys.path` paths list. Is there a way to use one of those mechanisms?

**Comment by davidism** [comment]
How do current tools know about pth files? A maintainer of each static analysis tool, linter, and language server saw that was a thing and made their tool know about it. If editable installs with pth files hadn't already existed, and then a PEP was made to describe them, it seems like you'd be making a similar statment that all tools should not be adding support for it because they'd all have to add support for it.

> Is there a way to use one of those mechanisms?

That's what I was suggesting, tools already know how to follow a path in a pth file to the true source, they could add an extra check that looks for a comment with the same path to follow in the same way. So they're essentially reusing the existing pth support, but in a way that can work with these new editable techniques that are emerging.

**Comment by erictraut** [comment]
Import resolution and code analysis are very different stages within tools like pyright, mypy, etc. This is an import resolution problem. Let's look for solutions that are in the domain of import resolution.

Can you think of a solution that updates the `sys.path` list to include all of the relevant import resolution paths for editable installs? Most static analysis tools (including pyright and mypy) invoke the python interpreter to dump the value of `sys.path` and use that for import resolution. Since the Python interpreter knows about pth files, those paths are present in the `sys.path` list.

**Comment by davidism** [comment]
I'm not an expert on these, so I'm mostly going off the details I've gleaned from you and others about these tools. If you ask me to come up with a solution, I'll come up with something that sounds logical to me, but I think you and other tools maintainers are in a better position to do this.

So they've dumped `sys.path`, and `pth` files have already added extra directories to the list. Right now, it sounds like the tool enumerates all the Python files it needs to analyze, then analyzes them. If, as part of the "enumerae all Python files" step, it also looked 

```python
queue = dump_sys_path()
py_files = []

for dir in queue:
    for py files in dir:
        if first line is "# editable-src:":
            add_dir_to_queue()
        else:
            py_files.append(py file)

analyze_code(py_files)
```

**Comment by erictraut** [comment]
No, that's not how language servers work.

Import resolution should not require tools to open source files and scan for comments. I'll give you points for creativity, but let's keep looking for better options.

This is probably not the right forum to be discussing this. We should move this to typing-sig or some other forum where other tools developers can weigh in.

**Comment by davidism** [comment]
OK, in any future discussion, it would probably be helpful to expand on *why* a language server doesn't work that way, what constraints it has, why they can't open a file even though they're about to open the file anyway, etc., otherwise people aren't going to be able to come up with solutions.

**Comment by gaborbernat** [comment]
> This is probably not the right forum to be discussing this. We should move this to typing-sig or some other forum where other tools developers can weigh in.

The forum for that is https://discuss.python.org/t/pep-660-support-and-ides/13878/9 but tool developers doesn't seem to weigh much in 😊

**Comment by erictraut** [comment]
Tool developers don't hang out in that forum. You will get more attention from them if you post in the typing-sig or the discussions section of [python/typing](https://github.com/python/typing/discussions).

**Comment by gaborbernat** [comment]
But this is a topic about packaging why would open a discussion on the unrelated typing forum?

**Comment by judej** [comment]
Until the typing community and the packaging community agree on a direction, there is nothing that Pylance can do.

**Comment by gaborbernat** [comment]
But this isn't related to the typing system. This is purely about packaging 🤔  and this issue was a call for input from the PyLance team 🤔  there's no point in us agreeing on something that the pylance team then doesn't adopt.

**Comment by erictraut** [comment]
@gaborbernat, this is an issue that goes beyond pylance. A viable solution must also work for other static analysis tooling (mypy, pytype, pyre, pylint, PyCharm, etc.). If you want to engage with authors of static analysis tools and get their support, you need to go to the forums where they hang out, and you need to work with that community on a standard.

If the standard involves one of the existing mechanisms for discovering import resolution paths in a static manner (as I recommend), then there will be no need for pylance or any other existing tools to do any work to support PEP 660.

If there is some new mechanism required, then it should take the form of a PEP that goes through the normal review and ratification process. Once a mechanism is agreed upon, pylance will implement support for it.
