### ISSUE TITLE
Type variable info is missing in hovering tip with type alias

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#2151]
## Environment data

-   Language Server version: 2021.12.0
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.12 Anaconda

## Sample code

```python
from __future__ import annotations

from typing import Generic, TypeVar

V_t = TypeVar("V_t", bound=int)

class A(Generic[V_t]): ...

B = A

# Using an incompatible type variable to see if the type check works.
def f() -> B[object]: ...
```

## Expected behavior

Get "(function) f: () -> B[object]" on hovering `f`.

## Actual behaviour

Got "(function) f: () -> B" on hovering `f`.

**Comment by erictraut** [comment]
If your intent is to define a generic type alias called B, the line `B = A` should be `B = A[V_t]`. By omitting the type variable, you are defining a type alias that `B` is the equivalent of `A[Any]`.

You might wonder why pyright doesn't automatically fill in the `Any` in this case. The problem is that the statement `B = A` is somewhat ambiguous. It's not clear whether you're simply assigning `A` to `B` or defining a type alias called `B`. Unlike most modern languages, Python doesn't provide a keyword for defining type aliases, so type checkers need to fall back on a set of heuristics to determine whether it's a type alias or not. The heuristics in pyright have been tuned over time to minimize the likelihood of false positives. In this particular case, it's treating it a way that it can be used as either a type alias or an assignment. The side effect of this behavior is that `B` is not specialized to `A[Any]` as it would be if this were known to be a type alias.

If you want to unambiguously indicate that this is a type alias, you can use `B: TypeAlias = A[V_t]`. 

If you were to use `B: TypeAlias = A`, that would still be legal, but it would imply `B: TypeAlias = A[Any]`. Pyright could do a better job reporting errors in this particular case. I've made some modifications to improve the error messages here.

**Comment by Azureblade3808** [comment]
I wasn't aware that type variables should be used in type aliases. It makes sense now.

But still another problem, shouldn't the use of `B[object]` be an error given that `B` is considered not using a type variable?

**Comment by erictraut** [comment]
`B[object]` does result in an error.

![Screen Shot 2021-12-08 at 9 01 19 PM](https://user-images.githubusercontent.com/7040122/145337371-b8481751-44a1-474d-8524-cc28b116a037.png)

**Comment by Azureblade3808** [comment]
This is because `object` doesn't meet the bound of `int`. If you replace `B[object]` with `B[int]`, the error is gone, when I expect the opposite.

**Comment by erictraut** [comment]
If you use `B = A`, no error is given. This is because of the heuristic I described above.

If you use `B = TypeAlias = A`, an error should be given if you try to use `B[int]`. In the current version of pyright, there is no error generated in this case. I noticed this was missing when I was investigating this issue, and I've added an error for this case. This will be in the next release.

**Comment by Azureblade3808** [comment]
And here is an example that definitely crashes, but doesn't get a warning or error.

```python
from __future__ import annotations

from typing import Generic, TypeVar
from typing_extensions import TypeAlias

V_t = TypeVar("V_t", bound=int)

class A(Generic[V_t]): ...

B: TypeAlias = A[Any]
C: TypeAlias = B[Any]  # Raises TypeError: __main__.A[typing.Any] is not a generic class
```

**Comment by erictraut** [comment]
Yep, this will generate an error in the next release.

**Comment by Azureblade3808** [comment]
Since the behavior mentioned in the title has been explained, I'm closing this issue.
