### ISSUE TITLE
A way to specify that a module has on-import effects

### ISSUE THREAD

**Issue by tdaniely-dn** [microsoft/pylance-release#2165]
Although many would rightly say it is bad practice to have on-import side effects, In some contexts, importing modules with side effects is the common use. e.g in Pulumi projects most of the code is declarative registration that notifies the pulumi cli that spawns the main module. Even for a large project there's little point in wrapping everything in methods.

In this instance the gray-out visual que is not relevant, and distracting.
The gray out feature is an active prompt to the programer to fix something. In shared code this easily wastes time and can cause errors.

Suggest to introduce some mechanism, such as a doctring keyword to explicitly mark a module as having on-import side effects.

**Comment by erictraut** [comment]
I presume that you're referring to the grayed-out module name in an import statement when there is no reference to the imported module within the source file?

Here are some options for you:
1. Avoid using on-import side effects. As you pointed out, this is a bad practice and should generally be avoided.
2. If it can't be avoided, I would think that a comment with a very visible and obvious warning statement would be important to include above the import statement. Otherwise, someone will be inclined to delete the apparently-unused import. Such a comment should serve as a justification for why the grayed-out text in this case can be ignored.

If the grayed-out text really annoys you, you can use one of the following workarounds:
3. Rather than using `import foo`, use `import foo as _`. This will still perform the import but will assign the module reference to the local symbol `_` which, by convention in Python, means "this symbol is intentionally unreferenced".
4. Create a dummy reference to the symbol, such as:

```python
if False:
    print(foo)
```

or 
```python
if typing.TYPE_CHECKING:
    foo
```

This dummy reference also provides a good place to insert a warning to other developers explaining why this is needed.
