### ISSUE TITLE
[Feature Request] show more suggestions via fuzzy text.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#217]
write `pr` and see the suggestion list:

using jedi:

![image](https://user-images.githubusercontent.com/26390254/89708943-91089c00-d990-11ea-8aac-adb7b6e1f139.png)

using Pylance:
![image](https://user-images.githubusercontent.com/26390254/89708950-a1207b80-d990-11ea-80e0-747b4fbb7a5f.png)

in Pylance, we can't see `PermissionError` and `PendingDeprecationWarning`.

**Comment by erictraut** [comment]
Thanks for the suggestion.

There's no single "right" way to determine which suggestions to show or which order to display them. Pylance incorporates a complex set of heuristics that take into account context, fuzzy text matching, symbol types, and historical usage. It's significantly more sophisticated than the method used by Jedi. So our goal is not to simply copy Jedi here.

Can you provide more details about what you like about Jedi's results in this specific example? It sounds like you want the fuzzy text matching to be slightly "fuzzier"?

If I adjust our "similarity cutoff" just slightly, the additional suggestions appear. But there's a tradeoff in doing this. It means the suggestions will be noisier.

@jakebailey & @savannahostrowski , I'm interested in your thoughts here. If I change `similarityLimit` from 0.25 to 0.249, the following suggestions are provided in the example above.

![Screen Shot 2020-08-08 at 8 13 38 AM](https://user-images.githubusercontent.com/7040122/89713842-39960c00-d94f-11ea-821f-cdf56bebdaa4.png)

**Comment by byehack** [comment]
> Can you provide more details about what you like about Jedi's results in this specific example?


### My Suggestion:

when write one character:
the suggestion should starts with this character<non-sensetive> (like now of Pylance)

when write two or more characters:
the suggestion should has all of the characters <non-sensetive>, but first character's index < second's character index < third ...

example of words that should suggest the HelloWorldTest from this code: `HelloWorldTest = None`:
```
h
H
hw
hW
hwt
world
test
```

example of words that should not suggest:
```
olleh
tset
```


this is usefull when we want the see all Exception list to choice the Exception that endswith 'Error'.

![image](https://user-images.githubusercontent.com/26390254/89717288-34c26e00-d9ca-11ea-8da6-9b4cb55c865a.png)
in above when i write `hwt` and `wrd`, it shows the `HelloWorldTest`. i think this is from vscode not pylance because it doesn't have value icon. maybe you can also get help with vscode method to how show the suggestions?

**Comment by jakebailey** [comment]
After a few completions, we mark the completion list as "complete" to save CPU time as the user continues typing. If the server does any sort of filtering, then when the client (VS Code) stops querying and starts doing its own filtering, things will be missing. That's what's happening here.

In MPLS (and Jedi), the server returns the first completion list as complete the first time and then lets the client do the rest of the filtering. Arguably, this is the simplest way to get good fuzzy matching.

But in our case, we have auto-import completions we'd also like to save work on calculating if their names aren't similar, which requires more filtering, and so we can't mark the first completion as complete (without including a world's worth of auto-import suggestions).

This will take a bit of work to figure out how to fix up efficiently, maybe move some matching back into Pylance to save work internally rather than trying to go for full completeness.

**Comment by jakebailey** [comment]
This should be fix via #608 as well.
