### ISSUE TITLE
Showing error even if the file runs

### ISSUE THREAD

**Issue by Shubham20091999** [microsoft/pylance-release#219]
## Environment data

-   Language Server version: 2020.8.0
-   OS and version: Windows 10 2004
-   Python version (& distribution if applicable, e.g. Anaconda):  3.7.7

## Expected behaviour

Error ("Single close brace not allowed within f-string literal; use double close brace") should not have occured

## Actual behaviour

Error occuring at closing brace in \{video} in the code provided

![image](https://user-images.githubusercontent.com/43275176/89710208-805f2280-d99e-11ea-9568-aed212839a5a.png)

## Logs

```
[Info  - 5:34:19 pm] No configuration file found.
[Info  - 5:34:19 pm] Setting pythonPath for service "Youtube Downloader": "C:\ProgramData\Miniconda3\python.exe"
[Error - 5:34:19 pm] stubPath d:\Projects\Python\Youtube Downloader\typings is not a valid directory.
[Info  - 5:34:19 pm] Assuming Python version 3.7
[Info  - 5:34:19 pm] Assuming Python platform Windows
[Info  - 5:34:19 pm] Searching for source files
[Info  - 5:34:19 pm] Found 2 source files
[BG] analyzing: d:\Projects\Python\Youtube Downloader\logic.py ...
[BG]   parsing: d:\Projects\Python\Youtube Downloader\logic.py (56ms)
[BG]   parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\2and3\builtins.pyi (71ms)
[BG]   binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\2and3\builtins.pyi (28ms)
[BG]   binding: d:\Projects\Python\Youtube Downloader\logic.py (1ms)
[BG]   checking: d:\Projects\Python\Youtube Downloader\logic.py ...
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\json\__init__.pyi (1ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\json\__init__.pyi (1ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\os\__init__.pyi (10ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\os\__init__.pyi (4ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\subprocess.pyi (5ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\subprocess.pyi (2ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\sys.pyi (6ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\sys.pyi (6ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\typing.pyi (21ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\typing.pyi (5ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\abc.pyi (1ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\abc.pyi (0ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi (14ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi (0ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\third_party\2and3\typing_extensions.pyi (1ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\third_party\2and3\typing_extensions.pyi (1ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\json\decoder.pyi (1ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\json\decoder.pyi (0ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\posix.pyi (0ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\posix.pyi (1ms)
[BG]     parsing: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\os\path.pyi (6ms)
[BG]     binding: c:\Users\Shubham\.vscode\extensions\ms-python.vscode-pylance-2020.8.0\server\typeshed-fallback\stdlib\3\os\path.pyi (0ms)
[BG]   checking: d:\Projects\Python\Youtube Downloader\logic.py (195ms)
[BG] analyzing: d:\Projects\Python\Youtube Downloader\logic.py (351ms)
```

## Code Snippet / Additional information

```python
os.system(f'''Dependencies\youtube-dl -o "{outLoc}\{video}.%(ext)s" --add-metadata -x --audio-format {ext} "https://www.youtube.com/watch?v={video.id()}">NUL''')
```

**Comment by erictraut** [comment]
Thanks for the bug report. There is indeed a bug in Pylance here, but there's also a bug in your code. Let me explain.

You are using the backslash in your string in two locations. In Python strings, the backslash character is used to start an escape sequence. It is supposed to be followed by one or more other characters to complete the escape sequence. For example "\n" represents a new-line character and "\048" is an octal escape sequence. A full list of recognized escape sequences can be found in [the Python documentation](https://docs.python.org/3/reference/lexical_analysis.html). Escape sequences that are not listed are considered bugs. In the current version of the Python interpreter, these cases are flagged with a deprecation warning, but in future versions they will be rejected as an error. Here's the text from the spec:

>Changed in version 3.6: Unrecognized escape sequences produce a DeprecationWarning. In a future Python version they will be a SyntaxWarning and eventually a SyntaxError.

Pylance was incorrectly handling the unrecognized escape sequences found in your string literal. When it saw the backslash, it skipped over the next character. In the case of "\{video}", it skipped the open bracket character. I've fixed this problem, and it will be corrected in the next version of Pylance.

The way to fix the bug in your code is to use a double backslash "\\" rather than a single backslash.

Pylance contains code to warn you about unrecognized escape sequences, but this diagnostic is suppressed when typeCheckingMode is "off". If you set typeCheckingMode to "basic", you will see a warning for this condition.

@savannahostrowski & @jakebailey , we might consider enabling the `reportInvalidStringEscapeSequence` diagnostic rule (at "warning" severity level) even when typeCheckingMode is "off". It's a useful diagnostic even for users who are not interested in type checking, and it will not produce false positives. Let me know what you think here.

**Comment by Shubham20091999** [comment]
Thank You
I had did not know we have to use \\ when we use triple quotes. I was not getting any error or warning while running the code so I assumed that there was no error
Thanks for the Information

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202081-13-august-2020

**Comment by forestGoroli** [comment]
Thank you very much.
The same problem occurs in version 2020.9.8.
I confirmed that no error occurs when only the f-string is used. However, the same error message is displayed when the f-string and raw-string are combined, and a backslash is placed before the braces, as shown in the following example.

`x = 'filename'
windows_path = rf'aaa\{x}'`

I often use this style of writing to specify a file path in the Windows environment.
I'm sorry if my syntax is wrong on this.

**Comment by erictraut** [comment]
Thanks for reporting. You are correct that pylance was not handling backslashes correctly within a raw f-string. This will be addressed in the next release.

**Comment by forestGoroli** [comment]
@erictraut 
I appreciate your prompt reply.
That fix would be very helpful for me.
