### ISSUE TITLE
Seaching where has this function called does run slowly

### ISSUE THREAD

**Issue by miaokela** [microsoft/pylance-release#2190]
Seaching where has this function called does run slowly

**Comment by judej** [comment]
Thanks for the report. Are you referring to find all references? or call hierarchy? 

The first time you ask for "find all references" it would be slow, is it always slow? 

thanks

**Comment by miaokela** [comment]
"find all references" always takes five seconds at least.And the status bar is being loading "finding reference" when i refind all references without terminate previous unfinished load.

**Comment by miaokela** [comment]
and the process Electron has not terminated after i close the vscode for a long time when i use macbook.

**Comment by heejaechang** [comment]
how big is your workspace?

**Comment by heejaechang** [comment]
by the way, can you use this template https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue to add more info on your issue so that we can have at least some logs ("python.analysis.logLevel": "Trace") to see what is going on while "find all references" are running?

**Comment by miaokela** [comment]
Thanks a lot. I have figured out that there is too many files in the workspace, include history plugin files and pycache that may be analysed,i have no idea. Fortunately, i can find references quickly in a empty folder.
