### ISSUE TITLE
Required and NotRequired not allowed in TypedDict alternative syntax

### ISSUE THREAD

**Issue by sethmlarson** [microsoft/pylance-release#2194]
The new `Required` and `NotRequired` types don't work with the [`TypedDict` alternative syntax](https://www.python.org/dev/peps/pep-0589/#alternative-syntax).

```python
from typing import TypedDict
from typing_extensions import Required, NotRequired

Example = TypedDict("Example", {"required": Required[int], "not_required": NotRequired[int]})
```

Both the `Required[int]` and `NotRequired[int]` are highlighted red with the message:

```
(variable) NotRequired: Type[NotRequired]
"NotRequired" is allowed only within TypedDict
```

**Comment by erictraut** [comment]
At the time I implemented this support, the PEP was not yet finalized, and we were debating whether `Required` and `NotRequired` should be supported in the alternative syntax. My view was that it should not be, since the normal syntax is the preferred form, and I didn't want to encourage the use of the non-standard form. The author of the PEP was leaning more toward supporting the alternative syntax. He said that he'd update the PEP to clarify whether of not it was supported, but I don't think that ever happened.

I'm curious, is there a reason you want to use this non-standard form of `TypedDict` over the standard class-based form? The latter is more readable and doesn't require runtime evaluation of the type annotations.

**Comment by sethmlarson** [comment]
@erictraut I believe the alternative syntax is the only way to represent keys that aren't valid Python names (like `1` or `key-with-dash`). Without support for `Required` and `NotRequired` there's currently no way to represent invalid Python names as required keys in a TypedDict with required and not-required keys:

```python
# These work:
AllRequired = TypedDict("AllRequired", {"key-with-dashes": Any})
AllNotRequired = TypedDict("AllNotRequired", {"key-with-dashes": Any}, total=False)

# But there's no way to do the sub-class trick/hack with the alternative syntax without Required/NotRequired:
_NotRequiredKeys = TypedDict("_NotRequiredKeys", {"optional-key-with-dashes": Any}, total=False)

class RequiredKeys(_NotRequiredKeys):
  required-key-with-dashes: Any  # This can't be an invalid identifier :(
```

**Comment by erictraut** [comment]
That's a good point. I've added support for `Required` and `NotRequired` for the alternative syntax form. This will be included in the next release of pylance.
