### ISSUE TITLE
Incorrect reportUnnecessaryComparison between dict keys and set

### ISSUE THREAD

**Issue by ajkaijanaho** [microsoft/pylance-release#2216]
Issue Type: <b>Bug</b>

The following script

```Python
print({ "foo": "bar" }.keys() == { "foo"})
```

is reported as

```
Condition will always evaluate to False since the types "dict_keys[str, str]" and "set[str]" have no overlap
```

yet running the script prints `True` (at least in Python 3.9).

Extension version: 2021.12.2
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.16GB free)|
|Process Argv|--crash-reporter-id b2eebf21-5c30-4125-bbf3-c0dc2ddb4b12|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by erictraut** [comment]
This check involves some heuristics because in Python any object type can potentially handle comparison to any other object type. 

The heuristics we use for this diagnostic check are discussed in [this issue](https://github.com/microsoft/pyright/issues/1744).

I can think of three options:
1. Remove the `reportUnnecessaryComparison` diagnostic check entirely because the heuristics will inevitably fail in some cases like this one.
2. Live with the edge cases of `reportUnnecessaryComparison` and use `# type: ignore` or `# pyright: reportUnnecessaryComparison=false` or a different code form to suppress the error in this case.
3. See if the typeshed maintainers would be open to adding an `__eq__` method to the `dict_keys`, `dict_values`, and `dict_items` class definitions to work with the existing heuristics.

Since this is a strict-mode diagnostic check and this is the first time someone has reported an issue, I'm not inclined (without more evidence) to conclude that we should completely remove this check. That eliminates option 1.

I think we could do a combination of option 2 and 3.

If you are interested in pursuing 3, I encourage you to file an issue (or better yet, a PR) in the typeshed github repo.

**Comment by ajkaijanaho** [comment]
I think 1 is not necessary, as this is sometimes a useful thing to catch. I think both 2 & 3 are feasible.

My issue in this bug stems mostly in from Pylance stating that the code is wrong with certainty. "Condition will always evaluate to False" is simply not true in this case. I would be happy if the wording was a little more tentative given that this is a heuristic, not a certainty.

Also, I would like it to be possible for me to override this particular check on this particular line, like I can do with mypy's edge cases (I do not want to disable all checking on that line, since that might hide other issues unrelated to this one). My understanding is that # pyright: reportUnnecessaryComparison=false is a file-level override, and that is too broad for my tastes.

Option 3 is also possible, but since I do not know Pyright's logic very well, I feel I am not the right person to advocate any particular change.

**Comment by ajkaijanaho** [comment]
As an aside: my experience is that strict mode is too strict (for example, dealing with third-party libraries with typing issues) and non-strict checking is too loose. I would prefer the option of too strict with case-by-case override (as I mentioned above). I understand it is a conscious choice not to provide one, but this makes Pylance a bit of a problem for me.

In my experience, Pylance is superior to other checkers, but it has its quirks, and it is difficult to wrestle with when they surface.

**Comment by erictraut** [comment]
If you find that strict mode is too strict, you can start with basic mode and then enable a subset of strict-mode diagnostic checks for your project. These can be enabled one at a time as you make changes to your code base. Pyright was designed with this incremental approach in mind.

You can disable the errors on a single line by using the `# type: ignore` comment on the end of that line. This approach is specified in PEP 484, so it's standard across type checkers.

**Comment by judej** [comment]
Another workaround would be to cast the left hand side to a `set`. 

You could also have Pylance ignore this error with:
`print({ "foo": "bar" }.keys() == { "foo"}) # pyright: ignore[reportUnnecessaryComparison]`
