### ISSUE TITLE
In the absence of stub files, auto-import should use better heuristics for picking preferred import path

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#222]
This suggestion comes from @tiangolo and is copied from https://github.com/microsoft/pyright/issues/922. 

The auto-import feature is not as smart as it could be about choosing the best import path for a symbol. With stub files, a library author can (but doesn't need to) specify a single export point for a symbol. For libraries that are missing stub files, a symbol is often imported and then re-exported by many submodules.

The auto-import feature should generally choose the shortest import path — i.e. the highest-level module that re-exports it.

**Comment by heejaechang** [comment]
now we handle this situation. for import alias (re-exported by stub files), we only show one that is the shortest path (smallest ".") in completion.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020

**Comment by tiangolo** [comment]
Hey all! Thanks for this. :rocket: 

(And as I'm writing this on Dec 25, Merry Christmas/happy holidays to you all! :christmas_tree: :mrs_claus: )

I recently released a new version of FastAPI with support for `mypy --strict`, with explicit symbol re-export and integrated type annotations in the source files (instead of additional/external `.pyi` files).

This was all after some email conversations with @erictraut finding the best ways to support type analysis, and after reading the guidelines in https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md

Now, when I'm on a block like:

```Python
from fastapi import 
```

...and I trigger autocompletion there, Pylance/Pyright now can correctly detect that there are symbols available to import from the top level, like `Query`. And the final result is:

```Python
from fastapi import Query
```

That's great! :tada: :clap: 

---

But then when using auto-import, it is not behaving as I would imagine.

With a snippet like:

```Python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def main(name: str = Query()):
    pass
```

...if I trigger autocompletion/auto-import for `Query`, it suggests to import from the source of that function `Query`, at `fastapi.param_functions`.

![Selection_215](https://user-images.githubusercontent.com/1326112/103138918-57ce8f80-46d7-11eb-990a-c88ad28592a6.png)

I would expect it to suggest:

```Python
from fastapi import Query
```

---

## Environment data



-   Language Server version: Pylance language server 2020.12.2 (pyright 6feebac9)
-   OS and version: Ubuntu 18.04, VS Code 1.51.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7 in a venv with a fresh FastAPI installation.

---

I imagine this is the right place to comment about this, but let me know if it should be in https://github.com/microsoft/pyright/issues/922 or if I should create a new issue.

Thanks! :cake: :coffee:

**Comment by erictraut** [comment]
Thanks @tiangolo for the issue. I think this one is different from the one that kicked off this thread. Could you please open a new issue for pylance-release? I just reviewed the latest version of `__init__.py` checked in to the fastapi repo, and it looks correct to me, so this must be a bug in pylance's auto-import logic. It should prefer the shorter import path.

**Comment by tiangolo** [comment]
Thanks for the speedy reply and feedback @erictraut ! :nerd_face: 

I just created a new issue here: https://github.com/microsoft/pylance-release/issues/774
