### ISSUE TITLE
False positive `reportUnnecessaryComparison` with `global`/`nonlocal` and unpacking

### ISSUE THREAD

**Issue by Molkree** [microsoft/pylance-release#2233]
## Environment data

-   Language Server version: v2022.1.0
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10

## Expected behaviour

No error warnings.

## Actual behaviour

```
Condition will always evaluate to False since the types "Literal['UP']" and "Literal['DOWN']" have no overlap
Condition will always evaluate to False since the types "Never" and "Literal['DOWN']" have no overlap
```

## Code Snippet / Additional information

```python
state = (0, 0), "UP"


def foo(instruction: str) -> None:
    global state
    position, direction = state
    if instruction == "C":
        state = position, "UP" if direction == "DOWN" else "DOWN"
    elif instruction == "P":
        if direction == "UP":
            print(direction)
        elif direction == "DOWN":
            print(direction)


for instruction in "CP":
    foo(instruction)
```

Pylance reports that `direction` can never be `"DOWN"`, but executing this code you will see `"DOWN"` printed.

This also works in a similar case with `nonlocal`.
I can only reproduce it when unpacking `global`/`nonlocal`, there are no errors if I create `direction = "UP"` and modify it directly.

**Comment by erictraut** [comment]
This is a limitation of the type inference logic in pyright, the type checker that underlies pylance.

You have not provided a type declaration for the variable `state`, so pyright needs to infer its type based on the values that are assigned to it. It's able to evaluate the type of the expression `(0, 0), "UP"`. But when it attempts to evaluate the type of the expression `position, "UP" ...`, it needs to first evaluate the type of `position`. But `position` is dependent on `state`. Because of this circular dependency, it cannot fully evaluate all assigned types.

I don't see a way to fix this issue. When you pack and unpack values into a tuple, type inference becomes very challenging because of shared dependencies between values.

I can offer you three workaround:
1. Disable `reportUnnecessaryComparison`. This is an advanced, strict type checking rule that is not enabled by default because it has some potential for false positives. If you don't want to disable it, you will need to help the type checker by doing one of the following.
2. Don't pack your variables into a single tuple value. Use separate variables for `direction` and `position`.
3. Provide a type annotation for `state` so the type checker doesn't need to infer its type.

```python
state: tuple[tuple[int, int], Literal["UP", "DOWN"]] = (0, 0), "UP"
```

**Comment by Molkree** [comment]
That's unfortunate but thank you for the explanation and workarounds. Not sure if this should be just closed or left open.
