### ISSUE TITLE
No warnings for incorrect explicit implementations of Protocols

### ISSUE THREAD

**Issue by nalkhish** [microsoft/pylance-release#2254]
## Environment data

-   Language Server version: v2022.1.1
-   OS and version: Windows 10 Home 19042.1466
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10 64-bit

## Expected behaviour

Pylance can verify that explicit subclasses of a protocol do not implement a protocol correctly

PEP 544:
![image](https://user-images.githubusercontent.com/43485534/149671483-8dac5c02-5c32-4cdf-a35b-9c0c82665d7c.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/43485534/149671303-a1935887-6ddb-4d4e-ba42-60bcad6257da.png)

Pylance only recognizes that my implicit subclass fails to implement "some_num" but it does not warn me that my explicit subclass is wrong.

**Comment by erictraut** [comment]
The current implementation is based on the assumption is that if you declare a variable (either a class variable or an instance variable) in an explicit base class, even if that base class is a protocol, that the variable is implemented in that base class. However, I can see how that might not be a good assumption.

Mypy appears to treat such a variable as "implemented" if it receives an assignment in the protocol base class and "not implemented" if it doesn't. That sounds like a reasonable approach.

Since this is a core type checking feature, I've created a tracking issue for pyright: https://github.com/microsoft/pyright/issues/2878.

**Comment by nalkhish** [comment]
Interesting. Thanks for correctly placing the issue!

**Comment by erictraut** [comment]
This new check will be incorporated in the next release of pylance.

**Comment by heejaechang** [comment]
this should be fixed in the latest release.
