### ISSUE TITLE
sql auto completion

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/pylance-release#2291]
Some python IDEs offer sql auto completion like https://stackoverflow.com/questions/64214953/autocomplete-sql-query-in-db-execute-on-vscode https://stackoverflow.com/questions/65013610/way-to-have-sql-intellisense-or-autocompletion-inside-code-strings-in-visual-stu asked. It would be useful if this extention could offer this. Also, since https://github.com/mtxr/vscode-sqltools lack developer. It might be useful if microsoft take that over and integrate into the python extension.

**Comment by judej** [comment]
Thanks for the request. Will wait for upvotes in this issue.
Thanks

**Comment by judej** [comment]
Discussion (https://github.com/microsoft/pylance-release/discussions/2591) covers highlighting SQL keywords. I will dupe this request to that enhancement. We will not provide SQL intellisense since it is so far outside Pylance's scope. But keyword highlighting is I believe, a meaningful feature in that direction
