### ISSUE TITLE
Pylance thinks ast.stmt is not compatible with ast.AST

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pylance-release#231]
## Environment data

-   Language Server version: 2020.8.0 (pyright 4b16a648)
-   OS and version: Windows 18362.959
-   Python version: CPython 3.8.5

## Expected behaviour

As stated in the Python official document (https://docs.python.org/3/library/ast.html), `ast.AST` is the base class for all ast node classes. So `ast.stmt` should be compatible with `ast.AST`.

## Actual behaviour

See below screenshot:
![Snipaste_20200813_003135](https://user-images.githubusercontent.com/25131775/90042301-18da0780-dcfd-11ea-980e-4d17ec1f9984.png)
![Snipaste_20200813_003148](https://user-images.githubusercontent.com/25131775/90042317-1f687f00-dcfd-11ea-8a31-5b22af86e401.png)

## Code Snippet / Additional information

```python
import ast
from typing import List

def do_something(nodes: List[ast.AST]) -> None:
    pass

tree = ast.parse("a = 1")
do_something(tree.body)
```

**Comment by erictraut** [comment]
The problem here is that the type of the expression `tree.body` is `List[seq]`, but the method `do_something` is annotated to take a `List[AST]`. The type argument for `List` is invariant, so it must be an exact match. This is required because `List` is a mutable container. (For more details about type invariance, refer to PEP 483.)

The correct fix in this case is to switch to a Sequence, which is the immutable analog of a List.

Changing your code to the following will make the type error go away:
```
def do_something(nodes: Sequence[ast.AST]) -> None:
    pass
```

**Comment by MapleCCC** [comment]
@erictraut Thank you for your kind reply. You are right. This is not a bug. The error goes away after switching to `typing.Sequence`. I will close the issue then.

**Comment by erictraut** [comment]
This is a frequent source of confusion, so I've written some additional documentation to help provide clarity.

https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md
