### ISSUE TITLE
Auto import feature doesn't work properly

### ISSUE THREAD

**Issue by bootstrap123002** [microsoft/pylance-release#2312]
I want to get the auto-import hint when inputing an Class or Function defined in another module. But pylance don't give the correct  hint. 
In this case,I want to get the quick fixes suggestion for 'DictCursor' defined in the 'cursors.py' of pymysql package. Bud the amazing thing is when I reload the window ,it will give the correct hint whit quick fixes in a few seconds,and soon disappeared.
After review the trace output of pylance,the 'cursors.py' has been parsed.
(99398) [BG(1)]     parsing: /Users/python/vscode/vscode/venv/lib/python3.9/site-packages/pymysql/cursors.py [fs read 0ms] (9ms)
(99398) [BG(1)]     binding: /Users/python/vscode/vscode/venv/lib/python3.9/site-packages/pymysql/cursors.py (4ms)
What happened,is there any configuration should be setup?

https://user-images.githubusercontent.com/64769877/151911962-18e80282-7302-4041-a702-1b8d54ecad8d.mov

**Comment by heejaechang** [comment]
it looks like a bug. thank you for reporting the issue!

**Comment by bootstrap123002** [comment]
It's my honor for getting confirmed by you.The problem also happened with the module in the subdirectory of the package.&nbsp;
Be waiting for the next update for the solution.




------------------------------------------------------------
it looks like a bug. thank you for reporting the issue!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heejaechang** [comment]
so, it is happening since DictCursor is not in __ all __ nor there is pyi file. so we don't know whether it is a part of public API or not. so we dropped it.

**Comment by heejaechang** [comment]
Since we don't want to bloat completion with bunch of symbols, I dont think we want to enable it by default, but I added a hidden option as an escape patch.

Basically, if one adds this to setting.json, we will treat the package special and scan more symbols from it.

"python.analysis.packageIndexDepths": [[packageName: string, depth: number, forceIndexing: boolean]*],

ex)
```
"python.analysis.packageIndexDepths": [["pymysql", 3, true]],
```

packageName is the name of the package, depth means how deep the scanner will scan, forceIndexing means it will include all symbols in the py file discovered regardless of __ all __ or py.typed.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.3.2, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202232-16-March-2022)

**Comment by cdce8p** [comment]
> ```
> "python.analysis.packageIndexDepths": [["pymysql", 3, true]],
> ```

@heejaechang That is awesome! Would something similar work for local files too? I keep having issues where auto-import / suggestions don't work or symbols aren't found. Even with `"python.analysis.indexing": true`.
Would love an option to say Pylance "always index these core and helper modules + constants file".

_The project I currently work on usually doesn't use `__all__` and hasn't added `py.typed` yet since we are still in the process of adding all full type annotations._

_With `indexing: true` I also get a warning._
```
Workspace indexing has hit its upper limit: 2000 files
```

**Comment by heejaechang** [comment]
@cdce8p the option should work with multiroot workspace as long as root is installed with pip install -e ...

but that being said, I opened this issue to track UX on multiroot workspace - https://github.com/microsoft/pylance-release/issues/2601

**Comment by ajlive** [comment]
Is there any way to use the packageIndexDepths workaround without specifying the package? The inability to get auto-imports for most of the third-party packages I use is frustrating, and I don't want to have to configure these package by package.

**Comment by bschnurr** [comment]
for default 3 levels I believe this is it:
```json
"python.analysis.packageIndexDepths": [
	["",3]
],
```

**Comment by ajlive** [comment]
Thanks, that works!

**Comment by rustam-ashurov-mcx** [comment]
Using normal VS code (not Insiders) with this config in settings.json gives me: an "Unknown Configuration Setting" popup in VS Code and the config line looks gray-out. Also can not say that it fixes anything for me.
Do I need to install anything more/else than the latest VS Code + Python/Pylance extensions to make it work for me?
