### ISSUE TITLE
Overriden methods navigation doesn't work

### ISSUE THREAD

**Issue by yaroslavsadin** [microsoft/pylance-release#2315]
Issue Type: Feature

I'm working on rather large code base and I can't navigate through overriden methods of a base class. Say, I have:

```python
class A:
    def foo():
        pass

class B(A):
    pass

class C(B):
    def foo():
        pass
```

Doing Show all References on A's foo doesn't show C's foo.

Extension version: 2022.1.5
VS Code version: Code 1.63.2
OS version: Ubuntu 18.04

**Comment by heejaechang** [comment]
currently, pylance does only exact symbol match but doesn't do symbol propagation which will find all derived types and overriden symbols to find all matches.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by yaroslavsadin** [comment]
Why do you close it? Feature is still wanted

**Comment by debonte** [comment]
@yaroslavsadin, over the past couple weeks we've been aggressively purging old items from our issue tracker. In this case I think we should have actually marked the issue as fixed.

It looks like this is working as of 2022.4.1, fixed by the same change that fixed https://github.com/microsoft/pylance-release/issues/813. It works for me. Can you confirm?

**Comment by yaroslavsadin** [comment]
@debonte this indeed works in 2022.4.1, thanks!
