### ISSUE TITLE
Commented code at the end of a method doesn't collapse with method

### ISSUE THREAD

**Issue by desktopgun** [microsoft/pylance-release#2321]
I've gotten so use to how it worked before, please help me fix this issue unless it was intentionally changed or there is a setting that needs to be changed. This has just happened recently. 

Issue - 

Expected result - Commented code at the end of a method should collapse with the method.
Actual result - Commented code at the end of a method doesn't collapse with the method. Please see screenshots

The whole method including commented code at the end, collapse after I disable pylance.

I've checked all 17 pages of issues and didn't find anything related.

Python version 3.8.10
System - Ubuntu 
Visual Studio Code

![Screenshot from 2022-02-01 14-51-56](https://user-images.githubusercontent.com/74871813/152057977-b80cadf3-4c64-44eb-9f82-833410876fb2.png)

![Screenshot from 2022-02-01 14-54-56](https://user-images.githubusercontent.com/74871813/152057964-63c01930-a732-4547-8ac9-7d2ff5b751eb.png)

Thank you,
David Catalfano
desktopgun@gmail.com

## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by debonte** [comment]
I have an attempt at a fix in https://github.com/debonte/pyrx/tree/issue2321_foldingTrailingFunctionComment. It works for comments after functions, but not comments after if blocks. Here are my notes from when I was working on this:

- Figured out why this folding wasn't happening as I expected for comments after if statements and the like. It's because the start character of those statements is the : of the suite, not the start of the statement, and I'm determining which comments should be included by comparing the comment's # indent against the indent of the range's start node.
- I'm really not sure how to handle this. Should we limit the functionality to comments after functions and classes? The behavior currently is a bit strange
  - Comments after if statements (and the like) are folded only if heavily over-indented (past the : column)
  - Comments above the next function would be folded with the current/previous function. This is the worse issue. Not sure yet how to differentiate the two. I guess if there's no newline between the comment and the next block/node/function/class/whatever?

**Comment by erictraut** [comment]
I don't think there's a good reason to include the ":" token in the suite parse node. I don't recall any reason why I would have included that when writing the parser, so it might have just been an oversight. So if it helps to omit the ":" from the suite node, you could change the parser accordingly.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.2.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023211-1-february-2023-prerelease)
