### ISSUE TITLE
Union requires two or more type arguments when using tuple as argument

### ISSUE THREAD

**Issue by Mr-Pepe** [microsoft/pylance-release#2323]
## Environment data

-   Language Server version: v2022.1.5
-   OS and version: Kubuntu 21.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.11, built from source

## Expected behaviour

Pylance does not show an error message.

## Actual behaviour

Pylance reports: "Union requires two or more type arguments"

## Code Snippet / Additional information

```python
from typing import Union

types = (int, float)
my_union = Union[types]
```

**Comment by erictraut** [comment]
The behavior is correct. Type annotations do not support tuples for type arguments, nor do they support the use of variables as type arguments. Type annotations must be statically evaluatable and cannot use complex expressions.

Mypy (another popular Python type checker) emits an error in this case as well.

**Comment by Mr-Pepe** [comment]
But I can execute the code and see that the union gets created as if I ran `Union[int, float]`. Is that undefined behavior?

**Comment by erictraut** [comment]
Just because it doesn't generate a runtime exception doesn't mean that it's valid. The `Union` special form was introduced in PEP 484 to facilitate static type checking, and this PEP specifies the rules that govern the validity of type expressions. For example, the statement `y: Tuple[1 + 1, ..., int]` will not generate an exception at runtime, but that type annotation is an invalid type expression.

**Comment by Mr-Pepe** [comment]
Thank you very much for the explanation!

**Comment by prashantgupta24** [comment]
@erictraut thank you for your explanation!

If we had to ignore this error using `diagnosticSeverityOverrides`, what error type would we use?

```
"python.analysis.diagnosticSeverityOverrides": {
    "report???": "none"
}
```

**Comment by erictraut** [comment]
@prashantgupta24, are you saying that you want to leave an invalid type annotation in your code but tell pyright to suppress the error associated with it? Such an annotation will not be honored by pyright, so it would be preferable to fix it rather than suppress the error.

This is reported under the `reportGeneralTypeIssues` diagnostic rule. This is a general "catch all" rule, so if you disable it, you'll disable many type checking diagnostics, so I wouldn't recommend that.
