### ISSUE TITLE
Inner class cannot be specified as generic.

### ISSUE THREAD

**Issue by iHalt10** [microsoft/pylance-release#2339]
## Environment data

-   Language Server version: 2022.2.0 (pyright 65946fc7) starting
-   python version: 3.9.9
-   mypy: 0.931

## Expected behaviour
I wrote it with "string forward reference" to specify the inner class as "generic".
It works fine on mypy, but I get an error on "pylance".

In the description of "reportGeneralTypeIssues" in [Diagnostic Severity Rules](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md), it was "... unsupported operations ...".
However, I think that writing in "string forward reference" is an operation that works fine.

## Actual behaviour
<img width="597" alt="SC 2022-02-06 15 18 53" src="https://user-images.githubusercontent.com/24728342/152670929-f13556db-71ff-41f1-a66a-d68915f447a4.png">

## Code Snippet / Additional information

```python
from typing import TypeVar, Generic

T = TypeVar("T")


class Base(Generic[T]):
    pass


class Outer(Base["Outer.Inner"]):
    class Inner:
        pass

```

**Comment by erictraut** [comment]
This is a form of circular reference that will not work with pyright, the type checker that pylance is built upon. You are attempting to reference a member of class `Outer` within its base class list. The base class list is required to establish the class hierarchy and MRO (method resolution ordering) for the class, and that information is needed to properly resolve a reference to a class attribute such as `Inner`. You'll need to eliminate the circular reference if you want this to work with pyright.

I suspect that mypy is able to handle this particular case because it is a multi-pass analysis architecture, but pyright uses a single-pass (just-in-time) analysis technique that is much faster, but this technique doesn't permit this type of circular reference.

**Comment by iHalt10** [comment]
Thank you for your response.

In other words, ”circular reference" operation will not be added in the future.

Oh well, close this issue.
Thank you.
