### ISSUE TITLE
pylance considers imports used in `# type: X` comments as unused, when used with a context manager/for loop.

### ISSUE THREAD

**Issue by jhgg** [microsoft/pylance-release#2340]
## Environment data

-   Language Server version: 2022.2.0 (pyright 65946fc7)
-   OS and version: Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Expected behaviour

Consider the following code:

```py
from typing import Any

with foo() as a: # type: Any
    pass
    
for i in range(50): # type: Any
     pass
```

It would be expected that `Any` is considered used, as it appears in a type comment.

## Actual behaviour

Pylance considers `Any` as being unused, however, it infact is used, and removing it from being imported would break the type comment. This is valid, as per PEP-484: https://www.python.org/dev/peps/pep-0484/#type-comments

**Comment by erictraut** [comment]
Pylance includes limited support for old-style (Python 2.x) `# type` comments. In particular, it supports `# type` comments in contexts where a modern (Python 3.x) type annotation syntax is supported. That doesn't include variables for context managers or for loops. Since these old-style `# type` comments are deprecated, we don't plan to expand support.

You will need to switch to use modern syntax if you want to provide annotations for these variables.
```python
a: Any
with foo() as a:
    pass

i: Any
for i in range(50):
     pass
```

Alternatively, you could use a `cast` call if you want to override the inferred type of the expression.
```python
with cast(Any, foo()) as a:
    pass

for i in cast(Any, range(50)):
     pass
```

**Comment by jhgg** [comment]
Thanks for the reply, we'll adjust accordingly.
