### ISSUE TITLE
python.analysis.autoImportCompletions -> false by default

### ISSUE THREAD

**Issue by zolvaczi** [microsoft/pylance-release#2344]
Please make this feature disabled by default, as it is regularly auto-importing random things as I type code. Very annoying!

**Comment by judej** [comment]
Thanks for your suggestion. Will wait for upvotes on this request.

**Comment by CodeCrazy-ywt** [comment]
I don't think this feature should be disabled by default, because you don't need to go to the top, write `import xxx` and `from xxx import xxx`, and go back (sometimes you may go to the wrong place) as you code, which is not convenient. As for importing things you don't want as you type `enter`, you can set `"editor.acceptSuggestionOnEnter"` to `"smart"` or `"off"`.

**Comment by Simakeng** [comment]
Every time when I try to type `imp` then press `Tab` in order to generate `import`, it always gives me `import imp`, which is really annoying. A time-saving feature that ended up wasting my time fixing the trouble it caused.

This feature could be useful, but I don't think the suggestions generated by autoImport should take precedence over contextual statements, which most of the time the entered word is more relevant to.

The first three options in the example below are all generated by autoImport, but they are all from different packages, none of which are related to the context.
![image](https://user-images.githubusercontent.com/20399522/155439480-0b29daa9-2fa2-43d8-98f6-20599023f7b7.png)

**Comment by zolvaczi** [comment]
@CodeCrazy-ywt, I understand what was the aim with this feature, and it might work with Typescript (a language I don't use) but it is impossible to reliably autoimport things for Python. It always gives suggestions from packages that I don't intend to use. Small annoying things like this can be enough to deter people from start using Visual studio code, which otherwise is a great tool!

**Comment by OlofHarrysson** [comment]
My code started having a bunch of random imports added from this that I only caught in my PR. I'll admit I'm a bit trigger-happy on the tab key.

Disabled for now. Would love to use it, but will need some way to eliminate it importing things when I'm trying to tab-complete variable names and the likes.

**Comment by Rufus-SN** [comment]
Was this closed by virtue of not enough upvotes?  I was working on legacy code, and wondered "Where did those imports come from?" so I commented them out, to see if they were needed (they weren't).   Then when more unneeded imports were added, I did a search and wound up here.  The problem with the "auto-add" imports is they don't go away when you remove the typo that caused them to appear in the first place!

**Comment by dhensen** [comment]
Somehow the request in this issue got satisfied, but I'm not happy with it: https://github.com/microsoft/pylance-release/issues/3604

It is changing stuff that used to work, instead people that are annoyed should toggle it off. 
This is basically the same as maintaining backwards compatibility, but I guess that's a hard thing to ask.

**Comment by debonte** [comment]
@dhensen, consider upvoting https://github.com/microsoft/pylance-release/issues/3579

**Comment by jbmusso** [comment]
To anyone who ends up here and wonders why Pylance isn't automatically completing imports, consider adding this to `settings.json`. This might fix the issue you're having, by reverting back to the default behavior:

```
"python.analysis.autoImportCompletions": true,
```

**Comment by merc1er** [comment]
> To anyone who ends up here and wonders why Pylance isn't automatically completing imports, consider adding this to `settings.json`. This might fix the issue you're having, by reverting back to the default behavior:
> 
> ```
> "python.analysis.autoImportCompletions": true,
> ```

It looks like VS code doesn't recognize this setting for some reason:
<img width="477" alt="Screenshot 2023-12-20 at 11 27 44" src="https://github.com/microsoft/pylance-release/assets/21960643/873a0b2b-c03e-412f-a7cf-2d5a2dc94019">
