### ISSUE TITLE
conflict with editor.wordBasedSuggestions setting

### ISSUE THREAD

**Issue by mikh3x4** [microsoft/pylance-release#2354]
Issue Type: <b>Bug</b>

Install Pylance extension and in settings enable "editor.wordBasedSuggestions" option. 

What should happen: if there is no pylance suggestions vscode should fallback to word suggestions (dumb autocomplete) from other words present in the file even if the grammer doesn't match. (Same symptom as here https://github.com/Microsoft/vscode/issues/15411) 

Extension version: 2022.2.0
VS Code version: Code 1.64.0 (Universal) (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:17.224Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-167-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 65242ef1-f96e-4276-b8e8-96bcfdfbbf65|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: kessel|
|OS|Linux x64 4.15.0-167-generic|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 1200)|
|Memory (System)|62.83GB (46.08GB free)|
|VM|0%|
</details>

**Comment by luabud** [comment]
@jrieken quick question -- it seems the Python/Pylance extension disables the `editor.wordBasedSuggestions` setting because when we had it enabled in the past, users complained that the word based completions option would show up before the Pylance ones. Do you know if it would be possible for us to fallback to word based suggestions only when we fail to provide completions for any reason?

**Comment by jrieken** [comment]
> , users complained that the word based completions option would show up before the Pylance ones. 

Do you have exact details on that? Word based completions are implemented to only ever show when a "more important" provider fails to yield a result. So, it does work as fallback just has you have suggested. The definition of "more important" is derived on how well the document selector of a provider scores. Saying that you target `python` (e.g use language ids in the selector) gives the high score, using `*`,  to say that you support all languages, gives you the low score. There is more docs here https://github.com/microsoft/vscode/blob/a330b89e5d83293bacee75ac910626b64ad8c3fd/src/vscode-dts/vscode.d.ts#L11844

**Comment by luabud** [comment]
Thanks for the context and for linking the docs, @jrieken! It could be that we were doing something wrong/unexpected then. We'll investigate further 😊

**Comment by heejaechang** [comment]
@jrieken problem of word based suggestion was it showing completion when we know no item should be shown. and people doesn't know what word based suggestion is and what language server based syntactic, semantic suggestion is, complains that we are suggesting wrong thing (specially if you hit enter, it puts the selected item unintentionally)

simple example is declaration location such as

import package as [/* here */]

since it is alias name decl location, there shouldn't be anything suggested but word based does since we return nothing.

that being said, you should be able to override this behavior in settings (settings.json) if you want it back.

```
"[python]": {
        "editor.wordBasedSuggestions": true
    }
```

**Comment by jrieken** [comment]
> @jrieken problem of word based suggestion was it showing completion when we know no item should be shown. and people doesn't know what word based suggestion

I understand, this is the typical view when authoring a language server. However, users and use-cases are different and sometimes they want to type things that aren't matching semantics and grammars. You shouldn't patronise users but lets them use suggestions the way they want, e.g in your sample it is very possible that word-based suggestions are correct esp when I have multiple documents open that have such imports already
