### ISSUE TITLE
Argumented async context manager infers yield type as Any

### ISSUE THREAD

**Issue by DevilXD** [microsoft/pylance-release#2355]
It looks like Pylance breaks on async context manager typing, as long as the decorated generator accepts at least one argument. Argumentless generators work as expected. Using `AsyncGenerator[int, None]` as the return type, instead of `AsyncIterator[int]`, yields the same behavior.

Linting the same code with MyPy shows that both generators infer `int` correctly.

## Environment data

-   Language Server version: `v2022.2.0`
-   OS and version: Win7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Code

```py
from typing import AsyncIterator
from contextlib import asynccontextmanager

@asynccontextmanager
async def gen1() -> AsyncIterator[int]:
    yield 1

@asynccontextmanager
async def gen2(thing: str) -> AsyncIterator[int]:
    yield 2

async def main():
    async with gen1() as result1:
        reveal_type(result1)
    async with gen2("yes") as result2:
        reveal_type(result2)
```

## Expected behaviour

```
Type of "result1" is "int"
Type of "result2" is "int"
```

## Actual behaviour

```
Type of "result1" is "int"
Type of "result2" is "Any"
```

## Logs

https://pastebin.com/xHtWKVyM

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported. The sample above results in the expected behavior. Both revealed types are `int`. Can you confirm that the sample produces an `Any` type for the `result2`?

**Comment by DevilXD** [comment]
![Yes](https://i.imgur.com/TmliitE.png)

**Comment by DevilXD** [comment]
Yes, it does on my side, as shown on the above screenshots. I've ran into this while designing a context manager for retrying an `aiohttp` request when connection issues arise, and managed to extract the exact conditions under which it happens via the code attached in the original issue description. I'm not sure why you can't repro this on your side, could it be related to the 3.8 Python version I'm using?

**Comment by erictraut** [comment]
Thanks for confirming. I'm still not able to repro the problem, and neither have the other members of the Pylance team.

I can tell from the screen shot above that the code in the screen shot isn't identical to the sample you posted in the but report. I can see a `yield 1` at the top of the screen shot, but that's different from the code in the sample. Can you double check that you are using the exact same code as in your sample at the beginning of this post? I want to eliminate the possibility that we're looking at different code.

If you hover over the symbol `gen2` in the `with` statement, what type is shown? I would expect it to say `gen2: (thing: str) -> _AsyncGeneratorContextManager[int]`. If it doesn't show this, please right click on the `asynccontextmanager` symbol and choose "Go To Declaration". That should take you to the type declaration used for that decorator. It should take you to the type stub file `contextlib.ypi`, and the declaration should look like this:

```python
if sys.version_info >= (3, 7):
    def asynccontextmanager(func: Callable[_P, AsyncIterator[_T_co]]) -> Callable[_P, _AsyncGeneratorContextManager[_T_co]]: ...
```

**Comment by erictraut** [comment]
Pyright (and Pylance) are not written in Python and don't depend directly on the version of Python that you have installed. However, Pyright does attempt to determine the version of Python that you're running so it can apply the version-specific logic in the stdlib type stubs (such as the `if sys.version_info >= (3, 7)` conditional in your screen shot above). You can also manually specify which version of Python you would like Pyright or Pylance to assume. In my attempt to repro the problem you're reporting, I'm manually overriding it to specify Python 3.8.

The fact that `_P` is being evaluated as `Any` is a good clue. You're correct that `ParamSpec` was added in Python 3.10, but since type checkers don't "execute" the code they're analyzing, they're able to use newer language features than the runtime supports. In this case, the definition of `ParamSpec` should be coming from the `typing_extensions.pyi` type stub, which is bundled with Pylance. If you return back to the `contextlib.pyi` file and scroll to the top, you'll find the line `from typing_extensions import ParamSpec`. Please right click on `typing_extensions` and choose "Go to Declaration". This should take you tot he copy of `typing_extensions.pyi` that is bundled with Pylance. My suspicion is that you have a different (older) copy of `typing_extensions.pyi` or `typing_extensions.py` somewhere in your project, and you're overriding the version that ships with Pylance.

**Comment by DevilXD** [comment]
Hmm, I see how it works now.

This is my `PramSpec` declaration from `typing_extensions`:

![ParamSpec](https://i.imgur.com/BPEQLPD.png)

It appears to be coming from `C:\Python38\Lib\site-packages\typing_extensions-stubs\__init__.pyi`. Based on this, I'm assuming there's some random leftover package still installed. Here's what `pip list` tells me:

![pip list output](https://i.imgur.com/HzDVtCQ.png)

I'm assuming this `types-typing-extensions` is the problem here then?

**Comment by erictraut** [comment]
Yes, that's the problem. PEP 561 specifies that type checkers should resolve stub packages before typeshed stubs. But you have some out-of-date stub package installed for typing_extensions. If you uninstall that from your Python environment, the problem should go away.
