### ISSUE TITLE
Autocompletion/Intellisense bug on Process object method

### ISSUE THREAD

**Issue by Nicolacarrino** [microsoft/pylance-release#2383]
## Environment data

-   Language Server version: v2022.2.1
-   OS and version: Ubuntu 20.04.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10 (from Ubuntu distro)

## Expected behaviour

![Jedi_join](https://user-images.githubusercontent.com/26420873/153964749-816eabe2-3cfc-45e1-ad9a-9002807fbf37.png)
This shows what I would expect from auto-completion, in this case I am using Jedi language server(it can be noted from the different code highlighting). Jedi is able to recognize that `p` is of type `Process` and suggests related methods.
## Actual behaviour

![Pylance_join](https://user-images.githubusercontent.com/26420873/153964768-bcdad76d-346d-48dd-99ad-746d697c5625.png)
This shows what I get from auto-completion when using Pylance. Pylance is not able to give any hints in this case. This lack of auto-completion has happened to me several times with Pylance.

## Logs

```
None
```

## Code Snippet / Additional information

```python
from multiprocessing import Process
import os
import time as time

processes = []
num_processes = os.cpu_count()


def square_numbers(a):
    for i in range(a * 10):
        b = i ** 2
        print(b)
        time.sleep(0.1)
    print("Process Done")


# Create processes
for i in range(num_processes):
    p = Process(target=square_numbers, args=(i,))
    processes.append(p)

for p in processes:
    p.start()

for p in processes:
    p.join()

print("All processes Done!")
```
I would like to know how to solve this behavior of Pylance.

**Comment by erictraut** [comment]
This is related to the type inference rules in Pyright, the static type analyzer that underlies Pylance. In this case, the type of the variable `processes` is inferred to be `list[Any]` because of the assignment `processes = []`. For situations like this, you can provide a type hint, like this: `processes: list[Process] = []`. If you're interested in more of the technical details, you might want to check out [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

**Comment by Nicolacarrino** [comment]
I added the type hinting and Pylance is able to suggest a completion.
I was going through your suggested documentation [type-concepts](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md) and I have found something odd. If I use `reveal_type()` to check the type of p
```python
for p in processes:
    reveal_type(p)
```
the result is `Runtime type is 'Process'` both if I use type hinting:
```python
processes: List[Process] = []
```
and if I do not:
```python
processes = []
```
So why Pylance cannot recognize that the type is `Process` when the typing extension can without problems?

**Comment by Nicolacarrino** [comment]
I have slightly modified the previous code to test `reveal_type`. I have added `reveal_type` to the code. This is the new code:
```python
from multiprocessing import Process
import os
import time as time
from typing_extensions import reveal_type


processes = []
num_processes = os.cpu_count()


def square_numbers(a):
    for i in range(a * 10):
        b = i ** 2
        print(b)
        time.sleep(0.1)
    print("Process Done")


# Create processes
for i in range(num_processes):
    p = Process(target=square_numbers, args=(i,))
    processes.append(p)

for p in processes:
    # Start code change
    # p.start()
    reveal_type(p)
    exit()
    # End code change

for p in processes:
    p.join()

print("All processes Done!")

```
If I now run this code, the output is `Runtime type is 'Process'` both if I use type hinting:
```python
processes: List[Process] = []
```
and if I do not:
```python
processes = []
```


> Is that consistent with what you're seeing?

Yes it is consistent. If I insert `reveal_type` without running the code what you described is what I see. What I do not understand is the different behavior of `reveal_type` at runtime. In that case it is able to recognize the type even without type hinting.

**Comment by erictraut** [comment]
Type annotations (aka "hints") do not have an impact at runtime. The code will run the same regardless of whether a type annotation is present. Annotations are meant as a way for developers to statically declare the types of variables for static analysis tools (like Pylance). In cases where type annotations are absent, a static analysis tool needs to "infer" the type of a variable. It uses various heuristics to do so, but there are times when the type of a variable cannot be inferred because there is insufficient information or the inference heuristics lead to ambiguous results. By adding a type annotation in a case like this, you remove the ambiguity.

The `reveal_type` call doesn't exist at runtime, so if you insert this into your code and attempt to run it, you'll see a runtime crash.

**Comment by Nicolacarrino** [comment]
Thank for the explanation, I didn't know that. 


> The `reveal_type` call doesn't exist at runtime, so if you insert this into your code and attempt to run it, you'll see a runtime crash.

The only thing that still seems strange is that I can actually run that code without crashing and `reveal_type` prints on the console `Runtime type is 'Process'`.

**Comment by erictraut** [comment]
Ah, are you importing that symbol from `typing_extensions`? Runtime support for `reveal_type` was added to the latest version of the `typing_extensions` published just last week. So if you're using the absolute latest version, then that would explain why it's not crashing at runtime. Prior to last week, that would have crashed. :)

**Comment by Nicolacarrino** [comment]
Ah, yes I imported `from typing_extensions import reveal_type`. Now it makes sense, I didn't know it was added last week.
Thank you for your time, you clarified my concerns, so for me the issue can be closed.
