### ISSUE TITLE
spurious error using pytorch Tensor.item()

### ISSUE THREAD

**Issue by joelgrus** [microsoft/pylance-release#24]
## Environment data

-   Language Server version: 2020.6.1
-   OS and version: Ubuntu 18.04.4
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.4

Here's the code

```python
import torch

t = torch.tensor(0)
x = t.item()

values = ['a', 'b', 'c']
print(values[x])
```

![Screenshot from 2020-07-01 17-25-02](https://user-images.githubusercontent.com/1308313/86303663-5fe2c200-bbc1-11ea-941b-f3bc3ad64acf.png)

![Screenshot from 2020-07-01 17-25-28](https://user-images.githubusercontent.com/1308313/86303511-d7642180-bbc0-11ea-9985-db7fe3a7773b.png)

in theory a `Tensor.item()` could be a bool or a float, but here the dtype is int64, so I believe it has to be an int. I get that it's hard for the type system to know that, but now I'm stuck with an "error".

**Comment by gramster** [comment]
Hi Joel,

As a short term workaround, you can use a comment to override the type inference, as in:

```
x = t.item()  # type: int
```

It's not ideal if you don't want these in your code, but I expect there are going to be many edge cases that we will have to address over the next few months (this is part of the reason it is a separately-installed extension and not installed by default by the Python extension).

**Comment by joelgrus** [comment]
it doesn't like that either (nor `typing.cast`, which I also tried)

![Screenshot from 2020-07-01 20-54-09](https://user-images.githubusercontent.com/1308313/86314738-42bbec80-bbdd-11ea-9435-73eda81b632e.png)

**Comment by gramster** [comment]
Interesting, so that hint seems to have coerced x *before* the assignment. @EricTraut, any ideas for a workaround here?

**Comment by erictraut** [comment]
Type annotations don't perform type coercion or casting. They declare the type of a symbol. In this case, the type annotation that you added ("# type: int") indicates that the type of `x` is an `int`. You are attempting to assign a value that is of type `Union[int, float, bool]` to an `int`, hence the type error.

Incidentally, I wouldn't recommend using type comments unless you need to maintain backward compatibility with Python 3.5 or earlier. As of Python 3.6, variables can be annotated using a more readable syntax like this:
```
x: int = t.item()
```

The method `Tensor.item` is annotated to return a value of type `Union[int, float, bool]`. I don't know much about pytorch, so I can't say for sure whether this is correct or a bug in the type stub. I'm surprised to see that the `Tensor` class is not a generic class. Perhaps that's the problem here. Since it's not generic, the authors of this type stub assume that it supports elements that are int, float or bool. 

There are a couple of workarounds here:
1. Use an assert.
```
x = t.item()
assert isinstance(x, int)
```
2. Use a cast.
```
x = cast(int, t.item())
```

I almost always prefer asserts over casts since the former affords a level of runtime validation. I tend to use casts only as a last resort because they disable all type checking.
