### ISSUE TITLE
Why doesn't Pylance like `str.__class__.__module__`?

### ISSUE THREAD

**Issue by bland328** [microsoft/pylance-release#2420]
Using Python 3.10.2 _(under macOS 10.15.7)_, referencing `str.__class__.__module__` works as I expect (the value being `"builtin"`) and seems legitimate enough to me, but Pylance complains `Cannot access member "__module__" for type "property"` `Member "__module__" is unknown Pylance(reportGeneralTypeIssues)`.

Why doesn't Pylance like this construct? Am I being cheekier than I realize, or shall I raise this as bug?

**Comment by erictraut** [comment]
This problem is related to the way that the typeshed stubs (which define type information for the built-in Python types) models the `__class__` attribute. It [models it as a property](https://github.com/python/typeshed/blob/ee8aa1e0120fcc0bd88421e2a5d39fad4243e473/stdlib/builtins.pyi#L88), presumably so it is treated as read-only.

I can offer a couple of suggestions:
1. If you want to file a bug in the typeshed repo — or submit a PR for a fix, you're welcome to do so. We regularly pull updated versions of these type stubs, so if you or someone else introduces a fix, Pylance will reflect that change.
2. If you change your code to `str().__class__.__module__`, it will work as you expect. That's because Pylance will think that you are accessing the property value if you use `str().__class__`.

**Comment by bland328** [comment]
Ah...makes plenty of sense. Thanks very much!
