### ISSUE TITLE
Inheriting Hint for 'with as' clause

### ISSUE THREAD

**Issue by Fikralaksana** [microsoft/pylance-release#2421]
When i use 'with as' clause, the new variable not inherit hint. I think it will be helpfull if it does.

spot the different color on method. VScode not detect `execute()` method on `session` variable
![image](https://user-images.githubusercontent.com/79677026/155828306-2047ecd7-1043-4f08-ba8c-d08557b0bc5f.png)

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by Fikralaksana** [comment]
it is all about `hint` in vscode.
`hint` is working fine using `=`, type suggestion also working.
![image](https://user-images.githubusercontent.com/79677026/156759420-b3d8740f-6146-431a-b1cd-3165bf25b051.png)
![image](https://user-images.githubusercontent.com/79677026/156759353-8a3eec80-3785-48d0-b0fa-22cd5001b556.png)

I expect the same in "with as", but it is not.
`hint` return any, not ObjectClass type. type suggestion not show anything.
![image](https://user-images.githubusercontent.com/79677026/156759622-dd3c0899-7eb6-4a03-b2f7-ed2598017bc8.png)
![image](https://user-images.githubusercontent.com/79677026/156759702-d09ac22d-b913-4365-9d47-8aacfae136bf.png)

**Comment by erictraut** [comment]
Please do not post screen shots of code. A minimal self-contained code snippet in text form is much more helpful.

Here's a transcription of your screen shot:

```python
class ObjectClass:
    param1: str
    param2: int
    param3: float

    def method1(self):
        pass

obj = ObjectClass()

with obj as new:
    print(new)
```

The reason pylance is not giving you completion suggestions is because the code is invalid. If you run this code in the Python interpreter, you will see that it generates a runtime exception because `ObjectClass` does not support the context manager protocol, but you're attempting to use an instance of `ObjectClass` in a `with` statement. To make this work, you would need to implement an `__enter__` and `__exit__` method in the class.

If you set the "python.analysis.typeCheckingMode" setting from "off" (the default) to "basic", pylance will provide more error messages including the error above.

**Comment by Fikralaksana** [comment]
how about this code? I can execute this code with no error.
but  the suggestion for `session` variable still not shown. 
library used : sqlalchemy

```
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

async def getCost( db_session: AsyncSession, product_id: str = "product", code : str = "code") -> dict:
    async with db_session as session:
        try:
            response_msg = 'Parameter Cost'
            response_code = '00'
            resp = {}

            if code!='code':
                code="'{code}'".format(code=code)
            if product_id!='product':
                product_id="'{product_id}'".format(product_id=product_id)
    
            cost = await session.execute("select value as cost from table_name where category = 'column1' and code = {code} and product = {product}".format(code=code,product=product_id))
            cost = cost.first()
            if cost:
                resp= dict(cost)
            else:
               response_msg = 'Product not found'
               response_code = '1'
                
            await session.commit()
            return {
                'response_msg': response_msg,
                'response_code': response_code,
                'response_data': resp
            }
        except gevent.Timeout:
            await session.invalidate()
            return {
                'response_code': '99',
                'response_msg': 'DB transaction was time out...'
            }

        except SQLAlchemyError as e:
            print(e)
            await session.rollback()
            return {
                'response_code': '99',
                'response_msg': str(e)
            }
```

**Comment by erictraut** [comment]
That's because sqlalchemy's interface is described using a set of community-maintained type stubs, and these type stubs are incomplete. These stubs can be found within the "typeshed" repo. The exact line that explains the lack of completion suggestions in the code above can be found [here](https://github.com/python/typeshed/blob/cda3d9cf722f38f5646e99cacbc169620e268786/stubs/SQLAlchemy/sqlalchemy/ext/asyncio/session.pyi#L53). You'll note that the `__aenter__` method is present, but its return type is not annotated. So Pylance has no way of knowing what the context manager returns in this case. 

If you'd like, you can file a bug (or even better, a PR) in the typeshed repository. Pylance regularly picks up new versions of these type stubs, so any bug fixes or improvements will show up relatively quickly in Pylance.

I'll also note that the developers who maintain sqlalchemy are actively working on an updated version of the library that contains inlined type information so the community will not need to rely on separate stubs in the future. We're working with these developers to make sure that Pylance and this future version of sqlalchemy work great together. I realize that might be a frustrating answer because it doesn't give you an immediate solution, but some of these issues take time to solve.

**Comment by Fikralaksana** [comment]
alright, thanks for your detailed explanation. 
I will send them a bug then, because the code structure is from their documentation too.
