### ISSUE TITLE
Pylance doesn't handle type hinting overloading/unions/NoReturn correctly

### ISSUE THREAD

**Issue by bucknerns** [microsoft/pylance-release#2424]
## Environment data

-   Language Server version: Pylance  v2022.2.5-pre.1 
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Cpython 3.9.7

When using NoReturn with unions/overloading pylance should not warns about branches that aren't possible.
Expected behavior is that the call to error where raise_error is True should be handled like raise Exception.

    from __future__ import annotations
    from typing import NoReturn, overload, Literal

    @overload
    def error(msg, raise_error: Literal[True]) -> NoReturn: ...

    @overload
    def error(msg, raise_error: Literal[False]) -> None: ...

    @overload
    def error(msg, raise_error: bool) -> NoReturn | None: ...

    def error(msg, raise_error: bool) -> NoReturn | None:
        ...

    # Expected behaviour : This block should function like the block below
    did_error = False
    b = 1
    if did_error:
        b = None
        error("Some error", raise_error=True) # Detects proper type NoReturn
    b.bit_length # "bit_length" is not a known member of "None" Pylance[reportOptionalMemberAccess]

    did_error = False
    b = 1
    if did_error:
        b = None
        raise Exception("Some error")

    b.bit_length # Works fine, no complaints

**Comment by erictraut** [comment]
This is a known limitation within the current implementation of pyright, the type checker that powers pylance. A `NoReturn` call affects the code flow graph, but the code flow graph is required for type evaluation, and type evaluation is required to determine whether a call returns `NoReturn`. This circular dependency is handled by performing "lightweight" type evaluation of call expressions that doesn't rely on the power of the full type evaluation engine. This lightweight mechanism is able to handle all common cases, but it can't deal with complexities like overloads where some of the overloads return `NoReturn` and some do not.

This issue is related to [this open issue](https://github.com/microsoft/pyright/issues/3001) in pyright's issue tracker.

I don't have a suggested workaround at this time other than to avoid using an overload that returns `NoReturn` for a subset of signatures.

**Comment by bucknerns** [comment]
Closing in favor of the other issue.

**Comment by multimeric** [comment]
So the linked issue relates to general support for `NoReturn`, but this particular case where some overloads are `NoReturn` (`Never`) seems to still be an issue. Should I open a new issue in pyright?
