### ISSUE TITLE
Stub generation some times generates empty blocks

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#244]
## Environment data

-   Language Server version: 2020.8.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3

## Expected behaviour

Should not generate empty blocks.

## Actual behaviour

```
ci_and_not_headless = False
if sys.platform == "darwin" or sys.platform.startswith("linux") and ci_and_not_headless:
    ...
if sys.platform.startswith("linux") and ci_and_not_headless:
    ...
```

## Logs

```
XXX
```

## Code Snippet / Additional information

Actual python file that led to the generation of the pyi file above.
```python
import importlib
import os
import sys

from .cv2 import *
from .data import *

# wildcard import above does not import "private" variables like __version__
# this makes them available
globals().update(importlib.import_module("cv2.cv2").__dict__)

ci_and_not_headless = False

try:
    from .version import ci_build, headless

    ci_and_not_headless = ci_build and not headless
except:
    pass

# the Qt plugin is included currently only in the pre-built wheels
if (
    sys.platform == "darwin" or sys.platform.startswith("linux")
) and ci_and_not_headless:
    os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "qt", "plugins"
    )

# Qt will throw warning on Linux if fonts are not found
if sys.platform.startswith("linux") and ci_and_not_headless:
    os.environ["QT_QPA_FONTDIR"] = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "qt", "fonts"
    )

```

**Comment by erictraut** [comment]
If/else statements at the global level of a file are sometimes important to include in a stub, especially when they're conditionally testing for sys.platform or sys.version_info. When the stub writer is emitting this, it doesn't yet know whether there's anything important to include within the body of the if/else. I could add a bunch of extra complexity to the stub writer to avoid this, but since there's no harm in including it, and I expect that users will need to clean up this sort of thing anyway, I'd prefer to not add the extra complexity.
