### ISSUE TITLE
Tuple length checking doesn't work with `tuple()` constructor

### ISSUE THREAD

**Issue by xavdid** [microsoft/pylance-release#2445]
I searched for other, similar issues, but none seemed to cover this exact case.

<h3> Environment data </h3>

-   Language Server version: 2022.2.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): `3.10.0`
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

An error should be raised if `tuple()` is assigned to a tuple type of defined length

<h3> Actual behaviour </h3>

No error is raised

<h3> Code Snippet / Additional information </h3>

```python
from typing import Tuple
Point3D = Tuple[int, int, int]

t1: Point3D = 1, 2, 3  # correct no error
t2: Point3D = 1, 2, 3, 4  # correct error; Element size mismatch; expected 3 but received 4
t3: Point3D = () # correct error; Element size mismatch; expected 3 but received 0
t4: Point3D = tuple() # expected error, none thrown
```

Given that `tuple()` returns an empty tuple, I'd expect `t3` and `t4` to behave identically. But, only one throws an error.

**Comment by erictraut** [comment]
This is expected behavior, although I admit that it's less than ideal.

The type returned by the constructor call `tuple()` is dictated by the typeshed stub file `builtins.pyi`. Here's the [specific line](https://github.com/python/typeshed/blob/77e5a2d4680341f20b351bc7d5554a8fa31ec1b6/stdlib/builtins.pyi#L774) that declares the `__new__` method. You'll see that the parameter `__iterable` has a default value. If you call the constructor and don't provide an argument for this parameter, the type variable `_T_co` is not populated, so the resulting type is `tuple[_T_co@tuple]`, which is effectively `tuple[Any]`.

A potential fix is for the typeshed stub to provide an overload that specifies a return type of `tuple[()]` if the `__iterable` argument isn't provided. You're welcome to file a bug (or a PR) in the typeshed repo. Pylance regularly picks up new versions of the typeshed stubs.

In the meantime, I recommend using the `()` form rather than `tuple()`. Not only is it more terse, but it also avoids this problem from a type checking standpoint.

**Comment by xavdid** [comment]
Fair enough, thank you!

**Comment by xavdid** [comment]
I'm happy to file a PR. While I was playing with it, I noticed that `mypy` _does_ handle this as expected. `t4` above throws `main.py:7: error: Incompatible types in assignment (expression has type "Tuple[<nothing>, ...]", variable has type "Tuple[int, int, int]")`.

I think the typeshed PR makes sense in this case, but I wanted to point that out in case it was useful.

**Comment by erictraut** [comment]
Yes, I noticed that mypy handles this case. It probably overrides the type stub in this particular case. I'm reluctant to ignore / override the information in the type stub because that often leads to other problems as the type stubs evolve or improve. It's preferable to solve this problem in the stubs.
