### ISSUE TITLE
Incorrect member function overrided inference.

### ISSUE THREAD

**Issue by kong13661** [microsoft/pylance-release#2449]
## Environment data

-   Language Server version: 2022.3.0
-   OS and version: ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9, Miniconda

## Expected behaviour

![image](https://user-images.githubusercontent.com/28509442/156978566-c0dbda5b-4ed1-4693-8411-8ac2acec0a80.png)

Look at this code.

In class `A`, I definite a function raising Exception. In the member function `b()`, I call the function `self.a()`, and the following code `c = 1` is unreachable (lines 7-8). This right. 

In class `B`, I override the function `a()`. The code `c = 1` (line 17) is reachable now, since the function `a()` does not raise Exception now.

## Actual behaviour

![image](https://user-images.githubusercontent.com/28509442/156979180-d66c16f6-00ab-4811-ba24-034bf2b84c90.png)

Pylance marks the code unreachable.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment]
This is expected behavior. If you want to avoid this, you can do any one (or preferably all) of the following:

1. Make the base class an abstract base class. It should derive from ABC, and the unimplemented method should be decorated with `abc.abstractmethod`.
2. Raise a `NotImplementedError` rather than a general `Exception`.
3. Add an explicit return type annotation for the method in the base class. In your example, it should be `a(self) -> int`.
