### ISSUE TITLE
Class-style TypedDict variables with NotRequired annotations are treated as Required

### ISSUE THREAD

**Issue by munael** [microsoft/pylance-release#2469]
## Environment data

-   Language Server version: v2022.3.1
-   OS and version: Windows 10, 19043
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7

## Expected behaviour

Using NotRequired should work in class-style type definitions just as it does in alias style.

```python
class FooClass(TypedDict):
    x: NotRequired[int]
FooAlias = TypedDict('FooAlias', {'x': NotRequired[int]})
```

## Actual behaviour

![image](https://user-images.githubusercontent.com/5769148/157660178-546d7e03-ff8f-437a-8b43-c157932e93a6.png)

## Logs

```
// Lots of searching for typesheds and analyzing files. No errors.
(20292) Background analysis message: getDiagnosticsForRange
```

## Code Snippet / Additional information

```python
class FooClass(TypedDict):
    x: NotRequired[int]
FooAlias = TypedDict('FooAlias', {'x': NotRequired[int]})
foo: FooClass = {} # Error
foo: FooAlias = {} # No Error
```

**Comment by erictraut** [comment]
Since this is a core type checker issue, I've created a tracking bug in the pyright issue tracker.

**Comment by erictraut** [comment]
I'm not able to repro the problem. There is an error reported for the code sample, but it's not related to `Required` or `NotRequired`. It's because you have redeclared the symbol `foo`.

Here's an updated code sample with no errors reported.

```python
from typing import TypedDict
from typing_extensions import NotRequired

class FooClass(TypedDict):
    x: NotRequired[int]

FooAlias = TypedDict("FooAlias", {"x": NotRequired[int]})
foo1: FooClass = {}
foo2: FooAlias = {}
```

**Comment by munael** [comment]
@erictraut 

"Fixed" example, hopefully :T

### utils.py
```python
try:
    from typing import TypedDict, Required, NotRequired
except ImportError:
    from typing_extensions import TypedDict, Required, NotRequired
```

### test.py
```python
from utils import TypedDict, NotRequired

class FooClass(TypedDict):
    x: NotRequired[int]

FooAlias = TypedDict("FooAlias", {"x": NotRequired[int]})

foo1: FooClass = {}
foo2: FooAlias = {}
```

**Comment by erictraut** [comment]
This is expected behavior. The problem is that you're re-exporting `Required` and `NotRequired` from a local file (utils.py). These are special forms that pyright (the type checker that underlies pylance) needs to handle early in its analysis, so it can't deal with this form of aliasing. You must import them directly from `typing` or `typing_extensions` if you want them to work with pyright.

**Comment by munael** [comment]
@erictraut - But why does it want with the construction style and break only with definition style?

**Comment by erictraut** [comment]
Because the class style makes use of type annotations and the function style doesn't. Those are very different code paths — both within the Python interpreter and in a static type checker. 

I really with that the function style was never introduced, and I recommend against using it. Stick with the class style for best results. The same is true for dataclass, Enum, and NamedTuple definitions.
