### ISSUE TITLE
Turn off ALL analysis rules

### ISSUE THREAD

**Issue by kiruh** [microsoft/pylance-release#2482]
When `python.analysis.typeCheckingMode` is set to `off`, some analysis is still conducted and there is no way to turn it off.

I want to disable the following errors:

> Generic class type cannot be assigned

> Type "type-name" is already specialized

There is no way to disable them through `python.analysis.diagnosticSeverityOverrides` either, since there are no keys for them.

**Comment by erictraut** [comment]
Type analysis is always conducted for code files that you open. That's needed to support basic operations like completion suggestions.

However, I think it's reasonable to move those two diagnostic messages under the reportGeneralTypeIssues diagnostic rule since they are type-related. I've made the change, and this will be in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.3.2, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202232-16-March-2022)
