### ISSUE TITLE
How to install Pylance without also installing the 3 Jupyter extensions?

### ISSUE THREAD

**Issue by Cyberbeni** [microsoft/pylance-release#2510]
I have a script that installs useful stuff for whenever I move to a new Mac and I noticed that trying to install this extension also installs some other extensions. Is there a way to only install this extension?

**Comment by luabud** [comment]
(I edited your message to be more aligned to our code of conduct).

The reason why installing Pylance also installs the Jupyter extensions is because Pylance depends on the Python extension, which automatically installs the Jupyter extension. In the Python extension repo there's a request to drop this "soft" dependency which you can upvote if you're interested: https://github.com/microsoft/vscode-python/issues/18073.

In the mean time, you can uninstall the Jupyter extension, and any updates of the Pylance and the Python extensions will not auto install it again. 

Closing in favour of https://github.com/microsoft/vscode-python/issues/18073.
