### ISSUE TITLE
Add type inference for __class_getitem__

### ISSUE THREAD

**Issue by FizzyJelly** [microsoft/pylance-release#2513]
Hi,

I've just noticed that pylance does not hint objects from **\_\_class_getitem\_\_** method.
```python
T = TypeVar("T")

class Example:

    def __class_getitem__(self, key: T) -> T:
        return key

    def __getitem__(self, key: T) -> T:
        return key
```

Instance getitem nicely infers the type:
![image](https://user-images.githubusercontent.com/37189039/160384953-06abb74a-2cb5-4319-8573-25c4d635cfe9.png)
Whereas it's not the case for class level getitem:
![image](https://user-images.githubusercontent.com/37189039/160385045-43e04bc1-c0f4-4b67-83b3-ed5816b1519c.png)

Could this be added?

Thanks in advance.

Using Python v2022.2.1924087327 and Pylance v2022.3.3

**Comment by erictraut** [comment]
You're using `__class_getitem__` in a manner in which it isn't intended. It was added to support generic classes. The expression `Example["string"]` is assumed to be a specialization of `Example` with a type argument of `"string"` (which is assumed to be a forward reference to a type since it's quoted). For more details, refer to [this documentation](https://docs.python.org/3/reference/datamodel.html#emulating-generic-types).

**Comment by FizzyJelly** [comment]
Okay, thanks for clarification. What I'm doing allows for some neat syntax in my project, I did not dig into the intended use case really.

It works on metaclass \_\_getitem\_\_ though, so I'm set.

![image](https://user-images.githubusercontent.com/37189039/160552909-7215967f-b926-4c74-abe0-6c2a4ecd8d11.png)
