### ISSUE TITLE
Pylance 2022.3.4 shows errors with `python-box` Box class that is not thrown on 2022.3.3 or other IDEs/tools (like running `mypy` directly)

### ISSUE THREAD

**Issue by macintacos** [microsoft/pylance-release#2528]
<h3> Environment data </h3>

-   Language Server version: 2022.3.4
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.2
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

I have a project I'm working on where we use [the `python-box` dependency](https://pypi.org/project/python-box/) on 5.4.1. We have code that looks similar to the following:

```python
from box import Box

some_box: Box = Box(({"hi": {"lol": "foo"}}))
some_other_box: Box = some_box.hi
```

In 2022.3.3 and other IDEs/editors/tools (like Pycharm/Neovim/`mypy`), there are no type issues thrown for the above code. I expect the same in Pylance 2022.3.4.

<h3> Actual behaviour </h3>

In 2022.3.4, the following error is shown:

<img width="732" alt="CleanShot 2022-04-01 at 16 26 10@2x" src="https://user-images.githubusercontent.com/8128941/161336543-8e3b44c5-4265-4a4a-8547-fd80490f2e66.png">

I'm not sure why Pylance thinks it's a BoxList in this context, but it's clearly not/shouldn't be interpreted as one. Even when I check the type in an interpreter, it reports it as a type `box.box.Box` (no BoxList to be found):

```
>>> from box import Box
>>> some_box: Box = Box({"hi": {"lol": "foo"}})
>>> some_other_box: Box = some_box.hi
>>> print(type(some_other_box))
<class 'box.box.Box'>
```

Any help in figuring out what's wrong here? Thanks!

**Comment by erictraut** [comment]
This appears to be an untyped library — no annotations and no stub files. When "python.analysis.useLibraryCodeForTypes" is set to true (as it is by default), Pylance attempts to infer the types based on source. Mypy doesn't do this; it treats all symbols imported from an untyped library as `Any`.

For some complex functions — especially those that are polymorphic (where the return type depends on the input types), type inference can result in incomplete or incorrect return types. Inferred types are sufficient for completion suggestions, but they are often not good enough for static type checking. 

In this particular case, the `Box` class defines a `__getattr__` method that is unannotated. Pylance uses a variety of techniques to infer the return type. Once of the more advanced techniques is called [call-site return type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#call-site-return-type-inference) where it uses the input argument types to infer the return type of a polymorphic unannotated method. This technique is powerful, but it's also extremely costly. There are heuristics in place that determine when it should be used and when it shouldn't. I adjusted one of those heuristics recently to improve performance. This change means that call-site return type inference is no longer used for the `Box.__getattr__` method, and the inferred return type is now `Unknown | Any | BoxList` rather than `Unknown`, as it was previously. 

So this is an unexpected side effect of a small tweak to one of Pylance's internal heuristics.

If you enable static analysis diagnostics (as you have apparently done), we recommend that you set "python.analysis.useLibraryCodeForTypes" to false. This will tell Pylance to no longer attempt to infer return types from untyped libraries, matching mypy's behavior in this respect. Unfortunately, that means you will forego all completion suggestions for symbols that come from any untyped libraries.

The real long-term solution here is for all libraries to include static type annotations. Many library maintainers have already made this investment, but it appears that the maintainers of `python-box` have not. If this library is important to you, you may want to encourage them to do — or even better, contribute PRs to add type information to the library. We've prepared [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) to help library authors add type information.

**Comment by macintacos** [comment]
@erictraut thank you for the insight! I reached out to the maintainers of that project.
