### ISSUE TITLE
Intellisense including from xxx import {haven't specified classes}

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#2533]
For example:

`from PySide6.QtWidgets import QApplication,`

The Intellisense including `QPushButton`  when I type `QP`, and after I selected it, `QPushButton` will be imported automatically. the import will be changed to:

`from PySide6.QtWidgets import QApplication, QPushButton`.

**Comment by heejaechang** [comment]
fix will be in the next release. 

but, it won't be supported out of box since we only include first level symbols in auto import. you will need to use our hidden options to enable it.

in settings.json, put this for us to pick the symbols up for auto import.

``` 
 "python.analysis.packageIndexDepths":[["PySide6",2]],
```

what it basically means is ["package name", "max depth to search"]. "max depth" basically means how many dot you need to access the module you want. 

ex) PySide6.QtWidgets 
this is 2 level deep.

deeper you go, Pylance will take more time to scan python files.

if you put, ["", 2], it will change default depth not one particular library's search depth.

thank you.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.4.0, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202240-6-April-2022)

**Comment by stefanbschneider** [comment]
Adding this to my settings.json, VSCode tells me "Unknown Configuration Setting" and shows the line in reduced colors.

**Comment by willygroup** [comment]
> Adding this to my settings.json, VSCode tells me "Unknown Configuration Setting" and shows the line in reduced colors.
> 
> And it does not seem to work.

Hi, 
I solved it by putting this value to true in `settings.json`:
`"python.analysis.indexing": true,`

**Comment by nicodea** [comment]
I also updated my `settings.json` with the following lines:
```
"python.analysis.indexing": true,
"python.analysis.packageIndexDepths": [["", 10],],
```
This does seem to work for imports _outside_ the workspace. However, imports inside the workspace still seem to be a problem. Has anyone encountered a similar behavior and/or found a solution for it?

**Comment by Smeb** [comment]
Can report a similar issue - imports within the workspace aren't being auto-completed. I'm working in a development container with code in `src` - fixing imports works, and suggestions are given after a file has been opened, but otherwise it'll only complete non-user code.

**Comment by 3pimz3** [comment]
> Can report a similar issue - imports within the workspace aren't being auto-completed. I'm working in a development container with code in `src` - fixing imports works, and suggestions are given after a file has been opened, but otherwise it'll only complete non-user code.

Similar if not the same issue, here. Trying to use Kivy and it's only suggesting imports from official Py libraries.
