### ISSUE TITLE
Cannot import django

### ISSUE THREAD

**Issue by gramster** [microsoft/pylance-release#2561]
### Discussed in https://github.com/microsoft/pylance-release/discussions/2308

<div type='discussions-op-text'>

<sup>Originally posted by **Rishabh7777** January 29, 2022</sup>
I have installed django in my virtual environment and also selected it in VSCode, but still its giving error with Pylance.
![django error](https://user-images.githubusercontent.com/53748445/151686739-791a2c2a-06b0-41a3-aab3-89b45082f44c.PNG)</div>

**Comment by msimkins** [comment]
This may be related to #1081, and it appears that the current (currently selected) 'python' site-packages is not scanned for the packages.

**Comment by mkhuramj** [comment]
@msimkins I have not same but related issue. I have created a docker container for my Django app on Windows. When I import anything from django/drf Pylance resolves it and show the import without any error. But the issue is I  have to manually import everything from Django/DRF, Pylance can't hint or auto import any of the Django/DRF class of any module.

here is my .vscode/settings.json for paths:
`
      "python.defaultInterpreterPath": "/usr/local/bin/python",
      "python.analysis.extraPaths": [
        "/usr/local/lib/python3.9/site-packages",
      ],
      "python.autoComplete.extraPaths": [
        "/usr/local/lib/python3.9/site-packages",
      ],
`

**Comment by heejaechang** [comment]
I answered question on the original discussion (https://github.com/microsoft/pylance-release/discussions/2308). basically, the user selected venv in terminal but didn't pick right venv for vscode. and that's why we don't see django.

**Comment by heejaechang** [comment]
@mkhuramj your issue is completely different one. it is happening since we only scan top level symbols for third party lib for auto import.

you can customize the behavior (with perf hit) if you want with our hidden options. see https://github.com/microsoft/pylance-release/issues/2533#issuecomment-1089268739 for more detail.

but in short answer, if you put this in settings.json, viewsets will be picked up

"python.analysis.packageIndexDepths":[["rest_framework",2, true]],
