### ISSUE TITLE
Pylance should detect methods of a cached_property 

### ISSUE THREAD

**Issue by diepala** [microsoft/pylance-release#2565]
## Environment data
-   Language Server version: pylance v2022.4.0
-   OS and version: Windows 10, VS Code 1.66
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.7, anaconda

## Expected behavior

Pylance should detect a method of a cached_property. i.e. it should be able to show its documentation for example.
It already works with normal properties.

## Actual behavior

Pylance does not find the docs (or definition) of a cached property, but is does when there is a normal property.

## Code Snippet / Additional information

```python
from cached_property import cached_property

class MyProperty:
    def method(self):
        """
        Method to find
        """
        pass

class MyClass:
    @cached_property
    def my_property(self) -> MyProperty:
        return MyProperty()

def main():
    my_class = MyClass()
    my_class.my_property.method()
```

In the main function, the `method` call is not identified.

**Comment by diepala** [comment]
When I say method not identified, I mean that when you place the cursor over the method call, it does not find the documentation for example.

Sorry the script was incorrect, I was trying to make a minimal reproducible example, now it is solved. The problem I mentiond happens when using `cached_property` from the `cached_property`. This function was not introduced in the python standart library until python 3.8, and my project uses python 2.7.

**Comment by erictraut** [comment]
Pyright (the type checker that pylance is built upon) contains a bunch of special-case knowledge of `property`. This includes logic to propagate docstrings from the getter and/or setter method to the resulting property symbol. It's able to do this because it has internal knowledge of how the `property` class works.

Other descriptor classes like `functools.cached_property` that implement the descriptor protocol are not special-cased, at least not in a general way that always forwards docstrings from a decorated function to the resulting descriptor object. That's not generally possible because a static type checker can't have knowledge of the internal behaviors of all descriptor classes.

There is one way that a descriptor class can indicate to pyright that it acts as a decorator for a getter method and therefore should "adopt" the docstring for the getter method. This technique involves the use of a `ParamSpec`, which is described in PEP 612.

Currently, the typeshed stubs define `functools.cached_property` as follows:

```python
    class cached_property(Generic[_T]):
        func: Callable[[Any], _T]
        def __init__(self, func: Callable[[Any], _T]) -> None: ...
        @overload
        def __get__(self, instance: None, owner: type[Any] | None = ...) -> cached_property[_T]: ...
        @overload
        def __get__(self, instance: object, owner: type[Any] | None = ...) -> _T: ...
        ...
```

If we change the definition to use a `ParamSpec`, pyright then knows to forward the docstring.
```python
class cached_property(Generic[_P, _R]):
    func: Callable[_P, _R]
    def __init__(self, func: Callable[_P, _R]) -> None:
        ...
    @overload
    def __get__(
        self, instance: None, owner: type[Any] | None = ...
    ) -> "cached_property[_P, _R]":
        ...
    @overload
    def __get__(self, instance: object, owner: type[Any] | None = ...) -> _R:
        ...
```

I can't tell from your example whether you're importing `cached_property` from `functools` or whether you're defining your own descriptor class called `cached_property`. If it's the latter, you'll need to make a similar change in your code. If you're using `functools.cached_property`, you could file an issue (and optionally submit a PR) in the [typeshed project](https://github.com/python/typeshed/blob/ce88976c0d0a600a51e4e2267dd43256938bfb2a/stdlib/functools.pyi#L168) to update `functools.pyi`. Pyright and pylance regularly pick up updates to typeshed, so any improvements in these type stubs will be reflected in new versions of pylance.

**Comment by diepala** [comment]
By using the `functools.cached_property`, pylance works as expected and find the documentation. The problem appears when using the decorator `cached_property.cached_property`, where `cached_property` is a public library: https://github.com/pydanny/cached-property

**Comment by erictraut** [comment]
The `cached_property` library is completely unannotated, so there's no type information beyond what pyright can infer. I recommend either switching to `functools.cached_property` or contacting the maintainer of `cached_property` and encouraging them to add the relevant type information.

**Comment by diepala** [comment]
Switching to `functools.cached_property` is not possible as the project I am working on uses python 3.7.
I thought it should be possible to support this in pylance, because PyCharm correctly detects the methods by using `cached_property.cached_property`, but no idea how pycharm works.

**Comment by judej** [comment]
After discussion with the team, we are not going to special case libraries. One option would be to contribute stubs for `cached_property`.
