### ISSUE TITLE
Pylance Marking Function Type annotation as Incorrect

### ISSUE THREAD

**Issue by vitonash** [microsoft/pylance-release#2566]
<h3> Environment data </h3>

-   Language Server version: 2022.4.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

No squiggle

<h3> Actual behaviour </h3>

Gives a red squiggle under the type annotation after the function header if it is in quotes. 

<h3> Code Snippet / Additional information </h3>
![image](https://user-images.githubusercontent.com/80741323/163263184-e545a5e9-f2b6-42b5-9ab1-eb7f030d5f2c.png)

```python
XXX
```

**Comment by erictraut** [comment]
The type annotation in your example isn't a valid syntax for type annotations, which is why it's flagged as an error. For information about type annotation syntax, please refer to PEP 484. The proper way to annotate a return type in this case is:
```python
def getAction(self, number: int) -> Action:
    ...
```

If you want to use annotations for purposes other than typing, you can use `typing.Annotated` as described in [PEP 593](https://peps.python.org/pep-0593/).

**Comment by vitonash** [comment]
> The type annotation in your example isn't a valid syntax for type annotations, which is why it's flagged as an error. For information about type annotation syntax, please refer to PEP 484. The proper way to annotate a return type in this case is:
> 
> ```python
> def getAction(self, number: int) -> Action:
>     ...
> ```
> 
> If you want to use annotations for purposes other than typing, you can use `typing.Annotated` as described in [PEP 593](https://peps.python.org/pep-0593/).

thanks, I'm an idiot
