### ISSUE TITLE
Intellisense lists symbols not included in __all__

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#2573]
## Environment data

Pylance language server 2022.1.3 (pyright 98868f26)
Windows 10 Enterprise
Python 3.9.4 (PSF distribution)
VS Code 1.57.1
Panel==0.13.0

## Expected behavior

Only symbols listed in `__all__` would be listed by intellisense.

## Actual behaviour

More symbols are listed.

![image](https://user-images.githubusercontent.com/42288570/163700846-9acf2621-3660-427e-bbcb-d383b7354ebe.png)

## Reproduce

In a fresh python environment pip install the Panel PR https://github.com/holoviz/panel/pull/3411 commit aee337ab6955d490185ae8337a891f2f146ed069

```bash
pip install git+git://github.com/holoviz/panel.git@aee337ab6955d490185ae8337a891f2f146ed069
```

Then open VS Code and enter

```python
import panel as pn

pn.links.
```

**Comment by erictraut** [comment]
This is expected behavior. Adding an `__all__` doesn't indicate that those are the _only_ public symbols in a module. Other symbols declared within that module are also considered public if they do not use naming conventions that indicate they should be private (i.e. an identifier that begins with an underscore). In your screen shot above, I can see that `assert_source_syncable` is declared within that module, and its name implies that it is public.

**Comment by MarcSkovMadsen** [comment]
Ok. Makes sense. Thanks.

**Comment by erictraut** [comment]
Here's an example module that may help provide additional clarity:

```python
# foo is considered private
from .submodule1 import foo

# bar is considered private
from .submodule2 import bar as bar

# baz would normally be considered private, but because it's included in __all__ it is considered public
from .submodule3 import baz
__all__ = ["baz"]

# _private_func is private because its name starts with an underscore
def _private_func() -> None:
    return

# public_func is public because its name doesn't start with an underscore
def public_func() -> None:
    return
```

**Comment by MarcSkovMadsen** [comment]
Thanks for your patience and help.
