### ISSUE TITLE
Could we support `add a type hint` action in VSCode like the PyCharm does?

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#2575]
[Adding type hints in PyCharm](https://www.jetbrains.com/help/pycharm/type-hinting-in-product.html#adding-type-hints):

![屏幕截图 2022-04-18 163930](https://user-images.githubusercontent.com/21306413/163782054-69380c1d-377a-4795-aa61-6492ad42ab29.png)

**Comment by erictraut** [comment]
Thanks for the suggestion.

I'm curios what problem such a code action would solve. Do you think of it mainly as a discoverability aid, since some users don't know about type annotations? It doesn't seem to save any typing because the code action would still require you to type in the text of the annotated type, so presumably the purpose is not to improve the efficiency of adding annotations.

Of course, if the code action could suggest the type for you based on context, that would be a more obvious benefit.

**Comment by heejaechang** [comment]
typescript also provide similar code action and I believe it can improve perf by putting explicit return type. so, return type is no longer needed to be inferred.

**Comment by hans4dev** [comment]
A **type hint** action can solve following problems: 

easily add type-hints and thus

* improve parts of code selectively (readable, documented, performant)
* reduce the manual effort required for looking up the type of a symbol
* reduce the manual effort required to navigate to the symbol where the hint should be added

See also:

* Stackoverflow: [How to add type hints in PyCharm?](https://stackoverflow.com/questions/71904130/how-to-add-type-hints-in-pycharm) - question that inspired this feature-request
* PythonStacks: [Python Type Hints: Why They're Important and How to Use Them](https://www.pythonstacks.com/blog/post/type-hints-python/)
* Better Programming: [Python Type Hints | by Nicholas Obert](https://betterprogramming.pub/how-to-write-clearer-python-code-with-type-hints-330216291b7c)
* Medium: [Why You Should Consider Using Python Type Hints | by Fernando Souza](https://medium.com/vacatronics/why-you-should-consider-python-type-hints-770e5cb1570f)

**Comment by erictraut** [comment]
@hans4dev, I'm very familiar with the benefits of adding type annotations to Python code. Annotations are especially important for function parameters because these types generally cannot be inferred. In most other cases — notably, for local variables, instance variables, and function/method return types — types can be inferred from context, so adding annotations in those cases provides much less value than annotations for function parameters.

In the case of function parameters where a type cannot be inferred, supplying a type annotation requires knowledge of the function and its intent, so the programmer will need to type in the type annotation rather than having a tool provide it for you. I suppose it's possible that we could use some more sophisticated mechanism like an AI model that can make an educated guess about the code's intent based on contextual clues and doc strings. We've explored some techniques like this, but none of them have proven accurate enough to justify adding such a feature.

So my point is that a code action to add an annotation would save time and effort only in cases where a type annotation isn't really needed because the type can already be inferred.

For more information about type inference, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md). Pyright is the static type analyzer that powers the Pylance language server.

**Comment by pukhov** [comment]
Just an idea, similar to the one above:
What about the "Infer return type" command? E.g. an unannotated function returns 3 variables, pylance is clever enough to understand its return type is `tuple[int, str, Any]`. I now copy it manually, then change `Any` to the correct type. Annotating it via shortcut would be faster. 

It would be really helpful for annotating old (and even new) modules! Maybe not something many people would know about, though.

**Comment by bschnurr** [comment]
double clicking on non-Unknown/Any type inlay hint will now insert it.

see
https://github.com/microsoft/pylance-release/releases/tag/2022.7.41
