### ISSUE TITLE
Entry in `django.db.models.base.pyi` prevents `objects` attribute autocompletion

### ISSUE THREAD

**Issue by Real-Gecko** [microsoft/pylance-release#2586]
## Environment data
-   Language Server version: v2022.4.1
-   OS and version: Arch Linux
-   Python version: 3.10.4

## Expected behavior

I have a model manager that has some custom methods I use for model filtering. When I type `Article.objects.` I expect `for_user` method to be in autocomplete suggestions

![image](https://user-images.githubusercontent.com/2231969/163863166-04115307-f6cc-420f-8a69-10f1c9950bcd.png)

## Actual behavior

No suggestion

![image](https://user-images.githubusercontent.com/2231969/163863375-04bb5bf6-c9b1-45f3-96a7-a4db2f496133.png)

## Code Snippet / Additional information

```python
from django.db import models

from django.contrib.auth.models import User

class ArticleManager(models.Manager):
    def for_user(self, user):
        return self.get_queryset().filter(user=user)

class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    user = models.ForeignKey(User, models.CASCADE)

    objects = ArticleManager()
```

## Note

If I go to `base.pyi` and comment the line:

```python
   objects: BaseManager[Any]
```
everything works like a charm.

**Comment by erictraut** [comment]
This is intended behavior. The base class is declaring the type of the class variable `object`. Your subclass doesn't provide a type declaration, so the declared type is inherited from the base class. If you want to override the base class type declaration with a narrower type, such as `ArticleManager`, you can do so in your class by providing an explicit type annotation:

```python
class Article(models.Model):
    ...
    objects: ArticleManager = ArticleManager()
```

This may seem redundant, but it's needed in this case. To understand why, consider the following class hierarchy:

```python
class Parent:
    foo: float | str | None

class Child(Parent):
    foo = 1
```

In this contrived example, the base class declares that the variable `foo` must be of type `float`, `str` or `None`. The child class assigns a value of `1` which is an `int`. That's a valid assignment because an `int` is a subtype of `float`. However, it would be incorrect for a static type analyzer to assume that `foo` is now limited to be an `int`. The base class has indicated that it can be `float`, `str`, or `None`, and the child class hasn't declared otherwise.

The ideal fix in this case is for the django maintainers to make `Model` generic and the type of `objects` a type parameter. Unfortunately, that's not how `Model` is currently declared, which necessitates a manual type declaration for subclasses of `Model`.

For more details about how pyright (the static type analyzer that underlies pylance) handles type declarations and type inference, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

**Comment by Real-Gecko** [comment]
But it can work without explicit type hinting if I comment Pylance stub, watch the video

https://user-images.githubusercontent.com/2231969/163867836-6e180cd5-2fb2-4747-ba22-28ed0e4e1d4d.mp4

**Comment by erictraut** [comment]
Yes, if you comment out the type declaration in the base class, you are removing the declared type provided by the base class. When there is no type declaration provided, pyright falls back on type inference techniques to infer the type of the variable based on assigned values. Type inference does not always produce the correct result, which is why pyright always prefers type declarations if they are present.

**Comment by Real-Gecko** [comment]
Maybe this can be optional? Because I definitely don't like default behavior.

**Comment by Real-Gecko** [comment]
Same for autocomplete of inherited methods:

https://user-images.githubusercontent.com/2231969/163870304-aa12c89d-5975-4f91-a8b3-9e7cf63e8240.mp4

**Comment by erictraut** [comment]
We're unlikely to change this behavior or make it optional. The type analyzer works this way for a reason, and changing the behavior will have other undesirable side effects in many places.

As I said, the ideal fix is for the django maintainers to address the issue in their code. In the meantime, you can work around the issue in your code using a type annotation as suggested.

**Comment by Real-Gecko** [comment]
Then it's easier to disable Pylance completely. Because this way I can code faster.
