### ISSUE TITLE
show document of callable objects doesn't works when "python.autoComplete.addBrackets" is on.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#273]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

show args of `print` function after write `pr` and enter with "python.autoComplete.addBrackets" enable.

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by savannahostrowski** [comment]
Hey there. You should use the new `python.analysis.completeFunctionParens` to enable this functionality in Pylance. 

If there is another issue with this feature, can you please provide more details?

**Comment by jakebailey** [comment]
Assuming this is the signature help that shows up when `()` is typed, it doesn't work because VS Code doesn't trigger it until the user types `(`, `)`, or `,`, and with the snippet that adds the parens, the user's not typing it anymore.

We'd need a way to force VSC to run `editor.action.triggerParameterHints` when the completion item is selected, which could be done via a command, but we have other uses for commands and can't send more than one. Or, the LSP needs an extension to allow us to ask the client to immediately request the hints.

**Comment by byehack** [comment]
> Hey there. You should use the new `python.analysis.completeFunctionParens` to enable this functionality in Pylance.
> 
> If there is another issue with this feature, can you please provide more details?

still now working.

**Comment by jakebailey** [comment]
I found a relatively clean way to handle this. The next release will open the signature help when one of these completion items is selected.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
