### ISSUE TITLE
Apple M1 - Pylance shows type errors for me. Default settings

### ISSUE THREAD

**Issue by ts-ingka** [microsoft/pylance-release#2748]
## Environment data

-   Language Server version: v2022.4.3
-   OS and version: Apple M1 Pro - Monterey 12.3.1
-   Python version (& distribution if applicable, e.g. Anaconda): Brew - 3.10 & 3.9 (tested with same results)

## Expected behavior

No type errors suggested. This code is based off FastAPI docs, colleagues and friends don't seem to have the issue. Tested with Python 3.9 and 3.10.

## Actual behavior

![image](https://user-images.githubusercontent.com/66014422/165710560-7fa8879c-35d6-490d-8de1-d25d2121c233.png)

## Logs

See attached file
[logs.txt](https://github.com/microsoft/pylance-release/files/8580941/logs.txt)

## Code Snippet / Additional information
```python
def read_items(q: str | None):
    results = {"items": [{"item_id": "Foo"}, {"item_id": "Bar"}]}
    if q:
        results.update({"q": q})
    return results
```
Where code came from: fastAPI docs https://fastapi.tiangolo.com/tutorial/query-params/

**Comment by erictraut** [comment]
I presume that you have set "typeCheckingMode" to "basic"? By default, type checking diagnostics are not reported by pylance.

If you enable type checking diagnostics, pylance will enforce type rules. In this particular case, you have declared no type for the local variable `results`, so pyright (the type checker that pylance is built upon) infers its type. The type inference rules pyright uses for dictionary expressions is documented [here](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#dictionary-expressions). In this particular case, the inferred type of `results` is `dict[str, list[dict[str, str]]`. And since the type parameters for `dict` are invariant (see PEP 484 for an explanation), you cannot subsequently add values of a different type without triggering a type violation.

If you want your dictionary to accommodate values of varying types, the recommended approach is to provide the following type declaration.
```python
results: dict[str, Any] = {...}
```

In any case, this is not a bug. It's expected and intended behavior of a static type checker.

**Comment by erictraut** [comment]
I presume your colleagues have configured pylance differently than you. They have probably not enabled type checking diagnostics. Were you able to find where you configured the "python.analysis.typeCheckingMode" setting? You can set it to "off" if you don't want to see type checking diagnostics.

**Comment by ts-ingka** [comment]
@erictraut thanks for your input. I thought the setting was enabled by default, hence my confusion as I have no memory of changing any settings.

**Comment by joshpark8** [comment]
@ts-ingka This is a year late but did/do you happen to use VS Code Insiders? I use Insiders on my M2 MacBook and it was enabled by default, but on my other devices that use the stable release version (an Intel Mac Mini and Intel MS Surface) they both had it off by default.
<img width="477" alt="M2 Settings" src="https://user-images.githubusercontent.com/84344359/226949795-164b603e-b272-42d7-976d-b6b2122fa5a1.png"> 
> Above: M2 Mac settings
> Below: Intel Mac Mini settings
<img width="375" alt="Intel Mac Mini Settings" src="https://user-images.githubusercontent.com/84344359/226950262-843b57c7-278b-4868-9d77-42803cd4d3bc.png">
