### ISSUE TITLE
Python curses module on Windows is never allowed to autocomplete

### ISSUE THREAD

**Issue by lapraswastaken** [microsoft/pylance-release#2763]
## Environment data

-   Language Server version: 2022.4.3
-   OS and version: Windows 10 Home, 21H2
-   Python version): 3.10.2

## Expected behavior

Autocompletion for the `curses` module should work on Windows, to support libraries like [`windows-curses`](https://pypi.org/project/windows-curses/).

## Actual behavior

Autocompletion for the `curses` module doesn't work.

## Code Snippet / Additional information

This can be replicated simply by importing the `curses` module and typing a dot after it:

![image](https://user-images.githubusercontent.com/63134341/166431753-3227ff87-ec5c-48c4-8643-7555d59d34a8.png)

After ctrl+clicking the `curses` import to get to its `__init__.py` file, there are multiple problems telling me that things aren't defined:

![image](https://user-images.githubusercontent.com/63134341/166432053-933c0b04-b0c6-417c-bb2d-45a54333a8fc.png)
![image](https://user-images.githubusercontent.com/63134341/166432070-e41c6b50-b5e7-49e7-94e9-8432fcac2ba0.png)

After ctrl+clicking the `_curses` import at the top of the init file, I see that anything in the `curses` module is only defined if `sys.platform` is not Windows:

![image](https://user-images.githubusercontent.com/63134341/166432280-7aa6a009-8b1b-41c7-b38b-3b7e6969d530.png)

I've installed `windows-curses` via pip and everything runs as it should, but I can't get autocompletion without removing the conditional.

**Comment by debonte** [comment]
Although the type stub files for `curses` that you mention above are shipped with Pylance, they come from https://github.com/python/typeshed. If you believe they should be changed, please file an issue there. If you do that, you might want to reference the PR that added the Windows platform check: https://github.com/python/typeshed/pull/6749.

There's no mention of `windows-curses` in that PR's discussion, so when `typeshed` took that change, I'm not sure if they didn't realize that [`windows-curses`](https://github.com/zephyrproject-rtos/windows-curses) existed, or if perhaps they wanted `windows-curses` to provide it's own dedicated stub file for some reason (ex. because `windows-curses` is not an official part of the stdlib). In any case, you might also want to open an issue on `windows-curses` asking them to provide a stub file.

For what it's worth, I'm working on a side-project that uses `curses`, so I feel your pain. I worked around this by copying `_curses.pyi` into a `typings` subdirectory off the root of my project, renaming it to `curses.pyi`, and then removing the `sys.platform` check. For more information on the `typings` directory, see the entry for `stubPath` [here](https://github.com/microsoft/pyright/blob/ab1fbfc0d6c20c911bb5bf3576939b2223bb5c0d/docs/configuration.md#main-pyright-config-options).

**Comment by TheStef56** [comment]
> Although the type stub files for `curses` that you mention above are shipped with Pylance, they come from https://github.com/python/typeshed. If you believe they should be changed, please file an issue there. If you do that, you might want to reference the PR that added the Windows platform check: [python/typeshed#6749](https://github.com/python/typeshed/pull/6749).
> 
> There's no mention of `windows-curses` in that PR's discussion, so when `typeshed` took that change, I'm not sure if they didn't realize that [`windows-curses`](https://github.com/zephyrproject-rtos/windows-curses) existed, or if perhaps they wanted `windows-curses` to provide it's own dedicated stub file for some reason (ex. because `windows-curses` is not an official part of the stdlib). In any case, you might also want to open an issue on `windows-curses` asking them to provide a stub file.
> 
> For what it's worth, I'm working on a side-project that uses `curses`, so I feel your pain. I worked around this by copying `_curses.pyi` into a `typings` subdirectory off the root of my project, renaming it to `curses.pyi`, and then removing the `sys.platform` check. For more information on the `typings` directory, see the entry for `stubPath` [here](https://github.com/microsoft/pyright/blob/ab1fbfc0d6c20c911bb5bf3576939b2223bb5c0d/docs/configuration.md#main-pyright-config-options).

Recently ```typeshed``` repo accepted a [pull request](https://github.com/python/typeshed/pull/11241) making a change that lets pylance autocomplete when using curses. Can you update pylance so that it downloads the last version of typeshed?

**Comment by erictraut** [comment]
@TheStef56, thanks for the heads up. I just updated the typeshed stubs in pyright. Pylance will pick those up the next time it syncs with pyright.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2024.4.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20244101-10-April-2024-PreRelease)
