### ISSUE TITLE
type information is lost in list comprehension

### ISSUE THREAD

**Issue by beauxq** [microsoft/pylance-release#2780]
The list comprehension can yield a more general type than the typing information provides, leading to false positive type errors.

```python
MyTypeOfLiterals = Literal[1, 2]


def f() -> MyTypeOfLiterals:
    g: Tuple[MyTypeOfLiterals, ...] = (1, 2)
    return_from = [x for x in g]
    return return_from[0]
```

## Expected behavior

no error

## Actual behavior

`Expression of type "int" cannot be assigned to return type "MyTypeOfLiterals"`

Note that pylance correctly sees the type of `x` to be `Literal[1, 2]`, so it should be able to carry that information to the list.
But the type of `return_from` is seen as `list[int]`, so it thinks the return type is wrong.

## Environment data

-   Language Server version: v2022.4.3
-   OS and version: Ubuntu 20.04
-   Python version: 3.9

**Comment by erictraut** [comment]
PEP 586 isn't specific about type inference and TypeVar solving behaviors when literal types are involved. This is both good and bad. It's bad because different Python type checkers may apply different rules. It's good in that it gives Python type checkers the ability to experiment and innovate when deciding how and when an inferred type should retain literal types and when the type should be widened to a corresponding non-literal type. We've done a lot of experimentation over the course of developing pyright to try to optimize the behavior for the most common cases.

We've documented the resulting inference behaviors [here](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md).

In the code sample above, the variable `return_from` doesn't have a type declaration, so its type must be inferred. This inference must be done without the assistance of an "expected type", so bidirectional type inference is not used here. It falls back on its default list inference behaviors.

Pyright's list inference behavior in this case is to widen the type of the list elements, effectively stripping out any literal types. This makes sense in common use cases for lists with literals. For example,
```python
x = [1, 2, 3]
```
In this case, although the elements of the list are literals, most developers would expect the type of `x` to be `list[int]` rather than `list[Literal[1, 2, 3]]`.

This same behavior is applied consistently for all lists whether they contain simple elements, unpacked elements, or comprehensions. This explains why you're observing the current behavior.

Looking at your code sample, I can understand why someone might assume that literal types would be retained when inferring the type of `return_from`. I played around with the idea of retaining literal types specifically for list comprehensions, but not for list expressions without a comprehension. While this would introduce an inconsistency, my thought was that it might be a useful inconsistency. Unfortunately, this small change causes havoc for internal Microsoft source bases that use pyright. They rely on the current (consistent) behavior for list inference. I presume that other source bases outside of Microsoft that use pyright and pylance would similarly see a bunch of new false positives if we were to make this change. Therefore, I don't think we can justify such a behavioral change.

There is a simple workaround that you can apply in your case — provide a type declaration for `return_from`. 
```python
    return_from: list[MyTypeOfLiterals] = [x for x in g]
```
This works because pyright can use bidirectional type inference to override the fallback list inference behavior.

**Comment by beauxq** [comment]
To add clarification to Eric's example:
```python
x = [1, 2, 3]
x.append(4)
```
Most people would not like seeing an error on `x.append(4)` because x is inferred as `list[Literal[1, 2, 3]]`.
