### ISSUE TITLE
Decorators that change input/output types aren't respected when inspecting type correctness

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/pylance-release#2789]
## Environment data

-   Language Server version: `v2022.4.3`
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): PyEnv on WIndows, 3.8.10

## Expected behavior

A decorator wrapped function has the final input and return types inspected, rather than the ones in the document before the decorator is applied

## Actual behavior

Only the raw document hints are used

## Code Snippet / Additional information

Consider PySpark  [Pandas UDFs](https://docs.databricks.com/spark/latest/spark-sql/udf-python-pandas.html#series-to-series-udf).

These are functions that _must_ be used on a Spark dataframe, _must_ be fed Spark columns, and _must_ declare Pandas-equivalent hinting.

So the definition

```python
@pandas_udf(IntegerType())
def doConversion(inputCol1:pd.Series, inputCol2:pd.Series) -> pd.Series[int]:
    """
    stuff
    """
    # Do things
   return pd.Series(thing)
```

Returns a `pyspark.sql.column.Column` object with datatype `IntegerType()` after ingesting two input `pyspark.sql.column.Column` objects. However, the UDF will raise an exception if the type hints `pd.Series` are not applied on the function.

Pylance understands the inputs and outputs of the decorator:

![image](https://user-images.githubusercontent.com/165937/167486653-c78360c6-ff8f-4d2e-b20c-baf4596f554d.png)

but still vomits type errors all over the place without an ignore statement for each argument and the function as a whole

![image](https://user-images.githubusercontent.com/165937/167486905-87a2afb4-bd67-40bd-a156-9414152eea48.png)

**Comment by erictraut** [comment]
Thanks for submitting the issue. Could you provide a self-contained minimal code sample? It's a good idea to assume that we are not knowledgeable about the libraries in question. It would also help if you can provide the names and versions of the libraries required to repro the issue, and let us know if you have any specific type stubs installed locally or as stub packages. This will help us repro the issue and offer assistance.

**Comment by tigerhawkvok** [comment]
I have no type stubs installed at all (that I'm aware of).

This zip should fully replicate the issue in VSCode (the `settings.json` file enables basic type checking):

![image](https://user-images.githubusercontent.com/165937/167510693-b5f8aa5c-f20a-4af6-8db0-c8fe0fca7cc9.png)



[pylance-type-hint-decorator.zip](https://github.com/microsoft/pylance-release/files/8655827/pylance-type-hint-decorator.zip)

**Comment by erictraut** [comment]
Thanks for providing the example. I'm able to repro the errors you're seeing.

The issue is that `pandas_udf` is an overloaded function, and you're passing an argument expression (`IntegerType()`) that doesn't match any of the overloads. You have suppressed this type error by adding a `# type: ignore`, but that simply masks the error. It doesn't address the underlying problem. The type checker is unable to evaluate the resulting type of the decorator call. In such cases, the type checker makes the best assumption that it can — that the signature of the decorated function is left unmodified.

I don't know enough about these libraries to say whether it should be legal to pass `IntegerType()` as an argument to `pandas_udf` without providing any other arguments. If you think that it is allowed, you should contact the maintainers of the pyspark library and report the bug in the `functions.pyi` type stub file. It looks like all of the overloads expect a first argument (corresponding to the `f` parameter) that is a callable and a second argument (corresponding to the `returnType` parameter).

Given the type information provided to pylance, I think it is correctly applying the typing rules and reporting the appropriate errors.

**Comment by tigerhawkvok** [comment]
As per their own documentation, it's correct:

![image](https://user-images.githubusercontent.com/165937/167676124-4fe0b58c-31cc-4610-951e-732ecb782d28.png)

[see this](https://github.com/apache/spark/blob/master/python/pyspark/sql/pandas/functions.py#L42-L60)

So I've filed an issue with them: https://issues.apache.org/jira/browse/SPARK-39142

Thanks!
