### ISSUE TITLE
code is unrechable

### ISSUE THREAD

**Issue by KonstantinKlepikov** [microsoft/pylance-release#2804]
![image](https://user-images.githubusercontent.com/20581667/168092453-109ba97b-530b-408b-87df-41edfd8cc3b1.png)

2022.5.1 (11 May 2022) 
vscode, ubuntu 20.04

how to cure it

**Comment by WindSoilder** [comment]
Here is the a minimum code to reproduce.

```python
class DummyClient:
    def __init__(self):
        pass

    def exec(self):
        raise RuntimeError()


class ValidClient:
    def __init__(self):
        pass

    def exec(self):
        return 3


_CLIENT = DummyClient()


def init():
    global _CLIENT
    if isinstance(_CLIENT, DummyClient):
        _CLIENT = ValidClient()


def x():
    init()
    _CLIENT.exec()
    # the following is unreachable.
    a = 3
    b = 4
```

**Comment by erictraut** [comment]
Thanks for the sample. 

Yes, this is the intended behavior in this case. The base class `DummyClient` has no return type annotations, so pyright (the type checker that underlies pylance) must infer the return type for for the `exec` method. This method is not decorated as an `@abstractmethod`, nor does it raise a `NotImplementedError`. Instead, it's raising a `NotImplemented` object. This is [a common source of confusion](https://www.youtube.com/watch?v=GSBqmYUnBdk). `NotImplemented` is not the same as `NotImplementedError`. The latter should be used in this case. The former is intended for use as a sentinel value for magic methods like `__eq__` and `__iter__`.

You can apply any one (or multiple) of these solutions to fix this problem:
1. Add a return type annotation to `exec`.
```python
    def exec(self) -> int: ...
```

2. Add an `@abstractmethod` decorator to `exec`:
```python
    @abstractmethod
    def exec(self): ...
```

3. Raise the proper exception type `NotImplementedError` for an unimplemented method.
```python
    def exec(self):
        raise NotImplementedError
```

In my code, I tend to use all three of these techniques because each one has value in itself, but any one of them used by itself will tell pyright that it should not use normal inference rules and assume that the method always generates an exception.

**Comment by WindSoilder** [comment]
> Raise the proper exception type NotImplementedError for an unimplemented method.

It seems that this doesn't work, actually, my original code in exec is something like this:
```python
def exec(self):
    raise RuntimeError("It's not initialized")
```

**Comment by erictraut** [comment]
A `RuntimeError` is not the proper error to raise in this case. If you replace it with `NotImplementedError`, which is the proper exception type for this context, pylance will interpret it as if this were an abstract method — one that is intended to be overridden by subclasses.

**Comment by WindSoilder** [comment]
Consider adding this information to https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md page?

**Comment by erictraut** [comment]
Yeah, maybe we should add it to troubleshooting. It is documented [here](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#noreturn-return-type) in the pyright documentation, but most pylance users wouldn't know to look there.
