### ISSUE TITLE
Pylance fails to resolve type of boto3.client method

### ISSUE THREAD

**Issue by jarruda** [microsoft/pylance-release#2809]
With the `boto3-stubs` package installed, Pylance is failing to correctly parse the [sample code](https://youtype.github.io/boto3_stubs_docs/mypy_boto3_logs/#from-pypi-with-pip) from (at least) the CloudWatchLogs module:

```py
from boto3.session import Session

from mypy_boto3_logs.client import CloudWatchLogsClient

def get_client() -> CloudWatchLogsClient:
    return Session().client("logs")  # "Type of  of 'client' is partially unknown"
```

(contents of Overload have been snipped to fit)
```
Type of "client" is partially unknown
  Type of "client" is "Overload[(service_name: Literal['logs'], region_name: str | None = ..., api_version: str | None = ..., use_ssl: bool | None = ..., verify: bool | str | None = ..., endpoint_url: str | None = ..., aws_access_key_id: str | None = ..., aws_secret_access_key: str | None = ..., aws_session_token: str | None = ..., config: Config | None = ...) -> CloudWatchLogsClient, (service_name: Literal['lookoutequipment'], region_name: str | None = ..., api_version: str | None = ..., use_ssl: bool | None = ..., verify: bool | str | None = ..., endpoint_url: str | None = ..., aws_access_key_id: str | None = ..., aws_secret_access_key: str | None = ..., aws_session_token: str | None = ..., config: Config | None = ...) -> Unknown, (service_name: Literal['lookoutmetrics'], region_name: str | None = ..., api_version: str | None = ..., use_ssl: bool | None = ..., verify: bool | str | None = ..., endpoint_url: str | None = ..., aws_access_key_id: str | None = ..., aws_secret_access_key: str | None = ..., aws_session_token: str | None = ..., config: Config | None = ...) -> Unknown, (service_name: Literal['lookoutvision'], region_name: str | None = ..., api_version: str | None = ..., use_ssl: bool | None = ..., verify: bool | str | None = ..., endpoint_url: str | None = ..., aws_access_key_id: str | None = ..., aws_secret_access_key: str | None = ..., aws_session_token: str | None = ..., config: Config | None = ...) -> Unknown, (service_name: Literal['machinelearning'], region_name: str | None = ..., api_version: str | None = ..., use_ssl: bool | None = ..., verify: bool | str | None = ..., endpoint_url: str | None = ..., aws_access_key_id: str | None = ..., aws_secret_access_key: str | None = ..., aws_session_token: str | None = ..., config: Config | None = ...) -> Unknown]"
```

I can see the requisite overload for the "logs" literal there, so my assumption is that this is an issue with Pylance and not the mypy package, but I'm not very familiar with the syntax here:

```
 (service_name: Literal['logs'], region_name: str | None = ..., api_version: str | None = ..., use_ssl: bool | None = ..., verify: bool | str | None = ..., endpoint_url: str | None = ..., aws_access_key_id: str | None = ..., aws_secret_access_key: str | None = ..., aws_session_token: str | None = ..., config: Config | None = ...) -> CloudWatchLogsClient
```

Environment:
* Pylance v2022.5.1
* Type checking mode "strict"
* boto3-stubs 1.22.13

**Comment by bschnurr** [comment]
I believe these just means that not all there code paths return a known type. Its a issue to log in the boto3-stubs repo.

**Comment by erictraut** [comment]
The stub files in `boto3-stubs` are modularized. When you install `boto3-stubs` by itself, you are not installing the stubs for all of the various `boto3` submodules. The `client` call is an overload that returns various types imported from `boto3` submodules. If you want to eliminate the `Type of 'client' is partially unknown` error, you will need to install stubs for all of the boto3 submodules. I'm not sure if there's a way to do that automatically. Please consult the boto3 documentation.

If you don't want to install all of the boto3-stubs submodules (there's a lot of them after all!) but still want to use strict type checking, you could add a `# type: ignore` or `# pyright: ignore[reportUnknownMemberType]` to the end of that line.

**Comment by jarruda** [comment]
@erictraut I have tried to install every service, and the issue still occurs, I believe you have closed this issue prematurely.

Even if every service _wasn't_ installed, there is a specific overload that covers my call and it _isn't_ Unknown -- so why would Pylance call this partially unknown?

**Comment by jarruda** [comment]
@bschnurr No control paths should be evaluated at the call site; only the stubs should be used.

**Comment by erictraut** [comment]
> why would Pylance call this partially unknown?

A symbol is flagged as partially unknown if any portion of its type cannot be determined. In this particular case, the symbol `client` is an overloaded method. If any of the overload signatures reference an input parameter or return type that is unknown, the overall type is considered partially unknown. Unknown input parameter types within an overload signature can be especially problematic because they can lead to incorrect overload matching, so it's important for pylance to inform you about partially unknown types in this case.

I presume that you have enabled "strict" type checking? Was that your intent? If you enable strict type checking, you may find that you need to work around limitations in library or stub types. If it wasn't your intent to enable strict type checking, you might find that "basic" type checking is preferable. If you really are intent on enabling all of the strict checks, you can suppress this particular error if you're confident that it's not an issue for your use case.

**Comment by jarruda** [comment]
> I presume that you have enabled "strict" type checking? Was that your intent?
Yes I have strict enabled.  I wanted libraries I'm producing to have no warnings or errors under that mode.

> A symbol is flagged as partially unknown if any portion of its type cannot be determined.
I see, thanks for the clarification.  I would have thought that the error would have been generated at the stub site and not a call site that wasn't using an unknown type, but I expect there's good reason for that.

Re: how this happens with boto3-stub's modular nature, do you have guidance on how that package could be fixed to be compliant in strict mode without all modules installed?

Feel free to close this issue with your reply. Thanks!

**Comment by erictraut** [comment]
The problem is caused by the fact that all of the objects in the boto3 framework are funneled through a single massive overloaded `create` function. This is very atypical. I can't think of any other Python libraries that do this. Most libraries have you call constructors directly rather than going through a polymorphic wrapper function like this.
