### ISSUE TITLE
Showing "Code is unreachable" but code actually works

### ISSUE THREAD

**Issue by RuceShao1994** [microsoft/pylance-release#2818]
Used Version 2022.5.1 and shows "Code is unreachable" after the line of using grad function from Autograd.
![unreachabl](https://user-images.githubusercontent.com/89484883/168632370-349bddb8-dbcf-4be6-8d4e-ec5f71ff1469.png)

Change to Version 2022.4.3 and highlighting works normally.
![reachable](https://user-images.githubusercontent.com/89484883/168632694-2a837bc2-10cf-440c-8085-e0e795559a2e.png)

**Comment by erictraut** [comment]
Could you please provide a self-contained minimal code sample that demonstrates the problem? Diagnosing problems based on partial-code screen shots is difficult at best. Your sample should include import statements for any non-builtin symbols. It would also be useful to understand the versions of the library (or libraries) that you are importing.

**Comment by erictraut** [comment]
OK, I think I've figured out the information I requested above.

Here's a self-contained minimal code sample:
```python
from autograd import grad

def d(g):
    grad(g)
    print(g)  # Unreachable
```

This is using the autograd library version 1.4 (installed via `pip install autograd --upgrade`).

Autograd is an untyped library, so pyright (the static type analyzer that underlies pylance) attempts to infer type information from the available source code.

The `grad` function calls a function `_make_vjp`. This in turn calls a class method `VJPNode.new_root` which calls an instance method `Node.initialize_root`. This instance method is implemented as `assert False` which will always raise an error. The method is not marked as an abstract method, and it doesn't raise a `NotImplementedError`, so pyright assumes that the method is not designed to be overridden.

I don't think there's much we can do in pyright or pylance to address this. Potential fixes include the following:
1. The maintainers of autograd could add type information to the next release of the library. Increasingly, library maintainers are doing this to improve the experience for developers who consume their library.
2. As a more surgical fix, the maintainers of autograd could update the `Node.initialize_root` method in tracer.py to be marked as `@abstractmethod` or raise a `NotImplementedError` rather than simply `assert False`.
3. You could find and install type stubs for this library. This provides type information such that pylance doesn't need to infer type information from the library's source code.
