### ISSUE TITLE
Suppress reportUnboundVariable for a variable or a code block

### ISSUE THREAD

**Issue by hzhwcmhf** [microsoft/pylance-release#282]
### The Problem

In the following code

```
def func(flag):
    # some operations...
    if flag:
        variable = 1
    # some other operations...
    if flag:
        if variable:
            pass
        else:
            pass
        # more operations about variable
```

``variable`` will be reported unbound no matter whether ``flag`` is not changed. I know it's not simple for pylance to find ``variable`` are defined because of the unchanged condition, but I didn't found a satisfying workaround.

### Known Workarounds

As discussed in #216 , a workaround is defining variable in the outer space, like:
```
variable = None
```
However, I'd like to see errors if the code accidentally uses undefined ``variable`` outside ``if flag``. It can be dangerous if ``None`` has meanings, such as passing ``variable`` to another function where ``None`` means default value.

Another workaround is disabling warnings on a specific line:
```
if variable: # type: ignore
    pass
```
However, ``variable`` can be used in multiple lines and it is impossiblee to mark all of them.

### Suggestions

I hope there are some ways to solve the problem without changing the program behavior.

One possible way is adding hint manually and telling pylance it is defined, which is compatitable with [mypy](https://github.com/python/mypy) for type checking.

```
def func(flag):
    # some operations...
    if flag:
        variable = 1
    # some other operations...
    if flag:
        variable: int
        if variable:
            pass
        else:
            pass
        # more operations about variable
```

Another possible solution is disabling warnings in a block, rather than in a line or a file. (**Update**: a better way maybe follow [pylint message control](http://pylint.pycqa.org/en/latest/user_guide/message-control.html))

```
def func(flag):
    # some operations...
    if flag:
        variable = 1
    # some other operations...
    if flag:
        #pylance: disable-reportUnboundVariable
        if variable:
            pass
        else:
            pass
        # more operations about variable
        #pylance: enable-reportUnboundVariable
```

**Comment by erictraut** [comment]
Leaving variables unbound on some code paths in your code is not a good idea. You can always work around this by pre-initializing your variable.

You mentioned that it can be dangerous if `None` has meanings. Can you give a concrete example of this?

**Comment by hzhwcmhf** [comment]
Thanks for your quick response. My example is doing neural network prototyping using ``pytorch``:

The code is starting from
```python
x = ...   # x is pytorch.Tensor
y = some_network(x)
loss = ...
```

And I want to add a patch before and after the codes (to try a new idea)

```python
x = ...   # x is pytorch.Tensor

if config.extra_input_type == "a*b":
    x = x + ...  # x.shape: [a * b]
    target_dim = 1 # store some variable for latter use
elif config.extra_input_type == "a*b*c":
    x = x.unsqueeze(-1) + ... # x.shape: [a * b * c]
    target_dim = 2 # store some variable for latter use

y = some_network(x)
loss = ...

if config.extra_input_type:
    loss += y.sum(dim=target_dim).mean()
```

I can add ``target_dim=None`` before the patched code, but it is not very safe if I mistaken the latter condition:

```python
x = ...   # x is pytorch.Tensor

target_dim = None
if config.extra_input_type == "a*b":
    x = ...  # modify x for new input
    target_dim = 1 # store some variable for latter use
elif config.extra_input_type == "a*b*c":
    x = ... # modify x for new input
    target_dim = 2 # store some variable for latter use

y = some_network(x)
loss = ...

# if config.extra_input_type:  # I may forgot to add this line
loss += y.sum(dim=target_dim).mean()
# if ``target_dim`` is None, this code gets the sum of y.
# if ``target_dim`` is 1, this code first gets average of y along the first dim, and then gets the sum.
```

See the pytorch documentation for [Tensor.sum](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.sum). In this case, I hope to see errors if I forgot ``if config.extra_input_type:``, instead of no errors but wrong answers. (It doesn't worth hiding a bug just because I want to suppress the warning.)

I know your point that it is safe and tidy to bound variables at all code paths like C, but some of users are doing prototyping, and it is not always efficient to do that.

From my point of view, 

* Suppress warning is a regular option, e.g. [pylint](http://pylint.pycqa.org/en/latest/user_guide/message-control.html)
* It's usually better to provide more options than telling users always follow the best practice. (We may not be able to imagine the situation that the user faces)

**Comment by erictraut** [comment]
I don't buy the argument that it's unsafe to initialize the variable to `None`. If it's unbound, the program will crash if you reference it.

If you really don't want to fix this in your code, you can suppress the diagnostic (the warning or error message) using a `# type: ignore` comment on the line where the diagnostic is being reported. Or you can suppress this diagnostic rule within the file by placing this comment at the top "# pyright: reportUnboundVariable=false", or you can disable the diagnostic rule entirely using the `python.analysis.diagnosticSeverityOverrides` setting.

**Comment by Justin1904** [comment]
If a variable is unbound, the program will crash and you will know it immediately so that you can go and fix the problem. If it is initialized with `None` instead, in the example @hzhwcmhf provided, the program would execute with unexpected behaviors without throwing any errors and it'll be much harder to figure out.

**Comment by hzhwcmhf** [comment]
> 
> 
> If a variable is unbound, the program will crash and you will know it immediately so that you can go and fix the problem. If it is initialized with `None` instead, in the example @hzhwcmhf provided, the program would execute with unexpected behaviors without throwing any errors and it'll be much harder to figure out.

Yes, that is exactly what I mean. It allows the program crash and let me figure out the problem. 

I just hope pylance consider (1) providing a fine-grained message control, like pylint (Existing methods of supressing only works in a line, a file, and the whole project); or (2) providing a hint to solve the unbound issue in some paths, like mypy. (The examples of prefered solution are in my first comment.)

**Comment by Kein** [comment]
> # pyright: reportUnboundVariable=false

Can it be extended so rather than being processed once per document/file scope it is processed per block with last value overriding for the rest of the document?
For example:
```
# pyright: reportUnboundVariable=false
some code
no unbound  errors or warnings reported here
more code
    inner scope
    still no reports
# pyright: reportUnboundVariable=true
now it is reported, type default to global definition of severity for reportUnboundVariable
```
See #699, facing similar issue

**Comment by erictraut** [comment]
These comments are designed to be at the document level, not used in inner scopes.

The workaround is to ensure that you don't have uninitialized variables in your code.

**Comment by Kein** [comment]
> The workaround is to ensure that you don't have uninitialized variables in your code.
I wasn't really talking about this specific issue, because the problem discussed here and possible solutions (as proposed in OP) are more of general use than this specific case of unbound variables.

> These comments are designed to be at the document level, not used in inner scopes.
Yes, and I'm suggesting to promote them to their own 'flat' block-scopes. If it is at the top of the document then it works for whole document until it meets counterpart that disables it. And then re-enables. Pyright already respect pylint's-alike `#type: ignore` for each line. What exactly is the problem to adapt Pyright-specific directives to be more flexible?
Static typing analysis will never work as properly or comfortable in Python as in language designed around that (i.e.C#) so, inevitably, there is a need for more flexible workarounds.

**Comment by reservoirinvest** [comment]
I have quite a few try: except blocks. Variables used in try are ignored and `reportUnboundVariable` problem messages create a mess. How does one resolve this?

**Comment by erictraut** [comment]
@reservoirinvest, can you provide a minimal code sample that demonstrates the issue you're seeing?

**Comment by reservoirinvest** [comment]
Here is a sample...

[reportUnboundVariable_errors.pdf](https://github.com/microsoft/pylance-release/files/5767545/reportUnboundVariable_errors.pdf)

**Comment by erictraut** [comment]
Pylance is doing the right thing here. It's telling you that you have a bug in your code. If an exception occurs within the try block, `s500` will be unbound after the except block is executed, and an exception will be generated (outside of the try/except block) when you attempt to use `s500`.

You can easily fix this bug by assigning it an empty value (like `[]`) before the try block. If you choose not to fix the bug, you can either ignore the warning or disable it.

**Comment by killerkalamari** [comment]
Is there any way to ignore this for a specific variable rather than for a block? That way I can still get a warning about other unbound variables than the ones I specifically excluded.

**Comment by erictraut** [comment]
Pyright (which is the type checker upon which pylance is built) doesn't support `# type: ignore[code]`. That's a mypy-specific extension. Pyright does allow you to specify a code in brackets, but it ignores the code. Any such codes would be type-checker-specific anyway, since there's no standardization in terms of error codes or error names.

The best way to handle `reportUnboundVariable` violations is to fix the issue that's causing it in the first place. Often times that means initializing the variable prior to a loop or within an `else` block. Most programming languages wouldn't allow this sort of an error to exist because variables need to be declared, but Python is a bit lax here, which leads to some common errors.

I strongly recommend against using `# type: ignore` to suppress errors. As you said, it makes the code look bad, and it's really just covering up the problem rather than addressing it. This leaves your code vulnerable as is continues to evolve. I use `# type: ignore` only as an absolute last resort. I can't remember the last time when I needed to resort to it. There's almost always a better choice.

**Comment by killerkalamari** [comment]
You're certainly entitled to your opinion, but IMHO you're making a lot of unwarranted assumptions and it comes off as a bit condescending. I've already considered (and implemented!) multiple alternatives, and I think the way I'm doing it is the best option.

**Comment by erictraut** [comment]
Apologies if I came across as condescending. Many Python developers have relatively little experience with static type checking, and I've found that they are not familiar with ways to address type errors. If you're happy with the approach you've taken, the by all means continue to use it. I'm just sharing my experience and advice based on my own use of static type checkers in multiple programming languages. I would not recommend using the approach you're advocating above.

**Comment by Kein** [comment]
While I agree with your general idea, the issue is that at the current state of type checking support a lot of these things are workarounds and  compromises you resort to rather then understanding the issues and realizing it nudges you the right way. I've mentioned C# before and I have somewhat modest C# background so I can compare. Python never mean to be static typing language so while it helps it never feels consistent and "just right". And until one day it is - having the aforementioned flexibility can be very useful.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
