### ISSUE TITLE
Support line formatting

### ISSUE THREAD

**Issue by hauselin** [microsoft/pylance-release#283]
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: Mac 10.13.6
-   Python version: Anaconda Python 3.8.1
-   VSCode version: 1.48.2

## Expected behaviour
I've set `"editor.formatOnType": true` in `settings.json`. When I press return/enter after a line, that line should be formatted automatically.  

## Actual behaviour
Any given line won't format automatically when pylance is enabled. When I comment out `"python.languageServer": "Pylance",` in my `settings.json`, format on type works again.

![formatontype](https://user-images.githubusercontent.com/7620977/91322263-89693580-e78d-11ea-986f-ddc38298e998.gif)

**Comment by jakebailey** [comment]
We don't implement this LSP method. The MPLS did, and the core extension has (old, hacky) logic for doing this when running jedi.

I'm not sure that we are going to reimplement this, as the core extension is planning on having this feature reworked in order to better support auto-formatting on enter (and thus requires us to not declare support for it): microsoft/vscode-python#8996

**Comment by savannahostrowski** [comment]
This should have been closed previously as this is being handled on the core extension side as mentioned above.
