### ISSUE TITLE
Pylance doesn't check `extraPaths` if the imported module names match the workspace modules.

### ISSUE THREAD

**Issue by cmurat** [microsoft/pylance-release#2855]
## Environment data

-   Language Server version: 2022.1.3
-   OS and version: macOS Big Sur 11.2.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

### Snippet 1
```python
from company.team import library1
```

### Snippet 2
```python
from company.team.library1 import method1
```
## Repro Steps

```
- src
  - company
    - __init__.py
    - team
      - __init__.py
      - project
        - __init__.py
        - A.py
        - B.py
```

- Setup the workspace above
- Install the `company.team.library1` under `/lib/python3.8`
- Add `/lib/python3.8` to `extraPaths`
- Use the snippets above in any python file.

## Expected behavior

Both imports should be resolved. Pylance should look at `extraPaths` if it can't find the dependency in the workspace.

## Actual behavior

Snippet 1 can NOT be resolved, while snippet 2 can be resolved.

Conjecture: Pylance uses `from` part in the import statement to decide whether to check only the workspace or provided `extraPaths`.

**Comment by bschnurr** [comment]
could be due to how we handle library interfaces.
https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface

Also, I dont see "project" or "A" or "B" in your import statement

**Comment by erictraut** [comment]
@bschnurr, this isn't a "py.typed" library, so that document doesn't apply.

@cmurat, if I understand your steps correctly, your project looks like the following once you have installed `company.team.library`:
```
- src
  - company
    - __init__.py
    - team
      - __init__.py
- lib
  - python3.8
    - company
      - __init__.py
      - team
        __init__.py
        library1
          __init__.py
```

Is that correct? If so, there are two valid resolutions for `company.team`. The first resolves to `src/company/team/__init__.py`, and the second resolves to `lib/python3.8/company/team/__init__.py`. Since `extraPaths` is appended to the list of search paths, it comes later, so the earlier resolution is chosen in this case.

In your second snippet, there is only one valid resolution for `company.team.library1`. It resolves to `lib/python3.8/company/team/library1/__init__.py`.

It sounds like you are expecting these to be resolved as [implicit namespace packages](https://peps.python.org/pep-0420/). If so, you should delete the `__init__.py` files. If you do this, both import forms should resolve as you expect.
