### ISSUE TITLE
Show completions ignoring what is to right of cursor

### ISSUE THREAD

**Issue by gramster** [microsoft/pylance-release#286]
When generating completions, I'd like them to be based on what is to the left of the cursor, so, for example, if I have:

```python
import pandas as pd

pd.r[]
```

and the cursor is between the `r` and `[`, I should see completions for `pd.r` such as `read_csv`.

**Comment by erictraut** [comment]
Thanks for the bug report. This was due to a poor interaction between the parser (which was injecting an error node into the parse tree to deal with the syntax error due to the missing expression between the square brackets) and the completion provider. The same problem occurred when the right square bracket was missing. I've improved the behavior in this case.

If you see other specific cases where completion suggestions are missing but you expect them to appear, please file more bug reports.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202083-28-august-2020
