### ISSUE TITLE
Support of incomplete stubs files

### ISSUE THREAD

**Issue by pukhov** [microsoft/pylance-release#2866]
Let's say I have files

a.py: (NOTE: `foo` is NOT annotated, but `bar` IS annotated).
```
def foo():
    ...

def bar() -> str:
    ...
```
a.pyi
```
def foo() -> str:
    ...
```

then, when I import a module, VSCode shows only `a.foo` as available functions, while I would expect the following behavior:
it first scans all functions in `a.py`, then it overwrites them with definitions in a.pyi.

Note that here https://peps.python.org/pep-0484/#stub-files it says it is possible to define incomplete stubs files, but even if I change my `a.pyi` file to:
```
from typing import Any

def __getattr__(name) -> Any: ...

def foo() -> str: ...
```
It still does not work.

Is it intended or not?

**Comment by erictraut** [comment]
This is how type stubs work. When a type stub is present, its information is used rather than the type information in a corresponding `.py` file. Type information is never somehow "merged" from the two. Merging type information in that manner cannot be reliably done. 

A type stub is meant to be a stand-in for the module.

If you add `def __getattr__(name) -> Any: ...` to a stub file, any symbol imported from that module will be considered "present". Unless otherwise specified, a symbol will have the type provided by the return type of `__getattr__`, typically `Any`.

So pyright is working as expected here. It's consistent with PEP 484 and with other type checkers like mypy.

**Comment by pukhov** [comment]
Indeed, I misunderstood usage of `def __getattr__(name) -> Any: ...` here, then it makes perfect sense.Though it's a pity when you want to additionally annotate 1 function of 10 (e.g. by providing overloads) in stubs file, well, wrong usage...

Thanks, closing!
