### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by vishalzac** [microsoft/pylance-release#2867]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by erictraut** [comment]
You didn't provide the information requested in the bug template. Closing the bug report because there is insufficient information to diagnose. 

@viralzac, you have been asked multiple times to provide specific details in [this thread](https://github.com/microsoft/pylance-release/commit/18efa3eb1ace413951bab7865b31d705eca14244#commitcomment-74822746). If you want assistance, we're happy to help, but please don't waste our time.
