### ISSUE TITLE
<Feature request> Adding a new option in python.analysis

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#2875]
Can pylance adding "reportUnusedParameter" to "python.analysis.diagnosticSeverityOverrides"?

**Comment by erictraut** [comment]
Can you explain what you mean by `reportUnusedParameter`? There is currently no `reportUnusedParameter` check in pyright, the type checker that underlies pylance, so there is no such check to expose. Did you mean some other (existing) diagnostic rule? Or did you have a specific (new) check in mind when you said `reportUnusedParameter`?

There was a [recent discussion](https://github.com/microsoft/pyright/issues/3473) about adding a check for unreferenced input parameters. It's a feature I'm reluctant to add because there are many legitimate and common uses for unused parameters in Python. So in practice, this would be a noisy check that would produce many false positives. Its benefits (catching bugs related to parameters that are meant to be used but are not) are small compared to the downsides (large numbers of false positive errors in most Python code bases).

**Comment by ydmykr** [comment]
@erictraut Thank you for your clarification

**Comment by OmniscienceAcademy** [comment]
Hi, @ydmykr , I've also been through this, and for me, installing flake8-unused-argument has been the solution.
