### ISSUE TITLE
Unable to find a matching function overload after raise EOFError

### ISSUE THREAD

**Issue by zhouzq-thu** [microsoft/pylance-release#2884]
## Environment data

-   Language Server version: v2022.6.0
-   OS and version: macOS12.4 (21F79)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12

## Code Snippet

```python
class Base:
    def _eval(self, a, b):
        raise EOFError('Not implemented')
        #raise NotImplementedError

    def do(self, a, b):
        return self._eval(a, b)

class Add(Base):
    def _eval(self, a, b):
        return a + b

calc = Add()

print(calc.do(1, 3))
print(calc.do(4, 3))
```

## Expected behavior

The behavior is ok if raise NotImplementedError:

![NotImplementedError](https://user-images.githubusercontent.com/9458157/171568641-4759730c-6a7a-4de0-ae25-a334a53d0e2a.png)

## Actual behavior

![EOFError](https://user-images.githubusercontent.com/9458157/171568712-7933ceb4-9083-433c-b757-1f43972ff650.jpg)

**Comment by erictraut** [comment]
This is expected behavior. You have not provided a return type annotation for `Base._eval`, so pylance is inferring the return type based on the implementation. In this case, it is inferring the return type to be `typing.NoReturn` because all paths raise an exception.

If the intent is for `Base` to be an abstract base class where `_eval` must be overridden by subclasses, you can do one of the following:

1. Raise `NotImplementedError`, which is the standard way to indicate that a method should be overridden.
2. Decorate `_eval` with `@abstractmethod`. This has the added benefit of telling tools like pylance that the method must be overridden by subclasses.
3. Add a return type annotation to `Base._eval`. For example, if the intended return type is `int`, add `-> int` before the colon. Pylance will no longer need to infer the return type in this case.

**Comment by zhouzq-thu** [comment]
@erictraut Thanks!
