### ISSUE TITLE
Extract symbols from C libraries

### ISSUE THREAD

**Issue by kiwixz** [microsoft/pylance-release#294]
Note: previously closed as wontfix here: microsoft/pyright#723, but the fate of Pyright changed as it is now supposed to replace Microsoft's python language server.

I'd like the language server to extract symbols from C libraries in case it does not find type stubs.
Without this, there is no autocompletion on those symbols (and errors everywhere).
I can't replace Jedi with Pylance (instead of just having Pyright running on the side) until this is implemented.

Related to #166.

**Comment by jakebailey** [comment]
We're currently discussing this topic, but there are a lot of things to consider here. Things like:

- Should this be automatic, or a behavior with user interaction because it executes code?
- Given Pylance has type checking, how will can we reconcile the fact that the output of the scraper is usually very poorly typed?
- How can we better support library authors who are working on stubs or want to generate stubs for their compiled code?

MPLS had it "easy"; it wasn't a type checker, it just showed you things even if they were wrong, and left it to the user to deal with. That's not an optimal solution, however, and getting properly written stubs for libraries with compiled code is the best solution of the bunch. A scraper is at best a hack.

**Comment by shelper** [comment]
any update for this?
since c libs are a big part of python ecosystem, a early incomplete solution that is similar to MPLS would be very useful if a full solution is difficult any time soon,

**Comment by jakebailey** [comment]
We will update this thread when we have updates; the above comment is still true.

More recently, we've started pre-scraping some critical compiled code (such as a few modules from numpy) to help stem this. If there's something you're missing, then that feedback would be appreciated.

**Comment by judej** [comment]
Since this is a compiled module, we will not be able to get type information without a Typestub. This is something that the package author needs to create. Executing the module would open the user to security vulnerabilities and therefore Pylance does not do that. My recommendation is to file an issue with the package author to create Typestubs. Thanks
