### ISSUE TITLE
Control + click doesn't work on unreachable code

### ISSUE THREAD

**Issue by ikjelle** [microsoft/pylance-release#2940]
<h3> Environment data </h3>

-   Language Server version: 2022.6.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
def some_func():
    var x = Object()
    x.do_something()
    return x
    # Unreachable code below
    x.do_something_else()
```

<h3> Repro Steps </h3>

1. Write code and have a return statement or other ways to make code unreachable.
2. Try to control + click on a function or variable and it doesn't do anything

<h3> Expected behavior </h3>

I expect that even though code is unreachable that I can still use that code to quickly navigate around with control + click. Or say even though the code is grayed out I can still control + click on that.

<h3> Actual behavior </h3>

Control + click on unreachable code does nothing at all.

<h3> Severeness </h3>
Very low  
I just think that its weird that unreachable code is also unreachable for the developer and see no reason why it should be.

**Comment by erictraut** [comment]
The current behavior is intended. Provably unreachable code is not analyzed because we don't want to generate any diagnostics for that code. Any such diagnostics are likely to be false positives. But because we don't analyze the code, there's no type information to inform "go to definition", semantic highlighting, semantic find, semantic rename, etc.
