### ISSUE TITLE
Pylance, MSL, JEDI, ... how to: transition of settings and VSCode configuration

### ISSUE THREAD

**Issue by schperplata** [microsoft/pylance-release#295]
Background:
Originally, I started by using Jedi + .pylintrc file, where all my rules were defined. Because [things didn't work](https://github.com/microsoft/python-language-server/issues/2053) I switched to Pylance (and in between to MPSL, where other things didn't work). At the moment, I am struggling about what is the best of the three _non-working extensions_ and which limits me the least. 

Question: what is the plan how users will transit their current workspaces/projects to Pylance? 

For example, I work with python projects for the last couple of years and I've never needed any stub typings files or similar. I understand that code completion and recommendation has massively improved during these years and there are some costs to it, but still, will Pylance force users to have additional work just to report unresolved imports? 

For example, to report error in import statement, I need to add:
```
"python.analysis.diagnosticSeverityOverrides":{
    "reportMissingTypeStubs": "error"
}
```
... and I had to check other possible attributes, like:
```
    "reportMissingModuleSource": "error",
    "reportMissingImports": "error",
```
... where I would blindly choose `reportMissingModuleSource` instead of `reportMissingTypeStubs`.
Even when I enable this diagnostic report area, Pylance bothers me with stub files which are of course not needed by my project.
![image](https://user-images.githubusercontent.com/8736111/91577586-363be200-e949-11ea-9fb2-4959e17ec34d.png)
Than, some 3rd party packages report also report issues, which I can't solve since I won't generate stub files:
![image](https://user-images.githubusercontent.com/8736111/91579858-8799a080-e94c-11ea-883f-ae0aeba465e1.png)

I am very happy that code completion and language support is developing fast - which is a must for Python that is so happy with user mistakes in code, usually prevented by compile stage in other languages - I am just concerned If I will really have to constantly configure IDEs and adapt my workspaces. I changed "analysis" engine a couple of times in the last two years with VSC, and I still don't have a clue: Use old extensions where things worked? Use latest extensions and find workarounds for basic stuff? Ask for every little thing that is not documented, for example Pylance Diagnostic Severity Rules default values? Will Pylance cover _everything_ Jedi, Flake and others supported, or will we need to use all of them to cover all areas? Will VSC support multiple analysis extensions? ...

As this (autocomplete, linting, formatting) is a very important part of any python projects, it would be really nice if someone would clarify things a little bit: Jedi, Pylance, Intellisense, auto-sort by pylance, auto-sort by autopep8, ... What are the good practices and how to really use VSCode with Pylance without sacrificing other cool (and also basic) stuff we already had?

**Comment by jakebailey** [comment]
> For example, I work with python projects for the last couple of years and I've never needed any stub typings files or similar. I understand that code completion and recommendation has massively improved during these years and there are some costs to it, but still, will Pylance force users to have additional work just to report unresolved imports?

You aren't required to have a typings folder in your project, but stubs behind the scenes are the fundamentally best way to get accurate information about libraries. MPLS used stubs as well, Pylance can handle the full typing specification to make use of them. By default, we'll still attempt to analyze libraries if they're unstubbed, just as MPLS did. We're largely trying to "hide" the stubs from users (as stubs and typing are a relatively new thing to many Python developers), and by default don't show errors about missing stubs, hide type checking messages, etc.

> will Pylance force users to have additional work just to report unresolved imports

We always report unresolved imports, at every type checking level (except strict, where you pretty much _need_ fully typed stubs, so the messaging is focused around that). If you're seeing otherwise, then that's a bug. Do you have warnings hidden in your editor? They are warnings, as they were in MPLS.

> Even when I enable this diagnostic report area, Pylance bothers me with stub files which are of course not needed by my project.

You don't need to enable the missing stub diagnostic, the other diagnostics should cover this case. You'd really only want this diagnostic if you were interested in making a type stub for a library you were using since there's a quick fix you can apply that will generate them (when possible).

> What are the good practices and how to really use VSCode with Pylance without sacrificing other cool (and also basic) stuff we already had?

I'm really curious what think is being sacrificed with the Python extension + Pylance combo; the Python extension manages formatting/import sorting, and Pylance does nearly everything else (autocomplete, symbol searching, diagnostics).

**Comment by schperplata** [comment]
> We always report unresolved imports, at every type checking level (except strict, where you pretty much need fully typed stubs, so the messaging is focused around that). If you're seeing otherwise, then that's a bug. Do you have warnings hidden in your editor? They are warnings, as they were in MPLS.

Bug: https://github.com/microsoft/pylance-release/issues/300

> I'm really curious what think is being sacrificed with the Python extension + Pylance combo; the Python extension manages formatting/import sorting, and Pylance does nearly everything else (autocomplete, symbol searching, diagnostics).

Seems like some other bugs will have to be reported. For example, as soon as I set Pylance as a language server, Pylint stops working and no warnings are issued about line length. I assume things were designed in a good way, still covering most use cases - but apparently they don't work out of the box or my configuration is invalid. 
Anyway, seems like the whole "package" of non-working things lead to this issue report.

**Comment by jakebailey** [comment]
> Seems like some other bugs will have to be reported. For example, as soon as I set Pylance as a language server, Pylint stops working and no warnings are issued about line length.

Yes, that's microsoft/vscode-python#13315, as the Python extension typically only uses Pylint to handle syntax checks on save.

**Comment by schperplata** [comment]
oh. I wish this kind of how-to's and bug reports were easier to find. Thank you @jakebailey.
