### ISSUE TITLE
.txt file not opening

### ISSUE THREAD

**Issue by arthrrrrr** [microsoft/pylance-release#2959]
## Environment data

-   Language Server version: v2022.6.20
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.10.0

## Code Snippet

```python
f = open("demofile.txt", "r")
print(f.read())
```

## Expected behavior
should print
Hello! Welcome to demofile.txt
This file is for testing purposes.

## Actual behavior
```python
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'demofile.txt'
  File "C:\Users\Arthu\Documents\python\txt test\txt test.py", line 1, in <module>
    f = open("demofile.txt", "r")
```

**Comment by bschnurr** [comment]
it appears it can't find your file 'No such file or directory: 'demofile.txt''

**Comment by erictraut** [comment]
This doesn't appear to be related to Pylance. This isn't the right forum for general Python programming and debugging questions.

**Comment by arthrrrrr** [comment]
It works fine on python IDLE, VS code is screwing it up

**Comment by debonte** [comment]
The problem is most likely that `demofile.txt` does not exist in your [current working directory](https://en.wikipedia.org/wiki/Working_directory). Are you familiar with the concept of [relative and absolute paths](https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths)? Since you are calling `open` with just a filename (which is a relative path), open is trying to find that file **relative** to your current working directory. If your current working directory is not the directory that contains `demofile.txt` it won't be found.

Try adding this before your `open` call to see what you current working directory is:

```python
from os import getcwd
print(getcwd())
```

I believe that by default, VS Code will use the root of your current workspace as your working directory. You can override that in your `launch.json` file by setting the `cwd` property. For example, you could set your current working directory to always be the directory containing the `.py` file that you are running, which may be what you are expecting(?), by using the [`${fileDirname}` variable](https://code.visualstudio.com/docs/editor/variables-reference):

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "cwd": "${fileDirname}"
        }
    ]
}
```
