### ISSUE TITLE
Python intellisense fails to find module

### ISSUE THREAD

**Issue by ai623** [microsoft/pylance-release#2976]
Issue Type: **Bug**

# Behaviour

Python intellisense cannot find a module when there exists a directory with the same name of that module in the root of workspace.

### Actual
![1](https://user-images.githubusercontent.com/37432548/176005786-07b6646c-e1d8-4f34-ad64-8b79418d439f.png)
![2](https://user-images.githubusercontent.com/37432548/176005796-7ed2a47d-4230-4c5a-8e9e-e03538a25af4.png)

### Expected
![3](https://user-images.githubusercontent.com/37432548/176005812-0f146444-c326-47df-b778-fd6bbc0a5992.png)

## Steps to reproduce:

See previous section.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
LSP Notebooks experiment is disabled -- Jupyter disabled or not installed
Python interpreter path: .\Python\Python38\python.exe
Starting Pylance language server.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

terminal
• activateEnvironment: false

```

</p>
</details>

**Comment by erictraut** [comment]
Based on the screen shots above, it looks like `header.py` is located within a subdirectory called `example` rather than in the root of the workspace. Please confirm.

If you want to place `header.py` in a subdirectory, you need to tell pylance that the subdirectory should be used for import resolution. You can do this by adding "example" to the `python.analysis.extraPaths` setting.

**Comment by ai623** [comment]
> Based on the screen shots above, it looks like `header.py` is located within a subdirectory called `example` rather than in the root of the workspace. Please confirm.
> 
> If you want to place `header.py` in a subdirectory, you need to tell pylance that the subdirectory should be used for import resolution. You can do this by adding "example" to the `python.analysis.extraPaths` setting.

Yes. I want to place `header.py` in a subdirectory. Pylance works well if there there doesn't exists a directory called "header." But if I create a directory called "header", it won't work. It's stange to change the behaviour just because of adding an empty directory to the root of workspace.

I can't just simply add the subdirectory to python.analysis.extraPaths. Because suppose there are not only one subdirectory of python scripts in my project, the python module name will conflict.

Actually, I expect that Pylance can respect the default module search path:
![image](https://user-images.githubusercontent.com/37432548/176080289-f88fc5b8-8a01-4765-9a4a-cf431c37774a.png)

**Comment by erictraut** [comment]
Pylance does honor the standard import resolution rules and the sys.path for your selected Python interpreter. However, when you run the Python interpreter to execute a script, the working directory is added to the sys.path. Pylance has no way of knowing what working directory you will use when running a script. Unless told otherwise, it assumes that you will be executing code from the root directory of your project, so the root directory is added to the import resolution path. If you intend to execute code from other working directories, you can add those to the extraPaths.

Another option is to create a multi-root workspace. Choose "Open Folder..." from the VS Code File menu and select the `example` directory. This effectively tells Pylance that you want to treat that directory as its own project, and its project-specific root directory will be used for import resolution.

**Comment by ai623** [comment]
Thank for your patience. 

I understand the issue. However, maybe there is a better workaround solution. Pylance can detect python module inside in the same directory correctly. It only won't work if there is a directory with same name in the root of workspace. How about checking if the directory is a valid python package. If it is not, then still use the python module inside in the same directory.

**Comment by ai623** [comment]
Or, more directly, How about allowing user to explicity configure default working directory as where the script in. I think it's a common option because by default vscode will choose where the script in as the working directory when you click "Run Python Script" button.

**Comment by erictraut** [comment]
Pylance already has a bunch of complex heuristics in place to auto-detect import roots. The reason this isn't working for you is because you have another subdirectory named `header` in your workspace root. This makes the intent of the import ambiguous. The recommended workaround in this case is to either add the `example` subdirectory explicitly to `python.analysis.extraPaths` or to rename either `header.py` or the `header` subdirectory to avoid the ambiguity.

**Comment by ai623** [comment]
Thank you for your help. I understand complexity. I just recommend for improvements. Just ignore it if it's difficult to do or there are some other considereations.
