### ISSUE TITLE
Support for attrs type declarations within attr.ib() method

### ISSUE THREAD

**Issue by msert29** [microsoft/pylance-release#3013]
Although Pylance currently supports type annotations within as such declarations

```
@attr.s(slots=True)
class Person:
    name: str = attr.ib(default=None)
    surname: str = attr.ib(default=None)
```

It would be extremely useful to support the type annotations passed as parameter arguments i.e.

`name = attr.ib(type=str, default=None)`. This is currently supported by PyCharm and since the existing project structure is built using this format,  we constantly get unrecognised construction parameter errors which we have to just ignore. Would be 🚀 feature to cover this within pylance.

**Comment by judej** [comment]
Thanks for the suggestion, we don't support this because Pylance is built on Pyright, which is a standards-based type checker, and it does not embed specialized knowledge of third-party libraries like attrs. There is currently no way to specify the behavior of the attr.ib in the Python type system. The recommended approach is to use type annotations for fields rather than using the non-standard type parameter. The former is also fully supported by attrs and will work fine with Pylance.
