### ISSUE TITLE
Where do i find which version of pyright pylance is using?

### ISSUE THREAD

**Issue by laundmo** [microsoft/pylance-release#3019]
I'm running into an inconsistency between pyright CLI and pylance, and would like to know which version of pyright pylance is using. 

It seems that information isn't easily accessible, though.

Where could I find out which version of pyright my current pylance version is using?

If I can't easily find out, consider this a feature request.

**Comment by debonte** [comment]
You can find our current pyright commit id at the top of your Pylance log ("Python Language Server" in the Output window). For example, here's mine:

> [Info  - 9:21:10 AM] (37848) Pylance language server 2022.7.20 (pyright 7cadfb74) starting

We output the commit id instead of a version number because Pylance sometimes ships Pyright changes that have not yet shipped in an official Pyright release.

Alternatively, you can look in the Pylance changelog, either in VS Code's extensions view or [here on GitHub](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md). Whenever we update our version of Pyright, it is reported in the changelog with a line like this:

> Pylance's copy of Pyright has been updated from 1.1.256 to 1.1.257.

**Comment by dlukes** [comment]
In case anyone finds this useful -- for programmatic access, you can also hit: https://raw.githubusercontent.com/microsoft/pylance-release/main/releases/latest-release.json

Instead of `latest-release`, you can also use `latest-prerelease` or a specific version like `2024.11.3`.
