### ISSUE TITLE
Maximum parse depth exceeded; break expression into smaller sub-expressions

### ISSUE THREAD

**Issue by yechenzhi** [microsoft/pylance-release#3023]
I'm writing code for a big project, and when I edit a file, which has a long sentence, around 2000 lines, my Visual Studio code editor keeps underlining my code incorrectly, VS Code says 'Maximum parse depth exceeded; break expression into smaller sub-expressions pylance' .

When I break the expression into smaller sub-expressions, the problem is solved. However because many people are working on this project, I can not change the file structure. So how can I stop these squiggly lines that appear incorrectly while not changing my code structure?

**Comment by erictraut** [comment]
The solution is to break the expression into subexpressions as indicated in the error message. You don't need to change the file structure, just update the expression. This will aid in readability and maintainability of the code, so it will have other benefits as well.

**Comment by yechenzhi** [comment]
thank you so much, but are there any other ways to solve this problem? Like adjusting the setting of pylance?

**Comment by erictraut** [comment]
The way to solve the problem is to break your expression into smaller sub-expressions. Alternatively, you can ignore the error message. But if you decide to ignore it, the expression in question will not receive any analysis, so any semantic or type errors that would normally be caught and reported by pylance will not be reported.
