### ISSUE TITLE
Pylance does not recognize variable binding done inside a nested function

### ISSUE THREAD

**Issue by vbrozik** [microsoft/pylance-release#3048]
## Environment data

-   Language Server version: Pylance language server 2022.7.30 (pyright f3e85ee2)
-   OS and version: Ubuntu 22.04 (WSL2), VS Code in Windows 10 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.4, Ubuntu

## Code Snippet

```python
def function():
    counter: int
    def reset_state():
        nonlocal counter
        counter = 0
    reset_state()
    print(counter)
#         ^^^^^^^--- error reported here
```

## Repro Steps

1. Leave the Pylance analysis to run.

## Expected behavior

No errors

## Actual behavior
Error message about unbound variable `counter`:
```
"counter" is unbound
```
```
	"severity": 8,
	"message": "\"counter\" is unbound",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 11,
	"endLineNumber": 7,
	"endColumn": 18
```
## Logs

Nothing relevant found.

**Comment by erictraut** [comment]
Yes, this is as designed. Side effects performed outside of the current execution context are not considered as part of the local execution analysis. In practice, such side effects are impossible to model because they can be performed conditionally or in a temporal order that cannot be predicted statically.

You can choose to suppress this error using `# type: ignore` or refactor your code to avoid this coding pattern. If you are using this pattern in production code, I would recommend refactoring because it's a fragile pattern to begin with. If this is used in test code, then simply suppressing the error may be justified.

**Comment by vbrozik** [comment]
Thank you for the explanation. The example is of course maximally simplified.

In reality I am calling `reset_state()` at multiple places of the function so to follow the DRY principle I think it is logical to create the nested function for this.

I am not sure if this is a bad design when everything is encapsulated inside a function of just several dozen lines.

What about adding the Pylance a limited lookup? For example:
* Just for unconditional calls of nested functions.
* Just for a single level of function nesting?

**Comment by erictraut** [comment]
Tracking side global or non-local effects across execution contexts isn't feasible within a type analyzer.

As I said, I recommend that you avoid this coding pattern. There are typically always better approaches. If you don't want to refactor your code, you can use `# type: ignore` to suppress the error.
