### ISSUE TITLE
Typing hint for a tuple field in dataclass

### ISSUE THREAD

**Issue by K-W-Li** [microsoft/pylance-release#3051]
## Environment data

-   Language Server version: 2022.7.30 (pyright f3e85ee2)
-   OS and version: macOS Monterey 12.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.5

## Code Snippet

```python
from dataclasses import dataclass, field


@dataclass
class Class:
    something: tuple[int, ...] = field(default_factory=tuple)

```

## Expected behavior

Pass pyright strict type checking without error.

## Actual behavior

Shows an error
- (variable) something: tuple[Unknown, ...]
- Type of "something" is partially unknown
    - Type of "something" is "tuple[Unknown, ...]" Pylance ([reportUnknownVariableType](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules))

**Comment by K-W-Li** [comment]
I can confirm no third-party library named ```dataclasses``` is installed.

Current vscode configuration:
```
{
    "python.languageServer": "Pylance",
    "python.analysis.inlayHints.functionReturnTypes": true,
    "python.analysis.inlayHints.variableTypes": true,
    "python.analysis.typeCheckingMode": "strict"
}
```

Notice there will be no error if you set ```python.analysis.typeCheckingMode``` to ```basic```.

**Comment by K-W-Li** [comment]
Update:
I tried switching to pre-release of Pylance and no error is shown. Maybe it is solved by new pyright version?
Though mouse over ```something``` gives typing hint: ```(variable) something: tuple[()]```. Is it expected?

**Comment by erictraut** [comment]
Yes, the version of pyright used in the public version of pylance is nearly two weeks out of date, and a number of issues have been fixed since then. I'm glad to hear that switching to the pre-release version addressed the issue.

The `tuple[()]` hover text is currently expected, but it is somewhat misleading. It is caused by an interaction between the `field` type declaration and a recent change made to the type information for the `tuple` constructor in the typeshed stubs. I requested that the recent change to the tuple constructor be reverted, and it subsequently was. The next release of pyright will pick up this typeshed change. In the meantime, you can ignore the misleading hover text in this case. The important part is that the `__init__` method for the dataclass picks up the expected type of `tuple[int, ...]` for the input parameter. You can see this if you type `Class(` and look at the signature help text

![Screen Shot 2022-07-17 at 8 28 59 AM](https://user-images.githubusercontent.com/7040122/179405403-3caff6fd-0c15-4ff4-9b6e-01a882cac53b.png)
.

**Comment by erictraut** [comment]
I just noticed that you were using strict type checking, and that changes my analysis.

It was the recent regression in typeshed (the one that resulted in a type evaluation of `tuple[()]`) that was actually masking the problem you were seeing in 2022.7.30. The prerelease version of pylance (2022.7.31) contains that typeshed regression. Once I updated the typeshed stubs, the regression was fixed, but your `reportUnknownVariableType` error returns. That's because the `field` function is defined as follows:

```python
def field(*, default_factory: Callable[[], _T], ...) -> _T: ...
```

The return type of `field` comes from the `default_factory` return type. In the case of `tuple`, the return type of the `tuple` constructor is `tuple[Unknown, ...]`, which explains why you're seeing that error.

That means you'll need to find some workaround if you want to use strict-mode type checking here. Here are two workarounds:

1. Add a `# pyright: ignore[reportUnknownVariableType]` comment to the end of that line of code.
2. Use a lambda, like this:
```python
    something: tuple[int, ...] = field(default_factory=lambda :tuple())
```
