### ISSUE TITLE
`nodeLanguageServer.0.0.346/server.bundle.js` not found

### ISSUE THREAD

**Issue by ezwiefel** [microsoft/pylance-release#307]
## Environment data

-   Language Server version: 2020.8.3
-   Python extension version: 2020.8.101144 (and later)
-   OS and version: Ubuntu 16.04 (same issue on MacOS 10.15.6)

## Expected behaviour

Language server is able to boot.

## Actual behaviour

An error is raised `The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.`

## Logs

From "Python Language Server" output panel.
```
Error: Cannot find module '/home/azureuser/.vscode-server/extensions/ms-python.python-2020.8.105369/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

## Code Snippet / Additional information
Downgrading to Python extension 2020.7.96456 solves the issue (or copying the nodeLanguageServer folder from the 2020.7.xx extension folder to the 2020.8.xx extension folder)

**Comment by ezwiefel** [comment]
Also raised issue at https://github.com/microsoft/vscode-python/issues/13721

**Comment by jakebailey** [comment]
This is due to the use of some old internal pre-release settings; the code that's making this use will be deleted eventually, but that method hasn't been supported since the Pylance release. Resolved internally.

**Comment by Edilmo** [comment]
Hi - I'm getting this same error on my Mac. I already tried uninstalling everything (and deleting all extensions). Anything else that I could try?

I was doing dogfooding of PyLance (and the PyRight support) before being released (I worked at MSFT).

**Comment by erictraut** [comment]
Hi Edi, did you try the steps suggested in [this related issue](https://github.com/microsoft/vscode-python/issues/13721)? They tell you how to manually delete the old pylance extension from your system. I think this will resolve your problem. If not, let me know, and we'll look for additional solutions.

**Comment by Edilmo** [comment]
Hi Eric,

Yes, I found that Issue before reporting this. I followed the steps there (and also others suggested in a related issue linked there). The error is still happening. I think there is something else that I have to delete (beside the extensions in ~/.vscode/...) but not sure where else vscode extensions (or Pylance specifically) could be storing things.
The Microsoft Python extension has not issues, at least there are no errors in the console if I installed that extension alone. The error happens when I install pylance after installing the Microsoft python extension.
