### ISSUE TITLE
Type issue in library code gets reported in user code

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#3102]
## Environment data

-   Language Server version: v2022.7.41 Pre-Release
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13 Anaconda

## Code Snippet

```python
from ariadne import make_executable_schema

_ = make_executable_schema("")
```

## Repro Steps

1. Install "ariadne" through "pip"
```shell
pip install ariadne==0.15.1
```
2. Set type checking mode to strict.
3. Check the sample snippet.

## Expected behavior

Nothing is reported, as the default value type mismatch occurs in the library code.

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/181199157-873db989-77aa-4b09-b0c5-dfa5b7dea193.png)

## Logs

"settings.json"
```json
{
    "python.analysis.diagnosticMode": "workspace",
    "python.analysis.diagnosticSeverityOverrides": {
        "reportAssertAlwaysTrue": "error",
        "reportConstantRedefinition": "error",
        "reportDuplicateImport": "warning",
        "reportFunctionMemberAccess": "error",
        "reportGeneralTypeIssues": "information",
        "reportImplicitStringConcatenation": "warning",
        "reportImportCycles": "none",
        "reportIncompatibleMethodOverride": "error",
        "reportIncompatibleVariableOverride": "error",
        "reportInvalidStubStatement": "none",
        "reportMissingTypeArgument": "none",
        "reportMissingTypeStubs": "none",
        "reportOverlappingOverload": "none",
        "reportPrivateImportUsage": "none",
        "reportPrivateUsage": "none",
        "reportPropertyTypeMismatch": "none",
        "reportUnknownArgumentType": "none",
        "reportUnknownLambdaType": "none",
        "reportUnknownMemberType": "none",
        "reportUnknownParameterType": "none",
        "reportUnknownVariableType": "none",
        "reportUnnecessaryCast": "none",
        "reportUnnecessaryComparison": "none",
        "reportUnnecessaryIsInstance": "none",
        "reportUnsupportedDunderAll": "warning",
        "reportUnusedCallResult": "error",
        "reportUnusedClass": "error",
        "reportUnusedFunction": "error",
        "reportUnusedImport": "warning",
        "reportUnusedVariable": "error",
    },
    "python.analysis.typeCheckingMode": "strict",
}
```

**Comment by erictraut** [comment]
This is working as designed. You are calling a function with a default argument, and the type of the default argument doesn't match the annotated type of its parameter. The call is in your code, so the error is reported there.

This error is ultimately caused by a bug in the library's type information. Such bugs can result in user-visible errors during type checking for a wide variety of reasons. So this situation is not unique to a default argument mismatch.

Your choices in this case include:
1. Create a `pyrightconfig.json` file that sets `strictParameterNoneValue` to false. The library appears to be relying on old (deprecated) behavior where ` = None` implies that the parameter type should be `Optional`.
2. File a bug report and/or PR with the library.
3. Use a `# type: ignore` to suppress the error.
