### ISSUE TITLE
Not getting correct types when handling exceptions

### ISSUE THREAD

**Issue by filipecaixeta** [microsoft/pylance-release#3169]
Take this code as an example
```python
def foo(a: int) -> Union[int, Exception]:
    if a>42:
        raise Exception()
    return 42

def bar() -> Union[int, Exception]:
    try:
        b = foo(1)
    except Exception as e:
        raise e
    return b+1
```

It is very clear that `b+1` is a valid operation since `b` can't be of type `Exception` 

This is the error I get

> Operator "+" not supported for types "Exception" and "Literal[1]" when expected type is "int | Exception"

**Comment by erictraut** [comment]
You are using type annotations incorrectly here. The return type annotation for `foo` should be `int`, not `Union[int, Exception]` because the function never returns an object of type `Exception`. The Python static type system is not designed to track or annotate exception types.

If you correct the return type annotations in your code, it will type check without errors.

```python
def foo(a: int) -> int:
    if a > 42:
        raise Exception()
    return 42

def bar() -> int:
    try:
        b = foo(1)
    except Exception as e:
        raise e
    return b + 1
```

**Comment by filipecaixeta** [comment]
Then I guess there is no way to have hints on unhandled exceptions

**Comment by erictraut** [comment]
Correct. The static type system is not designed to reason about exceptions. That's true of compilers and static type checkers in most programming languages.
