### ISSUE TITLE
Intelisense does not work properly when we work with nested objects\lists

### ISSUE THREAD

**Issue by YordanPetrovDS** [microsoft/pylance-release#3184]
The append methond is not recognized by the intelisense maybe because it is applied to a nested list:
![image](https://user-images.githubusercontent.com/51719948/183291201-0332a4c2-495f-4de2-8c79-f28c07c2e170.png)

And also as you can see from the picture below, the atributes of edge object are not recognized:
![image](https://user-images.githubusercontent.com/51719948/183291157-49292225-749e-4e1c-9577-103d6b194b68.png)

**Comment by brettcannon** [comment]
Because the types are hidden within dynamic code, I suspect Pylance can't infer `graph` is a list of lists. You probably need to add a type hint to help Pylance out: `graph: list[list[Edge]]` (assuming the list is meant to contain lists of `Edge` objects).

Tangentially, I would create your `graph` list as:

```python
[[] for _ in range(nodes)]
```

For your first assignment in the loop, I would do:
```python
first, second, weight = map(int, input().split())
```

**Comment by judej** [comment]
Thanks @brettcannon. @YordanPetrovDS, please reopen if this is still a problem.
