### ISSUE TITLE
list(filter(bool ?

### ISSUE THREAD

**Issue by chapmanjacobd** [microsoft/pylance-release#3254]
It seems like `t` should be `list[int]` ?

```
t = list(filter(bool, [1,2,3, None]))
```

but it is

```
t: list[int | None]
```

maybe it is not possible to easily figure that out from the AST ?

```
t = [p for p in [1,2,3, None] if p]
t: list[int]
```

this one is correct

**Comment by erictraut** [comment]
From a type analysis standpoint, `list[int | None]` is the correct type for this expression.

The type of subexpression `[1, 2, 3, None]` is inferred as `list[int | None]`. The `filter` class is defined as follows:
```python
class filter(Iterator[_T]):
    @overload
    def __init__(self, __function: None, __iterable: Iterable[_T | None]) -> None: ...
    @overload
    def __init__(self, __function: Callable[[_S], TypeGuard[_T]], __iterable: Iterable[_S]) -> None: ...
    @overload
    def __init__(self, __function: Callable[[_T], Any], __iterable: Iterable[_T]) -> None: ...
    def __iter__(self: Self) -> Self: ...
    def __next__(self) -> _T: ...
```

Your usage of `filter` employs the third overload of the `__init__` method. That means the resulting type of `filter(bool, [1, 2, 3, None])` is `filter[int | None]`, and the return type of `filter[int | None].__next__` is `int | None`.

You happen to have special knowledge of what `filter` does internally — in this case, eliminating `None`, but a static type checker doesn't have such knowledge. It analyzes expressions based solely on the type information it is provided.

I can suggest a few workarounds.

1. You could define your own filter method that has a declared `TypeGuard` return type. This works because of the second overload of `filter.__init__`. For more details about `TypeGuard`, refer to [PEP 647](https://peps.python.org/pep-0647/).

```python
def is_truthy(val: int | None) -> TypeGuard[int]:
    return bool(val)

t = list(filter(is_truthy, [1, 2, 3, None]))
reveal_type(t) # list[int]
```

2. You can override the evaluated type with a cast.

```python
from typing import cast
t = list(cast(filter[int], filter(bool, [1,2,3, None])))
```
or
```python
from typing import cast
t = cast(list[int], list(filter(bool, [1,2,3, None])))
```
