### ISSUE TITLE
Importing submodule without importing parent causes incorrect unknown member errors

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#3263]
## Environment data

-   Language Server version: v2022.8.40
-   OS and version: macOS 12.5.1
-   Python version: 3.9.13 (conda env)

## Code Snippet

```python
import librosa.core
librosa.midi_to_hz(60)
```

## Expected behavior

No errors should be reported on second line.
Completion should be available after typing librosa followed by a dot.

## Actual behavior

* Error is reported ("midi_to_hz" is not a known member of module) even though the code runs without problems.
* Completion is not available after typing librosa followed by a dot.
* If you add `import librosa`, the error goes away, and completion works.
* `reveal_type(librosa)` shows `Type of "librosa" is "Module("librosa.core")"` which is weird

**Comment by erictraut** [comment]
This is intended behavior. If you are going to use symbols from the parent module, you should import it separately. 

```python
import librosa
```

It's fragile to rely on importer side effects, so pyright (the static type checker that underlies pylance) intentionally does not model these side effects. Your code should be explicit about what modules it is importing.

**Comment by matangover** [comment]
It's not a side effect, it's part of the [language reference](https://docs.python.org/3/reference/simple_stmts.html#import)

```
If the module being imported is not a top level module, then the name of the top level package that contains the module is bound in the local namespace as a reference to the top level package. The imported module must be accessed using its full qualified name rather than directly
```

**Comment by erictraut** [comment]
Yes, the part you quoted is modeled faithfully in pyright. If you use an import statement to reference a submodule, you can then access all of the symbols from that submodule by using its full qualified name. For example, if you use `import a.b`, you can now access symbol `a.b.c` (assuming `a.b` defines a symbol named `c`). It does not mean that you can access `a.foo` because that relies on the side effect of `a` being initialized.

If you want your code to work with pyright's type checker, you'll need to explicitly import the top-level module before accessing symbols in the top-level module. If you don't want to use type checking features, you can disable them by setting `typeCheckingMode` to "off".

**Comment by matangover** [comment]
https://docs.python.org/3/reference/import.html

> A regular package is typically implemented as a directory containing an `__init__.py` file. When a regular package is imported, this `__init__.py` file is implicitly executed, and the objects it defines are bound to names in the package’s namespace. [...] Importing parent.one will implicitly execute `parent/__init__.py` and `parent/one/__init__.py`.

**Comment by erictraut** [comment]
We have discussed this at length before in other forums, and it's unlikely that we will change the behavior in pyright to accommodate reliance on implicit side effects of import loading. As I said, if you want your code to work with pyright's type checker, you'll need to explicitly import the top-level module before accessing symbols in the top-level module.

**Comment by erictraut** [comment]
The purpose of a static type checker is to help you write robust and bug-free code. There are many documented aspects of Python that "work" at runtime but are impossible or infeasible to validate statically or lead to code that is not robust.

There are many ways to subvert static type checking,. If you work with the tool rather than against it, a static type checker will be very effective at helping you write robust and bug-free code. You may need to accommodate small changes in your code to work with the type checker.

Let's consider another example related to implicit import behavior. Let's say that a module `a.py` imports `librosa` and then calls a function defined in another module `b.py` that imports `librosa.core`. The first module `a.py` can now access `librosa.core` even though it didn't explicitly import that submodule. That works because of the documented (implicit) behaviors of the Python import mechanism. Should you rely on this documented implicit behavior? No, not if your intent is to write robust code.

My point with this example is that a static type checker whose goal is to help you write robust and bug-free code should not attempt to model or allow all documented behaviors. There's a judgement call that needs to be made for certain behaviors. We've tried to establish principles and apply them consistently when deciding which behaviors to support in pyright. One of those principles is that we don't support implicit side effects of the Python import loader. (The "Zen of Python" principle "Explicit is better than implicit" is especially applicable here.)

Other pyright users have asked questions about this behavior, but in most cases they realized that they had intended to include an explicit import of the top-level module but forgot to add it. They were thankful that pyright detected the omission. I think you may be the first pyright user who is arguing that reliance on implicit module imports is a good thing — something that you want to rely on in your code.

I don't consider the current behavior a bug. It is working as designed, and the behavior is based on a principle that we have tried to follow consistently.

My recommendation is that we transfer this issue to a discussion section to get additional feedback from other pylance/pyright users. If there is strong signal that many other users also want to rely on this particular form of implicit import loader behaviors, we can revisit this decision in the future.

**Comment by matangover** [comment]
Thanks for taking the time to write a long explanation, I totally understand. While I agree with the general sentiment, I disagree with the specific decision in this case. However, there is no point in discussing it. One thing I would still suggest is adding an explicit ;) specific error message for this case. Because as is, the behavior is confusing - pyright "knows" of the variable librosa but doesn't know of its members, and gives a downright false error message, which to me was very confusing. Hence if this is a conscious design decision, I suggest to implement it in a more user-friendly way. The error could say something like `Member 'librosa.midi_to_hz' cannot be accessed because 'librosa' is not explicitly imported. Add 'import librosa'?`

**Comment by matangover** [comment]
I still don't agree with the 'cannot', but I don't think a type checker error message should include 'should not' :)
