### ISSUE TITLE
ability to ignore path/files from linting

### ISSUE THREAD

**Issue by sureshmalifcst** [microsoft/pylance-release#3286]
I am using dbt packages inside my project.  dbt packages are installed within workspace, (most of it python files). Unable to ignore the errors. When Python analysis is set to workspace.  Set to open files is not solutions. becase I need to any code change that affect rest of the project. requires ignore setting like in pylint.
my directory to ignore.  db/dbt_packages/.   something like this is reqd. \*\*/dbt_packages/\*\*/\*.py

**Comment by erictraut** [comment]
Pylance is built on top of pyright, Microsoft's open-source Python type checker. Pyright provides a way to exclude and/or ignore errors for portions of your project. To use this functionality, you need to create a `pyrightconfig.json` file (or a `pyproject.toml` file, if you prefer) and specify an `exclude` or `ignore` option. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

In your case, you probably want:
```
# pyrightconfig.json
{
    "exclude": ["**/dbt_packages"]
}
```

If the python source files under `dbt_packages` are imported by other modules in your project, pyright will still consider them part of your workspace and analyze them. In that case, you could use "ignore" rather than "exclude" to suppress all of the errors in these files.

**Comment by sureshmalifcst** [comment]
thanks it worked,  @erictraut  we can close the issue.
