### ISSUE TITLE
Provide quick fix for automatic import

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3289]
![image](https://user-images.githubusercontent.com/100815370/188565647-538d7256-2ea3-4717-8938-69c1fe6d3508.png)

![image](https://user-images.githubusercontent.com/100815370/188565705-7535e322-1959-4e04-a69d-b6f61f0fb618.png)

It is strange that automatic import is not provided in quick repair, which requires me to input it manually

**Comment by heejaechang** [comment]
it is happening because pyngrok's ```__init__.py``` is empty. and for third party lib, we only support top level symbols of top ```__init__.py``` and we ignore package that is empty.

for this, you first need to enable indexing in your settings.json  - "python.analysis.indexing": true,

and need to add this hidden option. - "python.analysis.packageIndexDepths":[["pyngrok", 3, true]]

but that being said, according to https://pyngrok.readthedocs.io/en/latest/index.html
```pyngrok.connect``` doesnt exist. so, I dont think connectc will work.

**Comment by heejaechang** [comment]
created an issue - https://github.com/microsoft/pylance-release/issues/3293

**Comment by bschnurr** [comment]
Closing due to external and workaround.
