### ISSUE TITLE
`assert 0` isn't interpreted same as `assert False`

### ISSUE THREAD

**Issue by syagev** [microsoft/pylance-release#332]
## Environment data

-   Language Server version: Pylance language server 2020.8.3 (pyright 8c5415fd)
-   OS and version: Win 10.0.19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.4

## Expected behaviour

`assert 0` should be interpreted same as `assert False` when analyzing code paths.

## Actual behaviour

`assert 0` is not interpreted as an "always stop" code path

## Code Snippet / Additional information

```python
import random

def func():
    cond = random.choice((True, False))
    
    if cond:
        res = 'good'
    else:
        assert 0

    return res
    #      ^^^ pylance alerts for a possibly unbound `res` with assert False above there is no warning
```

**Comment by erictraut** [comment]
This is intended behavior.

Pyright (the static type checker that Pylance is built upon) performs several stages during type checking analysis. During one of the earlier phases (the "binding" phase), Pyright builds a control flow graph to determine which paths the code can take within the program. Some statements generate branches within the control flow graph: if/else statements, ternary operators, and or/and operators (both of which perform early termination). Assert statements also generate control-flow branches. In general, both the "true" and "false" branches in a control flow graph are assumed to be possible at runtime. For example, if an "if/else" statement is encountered, both the "if" and "else" portions of the code flow graph are generally assumed to be executable. However, there are cases where it's important for the code flow graph to be "pruned" based on the use of certain conditional expressions. In particular, Pyright special-cases conditional expressions that involve a boolean literal (False or True), `sys.version_info` comparisons, `sys.platform` comparisons, and the symbol `typing.TYPE_CHECKING`. These cases are needed because it's common for code (especially in type stubs) to declare functions and classes differently based on these conditions.

That is why `assert False` works the way it does. Because "False" is handled as a special case during the binding phase, the control-flow graph is pruned, and later phases of analysis can determine that code flow never exits the bottom of the "else" block.

It would be possible to add support for static evaluation of expressions that contain simple numeric literals like "0", but this is a slippery slope. If Pyright were to support "0" in this case, then someone would expect to also support "0 * 3" and "4 - 2 * 2", "MY_CONSTANT", "x + y", etc. It's not feasible to support all of these cases, especially at such an early phase where no symbol types are known.

If you like the behavior afforded by `assert False`, then you can change your code to that. I'd argue that's more appropriate and readable for an assert statement anyway.

Another workaround is to initialize `res` with `None` so it is not unbound along some code paths.

**Comment by syagev** [comment]
Thanks for the answer. Some of team members like `assert 0` over `assert False` for some unexplained reason, let's see if proper re-education from some leftover C-style personality can resolve this issue ;)
