### ISSUE TITLE
[Question] How to disable warnings for a scope?

### ISSUE THREAD

**Issue by EonYang** [microsoft/pylance-release#333]
Hi, guys, first of all, thank you for providing this fantastic tool. I love it so much. 

Here's a small issue I don't know how to solve.

Suppose there's a warning I'm aware of, but I can't solve it because it's a third-party tool. I also know that it won't hurt me, so I want to just ignore it for this single line. 

I don't wanna suppress the warning for the whole category because I need the warning elsewhere.

Is there a Pylance equivalent works as `# pylint: disable-something`?

Thank you.

### My case

```python3
from smart_open import open
with open('./hello.txt', 'r', transport_params=params) as target:  
    content = target.read()
print(content)

'''
Warning:
{
	...
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Object of type \"str\" cannot be used with \"with\" because it does not implement __enter__",
	"source": "Pylance (reportGeneralTypeIssues)",
	...
}
'''
```

In this case, the return type of `open` includes `str`, but I'll never use that and I know my code will get a `StreamReader` of something. so I wanna ignore this warning for only this line. `reportGeneralTypeIssues` is super useful so I don't wanna disable it globally.

**Comment by erictraut** [comment]
Yes, Pylance follows PEP 484 and supports the `# type: ignore` comment for suppressing diagnostics on a particular line.

There's almost always a better way to handle the error. Here are some common solutions:
1. Add a missing type annotation.
2. Add an assert (e.g. `assert foo is not None` if you know that `foo` cannot be `None` at that location).
3. Use a `cast` call.

In my team's code base, we disallow the use of `# type: ignore` because it's usually not the best fix. That's why I added the [enableTypeIgnoreComments configuration setting](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

**Comment by EonYang** [comment]
Great! This solves my issue.
@erictraut Thank you for your answer and your valuable advice.

**Comment by JosXa** [comment]
You say you support PEP 484, but the decorators mentioned in the same sentence don't seem to work for me. Do you need an example or are `@no_type_check(_decorator)` simply not implemented yet?

> To mark portions of the program that should not be covered by type hinting, you can use one or more of the following:
>
> a `# type: ignore` comment;
> a `@no_type_check` decorator on a class or function;
> a custom class or function decorator marked with `@no_type_check_decorator`.

__https://www.python.org/dev/peps/pep-0484/#compatibility-with-other-uses-of-function-annotations__

**Comment by jakebailey** [comment]
I don't believe we support `no_type_check` or `no_type_check_decorator` as ways to suppress diagnostics; I wasn't aware those were options but I do see them declared in the `typing` stub.

Can you open a new issue? Maybe this is more relevant in the pyright repo, actually. @erictraut

**Comment by erictraut** [comment]
I never implemented these because I considered them a bad idea. There are many other (much better) ways to address individual type-related errors. 

I was reluctant to even add support for "# type: ignore". Within my team's code base, we don't allow "#type: ignore" comments (i.e. we set the "enableTypeIgnoreComments" config to false.)

@JosXa, could you provide a specific example of a type error or series of errors that you're encountering? I could offer you better suggestions for how to address those errors rather than suppressing all of the errors in a scope.

**Comment by JosXa** [comment]
Thanks, and yes of course. Will do that in a new issue then to stop gravedigging 🙂

**Comment by memeplex** [comment]
Sorry to revisit this, but can you add an option to support the popular `# noqa` marker as PyCharm did? It's a bit annoying having to silence flake8 and pylance every time.

**Comment by jakebailey** [comment]
That's a common request, but doesn't seem to have its own issue (which surprises me). It's something we're still considering, and if you make a new issue we can triage it so we don't lose it in comments.

**Comment by stangier** [comment]
Hello, I am stumbling upon this issue while I am looking for a way to disable a specific kind of error for a specific file, much like the creator of the issue stated in the first post. My use case is the following:

```Python
import re
from typing import List

def test(s: str) -> List[str]:
    return re.split("\s", s) 
```

PyLance/PyRight highlights the "\s" with the error: 
`Unsupported escape sequence in string literal - PylancereportInvalidStringEscapeSequence`
This is of course technically correct, because "\s" is no valid escape sequence in Python. It is, however, a correct regular Expression which is parsed correctly by the `re` module. 

I would now like to suppress this specific warning from PyRight/PyLance for this particular file - this warning occurs multiple times in one file. I know that I could disable every warning for every specific line by using `type: ignore`, I do think, however, that disabling it file-wide would be more elegant and versatile, at least for my specific case. Is there any way to achieve this in the current state of PyLance/PyRight?

**Comment by erictraut** [comment]
@stangier, in this case, Pylance is warning you about a legitimate error in your code that you should fix. If you don't, your code could fail to run in future versions of Python. The [Python specification](https://docs.python.org/3/reference/lexical_analysis.html) says the following:

>Unrecognized escape sequences produce a DeprecationWarning. In a future Python version they will be a SyntaxWarning and eventually a SyntaxError.

The correct fix is to change your string literal to: `"\\s"` or to `r"\s"`. Both are correct and will fix the bug in your code.

**Comment by pmsoltani** [comment]
Hi. I found this issue trying to find my way around a SQLAlchemy model:

```python3
from sqlalchemy import Column, Integer, String

from my_app.db_models.base import Base


class Group(Base):
    __tablename__ = "group"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    name: str = Column(String, nullable=False, unique=True)
```

Now, this is a simplified example, but I've added type annotations because late on it would be helpful when developing different queries. However, it drives Pylance crazy:

```
Expression of type "Column[int]" cannot be assigned to declared type "int"
  "Column[int]" is incompatible with "int"PylancereportGeneralTypeIssues
```

Any suggestions on how to keep the annotations and make Pylance happy?

Appreciate your help 🙏

**Comment by erictraut** [comment]
If you're going to add type annotations, you need to use the _correct_ type annotations. It does no good to add incorrect type annotations. The correct type of `id` in your example above is `Column[int]`, not `int`. So pylance is correctly complaining about the type inconsistency.

My recommendation for you is to remove the type annotations in these cases and let pylance infer the proper type. If you want to keep the explicit type annotations, you will need to change them so they are correct.

If you're not interested in type checking, you can change `python.analysis.typeCheckingMode` to "off", and pylance will not report any of these errors.

**Comment by jakebailey** [comment]
Related is #837; since the class for SQLAlchemy is just a descriptor (and the actual instance variables are of the non-column type), I believe the mypy module included with the stubs actually modifies the types to make this type check. It's sort of bad either way, because if you solve this error by making it `Column[int]`, you'll then cause type errors when you try to use it. I would actually think that type ignoring the line would work better, but it's certainly not great that the stubs require the plugin to work to their fullest extent thanks to this.

**Comment by pmsoltani** [comment]
@erictraut @jakebailey Thank you both for your insights. I guess with SQLAlchemy, things always going to be a bit different 😅
Anyway, after @erictraut's reply, I got to thinking that maybe I can make a wrapper function for SQLAlchemy's query to cast the result into [Pydantic](https://pydantic-docs.helpmanual.io/) schemas and problem solved. If I arrive at a solution, I'll publish it here for posterity.

**Comment by jrc** [comment]
Regarding @pmsoltani's issue, simply declaring the type as `Column[int]` didn't work for me, but casting does, e.g.

```
class Group(Base):
    __tablename__ = "group"

    id: int = cast(int, Column(Integer, primary_key=True, autoincrement=True))
    name: str = cast(str, Column(String, nullable=False, unique=True))
```

**Comment by adam-grant-hendry** [comment]
> Yes, Pylance follows PEP 484 and supports the `# type: ignore` comment for suppressing diagnostics on a particular line.
> 
> There's almost always a better way to handle the error. Here are some common solutions:
> 
> 1. Add a missing type annotation.
> 2. Add an assert (e.g. `assert foo is not None` if you know that `foo` cannot be `None` at that location).
> 3. Use a `cast` call.
> 
> In my team's code base, we disallow the use of `# type: ignore` because it's usually not the best fix. That's why I added the [enableTypeIgnoreComments configuration setting](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

One thing these methods do not cover well are unused imports in `__init__.py` files. It's often considered polite to import submodules directly into your package namespace so that users do not have to do deep `.attribute` lookups. In fact, Raymond Hettinger comments on this in PyCon 2015 talk [Beyond PEP 8](https://www.youtube.com/watch?v=wf-BqAjZb8M).

In this instance, without a file-level ignore (or scope-level), one must add `# pyright: ignore[reportUnusedImport]`'s everywhere in this file.

**Comment by adam-grant-hendry** [comment]
> > Yes, Pylance follows PEP 484 and supports the `# type: ignore` comment for suppressing diagnostics on a particular line.
> > There's almost always a better way to handle the error. Here are some common solutions:
> > 
> > 1. Add a missing type annotation.
> > 2. Add an assert (e.g. `assert foo is not None` if you know that `foo` cannot be `None` at that location).
> > 3. Use a `cast` call.
> > 
> > In my team's code base, we disallow the use of `# type: ignore` because it's usually not the best fix. That's why I added the [enableTypeIgnoreComments configuration setting](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).
> 
> One thing these methods do not cover well are unused imports in `__init__.py` files. It's often considered polite to import submodules directly into your package namespace so that users do not have to do deep `.attribute` lookups. In fact, Raymond Hettinger comments on this in PyCon 2015 talk [Beyond PEP 8](https://www.youtube.com/watch?v=wf-BqAjZb8M).
> 
> In this instance, without a file-level ignore (or scope-level), one must add `# pyright: ignore[reportUnusedImport]`'s everywhere in this file.

To be clear, in the above, I do not want to blanket `exclude` the file from `pyright`/`pylance` linting altogether (this is bad practice). Instead, I want to ignore a specific error at a specific scope.

**Comment by erictraut** [comment]
> In this instance, without a file-level ignore (or scope-level), one must add # pyright: ignore[reportUnusedImport]'s everywhere in this file.

The correct way to handle this is to use a redundant form of the import such as `from x import y as y`. This tells type checkers and language servers that `y` is intended to be re-exported from the module, as opposed to private usage (an implementation detail). This convention comes from PEP 484 and has been adopted for "py.typed" libraries. If pyright sees a redundant import form, it will assume that the intent is to re-export the symbol, and it will not mark it as an unused import. Likewise, if the imported symbol appears in an `__all__` definition (which is used by a module to specify which symbols should be included in a wildcard import), pyright will assume that the imported symbol is intended to be re-exported. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface).

**Comment by adam-grant-hendry** [comment]
> > The correct way to handle this is to use a redundant form of the import such as `from x import y as y`.
> 
> I keep forgetting about this! Thank you. I'm going to consider myself a newbie with type hinting...I thought I knew what I was doing, but I clearly still need more practice.
> 
> > This tells type checkers and language servers that y is intended to be re-exported from the module, as opposed to private usage (an implementation detail).
> 
> When I do the redundant alias imports, I keep getting the `mypy` error `Incompatible import of...`. For example, when trying to re-export `z` from `x.y` in my `__init__.py` like so
> 
> ```python
> from x.y import z as z
> ```
> 
> mypy complains
> 
> ```
> Incompatible import of "z" (imported name has type "Type[x.y.z]", local name has type "Type[x.z]") (diff)
> ```
> 
> I can't make heads or tails of this error because I can't find any documentation on it in the [mypy docs](https://mypy.readthedocs.io/en/stable/getting_started.html).
> 
> I actually opened [Issue #13031](https://github.com/python/mypy/issues/13031) on this yesterday.
> 
> Do you know what this error is about?
> 
> Currently, I can't get redundant imports to work because `mypy` will spit out this error.

In my particular instance, this may be happening due to [an existing bug with conditional imports](https://github.com/python/mypy/issues/1153).

**Comment by zoltanszocs** [comment]
What about accessing protected members in unit tests? This seems like an acceptable practice in setting up test data, but it would be good to be able to disable the reportPrivateUsage warning only for a portion of the unit test.
Is there some good solution for this?

**Comment by erictraut** [comment]
You can use `# pyright: reportPrivateUsage=false` at the top of your unit test file. Or you can use `# pyright: ignore[reportPrivateUsage]` on a line-by-line basis.
