### ISSUE TITLE
Today Pylance suddenly throws unimportant errors ?

### ISSUE THREAD

**Issue by blaze-Youssef** [microsoft/pylance-release#3358]
Hi, I use Vs code insiders every day as an IDE for my python projects.
Everything was working smoothly until today, when I opened the IDE, I get a lot of errors that were not yesterday in my code,
like:

> [reportGeneralTypeIssues]

> [reportOptionalMemberAccess]

![Screenshot 2022-09-18 145258](https://user-images.githubusercontent.com/83608661/190910240-83dea57f-d6ff-4402-a366-1a40a8a42bda.png)

I said unimportant errors because the script runs successfully.
I don't remember changing any settings yesterday. 
I am using the default Pylance and python configurations.
I know I can override this in **settings.json** by disabling the above errors, but I want it to get this as default for all my projects.
I am using Vs code for 2 years and never got this problem.
I think an update caused this change.
Any fix?
Update:
I changed to **2022.07.30** and the errors are gone. Now, how to get the same result in new versions?

**Comment by judej** [comment]
Thanks for your report. As you noticed, yes, there is a difference in behavior in the insider builds. Specifically, for the insiders releases, we have changed the default type checking setting from `off` to `basic`. The type checker warnings might appear to be false positives especially when the code runs fine. The reason for the warnings is because Pylance’s type inference is incorrect or incomplete.  

You can turn off type checking with the following setting and that will revert to the old behavior.

`python.analysis.typeCheckingMode': 'off`

Having type checking turned on has several benefits including catching errors early, spotting otherwise hard to find bugs. However, there are circumstances where type checking would be less advantageous - for example, when the code is a small use-once script. Also, when using libraries (like Django) that use dynamic typing, Pylance would complain about not being able to infer type info. This can become noisy.

So, while I'd encourage you to keep the typechecking at 'basic' or even go to 'strict' for well annotated code and when using well typed libraries, if type checking is not appropriate for your codebase, you can turn it off with the setting above.

In an upcoming release we will make changing type checking mode easier by adding that option right on the status bar.

Look forward to any feedback you have on type checking modes.
