### ISSUE TITLE
Wrong reportGeneralTypeIssues for pydantic constrained types annotations

### ISSUE THREAD

**Issue by lachaib** [microsoft/pylance-release#3368]
Hello

## Environment data

-   Language Server version: v2022.9.21 (pre-release
-   OS and version: Linux, MacOS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

Using pydantic 1.10.2

```python
class User(BaseModel):
    first_name: constr(min_length=1) | None
```

## Expected behavior

No reported error (code works fine anyway)

## Actual behavior
Error message is displayed:
Illegal type annotation: call expression not allowed

**Comment by judej** [comment]
Thanks for your report. As you noticed, yes, there is a difference in behavior in the insider builds. Specifically, for the insiders releases, we have changed the default type checking setting from `off` to `basic`. The type checker warnings might appear to be false positives especially when the code runs fine. The reason for the warnings is because Pylance’s type inference is incorrect or incomplete.  

You can turn off type checking with the following setting and that will revert to the old behavior.

`python.analysis.typeCheckingMode': 'off`

Having type checking turned on has several benefits including catching errors early, spotting otherwise hard to find bugs. However, there are circumstances where type checking would be less advantageous - for example, when the code is a small use-once script. Also, when using libraries (like Django) that use dynamic typing, Pylance would complain about not being able to infer type info. This can become noisy.

So, while I'd encourage you to keep the typechecking at 'basic' or even go to 'strict' for well annotated code and when using well typed libraries, if type checking is not appropriate for your codebase, you can turn it off with the setting above.

In an upcoming release we will make changing type checking mode easier by adding that option right on the status bar.

Look forward to any feedback you have on type checking modes.
