### ISSUE TITLE
"Fields without default values cannot appear after fields with default values" when using custom field function

### ISSUE THREAD

**Issue by joelspadin** [microsoft/pylance-release#3393]
I have some code which uses dataclasses and many fields need similar metadata. I created a function which simply calls `dataclasses.field()` and fills in the metadata. For any fields following a field that uses this function, Pylance gives a false positive error saying that a field without a default value cannot appear after a field with a default value, but the previous field does not have a default value.

```py
def customfield(v):
    return field(metadata={"custom": v})

@dataclass
class Test:
    foo: str = customfield(True)
    bar: str # <- Fields without default values cannot appear after fields with default values
```

If I write the same code using `field()` directly instead of my helper function, Pylance correctly does not flag this as an error.

```py
@dataclass
class Test:
    foo: str = field(metadata={"custom": True})
    bar: str
```

**Comment by erictraut** [comment]
Static type checkers like pyright (the type checker that underlies pylance) require that you use `field()` directly in your dataclass definition. It won't work if you call `field` dynamically in another function. This is because the values passed as arguments to the `field` function must be statically evaluated because many of them affect the type behavior. It's also related to the fact that the `field` function in `dataclasses.pyi` is declared to return an `Any` value, so the inferred return type of `customfield` is also `Any`.

So you'll need to use `field()` directly if you want this to work with static type checking.

Do you have typeCheckingMode set to "basic", or is it "off"? Currently, this error message is always emitted regardless of the typeCheckingMode. The error isn't associated with any type checking rule. I think it would be reasonable to associate it with the `reportGeneralTypeIssues` rule. That way, the error would no longer be emitted if typeCheckingMode is set to "off". Note, however, that this will simply suppress the error. Pyright will not synthesize the intended `__init__` method for the dataclass, so you will not get correct signature help when calling the `Test` class constructor. For this reason, I still recommend using `field()` directly in your dataclass definition rather than calling another function.

**Comment by joelspadin** [comment]
Thanks. I'll just make a function which returns the required metadata and use it like
```py
@dataclass Test:
    foo: str = field(metadata=custommeta(True))
```

This is a bit of annoying boilerplate, but if there's no way the static type checker could reasonably be made to understand this, it's not that bad.

**Comment by olivercoleman-switchdin** [comment]
A workaround is to add `(kw_only=True)` to the `@dataclass` decorator.
This also works with the `attrs` package class decorators. 

```
def customfield(v):
    return field(metadata={"custom": v})

@dataclass(kw_only=True)
class Test:
    foo: str = customfield(True)
    bar: str
```
