### ISSUE TITLE
`exclude` in pyrightconfig.json not working

### ISSUE THREAD

**Issue by maxwellzh** [microsoft/pylance-release#3406]
## Environment data

-   Language Server version: 2022.9.40
-   OS and version: on remote linux server ubuntu 18.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Describe the bug

I don't want the fs watcher to track the update of the log files (which updates very frequently), and here is my configuration `pyrightconfig.json`

```json
{
    "verboseOutput": true,
    "exclude": [
        "**/log"
    ]
}

```

But it just not working.

```
...
[Info  - 12:59:00] (71313) SourceFile: Received fs event 'change' for path '/mnt/workspace/zhenghh/Transducer-dev/egs/aishell/exp/test-ctc-base/log/20220929-062141/events.out.tfevents.1664403701.ubuntu.45913.0'
[Info  - 12:59:00] (71313) SourceFile: Received fs event 'change' for path '/mnt/workspace/zhenghh/Transducer-dev/egs/aishell/exp/test-ctc-base/log/20220929-062141/events.out.tfevents.1664403701.ubuntu.45913.0'
[Info  - 12:59:00] (71313) SourceFile: Received fs event 'change' for path '/mnt/workspace/zhenghh/Transducer-dev/egs/aishell/exp/test-ctc-base/log/20220929-062141/events.out.tfevents.1664403701.ubuntu.45913.0'
[Info  - 12:59:01] (71313) SourceFile: Received fs event 'change' for path '/mnt/workspace/zhenghh/Transducer-dev/egs/aishell/exp/test-ctc-base/log/20220929-062141/events.out.tfevents.1664403701.ubuntu.45913.0'
[Info  - 12:59:01] (71313) SourceFile: Received fs event 'change' for path '/mnt/workspace/zhenghh/Transducer-dev/egs/aishell/exp/test-ctc-base/log/20220929-062141/events.out.tfevents.1664403701.ubuntu.45913.0'
```

**Comment by debonte** [comment]
`exclude` excludes files from analysis, not from the file watcher. See https://github.com/microsoft/pyright/issues/2108#issuecomment-884932599

**Comment by joaotavora** [comment]
Hello @debonte,

In this issue joaotavora/eglot#1224 issue a user is reporting that watching too many files in `.venv` (presumably uselessly since these files aren't changed during development) exhausts the file-watching capabilities of certain clients in certain operating systems (such as MacOSX).  

If something is excluded from analysis, why not _also_ exclude it from the file watcher?  If this is "by design" what is the rationale for this design?

**Comment by rchiodo** [comment]
There's a separate setting for excluding things from the file watcher. VS code has a setting for that : `files.exclude`. 

It's described here:
https://code.visualstudio.com/docs/getstarted/settings

**Comment by erictraut** [comment]
Files that are part of the project can import symbols from files in the venv. That means type analysis is affected by these files. If files in the venv change (e.g. due to a `pip install` or `pip uninstall`), type analysis needs to be performed again on any dependent files. The contents of the venv also affects language server features like completion suggestions with auto-import. When the venv files change, any cached auto-import information needs to be invalidated and recomputed.

The `exclude` setting in the pyrightconfig is completely unrelated to import dependency tracking. It should have no bearing on which files the fs watcher is applied to.

**Comment by joaotavora** [comment]
Certainly some files in `.venv` are probably worth analysing and/or watching.  But as far as I understand, Pyright requests by default that _every file_ in the project is analysed.  I'm not a Pyright user but the bug reporter sent me this report of a server request  (this is JSON represented as Lisp, you should be able to read it).

```
[server-request] (id:4) Fri May 12 02:33:40 2023:
(:jsonrpc "2.0" :id 4 :method "client/registerCapability" :params
  (:registrations
    [(:id "5f68e7c3-d6be-46f9-b8f5-18ca46acd165" :method "workspace/didChangeWatchedFiles" :registerOptions
       (:watchers
         [(:globPattern "**/pyrightconfig.json" :kind 7)
           (:globPattern "**" :kind 7)]))]))
```

Presumably the user's `.venv` file has a lot of files and maybe -- rather probably -- not all of them are Python files in the conditions you describe.  So why ask the client to spend system resources to watch them?  What files is Pyright actually interested in?

**Comment by erictraut** [comment]
None of the files in a venv are "analyzed", but their contents (and even their presence) affects the type analysis of files within your project. They also affect which symbols are available for completion suggestions.

The addition or removal of any importable file (".py", ".pyi", ".pyc", ".so", etc.) or any directory within the `site-packages` directory can affect import resolution. Likewise, any of these can necessitate the addition or removal of auto-import entries. It's reasonable for users to expect that when a change is made to their venv, a language server will be smart enough to reflect those changes without restarting the language server.

Modern file systems allow a caller to install a file watcher on a directory recursively. Changes are then reported for any directory or file within that hierarchy. This doesn't require significant system resources.

**Comment by joaotavora** [comment]
> The addition or removal of any importable file (".py", ".pyi", ".pyc", ".so", etc.)

If these are the files you are interested in, just code this into Pyright so that -- instead of `**` -- it requests watcher in files.  Aren't LSP globs flexible enough for you?  Do you _really_ need to watch `**` i.e. ALL files??

> This doesn't require significant system resources.

Depends on the implementation underlying platform.  On Linux, you're right, on Mac OSX, the kqueue mechanism doesn't scale well and hits a limit.  And there's also the case of all the wasted client->server bandwidth for files that Pyright probably couldn't care less about.

**Comment by erictraut** [comment]
All directories and nearly every file within a venv need to be watched.

> Depends on the implementation underlying platform. On Linux, you're right, on Mac OSX, the kqueue mechanism doesn't scale well and hits a limit.

I regularly use pyright and pylance with venvs that contain 10K+ files on a Mac, and I don't see problems with recursive fs watchers or watcher exhaustion.

Also, my understanding is that this is a per-process limit, not a global limit, so if some fs-specific limit is reached, it should affect only pyright, not other processes. Pyright degrades gracefully in this case. It sill runs, but you will need to restart the language server if you make changes to your venv.

> And there's also the case of all the wasted client->server bandwidth

This hasn't been an issue. Files and directories within a venv don't typically change very often. Only when installing and uninstalling libraries.

Are you concerned about some theoretical problem, or are you observing an actual problem? If it's an actual problem, what symptoms are you seeing?

**Comment by joaotavora** [comment]
> Are you concerned about some theoretical problem, or are you observing an actual problem? If it's an actual problem, what symptoms are you seeing?

Actual problem.  See issue I linked to: https://github.com/joaotavora/eglot/issues/1224

> All directories and nearly every file within a venv need to be watched.

Hmm, just how much is in that "nearly"?  In the user's MRE, they install `numpy` and `numpydoc` only.  Just from those two packages, I ran the following command (taken from your account of the file extensions needed to track dependencies).

```
❯ find .venv | grep  -E -v "\.(py.?|so)$" | grep -E -v "^.venv/bin" | wc -l
3410
```

That list is full of C, fortran, csv files, txt files.  Does Pyright need to be notified of changes to them?  Why?

> I regularly use pyright and pylance with venvs that contain 10K+ files on a Mac, and I don't see problems with recursive fs watchers or watcher exhaustion.

That's because your're either using a client that doesn't use `kqueue` watchers or you're using a client that actively refuses to put watches in `.venv` ,such as this one. https://github.com/emacs-lsp/lsp-mode/blob/c8bbdb80ed2dbfdbf55b6c4058308dab092306b5/lsp-mode.el#L366.  The latter, according to your account, will have broken dependency tracking.

I maintain another client, whose platform on Mac OS also uses `kqueue`. I'm asking this question before offering my users a IMHO cumbersome & error-prone option of ignoring server watches.

> This hasn't been an issue. Files and directories within a venv don't typically change very often. Only when installing and uninstalling libraries.

Anyway, this isn't about `.venv` only.  It's not very hard to imagine projects having many more files changed very frequently.  This users's log files, for example: https://github.com/microsoft/pyright/issues/2108#issuecomment-884932599

> Also, my understanding is that this is a per-process limit, not a global limit, so if some fs-specific limit is reached, it should affect only pyright, not other processes. Pyright degrades gracefully in this case. It sill runs, but you will need to restart the language server if you make changes to your venv.

The watchers are owned by the process which runs the client.  That process `emacs` in this case, can be connecting to many other LsP servers (for other documents in other languages).  So it affects other processes.

Here's the relevant interaction from my user's log file:
```
[server-notification] Fri May 12 02:33:40 2023:
(:jsonrpc "2.0" :method "window/logMessage" :params
  (:type 3 :message "Found 11 source files"))
[server-request] (id:4) Fri May 12 02:33:40 2023:
(:jsonrpc "2.0" :id 4 :method "client/registerCapability" :params
  (:registrations
    [(:id "5f68e7c3-d6be-46f9-b8f5-18ca46acd165" :method "workspace/didChangeWatchedFiles" :registerOptions
       (:watchers
         [(:globPattern "**/pyrightconfig.json" :kind 7)
           (:globPattern "**" :kind 7)]))]))
[client-reply] (id:4) ERROR Fri May 12 02:33:41 2023:
(:jsonrpc "2.0" :id 4 :error
  (:code -32603 :message "Internal error"))
[server-notification] Fri May 12 02:33:41 2023:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
  (:uri "file:///Users/tfn/Library/CloudStorage/Dropbox/fortochka/Python/Doodles/tree.py" :version 0 :diagnostics
    []))
[stderr] Error: Internal error
[stderr]     at handleResponse (/Users/tfn/.cache/pyright-python/1.1.307/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
[stderr]     at handleMessage (/Users/tfn/.cache/pyright-python/1.1.307/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
[stderr]     at processMessageQueue (/Users/tfn/.cache/pyright-python/1.1.307/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
[stderr]     at Immediate.<anonymous> (/Users/tfn/.cache/pyright-python/1.1.307/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
[stderr]     at processImmediate (node:internal/timers:478:21)
```

My understanding from this is that Pyright, upon receiving the "internal error" report by the client that the humongous file-watching request couldn't be honoured, just dies.  My client will then restart it a few times, but that will just make Pyright start up again and re-request the watchers.   I don't have Mac OS to test this.

Finally, curiously the users seems to hint that Pyright (when ran standalone) has file watching capabilities itself (but they don't seem to work also).

**Comment by erictraut** [comment]
> That's because you're either using a client that doesn't use kqueue watchers

Yeah, that would explain it. I'm using VS Code. Perhaps you would consider updating your client to use a more robust fs watcher mechanism on MacOS? Even if we were to change pyright to specify only a subset of file types (plus all directories), I think you'd find that you'd hit the same issue for all but the smallest of venvs. In other words, I don't think this is something we can fix within pyright.

I think you'll need to find a workaround for this issue in your client if you want to work with the pyright language server. One option is to report that your client isn't compatible with server-side file watchers, and pyright will then not attempt to request any file watchers from your client.

> Pyright (when ran standalone) has file watching capabilities itself

Yes, if you run the CLI version of pyright in `--watch` mode, it uses file watchers to determine what has changed in the venv. If it's unable to install a file watcher, it still works fine, but users need to restart pyright if they modify their venv.

**Comment by joaotavora** [comment]
> I think you'll need to find a workaround for this issue in your client if you want to work with the pyright language server. One option is to report that your client isn't compatible with server-side file watchers, and pyright will then not attempt to request any file watchers from your client.

You mean "report that your client isn't compatible with **client**-side file watcher", right??  Well, it is compatible and no other server has this problem. But yes, my client's users can do that.  But will Pyright server-side's watching capabilities kick in then?

> Perhaps you would consider updating your client to use a more robust fs watcher mechanism on MacOS? 

That's being worked on AFAIU, but it there's still old versions to think about.  And I think it's infinitely easier to supply an option in pyright, similar to the `exclude`.  

Or to just not request the `**` blob.  I can't think of a good reason not to fix that `**` blob on Pyright's side since at the very least Pyright's insistence on keeping it will _still_ lead to tons of useless messages from the client -> server.  On every platform, and regardless of venv or not.  It's quite possible it's a one-line fix somewhere in your code:

```diff
diff --git a/packages/pyright-internal/src/languageServerBase.ts b/packages/pyright-internal/src/languageServerBase.ts
index 7e296a021..27cba25a7 100644
--- a/packages/pyright-internal/src/languageServerBase.ts
+++ b/packages/pyright-internal/src/languageServerBase.ts
@@ -1390,7 +1390,7 @@ export abstract class LanguageServerBase implements LanguageServerInterface {
         // Set default (config files and all workspace files) first.
         const watchers: FileSystemWatcher[] = [
             ...configFileNames.map((fileName) => ({ globPattern: `**/${fileName}`, kind: watchKind })),
-            { globPattern: '**', kind: watchKind },
+          { globPattern: '*.{py,pyc,pyi,so}', kind: watchKind },
         ];
 
         // Add all python search paths to watch list
```

**Comment by simurgh9** [comment]
<p align="center"><img width="1027" alt="sc" src="https://github.com/joaotavora/eglot/assets/43047754/72c12fa8-bf52-4f17-b7f9-f3517b9d9a08"></p>

@erictraut the above is on MacOS Venture 13.3.1 and Pyright 1.1.307.

Now, I don't entirely understand what is going on, but, could you help me understand or tell me why my questions don't make sense?

What is this bit saying,

```
Search paths for /Users/tfn/Desktop/mre
  /Users/tfn/.cache/pyright-python/1.1.310/node_modules/pyright/dist/typeshed-fallback/stdlib
  /Users/tfn/Desktop/mre
  /Users/tfn/Desktop/mre/typings
  /Users/tfn/.cache/pyright-python/1.1.310/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11
  /opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
  /Users/tfn/Desktop/mre/.venv/lib/python3.11/site-packages
```

Is it that it is looking for changes to files in those directories? If so, why do we need to look for changes in `/Users/tfn/.cache/pyright-python/1.1.310/node_modules`?

Also with `/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11` are we expecting changes to the Python standard libraries, e.g., for completion?

`Watcher could not use native fsevents library. File system watcher disabled.` Why not? Is this due to the excessive file watch requests? If yeah, should this not be handled in someway within Pyright since I am running it with nothing else and this seems like an undesirable behaviour caused solely by invoking Pyright in the Terminal.app.
