### ISSUE TITLE
Method suggestion from stubfile type hints

### ISSUE THREAD

**Issue by m-lyon** [microsoft/pylance-release#3422]
Given type hints for a variable within a `.py` file, Pylance will recognise the type hint and provide method suggestions and colour the method accordingly. This is great, but sometimes i'll have a long function or method declaration that i don't want to clutter with typehints inline. To provide type hints still I can use a `.pyi` stub file, however when editing the associated `.py` file, Pylance doesn't seem to recognise the variable type hints. Below is a simple example

Given the two files in a python project:

```python
# test_file.py

def test_func(var1, var2):
    return var1 + var2
```

```python
# test_file.pyi

def test_func(var1: str, var2: str) -> str: ...
```
If i were to then begin typing `var1.` within `test_func` in `test_file.py`, there would be no method suggestions.

Is there a way to enable the desired behaviour?

**Comment by erictraut** [comment]
That's not how stub files work. A stub file is designed to be a stand-in for a library module when that module's source is not available (e.g. it is written in another language like C) or the library author has not included inlined types for that module.

The type information for a stub file is used when you import that module. In your case above, the type information for `test_file.pyi` will be used if you `import test_file`. The type information in the stub is not used in `test_file.py` itself. That would require somehow "merging" symbols and type information between the ".pyi" and ".py" file.

If you are developing your own code, you should provide type annotations directly within the code. Type stubs will not work in this case because that's not what they're designed to do.

**Comment by erictraut** [comment]
It's perhaps useful to think of type annotations as "super comments". They're better than normal comments in that they are unambiguous and readable by both humans and computers, and enforceable by programming tools. Text-based comments can be incomplete, ambiguous, and can be understood only by human readers.

I'm guessing that you wouldn't say "I don't want to clutter my code with comments".

**Comment by m-lyon** [comment]
Ah, my apologies for misunderstanding the intended purpose of stub files. Thank you for taking the time to respond.

> I'm guessing that you wouldn't say "I don't want to clutter my code with comments".

Yes that's very true. I think overall this is an aesthetic preference but I find typical docstring formatting, e.g. below, to be visually pretty good.
```python
'''Some function description

Args:
    arg1 (type): description
    arg2 (type): etc
'''
```
However, having to wrap around a function definition into an indented list when the line gets too long isn't visually as good (in my opinion), so really I was looking for a 'have your cake and eat it' type situation.

Thanks for your insights anyway.

**Comment by erictraut** [comment]
Yeah, if you're not used to looking at type annotations, an annotated function might seem "cluttered" at first. You may find after a while that function signatures look "naked" without annotations. :)

If you're worried about formatting and readability, one technique that many Python developers now use is to rely on an auto-formatter like "black". This eliminates the mental overhead of code formatting, and it does a great job formatting long function signatures with type annotations so they are readable.

```python
def test_func(var1: str, var2: str) -> str: ...

def test_func_long(
    var1: str,
    var2: str
    var3: list[str]
    var4: int | None = None
) -> str: ...
```
