### ISSUE TITLE
Auto import not working for symbols in`__init__.py`

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#3446]
### Discussed in https://github.com/microsoft/pyright/discussions/4018

<div type='discussions-op-text'>

<sup>Originally posted by **daya0576** October  7, 2022</sup>
I understand that auto import only works for symbols that have been imported. 

But for the symbol `foo` already imported in file `a.py`, still can not be found in `b.py`:

```
├── a.py
├── b.py
└── module
    └── __init__.py

==> __init__.py <==
class Foo:
    ...
foo = Foo()
__all__ = ["foo"]
```

```python
==> a.py <==
# import symbol foo manually
from module import foo
print(foo)

==> b.py <==
# auto import still not working
foo

```

</div>

**Comment by heejaechang** [comment]
@daya0576 HI. as Eric explained in the discussion, we only enable it through `add import` from `code action`, but not through `auto import` from `completion`. the reason is to reduce number of items shown in `completion` which can impact user's editor typing experience.

As you can see the below, you should be able to get it through `add import`
![addimport](https://user-images.githubusercontent.com/1333179/199892633-a1792ba2-7a14-4d1b-b251-3bb477ae6c2c.gif)

and you don't need mouse to execute the code action, you can use shortcut key for the `quick fix`
![image](https://user-images.githubusercontent.com/1333179/199893458-268e537f-7dca-43ea-b50c-40a203e08259.png)

**Comment by daya0576** [comment]
> the reason is to reduce number of items shown in completion which can impact user's editor typing experience.

Discussed with @erictraut that allowVariableInAll is disabled by default.
https://github.com/microsoft/pyright/discussions/4018#discussioncomment-3826742

Is it possible to provide user an option? whether including variables from `__all__` or not ❤️
