### ISSUE TITLE
Pylance incorrectly complains about inner-class reference even when postponed evaluation of annotations is enabled

### ISSUE THREAD

**Issue by mjarosie** [microsoft/pylance-release#3483]
<h3> Environment data </h3>

-   Language Server version: 2022.10.20
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.6
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from __future__ import annotations
from typing import TypedDict


class MyClass:
    class SomeIdFieldDict(TypedDict):
        some_nested_field: str

    class SomeDict(TypedDict):
        id: SomeIdFieldDict | None


def f(x: MyClass.SomeDict) -> None:
    print(x)


if __name__ == '__main__':
    f({"id": {"some_nested_field": "a"}})
    f({"foo": "bar"})
```

<h3> Repro Steps </h3>

1. Install "Python" extension v2022.16.1 in Visual Studio Code
2. Open the file with the above code.

<h3> Expected behavior </h3>

Pylance correctly resolves a reference to `SomeIdFieldDict` type thanks to the "postponed evaluation of annotations" functionality enabled by importing `from __future__ import annotations` (see [PEP 563](https://peps.python.org/pep-0563/)).

The code itself works, by invoking `python test.py` with the above code put in `test.py` file - the output is:

```
{'id': {'some_nested_field': 'a'}}
{'foo': 'bar'}
```

When the `__future__` import is removed, the following error expectedly occurs:

```
Traceback (most recent call last):
  File "/.../test.py", line 4, in <module>
    class MyClass:
  File "/.../test.py", line 8, in MyClass
    class SomeDict(TypedDict):
  File "/.../test.py", line 9, in SomeDict
    id: SomeIdFieldDict | None
NameError: name 'SomeIdFieldDict' is not defined
```

<h3> Actual behavior </h3>

Pylance complains with `reportUndefinedVariable` error that `"SomeIdFieldDict" is not defined`:

![image](https://user-images.githubusercontent.com/9082353/196035359-0bb1857f-2fd0-4246-bd2a-6a08f0982188.png)

**Comment by erictraut** [comment]
This isn't an issue of "postponed evaluation". After all, the `SomeIdFieldDict` symbol is defined before it is used in this case.

This is an issue of scoping rules and symbol resolution. In Python's scoping rules, a symbol defined in a class scope is not visible (i.e. not captured by) an inner class or function defined within that same outer class.

You can see this if you attempt to do something like this:
```python
class Foo:
    class A: ...

    class B:
        x = A() # Error: A not defined
```

Since `SomeIdFieldDict` isn't visible from that scope, you can't access it by simple name. If you were to use this in a runtime type checker (which would probably call `typing.get_type_hints()`), it would receive an exception trying to evaluate this symbol in a postponed manner.

If you want to use `SomeIdFieldDict` in a type annotation at this location, you need to refer to it by its qualified name starting with `MyClass`, which is visible from the inner scope of `SomeDict`.

```python
    class SomeDict(TypedDict):
        id: MyClass.SomeIdFieldDict | None
```

So, this isn't a bug in pylance. This is a bug in your code, and pylance is correct to flag it as an error.

**Comment by mjarosie** [comment]
Ok that's clear now, thanks for taking time to explain this. I'll close the issue.
