### ISSUE TITLE
Is a classmethod a classvar?

### ISSUE THREAD

**Issue by CaselIT** [microsoft/pylance-release#3484]
Hi

as per title, is a classmethod considered a classvar?
In particular if it can override a variable defined a classvar in a supertype, since pylance, pyright and mypy seem to have differing opinions in this regard.

The following example type checks fine in mypy and pyright 
```py
from typing import Any, ClassVar

class Foo:
    Bar: ClassVar[Any]

class Baz(Foo):
    @classmethod
    def Bar(cls) -> int:
        return 42

class FooBar(Foo):
    Bar = 42
```
but errors in pylance with 
```
Instance variable "Bar" overrides class variable of same name in class "Foo"Pylance[reportIncompatibleVariableOverride](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

Adding classmethod  to the Bar definition works for pylance and pyright
```py
from typing import Any, ClassVar

class Foo:
    Bar: ClassVar[Any] | classmethod[Any]

class Baz(Foo):
    @classmethod
    def Bar(cls) -> int:
        return 42

class FooBar(Foo):
    Bar = 42
```
but errors in mypy with
```
error: Invalid type: ClassVar nested inside other type  [misc]
error: Signature of "Bar" incompatible with supertype "Foo"  [override]
```

Context for this question is [`__tablename__` in sqlalchemy](https://github.com/sqlalchemy/sqlalchemy/blob/c97ab04e0138a9e1fb612938047cf337dc1ec100/lib/sqlalchemy/orm/decl_api.py#L688), that's currently typed as `ClassVar[Any]` but that's not liked by pylance.
This is the original issue reported to sqlalchemy https://github.com/sqlalchemy/sqlalchemy/issues/8645

cc @zzzeek

**Comment by erictraut** [comment]
The `reportIncompatibleVariableOverride` is a strict-mode check that is not enabled by default. I presume that you've enabled it manually or set typeCheckingMode to "strict".

The `reportIncompatibleVariableOverride` check validates when a variable is declared in a base class, a subclass that attempts to override this symbol declares it as a variable of a compatible type. If the variable is declared as `Final` or `ClassVar`, it also verifies that the override does not violate those variable attributes. As with many of pyright's strict-mode checks, it tends to be a bit more opinionated (and hence strict) about what it considers correct.

In your code sample above, the base class `Foo` declares a class-scoped variable called `Bar` and indicates that this variable must be a `ClassVar` — i.e. it cannot be written through an object reference. The subclass then attempts to redeclare a symbol of the same name not as a variable but as a method using a `def` statement. There is no way with a `def` statement to specify whether the symbol should have `ClassVar` semantics because `ClassVar` is meant to be used with variables, not methods.

If your intent is to require that a subclass provide a compatible class method implementation, then I recommend using the ABC pattern, like this:

```python
class Foo(ABC):
    @abstractmethod
    @classmethod
    def Bar(cls) -> int:
        raise NotImplementedError()
```

If your intent is to assign the value of the class variable `Bar` to a value that happens to be a function defined locally in the class, you could use the following approach.

```python
class Baz(Foo):
    @classmethod
    def _Bar(cls) -> int:
        return 42
    
    Bar = _Bar
```

In your example, is `Foo` a class in a library that you're consuming, or is it in your own code? If it's your own code, then I recommend against using `Any` to define the variable's type if you're interested in strict type checking. Using `Any` undermines the utility of strict-mode type checking.

I'll also note that the type annotation `ClassVar[Any] | classmethod[Any]` doesn't make sense and should be considered illegal. `ClassVar` is a special form, not a class, so it cannot be combined with other types using a union operator. The expression `ClassVar[classmethod[Any] | Any]` is a valid annotation, but it's kind of a silly type because a union with `Any` is effectively the same as `Any`.

**Comment by CaselIT** [comment]
Thanks for the reply, the reasoning makes sense to me.

> In your example, is `Foo` a class in a library that you're consuming, or is it in your own code?

The example here is extracted from the sqlalchemy library, where the base class for model has the `ClassVar[Any]` signature for `__tablename__`. It's defined here https://github.com/sqlalchemy/sqlalchemy/blob/c97ab04e0138a9e1fb612938047cf337dc1ec100/lib/sqlalchemy/orm/decl_api.py#L688

I gather that the only alternative is to type something that can be a class variable or a classmethod so that it passes strict checking is `Any`?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by kkirsche** [comment]
@judej out of curiosity, why was this closed when the submitter was the one asking the question, not a Pylance team member?
