### ISSUE TITLE
Identifying Issue in code with functioning code

### ISSUE THREAD

**Issue by ancrahul** [microsoft/pylance-release#3493]
Type: <b>Bug</b>

highleting working code with red underline and previously it was working absolutly fine

Extension version: 2022.10.20
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:47.539Z)
OS version: Linux x64 5.15.0-50-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx (8 x 2395)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|5.68GB (1.65GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id aaecdb52-cac3-4267-b866-dfe5941ec134|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pylantcb52:30590119
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by debonte** [comment]
@ancrahul, can you please provide the error that you are seeing and a code snippet that reproduces the issue?

**Comment by williamzerner** [comment]
Same here.. the error varies from case to case. Sometimes a variable i which is part of a for loop (Python) will be red underlined saying i is unbound. 

![image](https://user-images.githubusercontent.com/29161352/196389475-e3bb2c4b-3a0e-447e-b614-cb3454244543.png)

This is one of the examples and this started coming since today. I am connected to my SSH via VSCode.

**Comment by williamzerner** [comment]
> Same issue here, all my code is was okay 2 days ago, now it shows a lot highlighted errors (that are not actually errors, the code works just fine and they were not highlighted before). ![image](https://user-images.githubusercontent.com/68303239/196473799-04093e06-b60c-4407-9c16-90226db7347b.png) ![image](https://user-images.githubusercontent.com/68303239/196473993-f42be3e4-3e0b-4096-83a2-b4a5546f3cf6.png)

Are you also running the code on SSH?

**Comment by ReiDoBrega** [comment]
> Same issue here, all my code is was okay 2 days ago, now it shows a lot highlighted errors (that are not actually errors, the code works just fine and they were not highlighted before). ![image](https://user-images.githubusercontent.com/68303239/196473799-04093e06-b60c-4407-9c16-90226db7347b.png) ![image](https://user-images.githubusercontent.com/68303239/196473993-f42be3e4-3e0b-4096-83a2-b4a5546f3cf6.png)

it's not the best fix but I was having the same problem here so I went back to PyLance version `2021.12.2` and the problem was "solved"

**Comment by ReiDoBrega** [comment]
> Same issue here, all my code is was okay 2 days ago, now it shows a lot highlighted errors (that are not actually errors, the code works just fine and they were not highlighted before). ![image](https://user-images.githubusercontent.com/68303239/196473799-04093e06-b60c-4407-9c16-90226db7347b.png) ![image](https://user-images.githubusercontent.com/68303239/196473993-f42be3e4-3e0b-4096-83a2-b4a5546f3cf6.png)

downgrade to PyLance v2022.8.10

**Comment by judej** [comment]
@ReiDoBrega, @williamzerner, @ancrahul, @GonzaloVich, thanks for the reports. The reason you are seeing this is because, we started to roll out a setting change: making the type checking `basic` by default. Previously, it was `off`. Type checking helps you find bugs that you might typically miss if you did not have type checking.

To turn it off, if you hover over the `{} Python` in the toolbar and click `Switch to off` as shown below.
![Python-typing-off](https://user-images.githubusercontent.com/547753/196522685-c306a3c8-cf31-4176-af44-8d9197ccc350.gif)

Based on your feedback we are reviewing whether or not to continue rolling this out. If you have more feedback or questions, please let me know.
