### ISSUE TITLE
Cannot access member "to" for type "None"   Member "to" is unknownPylance(reportGeneralTypeIssues)

### ISSUE THREAD

**Issue by Chaiyut1002** [microsoft/pylance-release#3494]
How do I fix this problem, it suddenly appeared today
<img width="1063" alt="Snipaste_2022-10-18_17-44-42" src="https://user-images.githubusercontent.com/90961172/196396609-f88562fb-378e-414c-8db3-72ceba2b6dde.png">

**Comment by williamzerner** [comment]
This is a bug. This issue is also being disccussed in Issue No. #3493

**Comment by Chaiyut1002** [comment]
> This is a bug of Pylance. This issue is also being disccussed in Issue No. #3493

Thanks! It was working fine previously. The code is running on ssh.

**Comment by judej** [comment]
@Chaiyut1002, thanks for the reports. The reason you are seeing this is because, we started to roll out a setting change: making the type checking basic by default. Previously, it was off. Type checking helps you find bugs that you might typically miss if you did not have type checking.

To turn it off, if you hover over the {} Python in the toolbar and click Switch to off as shown below.
Python-typing-off

If you have more feedback or questions, please let me know.

Thanks

**Comment by baddri** [comment]
welp, sorry to say this but the problem is still there. we just set the `"python.analysis.typeCheckingMode": "off"` to avoid the problem.
I got the same issue with Django HttpRequest [here](https://github.dev/django/django/blob/4470c2405c8dbb529501f9d78753e2aa4e9653a2/django/http/request.py#L107). the language server didn't seem to detect method `accepts`

![image](https://user-images.githubusercontent.com/49059318/213395511-f3fffa1a-7296-41d4-8eec-f71dcdb4ff21.png)


> @Chaiyut1002, thanks for the reports. The reason you are seeing this is because, we started to roll out a setting change: making the type checking basic by default. Previously, it was off. Type checking helps you find bugs that you might typically miss if you did not have type checking.
> 
> To turn it off, if you hover over the {} Python in the toolbar and click Switch to off as shown below. ![Python-typing-off](https://user-images.githubusercontent.com/547753/196522685-c306a3c8-cf31-4176-af44-8d9197ccc350.gif) [ ![Python-typing-off](https://user-images.githubusercontent.com/547753/196522685-c306a3c8-cf31-4176-af44-8d9197ccc350.gif) ](https://user-images.githubusercontent.com/547753/196522685-c306a3c8-cf31-4176-af44-8d9197ccc350.gif) [ ](https://user-images.githubusercontent.com/547753/196522685-c306a3c8-cf31-4176-af44-8d9197ccc350.gif)
> 
> If you have more feedback or questions, please let me know.
> 
> Thanks

**Comment by danconsidine** [comment]
No update on this issue? 
![image](https://user-images.githubusercontent.com/10943662/234292413-2fe4193b-f46f-49a4-83f7-584b01804cd9.png)

**Comment by rchiodo** [comment]
That error really depends upon the situation. It can happen for a number of reasons:

- It's a legit error. The method you're calling doesn't exist on the type being used. This might be user error, or it might be the type Pylance thinks the object isn't what you expect. 
- It's a type stub problem. The type Pylance is using for the class may be coming from a type stub. That type stub may not match the version of the package you're using.

Please log a new issue if you think the error is incorrect.

**Comment by danconsidine** [comment]
It seems whenever I use a conda environment everything works perfectly. 
![image](https://user-images.githubusercontent.com/10943662/234519955-fc5287a7-b921-4855-9ef4-6956d9b3b8a5.png)
To see if my installation was incorrect I spun up a fresh VM and it is still the same case. Using a standard python kernel doesn't work but as soon as I switch to a conda it begins working. It's possible (maybe probable) that I'm just installing things incorrectly.

**Comment by Arengard** [comment]
this is annoying

**Comment by Daniel-Considine** [comment]
> this is annoying

See here https://github.com/microsoft/pylance-release/issues/4577

**Comment by JotaRata** [comment]
This is annoying when importing packages without proper stubs/hints

In the meantime you can assert an object is from a certain type

Example using astropy
`header = hdu[0].header  # Cannot access header from HDUList`

with assertions you make sure an object is from a certain type:

```
hdu = hdu[0]
assert isinstance(hdu, PrimaryHDU)
header = hdu.header  # Everything works!
```
