### ISSUE TITLE
Wrong diagnostics in `reportUnnecessaryComparison`

### ISSUE THREAD

**Issue by oskgo** [microsoft/pylance-release#3517]
## Environment data

-   Language Server version: v2022.10.31
-   OS and version: Mac OS Monterey 12.5.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.11

## Code Snippet

```python
print(False == 0)
```

## Repro Steps

1. Hover the `0 == False` text in VSCode

## Expected behavior

Pylance tells me that it will always evaluate to `True`

## Actual behavior

Pylance tells me that it will always evaluate to `False` because the literals have no overlap, even though during runtime it evaluates to `True`.

**Comment by erictraut** [comment]
This is expected behavior for the `reportUnnecessaryComparison` check.

Most operations can be overridden in Python, there's no foolproof way to statically determine whether a comparison will always evaluate to `False` or `True`. This check makes assumptions about type overlaps that are generally true, but there will be edge cases like the one you've highlighted here where these assumptions fail. In this particular case, the `bool` class contains some non-standard logic in its `__eq__` method implementation that violates the assumption.

You can work around this issue by making a change to your code to avoid an error. Or you can disable the check if you'd prefer. You can also suppress this particular error using a `# type: ignore` or `# pyright: ignore[reportUnnecessaryComparison]` comment.

**Comment by oskgo** [comment]
Is it a non-goal to handle the edge cases of comparison on built-in types? Those cases cannot be overridden, and cannot change without changing the language in a way that breaks backwards compatibility. The language reference states that booleans generally behave as integers except when converted to strings.

**Comment by debonte** [comment]
> Is it a non-goal to handle the edge cases of comparison on built-in types? 

Yes
