### ISSUE TITLE
Enum values for python.analysis.logLevel are inconsistent

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#353]
The Python extension, Pylance and Pyright all define the "python.analysis.logLevel" setting in their package.json files, but they are inconsistent in the enumerated values that are supported.

The Python extension supports:
* Error
* Warning
* Information
* Trace

Pylance and Pyright support:
* Error
* Warning
* Info
* Trace

Note the difference between "Information" and "Info".

The code within Pyright supports only "Info" (or case-insensitive variants thereof).

For consistency with other settings in Pylance and Pyright, these would ideally be 'error', 'warning', 'info' and 'trace' (all lowercase), but we're probably stuck with the enum values defined by the Python extension.

**Comment by erictraut** [comment]
@judej & @jakebailey, what is the consensus on this? Should we move to [error, warning, information, trace] (lowercase)?

I just noticed yet another logging-related setting: "python.logging.level". It uses yet another inconsistent set of enumerated values: [off, error, warn, info, debug]. I'm going to ignore that one. Let's try to at least be consistent across the board for "python.analysis.logLevel".

**Comment by jakebailey** [comment]
Yeah, I wouldn't worry about `python.logging.level`, that's the logging setting for the Python extension itself.

The casing issue is #250, but the implication of changing it to "Info" instead of "Information" is the same, that this is still defined in the core extension and is read only in that format by MPLS. The uppercase is an artifact of it being a C# enum read directly. I'm iffy on changing it there until every other setting is dropped.

Earlier today, I had heard that this was going to be evened out by modifying pyright to accept "Information" rather than "Info" (hence the assignment), as it was the least friction. Is that not the case? Perhaps there was a misunderstanding. (Then when the time's right and we can move the `logLevel` setting to our setting definitions we can lowercase it to what we really want and be done.)

**Comment by erictraut** [comment]
OK, for now, I'll limit the change to go from "Info" to "Information".

**Comment by erictraut** [comment]
Done

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.5, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202095-16-september-2020
