### ISSUE TITLE
Incorrect Optional type inference in lambdas in loops

### ISSUE THREAD

**Issue by Nufflee** [microsoft/pylance-release#3533]
## Environment data

-   Language Server version: 2022.10.31 (pyright 24992a73)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.0rc1

## Code Snippet

```python
from typing import Optional

value: Optional[int] = None

while True:
    value = 1

    fun = lambda: value + 1
```

## Repro Steps

1. Create an `Optional` variable outside of a loop, assign it to a definite value in the loop and try to use the said variable inside of a lambda in the loop (like in my snippet)
2. Observe an error being reported regarding the variable potentially being `None` in the lambda, even though it's been reassigned to a definite value in all code paths

## Expected behavior

No error should be reported - the type of the variable should correctly be inferred to just the inner type (`T`) and not `Optional[T]`.

## Actual behavior

`Operator "+" not supported for "None" Pylance(reportOptionalOperand)` error on line 6.

![image](https://user-images.githubusercontent.com/19150550/197772202-51187f5a-7fb0-45ff-891c-5032504b62aa.png)

**Comment by erictraut** [comment]
This behavior is expected in this case. You will see the same error if you use other static type checkers like mypy.

The problem is that lambda is a separate execution context that captures the outer-scope variable `value`. The value of `value` could be overwritten by the time you actually invoke `fun`. Since `value` is declared as having the type `int | None`, it could be overwritten with a `None`. Outside of the lambda (at the scope of the while loop's body), the type of `value` is narrowed to `int`, but this narrowed type cannot be used within the lambda's execution context. (For more details about type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing).)

The recommended workaround in this case is to assign the value to another temporary variable whose type is `int` rather than `int | None`. This temporary variable can then be captured by the lambda.

```python
    value2 = value
    fun = lambda: value2 + 1
```

**Comment by Nufflee** [comment]
Ah! That makes sense. I was wondering if there was some lambda "quirk" causing this indeed, but then again, there's no code path in which `value` could possibly be `None`, although that may just be a limitation of static analysis.

Thanks for the quick response and as far as I'm concerned, this issue can be considered closed.
