### ISSUE TITLE
Pylance doesn't recursively evaluate types

### ISSUE THREAD

**Issue by mattangus** [microsoft/pylance-release#3535]
<h3> Environment data </h3>

-   Language Server version: 2022.10.30
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda):  3.8
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from typing import List, Optional


class Test:

    def __init__(self, var1: Optional[List[int]]):
        self.var1 = var1

    @property
    def is_set(self):
        return self.var1 is not None

    def is_set_fun(self):
        return self.var1 is not None

    def foo(self) -> Optional[int]:
        if self.is_set:
            if len(self.var1) > 0:
                return self.var1[0]
        if self.is_set_fun():
            if len(self.var1) > 0:
                return self.var1[0]
        if self.var1 is not None:
            if len(self.var1) > 0:
                return self.var1[0]
        return None
```

<h3> Repro Steps </h3>

1. Open the above code in vscode
2. turn on type checking basic
3. view problems

<h3> Expected behavior </h3>

The above `len` and indexing are guarded by the same `not None` checks so they should all have no errors.

<h3> Actual behavior </h3>

![image](https://user-images.githubusercontent.com/5302804/197803605-4c4c6e19-3f59-47db-bba7-ece8c5b6d52a.png)

<h3> Logs </h3>

```
[Info  - 15:30:27] (99825) Pylance language server 2022.10.30 (pyright 50e12b4b) starting
[Info  - 15:30:27] (99825) Server root directory: <homedir>/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist
[Info  - 15:30:27] (99825) Starting service instance "<project name>"
[Info  - 15:30:27] (99825) Notebook support: LSP
[Info  - 15:30:27] (99825) Interactive window support: LSP
[Info  - 15:30:27] (99825) No configuration file found.
[Info  - 15:30:27] (99825) No pyproject.toml file found.
[Info  - 15:30:27] (99825) Setting pythonPath for service "<project name>": "/bin/python3"
[Warn  - 15:30:27] (99825) stubPath <homedir>/<projectdir>/typings is not a valid directory.
[Info  - 15:30:27] (99825) Assuming Python version 3.8
[Info  - 15:30:27] (99825) Assuming Python platform Linux
[Info  - 15:30:27] (99825) Searching for source files
[Info  - 15:30:27] (99825) Found 64 source files
[Info  - 15:30:27] (99825) Background analysis(1) root directory: <homedir>/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist
[Info  - 15:30:27] (99825) Background analysis(1) started
[Info  - 15:30:27] (99825) Indexer background runner(2) root directory: <homedir>/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist (index)
[Info  - 15:30:27] (99825) Indexing(2) started
[Info  - 15:30:35] (99825) [IDX(2)] Long operation: index execution environment <homedir>/<projectdir> (7297ms)
[Info  - 15:30:35] (99825) [IDX(2)] Long operation: index libraries <homedir>/<projectdir> (8194ms)
[Info  - 15:30:35] (99825) Indexer done(2). indexed 766 files
```

**Comment by erictraut** [comment]
The current behavior is intended. This is the way static type analysis works. The type of an instance variable like `var1` is determined from its assignments. In your example, its type is `list[int] | None`. The type of the expression `self.var1` can be further narrowed (see [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing) for more details on type narrowing) within an execution context (e.g. within a method body), but type narrowing performed in one execution context does not affect the type in another execution context.

This is how all Python static type checkers work — and how they work in other languages as well. So you'll see the same error reported if, for example, you use mypy to type check your code.

There is a feature in some languages (like TypeScript) called a "type assert" that allows you to tell the type checker that the purpose of a function is to assert that the type of a specified value is some narrower type. That feature doesn't currently exist in the Python static type system, although it [has been proposed](https://mail.python.org/archives/list/typing-sig@python.org/thread/JTO3WKRKQFW5YFP3ZSMNTRIEA5NPJEM6/). In any case, that's not quite what your code is doing here. It's not raising an exception in the case when the value isn't set.

There are a couple of features in the Python static type system that you can use, but you'll need to change your code slightly.

Option 1: Within the conditional check, use `self.var1` directly rather than using a method call. This will narrow the type of that expression locally.

```python
        if self.var1 is not None:
            if len(self.var1) > 0:
                return self.var1[0]
```

Option 2: Use a TypeGuard as defined in [PEP 647](https://peps.python.org/pep-0647/)

```python
from typing import List, Optional, TypeGuard, TypeVar

T = TypeVar("T")

def is_set(val: T | None) -> TypeGuard[T]:
    return val is not None

class Test:
    def __init__(self, var1: Optional[List[int]]):
        self.var1 = var1

    def foo(self) -> Optional[int]:
        if is_set(self.var1):
            if len(self.var1) > 0:
                return self.var1[0]
        return None
```

**Comment by mattangus** [comment]
Thanks for your quick response! TypeGuard is exactly what I was looking for. Thank you!
