### ISSUE TITLE
Why object variable color syntax highlighting dissappear when declare type?

### ISSUE THREAD

**Issue by rhynzler** [microsoft/pylance-release#3563]
**Enviroment:**

Python version: 3.10
OS: Manjaro Linux
Pylance v2022.11.10

Here's an example:

if in an if statement I verify that an object variable is None and this variable has a declared data type, the variable color syntax highlighting disappears within the if statement

![image](https://user-images.githubusercontent.com/70046048/199347646-9dc73c39-b347-4a2f-b64f-3783e8da9d33.png)

**Comment by rhynzler** [comment]
Python version: 3.10
Platform: Manjaro Linux
Pylance v2022.11.10

**Comment by debonte** [comment]
Is there any chance that you have the [Python for VSCode](https://marketplace.visualstudio.com/items?itemName=tht13.python) extension installed? We had a somewhat [similar issue](https://github.com/microsoft/pylance-release/issues/3443) recently that was caused by having that extension installed. It appears to not be in active development / support anymore (last release was in 2016), so if you have it, I'd recommend uninstalling it.

Microsoft's extension is just called [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python).

**Comment by rhynzler** [comment]
I don't have installed that extension, I only have [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension installed.

![image](https://user-images.githubusercontent.com/70046048/199569668-6bfc478e-ecc4-4cd0-b8ed-ed84b4c89338.png)

**Comment by heejaechang** [comment]
I think Pylance's behavior is as expected. basically, what we are saying is.

![image](https://user-images.githubusercontent.com/1333179/199570525-8e46c63f-794e-4c15-9f99-9ccf82646412.png)

this `if statement` can't never be reached. you can confirm it by hovering over `a` inside of the `if statement`, it will say `a`'s type is `never` since `a` can't never reach there.

and any member off the `never` doesn't exist. so that's why it has no coloring.

the reason it says `a` is never is because we see `variable_1` is explicitly typed as `int` and the `if statement` is checking it with a type that `variable_1` can never be. and we see `variable_1:int = None` as an error. it is same for `variable_3`

`variable_2` and `variable_4` works since it is not typed and in that case, it can be any type so `if statement` can be reached.

if you change `is None` for `varialbe_1` and `variable_2` to correct type such as `int` or `str`, you will see coloring works as expected.

**Comment by erictraut** [comment]
If `variable_1` is meant to accept a value of `int` or `None`, you can declare its type as `int | None`. Then a conditional check of `a.variable_1 is None` will narrow its type to just `None`. For more details about type declarations and type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

**Comment by rhynzler** [comment]
> Your comments are right, but `a` will not be `never` in Python, only if some strict mode is configured, then your assertions would be valid, but it only happens with type None.
If I put any other object after `is` in the `if` statement that is different type of None, then it will accept me as valid, and it would contradict @heejaechang 's statement.

I accept @erictraut solution to mark the vars as Optional

**Comment by heejaechang** [comment]
@erictraut do we have special logic for "None" check? it looks like other type checking is fine but only None check, we narrow it to `Never`?

@rhynzler > a will not be never in Python
by `Python`, are you referring actual `python` interpreter at runtime? `never` only exists in static analysis context, not in runtime.

**Comment by rhynzler** [comment]
@heejaechang sorry my bad, i try to say that the code inside the if statement could be executed in runtime.

> the reason it says `a` is never is because we see `variable_1` is explicitly typed as `int` and the `if statement` is checking it with a type that `variable_1` can never be. and we see `variable_1:int = None` as an error. it is same for `variable_3`

![image](https://user-images.githubusercontent.com/70046048/199592348-8f1f7b95-dd7a-4934-8224-9d03a6e51d88.png)

If I change `None` to any other type diffentent that the one declared it will accept me as valid

**Comment by heejaechang** [comment]
ya, runtime doesn't care type you declared, it only cares actual value/type assigned to it at runtime. type annotation is more like you writing down you intention and static analysis tool show you places where you violated your intension. Python is dynamic language; it won't behave like static language just because you have type annotation.

For the other case, it is because pylance only special casing "None" case (https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/typeGuards.ts#L373)

you can see here all cases where pyright (the analysis engine pylance is built upon) does type narrowing - https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards

**Comment by rhynzler** [comment]
Typing helped me a lot to not get lost in the code, I even use stubs for some libs, thanks for your answer. i will append `| None` when declaring type in variables that present these scenarios.
