### ISSUE TITLE
Type narrowing on coupled return values

### ISSUE THREAD

**Issue by kossyrev-bg** [microsoft/pylance-release#3572]
<h3> Environment data </h3>

-   Language Server version: 2022.11.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
def fn(
    x: int,
) -> Union[Tuple[Literal[True], Literal[7]], Tuple[Literal[False], Literal[6]]]:
    if x == 0:
        return True, 7
    return False, 6


ret_bool, ret_int = fn(0)

if ret_bool:
    z = ret_int
```

<h3> Expected behavior </h3>

When I hover over z, it should say `(variable) z: Literal[7]`

<h3> Actual behavior </h3>

`(variable) z: Literal[7,6]`

<h3> Additional Info </h3>

The crux of this is I have a function that, depending on its inputs, returns either `(True, SomeInstance)` or `(False, None)` if it fails. I'd like to be able to then do
```
success, inst = some_fn(some_input)
if success:
  inst.run_some_method()
```
but the linter says `some_method is not a known variable of None` because it doesn't realize that `inst` must be of type `SomeInstance` after the `if success` call. I'm also open to defining `fn` to return some other type if this has been solved. I just couldn't find anything from googling.

**Comment by erictraut** [comment]
Pylance is working as designed. Type narrowing is applied within functions, not across functions. For an explanation of how type narrowing works in pyright (the type checker that underlies pylance), refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing).

If I understand your problem correctly, it sounds like you should be using `@typing.overload` to define two overload signatures for your polymorphic function.

```python
@overload
def fn(x: Literal[0]) -> tuple[Literal[True], Literal[7]]: ...
@overload
def fn(x: int) -> tuple[Literal[False], Literal[6]]: ...
def fn(
    x: int,
) -> Union[Tuple[Literal[True], Literal[7]], Tuple[Literal[False], Literal[6]]]:
    if x == 0:
        return True, 7
    return False, 6
```

**Comment by kossyrev-bg** [comment]
I suppose the basic example was too simple. In my case, while `x` is the input, the function depends on other things to occur inside of it, e.g.
```
def fn(x):
  is_true = lookup_some_value_in_db()  # could return true or false
  if is_true:
    return True, 7
  return False, 6
```

**Comment by erictraut** [comment]
Ah, I see what you mean now.

The problem in your original code is that you are unpacking the returned value into two separate variables `ret_bool` and `ret_int`. These are two independent variables with independent types. They are no longer "coupled" once you unpack them. If you avoid unpacking the the return result, the "coupling" is retained in the form of a union of tuples, and type narrowing can be applied.

```python
ret = fn(0)

if ret[0] == True:
    z = ret[1]
```

Note here that I'm using `ret[0] == True` in the conditional expression rather than `ret[0]`. Pyright's type narrowing logic for a simple truthy check does not support index expressions like `ret[0]`. We could add support for this, but it would have a potential performance impact on code analysis. The type narrowing logic for the expression pattern `x == <literal>` does support index expressions. That's why `ret[0] == True` works for narrowing in this case.

**Comment by kossyrev-bg** [comment]
Got it, thank you! I'll keep it coupled then.
