### ISSUE TITLE
pandas not detected as module?

### ISSUE THREAD

**Issue by nflnsr** [microsoft/pylance-release#3581]
Pandas not detected as modul?
I have installed pandas module using `pip install pandas` in my env and the code has worked properly, but i still got notif error and problem in my vscode. 
Any solution?

![Screenshot 2022-11-05 081835](https://user-images.githubusercontent.com/94155537/200094934-405069ac-1e37-4f0b-8657-0b48c4f3f220.jpg)

**Comment by chinmaykh** [comment]
This is a badly formatted issue. Please follow the template so that the issue can be resolved. There could be a host of problems causing the issue, it is impossible to narrow it down without knowing more. 

From just this information, I can recommend the following
1. Try `Python: Restart Language Server` in the command palette
2. See if the python version selected is really the you're running it with

**Comment by nflnsr** [comment]
the problem was gone when i installed the pandas module out of my environment.
but i still wondering why it's not detected on my env 🤔
