### ISSUE TITLE
Support choose local pyright version like typescript?

### ISSUE THREAD

**Issue by zhuangzhuang** [microsoft/pylance-release#36]
because pylance release is after pyright, i can't wait new feature and bug fix 🚀.

![image](https://user-images.githubusercontent.com/521058/86432535-a869bf00-bd2a-11ea-83d4-8c4b1801db2a.png)

**Comment by erictraut** [comment]
@zhuangzhuang, can you provide more details about why you want to use Pylance with a local fork of Pyright? What is the use case you have in mind? This can help us explore potential solutions that meet your needs.

Typescript is a different situation because it's a stand-alone compiler, so it's important to be able to select the language service provider independently of the compiler. Pylance and pyright serve the same purpose — they're both language service providers. Pylance offers a few additional features, but it is otherwise the same as Pyright.

**Comment by zhuangzhuang** [comment]
I thought pylance has use pyright as library. but seems not.

for this moment, pylance was release at 2020/7/1,but pyright release yesterday.

**Comment by erictraut** [comment]
Pylance is built with Pyright, but it's linked together into a single web-packed bundle. Pylance overrides some of the classes in Pyright to provide additional functionality (e.g. Intellicode compatibility).

Pyright is published on an ad-hoc basis (no well-defined cadence or release guarantees), whereas Pylance goes through a more formal build and release process on a regular cadence. When Pylance is published, it picks up all the latest changes from Pyright.

**Comment by zhuangzhuang** [comment]
Thanks

**Comment by zhuangzhuang** [comment]
Thanks
