### ISSUE TITLE
Allow inline disable of "Unreachable code"

### ISSUE THREAD

**Issue by pavel-rezabek** [microsoft/pylance-release#3614]
During writing tests, VSCode reports code as unreachable when it should be reachable. I understand that pylance cannot understand all code, so the best way to resolve this problem would be to add an option to suppress this warning.

There is an option to disable it alltogether (`"editor.showUnused": false`), but showing unused code may be desired in other places. Using a comment similar to other tools like `# noqa` or even pylance's `# pyright: disable=<report>` would be very convenient.

The code in question can be condensed to this:
```python
from unittest import mock
import pytest
a = mock.Mock(side_effect=Exception)
with pytest.raises(Exception):
    while True:
        a()

print("I am marked as unreachable")
```

**Comment by erictraut** [comment]
Which version of pytest are you using? Earlier versions had a bug where the `raises` function wasn't properly annotated, and that led to behavior you're seeing. I think that if you upgrade to the latest version of pytest (7.2.0), the problem will go away. I'm not able to repro it.

**Comment by pavel-rezabek** [comment]
I am on pytest version `5.0.0`. Upgrading pytest seems to fix this issue.

Thank you for your help!

**Comment by david-morris** [comment]
Sorry for the necrobump, but I don't see how to actually do this?
Demanding that a fallback value is unreachable a great tool for type-checking e.g. factory methods.

**Comment by debonte** [comment]
> Sorry for the necrobump, but I don't see how to actually do this? is there a specific Mypy rule that can be disabled?

We don't support line-specific disabling of unreachable code hints. Although the user originally requested that here, the solution we provided was to upgrade pytest to pick up new type annotations so their code wouldn't be flagged as unreachable in their specific pytest scenario.

If you're using Pylance and seeing a different issue with unreachability, please file a new issue.

If you're actually using mypy rather than Pylance you'd need to ask about this over at https://github.com/python/mypy.
