### ISSUE TITLE
Support for correctly marking functions with decorators that store the function as accessed

### ISSUE THREAD

**Issue by FeldrinH** [microsoft/pylance-release#3622]
It would be nice if pylance could somehow be instructed to consider a function as accessed if it has a decorator that stores the function for later use (these kinds of decorators are common for many web frameworks, routers and chatbot libraries).

For example with a program like this:
```python
from fastapi import FastAPI

def create_app():  
    app = FastAPI()

    @app.get('/hello')
    async def get_hello():
        return "Hello world!"
    
    return app
```

Pylance currently reports that get_hello is not accessed:
![image](https://user-images.githubusercontent.com/5256211/201539852-c161800f-c6f3-4a87-969c-b61eda386b2e.png)

This is incorrect, because the `@app.get` decorator actually stores the function and later calls it as a handler for the endpoint '/hello'.

**Comment by erictraut** [comment]
A static type checker has no way of knowing whether a decorator is storing a reference to the decorated function. 

From a static analysis perspective, it is correct to say that the symbol `get_hello` is not accessed. This isn't considered a program error, which is why no diagnostic is generated in this case. The grayed-out text is just a subtle hint to the developer that the symbol is not accessed, which can sometimes indicate the presence of a bug. If you know this to be OK, then you can ignore the fact that the name of the function is grayed out.

**Comment by Tinche** [comment]
I'm hoping you'd reconsider this call on the basis this this is a very common pattern (flask also uses it) and that these false positives make the entire feature (call attention to unused things) a little more difficult to use.

The feature itself is excellent, but the fact that mentally now I need to think about the context (and keep thinking about it every time I read the code) is unfortunate,

**Comment by erictraut** [comment]
The code above is the equivalent to this:

```python
def create_app():
    app = FastAPI()

    async def _get_hello():
        return "Hello world!"

    get_hello = app.get("/hello")(_get_hello)

    return app
```

As you can see, the `get_hello` symbol is not referenced even if the original function that is passed to the decorator is stored.

If the grayed-out text is something that really bothers you, here are a couple of options:

1. Don't use a decorator. Instead, call the function directly to register the callback.
```python
def create_app():
    app = FastAPI()

    async def _get_hello():
        return "Hello world!"
    
    app.get("/hello")(_get_hello)

    return app
```

2. Name the function `_`. This name is used in Python to indicate "this symbol isn't used", so it is exempt from the "unused symbol" detection logic on pylance.

```python
def create_app():
    app = FastAPI()

    @app.get("/hello")
    async def _():
        return "Hello world!"

    return app
```

**Comment by Tinche** [comment]
You're not wrong, I'm saying there's a little more nuance to this.

Your first suggestion is doable, but we'd be ignoring a powerful Python feature (decorators) because of a tool, and while the non-decorator use is equivalent, I'd argue it's unidiomatic for these frameworks (to some extent) and a little less readable.

The second suggestion I'm not sure about, usually the name of the handler ends up being meaningful, for example as a target for redirects, observability tagging, stuff like that.

Let me ask you, can pyright/pylance figure out the same function gets returned from a decorator? In other words, can it figure out that the code is actually:

```python
def create_app():
    app = FastAPI()

    async def _get_hello():
        return "Hello world!"

    app.get("/hello")(_get_hello)  # instead of get_hello = app.get("/hello")(_get_hello)

    return app
```
Because if so, maybe there could be a carve-out for this scenario? I guess then it'd be up to each particular framework to make this detectable, but it'd be a start.

**Comment by erictraut** [comment]
There's nothing in the type system that would allow a type checker to determine that a function (a decorator) returns the same function that it was passed. The closest it can do is determine that the _signature_ of a returned function is the same. But that doesn't really matter. Carving out a special case like this isn't something that I'd endorse. It would create an inconsistency that would be difficult to justify, and it would lead to situations where an unreferenced symbol that should be displayed as unreferenced will no longer be displayed as such (a false negative). Pyright is correct in marking this value as unreferenced because _it is unreferenced in your code_. I've suggested two ways that you can modify your code such that it is no longer unreferenced. A third option is to simply live with the fact that it's unreferenced and displayed as such.

**Comment by benglewis** [comment]
Having some ability to `whitelist` the decorators (via configuration) which cause the functions that they wrap to be defined, that would be really nice. This grayed-out approach can be confusing and thus makes Pylance much less useful in real world codebases, e.g. when using FastAPI
