### ISSUE TITLE
Type check not recognizing dict constructor (this is not #338)

### ISSUE THREAD

**Issue by Leedehai** [microsoft/pylance-release#364]
## Environment data

-   Language Server version: v2020.9.4
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2

## Expected behaviour

Code

```python
arr = ["a=2", "b=3"]
d = dict([tuple(e.split('=')) for e in arr])
```
Yields dictionary `d`: `{'a': '2', 'b': '3'}`, according to https://docs.python.org/3/library/stdtypes.html#dict

## Actual behaviour

```python
arr = ["a=2", "b=3"]
d = dict([tuple(e.split('=')) for e in arr]) # Pylance mark this line as error
```

Error message:
```
No overloads for "dict([tuple(e.split('=')) for e in arr])" match parameters
  Argument types: (List[tuple[str]])Pylance (reportGeneralTypeIssues)
```

## Logs

The log doesn't show anything interesting...

**Comment by erictraut** [comment]
Although your code sample runs without generating an exception, the error that Pylance is generating is correct. Any standards-compliant type checker would report an error in this location. I confirmed that mypy (another popular type checker) does the same.

The problem is that the constructor for `dict` (as defined in the `builtins.pyi` type stub) requires an input parameter that is an iterable sequence of two-element tuples, but the `split` method returns an arbitrary-length tuple. A static type checker would have no way of knowing whether the strings you are passing to `split` happen to generate two-element tuples in all cases.

There are various ways you could change your code to work properly with a static type checker (and be more robust in the process). Here's one such way:

```
arr = ["a=2", "b=3"]
splits = [e.split("=") for e in arr]
d = dict([(split[0], split[1]) for split in splits if len(split) == 2])
```

**Comment by Leedehai** [comment]
Understood. Is it possible to list the acceptable overloads for `dict()` for the user to compare the actual param type against? It would help a lot to tell users `I expect overloads X and Y, but the argument type I see is Z`. But thanks anyway!

**Comment by erictraut** [comment]
The error message does list the argument types for this reason. The list of overloads isn't included in the error message because it's not uncommon for there to be a dozen or more overloads, and it would get really busy to include them in the message. You can always "go to definition" (press F12) to see the overloads where they are defined.
