### ISSUE TITLE
Pylance says Code is unreachable even though it executes in python [BUG]

### ISSUE THREAD

**Issue by nsabir2011** [microsoft/pylance-release#3643]
## Environment data

-   Language Server version: v2022.11.20
-   OS and version: Ubuntu 22.04.1 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.15

## Code Snippet

```python
class CodeUnreachable:
    def __init__(self):
         num_figs = 6
         nrow, ncol = self._get_nrow_ncol(num_figs, 3)
         # pylance grays out code and says code unreachable

    @staticmethod
    def _get_nrow_ncol(
        num_plots: int,
        row_limit: int = None,
        col_limit: int = None,
    ):
        if row_limit is not None and col_limit is not None:
            raise ValueError(
                "Both `row_limit` and `col_limit` cannot be set"
            )

        if col_limit is not None:
            raise NotImplementedError(
                "`col_limit` arg functionality has not been implemented yet"
            )

        if num_plots <= row_limit:
            return (num_plots, 1)
        else:
            return (row_limit, np.ceil(num_plots / row_limit).astype(int).item())


```
## Expected behavior
Not graying out the code block

## Actual behavior
The function causing this issue :arrow_down_small: 
![Screenshot from 2022-11-17 09-16-34](https://user-images.githubusercontent.com/42509077/202348446-29b692e7-54b6-4718-9e5e-ebfa0f38926b.png)
The code block where the function is called :arrow_down_small: 
![Screenshot from 2022-11-17 09-17-41](https://user-images.githubusercontent.com/42509077/202348512-83b4cb81-e795-44a6-b0f9-bf18a3f95729.png)

## Logs

```
XXX
```

**Comment by erictraut** [comment]
The problem is that you've declared parameter `row_limit` and `col_limit` to be type `int`, which means they can never legally be `None`. That means that the statement `if row_limit is not None and col_limit is not None` will always evaluate to `True`, and the function will always raise a `ValueError` exception.

You can fix this one of several ways:
1. Fix the type declarations for `row_limit` and `col_limit` to be `int | None` (or `Optional[int]`).
2. Provide a return type annotation for method `_get_nrow_ncol` so the type checker doesn't need to infer its type.
3. Create a pyrightconfig.json config file that sets `strictParameterNoneValue` to 'false'. This tells pyright (the type checker that underlies pylance) to treat parameters that have a default argument value of `None` as though they are implicitly `Optional`. This implicit behavior was originally allowed in PEP 484, but the PEP was updated later to indicate that type checkers should not default to this behavior and should require explicit `Optional`.

**Comment by nsabir2011** [comment]
@erictraut 
Thank you for the information. I managed to fix it the following way:
```python
    def _get_nrow_ncol(
        num_plots: int,
        row_limit: Optional[int] = None,
        col_limit: Optional[int] = None,
    ) -> Tuple[int]:
```
