### ISSUE TITLE
packageIndexDepths doesn't seem to work for files inside your workspace

### ISSUE THREAD

**Issue by youssefm** [microsoft/pylance-release#3648]
This was originally reported here: https://github.com/microsoft/pylance-release/issues/2533#issuecomment-1217233216

@debonte suggested someone open an issue, so this is it

I'm running VSCode 1.73.1, Pylance v2022.11.30 with the following configuration:

```
  "python.analysis.autoImportCompletions": true,
  "python.analysis.diagnosticMode": "workspace",
  "python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "depth": 100,
      "includeAllSymbols": true,
      "name": ""
    },
  ],
```

and Pylance doesn't suggest all the symbols in my workspace beyond the first level for auto import.

**Comment by tnielens** [comment]
Seems to fail for packages installed in a venv in the project directory as well.

**Comment by bschnurr** [comment]
@youssefm Currently it is only designed to work for thirdparty libraries installed in your environment, in order to limit the amount of data returned.

**Comment by bschnurr** [comment]
> Seems to fail for packages installed in a venv in the project directory as well.

@tnielens can you create a new issue?

**Comment by heejaechang** [comment]
Let me clarify a few things.

`python.analysis.packageIndexDepths` is for `third party libraries` installed in folders like `site-packages`  (regardless whether it is under `workspace root` or not)

All symbols from user files under `workspace root` will be always indexed (if `indexing` is on) up to `2000` files.

All of symbols indexed will be suggested with `add symbols` through `light bulb` 
ex) 
![image](https://user-images.githubusercontent.com/1333179/203147884-89cb02d8-344d-495f-b04c-f3eaf2d65d03.png)

But only third-party symbols will be shown in `auto import` (assuming you enabled `python.analysis.autoImportCompletions`)
ex) 
![image](https://user-images.githubusercontent.com/1333179/203148193-18f18472-a5df-472d-b292-cb50eee222c0.png)

`Symbols from user files` won't be shown in `auto import` (we do show some when we know it has been already used in other open files but in principle we don't show them in `auto import`)

We decide not to show symbols from user files in `auto import` since it brings in too many symbols in completion even if no body explicitly asked them. unlike `auto import`, `add import` only show things when user explicitly `ask` them. so for now, it will be only in `add import`.

**Comment by youssefm** [comment]
Thanks for the explanation @heejaechang.

You say that:

> We decide not to show symbols from user files in auto import since it brings in too many symbols in completion even if no body explicitly asked them. unlike auto import, add import only show things when user explicitly ask them. so for now, it will be only in add import.

But I actually do want to be able to auto import all the symbols in my project. This is already how typescript auto import works in VSCode. This feels like a super basic, core scenario for Pylance. We should be able to start typing and get suggestions from our project that are not in open files.

Is there really no option that will let me auto import all the symbols in my project?

**Comment by heejaechang** [comment]
@youssefm you still can get those using `add import`. just not in `auto import`. and unlike many advanced users thinking `auto import` is an essential feature everyone needs, in reality, a lot of users doesn't know what it is and confused about it and that is why we turned it off by default and requires users to turn it on explicitly indicating they know what it is. 

That being said, we are now discussing, since `auto import` is off by default and require users to opted-in, it might be okay to include all user symbols in `auto import`. since we think the act of `opt-in` shows their intent that they are okay us showing a few tens thousands more symbols in completion for convenience every time.

previously, since it was on by default, a lot of users were confused by those extra tens thousands of symbols showing up.

now, about comparing with TS. all languages are different. for TS, they have accessibility keyword such as export, public or project.json's dependency metadata to indicate what are direct dependencies or what symbol is supposed to be accessible from other modules and etc. python doesn't have those. so, basically every module level symbol you have can be accessed from other modules making number of `auto import` symbols to show in completion way bigger than TS.

we had to cut that number somehow, and user symbols are what we have cut, especially since `auto import` was on by default.

but now, since it is off by default, we might be able to just include all those if user explicitly turn it on. but we still do some experiment to see whether most of users are okay with that.

**Comment by youssefm** [comment]
@heejaechang thanks for the context here. It's super helpful. I used to work at Microsoft in devdiv and I can understand how it's hard to make everyone happy.

I definitely appreciate that Python doesn't have the explicit exports that TS has, but are there any heuristics you could trim down the number of symbols you suggest?

For example, let's say I have a file person.py:

```
from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
```

I'm likely to want to import `from person import Person` and I probably don't want to import `from person import models`. So you could focus on the symbols that are actually defined in your project files rather than those that are imported and happen to be available.

On the point about auto import now being off by default, I agree that makes it possible to auto import user symbols. But even if you don't want to do that, at the very least there should be an additional opt-in setting called maybe "Auto-import all workspace symbols" that lets us tell Pylance that we do actually want all these symbols to show up in auto import.

I think this is a hugely important feature that would make Pylance so much more useful to a lot of developers.

What can I do about this at this point? Is there a feature request I can comment on, or should I create a new feature request?

Thank you again for explaining everything @heejaechang

**Comment by heejaechang** [comment]
@youssefm you can open a new feature request asking for an option for it. that being said, usually, people want to avoid adding more options if possible. so not sure how it will go.

**Comment by youssefm** [comment]
thanks @heejaechang - I've created this feature request: https://github.com/microsoft/pylance-release/issues/3670

**Comment by IgorArnaut** [comment]
Auto import does not work for Django REST Frameworks modules. Maybe this is related to this issue.
