### ISSUE TITLE
Package pyautogui miss the function screenshot() in the intellisense

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3658]
![image](https://user-images.githubusercontent.com/100815370/202596251-9f39e768-6b02-4611-b159-33d7c5d64f0b.png)

We can see that intellisense didn't give the screenshot() method in the lise while we can run it correctly.

Thank you for any help.

**Comment by ydmykr** [comment]
Is there any update？

**Comment by rchiodo** [comment]
I believe this is by design. Screenshot is not a member of pyautogui, but rather something it imports from pyscreeze. Pyright (the typechecker pylance uses) does not consider screenshot a part of pyautogui because it's just a side effect of importing.

For more information see this issue (similar situation):
https://github.com/microsoft/pylance-release/issues/3320
