### ISSUE TITLE
Duplicated Suggestion in Python

### ISSUE THREAD

**Issue by NelloHo** [microsoft/pylance-release#3693]
Does this issue occur when all extensions are disabled?:  No , offiocial Python package needed

- VS Code Version: 1.73.1 (system stetup)
- OS Version:  Win 10

Steps to Reproduce:

1.  start a clean VS code without any settings and packages
2.  install Microsoft's official Python package
3.  it will show duplicated suggestions in Jupyter Notebook
![image](https://user-images.githubusercontent.com/99171663/203790562-b9b1ef8c-20d4-4324-8457-683ccc2af4a4.png)

**Comment by bsaunders23** [comment]
I think this has been addressed in the prerelease #3617

**Comment by debonte** [comment]
You have two options for this:
1. Use a recent prerelease build of the Jupyter extension. I believe this requires VS Code Insiders btw because they are using some new APIs that aren't supported in VS Code stable yet.
2. Set `"python.pylanceLspNotebooksEnabled": true`. Note that this option has been removed from the Python extension, so it may be grayed out when you enter it into `settings.json`. That's fine. Older builds of Jupyter will still honor this.
