### ISSUE TITLE
Auto-add parenthesis to callable completions

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/pylance-release#37]
```json
"python.autoComplete.addBrackets": true
```

**Comment by Matin-Moezi** [comment]
I have the same problem.

**Comment by jakebailey** [comment]
For what it's worth, the expected behavior at the moment is for this to not work; anything under `python.autoComplete` has either moved to `python.analysis` (e.g., `python.analysis.extraPaths`), or hasn't been implemented. The list of currently supported options are in this repo's README.

**Comment by eaglet123** [comment]
This happens when "python.languageServer" is set to anything other than Jedi. 

People also encountered this problem here: https://github.com/microsoft/vscode-python/issues/12786

**Comment by jakebailey** [comment]
To give an update, this has been spec'd out (under a more descriptive name than "brackets"), but isn't yet implemented.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202082-20-august-2020

You can enable this by setting:

```json
{
    "python.analysis.completeFunctionParens": true
}
```

If you were already using `python.autoComplete.addBrackets`, your setting should be automatically ported. (We took this opportunity to name this more descriptively than the old `addBrackets` setting.)

**Comment by bwerere** [comment]
For my case, using VS code for Flutter/Dart, I resolved this error by disabling the Preview LSP (Language Server preview) which I had earlier enabled to remedy another VS Code error - Data analyser stopped working.

**Comment by nonoash** [comment]
referring to this issue, has it been fixed ? because it's not working for me with Pylance, thanks. https://github.com/microsoft/pylance-release/issues/180#issuecomment-1396780954

**Comment by rchiodo** [comment]
See https://github.com/microsoft/pylance-release/issues/3831. Should be fixed in the prerelease bits.
