### ISSUE TITLE
Support for folding-range requests

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#372]
This is a feature request from @leungbk in the pyright repo. Moving here so it gets the proper visibility.

https://github.com/microsoft/pyright/issues/1037

**Comment by petterssonandreas** [comment]
Has there been any updates regarding this issue since it was created? It would be really nice if the folding was based on syntax rather than just based on indent.

For me this is mainly an issue when there are multi-line strings, that are not indented like the surrounding code (because I don't want them to be). See gif below for example.

![fold](https://user-images.githubusercontent.com/26619300/120652739-583a3600-c480-11eb-9f9a-d8a8b3a2ca12.gif)

**Comment by jakebailey** [comment]
We typically try and work on issues based on votes by reactions; if you are interested in this, do vote it up. (We don't have infinite implementation time. 🙂)

**Comment by petterssonandreas** [comment]
@jakebailey Thanks for the quick reply! Sure, I understand that you focus on what's important/wanted. And I guess this issue has gotten very few interactions. It seems like there are a lot of issues posted on microsoft/vscode and microsoft/vscode-python about this or very similar things. But maybe those should be moved here to pylance now when it's officially released?

Some of the currently open issues:
microsoft/vscode-python#1847
microsoft/vscode-python#15218

**Comment by debonte** [comment]
Folding support was added in 2022.1.1
