### ISSUE TITLE
feature request: braces should auto-pair inside f-strings 

### ISSUE THREAD

**Issue by tuchandra** [microsoft/pylance-release#3743]
I searched for [f-string](https://github.com/microsoft/pylance-release/issues?q=f-string+) and didn't see an issue like this.  I also searched "brace", "paren", and "pair" in settings and found nothing. Please let me know if this already exists and I was just looking in the wrong places.

**Feature request:** if I'm typing inside an f-string and type an open brace `{`, I would like VS Code to automatically insert the closing brace.

https://user-images.githubusercontent.com/11623486/206767199-07f94edd-3336-46cf-84e2-7609f9362cb0.mov

This is a feature I miss from the TypeScript equivalent in template literals:

https://user-images.githubusercontent.com/11623486/206767503-1e9dc190-b31c-45de-b4fc-f111405613e0.mov

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.4.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023441-26-April-2023-PreRelease)

It has some prerequisites that need to be set in order for it to work though:
- Python and Jupyter extensions have to be Prerelease
- "python.analysis.pylanceLspClientEnabled": true
- "python.analysis.autoFormatStrings" : true
