### ISSUE TITLE
Detecting unreachable code via NoReturn does not work for most dunder methods

### ISSUE THREAD

**Issue by stereobutter** [microsoft/pylance-release#3749]
<h3> Description </h3>

Detecting unreachable code via annotations with `NoReturn` does not work for most *dunder* methods. It works for `__init__`, and `__call__` and gives another error for `__iter__` but does not work for:
* context manager methods (both sync and async)
* `__getattr__`, `__setattr__` and properties
* `__getitem__` and `__setitem__`
* `__str__`, `__len__`, `__bytes__` and friends 

<h3> Environment data </h3>

-   Language Server version: 2022.11.30
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.1

<h3> Code Snippet </h3>

```python
from typing import NoReturn


class FailEnter:

    def __enter__(self) -> NoReturn:
        ...

    def __exit__(self) -> None:
        ...

class FailExit:

    def __enter__(self):
        ...

    def __exit__(self, et, ev, tb) -> NoReturn:
        ...

class FailGetItem:

    def __getitem__(self, item) -> NoReturn:
        ...

class FailSetItem:

    def __setitem__(self, attr, item) -> NoReturn:
        ...

class FailStr:

    def __str__(self) -> NoReturn:
        ...


def exampleA():
    with FailEnter():
        print('here')  # should be marked unreachable
    print('there')  # should be marked unreachable

def exampleB():
    with FailExit():
        print('here')
    print('there')  # should be marked unreachable

def exampleC():
    FailGetItem()['hello']
    print('world')  # should be marked unreachable

def exampleD():
    FailSetItem()['hello'] = "world"
    print('here')  # should be marked unreachable

def exampleE():
    str(FailStr())
    print('here')  # should be marked unreachable
```

**Comment by erictraut** [comment]
This is by design. The code flow analysis employed by pyright (the static type checker that underlies pylance) does not take into account implicit calls to magic methods when determining reachability. Adding such logic would be theoretically possible, but it would be a significant performance hit — likely doubling the time it takes to analyze many functions. Since it's extremely rare for dundered methods to return `NoReturn`, this wouldn't be a good tradeoff, and we're therefore unlikely to implement such a feature.
