### ISSUE TITLE
Pylance is ignoring a validation using the all() method for a Optional field

### ISSUE THREAD

**Issue by rodrigoestevao** [microsoft/pylance-release#3774]
Type: <b>Bug</b>

I have a data class defined as following: 

````python
@dataclass
class VersionSave:
    version: Optional[str] = None
    entity_id: Optional[int] = None
````

the called method with following signature:

````python
def get_by_version_and_entity_id(
    self,
    version: str,
    entity_id: int,
    enforce_exist: bool = True,
    include_ended: bool = False,
) -> Optional[VersionPublic]:
    ....
````

when I do the following check:

````python
if all([parsed_data.version, parsed_data.entity_id]):
    obj = self.get_by_version_and_entity_id(
        version=data.version,
        entity_id=data.entity_id,
        enforce_exist=False,
    )
    ...
````

Pylance keeps marking the `version` and `entity_id` with the following error:

````
(variable) parsed_data: VersionSave
Argument of type "int | None" cannot be assigned to parameter "entity_id" of type "int" in function "get_by_version_and_entity_id"
  Type "int | None" cannot be assigned to type "int"
    Type "None" cannot be assigned to type "int" Pylance([reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues))
````

Extension version: 2022.12.20
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.80GB (104.52GB free)|
|Process Argv|--crash-reporter-id 07ff79ca-04b0-4b84-992b-72dc411036b3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 2999)|
|Memory (System)|100.44GB (97.16GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by erictraut** [comment]
It's difficult to diagnose the problem you're seeing because you haven't provided a self-contained minimal code sample. Your code snippets above refer to symbols whose definitions are not provided, so I need to guess at what they might mean.

If my guess is correct, the problem is that the technique you're using to check for `None` values in a `VersionSave` object is not supported for type narrowing purposes. Pyright (the type checker upon which pylance is built) supports a variety of so-called "type guards" that narrow types when they are used in `if` statements. The `all` pattern that you're using here is not one of them. For a full list of supported type guard patterns, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

If you're interested in making your code work with Python static type checkers (including pyright/pylance, mypy, or others), you will need to use a different technique here.

```python
def func(data: VersionSave):
    if data.version is not None and data.entity_id is not None:
        ...
```

**Comment by judej** [comment]
@rodrigoestevao, if you have additional questions, please reopen the issue and include a code snippet that we use.
