### ISSUE TITLE
Python debugger doesn't import local files in vs code

### ISSUE THREAD

**Issue by david26694** [microsoft/pylance-release#3778]
## Environment data

-   Language Server version: v2022.12.20
- OS Version: macOS Big Sur, Version: 11.3.1 (20E241) Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.0, anaconda

## Code Snippet

`folder_structure/main.py`:

```python
from folder_structure.utils.tools import dummy

if __name__ == '__main__':
    dummy()
```

`folder_structure/utils/tools.py`:
```python
def dummy():
    print("Dummy")
```

## Repro Steps

1. `mkdir folder_structure`
2. `mkdir folder_structure/utils`
3. `touch folder_structure/utils/tools.py`
4. `touch folder_structure/main.py`
5. Write in main.py:
```python
from folder_structure.utils.tools import dummy

if __name__ == '__main__':
    dummy()
```
6. Write in tools.py:
```python
def dummy():
    print("Dummy")
```
7. Run the vs code debugger

I'm getting:
```
Exception has occurred: ModuleNotFoundError
No module named 'folder_structure'
  File "/Users/davidmasip/Documents/Others/python-scripts/folder_structure/main.py", line 1, in <module>
    from folder_structure.utils.tools import dummy
```

I have the following in my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {
                "PYTHONPATH": "${workspaceRoot}"
            }
        }
    ]
}
```

How can I import a local module when using the debugger?

This works for me:
```bash
python -m folder_structure.main   
```

**Comment by judej** [comment]
Thanks for the report. @int19h, could you please take a look?

**Comment by int19h** [comment]
If you want to do the equivalent of your command line invocation, instead of "program", it should be:
```json5
"module": "folder_structure.main"
```
That aside, it's not entirely clear to me what the workspace root is with the existing config - are you opening `folder_structure` specifically as a folder in VSCode, or are you opening the parent folder that contains it? If it's the former, that would result in `PYTHONPATH` being set incorrectly.

Another thing to consider is "cwd". If you use "program" without specifying "cwd", and "program" is an absolute path (which it would be with substitution), that path is automatically used as "cwd" by default. Tweaking that might be a better approach than tweaking `PYTHONPATH`, although the same point applies - it must be the folder *containing* `folder_structure` as a subfolder in order to work.

**Comment by rmwenzel** [comment]
It doesn't look like you added `folder_structure/__init__.py`, if so `folder_structure` is not a Python module and the error is likely from the Python interpreter, not VS Code.
