### ISSUE TITLE
Code is unreachable false positive within a context

### ISSUE THREAD

**Issue by SnijderC** [microsoft/pylance-release#3779]
## Environment data

-   Language Server version: 2022.12.20 (pyright 621d886b)
-   OS and version: Debian 11 (docker image: python:3.9.16-slim)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16

## Code Snippet

```python
import contextlib
from collections.abc import Generator


def test(num: int) -> int:
    with error_handler():
        return 100 // num
    return 0  # Code is unreachable


@contextlib.contextmanager
def error_handler() -> Generator[None, None, None]:
    try:
        yield
    except ZeroDivisionError:
        print("Sweeping a problem under the rug")


assert test(0) == 0
```

## Repro Steps

Run pylance on the above.

## Expected behavior

Line 8 is reachable, as asserted on line 19. 

## Actual behavior

Pylance warns about line 8 being unreachable.

## Some context

I know this seems like a bad idea, but this is a simplified version of the actual code. The real code is a class with many methods that share the same error handling code. That code should proceed after a cache entry is not found (raising an exception), without the cache (regenerating instead).

**Comment by erictraut** [comment]
This is expected behavior. See [this thread](https://github.com/microsoft/pylance-release/issues/773#issuecomment-751282824) for more details. 

A context manager is allowed to "swallow exceptions", but most do not. A static type checker needs to be told whether to assume that exceptions will be swallowed. The `@contextlib.contextmanager` decorator is defined in a way that indicates that exceptions are not swallowed, which means that pylance will make that assumption. But your implementation of the context manager _does_ swallow exceptions.

If you want this approach to work with a static type checker like pylance, you will need to define your own context manager class rather than using the one provided by the `@contextlib.contextmanager` decorator.

**Comment by SnijderC** [comment]
Thanks for the quick reply! That makes sense, I guess there is not much you can do to detect that the context manager swallowed the exception with a static type checker.

I'll make my own context manager, it adds a lot of boiler plate code, but I can live with that. Thanks again!
