### ISSUE TITLE
Switch when pylance runs over code to dynamically inject `import mymodule`

### ISSUE THREAD

**Issue by gabyx** [microsoft/pylance-release#3782]
I have a module which I can only load with importlib.
Is it possible to get anyway syntax completion by somehow doing

```python

if pylance_is_running:
    import mymodule


mymod = load_my_mod_with_importlib()

mymod.sub.myfunc() # << No code completion here
```

together `python.analysis.extraPaths`

such that I get code completion also for the above usage.

**Comment by erictraut** [comment]
Yes, you can use the `typing.TYPE_CHECKING` symbol introduced in PEP 484. All static type analysis tools support it. It would look like this:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import mymod
else:
    mymod = load_my_mod_with_importlib()
```

There is some danger in using `TYPE_CHECKING` because the static analysis tools (including type checkers) are now analyzing different code than the code the Python interpreter will execute at runtime. But sometimes it's necessary to "lie" to the type analyzer to handle cases like this one.

**Comment by judej** [comment]
@gabyx, if this does not work, please reopen this issue.
