### ISSUE TITLE
Pylance: unreachable code when using threads

### ISSUE THREAD

**Issue by andreichalapco** [microsoft/pylance-release#3791]
## Environment data

-   Language Server version: v2022.12.20
-   OS and version: Linux Fedora 36
-   Python version: Python 3.10.8

## Code Snippet

```python
import concurrent.futures
import time

# for threaded application
executor = concurrent.futures.ThreadPoolExecutor(max_workers=10)


def threaded(func):
    def wrapper(*args, **kwargs) -> concurrent.futures.Future:
        # Submit the decorated function to the thread pool for execution
        return executor.submit(func, *args, **kwargs)
    return wrapper


class MyClass:
    @threaded
    def print_hello(self, s):
        # here is the problem ... 
        while True:
            # some work
            time.sleep(1)
            print(s)

    def make_something(self):
        for _ in range(5):

            # pylance thinks the next line won't be unreachable due to while true
            self.print_hello("hello")
            self.print_hello("world")


m = MyClass()
m.make_something()
```

## Repro Steps

1. Copy paste into vs code and see the warning of unreachable code

## Expected behavior

Although the while loop the code should be annotated as reachable

## Actual behavior

The code should be reachable

**Comment by erictraut** [comment]
This behavior is "as designed". The function `print_hello` has no return type annotation, so pyright (the static type checker upon which pylance is built) infers its return type from the function's body. Since it is an infinite loop, the return type is inferred as `NoReturn` which means that the function never returns control back to the caller. You are using a decorator `threaded` to wrap the function, but the decorator is also unannotated, so pyright assumes that the decorator does not modify the signature of the decorated function.

You can do a couple of things to fix this. The easiest is to simply add a `-> None` return type annotation to the `print_hello` function. The more sophisticated fix is to annotate your decorator as follows:

```python
P = ParamSpec("P")
R = TypeVar("R")

def threaded(func: Callable[P, R]) -> Callable[P, concurrent.futures.Future[R]]:
    def wrapper(*args: P.args, **kwargs: P.kwargs):
        # Submit the decorated function to the thread pool for execution
        return executor.submit(func, *args, **kwargs)
    return wrapper
```

By doing this, you'll preserve the full signature and docstring for the decorated function.

**Comment by andreichalapco** [comment]
Thank you very much!!!
