### ISSUE TITLE
Can no longer see function info in unexpanded quick info panel

### ISSUE THREAD

**Issue by adamerose** [microsoft/pylance-release#3922]
Not sure what version this regression happened on but in the latest pre-release (v2023.2.13) I can no longer see info here:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/10884874/217362922-1219078a-a2fe-4486-a6b0-91492ae5caa0.png">

Older version:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/10884874/217363206-a9527caf-3e2e-4ca8-b56b-ad8254ac4c10.png">

<details>
-   Language Server version: v2023.2.13
-   Python version: Python 3.9.6
-   Pandas version: 1.3.1

Version: 1.75.0 (system setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
</details>

**Comment by debonte** [comment]
@adamerose, we're betting that in your second ("Older version") screenshot you are using Jedi instead of Pylance. The missing [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) (identifiers are white instead of green, blue, yellow) is another clue that you're not using Pylance there.

Pylance only shows that "completion item detail" text for auto-import and dictionary key completions. We've never provided text in that area for other completion types.
