### ISSUE TITLE
Pylance fails to remove None-type from checked variable type hint

### ISSUE THREAD

**Issue by idelect** [microsoft/pylance-release#3935]
## Environment data

-   Language Server version: 2023.2.20
-   OS and version: Windows 11 Pro (Version 10.0.22621 Build 22621)
-   Python version: Python 3.11.2
-   VS Code Version: 1.75.1 (user setup)

## Code Snippet

```python
from typing import Optional


class TestClass:
    def __init__(self) -> None:
        self.val: Optional[float] = None


dict_w_class = {"foo": TestClass()}
float_val = 0.0
var_a = "foo"
if dict_w_class[var_a].val is not None:
    elapsed_time = float_val - dict_w_class[var_a].val
```

## Expected behavior

Display no "reportGeneralTypeIssues"

## Actual behavior

![image](https://user-images.githubusercontent.com/96303044/217986271-1a500b53-a994-4f5a-9f5e-f25bd0026d0a.png)

Pylance issues a "reportGeneralTypeIssues" error for the above code even though the variable has been type checked to eliminate the "None-type" option.
This issue can be removed if the dictionary key is entered using a string instead of a variable.

## Logs

```
[Info  - 9:28:52 PM] (6788) SourceFile: Received fs event 'change' for path 'c:\Users\idele\My Drive\Signal Scout\.git\FETCH_HEAD'
[Info  - 9:28:53 PM] (6788) SourceFile: Received fs event 'change' for path 'c:\Users\idele\My Drive\Signal Scout\.git\FETCH_HEAD'
(6788) Background analysis message: getDiagnosticsForRange
(6788) Background analysis message: getDiagnosticsForRange
```

**Comment by erictraut** [comment]
This is by design. Pyright (the type checker that underlies pylance) does not narrow the types of index expressions when the subscript is a dynamic expression, such as a variable. It does support narrowing in cases where the subscript is one-dimensional and is a literal string or integer value. For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing).

This same behavior is found in mypy and other type checkers (including those in other languages like TypeScript).

If you change your code to use a string literal, type narrowing will be performed.

```python
dict_w_class = {"foo": TestClass()}
float_val = 0.0
if dict_w_class["foo"].val is not None:
    elapsed_time = float_val - dict_w_class["foo"].val
```
