### ISSUE TITLE
New partial typeshed tensorflow stubs break pylance for tensorflow

### ISSUE THREAD

**Issue by alkatar21** [microsoft/pylance-release#3937]
## Environment data

-   Language Server version: 2023.2.20 (pyright cca7588f)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Code Snippet

```python
import tensorflow as tf
tf.keras.Input(shape=(1, 1)) # Input: Incomplete
```
If I switch to version 2023.2.10 the new partial typeshed  stubs are not bundled and everything works like before.

## Expected behavior

I would like to see a interim solution where either the stubs are not yet respected at all, or the stubs are respected but parts for which there are no stubs still work as without stubs (merge both things). I already asked about this in the typeshed issue first and got the following answer: https://github.com/python/typeshed/issues/7144#issuecomment-1425769593

## Actual behavior

There is nearly no autocompletion, display of function parameters, docs, etc. for tensorflow

**Comment by erictraut** [comment]
If a type stub is present, pyright will assume that it is authoritative for that module and will not attempt to infer types from the library code. "Merging" doesn't make sense here because the absence of a symbol within a type stub is every bit as important as the presence of a symbol. In other words, a type checker can't say "this symbol isn't present in the type stub, so I'm going to assume that the type stub author made a mistake and override its intent by looking for a symbol in the source code instead".

It sounds like the typeshed stubs are quite incomplete at this time, so they're doing more damage than good. I've just deleted them from the pyright repo, and we'll leave them out until they become more complete.

**Comment by alkatar21** [comment]
That sounds good, thank you very much. Would the pyright repo be the right place to go for something like that next time?

**Comment by erictraut** [comment]
Posting to either the pyright or pylance repo is fine. We monitor both.

**Comment by hmc-cs-mdrissi** [comment]
The merging I was thinking of was for files that exist in actual library but have no stub file to use that file. If library has foo.py and bar.py but stub package only has bar.pyi then still use foo.py. Not merging .pyi file with corresponding .py file which I agree would be more error prone.

On typeshed side would it help if we added py.typed file with partial? At moment stub packages typeshed produces never specify py.typed file and unsure if marking stub package as partial matters here.

**Comment by erictraut** [comment]
Pyright already supports the mixing of ".py" and ".pyi" files on a per-module basis. For example, let's assume that the type stub contains `foo/__init__.pyi` but not `foo/bar.pyi`. If the library includes `foo/bar.py`, you can `import foo.bar` in your code to access symbols from `foo.bar`. You cannot access these symbols directly from `foo` if `foo/__init__.pyi` doesn't export them. In the case of tensorflow, most developers tend to import the top-level library and expect that most symbols are accessible (i.e. re-exported from) the top-level module.

Adding a `py.typed` file wouldn't help here because typeshed files are not considered stub packages by pyright or pylance. They're treated differently from installed stub libraries, as per [PEP 561](https://peps.python.org/pep-0561/#type-checker-module-resolution-order).

**Comment by tc-wolf** [comment]
One incredibly disgusting workaround (that worked for me) is to go in and delete the stubs in the extension.  On Linux this looked like

```
rm $HOME/.vscode/extensions/ms-python.vscode-pylance-2023.2.20/.cache/stubs/tensorflow.json
rm -r $HOME/.vscode/extensions/ms-python.vscode-pylance-2023.2.20/dist/typeshed-fallback/stubs/tensorflow
```

and then reloading the language server / editor window.

This will get overwritten on upgrading or reinstalling the extension, though.

**Comment by erictraut** [comment]
We've decided to omit the tensorflow stubs in the latest release of pyright and an upcoming version of pylance. They are too incomplete at this point. We'll consider adding them back when they are further along.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.2.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023231-15-february-2023-prerelease)

**Comment by boxed** [comment]
> "Merging" doesn't make sense here because the absence of a symbol within a type stub is every bit as important as the presence of a symbol.

Sorry about commenting on something old, but this seems like the underlying issue and quite a serious one. Absence by mistake, absence by incompleteness, and absence on purpose to hide private APIs are three very different things. Shouldn't the typing system be able handle the difference cleaner? The two first could be the same, but incompleteness breaking all new APIs until the stubs are updated will by definition mean stubs will always hurt users for the time gap between new feature and the next updated to the type stubs.

**Comment by alkatar21** [comment]
As https://github.com/python/typeshed/issues/7144 seems to be ready now, the change could probably be reverted. Should a new issue be created for this?

**Comment by hmc-cs-mdrissi** [comment]
Tensorflow stubs have coverage of several key parts now. They still are partial and it's unclear to me what threshold for enough coverage is. Full tensorflow api is rather massive although commonly used parts are much smaller. In general stubs I've made should have less false positives then inferring from library code, but will for a long time likely be partial.

I haven't spent much time in recent months filling them out further although happy to review prs to typeshed for tensorflow.
