### ISSUE TITLE
Support for recognizing references to classes

### ISSUE THREAD

**Issue by nav9** [microsoft/pylance-release#3945]
**The issue:**  
```
class Video:
    def something(self):
        print('something)

v1 = Video(); v2 = Video(); v3 = Video()
videos = [v1, v2, v3]
for v in videos:
    v.something()
```
In the code above, `pylint` does not recognize that `v` belongs to the `Videos` class. So if I Ctrl+click on `something()` at the `v.something()` line, I'm not taken to the `Video` class. This also makes it difficult when renaming member variables and member functions. Please improve the linter to provide support for such a scenario (and more scenarios if any, where the references to functions, classes or variables aren't being recognized).

**Comment by debonte** [comment]
After adding the missing end quote in the `print('something)` call, Pylance is able to do what you want. Ctrl+click takes you to the declaration of `Video.something`. Rename renames the declaration and usage of `something`.

If you're not using Pylance already, give it a try! :)

**Comment by nav9** [comment]
I'm already using PyLance. To understand what I mean, please do a Ctrl+click on `isOpened` on the line `if video.video.isOpened():` at line 189 in [this project](https://github.com/nav9/splitVideoQualityViewer/blob/main/video.py). You'll see that clicking on it does not take you to the `isOpened` function in the `VideoFile` class definition.

**Comment by erictraut** [comment]
@nav9, pylance is built on top of pyright, which is a static type analyzer and checker, not a linter. Linting typically refers to a tool that enforces code style conventions. If you're interested in a linter, pylint is a great choice.

Pylance makes use of sophisticated static type analysis techniques, but there are limits to what it can determine statically, especially if you do not use type annotations in your code.

In your code, the variable `video` has an unknown type. You can tell by hovering over the variable, and you'll see `(variable) video: Unknown`. Its type is unknown because it is assigned a value from the iterable expression `self.videos`, and the type of this instance variable is `deque[Unknown]`. When you initialize `self.videos`, you could provide type information (`self.videos = deque[VideoFile]()` or `self.videos: deque[VideoFile] = deque()`).

For more information about type declarations, type inference, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

Your code is also making use of the cv2 library, which is not written in Python. That means pylance cannot extract static type information from the code. For this to work, the maintainers of cv2 would need to provide type information in the form of type stub files. See [this issue](https://github.com/microsoft/pylance-release/issues/138) for more information.

**Comment by erictraut** [comment]
Pyright's type analysis is very sophisticated, but it's not omniscient. It can't "guess" what the type of a variable might be based on its name, for example. It bases its analysis on the type information available to it.

**Comment by nav9** [comment]
I agree that's how it's currently done. I was suggesting adding one more layer of intelligence, which would see a variable, and trace it's origin, similar to how a human would. If it's not practical to implement it, please ignore my request. However, with the advent of so many other AI algorithms, perhaps such intelligence is something that could be built into PyLance.

**Comment by joncox123** [comment]
> Pyright's type analysis is very sophisticated, but it's not omniscient. It can't "guess" what the type of a variable might be based on its name, for example. It bases its analysis on the type information available to it.

Let me get this straight, so a human, which is not omniscient either can figure it out, by Pylance/pyright would need omniscient to do similar? Nav9's question/statement is essentially "I need more intelligence from the analysis algorithm". That is a fair request, I need the same thing. I don't expect mind reading, but if a human can figure it out through some process, the algorithm should be able to as well. 

Instead of making excuses and trying to justify the limitation in your software, just admit that either (1) the feature isn't supported yet; or (2) its a good idea, but you don't have the ability to figure out how to implement it.
