### ISSUE TITLE
Use `workspacePlatform` to configure "right" platform when editing in WSL

### ISSUE THREAD

**Issue by ashb** [microsoft/pylance-release#3947]
Originally posted as https://github.com/microsoft/pyright/issues/4450

I have the following code in a WSL project

```python
import multiprocessing
from multiprocessing.connection import Connection


ctx = multiprocessing.get_context()
p1, p2 = ctx.Pipe()
reveal_type(p1)

x: Connection = p1
```

![image](https://user-images.githubusercontent.com/34150/212308839-8cd916c9-8726-400d-a253-657a8cdd07a9.png)

Error text: 

> Expression of type "PipeConnection" cannot be assigned to declared type "Connection"
  "PipeConnection" is incompatible with "Connection"

The type stub for this has an `if sys.platform != "win32":` 
https://github.com/microsoft/pyright/blob/13492d8126929b184243ef18f9981d73ee826a2b/packages/pyright-internal/typeshed-fallback/stdlib/multiprocessing/context.pyi#L54-L57

```python
    if sys.platform != "win32":
        def Pipe(self, duplex: bool = True) -> tuple[Connection, Connection]: ...
    else:
        def Pipe(self, duplex: bool = True) -> tuple[PipeConnection, PipeConnection]: ...
```

It would be great if pylance could automatically configure pyright's platform based on the workspace platform. Currently it performs the type-checking based on the editor host OS.

**Comment by judej** [comment]
Triage disc: Pylance could start using `workspaceplatform`

**Comment by heejaechang** [comment]
`workspaceplatform` is `not` api exposed to `vscode SDK`. it is something you use in `package.json` like https://github.com/microsoft/vscode-extension-samples/blob/672ac9c79bbfd41a05600a94e626466c4a598586/getting-started-sample/package.json#L145

that said, I can't repro the issue. we correctly detect remote platform since `pylance` is running in remote such as WSL (assuming user trusted the workspace) and we call `os` to get `platform` kind in remote.
