### ISSUE TITLE
Be able to override the type of a variable manually

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#396]
As a specific example, I'm using tomlkit which returns a `_TOMLDocument` that acts like a dict. I created a `TypedDict` since I don't need the extra methods that tomlkit provides (they are for writing new TOML data out). But when I do `data: MyTypedDict = tomlkit.loads(...)`, Pylance says I can't do that.

**Comment by erictraut** [comment]
If you are sure that the RHS type is safe to assign to a type on the LHS, you can use the `typing.cast` call to perform the cast. I tend to use cast sparingly (as a last resort) because it completely overrides the type checking logic, making it unsafe.

To do this in a truly safe manner, you'd need to get the entries of the source dict and verify the type of each, then build a new dictionary that is provably compatible with the MyTypedDict.

```python
a = cast(MyTypedDict, tomlkit.loads(...))
```
