### ISSUE TITLE
Understand what `str.split(..., N)` means

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#397]
This is probably a shortcoming of Python's type system and how lists are represented, but I have `Class(*thing.split("/", 2), another_arg)` and Pylance (as well as mypy) are complaining that one of the arguments to `Class.__init__()` expects an int. But that argument is the fourth one, which can't be reached with that call structure.

**Comment by erictraut** [comment]
I'm not sure I understand. Could you please provide the signature for the `Class.__init__()` method?

**Comment by brettcannon** [comment]
Yeah, sorry for leaving that out.

```python
def spam(a: str, b: str, c: str, d: int = 42): ...
```

If I call `spam(*thing.split("/", 2), "hello")`, that will run perfectly fine and is a correct typing for those first three arguments. But because `str.split()` has a return type of just `List`, Pylance says that that `d` argument will get a `str` and not an `int` due to that unpacking _potentially_ filling every argument.

I'm about to open up a thread on typing-sig about fixing this gap in the typing system, but just in case there's interest in special-casing built-ins like this I wanted to also open this issue.

**Comment by brettcannon** [comment]
https://mail.python.org/archives/list/typing-sig@python.org/thread/4HISGN2ILWDUDEPJYEZ4DKJNJZQFDEMW/ for the discussion thread I just kicked off.

**Comment by erictraut** [comment]
A type checker has no way of knowing how many elements will be contained within a list, nor should it. Lists are not fixed-sized, and they're generally not used in cases where static-sized containers make sense. That's what tuples are designed for, and type checkers do understand tuple lengths.

The code sample you've provided here is generally unsafe because you're relying on split to always return two items. But what if the string that's passed in has no "/" characters? You'll receive a runtime exception in that case.

Here's how I would write this in a safe manner that also works with a type checker.

```python
def validate_input(input: str) -> Tuple[str, str]:
    elements = input.split("/", 2)
    if len(elements) != 2:
        raise Exception("Received bad value")
    return (input[0], input[1])

spam(*validate_input("/"), "hello")
```

If you are 100% sure that the input contains at least one "/" character, then you could do the following:

```python
elements = input.split("/", 2)
spam(elements[0], elements[1], "hello")
```

**Comment by brettcannon** [comment]
You're right that _in general_ you can't know the length of a list. But as you noted, `str.split()` will raise an exception if it can't produce a list of the exact size requested, so it's as guaranteed as it can be to returned the expected length.

To me, the two proposals you give, while satisfying the type checkers, do only that: satisfy the type checker. They don't actually enhance my code because I want the exception from `str.split()` to propagate up and I find it totally readable to do the call inline in the class initialization.

Anyway, all good if there isn't interest in special-casing `str.split()` for this; I realize it's somewhat of an edge case.

**Comment by erictraut** [comment]
What you're asking for would require way more than just special-casing `str.split()`. It would also require the introduction of a while new list type, one that includes its length as part of its type. Something like: `ListWithLength<int, Literal[2]>`. Methods would need to be added that properly transform the type whenever such a list is mutated (e.g. items are pushed or popped). And many operations would need to drop the length because there's no way to determine the updated length statically.

**Comment by jakebailey** [comment]
This has been an ongoing discussion for a while, as this sort of thing is being prototyped to allow for things like tensor dimensions (I believe there's a monthly call announced in the typing-sig, though it's at a time I can't make).
