### ISSUE TITLE
import os.path can not use os.listdir()

### ISSUE THREAD

**Issue by anemele** [microsoft/pylance-release#3980]
Pylance raises an error:

```python
import os.path
os.listdir('/')
```

but it runs correctly.

**Comment by erictraut** [comment]
This behavior is "as designed". You are not explicitly importing `os` in your code. You're relying on an implicit side effect of importing `os.path`. Pyright (the type checker that underlies pylance) intentionally doesn't model implicit loader side effects like this, and it considers it a bug to access modules that you haven't explicitly imported.

You can address this issue in your code by adding an `import os` statement.

**Comment by anemele** [comment]
According to [https://docs.python.org/3/tutorial/modules.html#packages](https://docs.python.org/3/tutorial/modules.html#packages), the second last paragraph, when using `from xxx import yyy`, python will try to load `yyy` if it is a module. Similiarly, when using `import xxx.yyy.zzz`, python will load `xxx`, `xxx.yyy` and `xxx.yyy.zzz`.
I think it is not a "side effect", but pythonic.

**Comment by erictraut** [comment]
It is an implicit side effect in that importing `xxx.yyy.zzz` is not only loading and initializing `xxx.yyy.zzz`, but it's also implicitly modifying the namespace of `xxx.yyy` and `xxx`. This side effect may be deterministic, but it is still implicit. There are other side effects of the Python loader that are both implicit and non-deterministic, at least from a static analysis perspective, because they depend on order of execution. We've previously discussed the idea of supporting this particular implicit side effect but decided against it. If you want pylance not to raise an error here, you will need to include `import os` explicitly. If you don't want to see errors like this, you can disable static type checking by setting the `python.analysis.typeCheckingMode` to "off".

**Comment by anemele** [comment]
Oh, it strikes me that `Explicit is better than implicit.`, from `The Zen of Python`.

Maybe your decision is appropriate.
