### ISSUE TITLE
Pylance autoimport suggests symbols that would be Unknown when imported

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pylance-release#3984]
## Environment data

pylance: v2023.2.31

## Code Snippet

```python
from typing import TypedDict


class UserBadgeBadge(TypedDict):
    badgeid: int
    appid: NotRequired[int]
```

## Repro Steps

![image](https://user-images.githubusercontent.com/50501825/220407931-6bd1947a-d8ab-43e6-bbdb-5b9ee29517f1.png)
![image](https://user-images.githubusercontent.com/50501825/220407986-7676e263-5570-4b55-a79e-fc24138d1c90.png)

## Expected behavior

The import should be suggested from typing_extensions where it is present.

## Actual behavior

The import is from typing which doesn't exist in according to my version set in my pyproject.toml
```toml

[tool.pyright]
typeCheckingMode = "basic"
pythonVersion = "3.10"
```
Interestingly this would work at runtime because I'm actually running 3.11

**Comment by judej** [comment]
This is by design since we are bundling the stubs assuming the latest version - currently 3.11. One option is to delete the stubs for the standard library that you can find at `.vscode\extensions\ms-python.vscode-pylance-2023.2.31\dist\bundled\indices` change version number to the version you are using. The downside is that if those stubs are deleted, every time you open the workspace, you will need to reindex the standard library. This will take about 4-5 seconds.

**Comment by erictraut** [comment]
@judej, the problem is not that the stubs assume the latest version. The typeshed stubs contain conditionals based on Python version, so they work with all supported versions of Python.

I think this is a legitimate pylance bug that needs to be investigated. Perhaps the indexer is assuming the latest Python version rather than the configured version?

**Comment by debonte** [comment]
@heejaechang 

I think Jude got some terminology wrong in his reply. Similar to what you suggested, I believe the issue is that the stdlib is pre-indexed assuming the latest Python version (3.11).

**Comment by heejaechang** [comment]
ya, it should have said `pre-generated indices` file rather than `stub`. Currently we ship pre-generated indices for stdlib with the latest python version. Currently we don't persist indices on users machine (and it needs to be per workspace , not per machine/user or per version/platform matrix) so, with current design, not much we can do. 

Only thing user can do is deleting the pre-generated indices as jude mentioned, but that will cause about 4-5 seconds to generate stdlib indices every time vscode runs (since we need to re-calcuate them every time) and user won't get auto/add imports for stdlib when indexing is off.

**Comment by erictraut** [comment]
Have you considered generating indexed variants for all supported Python versions (3.8 through 3.11)? If that's too large, perhaps the index format could include Python version information so pylance can determine whether a particular symbol is valid for the configured version?

**Comment by heejaechang** [comment]
we could do that, but it is actually not just versions, it is versions x platform matrix. so 4 x 3 = 12 variations. and yes, we could make our index format more complex so we can encode that information somehow. but my gut feeling is just calculating and persisting those index data per workspace might be just simpler. and we could use the same logic to persist all third party libraries index data if user wants to.

**Comment by erictraut** [comment]
As you know, I recommend against persisting caches on the user's machine. There are many problems with this approach.
