### ISSUE TITLE
Intellicode no longer works in Azure Notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4032]
Did some debugging with Barry. Root cause was this line here:

https://github.com/microsoft/pyrx/blob/f55fe7fe6b6632e2f0bc79ef6319127d8fbad346/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L563

We didn't use to check if the program owned a file before using the intellicode extension.

I think the owns result is wrong. In Barry's case the SourceFileInfo was there, but the file wasn't being tracked. I think `owns` should just check if there's a file info or not.

**Comment by heejaechang** [comment]
`SourceFileInfo` could be there for multiple reasons

1. a file is opened by editor (might or might not be a tracked (user) file. if it is not tracked, once file is closed, pylance will remove it from memory if no other file is using it transitively at some point.)
2. a file is a user file (scanning user files from service using `include/exclude` picked up the file) and marked as isTracked.
3. a file is used by other files such another file imported this file or this file is shadowing a pyi file. if `2` above didn't already bring in this file, it must be a file from `library or external path` and not marked as `tracked` and it will go away once there is no one transitively consume it.
4. extension (such as pytest) load them into memory. these won't be marked as `tracked` and go away like other ones.

there could be more but these are ones I can remember on top of my head. but main point is (except special case such as cloning service/program to process some special work such as creating stub files or indexing and etc), 
1. user files (that matches `include/exclude`) are loaded into many when workspace folder is open right away and those are ones that are marked as `tracked`
2. user file (that doesn't exist in file system such as notebook cells) can be dynamically added when a file is opened and marked as 'tracked`
3. all other files added to program won't have `tracked` flag set and they will go away once no one else is using them.

currently `program.owns` will say `yes` to (1), (2) case above. but `no` for other cases. we can't say a program owns a file just because `sourceFileInfo` exists for the file since it could be in due to (3), (4)

For example, if you have multi root workspaces, a file can exist as `sourceFileInfo` in multiple workspaces. one as `tracked` user file, the other as `not tracked` library file. ex) extraPath pointing to other workspace folder or editable install of 1 workspace folder to the other workspace.

so, we need to see why the `sourceFileInfo` is there and why intelliCode cares about it.

**Comment by rchiodo** [comment]
In Azure's example, it was a dummy file they were generating that was in memory. So it wasn't actually on disk or in the workspace, but it had been sent through `textDocument/didOpen`.

**Comment by heejaechang** [comment]
ya, in that case, if it was workspaceMap.getBestWorkspace..., it would return default workspace (hence program in the default workspace) if there was no workspace or multiple regular workspaces, or the regular workspace if there was only 1 regular workspace.

looks like current code in extensibility doesn't handle those cases.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023321-8-March-2023-PreRelease)
