### ISSUE TITLE
Pylance seems to ignore the annotation function

### ISSUE THREAD

**Issue by anemele** [microsoft/pylance-release#4034]
I have two functions as bellow:

```python
def f1(x: str):
    ...

@check
def f2(x: Union[int, str]):
   ...
   f1(x)
```

I write the type checking and converting part in an annotation:

```python
def check(func):
    @wraps(func)
    def wrapper(x):
        ...
        if isinstance(x, int):
            x = str(x)
        ...
        return func(x)
    return wrapper
```

Then Pylance raises an error at the calling `f1(x)` in `f2`.

**Comment by erictraut** [comment]
The behavior you're seeing is correct. You have annotated the input of the undecorated function `f2` as receiving a single parameter `x` of type `int | str`. Since `f1` doesn't accept an `int`, the type checker is correctly telling you that you have a type violation in your code. If your intent is for the undecorated `f2` to accept only a `str` argument, you should annotate it as such.

Here's how that would look:
```python
from functools import wraps
from typing import Callable

def f1(x: str): ...

def check(func: Callable[[str], None]) -> Callable[[int | str], None]:
    @wraps(func)
    def wrapper(x: int | str):
        ...
        if isinstance(x, int):
            x = str(x)
        ...
        return func(x)

    return wrapper

@check
def f2(x: str):
    f1(x)
```
