### ISSUE TITLE
Python/Pylance performance affects symbol search in C++ file

### ISSUE THREAD

**Issue by darrell-james** [microsoft/pylance-release#4035]
Heya,

Our codebase uses C++ & Python, but when in a C++ file and doing Ctrl+T to do a Workspace Symbol Search it takes a long time to complete on the first run. I determined that this was due to the Python/Pylance extension, after disabling it the speed was quick.

My question is, is there a way to configure Python/Pylance not to perform a symbol search when not in a *.py file (or similar mechanism)? I still would like this extension enabled for Python editing but currently I would have to disable and re-enable it for the best of both worlds.

**Comment by rchiodo** [comment]
Thanks for the issue.

Sorry but disabling pylance during 'workspace symbol search' when not in a python file is not possible. VS code doesn't currently support this level of granularity.

I assume you want like a "C++" workspace symbol search and a "Python" workspace symbol search.

You might try splitting your workspace into two folders? One for C++ code and one for Python code? 

Otherwise, you might try asking VS code for a setting to create a language specific workspace symbol search.

**Comment by darrell-james** [comment]
Hi rchiodo,

Thanks for that, that's a shame but it was what I was expecting basically. I don't think we can decouple the code so easily in our codebase, but I might try creating two workspace files in the same spot and use the disable for this workspace feature.

I'll go post on VS code to see if they'll accept it was a feature request.

Thanks!
