### ISSUE TITLE
Pylance is marking my code as unreachable erroneously.

### ISSUE THREAD

**Issue by MingwuZheng** [microsoft/pylance-release#4052]
## Environment data

-   Language Server version: v2023.3.20
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Code Snippet

```python


class MyClass():

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")

    @staticmethod
    def my_static_method():
        pass

a = MyClass()
i = 1
i += 1



```

## Expected behavior

I expect Pylance to recognize that the class only has static method and not mark the code as unreachable.

## Actual behavior

![image](https://user-images.githubusercontent.com/29904815/223907313-9889c1c3-aac6-4e1b-90fe-141cf986e2be.png)

**Comment by erictraut** [comment]
If you run this code, you will never execute `i = 1` because the constructor raises an exception. That's what pylance is telling you by graying out the code below the statement `a = MyClass()`.

If your intention is to create an abstract base class that has other non-abstract subclasses, then you should define it as follows:

```python
from abc import ABC, abstractmethod

class MyAbstractClass(ABC):
    @abstractmethod
    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")

    @staticmethod
    def my_static_method():
        pass

class MyClass(MyAbstractClass):
    def __init__(self, *args, **kwargs):
        pass

a = MyClass()
i = 1
i += 1
```

If your intent is to provide a class that has only static methods and therefore should never be instantiated, then you should not attempt to instantiate it by calling `MyClass()`.

**Comment by MingwuZheng** [comment]
Thanks for you response. However, I can assure you that I run this code without any exception. It is in a UE5 project.
![image](https://user-images.githubusercontent.com/29904815/223922701-e588a310-d839-4dcd-8291-e272787b9d18.png)


![image](https://user-images.githubusercontent.com/29904815/223922491-7dde9ce5-5132-4a3b-94ad-a2a0eeee707f.png)

Do you have any ideas? Thanks again!

**Comment by erictraut** [comment]
The code in your screen shot is different from the code you posted above. If you run the code you posted above, do you receive an exception when you run it?

I don't have enough context to debug the code in your screen shot. Could you provide more context? Ideally, we need a minimal sample that exhibits the problem. For example, it's not clear from your screen shot where the symbol `BoundedIOStream` comes from. I presume it's imported from a library. If so, what library and which version?

**Comment by erictraut** [comment]
Looking closer at the code in the screen shot, the `__init__` method for `FileStream` clearly raises an exception. That probably means that the class `BoundedIOStream` has a metaclass that implements a custom `__call__` method that doesn't call through to the `__init__` method of its constructed classes. Pylance should handle that case, so I'm not sure what's going on. I should be able to figure it out if you provide more details.

**Comment by MingwuZheng** [comment]
![image](https://user-images.githubusercontent.com/29904815/223926990-79293d5a-8679-47f2-857b-1ea45e61f43f.png)

class BoundedIOStream looks like this.

**Comment by MingwuZheng** [comment]
I am sure I can run the code without exceptions. But it is hard for me to extract a minimal, self-contained sample.

**Comment by erictraut** [comment]
Can you at least tell me where the symbol `BoundedIOStream` comes from? Which library and submodule? Which version?

**Comment by MingwuZheng** [comment]
> 

It's here.

**Comment by MingwuZheng** [comment]
> ![image](https://user-images.githubusercontent.com/29904815/223926990-79293d5a-8679-47f2-857b-1ea45e61f43f.png)
> 
> class BoundedIOStream looks like this.

It is here.

**Comment by erictraut** [comment]
That's a screen shot of the code. I'm asking which library you're importing this symbol from so I can construct a repro case. A screen shot doesn't help me.

**Comment by MingwuZheng** [comment]
Apologize . Here is the link. https://drive.google.com/file/d/1LYOUcPyGrwFBEg6KI0hK5Sc_SUoZsWWc/view?usp=share_link
Thanks again for you time.

**Comment by MingwuZheng** [comment]
` BoundedIOStream` is in the dna.py.

**Comment by erictraut** [comment]
Is this code part of a library that you're importing? Or is it code that you wrote? The code includes native binaries that are compiled for windows and linux. I'm using a Mac, so I'm not able to run the code to attempt to repro.

None of the classes in the class hierarchy for `BoundedIOStream` have a custom metaclass. However, the code is calling a function called `_py3dna.BoundedIOStream_swigregister` which is implemented in native code, so I can't tell what it does. My theory is that it monkey patches the class and overwrites its `__new__` or `__init__` method. If my theory is correct, Pylance would have no way of knowing that such behind-the-scenes manipulation is taking place.

**Comment by MingwuZheng** [comment]
It is a library I'm importing. If your theory is correct, how can I stop Pylance graying out all my following code?

**Comment by erictraut** [comment]
What is the library? Did you install it through pip (the pypi registry)? If so, what is its name? Is its code available in a public github project? If I can get some additional details, that will help me validate or invalidate my theory.

**Comment by MingwuZheng** [comment]
I'm using this library. https://github.com/EpicGames/MetaHuman-DNA-Calibration/tree/main/lib/windows

**Comment by erictraut** [comment]
The repo doesn't include the code used to compile the native libraries, so I can't tell what `BoundedIOStream_swigregister` is doing. As I mentioned above, I suspect it's monkey patching the `BoundedIOStream` class.

Here are two workarounds that you can use to avoid the "grayed out" text:
1. Set `python.analysis.useLibraryCodeForTypes` to false in your project settings. This will tell pylance not to attempt to infer any information about the symbols imported from this library (or any other libraries that don't include static type information). This will cause you to lose all completion suggestions for symbols imported from all such libraries.
2. Create a minimal stub file for this library. Name it `dna.pyi` and place it in directory called `typings` within your project.
```python
# ./typings/dna.pyi
from typing import Any

def __getattr__(name: str) -> Any: ...
```
This will tell pylance to ignore any symbols from the library `dna` and treat them all as `Any` rather than attempting to infer their types from the source code. As with option 1, you will lose completion suggestions for this library, but you won't lose completion suggestions for other untyped libraries that you're importing.
