### ISSUE TITLE
typeshed stubs are not resolved when library is imported from extraPaths

### ISSUE THREAD

**Issue by adamhl8** [microsoft/pylance-release#4063]
When importing a library from a directory I've added via `python.analysis.extraPaths`, the related typeshed types are not being resolved.

```python
from psutil import Process

parent_exe = Process().parent().exe() # Type warnings
# Type of "parent_exe" is "Unknown | str"
```

If my case, I'm using PDM to install `psutil` which installs to `__pypackages__`. My VS Code settings for pylance are:

```json
"python.analysis.extraPaths": ["${workspaceFolder}/__pypackages__/3.10/lib"],
"python.analysis.typeCheckingMode": "strict"
```

If I instead install `psutil` to site-packages via pip, I get the correct types:

```python
parent_exe = Process().parent().exe() # No type warnings
# parent_exe: str
```

I also have pyright installed separately via npm and it does not report any errors (with `psutil` installed in `__pypackages__`), so this seems related to pylance specifically.

As a workaround, if I also install `types-psutil` I get proper types.

## Environment data

-   Language Server version: v2023.3.20
-   OS and version: Ubuntu 22.04 (WSL2)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6

**Comment by debonte** [comment]
> I'm using PDM to install `psutil` which installs to `__pypackages__`.

To set expectations -- we do not currently support [PEP 582](https://peps.python.org/pep-0582/). There's an enhancement discussion about that [here](https://github.com/microsoft/pylance-release/discussions/2584). But I think we're unlikely to add PEP 582 support until it is closer to being finalized. It's still a draft PEP that is being [actively discussed](https://discuss.python.org/t/pep-582-python-local-packages-directory/963).

In any case, we don't support PEP 582, so the question is how to work around that missing support.

> If I instead install `psutil` to site-packages via pip, I get the correct types:
> ...
> As a workaround, if I also install `types-psutil` I get proper types.

Our import resolution logic is documented [here](https://microsoft.github.io/pyright/#/import-resolution?id=import-resolution). One thing that is not covered there is how we decide between multiple possible import results (files) during this process. This is in [`_pickBestImport`](https://github.com/microsoft/pyright/blob/ce66cc21bbcd87447aa3bd450340bd728603ae84/packages/pyright-internal/src/analyzer/importResolver.ts#L1512).

The reason you're seeing the current behavior is that although we do generally [prefer stubs](https://github.com/microsoft/pyright/blob/ce66cc21bbcd87447aa3bd450340bd728603ae84/packages/pyright-internal/src/analyzer/importResolver.ts#L1572) over `.py` files, we [prefer "local" packages](https://github.com/microsoft/pyright/blob/ce66cc21bbcd87447aa3bd450340bd728603ae84/packages/pyright-internal/src/analyzer/importResolver.ts#L1536) even more. And declarations found in `extraPaths` have `ImportType.Local`. Declarations found in the python search path (ex. in a venv) on the other hand have `ImportType.ThirdParty` which is why you're seeing different behavior with `pip`.

So rather than using `extraPaths` I'd suggest somehow getting `"${workspaceFolder}/__pypackages__/3.10/lib"` into the python search path.

### Workaround 1 -- `venvPath` + `venv`
I was hoping that you'd be able to do this by setting the following in your `pyrightconfig.json`:

```json
{
    "venvPath": "__pypackages__",
    "venv": "3.10"
}
```

But our [venv search logic](https://github.com/microsoft/pyright/blob/ce66cc21bbcd87447aa3bd450340bd728603ae84/packages/pyright-internal/src/analyzer/pythonPathUtils.ts#L147) expects a path like `<venvPath>/<venv>/lib/site-packages` and you're missing the `site-packages` bit. If you move the contents of the `lib` directory into `lib/site-packages`, the `pyrightconfig.json` above will fix your issue. But I assume that that will break compatibility with PDM.

### Workaround 2 -- venv with `.pth` file
Another option is to create a venv with a `.pth` file pointing to your `__pypackages__\3.10\lib` directory. This will cause `__pypackages__\3.10\lib` to be added to the python search path (when the venv is activated) and thus you'll get your desired behavior.

> I also have pyright installed separately via npm and it does not report any errors (with `psutil` installed in `__pypackages__`), so this seems related to pylance specifically.

I see the same errors when using Pyright 1.1.298 in VS Code.

**Comment by adamhl8** [comment]
Thank you for the detailed response. I think I have a better understanding of what's going on.

I realized that in my `[tool.pyright]` config, I'm not specifying extraPaths for pyright, only for pylance via my VS Code settings. So when I run pyright directly via cli not only is it able to import `psutil` locally, but it also resolves the types. As part of the PDM [install instructions for PEP 582](https://pdm.fming.dev/latest/usage/pep582/), it has you add `~/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/pep582` to `$PYTHONPATH`.

Which from what I understand is effectively doing what you suggest here:
> So rather than using extraPaths I'd suggest somehow getting "${workspaceFolder}/__pypackages__/3.10/lib" into the python search path.

If that's the case, I think that explains why pyright is working as expected.

Just to go through my thought process here (and this is all completely ignoring pylance for the moment):

With `psutil` installed locally via PDM, `extraPaths` not set, and `~/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/pep582` not on `$PYTHONPATH`:
- pyright reports `warning: Import "psutil" could not be resolved from source (reportMissingModuleSource)`, which is expected.
---
With `psutil` installed locally, `extraPaths` set to `["__pypackages__/3.10/lib"]`, and no `$PYTHONPATH`:
- pyright resolves the import and reports type errors (e.g. `Argument type is "Unknown | str" (reportUnknownArgumentType)` as expected.
---
If I add `~/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/pep582` to `$PYTHONPATH` and *remove* `extraPaths` from my config:
- pyright reports no errors.
---

What is a bit confusing to me is that if I have that directory on `$PYTHONPATH` and *keep* `["__pypackages__/3.10/lib"]` in `extraPaths`, pyright again reports those type errors, matching the behavior I'm seeing with pylance. So the working setup for pyright is to just have that directory on `$PYTHONPATH` and nothing else.

That made me think that perhaps I can do the same for pylance, but removing `"python.analysis.extraPaths": ["${workspaceFolder}/__pypackages__/3.10/lib"]` from my VS Code settings expectedly causes pylance to not be able to import `psutil`.

Anyway, point being, I thought that pylance might not be looking at `$PYTHONPATH` or something like that. I added `/home/<user>/<project>/__pypackages__/3.10/lib` to it directly, which allows pylance to find `psutil` but does not resolve the types.

For clarity's sake, here's a table of the different behaviors I'm experiencing between pylance and pyright:

|                                                       | **Pylance**             | **Pyright**             |
|-------------------------------------------------------|-------------------------|-------------------------|
|  `extraPaths` not set, `$PYTHONPATH` (PDM dir) not set | Cannot resolve `psutil` | Cannot resolve `psutil` |
|  Direct path to `__pypackages__/3.10/lib` on `$PYTHONPATH`, `extraPaths` not set, `$PYTHONPATH` (PDM dir) not set | Resolves `psutil`, Type errors  | ✓ No errors |
|  `extraPaths` not set, `$PYTHONPATH` (PDM dir) **set** | Cannot resolve `psutil` | ✓ No errors                         |
|  `extraPaths` **set**, `$PYTHONPATH` (PDM dir) not set | Resolves `psutil`, Type errors                        |  Resolves `psutil`, Type errors                       |
|  `extraPaths` **set**, `$PYTHONPATH` (PDM dir) **set** |   Resolves `psutil`, Type errors                       | Resolves `psutil`, Type errors                         |

**Comment by debonte** [comment]
Thanks for the additional details.

Pylance currently adds the paths in the `PYTHONPATH` environment variable into `extraPaths`. Pyright does not do this, which explains the difference in behavior.

@erictraut, what do you think about this inconsistency? It was introduced [here](https://github.com/microsoft/pyrx/pull/852). Should we address this in conjunction with https://github.com/microsoft/pylance-release/issues/4085? If so, thoughts on whether Pylance's behavior is incorrect (should be removed), should be configurable, etc?

**Comment by erictraut** [comment]
Oh, I didn't know that pylance added this divergent logic. I'm not sure I understand the reasoning behind this change. As you're probably aware, there's logic in pyright runs a short script to dump the `sys.paths` paths for the selected Python environment. This should include any additional paths configured through the `PYTHONPATH` environment variable. I presume that the logic added to pylance reads the value of `PYTHONPATH` from a local `.env` file instead of the configured environment variables?

It looks like @jakebailey added the change. Perhaps he has additional context.

As you know, there is increasing desire from users to use pylance in conjunction with the CLI version of pyright, and they're looking for consistent behavior. I think it would be good for us to reduce and eliminate any configuration differences between the two. (On a similar note, I've wondered whether we should change the `useLibraryCodeForTypes` default in pyright to match that of pylance.)

**Comment by jakebailey** [comment]
Git history is probably going to have more context than me at this point 😅 but I'm guessing this is related to https://github.com/microsoft/pylance-release/issues/2262 and the linked pylance PR, something to do with env file template replacement.

**Comment by jakebailey** [comment]
(but don't take my word for it, I can't recall at the moment without doing some looking)

**Comment by debonte** [comment]
> I presume that the logic added to pylance reads the value of PYTHONPATH from a local .env file instead of the configured environment variables?

Yes, that's correct. The two issues that lead to this are https://github.com/microsoft/pylance-release/issues/2262 and https://github.com/microsoft/pylance-release/issues/2195. There's some more context there.

The code that finds, reads, and watches the `.env` file is currently in the Python extension. The `PYTHONPATH` from the user's `.env` is passed down to Pylance with the rest of our settings.

@erictraut, would you be open to us adding support for `.env` files in Pyright? So `findPythonSearchPaths` could append the `.env` `PYTHONPATH` to the paths obtained from the interpreter? Then we could remove the code that adds these to `extraPaths`.

**Comment by erictraut** [comment]
If this comes from the Python extension, how would that work with the CLI version of pyright? Are you proposing that we'd no longer rely on the Python extension and replicate that functionality in pyright in its entirety?

Do we understand where users make use of `.env` files and how they are used? Does the Python interpreter pay attention to a ".env" file? Or do they typically "execute" the ".env" file to set the shell variables before running the Python interpreter?

I think your idea is worth considering. Here are a few considerations:
1. Does ".env" parsing involve a bunch of code with many internal dependencies within the Python extension? I don't have a good sense for the level of complexity. I'm guessing that it involves shell variable expansion. Does it have a full bash shell interpreter in it?
2. Based on how ".env" files are used, does it make sense for it to apply to CLI-based execution of pyright? Would it be better to tell users to "execute" the ".env" file before executing the pyright CLI?

**Comment by debonte** [comment]
> Are you proposing that we'd no longer rely on the Python extension and replicate that functionality in pyright in its entirety?

Yes, sorry I was unclear. I'm proposing that Pylance would no longer rely on the Python extension for obtaining this data. We'd replicate the relevant parts of what they are doing.

> Do we understand where users make use of .env files and how they are used?

The extent of my knowledge on the subject came from these two places. They're both quick reads:
- https://code.visualstudio.com/docs/python/environments#_environment-variables
- https://snarky.ca/use-toml-for-env-files/

Note that Brett's page says, "This is where .env files come in; by providing a file which acts as a place to write down environment variable defaults for your application, you can make environment variables just change the default settings." However, the Python extension treats `PYTHONPATH` as a special case -- the two values are concatenated.

> Does the Python interpreter pay attention to a ".env" file?

I believe the answer is no. Otherwise [python-dotenv](https://github.com/theskumar/python-dotenv ) would not exist.

> Or do they typically "execute" the ".env" file to set the shell variables before running the Python interpreter?

According to the python-dotenv docs, apps are expected to load the `.env` via an API call before checking their config:

```python
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

# Code of your application, which uses environment variables (e.g. from `os.environ` or
# `os.getenv`) as if they came from the actual environment.
```

> Does ".env" parsing involve a bunch of code with many internal dependencies within the Python extension? I don't have a good sense for the level of complexity. I'm guessing that it involves shell variable expansion. Does it have a full bash shell interpreter in it?

It seems pretty simple. It does support replacement of `{foo}` strings with currently defined env vars. That code is [here](https://github.com/microsoft/vscode-python/blob/main/src/client/common/variables/environment.ts#L113).

> Based on how ".env" files are used, does it make sense for it to apply to CLI-based execution of pyright? Would it be better to tell users to "execute" the ".env" file before executing the pyright CLI?

If there's a tool to apply a `.env` to the user's environment, that's an option. I haven't run into one. It would need to know to concatenate the system and `.env` `PYTHONPATH` values though, and it seems like the typical approach with `.env` is that the system environment values override the `.env` values.

@propertone, you opened [the issue](https://github.com/microsoft/pylance-release/issues/2262) asking Pylance to apply the `PYTHONPATH` from your `.env` to `extraPaths`. Do you happen to also use the CLI version of Pyright and have thoughts on this discussion?

**Comment by erictraut** [comment]
I agree that the logic for parsing the ".env" file doesn't look too complex. 

The Python extension allows the user to specify a path to the ".env" file. If we added this to pyright, we'd presumably need to add the ability to specify this as well. So this would add more complexity to the pyright configuration. Would we need to also provide a command-line option? Then it's even more complexity.

The ".env" file mechanism is a pretty kludgy one for the reasons pointed out in the article you linked above. Its format isn't standardized, and it is not cross-platform. 

I think our options are:
1. Move the ".env" logic into pyright and add new configuration support for selecting where the ".env" file lives.
2. Remove support for ".env" altogether, since it's such a kludgy mechanism.
3. Leave things as is and document that if you're using a ".env" file in pylance, you need to configure "extraPaths" in pyright if you want the same behaviors.

I'm guessing that there are some pylance users (including @propertone) who are relying on ".env" files, so option 2 is probably not a good option.

Of the two remaining options, I'm inclined toward 3. The ".env" mechanism doesn't feel like something pyright should know about. I think this is something we can document. Users who want to get the same behavior from pylance and pyright can either stop using a ".env" file in pylance or manually specify the "extraPaths" in pyrightconfig.json or pyproject.toml.
