### ISSUE TITLE
ipywidgets observe pattern raises reportGeneralTypeIssues on correct code

### ISSUE THREAD

**Issue by add-IV** [microsoft/pylance-release#4067]
<h3> Environment data </h3>

-   Language Server version: 2023.3.20
-   OS and version: Windows 10 Education x64 22H2 19045.2604
-   Python version: Miniconda, 3.10.9
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

inside minimal.ipynb
with fresh miniconda env
only additional install is ipywidgets 7.6.5
also traitlets version is 5.7.1

This is correct code but raises a reportGeneralTypeIssues Warning.

```python
import ipywidgets as widgets

text_widget = widgets.Text()

def do_stuff(change):
    print("changed")

text_widget.observe(do_stuff, names='value')

display(text_widget)
```
![pylance](https://user-images.githubusercontent.com/47333498/224911479-8f27dd7e-0428-443b-816c-7de2f7769416.gif)

<h3> Expected Behavior </h3>

Since this is the correct syntax pylance shouldn't show a problem.

<h3> Actual Behavior </h3>

Pylance shows the Problem:
Argument of type "Literal['value']" cannot be assigned to parameter "names" of type "Sentinel" in function "observe"
  "Literal['value']" is incompatible with "Sentinel"

I also tried names='All' since thats a basic traittype, same result.

<h3> Logs </h3>

[trace.txt](https://github.com/microsoft/pylance-release/files/10964678/trace.txt)

**Comment by erictraut** [comment]
You are correct that this is the correct syntax. Pylance isn't reporting a syntax error here. Rather, it's reporting a type violation. The library ipywidgets is an untyped library (i.e. it doesn't contain any static type annotations for its input parameters), so pylance does its best to infer these types based on available information. In this case, the type of the parameter `names` is inferred to be `Sentinel` based on the default value it is assigned. Apparently, the method accepts types other than `Sentinel` for this parameter, but pylance isn't able to infer this.

The ideal fix for this problem is for this library author to provide inlined type annotations or type stubs that provide the type information for the library's functions and methods. 

In the meantime, here are a couple of workarounds:
1. If you don't want to see any type-related errors or warnings in your code, you can disable this class of diagnostics by setting `python.analysis.typeCheckingMode` to "off".
2. You can suppress this error on this single line by adding a `# type: ignore` comment at the end. This is the standard way (as described in PEP 484) to suppress type-related errors.

**Comment by add-IV** [comment]
After checking out the repository for traillets, seems like they have fixed this but it isn't released yet: [commit](https://github.com/ipython/traitlets/commit/58ee9fb1ac36ca8115a2251653aefd365f038d58). I'll just use `# type: ignore` for now since I'm not going to bother with install from the repo directly. Thank you for your help Eric.
