### ISSUE TITLE
Variable (with type hint) from external library is marked as unknown

### ISSUE THREAD

**Issue by binh-vu** [microsoft/pylance-release#4091]
## Environment data

-   Language Server version: 2023.3.20 (pyright 93a4ef87)
-   OS and version: MacOS 12.6.3 / Centos 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.15 (Anaconda 2022.10)

## Code Snippet

```python
import numpy as np
from nptyping import NDArray, Shape
from nptyping.typing_ import Float64

class Test:
    a: NDArray[Shape["*"], Float64]
```

For the above code, Pylance warns me that usage of variable is not allowed because it's not type alias (see the following image).

<img width="770" alt="image" src="https://user-images.githubusercontent.com/4346739/225747513-6b5d4277-d49f-4e9d-a9ad-3b755c3795be.png">

However, the package (nptyping == `2.5.0`, numpy == `1.24.2`, typing-extensions == `4.5.0`) has annotated that the variable Float64 is a typed alias in`nptying.typing_.pyi`: `Float64: TypeAlias = np.dtype[np.float64]`. When I open the file `npyting.typing_` and hover over the variable `Float64`, I did see Pylance recognizes it as type alias. However, when I hover over the imported variable `Float64` in my test code, it shows the type Unknown (see the image below)

<img width="457" alt="image" src="https://user-images.githubusercontent.com/4346739/225748420-e9baa599-3daa-43da-94d2-16b0cd52047b.png">

I check the content of `nptyping` and see that they have `py.typed` file.

## Expected behavior

`Float64` is recognized as correctly as type alias

## Actual behavior

`Float64`'s type is unknown

## Logs

I checked the logs in the output and see no error. Here are some of the logs.

```
(91029) Background analysis message: getDiagnosticsForRange
(91029) Background analysis message: getDiagnosticsForRange
(91029) Background analysis message: getSemanticTokens full
(91029) [BG(1)] getSemanticTokens full at /Users/rook/workspace/pylance-bug/.venv/lib/python3.9/site-packages/nptyping/typing_.pyi (15ms)
(91029) Background analysis message: analyze
(91029) [BG(1)] analyzing: /Users/rook/workspace/pylance-bug/.venv/lib/python3.9/site-packages/nptyping/typing_.pyi ...
(91029) [BG(1)]   checking: /Users/rook/workspace/pylance-bug/.venv/lib/python3.9/site-packages/nptyping/typing_.pyi (2ms)
(91029) [BG(1)] analyzing: /Users/rook/workspace/pylance-bug/.venv/lib/python3.9/site-packages/nptyping/typing_.pyi (2ms)
(91029) Background analysis message: resumeAnalysis
(91029) Background analysis message: getDiagnosticsForRange
(91029) Background analysis message: getDiagnosticsForRange
```

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported. Are you able to repro this with a fresh virtual environment?

Please make sure that you don't have an old version of `type_extensions-stubs` installed in your Python environment.

**Comment by binh-vu** [comment]
This is the information of my environment.

OS: `Centos 7`
Python: `3.9.13` (from Anaconda3)

Test code: https://github.com/binh-vu/pylance-4091

Script that I used to create the environment (running in the project root directory):

```bash
python -m venv .venv
source .venv/bin/activate
pip install nptyping==2.5.0 numpy==1.24.2
```

Installed packages in the environment:
```
>>> pip freeze
nptyping==2.5.0
numpy==1.24.2
typing_extensions==4.5.0    
```

Select Python Interpreter in VSCode to be at `./.venv/bin/python`.

Current VSCode version: `1.76.2`. Pylance version: `v2023.3.30`. Type checking mode: basic. Diagnostic Mode: openFilesOnly.

Please let me know what else I can do to help reproduce the problem on your end. I just tested on another VM and the problem is still there.

**Comment by erictraut** [comment]
I was able to repro the problem.

The issue is in the `nptying` package, not in pylance. The `nptyping` package includes a type stub file called `nptyping/typing_.pyi`. It contains the following problematic code:

```python
try:
    from typing import (  # type: ignore[attr-defined] # pylint: disable=unused-import
        Dict,
        TypeAlias,
    )
except ImportError:  # pragma: no cover
    from typing_extensions import (
        TypeAlias,
    )
```

A type stub file should _never_ contain a `try` block because type stubs are not executable. They are meant solely for static type definitions, so `try`/`except` statements make no sense in a type stub file. It should simply import from `typing_extensions` rather than attempting to import from `typing`. That is, it should be changed to the following:

```python
from typing import Dict
from typing_extensions import TypeAlias
```

Pyright (the type checker that pylance is built upon) is a static type checker, so it cannot determine whether an error will be raised at runtime. When it sees an import statement within a `try`/`except` block, it always assumes that the one in the `try` block will succeed and the one in the `except` block will be unnecessary. In this case, that means it is assuming that the symbol `TypeAlias` will come from the `typing` module. However, the `typing.pyi` stub doesn't define `TypeAlias` for Python 3.9, so this symbol is undefined.

There's not much we can do to work around this problem. The maintainers of `nptyping` will need to fix the problem in their package. Please report the problem to them so they are aware of it.

In the meantime, the only workaround I can offer you is to switch to Python 3.10 or configure Pylance such that it thinks you're using Python 3.10. You can do this by setting the `pythonVersion` to "3.10" in a `pyrightconfig.json` or `pyproject.toml` file. For more details, refer to the [pyright documentation](https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options).

**Comment by binh-vu** [comment]
Thanks so much for the detailed explanation. I overlooked the try/catch block. I learned something useful today!
