### ISSUE TITLE
Introspecting Enumerations?

### ISSUE THREAD

**Issue by Shapedsundew9** [microsoft/pylance-release#4099]
<h3> Issue </h3>
Not sure if this is a bug, feature request or out of scope...
In the image below I could expect pylance to know Indices.A is Literal['0'] and thus 'a' is type Literal[1] rather than the union of types in the tuple. If I replace Indices.A in the assignment expression to the literal '0' it does that. 
The makes a use case of IntEnum unwieldy with the static type checking.

![image](https://user-images.githubusercontent.com/16618209/225976246-b1b3fd6c-09e4-4768-b5e8-e717345c8f3c.png)
<h3> Environment data </h3>

-   Language Server version: 2023.3.23
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from enum import IntEnum

class Indices(IntEnum):
    """Doc string"""
    A = 0
    B = 1


data: tuple[int, str] = (1, 'b')
A1 = data[Indices.A]  # Literal[1, 'b']
A2 = data[0] #  Literal[1]
```

<h3> Expected behavior </h3>

A1 is determined as of type Literal[1]

<h3> Actual behavior </h3>

A1 is determined as of type Literal[1, 'b']

<h3> Logs </h3>
```
[Info  - 11:44:29] (260690) Pylance language server 2023.3.23 (pyright 0997c335) starting
[Info  - 11:44:29] (260690) Server root directory: /home/shapedsundew9/.vscode/extensions/ms-python.vscode-pylance-2023.3.23/dist
[Info  - 11:44:29] (260690) Starting service instance "scratch"
[Info  - 11:44:29] (260690) Auto-indent enabled
[Info  - 11:44:29] (260690) No configuration file found.
[Info  - 11:44:29] (260690) No pyproject.toml file found.
[Info  - 11:44:29] (260690) Setting pythonPath for service "scratch": "/home/shapedsundew9/Projects/venv/bin/python3"
[Warn  - 11:44:29] (260690) stubPath /home/shapedsundew9/Projects/scratch/typings is not a valid directory.
[Info  - 11:44:29] (260690) Assuming Python version 3.11
[Info  - 11:44:29] (260690) Assuming Python platform Linux
[Info  - 11:44:29] (260690) Searching for source files
[Info  - 11:44:29] (260690) Found 1 source file
[Info  - 11:44:30] (260690) Background analysis(1) root directory: /home/shapedsundew9/.vscode/extensions/ms-python.vscode-pylance-2023.3.23/dist
[Info  - 11:44:30] (260690) Background analysis(1) started
[Info  - 11:44:31] (260690) Indexer background runner(2) root directory: /home/shapedsundew9/.vscode/extensions/ms-python.vscode-pylance-2023.3.23/dist (index)
[Info  - 11:44:31] (260690) Indexing(2) started
[Info  - 11:44:32] (260690) scanned(2) 174 files over 1 exec env
[Info  - 11:44:35] (260690) [IDX(2)] Long operation: index execution environment /home/shapedsundew9/Projects/scratch (3739ms)
[Info  - 11:44:35] (260690) [IDX(2)] Long operation: index packages /home/shapedsundew9/Projects/scratch (3771ms)
[Info  - 11:44:35] (260690) indexed(2) 123 files over 1 exec env
[Info  - 11:44:35] (260690) Indexing finished(2).
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is able to make the inference if you use `Indices.A.value` as the subscript for `data`. When you use `Indices.A`, the type of the subscript is not `Literal[0]` but rather `Literal[Indices.A]`. The reason this happens to work at runtime is because `IntEnum` happens to contain an `__int__` method that returns the associated value, but a type checker has no knowledge of this internal logic. Such knowledge would need to be special-cased specifically for the `IntEnum` class. Generally, we don't includes such special-case knowledge in the type checker because maintaining such knowledge for all stdlib classes wouldn't be feasible. We could add it in this particular case if there is sufficient demand, but my sense is that this is a very specialized and uncommon use case. Note that other type checkers like mypy do not handle this case either.

My recommendation is to use `Indices.A.value` if you want the additional type narrowing to apply here.

**Comment by Shapedsundew9** [comment]
Thank you for the explanation & path forward. That makes sense.

**Comment by Gobot1234** [comment]
> The reason this happens to work at runtime is because `IntEnum` happens to contain an `__int__` method that returns the associated value, but a type checker has no knowledge of this internal logic. 

This isn't strictly true, all IntEnum members are actually subclasses of `int`.
```py
In [1]: from enum import IntEnum
   ...: 
   ...: class Indices(IntEnum):
   ...:     """Doc string"""
   ...:     A = 0
   ...:     B = 1
   ...: 

In [2]: isinstance(Indices.A, int)
Out[2]: True

In [3]: Indices.A.__class__.__mro__
Out[3]: (<enum 'Indices'>, <enum 'IntEnum'>, int, <enum 'Enum'>, object)
```
