### ISSUE TITLE
Problems Stay on List After Closing Jupyter Interactive Window

### ISSUE THREAD

**Issue by jshtz4** [microsoft/pylance-release#4113]
<h3> Environment data </h3>

-   Language Server version: 2023.3.20
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Repro Steps </h3>

1. Open VS Code
2. Run Jupyter: Create Interactive Window
3. Enter and run any code that will generate an error such as: print(my_undefined_var)
4. Close Interactive Window
5. Pylance error for Interative-1.interactive remains in the Problem list even though window was closed.

<h3> Expected behavior </h3>

When an interactive window is closed, errors associated with that window should be removed.

<h3> Actual behavior </h3>

Errors stay on problem list.

<h3> Logs </h3>

[pylance.log](https://github.com/microsoft/pylance-release/files/11022568/pylance.log)

**Comment by heejaechang** [comment]
tagging @debonte

**Comment by debonte** [comment]
This is already fixed in our most recent prerelease build.

The problem was that we were relying on `textDocument/didClose` to call `setFileClosed` for notebook cells. For normal notebooks, the `textDocument/didClose` messages are received before the notebook's workspace is destroyed on `notebookDocument/didClose`. But for interactive windows the `notebookDocument/didClose` is received first. So when we later receive the `textDocument/didClose` messages for the cells, we can no longer find `SourceFileInfo` objects for them.

I'm not sure if/when this changed. But the recent notebook workspace changes including calling `setFileClosed` from the `notebookDocument/didClose` handler.
