### ISSUE TITLE
Incorrect error report on type of self being incompatible with any other type inside a collection.

### ISSUE THREAD

**Issue by MischaPanch** [microsoft/pylance-release#4126]
Pylance complains about the type of self being incompatible with any other type inside a collection.

Interestingly, implementing the return as  `return [self, other]` in the code snippet below doesn't trigger an error.

Since this is an error of  `reportGeneralTypeIssues`, I cannot simply disable it in settings

## Environment data

-   Language Server version: v2023.3.20
-   OS and version: Windows 11 and Ubuntu
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Code Snippet

```python

class A:
    def list_of_A(self, other: "A") -> list["A"]:
        result = [self]
        return result + [other]

```

## Expected behavior

No error

## Actual behavior

General typing error:

```
Expression of type "list[Self@A]" cannot be assigned to return type "list[A]"
  "list[Self@A]" is incompatible with "list[A]"
    TypeVar "_T@list" is invariant
      Type "Self@A" cannot be assigned to type "A"Pylance[reportGeneralTypeIssues]
```

## Logs

```
XXX
```

**Comment by erictraut** [comment]
This error is correct. The variable `result` has no type declaration (i.e. annotation), so its type is inferred. In this case, the inferred type is `list[Self@list_of_A]`. Because the `list` class is invariant, it doesn't allow you to append values of other types onto the list.

The way to handle this without generating a type violation error is to add a type declaration for the variable `result`.

```python
class A:
    def list_of_A(self, other: "A") -> list["A"]:
        result: list[A] = [self]
        return result + [other]
```

For more details about type declarations and type inference, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts).

If you are not interested in seeing any static type errors in your code, you can disable type checking by setting `python.analysis.typeCheckingMode` to "off".

**Comment by MischaPanch** [comment]
> This error is correct. The variable `result` has no type declaration (i.e. annotation), so its type is inferred. In this case, the inferred type is `list[Self@list_of_A]`. Because the `list` class is invariant, it doesn't allow you to append values of other types onto the list.
> 
> The way to handle this without generating a type violation error is to add a type declaration for the variable `result`.
> 
> ```python
> class A:
>     def list_of_A(self, other: "A") -> list["A"]:
>         result: list[A] = [self]
>         return result + [other]
> ```
> 
> Alternatively, if you want your function to handle subclasses of `A`, you could change it to the following:
> 
> ```python
> from typing import Self
> 
> class A:
>     def list_of_A(self, other: Self) -> list[Self]:
>         result = [self]
>         return result + [other]
> ```
> 
> For more details about type declarations and type inference, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts).
> 
> If you are not interested in seeing any static type errors in your code, you can disable type checking by setting `python.analysis.typeCheckingMode` to "off".

Thank you for the detailed answer! I knew about `Self` but since it's only a part of python 3.11, I was surprised that the inferred type was `list[Self@A]`. In any case, you proposal with the explicit type declaration works, even if it's a bit more verbose
