### ISSUE TITLE
Auto-complete suggestions includes overloaded methods that aren't valid for current object

### ISSUE THREAD

**Issue by siddhant3s** [microsoft/pylance-release#4146]
<h3> Environment data </h3>

-   Language Server version: 2023.3.20
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/295892/227652086-f5ac21e6-4767-4c44-aab0-6490d67e2f3d.png">
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/295892/227652167-43bb4db7-9b2b-49c8-a4c4-02e18e792439.png">

```python
from dataclasses import dataclass
from typing import Any, Generic, TypeVar, overload

@dataclass
class Student:
    s_name: str
    s_age: int

@dataclass
class Class:
    c_name: int
    c_duration: int

T = TypeVar("T")
class Q(Generic[T]):
    def __init__(self, inner: T):
        self.inner = inner
     # For Student
    @overload
    def name(self: "Q[Student]") -> "Q[str]":
        ...
    # For Class
    @overload
    def name(self: "Q[Class]") -> "Q[int]":
        ...
    # Impl
    def name(self) -> Any:
        ...
    
    # For Student
    def age(self: "Q[Student]") -> "Q[int]":
        ...

    # For Class
    def duration(self: "Q[Class]") -> "Q[int]":
        ...
    

s: Q[Student] = Q(Student("", 0))
c: Q[Class] = Q(Class(1, 1))
s.duration() # Type error, but auto-complete shows suggestion
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

Auto-complete suggestions shouldn't include `duration` for `s.` and it should not include `age` for `c.`

<h3> Actual behavior </h3>

Auto-complete suggestions includes `duration` for `s.` and `age` for `c.`

<h3> Logs </h3>

```
(58511) Background analysis message: setFileOpened
(58511) Background analysis message: markFilesDirty
(58511) [FG] completion at /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py:55:2 ...
(58511) [FG]   parsing: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (1ms)
(58511) [FG]   binding: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (0ms)
(58511) [FG] completion at /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py:55:2 [found 26 items] (17ms)
(58511) Background analysis message: analyze
(58511) [BG(1)] analyzing: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py ...
(58511) [BG(1)]   parsing: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (2ms)
(58511) [BG(1)]   binding: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (1ms)
(58511) [BG(1)]   checking: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (11ms)
[Info  - 3:13:01 PM] (58511) Heap stats: total_heap_size=87MB, used_heap_size=77MB, total_physical_size=82MB, total_available_size=4015MB, heap_size_limit=4096MB
(58511) [BG(1)] analyzing: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (14ms)
(58511) Background analysis message: getDiagnosticsForRange
(58511) Background analysis message: resumeAnalysis
(58511) [BG(1)] indexing: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py [found 6] (0ms)
(58511) Indexing Done: /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py
[Info  - 3:13:01 PM] (58511) Heap stats: total_heap_size=87MB, used_heap_size=78MB, total_physical_size=82MB, total_available_size=4015MB, heap_size_limit=4096MB
(58511) Background analysis message: getDiagnosticsForRange
(58511) Background analysis message: getSemanticTokens delta
(58511) [BG(1)] getSemanticTokens delta previousResultId:1679695971829 at /Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py (13ms)
(58511) Background analysis message: getDiagnosticsForRange
(58511) Background analysis message: getDiagnosticsForRange
(58511) Background inlayHint message
[Info  - 3:13:03 PM] (58511) SourceFile: Received fs event 'change' for path '/Users/ssanyam/projects/try_pyq/repro-overload-autocomplete.py'
(58511) Background analysis message: markFilesDirty
(58511) Background analysis message: analyze
```

**Comment by erictraut** [comment]
This is by design. Auto-complete suggestions do not take into account type details like this. Doing so would be cost prohibitive and would significantly extend the time it takes to display the completions list. We attempt to display completions in under 500ms in most cases, but performing type analysis for all of them as an additional filter would extend this time to second or tens of seconds in many cases.

It's very unusual to have overloads that annotate the `self` parameter. This is arguably an anti-pattern because a generic class shouldn't vary its behavior depending on its type arguments. So I think this pattern is quite rare and arguably should not be used. In any case, it would be a bad tradeoff to slow down completion suggestions for all common cases just to support this case.

**Comment by siddhant3s** [comment]
There are many instances where one wants to control the methods that are available on `self`. This is well documented in mypy's [documentation](https://mypy.readthedocs.io/en/stable/more_types.html#restricted-methods-in-generic-classes). 
NOTE: I've updated the issue to use this smaller repro instead of my larger one.

Now I can't argue how common or uncommon its use is, but I won't be so quick to conclude it to be an anti-pattern. There is a lot of healthy discussion on the PR that implements it in [MyPy](https://github.com/python/mypy/commit/673468cfc3d9f85f026983b264ee5e71d8dae47e). If you want, I can give many motivating examples where this is useful. Overall, this helps in shaping up the ergonomics of the generic class specially when defining an algebra (say when using interpreter pattern). 

Pragmatically speaking, I understand that filtering out these suggestions **might** cause a regression to the latency. I commend your focus on keeping the e2e latency in check. What I was really hoping for is if you could speak a bit more about what is the reasons this might regress the latency. I'm not skeptical to what you're saying, I am trying to get more details. 
For example, one thing I notice is that there is an additional box on the right that shows "undefined". Which means at the end of the rendering, the system has information about this suggestion not having a definitive type. When I use my arrow-keys to move up and down the suggestions, I don't see any activity on the LSP's logs (I've set it to Trace). This strongly suggest that the information which is being rendered on the right box is already fetched before showing all the suggestions. From which I hesitantly deduce that doing a filtering at that point wouldn't involve any fetches. I'll admit I haven't looked into the codebase yet. If you think my reasoning is sound I can make an attempt in doing so.
There are already few settings in Pylance that trades off latency vs richer/correct suggestions (eg: `python.analysis.autoImportCompletions`) which are off by default. This can potentially have a similar setting. Though I understand if you are trying to keep the list of settings small.

Ultimately, I'm trying to understand if you think we should not do it because it will increase the latency, or is it that there isn't really any appetite for this kind of coding pattern. Another way to ask that question would be, if this fix doesn't end up regressing latency, would you be supportive of the change (given that use case might not be that unusual).

**Comment by erictraut** [comment]
> Ultimately, I'm trying to understand if you think we should not do it because it will increase the latency, or is it that there isn't really any appetite for this kind of coding pattern.

The main reason is that it would _greatly_ increase the latency. This isn't a question of _might_. It definitely would. We have a lot of experience with this because we've spent a lot of time trying to reduce the latency. It's a metric we track closely, and we are always looking for ways to shave a few additional milliseconds off the average latency.

Even if it increased the average latency only slightly, the fact that this is not a common pattern (and is arguably an anti-pattern) would make this a bad tradeoff.

The reason this greatly increases the latency is that the list of completions is generated directly from the symbol table of the class on the LHS of the member access expression. The types of a symbol in the completion suggestion list is not evaluated until you select the item in the list. The type of that symbol is then lazily computed so it can be displayed in the secondary tooltip.

**Comment by erictraut** [comment]
If the file that defines the class is open in your editor, its types will already be evaluated and cached in memory. This is not guaranteed to be the case (and is often not true) when requesting completion suggestions. The class is often defined in another module that is not currently open, and its types need to be evaluated on demand because they are not cached.
