### ISSUE TITLE
import github (MissingImports) error

### ISSUE THREAD

**Issue by toughjay318** [microsoft/pylance-release#4164]
I have been attempting to get my new code to read repositories from Github directly, but when I use the function:

"""
from github import Github

"""
I continue to receive an error message stating either: 

" ModuleNotFoundError: No module named 'github' "

or 

"Import "github" could not be resolved Pylance[reportMissingImports]"

Could anyone please assist me in fixing this issue?!!

**Comment by rchiodo** [comment]
Thanks for the issue.

Can you include the logging output as discussed here:

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

The directories we searched for that site-package should be listed in the log if you turn on the trace log level.

**Comment by toughjay318** [comment]
how do I exactly turn on trace log? I have never heard of that or understand the reasoning

**Comment by rchiodo** [comment]
The directions in the link should describe how to turn it on.

**Comment by toughjay318** [comment]
Im sorry I don't follow. It says to add the command to my " settings.json configuration file." , and I am not familiar with that file or where it could be. Please help? IS this the only way to help with the import Github action line?

**Comment by rchiodo** [comment]
Yes, sorry we need the log in order to diagnose what might be going wrong.

Settings.json is accessible by hitting CTRL+SHIFT+P and then picking 'Open Users Setttings.json'

![image](https://user-images.githubusercontent.com/19672699/228633631-363b68ce-c107-4c0a-92f4-0ec1dc6c8959.png)

It's a json file that contains all of your settings that aren't the same as the default. VS code has more information here:
https://code.visualstudio.com/docs/getstarted/settings

Once you add the `"python.analysis.logLevel": "Trace",`, then this output tab should show a bunch of information:

![image](https://user-images.githubusercontent.com/19672699/228634175-3720628d-334c-4fe9-9441-c5ce72b40dd6.png)

**Comment by toughjay318** [comment]
Once I try to add it to file it says this: 

"This setting cannot be applied because it is not registered as language override setting."

**Comment by rchiodo** [comment]
It should look like this:

```json
{
  "python.analysis.logLevel": "Trace",
}
```

**Comment by rchiodo** [comment]
You can also do it with the UI:

![image](https://user-images.githubusercontent.com/19672699/228930511-2e631122-f572-40fe-bb61-87f007731634.png)

**Comment by gramster** [comment]
@rchiodo, if I'm not mistaken one of the errors in initial post is not from us but is a runtime error, in which case the user has not installed the needed package in their virtual environment and its not a pylance bug.

@toughjay318, perhaps you did a `pip install github`; that is not the right package, you would want `pip install pygithub`.
