### ISSUE TITLE
Is it possible to have a shared index or change the frequency pylance scans the include list of dirs?

### ISSUE THREAD

**Issue by andrearastelli** [microsoft/pylance-release#4171]
Pylance seems to be quite "intense" in IO operations while the indexing process runs, this is especially relevant when the folders in "python.analysis" contains a very big number of python packages (that are, for the most part, internally developed).

I'm not aware if there is a configuration where we can either limit this stress on the disks, or have a shared index that multiple instances of vscode can point at, or a way to limit at all the frequency used by pylance to rescan and rebuilds the index.

Thanks

**Comment by bschnurr** [comment]
are you seeing indexing after simple edits like adding a space?  the majority of indexing should only happen once at startup.

have you tried the latest pre-release of Pylance v2023.3.41?

currently to turn off indexing we only have 
"python.analysis.indexing": false,

**Comment by andrearastelli** [comment]
I can see that it's constantly looking at the folders listed in "python.analysis" (or my PYTHONPATH, they overlap up to a point).

The packages are "read only" once in those folders, but we release new versions very frequently and we switch between versions using symlinks.

The vast majority of the traffic seems to be related to the symlinks (we have lots of them).


Haven't tried the pre-release of Pylance yet, is there any improvement that may be relevant to this issue? Is there a changelog I could be looking at?

Thanks

**Comment by andrearastelli** [comment]
Hi, 

I've attached the log.
This is a truncated version of the log, 10Mb in size.
If left running, the log would go over 60Mb and it seems Pylance doesn't rotate more than 2 files with a fixed size of 30Mb each, which means I lose the beginning of the log.

Anyhow: I needed to hash the paths and some of the packages we use internally for confidentiality purposes. This shouldn't really affect the log, I think, as the path structure is maintained, and when relevant the python extensions are also maintained.

Let me know if this is of any help.
Thanks

[hashed_vscode_pylance_log.zip](https://github.com/microsoft/pylance-release/files/11124487/hashed_vscode_pylance_log.zip)

**Comment by rchiodo** [comment]
Indexing can be turned off or you can adjust it on a per directory basis. 

```json
"python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "name": "django",
      "depth": 4,
      "includeAllSymbols": true,
    },
    {
      "name" : "libcst",
      "depth": 4,
      "includeAllSymbols": true
    }
  ],
```

Indexing is not cached however, so you can't share it amongst machines.

**Comment by heejaechang** [comment]
@andrearastelli so I looked your log

For `third party library` (packages in site-package including one in virtual env), you can use 

```json
"python.analysis.packageIndexDepths": [
    {
      "name": "<package name>",
      "depth": 0,
    },
    ...
  ]
```

to exclude `package name` from the indexing.

For `user files` (files under workspace.root), we will index up to `2000` files per `workspace` when vscode is started. and then only files that are affected by the change. 

that being said, I see your file io is very slow

```
[Info  - 6:01:14 PM] (28938) [BG(1)] Long operation: parsing: /4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/cc273dcf3e6063adb.py (26298ms)
[Info  - 6:01:14 PM] (28938) [BG(1)] Long operation: parsing: /4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/117426151.py (2583ms)
[Info  - 6:01:14 PM] (28938) [BG(1)] Long operation: parsing: /4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/198ef90e4ea.py (9728ms)
[Info  - 6:01:14 PM] (28938) [BG(2)] Long operation: parsing: /4ea1/80d2d07ab/11a4a6/4c99c877e/1e32/430c5cbcc00853.py (8165ms)

I see 700+ of them from the log.

```

If your file io is this `slow`, I think any `workspace level features` such as indexing, find all reference, global rename, workspace symbols and etc that requires parsing every files in your context would be `un-usable` in your setup. features that require your `explicit request` such as `find all references` or `rename` would be `fine`, but features that would run in BG such as `indexing`, I think it would be better to be turned off.

you can use the setting below to turn it off
```
  "python.analysis.indexing": false
```

**Comment by andrearastelli** [comment]
We have thousands of individual Python packages and we add new ones every week, maintaining a list of depth limits for each individual package is not very practical.
And we do not think the volumes are slow.

With logging disabled we traced the IO operations done by pylance and we have recorded up to ten million operations per minute (average latency under one millisecond) issued for over six thousand different paths.
That number of operations per path combined with your suggestion of limiting the depth of the indexing per package is making us wonder if pylance has an issue with indirect cycling dependencies?
We know for a fact that we have indirect dependency cycles (package A depends on package B that depends on package C that depends on package D that depends on package A...).

Does pylance detect those indirect dependency cycles?
How are they handled?
Does it rely on a depth limit to break the cycles and avoid an infinite indexing loop?
What is the default depth limit?

**Comment by heejaechang** [comment]
For third party libraries, we only scan the top `__init__` by default (depth of 1), so those cycle shouldn't matter. and yes, we do detect those cycle since we use normalized file path to index.

the attached log seems cut out in the middle so we can't be 100% sure, but at least, log has this entry

```
(28938) [IDX(10)] scan packages /4ea1/80d2d07ab/558/a8920649816a (22394ms)
[Info  - 6:02:10 PM] (28938) [IDX(10)] Long operation: scan packages /4ea1/80d2d07ab/558/a8920649816a (22394ms)
[Info  - 6:02:10 PM] (28938) scanned(10) 1427 files over 1 exec env
```

meaning at least one of them (among multiple roots), finished scanning.

> we do not think the volumes are slow.

unfortunately, the log says otherwise (or at least, for things matter to us)

For example, the log shows that, scanning installed package for 1 root took 22 seconds. and log shows at least 9 more roots. if other roots are about the same shape, then it will take total about 180+ seconds. by the way, slowness might not be due to perf of each io, but due to number of files that add up to 180+ seconds.

also, I see over 700 files taking more than 2 seconds to parse.
either those 700 files are quite large or CPU is throttled or IO is slow.

```
[Info  - 6:01:14 PM] (28938) [BG(1)] Long operation: parsing: /4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/cc273dcf3e6063adb.py (26298ms)
[Info  - 6:01:14 PM] (28938) [BG(1)] Long operation: parsing: /4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/198ef90e4ea.py (9728ms)
[Info  - 6:01:14 PM] (28938) [BG(2)] Long operation: parsing: /4ea1/80d2d07ab/11a4a6/4c99c877e/1e32/430c5cbcc00853.py (8165ms)
```

For exmaple, this particular file `/4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/cc273dcf3e6063adb.py (26298ms)` took 26 second to parse. 

...

unless we can have a hand on some kind of live repro, it would be hard for us to find out why things behave this way for you guys.

**Comment by heejaechang** [comment]
> scans thousands of packages millions of times again and again 

the log shows only 1 scan packages, so I can't confirm whether it scanned again and again. unless you worry about github file limit or bandwidth, it would be easier for us to dig in more detail if we get full log to verify that we scanned some packages again and again and if it did, why we did it.

> As we mentioned before, we traced pylance doing millions of readlink operations per minute, again and again for the same packages, up to 200,000 IO operations per second

I think you are asking about disk walking we do. There are various different disk walking we do but ones we do in bulk are 2
1. scanning import roots (site-package and etc) per workspace to find all installed packages (indexing)
2. scanning workspace root per workspace to find all user files (files that meets include/exclude)

we also do disk walking when we resolve import statement but that happen lazily so it shouldn't happen in bulk.

now, you have 7 workspace roots and each workspace's import roots (site-packages and etc) might have overlapping folders but we cache them (unless we dump cache in the middle of walking due to heap limitation of vscode)

so, again, unless we can take a look at the full log, hard to know whether we are visiting same files or not.

> The package that you report took 22 seconds to parse has 87 Python files, less than 5 MB in total.

hmmm. if you are talking about this

> (28938) [IDX(10)] scan packages /4ea1/80d2d07ab/558/a8920649816a (22394ms)
[Info  - 6:02:10 PM] (28938) [IDX(10)] Long operation: scan packages /4ea1/80d2d07ab/558/a8920649816a (22394ms)
[Info  - 6:02:10 PM] (28938) scanned(10) 1427 files over 1 exec env

what it means is we found 1427 files we would consider to index from third party roots (site-packages and etc)

I think what you meant by "87 Python files, less than 5 MB in total" is that workspace has `87` user files under the workspace root?

...

here are other info I can see from log

For the workspace in the log, it has 26 different import roots our scanner need to dig into.
```
[Info  - 5:57:30 PM] (28938) Search paths for /4ea1/80d2d07ab/558/a8920649816a/11a4a6
[Info  - 5:57:30 PM] (28938)   /7cada/90b/4ea1/80d2d07ab/27bf025/20ef7739e8/0b8c2eb00f58285e586beb4ddf054a133f/bcae/04659b664da38b759/6c6838
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/558/a8920649816a/11a4a6
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/558/a8920649816a/${userHome}/python
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/558/a8920649816a/${userHome}/python/_Qt
[Info  - 5:57:30 PM] (28938)   /c1a/241/f6840/b986ae2d5/
[Info  - 5:57:30 PM] (28938)   /c1a/f79d/f6840/b986ae2d5/
[Info  - 5:57:30 PM] (28938)   /c1a/f9d35/f6840/b986ae2d5
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/558/a8920649816a/11a4a6
[Info  - 5:57:30 PM] (28938)   /c1a/f9d35/a95983534f7562083/8285abe475feafe640a2e7f3
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/a5d2f2/76b/b986ae2d5/14cb5cd8791d7
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/11a4a6
[Info  - 5:57:30 PM] (28938)   /4ea1/80d2d07ab/558/a8920649816a/8187df0
[Info  - 5:57:30 PM] (28938)   /7cada/90b/4ea1/80d2d07ab/27bf025/20ef7739e8/0b8c2eb00f58285e586beb4ddf054a133f/bcae/04659b664da38b759/1b101/ab5
[Info  - 5:57:30 PM] (28938)   /7cada/90b/4ea1/80d2d07ab/27bf025/20ef7739e8/0b8c2eb00f58285e586beb4ddf054a133f/bcae/4c4164b/1b101
[Info  - 5:57:30 PM] (28938)   /7cada/90b/4ea1/80d2d07ab/27bf025/20ef7739e8/0b8c2eb00f58285e586beb4ddf054a133f/bcae
[Info  - 5:57:30 PM] (28938)   /7cada/90b/4ea1/80d2d07ab/a5d2f2/76b/b986ae2d5/14cb5cd8791d7
[Info  - 5:57:30 PM] (28938)   /7cada/90b/4ea1/80d2d07ab/11a4a6
[Info  - 5:57:30 PM] (28938)   /7cada/90b/c1a/a7e04/e73c/45066dd/f6840/b986ae2d5
[Info  - 5:57:30 PM] (28938)   /usr/lib64/python3.7
[Info  - 5:57:30 PM] (28938)   /usr/lib64/python3.7/lib-dynload
[Info  - 5:57:30 PM] (28938)   /7cada/90b/c1a/a7e04/241/f6840/b986ae2d5
[Info  - 5:57:30 PM] (28938)   /7cada/90b/c1a/a7e04/241/f6840/b986ae2d5/4612828a/90b#72.0
[Info  - 5:57:30 PM] (28938)   /7cada/90b/c1a/a7e04/f79d/f6840/b986ae2d5
[Info  - 5:57:30 PM] (28938)   /7cada/90b/c1a/a7e04/f9d35/f6840/b986ae2d5
[Info  - 5:57:30 PM] (28938)   /usr/lib64/python3.7/site-packages
[Info  - 5:57:30 PM] (28938)   /usr/lib/python3.7/site-packages
```

and the workspace has 216,486 user files
```
[Info  - 5:57:30 PM] (28938) Searching for source files
[Error - 5:57:40 PM] (28938) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
[Info  - 5:58:22 PM] (28938) Found 216486 source files
```
among which, we will parse 2,000 files.

and assuming you have 8 more of these workspace with similar shape, we would dig in about 240 folders to find third party packages and discover 1.8M files and parse 18K files up front.

...

anyway, did you try to turn off `indexing` and see whether it improves `parse` time such as this? `/4ea1/80d2d07ab/558/a8920649816a/11a4a6/a8920649816a/cc273dcf3e6063adb.py (26298ms)`

even after turning off `indexing`, we would spend time to discover 1.8M files though.

**Comment by heejaechang** [comment]
you said `87 Python files, less than 5 MB in total` but log says `Found 216486 source files` so I wonder whether our default `include/exclude` doesn't work for your environment. try to set `include/exclude` explicitly in your `workspace settings file`, `pyrightconfig.json` or `pyproject.toml`. so we don't dig into folders that won't contain any user files.

**Comment by andrearastelli** [comment]
While looking at the logs we've found this particular message hundreds of times:
```text
FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
[Info  - 11:12:16 AM] Connection to server got closed. Server will restart.
```
and we were wondering if this could be Pylance running out of memory and restarting again again.

I'll be running more tests with `pyrightconfig.json` configured, but we've noticed that the logs behave in a strange way:
- they seems to be rotating with size up to 30Mb
- the rotation keeps only 2 logs at any given time: `#-Python Language Server.log` and `#-Python Language Server.1.log`

This means, like in our case, that if the log generated grows above 60Mb, we're not gonna get the beginning of the log.

Also, if pylance restarts again and again because goes out of memory, would that mean the log will grow indefinitely?

**Comment by heejaechang** [comment]
ya, it sounds like your case is above our max threshold. and it looks like your environment is above what `vscode` can handle (more specifically, what `electron` can handle - electron has a physical heap max limit of 4GB in 64bit OS - https://www.electronjs.org/blog/v8-memory-cage)

so, does your environment really need 1.8M user files? I am asking since a lot of these kinds of cases, user had `symlinks` to some random folders `outside` of `workspace root` under some random folders under `workspace root` that contained bunch of random py files laying around in the drive and due to naive default `include/exclude` (which says include every `py` and `pyi` files under workspace root), it discovered them all. 

most of cases, user could cut out unnecessary files, that are usually almost all of them, reducing number files to bring into memory dramatically.

if you really need those 1.8M files, only way I can think of right now is using a trick to use regular nodejs that has no pointer compression turned on so you can use full 64bit memory space. but that being said, I am not sure how much it will be useful except it won't OOM.

the trick is using `remote vscode` with this option `export NODE_OPTIONS="--max-old-space-size=<memory in MB>"` as described here (https://github.com/microsoft/pylance-release/issues/4121#issuecomment-1479713013). that will make vscode to use regular `nodejs` with max heap limit of `memory in MB` 

another way is rather than opening `folders`, just open a file without it so it doesn't bring in files for workspace side features such as `indexing`, `rename` and etc

but that being said, I think better way is just removing unnecessary files using `include/exclude` options.
