### ISSUE TITLE
"code is unreachable" doesn't trigger for 'if 0'

### ISSUE THREAD

**Issue by jleclanche** [microsoft/pylance-release#4175]
![image](https://user-images.githubusercontent.com/235410/229010719-9821291e-e30d-4d69-ab72-cd3196328367.png)

## Environment data
Pylance language server 2023.3.30 (pyright 68a8e98a) - WSL

## Code Snippet

```python
# works
if False:
    print("Hello world")

# doesn't work
if 0:
    print("Hello world")

# doesn't work
if "":
    print("Hello world")

```

**Comment by erictraut** [comment]
This is by design. Pyright (the static type checker upon which pylance is built) honors only certain static expression forms for determining whether code is reachable. This includes expression forms specified in PEP 484 such as `if TYPE_CHECKING:`, `if sys.version_info >= (3, 8):`, and `if False:`. It does not include `if 0:`, `if 1 < 2:`, etc.
