### ISSUE TITLE
Pylance crash when autocompleting aws_cdk

### ISSUE THREAD

**Issue by panilo** [microsoft/pylance-release#4241]
Pylance crash when trying to use autocompletion on `aws_cdk` library 

## Environment data

-   Language Server version: 2023.4.20 (pyright 64a33975)
-   OS and version: MacOS 13.2.1 (22D68)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16

## Code Snippet

```python
from aws_cdk import ...
```

## Repro Steps

1. Create a new python file 
2. import a package from `aws_cdk` (`from aws_cdk import ...`)
3. Press ctrl + space to open the autocompletion 

## Expected behavior

Pylance show autocompletion tips 

## Actual behavior

Python language server crash

## Logs

[logs.txt](https://github.com/microsoft/pylance-release/files/11231281/logs.txt)

**Comment by panilo** [comment]
PS as a temporary fix I added to my `.bashrc` `export NODE_OPTIONS="--max-old-space-size=8192` and it seems to fix the issue, though performance is quite bad, with autocompletion slow to open.

**Comment by bschnurr** [comment]
what is the pip install command for `aws-cdk`

**Comment by bschnurr** [comment]
looks like we are spending a lot of time index.

you can turn that off with
"python.analysis.indexing": true,

but you'll loose some auto import features.

**Comment by panilo** [comment]
> what is the pip install command for `aws-cdk`

`pip install aws-cdk-lib`

**Comment by bschnurr** [comment]
ok. seeing this now with this example
```python
from aws_cdk import App, Stack
from aws_cdk.aws_s3 import Bucket


app = App()
stack = Stack(app, "TestStack")
```

**Comment by erictraut** [comment]
This library exports over 80K symbols. Only 533 are exported from the top-level module (`aws_cdk`), but almost all of these symbols are defined in submodules which tend to import them from other submodules, etc. This means pyright needs to parse and bind 240 files when providing completions for the partial statement `from aws_cdk import `. The main reason it needs to do this is to determine the symbol class for each symbol, which allows it to display the proper icon in the completion suggestion list. It does this by `resolveAliasDeclaration` for each imported symbol within the `_addSymbol` method in the completion provider. This causes pyright to parse and bind the file that the alias declaration (i.e. import) targets, and it does this recursively until it's able to determine the original (non-alias) declaration for the symbol. Ideally, the code wouldn't need to do this until the user chooses that item from the completion list, at which time the symbol could be resolved and its type determined.

I can see a couple of potential solutions to this problem:
1. We could not resolve alias declarations in the completion provider. Or we could optionally not resolve them specifically when adding completion suggestions for import statements. This has the benefit of greatly speeding up completion suggestions in some cases and will avoid the heap exhaustion when importing from large packages, but it will result in incorrect (module) icons in the completion suggestion list for imported symbols.
2. If we continue to resolve alias declarations in the completion provider as we do today, we need to make sure that in the inner loop for the `_addSymbolsForSymbolTable` method, we should expose a method from the `program` module that calls through to the evaluator's `resolveAliasDeclaration` function but also calls `_handleMemoryHighUsage` so it can deal with low-memory situations and depopulate the caches if necessary. This should avoid the heap exhaustion issue and otherwise preserve the current behavior of the completion provider, but it won't improve performance in any way.

**Comment by erictraut** [comment]
Another interesting point to note is that the main `__init__.py` file in the `aws_cdk` package is 1.5MB in size and contains 30675 lines of code! It takes 1220ms to parse this file on my computer. Once it's parsed, the results are cached in memory, but the initial parsing does take enough time that it's noticeable on the first completion request even if we don't resolve any of the alias declarations for its exported symbols.

**Comment by bschnurr** [comment]
I wonder if stub generation might help

**Comment by erictraut** [comment]
Stub generation probably won't help much in addressing the performance or heap exhaustion crash. This is a "py.typed" library, and it's well annotated. Stubs might reduce the parse time somewhat, but they wouldn't eliminate the need to parse and bind 240 modules.

BTW, here's the `pyright --verifytypes aws_cdk` report on this library:

```
Symbols exported by "aws_cdk": 80097
  With known type: 54124
  With ambiguous type: 0
  With unknown type: 25973
  Functions without docstring: 210
  Functions without default param: 12
  Classes without docstring: 6100

Type completeness score: 67.6%
```

**Comment by bschnurr** [comment]
yup. didn't help

**Comment by panilo** [comment]
Hello, is there any update on this? The issue is still persisting on the version `v2023.5.10`

**Comment by heejaechang** [comment]
we will put some threshold how many items in the completion we will `resolve` for `icon`. this will make sure we won't exhaust all memory just to figure out what icon we need to show.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023621-14-June-2023-PreRelease)

**Comment by heejaechang** [comment]
@BwL1289 if it still happens, then what you are experiencing is probably not the same issue. please open new issue and attach `full log` so we can take a look. thank you.

**Comment by aracg** [comment]
I have a similar problem on Pylance v2023.12.1 https://github.com/microsoft/pylance-release/issues/5440
