### ISSUE TITLE
Type highlighting for dynamic type variables

### ISSUE THREAD

**Issue by alecglen** [microsoft/pylance-release#4245]
It seems ideal that a variable guaranteed to be a type should be highlighted as such (green in this example).

![image](https://user-images.githubusercontent.com/28493454/232160855-ae7ad3b2-6613-4804-9cd7-039ddd68c045.png)

I'm still learning - feel free to explain why blue is correct, or if this pattern is a bad idea in general.

**Comment by debonte** [comment]
`c` is a variable. It will be assigned either `int` or `str` after line 3 at runtime, but it's still a variable. For example, it can be reassigned:

```python
c = int if random() > .5 else str
c = 5
```

> if this pattern is a bad idea in general.

What are you planning to do with `c` later in your code?

**Comment by alecglen** [comment]
`int` and `str` were an oversimplification; really they are two classes with nearly identical attributes. My goal was to make a helper type that was a little smarter than just a union, but your comment made me realize it doesn't work that way since the check only happens at runtime.

If I replace it with `C = A | B`, it still doesn't seem to work how I'd expect. Both A and B have a class attribute `_id`, but referencing `C._id` gives me a Pylance error 'Cannot access member "_id" for type "object". Member "_id" is unknown.'

**Comment by erictraut** [comment]
The statement `C = A | B` (if found in module-level scope) will be interpreted by a type checker as a type alias, and `C` can now be used in a type annotation to represent the union. You'll notice if you hover over `C`, pylance will tell you that it is a "type alias". The statement `C = A | B` creates an object at runtime that is an instance of the internal type `UnionType` which represents the union. You can't access `_id` from this object.

```python
class A:
    _id = 0

class B:
    _id = 1

C = A | B

print(type(C))  # UnionType
print(C)  # __main__.A | __main__.B
print(A._id)  # 0
print(B._id)  # 1
print(C._id)  # AttributeError: 'types.UnionType' object has no attribute '_id'
```

If you have a type alias called `C`, you can use it in a type annotation like the following:
```python
my_var: C = A if random() > 0.5 else B
```

Note that `C = A | B` is very different from `C = A if random() > 0.5 else B`. The latter defines a variable, not a type alias. Its inferred type is `type[A] | type[B]`. At runtime, this variable refers to either the class `A` or the class `B` (or anything else you happen to assign to it later, since the Python runtime doesn't enforce static types).

**Comment by alecglen** [comment]
Thanks for the detailed explanation! That distinction between the UnionType and the runtime-evaluated class helped it click for me.
