### ISSUE TITLE
Misleading "reportMissingImports" 

### ISSUE THREAD

**Issue by mayrholu** [microsoft/pylance-release#4265]
Pylance marks module as missing even if guarded with try ... except ModuleNotFoundError. 

## Environment data

SuSE Linux SLE15
vscode 1.77.3
Pylance 2023.4.10
Python 3.11.0

## Code Snippet

```python
try:
    import numba
except ModuleNotFoundError:
    _NUMBA = False
else:
    _NUMBA = True
```

## Repro Steps

Open code snippet in vscode and wait for Pylance to underline "import numba".

## Expected behavior

No Pylance notification since missing module already handled. (compare pylint behavior)

## Actual behavior

reportMissingImports from Pylance

Please let me know if you need more info.

**Comment by erictraut** [comment]
This behavior is as designed. If the module is not found, it is important to note that because any uses of the module elsewhere in the file will have no type information available.

If you would like to suppress the diagnostic, you can add a `# type: ignore` or `# pyright: ignore[reportMissingImports]` comment at the end of the line. Or you can disable the `reportMissingImports` check for your entire project.

**Comment by mayrholu** [comment]
Ok, thanks for the info!
