### ISSUE TITLE
Missing completion items for method call expressions that appear inside the condition of `if` statements (but only for method names that fit a certain pattern) 

### ISSUE THREAD

**Issue by anthony-S93** [microsoft/pylance-release#4283]
To illustrate the issue, I will use the following setup: 
```python
class MyClass:
    def some_test(self) -> bool: # Other forms of method names work fine.
        return True
    
    def is_correct(self) -> bool:  # Method names with the pattern "^is.+" is problematic
        return True
```
When I try to use completion, what I expect is something like this:
![works](https://user-images.githubusercontent.com/69449791/233798327-6a706f3e-0e71-45c1-93c1-e2af59afbf23.gif)

But when I try it with the `is_correct()` method, the completion item is missing:
![no-completion](https://user-images.githubusercontent.com/69449791/233798404-92e78de1-123a-4b11-be38-4336ecd824d7.gif)

This issue applies to method names that begin with "is". For instance, if I tweak the above example: 
```python
class MyClass:
    def local(self) -> bool:  # Works
         return True
    
    def is_local(self) -> bool: # Does not work
        return True

    def i_local(self) -> bool: # Works
        return True
```
![2023-04-23-014121_399x185_scrot](https://user-images.githubusercontent.com/69449791/233798933-5d17da3b-8691-4f76-8036-255123f911c7.png)

![2023-04-23-014137_454x201_scrot](https://user-images.githubusercontent.com/69449791/233798943-591cbb66-3818-44e7-8af1-4fe301fb8353.png)

The method  `is_local()` no longer appeared in the completion list when I type "is":

![2023-04-23-014205_481x798_scrot](https://user-images.githubusercontent.com/69449791/233798961-6e49e81c-cdcd-4327-81bd-8499471e8dff.png)

Inputing 'is' populates the completion list with functions from python modules such as `isabs`, `isfile` etc. I scrolled down the list to the end without seeing `is_local()` anywhere on the list.

Surrounding the method call expression with parentheses makes the problem go away. As in:
![parenthesesworks](https://user-images.githubusercontent.com/69449791/233799158-aba6440c-58a2-40ef-8375-65a1b4c1ae34.gif)

To be frank, I'm not entirely sure if this is an issue with the completion engine or `pyright`. The thing is that I couldn't reproduce the issue on other language servers. Any insight is much appreciated.

**Comment by rchiodo** [comment]
I believe this is working now. At least I can't seem to reproduce the behavior. 



![Image](https://github.com/microsoft/pylance-release/assets/19672699/01d510c6-ee0d-4055-aa5a-ec844e245071)

**Comment by anthony-S93** [comment]
> I believe this is working now. At least I can't seem to reproduce the behavior.
> 
> ![Image](https://user-images.githubusercontent.com/19672699/257882385-01d510c6-ee0d-4055-aa5a-ec844e245071.png)

@rchiodo Has the fixed been released yet? 

I can still reproduce this on pyright 1.1.320

**Comment by rchiodo** [comment]
I'm using pylance 2023.8.11. I tried Pyright 1.1.320 and it works for me as well. 

Can you repro with just this code and nothing else in a workspace:

```python
class MyClass:
    def some_test(self) -> bool: # Other forms of method names work fine.
        return True
    
    def is_correct(self) -> bool:  # Method names with the pattern "^is.+" is problematic
        return True

    def is_local(self) -> bool:
        return False

    def i_local(self) -> bool:
        return False


ob = MyClass()

ob.is # Hit CTRL+SPACE here


```

**Comment by anthony-S93** [comment]
> ```python
> ```python
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Maybe there's something else in your environment causing the problem.
> ```

As mentioned in the original bug report, you have to use the completion in the context of an `if` conditional. 


https://github.com/microsoft/pylance-release/assets/69449791/c0ef18ae-f95a-479a-b270-3ef115a0b9df

**Comment by erictraut** [comment]
Completion suggestions are generated from the parse tree, and the parse tree is generated from the stream of tokens in your source file. In cases where there are no syntax errors, the shape and structure of the parse tree is well defined. In cases where syntax errors are present, the parser attempts to create a parse tree that is "good enough". It includes a bunch of heuristics that attempt to "recover the parse" (i.e. get back to a part of the token stream where parsing can continue) without generating a cascade of syntax errors.

In your particular example, we see a token stream consisting of an "if" keyword followed by an identifier ("ob") followed by a dot token followed by an "is" keyword token. This is clearly a syntax error. The fact that `is` is a Python keyword is the key to the problem here. If you choose some other sequence of characters (like "i" or "is_" or "si"), the parser generates a parse tree that works fine for the completion provider logic. But in the case of a keyword like "is" or "for" or "in", the parser's heuristics cause it to generate a parse tree that confuses the completion provider. If the parser sees the token stream `if ob.is`, it's reasonable for the parser to "guess" that the intended meaning was `if ob is ...`

The question is whether the heuristics can be updated in such a way that they produce a better parse tree for this particular situation but _not_ generate worse behavior in terms of parse recovery and cascading syntax errors. That may be a tricky balance to strike. If it proves to be too difficult, my recommendation is to leave the current behavior in place. This is an extreme edge case, after all.
