### ISSUE TITLE
`"submodule" is not a known member of module "module"` when importing as alias

### ISSUE THREAD

**Issue by scratchmex** [microsoft/pylance-release#4322]
## Environment data

-   Language Server version: Pylance v2023.5.11, Python v2023.8.0
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.2

## Code Snippet

```python
import module as mod
import module.submodule

print(mod.submodule)
```

```python-repl
>>> <module 'module.submodule' from '.../module/submodule/__init__.py'>
```

## Repro Steps

1. Have the following module structure

![image](https://user-images.githubusercontent.com/4014888/236354006-16b57c1e-5b5a-4be6-ad75-e0c86b85c271.png)

## Expected behavior

to have the module resolved as Python do

## Actual behavior

looking under `module.submodule` work as expected but `mod.submodule` not

![Screenshot from 2023-05-04 17-55-01](https://user-images.githubusercontent.com/4014888/236353944-cc1a0d8c-be7a-48d6-bd75-29eb1d20cf82.png)

the behaviour was extracted from sqlalchemy actually
![Screenshot from 2023-05-04 17-52-02](https://user-images.githubusercontent.com/4014888/236353513-f55963fc-45e1-4ec1-bb67-61467da37630.png)

## Logs

```
NA
```

**Comment by rchiodo** [comment]
Thanks for the issue, but this is actually by design. 

See these other issues for an explanation:

https://github.com/microsoft/pylance-release/issues/3522
https://github.com/microsoft/pylance-release/issues/4014
https://github.com/microsoft/pylance-release/issues/4037

You can also read about it here:
https://microsoft.github.io/pyright/#/import-statements?id=unsupported-loader-side-effects

**Comment by rchiodo** [comment]
If you wanted to reference the submodule, you should reference it directly or create another alias:

```
import module as mod
import module.submodule as mod_sub


print(mod_sub)
```
