### ISSUE TITLE
Pylance/Pyright not recognizing member of imported module inside package

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#4326]
## Environment data

-   Language Server version: `2023.5.10`
-   OS and version: `Windows 10.0.22621`
-   Python version: `Python 3.10.9, Anaconda`

## Repro Steps

1. Create a `test` folder with the 3 files (`run.py`, `mymodule.py` and `__init__.py`) in the following structure,
which includes a folder named `mypkg`:
```
test
│   run.py
│   
└───mypkg
    │   mymodule.py
    │   __init__.py
```
2 . Put the following code into the 3 files, try to run to show the interpreter resolution:

![image](https://user-images.githubusercontent.com/57204023/236696163-30f46f58-faa5-4f7f-b502-97e241ebbfb8.png)

## Expected behavior

To have the module resolved by Pylance/Pyright as Python interpreter does.

## Actual behavior

The following warning is raised in the file `run.py`:
```
"mymodule" is not a known member of module "mypkg" Pylance [reportGeneralTypeIssues]
```

![image](https://user-images.githubusercontent.com/57204023/236696229-fd0e9aed-a426-45b7-abc3-b92a9b081e43.png)

**Comment by erictraut** [comment]
This behavior is intended.

Your code is relying on fragile assumptions about cross-module loader side effects, and pyright (the static code analyzer upon which pylance is built) doesn't model these by design. See [this documentation](https://microsoft.github.io/pyright/#/import-statements) for more detail.

In your code, `run.py` is importing `mypkg`, but it is not importing `mypkg.mymodule`. The `mypkg.__init__.py` file doesn't assign a local symbol `mymodule` any value, so it is not explicitly part of the `mypkg` namespace. The `mymodule` symbol happens to be implicitly written to the `__init__.py` global namespace as a side effect of the `import mypkg.mymodule` statement, but your code should not rely on this.

If you want `mypkg.__init__.py` to import the `mymodule` submodule and assign it to a local `mymodule` symbol, you should include `from . import mymodule` in your `__init__.py` file. Alternatively, you could add an `import mypkg.mymodule` statement to `run.py`. Either of these will eliminate the error message you're seeing.

**Comment by Diogo-Rossi** [comment]
Ok, understood.
Thank you for the detailed explanation!
