### ISSUE TITLE
Incorrect interaction of Enum and Protocol

### ISSUE THREAD

**Issue by Vlod-github** [microsoft/pylance-release#4327]
There probably shouldn't be any errors.

## Code Snippet
```python
from enum import Enum
from typing import Protocol


class AbstractEnum(Protocol):
    @property
    def VALUE1(self) -> str:  # error pylance 1
        pass


class TestEnum(Enum):
    VALUE1 = 'value1'
    VALUE2 = 'value2'


def my_function(my_enum: AbstractEnum):
    print(f'{my_enum.VALUE1=}')


my_function(TestEnum)  # error pylance 2

```

## Environment data
-   Language Server version: v2023.5.10
-   OS: Linux | Windows
-   Python version : 3.11 | 3.10

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is correct in generating errors here. The first error is because the property is annotated to return a `str`, but its implementation returns `None`. Protocol classes are allowed to contain method implementations, but I think your intent here is not to implement the `VALUE1` property but instead provide a structural type definition for it. In that case, its body should contain `...` rather than `pass`.

The second error is because `TestEnum` does not meet the requirements of the protocol class. The `VALUE1` variable in `TestEnum` is a read-only class variable that has the type `Literal[TestEnum.VALUE1]`, but the `VALUE1` variable in `AbstractEnum` is a read-only instance variable that has a type of `str`. Those are not type compatible, so the protocol validation fails.
