### ISSUE TITLE
Python dynamic auto-completion and intellisense

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/pylance-release#4333]
Intellisense fails to pick up hints when working dynamically

![image](https://user-images.githubusercontent.com/108051416/236387087-11f3f090-b689-49f1-83b6-7c2777e86855.png)

Static properties work perfectly

![image](https://user-images.githubusercontent.com/108051416/236387273-007eb2b9-9e9a-4ace-8f49-64cf44ef2fb9.png)

Can intelligent prompts be improved so that dynamic attributes can also obtain intelligent perception?

**Comment by StellaHuang95** [comment]
Hi @xxc-zsz, pylance is a static analyzer, so unfortunately none of the dynamic behavior will be supported.

**Comment by humblemat810** [comment]
However, it does support namedtuple dynamic generation, it is hardcoded support in visual studio code, I tried to copy the class namedtuple file and renamed it to namedtuple2 and the dynamic support is no longer supported. 

`
from collections import namedtuple

Point = namedtuple('Point', ['x','y'])
point = Point(x=1,y=2)

#point. show x and y

Pointz = namedtuple('Pointz', ['z'])



class Point3D(Point,Pointz):
    pass
#myPoint3D = Point3D(1,2,3) # error
#myPoint3D = Point3D(x=1,y=2,z=3) # error
myPoint3D = Point3D(1,2)
# all hinting works properly though in visual studio code
print(myPoint3D.z)  #z should be uninitized but set to 1 as z is set to point to the first element due to the mechanics of namedtuple
`
you lose normal functionality and cannot multiple inherit the named tuples. It is not elegant.

**Comment by StellaHuang95** [comment]
@humblemat810 Thanks for bringing this up. Could you please open a new issue for this? We don't fully monitor closed issues, so creating a new one will help us manage and respond to your request more effectively.

**Comment by heejaechang** [comment]
we have support for python's built-in well known types such as `namedtuple`. that's because we know exactly how it supposed to work.

but your case, 

```
class Person:
    def __init__(self, ** kwargs):
        ...
        
p = Person (name=" John", age=10)
```

we have no idea how to interpret `(name=" John", age=10)` unless we understand what method body of `__init__` is doing. and that is out of scope for static analyzer.
