### ISSUE TITLE
Allow wildcard import under TYPE_CHECKING statement

### ISSUE THREAD

**Issue by icui** [microsoft/pylance-release#4349]
I find it inconvenient to import every single type I use in typing module and wish to import everything with a wildcard import. I know this is not a good idea at run time, but I think it would be nice if pylance allows the following code without giving a warning.

```py
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from typing import *
```

**Comment by StellaHuang95** [comment]
Hi @icui, you can turn off the warning by adding the following to your settings.json.

```json
"python.analysis.diagnosticSeverityOverrides": {
    "reportWildcardImportFromLibrary": "none",
}
```

**Comment by erictraut** [comment]
You can use a `# type: ignore` or `# pyright: ignore` comment at the end of the line if you want to suppress the `reportWildcardImportFromLibrary` check. Alternatively, you can disable this diagnostic check globally using pylance settings, as mentioned by @StellaHuang95 above.

The use of `TYPE_CHECKING` increases fragility of your code, so it's something that I recommend avoiding if possible. Any time you use `TYPE_CHECKING`, you're effectively "lying" to the static code analyzer, which means that it will not be able to protect you from crashes that it normally would. For example, let's say that you define a type alias in your code (`X = Callable[[], None]`). This will generate a runtime exception because `Callable` is not available at runtime. Pylance would have told you this normally, but because you lied to it, the error will not be detected statically.

Likewise, the use of wildcard imports from libraries leads to code fragility regardless of whether it's under the `TYPE_CHECKING` conditional. It pollutes your module's global namespace with an indeterminate list of names — a list that can change from one version of the library to the next.

**Comment by icui** [comment]
> You can use a `# type: ignore` or `# pyright: ignore` comment at the end of the line if you want to suppress the `reportWildcardImportFromLibrary` check. Alternatively, you can disable this diagnostic check globally using pylance settings, as mentioned by @StellaHuang95 above.
> 
> The use of `TYPE_CHECKING` increases fragility of your code, so it's something that I recommend avoiding if possible. Any time you use `TYPE_CHECKING`, you're effectively "lying" to the static code analyzer, which means that it will not be able to protect you from crashes that it normally would. For example, let's say that you define a type alias in your code (`X = Callable[[], None]`). This will generate a runtime exception because `Callable` is not available at runtime. Pylance would have told you this normally, but because you lied to it, the error will not be detected statically.
> 
> Likewise, the use of wildcard imports from libraries leads to code fragility regardless of whether it's under the `TYPE_CHECKING` conditional. It pollutes your module's global namespace with an indeterminate list of names — a list that can change from one version of the library to the next.

Thanks for the reply. I agree with your explanation so I'm closing this issue.
