### ISSUE TITLE
Generic type hint not working right with nested class

### ISSUE THREAD

**Issue by spacether** [microsoft/pylance-release#4366]
Type: <b>Bug</b>

With this first example, B[int] is correctly seen as A[int]
### Sample 1
```
import typing
import typing_extensions

T = typing.TypeVar('T')


class A(typing.Generic[T]):
    pass


B: typing.Type[A] = A
a: A[int]  # seen as A[int]
b: B[int]  # seen as A[int]
```

But with this second example the int generic info is missing:
### Sample 2
```
import typing
import typing_extensions

T = typing.TypeVar('T')


class A(typing.Generic[T]):
    pass

class Properties:
  C: typing.Type[A] = A

c: Properties.C[int] # seen as Type[A] only, no int info
```
Can vscode be fixed to correctly show that c should be type A[int]?

Extension version: 2023.8.0
VS Code version: Code 1.78.1 (Universal) (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:57:42.343Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|8.00GB (1.66GB free)|
|Process Argv|--crash-reporter-id c48e9027-7f92-4e80-b41f-684aa4a6e195|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30739705

```

</details>

**Comment by erictraut** [comment]
This is a duplicate of https://github.com/microsoft/pylance-release/issues/4350, which was closed.

**Comment by erictraut** [comment]
Do you intend for `C` to be a type alias or a variable? You have defined it as a variable, but you're trying to then use it as though it's a type alias. You can't specialize a variable using brackets.

If you want to define a generic type alias scoped to class `Properties`, you can define it as follows:
```python
class Properties:
    C: typing.TypeAlias = A[T]
```

If you want to define a variable `C` scoped to class `Properties`, you must specify its type arguments in the type annotation. If you omit the type arguments, a static type checker will assume that you meant `Any`.

```python
class Properties:
  C: type[A] = A # This is equivalent to `C: type[A[Any]] = A`
```

**Comment by spacether** [comment]
I do not intend it to be a type alias, I intend it to be a variable that stores the class.
My intention is to have the behavior be the same in Sample1 as in Sample 2.

Why should the behavior differ?
In both cases a class is first defined.
Then a variable is set equal to that class.
Then a new variable references the last variable and adds the generic type info.
It works in sample 1 but not in sample 2. The code has the same steps.

Why must a type alias be used in sample 2 but not sample 1?

**Comment by erictraut** [comment]
The difference between sample 1 and sample 2 is that you're referencing a symbol from the same execution scope in sample 1 but a different execution scope in sample 2. Assignment-based type narrowing is applied within an execution scope but not across scopes. The type of `B` in sample 1 is therefore narrowed based on the assignment of `A`. This narrowed type also takes into account the fact that you have specifically assigned `A`, not a value of type `type[A]` (which represents "any subtype of class `A`").

In sample 2, you are referencing `C` from outside the execution scope in which it is declared. That means its type is simply `type[A]`, which is interpreted as `type[A[Any]]` because you omitted the type argument. This type represents "any subtype of `type[A[Any]]`" in the Python static type system. 

It sounds like you might be new to static typing in Python. You're stumbling on some basic concepts. You may find it useful to read [this documentation](https://microsoft.github.io/pyright/#/type-concepts) and [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced).

I recommend that you enable type checking (set `python.analysis.typeCheckingMode` to either "basic" or "strict"). Pyright will then provide you with error messages that will help guide you. You're doing a number of things that are not allowed in the Python static type system.

**Comment by spacether** [comment]
Thank you for explaining this and for the resources.
