### ISSUE TITLE
Pylance Django Intelesence 

### ISSUE THREAD

**Issue by ghettoDdOS** [microsoft/pylance-release#4370]
## Environment data
-   Language Server version: v2023.5.20
-   OS and version: Windows 11
-   Python version: 3.7.12 pyenv

## Code Snippet
VSCode settings.json
```json
"python.languageServer": "Pylance",
```

## Repro Steps
1. Create Django model and call model.objects.create method

## Expected behavior
When I use Jedi as an LSP, I get the following result, I would like the same from Pylance.
![image](https://github.com/microsoft/pylance-release/assets/47575319/6b89b51b-a1aa-47c4-9721-b8bf950f6f42)

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/47575319/261f6052-b962-4302-aa21-610c8b99af5d)
Also when going to the definition I get stub files instead of the source code.

**Comment by heejaechang** [comment]
unfortunately, this is something `pylance` can't handle in current form. `jedi` could handle this since it actually run code to access those information, but `pylance` will only statically inspect code and this kind of thing is an area it can't handle. this kind of behavior can only be supported by tools that actually run code such as `jedi` or `notebook`

we go to `stub` when you go to def on either `object` or `create` since the `object` is dynamically added to the `Package` model (https://github.com/django/django/blob/main/django/db/models/base.py#L419) and it doesn't actually exist in code (or I should say it exists in code but not in a way tool can figure out without running the code)

so `stub` is one of workaround python tool uses in such situation. but for this particular case, there is another problem, the `objects`, code dynamically injected, can be different `manager` based on `concrete` type so `stub` has to use the `common denominator` which is `BaseManager` 

and that is why you see the catch all signature of `**kwargs`

in future, when we add `django` specific feature we might be able to figure out how to support this kind of dynamic behavior, but for now, I think you best bet is staying with tools that actually run code such as `jedi` or `notebook` if you want this kind of behavior.
