### ISSUE TITLE
Import from source for python.analysis config

### ISSUE THREAD

**Issue by bartektrybala** [microsoft/pylance-release#4396]
default import hint looks like: django.db.models import Max because django imports there all of the submodules' files

Some projects have a requirement to use imports from source so the proper import would look like django.db.models.aggregates import Max

Is it possible to implement such option?

**Comment by rchiodo** [comment]
Thanks for the issue.

By default, we list the symbols that have a shorter path first, so in this case django.db.models would come first. 

Additionally, the `django.db.models' stub is marking `Max` as a public import, so it takes precedence over the submodule too.

```python
# Inside of bundled\stubs\django-stubs\db\models\__init__.pyi
from .aggregates import Max as Max
```

Which originally comes from here:
https://github.com/typeddjango/django-stubs/blob/d1a355ba076d4be35c3974db243f9eb55cdf6a41/django-stubs/db/models/__init__.pyi#L6

In order to change this behavior, the stub would have to not export that symbol.

**Comment by rchiodo** [comment]
This documentation describes how Pyright (and Pylance) determines the public API of a module:
https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface
