### ISSUE TITLE
Can't override Type Checking level per-Workspace. 

### ISSUE THREAD

**Issue by carltongibson** [microsoft/pylance-release#44]
## Environment data

-   Language Server version: 2020.6.1 

## Expected behaviour

I can override a User value for Type Checking per Workspace. 

## Actual behaviour

I set Type Checking to Basic at the User level. In a workspace I want to set it to Off. No effect. I need to set Off at User level to disable.

**Comment by huguesv** [comment]
Thanks for the feedback.

It seems that the VS Code settings editor UI doesn't add this entry to the workspace settings.json because it considers 'off' to be the default, so it thinks it is unnecessary.

```
"python.analysis.typeCheckingMode": "off"
```

Workaround: If you switch to the JSON view and add the entry manually to the workspace settings.json, it works.

**Comment by huguesv** [comment]
https://github.com/Microsoft/vscode/issues/58038

**Comment by huguesv** [comment]
Please see and upvote the issue linked above to get VS Code to support this. Thanks!
