### ISSUE TITLE
Pylance v2023.5.40, envFile is ignored (PYTHONPATH possibly shadowed)

### ISSUE THREAD

**Issue by BaconPancakes** [microsoft/pylance-release#4422]
<h3> Environment data </h3>

-   Language Server version: 2023.5.30
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

N/A: See Repro steps.

Relevant setting:
```json
"python.envFile": "${workspaceFolder}/my.env"
```

<h3> Repro Steps </h3>

1. Define an envFile with PYTHONPATH out of the tree of the workspaceFolder.
2. Hover over module imports specifically defined in that envFile but not in the workspaceFolder.

<h3> Expected behavior </h3>

Module imports or type checking appears.

Working on v2023.5.30

<h3> Actual behavior </h3>

Symbols not found.
I suspect that the workspaceFolder is prepended to PYTHONPATH and shadows everything defined in envFile. If you have to do something like this, probably ought to append to PYTHONPATH only after the envFile is loaded.

Broken on v2023.5.40

<h3> Logs </h3>

Sorry, can't disclose paths to source files.

**Comment by debonte** [comment]
> Sorry, can't disclose paths to source files.

I'm unable to repro this issue. Can you create a standalone project to repro this issue and then either provide me with the project or a related Python Language Server log?

Btw, I noticed that you also filed https://github.com/microsoft/vscode-python/issues/21257. When `python.analysis.pylanceLspClientEnabled` is set to `false` the Python extension provides us with the value of `PYTHONPATH`. So I'm wondering if the two issues may have the same underlying cause.

**Comment by BaconPancakes** [comment]
It took a bit of finicking and the erroneous behavior doesn't exactly match what I'm seeing in my original codebase, but I did manage to repro it. Expected behavior on v30, broken on v40. Here's the trace log and project in a zip.

[sandbox_debug.zip](https://github.com/microsoft/pylance-release/files/11581070/sandbox_debug.zip)

**Comment by debonte** [comment]
@BaconPancakes, thanks for the repro project.

@erictraut, this behavior was changed by https://github.com/microsoft/pyright/commit/43a6a8fae55c5b40ee040608271f9420a353d1a5.

My hunch is that the [new "Prefer traditional packages over namespace packages" check](https://github.com/microsoft/pyright/commit/43a6a8fae55c5b40ee040608271f9420a353d1a5#diff-81d67b2637abe4f01bfed3e5ddffc08258efc91e5e82812e57230b9fda05745fR1581) still needs to be wrapped in the `if` block below which was removed. In this issue's scenario, both `bestImportSoFar` and `newImport` are namespace packages.

```python
if (bestImportSoFar.isNamespacePackage && !newImport.isNamespacePackage) {
```

Thoughts?

**Comment by erictraut** [comment]
I think the current import logic is correct and matches that of the interpreter. Can you describe the repro steps in detail? I presume that the issue involves both traditional and namespace modules on different paths?

**Comment by debonte** [comment]
> Can you describe the repro steps in detail?

1. Unzip [sandbox_debug.zip](https://github.com/microsoft/pylance-release/files/11581070/sandbox_debug.zip)
2. In VS Code: File > Open Folder...
3. Select `<zip extract dir>\sandbox_debug\my_project`.
4. Open `src\my_src.py`

Results:
Line 1: "my_out_of_tree_lib" is unknown import symbol
Line 2: Import "lib.inner.my_out_of_tree_lib" could not be resolved

However, runtime appears to work fine. At least, I think this is equivalent, but maybe not?
1. `set PYTHONPATH=<zip extract dir>\my_project_out_of_tree`   <-- this matches the `PYTHONPATH` from the `.env` file which Pylance adds to extra paths
2. `python src\my_src.py`

Results: No errors

> I presume that the issue involves both traditional and namespace modules on different paths?

There are these two imports with errors:
```python
from lib.inner import my_out_of_tree_lib  # import error
import lib.inner.my_out_of_tree_lib  # import error
```

And these are the related modules:

- `<workspace root>\lib\inner\__init__.py`
- `<extraPath from PYTHONPATH>\lib\inner\my_out_of_tree_lib.py`

`isNamespacePackage` is `true` for both. However, since `my_project\lib\inner` contains an `__init__.py`, I believe it is a traditional package?

**Comment by erictraut** [comment]
> At least, I think this is equivalent, but maybe not?

No, this is unfortunately not equivalent. When you run `python src\my_src.py`, the Python interpreter assumes that the default import resolution path is `./src`, not `.`. That means it won't attempt to resolve from `./lib/...`

Perhaps this will help clarify. Try the following:
1. Create a file `foo.py` that is a peer to the `src` directory.
2. Within `src/my_src.py`, add the line `import foo`. Note that this resolves fine according to pyright because it assumes you'll be executing your code from the `.` directory.
3. Run `python src/my_src.py` from the shell. You'll receive an error indicating that it cannot import module `foo`.

To make these equivalent, you'd need to create a top-level `__main__.py` file within the project's root directory. Within this file, include the statement `import src.my_src`. Now run `python __main__.py` from the shell. The import behavior will now match the behavior indicated by pyright. Pyright assumes that the default resolution path is `.` (the root directory of your project).

This is why I originally added support for "execution environments" in pyright. It allows you to specify the root execution directory for different "executables" in your project.

If you create a `pyrightconfig.json` file and add the following, you'll see that the imports now resolve without error in the sample:
```json
{
    "executionEnvironments": [
        {
            "root": "src", 
            "extraPaths": ["/users/eric/Desktop/sandbox_debug/my_project_out_of_tree/"]
        }
    ],
}
```

There's currently no way to specify a default import resolution path other than `.` except through the use of execution environments. One thing we could consider is to expose a `rootPath` configuration option (or some similar name) that allows you to specify a root path other than `.` for your project. I'm throwing this idea out there, but I'm not convinced it's a good idea. I think it would be a footgun for many users, and I worry that we'd be generating a bunch of support questions.

BTW, if you're thinking at this point that the import resolution behaviors in Python seem to be ludicrously complex, arcane, and filled with unexpected behaviors and edge cases, I would agree with you.

The problem described in this particular issue is a pretty significant edge case, and there are workarounds:
1. Add an `__init__.py` file under the `my_out_of_tree` directory so you're not mixing traditional and namespace modules.
2. Use pyright's "executionEnvironments" configuration option.

**Comment by BaconPancakes** [comment]
Assuming we did 
> Add an __init__.py file under the my_out_of_tree directory so you're not mixing traditional and namespace modules.

I see now that `import lib.inner.my_out_of_tree_lib` resolves. Neat.

Let's suppose we used the `from _ import _` syntax:
```python
from lib.inner import my_in_tree_lib, my_out_of_tree_lib
```

Now, `my_in_tree_lib` can be resolved but `my_out_of_tree_lib` can't be found. Is this because Pylance v40's compliance to arcane Python import resolution leads to "correctly" importing lib.inner from `.` instead of v30 behavior where it seemingly preferred PYTHONPATH?

**Comment by debonte** [comment]
> Add an `__init__.py` file under the `my_out_of_tree` directory so you're not mixing traditional and namespace modules.

Today was the first time I read any of PEP 420 in detail. [This section](https://peps.python.org/pep-0420/#differences-between-namespace-packages-and-regular-packages) seems particularly relevant.

Am I correct in thinking that `lib.inner.my_in_tree_lib` and `lib.inner.my_out_of_tree_lib` comprise a single namespace (single package?) but do not "come from the same directory structure" and therefore should be provided as a namespace package? If so, it looks like neither directory should have an `__init__.py` rather than both having one, since the PEP says, "Namespace packages have no `__init__.py` module."

> Now, `my_in_tree_lib` can be resolved but `my_out_of_tree_lib` can't be found.

That said, I saw this error in both configurations (`__init__.py` files in both dirs or neither dir). And I think that is because the `ImportResolver` always resolves each import statement to a single package/module. It doesn't seem to have the ability to resolve a different location for each symbol in the import. However, the runtime is able to do that.

Btw, I noticed when [`_pickBestImport`](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/importResolver.ts#L1634) is deciding between these two directories, both of their `ImportResult` objects have `isNamespacePackage` set to `true` in both cases -- if there is an `__init__.py` or not. I'm not sure if that's an `ImportResolver` bug or maybe my `__init__.py` files are not in the right place to create a traditional package. Adding and removing them did change the runtime behavior though, so I think the placement was correct.

**Comment by debonte** [comment]
>> Let's suppose we used the `from _ import _` syntax:
>> ```python
>> from lib.inner import my_in_tree_lib, my_out_of_tree_lib
>> ```
>> Now, `my_in_tree_lib` can be resolved but `my_out_of_tree_lib` can't be found.

>I think that is because the ImportResolver always resolves each import statement to a single package/module. It doesn't seem to have the ability to resolve a different location for each symbol in the import. However, the runtime is able to do that.

@erictraut, I assume this is known. Is this just a low-pri scenario that we haven't felt the need to support?

**Comment by erictraut** [comment]
Yes, that's correct. It's an edge case that has never come up before. It would require a significant rework of the import mechanism (with likely impact to compatibility and performance).

**Comment by debonte** [comment]
@BaconPancakes, one workaround is to split the import into two lines:

```python
from lib.inner import my_in_tree_lib
from lib.inner import my_out_of_tree_lib
```
