### ISSUE TITLE
Not known member of module when using alias

### ISSUE THREAD

**Issue by pkubik** [microsoft/pylance-release#4424]
## Environment data

-   Language Server version: 2023.5.40 (pyright e6d7b84c)
-   OS and version: Windows 10 Pro
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

```python
import lightning as L
import lightning.fabric


lightning.fabric.seed_everything(42)  # OK
L.fabric.seed_everything(42)  # "fabric" is not a known member of module "lightning"
```

## Expected behavior

Error should not be shown, because I explicitly import `lightning.fabric`.

## Actual behavior

`"fabric" is not a known member of module "lightning"` is shown on the line where `L.fabric` is being accessed.

## Workaround

I can use this as a workaround, but it's not something anyone would've expected.

```python
import lightning
L = lightning
```

**Comment by debonte** [comment]
This is intended behavior. The code above is relying on implicit import side effects, and pyright (the type checker that Pylance is based on) intentionally does not model those because they lead to code fragility.

This is covered in Pyright's documentation [here](https://microsoft.github.io/pyright/#/import-statements). The discussion and links in this Pyright issue may also interest you: https://github.com/microsoft/pyright/issues/4750

**Comment by pkubik** [comment]
Ok, I found relevant question and answer by @gvanrossum [here](https://github.com/python/typing/issues/1358#issuecomment-1462263905). He opinionated this should be left to the type-checker to decide. The problem was complicated alias analysis and not "code fragility" as pointed above.

And I posted this on a wrong repository anyway...
