### ISSUE TITLE
Issues with pandas Timedelta - init and addition

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#444]
## Environment data

-   Language Server version: 2020.9.7
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.5

## Expected behaviour

No error

## Actual behaviour

```python
import pandas as pd

ts = pd.Timestamp("10/1/2020 10:00")
td = pd.Timedelta(minutes=10)

sm = ts + td
print(sm)
```

reports 3 issues

1. On the `pd.Timestamp` line is the same issue as reported in #427 
2. On the `pd.Timedelta` line is the message `Argument missing for parameter "value"`
3. On the line with the sum, is the message: 
```
Operator "+" not supported for types "Timestamp" and "Timedelta"
  Operator "+" not supported for types "Timestamp" and "Timedelta"
```

Possible fix (not sure if the `__new__` part is right, but it worked!), which *include* the suggested fixes in #427 and #436
```
diff __init__.pyi.ORIG __init__.pyi
119,120c119,120
< class Timedelta(object):
<     def __init__(self, value: Any, unit: str = ..., **kwargs) -> None: ...
---
> class Timedelta(datetime.timedelta):
>     def __init__(self, value: Any = ..., unit: str = ..., **kwargs) -> None: ...
149c149,151
< class Timestamp(object):
---
> class Timestamp(datetime.datetime):
>     @override
>     def __new__(self, ts_input: Any, **kwargs): ...
153,158c155,160
<         freq: Any,
<         tz: Any,
<         unit: str,
<         year: int,
<         month: int,
<         day: int,
---
>         freq: Any = ...,
>         tz: Any = ...,
>         unit: str = ...,
>         year: int = ...,
>         month: int = ...,
>         day: int = ...,
243c245
<     def strftime(self) -> str: ...
---
>     def strftime(self, fmt:str) -> str: ...

```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020100-7-october-2020

**Comment by cwgonzalez1192** [comment]
Hi, has this issue returned?  As far as I can tell, I'm currently seeing it on v2023.2.30.  See screenshots below, in which Pylance misidentifies a `pd.Timestamp` as a `pd.Timedelta` following .  Perhaps it is due to my older Python and Pandas versions:
- Python v3.6.8
- Pandas v1.1.5

Location of warning:

![image](https://user-images.githubusercontent.com/8965551/220535439-9cc4dadb-19d4-4ce7-b44e-216021030a3d.png)

Description of warning:

![image](https://user-images.githubusercontent.com/8965551/220535497-8f1a875a-80a0-4f20-8b48-13a13679485f.png)

Version of Pylance:

![image](https://user-images.githubusercontent.com/8965551/220535590-eaf6e198-2309-454b-9407-b30555b0038d.png)

@bschnurr (sorry! just tagging someone who appears to be an active contributor - looks like @jakebailey no longer works on this repo)

**Comment by Dr-Irv** [comment]
1. Please report any issues with pandas stubs in the `pandas-stubs` repo.  https://github.com/pandas-dev/pandas-stubs
2. Don't use screenshots - if we are to test this, we need to copy/paste code samples.
3. With python 3.9, your issue doesn't occur.  You might be having a problem because you are using an old version of python as well as a very old version of pandas.  We test the stubs with python 3.8 through 3.11, and only with the latest release of pandas (currently 1.5.3)
