### ISSUE TITLE
Have stub files (pyi) be their own language mode

### ISSUE THREAD

**Issue by tristan957** [microsoft/pylance-release#447]
HI team! Thanks for the great extension + Pylance. Recently I have been generating Python bindings for an open source storage engine written in C using Cython. I wanted to be a good dev, so I went ahead and added some stub files to accompany my shared library outputs from Cython to give end users a better dev experience with autocompletion and all the goodies that Pylance and Python (ext) can give them. For reasons that aren't really relevant to this issue, I am required to do some codegen for docstrings within both my pyx and pyi files. So I have had to rename my files to `*.pyx.in` and `*.pyi.in` so maintainers can easily see the purpose of the file from the extension. Creating stub files in VSCode has been very easy 👍 when the extension is literally `.pyi`. When the extension is something like `.pyi.in` and I associate that extension with `python` in `files.associations`, the development experience of the stub file becomes quite a bit worse mainly because I think the Python extension or Pylance no longer understand that it is a stub file, and instead associate with a Python source file.

What I would like to see is something like the VSCode TypeScript team does where `.ts` files are `typescript` and `.tsx` files are `typescriptreact`. The Python equivalents would be something like `py` -> `python` and `pyi` -> `pythonstub`. Without being able to associate my `.pyi.in` files as Python stub files, I lose out on the great dev experience that this extension provides.

Here is a snippet of code that reports no errors as a `pyi` file, but reports the usual Python errors as a `pyi.in` file associated as `python`:

```python
class KvdbException(Exception):
    """
    @SUB@ hse.KvdbException.__doc__
    """

    returncode: int

    def __init__(self, returncode: int) -> KvdbException:
        ...
```

Please let me know if I can provide more information.

**Comment by jakebailey** [comment]
The file association is a VS Code detail, which only affects the UI's syntax highlighting choice as well as how VS Code directs its requests (e.g. send a request for a Python file to all providers who registered for the language).

As an LSP, we're only told the filename, not that the user chose to reassociate the file (associations aren't a part of the spec). Since pyi files behave differently than py files, we distinguish them via their file extension when analyzing them, resolving imports, etc. It's likely that it's going ".pyi? nope, so py" under the hood, and that's the behavior you're getting.

Splitting the language in two wouldn't help, because we won't get that info, and it will actually cause other issues as we won't have the right colorization for the language in the editor (without a bit of work to try and get it registered upstream where the Python language colorization is defined), among other troubles re: the other language features the core Python extension works with outside of Pylance.

I'm curious about your use case; if you were able to specify your types in the Cython source and have Cython generate stubs at build time (for distribution), would that workflow work better?

**Comment by tristan957** [comment]
If Cython generated stub files, my use case would be satisfied (assuming the output stub file makes sense). I don't claim to be an expert on all things cython, but I haven't found any way to generate stub files thus far.

Regarding your reply, how does the language server understand when I have an untitled file and associate the file through VSCode with Python to start doing various language server things? I may be misunderstanding your comment a bit though. Is VSCode just telling you the file is really "untitled.py" in that case?

**Comment by jakebailey** [comment]
> If Cython generated stub files, my use case would be satisfied (assuming the output stub file makes sense). I don't claim to be an expert on all things cython, but I haven't found any way to generate stub files thus far.

Yes, this is the thing that we'd love to see (use cython types and the docstrings and build the pyi as an artifact).

> Regarding your reply, how does the language server understand when I have an untitled file and associate the file through VSCode with Python to start doing various language server things? I may be misunderstanding your comment a bit though. Is VSCode just telling you the file is really "untitled.py" in that case?

VS Code sends us events with the URI something like `untitled:Untitled-1`, and we "handle" it by assuming it's python. Real files on disk look like `file:///home/jake/some/file.py` or `file://c:/Users/Jake/some/file.py`.

**Comment by erictraut** [comment]
VS Code does actually send the language ID as part of the `onDidOpenTextDocument` event. However, splitting the language ID as you've suggesting would break almost every tool in the Python / VS Code ecosystem because they all assume that both "py" and "pyi" files map to the same language ID ("python"). This approach also wouldn't work if you wanted to use command-line tools (e.g. hook up Pyright as part of your CI pipeline).

Can you provide more details about why it's not feasible to use the standard ".pyi" file extension for your stub files? That's what is assumed by all of the Python specs and tools throughout the Python ecosystem.

**Comment by jakebailey** [comment]
> VS Code does actually send the language ID as part of the `onDidOpenTextDocument` event.

Ah, TIL. 🙂

**Comment by tristan957** [comment]
Well damn. Thanks for the schooling on LSP and VSCode. Sucks it has to be this way for now. This whole Cython/stub files mess has really been a pain for me. On one hand you have to define docstrings in the pyx file for __doc__ to exist, and then you have to redefine the docstring in the stub file for language servers like Pylance to pick up. Had to move the docstrings out of line and have a script to insert them out of place (in a new file) during the `cythonize` function.

So I have defined docstrings in a `doctrings.toml` with unique keys for each docstring ala 

```toml
[hse.KVDB_VERSION_STRING]
__doc__ = """
A string representing the HSE KVDB libary version

The version string starts with a numeric sequence (e.g., 1.7.0) and then, depending
on the type of build may have additional information appended.
"""

[hse.KVDB_VERSION_TAG]
__doc__ = """
A string representing the HSE KVDB libary version tag

The version tag starts with a sequence (e.g., r1.9.0) and then, depending
on the type of build may have additional information appended.
"""

[hse.KVDB_VERSION_SHA]
__doc__ = """
A string representing the HSE KVDB library version commit hash

The version commit hash is a git commit hash
(e.g., b55fe07774d7cbc1492d7b8a47dc2c194cd3e24a).
"""

[hse.KvdbException]
__doc__ = """
Thrown when HSE encounters an error. Wrapper around `hse_err_t`.

Members:

returncode - error code returned by HSE
"""

[hse.Kvdb.close]
__doc__ = """
Close an open HSE KVDB

No client thread may enter the HSE KVDB API with the referenced KVDB after this
function starts. This function is not thread safe.
"""
```

My script looks for the `@SUB@ key.__doc__` pattern you see in the original comment, and does a text sub based on the key. So the script intakes `pyx.in` and `pyi.in`, and output `pyx` and `pyi` with the docstrings appropriately in place. I could probably just switch where the `in` is and get away with it, but typically I find `in` being the suffix in file names.

@erictraut hopefully the above explains my entire use case.

**Comment by jakebailey** [comment]
This makes sense; I think it's definitely the case that if Cython were to output stubs that you wouldn't have to do that, and that'd be the ideal.

**Comment by tristan957** [comment]
Yea :shrug:. Thanks for taking the time to entertain me, and listen to my soapbox about Cython development. Feel free to close as won't fix, since your explanations make sense to me.

**Comment by jakebailey** [comment]
Revisiting this, I don't think that we're likely to do this. We also have to handle files without extensions, and we assume that those files are python (since the editor is sending them to us), and pyi files are handled specially. There are other issues about handling the other py-ish formays like pyx and pyw, and we could handle those there, but I don't think splitting the language mode itself works for py vs pyi files.

**Comment by tristan957** [comment]
Thanks for the explanation @jakebailey. Makes sense
