### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by nitishxp** [microsoft/pylance-release#4488]
Given below a code snippet 

```
class Singleton(type):
    """Single metaclass to make any class singleton in nature"""
    _instances = {}

    def __call__(cls, *args, **kwargs):
        singleton = kwargs.pop('singleton', True)
        if singleton:
            if cls not in cls._instances:
                cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
            return cls._instances[cls]
        else:
            return super(Singleton, cls).__call__(*args, **kwargs)

class A(metaclass=Singleton):
   def test(self):
      print("test method")

a = A()
a.test() # Autocompletion not working here
```

**Comment by erictraut** [comment]
This is because pyright (the static type checker upon which pylance is built) is unable to infer the return type of the metaclass `__call__` method. You would need to add appropriate type annotations to the `__call__` method if you want completion suggestions to work in this case. I can't tell from your minimal code sample what the appropriate type annotation would be, but here's an educated guess.

```python
_T = TypeVar("_T")

class Singleton(type):
    ...
    def __call__(cls: type[_T], *args, **kwargs) -> _T: ...
```

**Comment by nitishxp** [comment]
Hi Eric `class Singleton(type):` is the actual snippet all other class just use this as a metaclass

**Comment by nitishxp** [comment]
Yes it's working thank you Eric and heejachang :)
