### ISSUE TITLE
Missing UndefinedVariable error when expected

### ISSUE THREAD

**Issue by FedericaBrando** [microsoft/pylance-release#4497]
Hi all, Thanks for the help in advance.
I searched in the issue history but couldn't find anything, if it was already asked please forgive me.

I was coding and expecting a `UndefinedVariable` report from pylance. I was wondering if this behaviour is expected and it is intended as it is or not, and if yes could you explain to me the reasons. Thanks a lot. 

## Environment data

-   Language Server version: v2023.6.10
-   OS and version: Ubuntu 22.04.2 LTS 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.3 

## Code Snippet

![image](https://github.com/microsoft/pylance-release/assets/52486325/27118f46-c6b9-435c-ab24-434443ca3bdc)

## Expected behavior

Expecting report error in both cases. 

## Actual behavior

When declaring in a function it is not reporting it.

**Comment by erictraut** [comment]
Here's the text of the sample so others don't need to retype it:

```python
def prova():
    try:
        c = 4
    except Exception as e:
        a = 4 + c + a
        return a
```

I'm able to repro the problem on pylance but not on pyright. Normally that would lead me to believe that it's a bug related to evaluation ordering, since pylance's semantic token feature often causes statements to be evaluated in a different order than they would otherwise be evaluated. But on initial inspection, I'm not able to repro the problem even if I change the evaluation ordering to match pylance. More investigation is needed.

**Comment by erictraut** [comment]
Ah, the issue is that pyright is using two different diagnostic rules for these two cases. For the global scope, it's reporting the problem using the `reportUndefinedVariable` diagnostic rule. In pylance, this is a warning by default, so you will see a yellow squiggly. For the function case, pyright is using the `reportUnboundVariable` diagnostic rule. In pylace, this is disabled by default, so you won't see any diagnostic. If you set `python.analysis.typeCheckingMode` to "basic", you will receive errors for both cases.

The two different cases may sound inconsistent, but the Python interpreter distinguishes between "undefined" and "unbound" variables in the same manner.

```python
a = a + 1 # NameError: name 'a' is not defined
```

```python
def foo():
    a = a + 1 # UnboundLocalError: cannot access local variable 'a' where it is not associated with a value
foo()
```

The reason that `reportUnboundVariable` is disabled by default in Pylance is that it can occasionally produce false positive errors in unannotated code.

So, I think this is all working as designed. No bug to fix.

**Comment by abdallahelkoly011-wq** [comment]
اصلح الكود
