### ISSUE TITLE
Better support for hyperparameters with ML frameworks

### ISSUE THREAD

**Issue by jlperla** [microsoft/pylance-release#4506]
A common feature of ML frameworks, such as Pytorch Lightning, is the use of a function which saves all arguments into an internal type. 
 This is used for logging directly (e.g. to weights and biases), saving to files for replication, etc.

The code looks like
```python
class MyModule(pl.LightningModule):
    def __init__(
        self,
        N: int,
        alpha_0: float,
        ml_model: torch.nn.Module, # maybe some stuff to ignore
    ):
        super().__init__()
        self.save_hyperparameters(ignore=["ml_model"])  # saves all locals except the `ml_model` into `self.hparams`
        self.ml_model = ml_model

   def f(self):
       print(self.hparams.N) # etc.  Access this way
       # need self.ml_model instead since was added manually
```
Note that you access thse through `self.hparams.N` and `self.hparams.alpha_0`   And also note that the ignored ones don't fit this.

The problem is that this creates havoc for linting because everytime it sees the `self.hparams.N` etc. it doesn't know the type.    The errors have text like:
```
Cannot access member "N" for type "MutableMapping[Unknown, Unknown]"
  Member "N" is unknown
```

Not sure how this can be solved , but it would be extremely helpful for ML workflows to be address this issue.  It makes linting useless in the current state.

**Comment by erictraut** [comment]
Technically, pylance is a type checker, not a linter. It performs static analysis of the types in your code to find potential errors.

Based on the lightning and pytorch source code, it appears that the `hparams` attribute is handled through the use of a mix-in class called `HyperparametersMixin` defined in `hparams_mixin.py`. The `hparams` symbol is a property that is declared to return a value of type `AttributeDict | MutableMapping`. Here's the relevant part of that source file:

```python
    @property
    def hparams(self) -> Union[AttributeDict, MutableMapping]:
        ...
```

Both `AttributeDict` and `MutableMapping` are dictionary-like types that support subscript (index) operators. That means you can access elements by name using a syntax such as `self.hparams["N"]`. The `AttributeDict` also has a `__getattr__` method, so it supports a member access (dot) operator (as in `self.hparams.N`). The `MutableMapping` class does not support this. I don't know enough about the internals of pytorch to say why `hparams` can be either an `AttributeDict` or a `MutableMapping`, but apparently it can be either of these types. That means your code could crash if it happens to return a `MutableMapping` rather than an `AttributeDict`.

A static type checker will not be able to tell which of these two types will be used at runtime, so it needs to analyze your code assuming that either type is possible. Since you're referencing attribute `N` in a way that isn't compatible with the `MutableMapping` type, it (correctly) informs you that you might have a bug.

Here are some options:
1. Change your code to use the subscript syntax to access the hyperparameter by name (`self.hparams["N"]`).
2. Disable type checking errors by setting `python.analysis.typeCheckingMode` to "off". This will eliminate these errors along with all other (potentially useful) errors, so this isn't a great option.
3. Contact the maintainers of pytorch to better understand why they chose to annotate the `hparams` property in that manner and see if they can provide better type information so as to avoid this ambiguity.
4. Temporarily suppress the type violation error by adding a `# type: ignore` comment to the end of the line.

As for `params`, I don't see any such attribute in the pytorch code, but I may be looking in the wrong place.

**Comment by jlperla** [comment]
Thanks so much.  (Sorry, I did had `self.params.N` as a typo when I had meant `self.hparams.N`.  Fixed above to be consistent there)

> Since you're referencing attribute N in a way that isn't compatible with the MutableMapping type, it (correctly) informs you that you might have a bug.

Just to be clear, there is no bug.  These show the errors on all usage (even correct usage) which makes it impossible to have static type checking on for the files.  Hundreds of errors since the `hparams` are used almost everywhere.

> A static type checker will not be able to tell which of these two types will be used at runtime, so it needs to analyze your code assuming that either type is possible

FWIW,
```
type(self.hparams)
<class 'pytorch_lightning.utilities.parsing.AttributeDict'>
```

No idea on the design of pytorch lightning and why they went this route, but these are all false-positive flags by pylance.  Is there something I could pass on to the PL developers on type annotations for their mixin which would fix these issues?


A MWE example here  is:
```python
import pytorch_lightning as pl
class MyModule(pl.LightningModule):
    def __init__(self,
                 N: int):
        super().__init__()
        self.save_hyperparameters()
    def f(self):
        print(self.hparams.N)                        

model = MyModule(N=10)
model.f()
```
Which works fine, but has the Pylance error: `Cannot access member "N" for type "MutableMapping[Unknown, Unknown]"
  Member "N" is unknown`

**Comment by hmc-cs-mdrissi** [comment]
Reading over pytorch lightning code it is possible for hparams to be non AttributeDict. Union return types are awkward design because of issues like this and tend to be pain point to work with.

`_to_hparams_dict` is what sets hparams. When `_to_hparams_dict` is given dict  it transforms it to AttributeDict. When given a non-dict mutable mapping it doesn't make an AttributeDict. My guess is non-dict mutable mapping is pretty rare and weird so that code path is not taken much. It wouldn't surprise me if 95% (or even higher) return type is attribute dict in practice and | Mapping case is pretty niche. But the type hint forces it to always be handled.

This makes it more a bug report for pytorch lightning type hints. Either they should adjust api to always return AttributeDict or at least change return type to be AttributeDict | Any (typeshed trick when some return type is rare). Current return type means you practically can't use it as AttributeDict especially as AttributeDict is subtype of MutableMapping.

**Comment by jlperla** [comment]
Much appreciated.  See linked post in PL repo: https://github.com/Lightning-AI/lightning/issues/17852  where I described the issue and linked to your ideas.

I will close this issue if that is OK, given that you have shown the fix is in a different codebase.
