### ISSUE TITLE
I have installed all the libraries in my virtual environment , selected the correct python interpreter also and tried all the methods but still it's showing library not accessed by pylance.

### ISSUE THREAD

**Issue by NitinSingh77** [microsoft/pylance-release#4566]
<h3> Environment data </h3>

-   Language Server version: 2023.5.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue. Do you have a specific example that reproduces the problem?

For example, this would show a library not accessed error:

```python
import sys
```

Because sys isn't used. But perhaps you meant this error:

![image](https://github.com/microsoft/pylance-release/assets/19672699/65588fd2-6279-4c4a-a618-9315b2759de2)


That would be from a module that pylance couldn't find.
