### ISSUE TITLE
Wrong suggestions with blender bpy package

### ISSUE THREAD

**Issue by LucaBonfiglioli** [microsoft/pylance-release#4580]
Pylance fails completely with `bpy` package. This is not an issue with BPY, since the only language server that fails with this library is pylance, other lang servers work perfectly with this package.

## Environment data

-   Language Server version: v2023.7.10
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10

## Code Snippet

```python
import bpy
bpy.ops
```

## Repro Steps

1.  Install bpy `pip install bpy==3.6.0`
2. Copy paste the two lines of code provided above.

## Expected behavior

The pylance server should suggest actual bpy submodules, like `ops`, `data` etc...

## Actual behavior

The pylance server throws this kind of error:

![image](https://github.com/microsoft/pylance-release/assets/6567253/41495326-9080-4838-b37a-0baa21fb9d6d)

It also suggests modules that are not really there:

![image](https://github.com/microsoft/pylance-release/assets/6567253/6edd1413-43e0-4596-a62e-d2a588608301)

## Logs

Unfortunately the pylance output log prints a lot of information, I am not going to fully copypaste it here, since it may contain info that I am not legally allowed to publish, and I am not going to skim through all of that. 

I might be able to provide you some specific entries, in case you need them. Just tell me which lines you need and I will manually see if I can post them.

**Comment by rchiodo** [comment]
Thanks for the issue. 

This is because `bpy` is actually a C++ DLL and not a python package. Pylance (and Pyright which Pylance is based upon) only work with `.pyd` files if there are stubs present for the `.pyd` file.

For more information see this documentation:
https://microsoft.github.io/pyright/#/type-stubs?id=importance-of-type-stub-files

This issue has a good discussion of the problem:
https://github.com/microsoft/pylance-release/issues/166

Ideally, Blender would provide type stubs for its python interface.

**Comment by rchiodo** [comment]
Seems there's a 3rd party set of type stubs for blender. If you pip install this package: 
https://pypi.org/project/blender-stubs/

Pylance will start providing completions for blender.
