### ISSUE TITLE
Paths to files are not resolved with realpath before opening

### ISSUE THREAD

**Issue by vient** [microsoft/pylance-release#4588]
<h3> Environment data </h3>

-   Language Server version: 2023.7.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.4
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

pyproject.toml
```
[tool.pyright]
extraPaths = ["development"]
```

a.py
```python
def f():
    pass
```

b.py
```python
from proj.a import f
```

folder structure
```
$ tree
.
├── a.py
├── b.py
├── development
│   └── proj -> ..    # this is a symlink to root project dir
└── pyproject.toml
```

<h3> Repro Steps </h3>

1. Open `a.py` and `b.py` in VSCode
2. Press "Go to definition" on `f` in b.py

<h3> Expected behavior </h3>

VSCode switches to previously opened `a.py` tab.

<h3> Actual behavior </h3>

VSCode opens another tab for file `development/proj/a.py`. It is the same `a.py` but now you have it opened in two tabs and you can start to modify both at the same time and face troubles.

**Comment by rchiodo** [comment]
Thanks for the issue but I believe this is by design. VS code doesn't follow symlinks and neither does Pylance. We don't run any python code to analyze the file, so this is just node.js opening the file for us.

See this issue:
https://github.com/Microsoft/vscode/issues/57873

You might try the symlink follow extension.

You can repro this without pylance being involved by just opening the two files in VS code. Changes are not reflected in each until you save.

**Comment by vient** [comment]
Okay, thanks, Symlink Follow extension with `"symlink-follow.autoFollow": true` setting solves my issue.

**Comment by starball5** [comment]
How is this expected though? If VS Code doesn't follow symlinks, then how would it open a symlink to the target file when you expect it to open the target file?

**Comment by rchiodo** [comment]
Actually, I think this is a bug. We're likely passing back the wrong URI for the file during goto defintion. See https://github.com/microsoft/pylance-release/issues/5136
