### ISSUE TITLE
Pylance does not display the function documentation in several cases

### ISSUE THREAD

**Issue by GitHunter0** [microsoft/pylance-release#4603]
<h3> Environment data </h3>

-   Language Server version: 2023.7.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off
-   VScode: 1.80.0
- Python 3.10.4 (but I also tested in 3.6 - 3.11)

Hey folks, in many cases, `Pylance` does not provide the proper documentation for a function or method.

Please, consider this example:
```python
import datar.all as d
import pandas as pd
df = pd.DataFrame({'x':[1,2,4]})
d.glimpse(df)
```

<h3> Actual  behavior </h3>
When the cursor is on `glimpse`, I don't get the proper documentation, `Pylance` only shows `(function) glimpse: Any` as below:

![image](https://github.com/microsoft/pylance-release/assets/26294221/843cb885-c33d-49f7-b967-304cbe8e00a8)   

However, when the cursor is on `DataFrame`, `Pylance` displays the full documentation, which is the expected behavior:
![image](https://github.com/microsoft/pylance-release/assets/26294221/30b583fa-0335-4b13-90e1-e4069244d6c4)

<h3> Expected behavior </h3>

`Pylance` should provide the complete documentation (including the docstring) with this info:
![image](https://github.com/microsoft/pylance-release/assets/26294221/fcf7fc6c-5761-4f50-b047-b26215edb850)

The lack of proper documentation display is the most essential issue with VScode for python in my experience. 

Thank you, any effort in this regard will be much appreciated.

**Comment by debonte** [comment]
Pylance doesn't support the dynamic manner in which the `datar.all` module is populated. The patterns we support for libraries to expose their interfaces are described [here](https://microsoft.github.io/pyright/#/typed-libraries?id=library-interface). If you'd like `datar` to be better supported by static analysis tools, I'd encourage you to file an issue about this in [their issue tracker](https://github.com/pwwang/datar/issues).

In the meantime, you can work around this by changing your import to `import datar.dplyr as d` since `dplyr.py` imports `glimpse` via a wildcard import (`from .apis.dplyr import *`) which we do support.
