### ISSUE TITLE
Should Pylance flag potential class member as an error within conditional check?

### ISSUE THREAD

**Issue by egeres** [microsoft/pylance-release#4621]
```python
class A:
    def __init__(self) -> None:
        foo : int = 1

my_a = A()

if getattr(my_a, "faa", None) is not None:
    print(my_a.faa)
```

Such code throws the following error at `my_a.faa`:

```
Cannot access member "faa" for type "A"
  Member "faa" is unknown
```

Even if the property `faa` is not a member of the `A` class, the `if` would indicate that such member exists at that code block, in the `my_a` instance. **Should Pylance flag this as an error?**

- Nothing really prevents a decorator or other patterns to alter the members of a class in a way that might be hidden from the explicit `__init__` definitions, so one could say this is a bug on the Pylance side because statically analyzing the `if` would reveal that such a member would exist
- On the other hand, this might lead to spaghetti code and could go against Pylance principle's of just statically analyzing what has been defined

**Comment by erictraut** [comment]
Yes, this is intentional. The type of `my_a` is `A`. The `getattr` call does nothing to change this type (i.e. it's not narrowed in any way), and the class `A` doesn't define any attribute called `faa`, so a static type checker will flag this as an error. Not surprisingly, mypy also generates the same error.

For more details about type narrowing, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced). 

If you're not interested in static type checking, you can disable these errors in pylance by setting `python.analysis.typeCheckingMode` to "off".

**Comment by egeres** [comment]
Thank you so much (again)!!
