### ISSUE TITLE
subtract of BDay results in days instead of pd.Timestamp

### ISSUE THREAD

**Issue by alippai** [microsoft/pylance-release#4631]
## Code Snippet
```python
from pandas.tseries.offsets import BDay
import datetime

(datetime.date(2023,1,1) - BDay(7)).date() # this line reports `.date()` is not a member of `date`, but actually it's a `pd.Timestamp` and the code works, only Pylance in VSCode has a false positive
```

**Comment by debonte** [comment]
Pylance is working correctly here. We include the latest [`pandas-stubs`](https://github.com/pandas-dev/pandas-stubs) in every Pylance release. In `pandas-stubs`, `BDay` inherits (indirectly) from `BaseOffset` which [has the following `__rsub__` overload](https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/_libs/tslibs/offsets.pyi#L63):

```python
_DatetimeT = TypeVar("_DatetimeT", bound=date)

# some lines removed for clarity

@overload
def __rsub__(self, other: _DatetimeT) -> _DatetimeT: ...
```

`date` doesn't have a `__sub__` overload that handles pandas types (which makes sense since `date` comes from the stdlib), so we look for a matching `__rsub__` and find this one which tells us that the result of a "`date` - `BDay`" subtraction operation will be a `date`.

If you feel that the stubs are incorrect, please file an issue on [`pandas-stubs`](https://github.com/pandas-dev/pandas-stubs/issues).

**Comment by alippai** [comment]
@debonte: indeed, the stub seems to be incorrect. Thanks for pointing me to the right direction.
