### ISSUE TITLE
Return arrow gets wrongly colored when using Type Parameter Syntax introduced in python3.12

### ISSUE THREAD

**Issue by yotaro-shimose** [microsoft/pylance-release#4645]
Hi. I love how pylance works with latest typing features. Thank you maintainers.
Here I'd like to post a bug report.

## Environment data

-   Language Server version: v2023.7.31
-   OS and version: Public python docker image python:3.12.0b4-bulluseye
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.0b4

## Code Snippet

```python
from dataclasses import dataclass
from typing import Self


@dataclass
class MyInt:
    value: int
    def __add__(self, other: Self) -> Self:
        return MyInt(self.value + other.value)


def add[T: MyInt](a: T, b: T) -> T:
    return a + b


if __name__ == "__main__":
    print(add(MyInt(value=3), MyInt(value=4)))

```

## Repro Steps
1. Start the container pulled from the official python repository with the above mentioned tag.
2. Attach to it using vscode remote-development extension.
3. Install the python extension.
4. Paste the code above and let the pylance analyze it.

## Expected behavior

I expected the color of the return arrow of add function to be white, 

## Actual behavior
it becomes red, which is very confusing.
![image](https://github.com/microsoft/pylance-release/assets/65691831/ab67ce75-9138-4152-beaf-f44252584d0d)

By the way, when I stop using custom MyInt class and typehint without type parameter syntax, this behaviour goes away.
![image](https://github.com/microsoft/pylance-release/assets/65691831/aca5ec84-beb6-4600-b30d-1d873cb71e73)

**Comment by erictraut** [comment]
The coloring issue here is a bug in the core Python extension, not in Pylance. The Python extension includes a TextMate grammar that is used for basic syntax coloring. It needs to be updated to support the new syntax extensions introduced in PEP 695. Could one of the pylance team members please transfer this bug?

**Comment by rchiodo** [comment]
I think the textmate grammar actually ships with VS code. But I believe we're (pylance) the ones who usually update it. It's here:
https://github.dev/microsoft/vscode/blob/08235aac22b640c5e25b83bf25831a0f566e3fd1/extensions/python/syntaxes/MagicPython.tmLanguage.json

**Comment by erictraut** [comment]
Ah, that's even better. Then you can fix it directly. :)

**Comment by rchiodo** [comment]
This might help to figure out how to get the write tmlanguage changes:
https://github.com/maelvls/grammar-debug

**Comment by StellaHuang95** [comment]
closing it but made it sub item of bigger work (shipping textmate grammar ourselves - https://github.com/microsoft/pyrx/issues/4026)

**Comment by dangotbanned** [comment]
Hi, I've been unable to find anymore information on PEP 695 syntax colouring since this this issue closed. The [issue](https://github.com/microsoft/pyrx/issues/4026) referenced above seems to be from a private repository.

Is there anywhere I can find more information on progress towards improved type parameter syntax highlighting support? 

Particularly the soft keyword `type`, as parameters/aliases created with this have no colour at all. I find myself gravitating towards the deprecated `TypeAlias` in some cases, since that is at least highlighted as a variable.

**Comment by debonte** [comment]
@dangotbanned, VS Code ships [a TextMate grammar](https://github.com/MagicStack/MagicPython) that rarely fixes issues. Their last commit was more than a year ago. In the past we've resolved TextMate issues as external bugs against that grammar but that's basically equivalent to saying that those issues will never get fixed. So we're currently thinking that we should maintain and ship our own grammar and fix any issues ourselves. The work has not started yet and it's probably better owned by vscode-python rather than Pylance. I agree that the work should be tracked by a public GitHub issue. Once the work is assigned to a team, we should create an issue either in vscode-python or pylance-release.

**Comment by dangotbanned** [comment]
@debonte thanks for the info.

**Comment by CaselIT** [comment]
Any update on this issue? it's still happening in vscode 1.100

**Comment by debonte** [comment]
@CaselIT, https://github.com/microsoft/pylance-release/issues/5824 is tracking our plans around replacing TextMate. We're currently blocked waiting for https://github.com/microsoft/vscode/issues/210475.

**Comment by CaselIT** [comment]
thanks for the update!
