### ISSUE TITLE
Autocomplete stopped working on local class members

### ISSUE THREAD

**Issue by BabakAmini** [microsoft/pylance-release#4658]
## Environment data
-   Language Server version: v2023.7.40
-   OS: Windows 11
-   Python version: 3.11

## Code Snippet
```python
from aiohttp import ClientSession

class MyClass:
    a = 0
    b: int

    def __init__(self) -> None:
        self.c = 0

    async def d():
        pass

async def func():
    async with MyClass() as mc:
        mc.a = 1
```

## Repro Steps
1. Type `mc.` followed by Ctrl+Space. There is no autocomplete suggestion (the `mc` class instance is found, but none of the local class members are accessible via autocomplete).
2. Change `async with MyClass() as mc:` to `async with ClientSession() as mc:` and try again. Autocomplete is working now.
3. Uninstall or disable the Pylance extension and reload VS Code. Now autocomplete works for the local class as expected but this time none of the `ClientSession` class members appears in the suggested list.

## Expected behavior

Autocomplete works for local class instances.

## Actual behavior
Below is what is happening when the Pylance is installed:

<p align="center">
  <img src="https://github.com/microsoft/pylance-release/assets/85762931/a790c5ac-ec35-4f6f-b3a6-2effd4ff0858" width="50%" height="50%">
</p>

And without Pylance:

<p align="center">
  <img src="https://github.com/microsoft/pylance-release/assets/85762931/bd05867d-2832-413c-9c3e-b3a00a971020" width="50%" height="50%">
</p>

- Everything was working well, and these issues appeared for no reason by yesterday.
- I'm running my code on a remote server, but I have the same issue on the local project as well.
- These issues exist in both Python files and Jupyter notebooks.
- Adding `"python.languageServer": "Default"` or `"python.languageServer": "Pylance"` to the `settings.json` didn't help.
- Updating VS Code and all the extensions including Pylance (both the latest stable and preview releases) didn't help as well.

**Comment by erictraut** [comment]
Your class `MyClass` doesn't support the async context manager protocol, so it's invalid to use here. If you attempt to run your code, it will crash at runtime. To make this work, you would need to implement an `__aenter__` and `__aexit__` method in `MyClass`. The `__aenter__` should return the context manager type, which provides the type to the variable `mc` in the statement `async with MyClass() as mc`.

If you enable type checking (set `python.analysis.typeCheckingMode` to "basic") in pylance, it will tell you about errors like this.

<img width="628" alt="image" src="https://github.com/microsoft/pylance-release/assets/7040122/71e08f72-f282-4a32-b052-8c0768f35e0b">

**Comment by erictraut** [comment]
Have you tried adding both an `__aenter__` and `__aexit__`? Both are required. If I add both of them, completion suggestions appear as expected. If I omit either of these methods, the code crashes at runtime if I call `func`.

```python
from types import TracebackType

class MyClass:
    a = 0
    b: int

    def __init__(self) -> None:
        self.c = 0

    async def d(self):
        pass

    async def __aenter__(self) -> "MyClass":
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        pass

async def func():
    async with MyClass() as mc:
        mc.a = 1
```

**Comment by erictraut** [comment]
Do you see the red squiggle under `MyClass()` in your screen recording? Pylance is telling you that you have a bug in your code. You need to fix that bug if you want your code to run without crashing. You also need to fix that error for type completions to work for `mc`. The type of the variable `mc` depends on the behavior of your `__aenter__` and `__aexit__` methods. If you don't define those methods, pylance cannot offer completion suggestions here. When a language server like pylance returns zero completion suggestions, VS Code offers some of its own suggestions based on other identifiers that it sees in the same file. That's what you're observing in this case.

Inside the class, you will get completions for methods that you are overriding from a base class. In your case, the only base class for `MyClass` is `object`, and the `object` class doesn't provide a `__aenter__` or `__aexit__` method, so you won't see any completion suggestions for these methods. The `object` class does define an `__init__` and `__init_class__` method, so pylance offers these as override suggestions.

Since `MyClass` is intended to be an async context manager, it should probably derive from the abstract base class `typing.AsyncContextManager`. If you do this, you'll then see override completion suggestions for `__aenter__` and `__aexit__`.

<img width="528" alt="image" src="https://github.com/microsoft/pylance-release/assets/7040122/06c626dd-a957-455e-8d36-7d605bfa3681">

Pylance appears to be working as designed. I don't see any bugs based on the behaviors you're observing. If there's a different behavior that you'd like to see, please consider filing an enhancement request.
