### ISSUE TITLE
Invalid type hints for decorators applied to class methods

### ISSUE THREAD

**Issue by sralloza** [microsoft/pylance-release#4659]
## Environment data

-   Language Server version: v2023.7.40
-   OS and version: Macbook pro M1 Ventura 13.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2

## Code Snippet

```python
from __future__ import annotations

import functools
from typing import Callable, Concatenate, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

Transactionable = Callable[Concatenate[type["Service"], P], R]


def ensure_login(func: Transactionable[P, R]) -> Transactionable[P, R]:

    @functools.wraps(func)
    def wrapper(
        cls: type[Service], /, *args: P.args, **kwargs: P.kwargs
    ) -> R:
        if not cls._logged:
            cls._login()
        return func(cls, *args, **kwargs)


    return wrapper


class Service:
    _logged = False
    @classmethod
    def _login(cls) -> None:
        cls._logged = True
        print("Logging in...")

    @classmethod
    @ensure_login
    def create_app(cls, *, name: str, msisdn: str) -> None:
        print(f"Created app {name} with msisdn {msisdn}")


Service.create_app(name="test", msisdn="123")

```

## Repro Steps

1. Write the previous code in a file
2. Set the setting "Python › Analysis: Type Checking Mode" to "basic"

## Actual behavior

Pylance shows a warning in the line 34 (when applying the `@ensure_login` decorator to the `Service.create_app` classmethod. Mypy doesn't complain about any error with the --strict flag.

**Comment by erictraut** [comment]
The issue is that the type of parameter is unannotated. In this case, its type is inferred to be `type[Self]`, not `type[Service]`. The former preserves the ability for a class method to be used in a subclass. Mypy doesn't currently handle this correctly, which is why you're seeing a different behavior. A parameter with `type[Self]` will not work with `Transactionable` in your example because parameters are contravariant, and `type[Service]` is not a subtype of `type[Self@Service]`. The converse is true.

If you want this to work with pyright (which is the type checker upon which pylance is built), you would need to do one of the following:

1. Add an explicit type annotation for the `cls` parameter: `cls: "type[Service]"`. 
2. Change the definition of `Transactionable` to use an `Any`: `Transactionable = Callable[Concatenate[Any, P], R]`.
