### ISSUE TITLE
Function return type hints cannot be disabled

### ISSUE THREAD

**Issue by MagnusOxlund** [microsoft/pylance-release#4661]
The option `"python.analysis.inlayHints.functionReturnTypes": false` doesn't seem to have any effect.

Function return type inlay hints are displayed on autocomplete regardless of toggle state in the example below.

This may be related to #2593 

![bug](https://github.com/microsoft/pylance-release/assets/10921083/ed99fb44-f716-402a-a9f2-ed92395907a3)

<h3> Environment data </h3>

-   Language Server version: 2023.7.40
-   OS and version: MacOS 12.6.6 x64
-   Python version: 3.10.5 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off
-   VS Code version: 1.80.2

**Comment by StellaHuang95** [comment]
Thanks for the issue. The `inlayHints.functionReturnTypes` controls whether to display inlay hints for function return types. These hints do not alter your code, they only provide additional information to the editor’s user interface. For example, when you type `class Test:
    def __init__(self):
        pass` with `inlayHints.functionReturnTypes` enabled, you will see the relevant inlay hints being displayed like this. 
![image](https://github.com/microsoft/pylance-release/assets/100439259/fad06e66-3739-4376-895f-5423be351040)
What you're describing in the issue comes from autocompletion. At the moment, disabling the return type from `__init__` is not supported. Please upvote [this enhancement request](https://github.com/microsoft/pylance-release/discussions/2593) so that it gets properly prioritized. Thanks.

**Comment by MagnusOxlund** [comment]
May I suggest updating the image shown in the preferences to include a background color around the inlay hint?

It might help other users avoid making the assumption I did. I had never enabled—and so never seen—type hints at the time. In the current image, the inlay hint looks indistinguishable from a return type annotation that's part of the actual document:

<img width="436" alt="Screen Shot 2024-02-07 at 6 37 14 PM" src="https://github.com/microsoft/pylance-release/assets/10921083/390c384a-69cb-424f-a310-2092c73c6134">
