### ISSUE TITLE
Pylance not finding venv modules what venv is active

### ISSUE THREAD

**Issue by highghlow** [microsoft/pylance-release#4679]
<h3> Environment data </h3>

-   Language Server version: 2023.7.40
-   OS and version: linux x64 (immutable)
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.11.3 (pacman, venv)
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
import numpy # venv is selected, code runs without an error, but pylance reports reportMissingModuleSource
print(numpy.__doc__)
```

<h3> Repro Steps </h3>

1. Create and activate a venv
2. Install a package into the venv
3. Write python code that uses that module

<h3> Expected behavior </h3>

Pylance should see that the venv is active and find the module

<h3> Actual behavior </h3>

Pylance reports reportMissingModuleSource

<h3> Logs </h3>

[python-language-server-log.txt](https://github.com/microsoft/pylance-release/files/12241575/python-language-server-log.txt)

**Comment by escummy** [comment]
I also received similar an error on my IDE VSCode and currently using mac m1.

First we need to make sure that the python3 interpreter version from terminal version is the same with our python version selection in VSCode.

I think I get it, if you open terminal and type 'python3' you'll see your python version (python3 version is 3.11.3), then open your IDE VSCode and navigate until any/current folder that related to python project on IDE, check your python version at the bottom right on IDE VSCode for example (in my case the python version is 3.11.3).

> The solution is changing or switching VSCode python version from 3.11.3 to 3.9.12 (same with your python version on your pc) and it's solved.

> Also, you can click on the interpreter version at the bottom left corner of the screen (VSCode for example) it should show a dropdown menu with a list of the available and selected python interpreter, click on add interpreter path and paste the path to the python interpreter with all the required modules installed and click enter.

Originally, I tried to install the pandas by the following command.

```bash
sudo apt-get install python3-numpy
````

Numpy was installed successfully as stated in the terminal but the problem is still there, but when I try to install pandas by the following command, the problem solved.

```bash
pip install pandas
```

Let me know, this should resolve the problem.

**Comment by StellaHuang95** [comment]
This message means that you don't have numpy installed in the Python environment that is currently selected. From reading your logs, the interpreter you have selected appears to be 3.10, which is different from the python version described in the issue. Could you check if that's the interpreter you've installed numpy into? If you look at the bottom right corner of the window, you should see which environment is selected. 
![image](https://github.com/microsoft/pylance-release/assets/100439259/ee78b773-f988-41d4-91b2-9d94b89ec134)



You can also refer to this guide on selecting your environment. https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

**Comment by highghlow** [comment]
This is really strange. The Python interpreter selected is `3.10.11 ('.venv': venv)`, but if I run the python executable from the venv, it says 3.11.3
![image](https://github.com/microsoft/pylance-release/assets/132668972/66f478e6-0321-4583-8622-6fe37e52d5d6)

**Comment by StellaHuang95** [comment]
You have `Setting pythonPath for service "MQTTSmartHome": "/mnt/disk/Projects/Hobby/MQTTSmartHome/venv/bin/python"` in your logs. Please refer to this guide on selecting your environment. https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

**Comment by highghlow** [comment]
> You have `Setting pythonPath for service "MQTTSmartHome": "/mnt/disk/Projects/Hobby/MQTTSmartHome/venv/bin/python"` in your logs. Please refer to this guide on selecting your environment. https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

I was working in `venvbug` whan reproducing the issue. There the venv is properly selected. SmartHome is unrelated to the issue

**Comment by mg-takuma-katanosaka** [comment]
I hit same issue.

**Comment by mg-takuma-katanosaka** [comment]
> I hit same issue.

I've changed pre-release version because I expected to fix this issue. I look fixing to me.

**Comment by StellaHuang95** [comment]
Hi there, can you verify if the problem still persists using the latest pylance? The `reportMissingModuleSource` diagnostic happens when a type stub is found, but the module source file was not found, indicating that the code may fail at runtime when using this execution environment. So you should be seeing the error if you have the package installed in your activated environment. Please reopen the issue if it still persists. Thanks!
