### ISSUE TITLE
Code should not be marked as unreachable in certain situations

### ISSUE THREAD

**Issue by cperezabo** [microsoft/pylance-release#473]
## Environment data

-   VS Code version: 1.50.0
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: macOS 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Remote Container, no venv.
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

The code should not be marked as unreachable when it is perfectly reachable 

## Actual behaviour

<img width="529" alt="CleanShot 2020-10-09 at 12 15 53@2x" src="https://user-images.githubusercontent.com/3604722/95658638-563af580-0af2-11eb-9acc-f44afddfd2f4.png">

As you can see, the above code is marked as unreachable just because `dangerous` raises an exception. 
I am justly testing that stack.capture() captures the exception. I think is not correct to mark the code as unreachable when there is a context manager that can handle the exception.

**Comment by erictraut** [comment]
A type checker needs to be told that your context manager can handle exceptions. Most of them do not.

Type checkers (including mypy and pyright/pylance) have adopted a convention whereby if the `__enter__` method is annotated to return a `bool`, it is assumed that the context manager handles exceptions. Refer to [this thread](https://github.com/python/mypy/issues/7214) for details.

**Comment by cperezabo** [comment]
Annotate `__enter__` to return a bool? Doesn't make sense but I have tried it anyways and doesn't work. 
And if it were, what about `@contextmanager` decorator? you can't annotate `__enter__`

**Comment by erictraut** [comment]
Sorry, the thread I referenced said `__exit__`, not `__enter__`. You're correct that this technique wouldn't work with the `@contextmanager` decorator. There's really no good solution here. If a static analyzer assumes that all context managers catch all exceptions, that will cause a different set of problems. Since most context managers do not catch all exceptions, it's better to assume that they don't unless informed otherwise.

Here's another simple workaround for your particular case. You can provide a `None` return type annotation for the `dangerous` method. Because your code doesn't provide a return type declaration, pylance is inferring the return type. And in this case, it's inferring a `NoReturn` because all of the code paths raise an exception.

```python
def dangerous() -> None:
    raise FakeException
```

**Comment by cperezabo** [comment]
You are right, annotating it with `None` does the job!
