### ISSUE TITLE
Using magic method `__bool__` to narrow down type does not work

### ISSUE THREAD

**Issue by MiikaLau** [microsoft/pylance-release#4807]
I'd like to use the magic method `__bool__` to differentiate between "good" responses and "bad" responses. Using the pattern provided in the code example however does not seem to work.

<h3> Environment data </h3>

-   Language Server version: 2023.8.50
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.5
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import random


class TestTrue:
    value: str

    def __init__(self, value: str):
        self.value = value

    def __bool__(self) -> bool:
        return True


class TestFalse:
    value: int

    def __init__(self, value: int):
        self.value = value

    def __bool__(self) -> bool:
        return False


test = random.choice([TestTrue("true"), TestFalse(0)])


def print_string(val: str):
    print(val)


if bool(test) is True:
    # type of value shown in vscode "str | int"
    value = test.value

    # Argument of type "str | int" cannot be assigned to parameter "val" of type "str" in function "print_string"
    # Type "str | int" cannot be assigned to type "str"
    print_string(value)

```

**Comment by erictraut** [comment]
To make this work, you need to make the following changes to your code:
1. Change the declared return types of your `__bool__` methods from `bool` to `Literal[True]` and `Literal[False]`, respectively.
2. Change your conditional expression from `bool(test) is True` to `bool(test)` or simply `test`.

The first change is needed to tell a static type checker that your `__bool__` methods will return only `True` and `False`.

The second change is needed because `bool(test) is True` is not a type guard pattern that is supported by pyright, the static type checker upon which pylance is built. For a full list of supported type guards, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards).

**Comment by MiikaLau** [comment]
Thanks! This works as expected. Should've dug a bit deeper, I tried the `Literal[True]` and `Literal[False]` and replacing the `bool(test) is True` but not with both together it seems...

Sorry for bothering 😶
