### ISSUE TITLE
[question] How do pylance handle explicitly type annotation?

### ISSUE THREAD

**Issue by Cologler** [microsoft/pylance-release#482]
Example 1:

``` py
class ProxyType:
    def __init__(self, target):
        self.target = target
    def __getattr__(self, name):
        return getattr(self.target, name)

a: dict = ProxyType({}) # pylance reported type `ProxyType`
```

Example 2:

``` py
a: str = '' if True else 0 # pylance reported type `str | int`
```

**Comment by Cologler** [comment]
Currently, I have to use `typing.cast` to cast all such types.

**Comment by erictraut** [comment]
You are using variable type annotations incorrectly. When you apply a type annotation to a variable, you are declaring its type. If you then attempt to assign a value to that variable with an incompatible type, it is considered a type error, and the type checker will flag it as such.

For example, if you declare that `a` must contain a `dict` but then attempt to assign a `ProxyType` to it, a type checker will tell you that it is a type violation.

The same is true for your second example. You have declared that `a` must be a `str`, but then you attempt to assign an `int` to it.

For details about how type checking and type annotations work, please refer to PEP 484 and PEP 526. For additional details, refer to the [pyright documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md). Pyright is the open-source type checker at the heart of pylance.

**Comment by Cologler** [comment]
@erictraut 

I see.

- So is there a way to use auto-completion on `ProxyType`?

**Comment by erictraut** [comment]
I'm not sure what you mean by "use auto-completion". If you have a variable `a` that is of type `ProxyType`, pylance will automatically provide auto-completion suggestions if you type `a.`. For example, if `ProxyType` had a method called `foo`, the symbol `foo` would appear in the suggestion list that appears when you type `a.`.

Is your intent that ProxyType is a subclass of `dict`? If so, it should be a proper subclass, like this:
```python
class ProxyType(dict):
   ...
```

Or more properly, since `dict` is a generic class, you would probably also want ProxyType to be generic, like this:
```python
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
class ProxyType(Dict[_KT, _VT]):
    ...
```

I guess I'm not clear on what your intent is with `ProxyType`. If you provide more details, I might have additional suggestions.

**Comment by Cologler** [comment]
@erictraut

Just like the `Proxy` object in typescript, which can proxy any type of target without losing their properties.

![image](https://user-images.githubusercontent.com/10906962/95823269-ddd96c00-0d5f-11eb-84c7-849127014eeb.png)

**Comment by Cologler** [comment]
This worked, but look ugly: 

![image](https://user-images.githubusercontent.com/10906962/95824449-e632a680-0d61-11eb-99cb-6a34c002a397.png)
