### ISSUE TITLE
Don't warn on structurally overlapping TypedDicts

### ISSUE THREAD

**Issue by stationname** [microsoft/pylance-release#4824]
( There's a chance my "bug" is considered a "feature", so I'll post it as feature)

Consider the following code. `A1` has a *loose* definition of `a` while `A2` has a *strict* definition of `a`. Their structure overlaps, so `{"a": 1}` could be considered as either one.
```
class A1(TypedDict, total=False):
   a: int

class A2(TypedDict):
   a: int
```

The following code triggers an error/issue `"a" is not required in "type[A1]"`.  
```
def run(param: A1):
   print (param)

var: A2 = {"a": 1}
run(var)
```

**Suggestion**: 

Don't warn in these cases.

**Reasoning**:

Working around this kind of problem might include static type casting or the use of `Any`, which will make the code more prone to problems and less readable.

**Comment by erictraut** [comment]
Pyright (the type checking upon which pylance is built) is correct in flagging this as a type violation.

The problem is that with type `A2`, the key `a` must exist and cannot be deleted. With type `A1`, `a` can be deleted.

```python
def run(param: A1):
    del param["a"] # This is allowed for A1 but not for A2

var: A2 = {"a": 1}
run(var)
print(var["a"]) # Crash!
```

Not surprisingly, mypy also generates the same error for your code sample.

Refer to [PEP 589](https://peps.python.org/pep-0589/) for details about how `TypedDict` works.

**Comment by stationname** [comment]
Thank you very much for taking the time to explain! 🙇

I indeed did oversee the mutability of the object. 

So my proposal would only be possible if immutability of the object could be guaranteed.
