### ISSUE TITLE
intellisense for cv2 is not working

### ISSUE THREAD

**Issue by ukalwa** [microsoft/pylance-release#4838]
cv2 intellisense seemed to have stopped in the latest releases. I don't see cv2 stubs bundled in vscode server pylance extension
`/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.9.10/dist/bundled/native-stubs` as I only see `lxml`, `pandas` and `numpy` in there. This was also not documented in the CHANGELOG.md of pylance-release so I assume it is a bug.

I tried both opencv-python and opencv-python-headless and the issue was the same. Then I came across [this issue comment](https://github.com/microsoft/pylance-release/issues/138#issuecomment-732839293) where it said that typings are bundled by pylance and that's when I knew it was a pylance issue.

I encountered the same issue even in pylance pre-release version (`2023.9.12`)

## Repro Steps

- Install opencv by running `pip install opencv-python==4.7.0.72`

![image](https://github.com/microsoft/pylance-release/assets/11986128/069c4981-274a-4161-a670-cd242d88a1ac)

## Environment data

-   Language Server version: 2023.9.10
-   OS and version: Host OS - Mac M1, Devcontainer - Ubuntu 22.04 on aarch64
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12

## Expected behavior

intellisense should work for cv2

## Actual behavior

It used to work but it doesn't anymore

**Comment by debonte** [comment]
The `cv2` stubs were [removed intentionally](https://github.com/microsoft/python-type-stubs/pull/292) because `opencv-python` now ships their own stubs. You can get them by upgrading to `opencv-python` `4.8.0.76`.

If you need our old `cv2` stubs, you can get them from https://github.com/microsoft/python-type-stubs. https://github.com/microsoft/python-type-stubs/commit/1add73961cc8251a8b2dad5e46ee8d78a9f260f8 was the last commit before they were removed.

Apologies for not mentioning this in the changelog.

**Comment by ukalwa** [comment]
Ah, ok. That makes sense and thanks for the quick response.
