### ISSUE TITLE
`dataclass` not recognized in `fields` function when it is not applied as decorator 

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#4843]
## Environment data

-   Language Server version: 2023.9.10
-   OS and version: Windows 10
-   Python version: 3.10.9 Anaconda

### Code Snippet

```python
from dataclasses import dataclass, fields

class Test:
    ...

Test = dataclass(Test)

f = fields(Test) # -> Error!
```

### Screenshot:

![image](https://github.com/microsoft/pylance-release/assets/57204023/fecc2ae2-b95a-45ea-8041-cef7d66f7d54)

### Error message:
```
Argument of type "type[Test]" cannot be assigned to parameter "class_or_instance" of type "DataclassInstance | type[DataclassInstance]" in function "fields"
  Type "type[Test]" cannot be assigned to type "DataclassInstance | type[DataclassInstance]"
    "__dataclass_fields__" is not present
    "Test" is incompatible with protocol "DataclassInstance"
    Type "type[Test]" cannot be assigned to type "type[DataclassInstance]"
      "__dataclass_fields__" is not present
```

## Expected behavior

The same as using `dataclass` as decorator (raises no error).

```python
from dataclasses import dataclass, fields

@dataclass
class Test:
    ...

f = fields(Test) # -> No Error

```

![image](https://github.com/microsoft/pylance-release/assets/57204023/6581ab43-488d-4905-bf60-b9dcdf4ee257)

**Comment by erictraut** [comment]
The handling of `dataclass` within a static analysis tool requires significant special-casing because some parameters of the dataclass must be determined statically. For example, passing `init=False` or `frozen=True`, the type checker needs interpret those values and treat the decorated class differently. It uses this information to simulate all of the "magic" that is performed at runtime by the `dataclass` function. This "magic" synthesizes a bunch of attributes and methods for the decorated class, but the exact behavior depends on the parameters that are used. For these reasons, you must use the `dataclass` call as a class decorator if you want it to work with static type checkers. 

If you don't want to use static type checking, you can disable it by setting `python.analysis.typeCheckingMode` to "off", and you will not see any type-related errors.

Note that the `dataclass` function modifies the original class, so if you use `Test1 = dataclass(Test2)`, the `Test2` class will be modified, and a copy of the modified class will be passed back and assigned to `Test1`. That means the result of applying the class decorator directly to the class versus calling `dataclass(Test)` after the class has been defined is the same.
