### ISSUE TITLE
Argument type is partially unknown with *args: T | Iterable[T]

### ISSUE THREAD

**Issue by carlos-souto** [microsoft/pylance-release#4851]
I am not sure if this is a bug or if I am missing something, but in the snippet below, the "Argument type is partially unknown" issue is shown when using a generic type parameter; however, when using a specific type, e.g., "int", no issue is raised.

## Environment data

-   Language Server version: v2023.9.10
-   OS and version: Windows 11
-   Python version: Python 3.11.4

## Code Snippet

```python
# pyright: strict

from typing import TypeVar
from collections.abc import Iterable

T = TypeVar("T")

def join_all(*args: T | Iterable[T]) -> list[T]:
    joined: list[T] = []
    for arg in args:
        if isinstance(arg, Iterable): joined.extend(arg) # Argument type is partially unknown
        else: joined.append(arg)
    return joined

test = join_all(1, 2, 3, [4, 5, 6], 7, 8, 9, [10, 11, 12])
print(test) # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]



# while this raises no issues (T replaced by int):

def join_all_int(*args: int | Iterable[int]) -> list[int]:
    joined: list[int] = []
    for arg in args:
        if isinstance(arg, Iterable): joined.extend(arg)
        else: joined.append(arg)
    return joined

test = join_all_int(1, 2, 3, [4, 5, 6], 7, 8, 9, [10, 11, 12])
print(test) # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

```

## Logs

Attached.

[log.txt](https://github.com/microsoft/pylance-release/files/12675038/log.txt)

**Comment by erictraut** [comment]
Yes, this is the correct behavior. The type of `arg` is `T | Iterable[T]`. When you use an `isinstance` check, this is narrowed to `Iterable[Unknown] | Iterable[T]`. That's because `T` could be an iterable of some sort (e.g. a `list` or a `dict`), and the type argument cannot be determined statically for such a type. In your second example, you've replaced `T` with `int`, and `int` has no overlap with `Iterable`, so the `isinstance` check will always return `False` in that case.

**Comment by carlos-souto** [comment]
Thanks, now I understand why this is the wanted behaviour. The problem in the code becomes obvious if instead of replacing `T` by `int`, `T` is replaced by some collection like `list[int]`.
