### ISSUE TITLE
Formatting of tooltips in notebook

### ISSUE THREAD

**Issue by maurosilber** [microsoft/pylance-release#4859]
Mostly this same issue reported before: https://github.com/microsoft/vscode-python/issues/17932, but for the notebook interface.

The rendering of the tooltip is not much helpful with long and typed signatures. But that only happens when typing on the cell, not when hovering with the mouse:

https://github.com/microsoft/vscode-jupyter/assets/9124827/52a4767f-8b90-4400-993f-37d29a809b2a

I think it would be great if the second tooltip that appears matches the last one, where each parameter is in its own line and there's synatx highlighting separating type annotations from parameter names.

Thank you!

**Comment by StellaHuang95** [comment]
Hi @DonJayamanne, thanks for your issue. This is by design. As you write a Python function call, VS Code shows information about the function signature and highlights the parameter that you are currently completing. Pylance doesn't have control over how the function signature is displayed. Please open an issue in vscode repo if you'd like to see it being displayed differently.

**Comment by maurosilber** [comment]
Can it be moved back to [vscode-jupyter](https://github.com/microsoft/vscode-jupyter) or whichever repo is in charge of formatting of the notebook's function signature tooltip?

**Comment by debonte** [comment]
@maurosilber, https://github.com/microsoft/vscode/issues would be the right issue tracker for this. However, rather than just moving this issue there, I think you'll get a better response if you create a new issue and replace the video with two static screenshots making it more clear what you are requesting (actual behavior and desired behavior). Also I'd suggest updating the description of the issue to use the standard terminology for the two features -- hover (where each parameter can be on its own line) and signature help (where it cannot). The main VS Code repo receives a lot of issues, so the clearer you make your feature request, the more likely you will get up-votes from other users and the more up-votes you get the more likely the team will act on it.
