### ISSUE TITLE
Problem with partial and contextvars.Context.run

### ISSUE THREAD

**Issue by kltws** [microsoft/pylance-release#4867]
## Environment data

-   Language Server version: 2023.9.21
-   OS and version: Windows 10
-   Python version: 3.7.9

## Code Snippet
Backporting the following asyncio method to a Python 3.7 project
```python
from asyncio import get_running_loop
from contextvars import copy_context
from functools import partial
from typing import Callable, TypeVar
from typing_extensions import ParamSpec

_P = ParamSpec("_P")
_R = TypeVar("_R")

async def to_thread(func: Callable[_P, _R], *args: _P.args, **kwargs: _P.kwargs) -> _R:
    """Asynchronously run function *func* in a separate thread.

    Any *args and **kwargs supplied for this function are directly passed
    to *func*. Also, the current :class:`contextvars.Context` is propagated,
    allowing context variables from the main thread to be accessed in the
    separate thread.

    Return a coroutine that can be awaited to get the eventual result of *func*.
    """
    loop = get_running_loop()
    ctx = copy_context()
    func_call = partial(ctx.run, func, *args, **kwargs)
    return await loop.run_in_executor(None, func_call)
```
I get the following typing error at the return line:
```
Expression of type "_T@run" cannot be assigned to return type "_R@to_thread"
  Type "_T@run" cannot be assigned to type "_R@to_thread"
```
Specifying the type of partial doesn't work either:
```python
func_call: partial[_R] = partial(ctx.run, func, *args, **kwargs)
```
```
Expression of type "partial[_T@run]" cannot be assigned to declared type "partial[_R@to_thread]"
  "partial[_T@run]" is incompatible with "partial[_R@to_thread]"
    Type parameter "_T@partial" is invariant, but "_T@run" is not the same as "_R@to_thread"
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) has a bunch of special-case logic to handle common usage of `functools.partial`, but this logic doesn't extend to calls with `*args`, `**kwargs` or ParamSpecs. In those cases, it falls back on the default type logic for `functools.partial` as indicated by the `functools.pyi` type stub. That's what's happening here, since your usage goes well beyond what pyright handles.

For comparison, mypy also special-cases logic for `functools.partial`, and it also doesn't handle `*args`, `**kwargs` or ParamSpecs.

In your code sample, you're using `functools.partial` where it's not really necessary. It's acting as an expensive variant of a lambda. If you change your code to simply use a lambda, it will type check without error.

```python
    func_call = lambda: ctx.run(func, *args, **kwargs)
```

**Comment by kltws** [comment]
Thank you for the reply. For my use case I did switch to a lambda since Pylance understood the type semantics in that case. Out of curiosity, is a partial more 'expensive' than a lambda? (The standard library implementation of to_thread uses partial)

**Comment by rchiodo** [comment]
Closing old issue. I believe Eric said that partial was an expensive variant of a lambda, so I think that answers your question?
