### ISSUE TITLE
Semantic highlighting for cached_property?

### ISSUE THREAD

**Issue by willfrey** [microsoft/pylance-release#489]
The semantic highlighting has been quite helpful to me, especially how `@property`-decorated methods appear like class and instance attributes would instead of methods.

Would it be possible to have `@functools.cached_property`-decorated methods have the same semantic highlighting? Currently, their semantic token type is still `function`.

There's also [a back-port available on PyPI](https://pypi.org/project/cached-property/) but I don't know how involved it would be to support both the standard library version and the back-port.

Here's a screenshot of what I see using the Monokai theme that ships with VS Code.

![code](https://user-images.githubusercontent.com/13784361/96029838-3294e980-0e29-11eb-906b-79226a8cb57c.png)

Thank you!

**Comment by akpircher** [comment]
I love VS Code, but this is my single biggest pet peeve. If I get around it so that it looks like a property, and not a function by doing
```python
class A:
    @property
    @functools.cache
    def aproperty(self) -> str:
         return 'hello, world!'
```

Then type checkers (mypy) don't reconize that `aproperty` is a property and not a callable that returns a string. If I use `@cached_property` then all of the properties look like functions. 

I can understand not wanting to necessarily change pylance under the hood so that it automatically detects decorators that turn methods into properties. 

But if you could just give us a semantic token or something so we can say "ha! this here is not a callable method, it's a property, because that's the decorator name. Look correctly for me", then at least I would be *incredibly* thankful.

Is there a chance we could get something to give us control over distinguishing between "decorators that turn methods into property-like objects" and "decorators that return functions"?

**Comment by erictraut** [comment]
I recently made a change to the hover provider (which is in the pyright code base) related to this issue. Previously, the hover provider showed `(property)` for descriptors that used the `builtins.property` decorator but `(method)` for all other descriptors. I changed it to show `(property)` for all class variables that are evaluated as descriptor objects. The assumption is that all such objects are acting like properties even if they are not using the `builtins.property` class. The `functools.cached_property` is a good example of this.

![Screen Shot 2022-04-12 at 7 55 48 PM](https://user-images.githubusercontent.com/7040122/163091704-fbc56067-f0e0-453a-93a6-1c7cefb78f31.png)

![Screen Shot 2022-04-12 at 7 56 12 PM](https://user-images.githubusercontent.com/7040122/163091715-130f6a39-a6ad-4254-b1c4-dfcd782b7161.png)

I think it makes sense for the semantic token provider (which is in the pylance code base) to make this same distinction and treat all descriptors as properties from a semantic analysis standpoint. That should address this issue.

@bschnurr, what do you think? If you agree with this, I think it's a simple change. Just modify line 402 of `semanticTokenProvder.ts` to call `isMaybeDescriptorInstance` rather than `isProperty`.

**Comment by erictraut** [comment]
@akpircher, you mentioned that mypy doesn't recognize `aproperty` as a property when you use `@property` in conjunction with `@functools.cache`. It looks like this is a [long-standing bug](https://github.com/python/mypy/issues/1362) (first reported about six years ago!).

The type checker that's built into pylance doesn't have this problem. If you set "python.analysis.typeCheckingMode" to "basic" you'll enable type checking diagnostics.

**Comment by akpircher** [comment]
Sorry for my slow reply @erictraut, you're right that the pylance type checker doesn't have this problem, I was mistaken. I'm familiar with the mypy bug. 

My usual workflow is to use Pylance's basic type checking within the editor and then run `mypy` from the command line. So when these cases occur, I find myself stuck between telling mypy to ignore decorated property errors, code that looks a little wonky, or having cached methods. 

(Sample of what it looks like on my modified Dark+, the `aproperty` in this case does register as a property in the hover provider)
![image](https://user-images.githubusercontent.com/8506086/169926257-621724fc-666b-44e5-823c-8c0d87eac2e2.png)

It sounds like what you suggested to @bschnurr would probably fix the coloring of the cached properties/potential descriptors. But, if that's not a path you guys want to take, then what about another semantic token type for "maybe descriptor methods" that defaults to property/method/function colors?

**Comment by erictraut** [comment]
Thanks for the additional info. If you don't mind me asking, I'd be interested in understanding why you use `mypy` from the command line rather than the type checker built into pylance. Do you have a large code base that's dependent on mypy's idiosyncrasies? Are there type checking features that you rely on in mypy that are missing in pylance? Is it just what you're used to? Or something else? Just curious.

**Comment by akpircher** [comment]
I don't mind you asking at all!

I honestly use both, but it comes down more to a focus thing for me. There's a balance between getting the important thing done and fixing technical debt. When I'm working on something new, or if I am adding new modules to an existing base, I usually have type checking turned on as I work, so at least that file is completely typed. 

But if it's *always* on, then I risk getting distracted fixing, refactoring, and typing code, because those little red squigglies are just screaming to get fixed. Same with red filenames. But that work likely deserves it's own branch/effort/ticket so that relevant changes for completing my current task don't get lost in major cleanup. (I've lost significant time in the past fixing my own technical debt for my part-time job, and just had to turn it off so I could _move on_.)

So usually, turning off type checking within the IDE and then running mypy from the commandline with strict mode enabled helps me stay on task. I have considered switching to pyright so that it's consistent, but `mypy` seemed stricter when I picked it, which is both a blessing and a curse.

I also just like running stuff on the command line. Especially when it comes to stuff like git, I like knowing the command I'm running and having control of it.

**Comment by erictraut** [comment]
Thanks for the additional details.

Pyright is available as a command-line tool as well, so if you prefer to run a command-line tool that gives you results that are consistent with pylance, you could run pyright from the command line. You can also run it in `--watch` mode so it runs incrementally when you make a change to one or more files.

You mentioned that mypy seems to be more strict than pyright. Pyright has various levels of strictness. In its strictest form, it's as strict (if not more so) than mypy. You can adjust this through the `python.analysis.typeCheckingMode` setting. Set it to "none", "basic" or "strict" for three levels of strictness.

We're looking at ways to make it easier to change the type checking mode, perhaps from a popup menu that is accessible from the bottom toolbar within VS Code. That could work well for your workflow. You could disable type checking diagnostics in normal editing mode but then enable them (either "basic" or "strict") temporarily to look for type consistency errors within the file. What do you think?

**Comment by debonte** [comment]
> So, in short, I would love an easier way to change the typechecking mode on the fly.

@bschnurr

**Comment by judej** [comment]
Type checking can now be changed via the button on the status bar.
