### ISSUE TITLE
Missing docstrings for builtins

### ISSUE THREAD

**Issue by LordKa0S** [microsoft/pylance-release#49]
I am using the extension with Python 3.8.3. On hover for any function, the tooltip shows only the type information (of parameters, return value etc.).
I'd prefer it showing the documentation of the function (wherever available) as well, so that it is clear what the function is being used for. This can be seen [demonstrated in the Pylance announcement blog post](https://devblogs.microsoft.com/python/wp-content/uploads/sites/12/2020/06/type_information.gif) for the pandas library.

## Environment data

-   Language Server version: 2020.6.1
-   OS and version: Windows 10 Version 20H2 (OS Build 19042.330)
-   Python version: 3.8.3 64-bit

## Expected behaviour

Before installing pylance
![image](https://user-images.githubusercontent.com/24961562/86480931-a163a080-bd6c-11ea-99e9-540a4ccfd8d3.png)

## Actual behaviour

After installing pylance
![image](https://user-images.githubusercontent.com/24961562/86480946-aaed0880-bd6c-11ea-97de-23006c3b6003.png)

**Comment by LordKa0S** [comment]
## Additionally Replicated on:
- OS and version: Windows 10 Version 2004 (OS Build 19041.329)
- Python version: 3.7.4 64-bit

**Comment by Brodersen** [comment]
With the Microsoft Language Server I get this,
<img width="468" alt="Microsoft" src="https://user-images.githubusercontent.com/4539216/89379095-749d0300-d6f5-11ea-9cf2-5cfeb7bcfae0.png">
<img width="613" alt="MicrosoftHover" src="https://user-images.githubusercontent.com/4539216/89379101-76ff5d00-d6f5-11ea-928a-8a65e1e7de56.png">
which to me is the most helpful, as it contains a description of the function and optional parameters.

If I use Pylance I get this,
<img width="469" alt="Pylance" src="https://user-images.githubusercontent.com/4539216/89379185-9d24fd00-d6f5-11ea-8c41-3cda991148e3.png">
<img width="816" alt="PylanceHover" src="https://user-images.githubusercontent.com/4539216/89379191-9f875700-d6f5-11ea-94cd-575ff421ba05.png">
which to more experienced programmers might be more useful, but for me it is a bit messy and doesn't contain any overall  description (docstring) of the function I'm hovering over.

Regardless of my choice of language server (except when I tried Jedi), enabling brackets in settings has no effect (bug):
<img width="296" alt="BracketsEnabled" src="https://user-images.githubusercontent.com/4539216/89379384-06a50b80-d6f6-11ea-8681-9a0be24ccf0f.png">

My expected behavior with Pylance and auto complete brackets enabled, is that the hover info is useful (makes use of the docstring and any type information) and automatically adds parenthesis with my curser placed inside it (|), when I use autocomplete.

**Comment by jakebailey** [comment]
> My expected behavior with Pylance (or Microsoft) Language Server and auto complete brackets enabled, is that the hover info is useful (makes use of the docstring and any type information) and automatically adds parenthesis with my curser placed inside it (|), when I use autocomplete.

That's #37.

**Comment by JonathanTay** [comment]
Hi,
Just wanted to say I am getting this issue too. I'd been using pyright/jedi previously, and the tooltips were showing docstrings. Switching over to pylance as the language server seems to replace docstrings with type signature only. This applies to all libs and functions (sklearn, numpy, pandas, my own custom libs) with the exceptions for functions defined in the same file where the docstring appears as normal. Unfortunately, I rely on docstrings in the IDE/editor over memorizing my library APIs, so despite my desire to use pylance I have been forced to "downgrade" back to Jedi/pyright.

**Comment by jakebailey** [comment]
This bug is specifically about the docstrings for builtins, which are distinct from the docstrings for other modules in that there is no file that can be read that contains the docstrings.

Our pandas type stubs mirror some of the docstrings to make sure we can access them (as pandas produces the docstrings at runtime from templates, defeating any static type checker that doesn't literally want to execute the code to try and pull info). If there are specific methods in pandas that we're missing or show inconsistently, I would suggest making a new issue, as the fix for that is going to be quite different than the fix for the builtins. `read_csv` being missing in particular is confusing, as that's definitely one we have mirrored.

**Comment by JonathanTay** [comment]
Thanks Jake. I appreciate the response. And thanks to the whole team for the work they've put into the tooling. I apologise for mis-filing this issue.

**Comment by chenyidao110** [comment]
> 
> 
> Thanks Jake. I appreciate the response. And thanks to the whole team for the work they've put into the tooling. I apologise for mis-filing this issue.

sir, when will patch this issue?

**Comment by jakebailey** [comment]
Hopefully soon (this is the top voted issue, after all), but I don't have a timeframe at the moment, sorry.

**Comment by cpbotha** [comment]
I am running into this issue with Django as well.

PyLance is showing the function signature from django-stubs (which it comes bundled with) instead of the docstring in the actual django code.

You can also see this when you `Go to definition` via that symbol: VSCode then jumps to that function in the type stubs file, instead of the original source, which would have been far more useful.

**Comment by chenyidao110** [comment]
When will resolve the issue?

**Comment by jakebailey** [comment]
This is being worked on, and we will update this issue when it's finished and available.

**Comment by jakebailey** [comment]
I'm happy to say that the next release (tomorrow?) will enable this:

![str](https://user-images.githubusercontent.com/5341706/93937423-9f124200-fcdc-11ea-8cf8-6d52c6e89feb.png)

![print](https://user-images.githubusercontent.com/5341706/93937437-a6d1e680-fcdc-11ea-92bc-dfc8b674b18e.png)

It's going to be limited to the builtins for now, i.e. what you get in the global scope. There are other standard library modules that are compiled that could benefit from this, but that'll take a bit more effort to implement correctly and we'd like to continue to work on the compiled module story as a whole before expanding things.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.6, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202096-23-september-2020

**Comment by jackblk** [comment]
@jakebailey:

I see that we have fixed this problem for builtins, what about custom function? Sorry if it might not fit this issue though, i dont want to create new issue for this.

If i use Microsoft Language Server:
![image](https://user-images.githubusercontent.com/12843654/95561712-54ffbf00-0a45-11eb-8f5e-faa9839af271.png)

If i use pylance:
![image](https://user-images.githubusercontent.com/12843654/95561834-88dae480-0a45-11eb-933a-231e48565f87.png)

If I hover on the function, it will display the docstring that I need. But it's very inconvenient to do so whenever i write something.

Is there any way to display the docstring like MLS? Thanks a lot :).

**Comment by jakebailey** [comment]
We definitely show info for your own functions. Based on the signature, that function appears to be using `functools.wraps`, which seems to drop the docstring. See #442 / #125 / microsoft/pyright#774.

**Comment by YodaEmbedding** [comment]
> This issue has been fixed in version 2020.9.6, which we've just released.

Just wondering: has this issue also been fixed in pyright?

**Comment by jakebailey** [comment]
No, the functionality to do this is implemented in Pylance (and doesn't affect type checking, only editor features). The builtins are compiled and that whole thing isn't quite settled; this is just a specific special case that we wanted to try out.
