### ISSUE TITLE
False positive error

### ISSUE THREAD

**Issue by Semkem** [microsoft/pylance-release#4904]
## Environment data
-   Language Server version: I don't find it
-   OS and version: ???
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5

## Code Snippet
```python
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)
```

Code works well

XXX

## Actual behavior

pylance get me this:
Argument of type "Literal['kiwi']" cannot be assigned to parameter "__value" of type "Literal['apple', 'banana', 'cherry']" in function "__setitem__"
  Type "Literal['kiwi']" cannot be assigned to type "Literal['apple', 'banana', 'cherry']"
    "Literal['kiwi']" cannot be assigned to type "Literal['apple']"
    "Literal['kiwi']" cannot be assigned to type "Literal['banana']"
    "Literal['kiwi']" cannot be assigned to type "Literal['cherry']"

## Logs
I hope it doesn't need

**Comment by debonte** [comment]
@erictraut can confirm, but I believe that this is by design based on our rules for type inference of [tuples](https://microsoft.github.io/pyright/#/type-inference?id=tuple-expressions) and [lists](https://microsoft.github.io/pyright/#/type-inference?id=list-expressions).

For `tuple`, "each...element is typed as specifically as possible", and for `list`, "if the list contains multiple elements that are of different types...use the union of all element types and infer `list[Union[(elements)]]`"

Therefore the type of `y` is `list[Literal['apple', 'banana', 'cherry']]`.

You could work around this by explicitly specifying the list type:
```python
y = list[str](x)
```

**Comment by erictraut** [comment]
Yes, this is working as designed. I presume that you've enabled type checking in your project. That means pyright (the type checker upon which pylance is built) will apply type consistency rules according to the Python static type system. If you want to learn more about static typing, you can read pyright's documentation [here](https://microsoft.github.io/pyright/#/type-concepts). For additional information about the type inference rules pyright applies for tuple and list expressions, check out [this documentation](https://microsoft.github.io/pyright/#/type-inference?id=tuple-expressions).

> You could work around this by explicitly specifying the list type

Or you can provide an explicit type declaration:

```python
y: list[str] = list(x)
```
