### ISSUE TITLE
Pylance and SymPy expressions

### ISSUE THREAD

**Issue by k2pctdn** [microsoft/pylance-release#4913]
## Environment data

-   Language Server version: Pylance language server 2023.9.30 (pyright 7e72aa15)
-   OS and version: Windows 10 Pro Education, Version 21H2, Build 19044.3086
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.8

## Code Snippet

```python
from sympy import Symbol, exp, integrate #SymPy version 1.12
x = Symbol('x')
f = 2.5*exp(-0.5*x)
print(integrate(f, (x,0,1)))
```

## Repro Steps

1. Creating a blank .py file, for example `testing.py`
2. Working with SymPy expression (see the code snippet above for a small example)
3. The package SymPy can be found here: https://www.sympy.org/en/index.html

## Expected behavior

PyLance should give no errors or warning

## Actual behavior

Pylance gives error and warning

```
Operator "*" not supported for types "float" and "exp"
Operator "*" not supported for types "float" and "Symbol"
```

## Logs

```
The log file is too long and exceeds the 65536 characters limitation. 
```
Please have a look at the log file here: https://pastebin.com/TnBBRDji

**Comment by debonte** [comment]
Sympy's behavior around algebraic expressions is too dynamic for Pylance to understand. Since `exp` and `Symbol` do not define `__rmul__` methods, Pylance believes that they cannot be multiplied in this way. [Internally](https://github.com/sympy/sympy/blob/master/sympy/core/sympify.py#L381) sympy is converting the `float` values to `sympy.core.numbers.Float` objects which do support [multiplication](https://github.com/sympy/sympy/blob/master/sympy/core/numbers.py#L1025) with other sympy types, but this is not declared in any way that Pylance can understand.

If you'd like your sympy-based code to work better with static type checkers, I would suggest filing an issue on sympy to see if they can improve their typing annotations / stubs. Strangely sympy ships with a `py.typed` file which implies that their code is typed, but from what I can see it is not.
