### ISSUE TITLE
Cannot access member "content" for type "Response"   Member "content" is unknown

### ISSUE THREAD

**Issue by sachinpatle98** [microsoft/pylance-release#4939]
if obj_result.status_code == 200:  # Check if OBJ translation is successful
                        result["content"] = obj_result.content 
                        # result["filename"] = result["filename"].replace(".svf", ".zip")
                        result["filename"] = node_urn.split("/")[-1].replace(".svf", ".zip")
                        guid_objects[node_guid] = result

**Comment by debonte** [comment]
Can you please provide a complete, minimal code sample (ex. your imports are missing) as well as the packages (with versions) required to reproduce this?

**Comment by yilmazdurmaz** [comment]
@debonte I was on a different issue from stackoverflow, yet it seems this problem is either solved by some fix for a coupling issue, or the underlying cause is very different. I don't see such a change mentioned in the [change log](https://marketplace.visualstudio.com/items/ms-python.vscode-pylance/changelog).

@sachinpatle98  I used this code fragment, and there is no such message you used in the title. I even used an older pylance version, v2023.8.40. it also autocompletes "content" and other members with no problem.

````py
import requests
from requests import Response

obj_result: Response = requests.get('https://w3schools.com')

result: dict[str,bytes]={}
if obj_result.status_code == 200: # Check if OBJ translation is successful
    result["content"] = obj_result.content
    print(result)
````

Please update extensions, try again, and close the issue if it is fixed, or give more details
