### ISSUE TITLE
Pylance reports "XX is not a known member of "None"" error when function optionally returns a value.

### ISSUE THREAD

**Issue by philosofool** [microsoft/pylance-release#4950]
## Environment data

-   Language Server version: v2023.10.10
-   OS and version: Linux x64 6.0.12-76060012-generic snap
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.10

## Code Snippet
```python
from typing import Any, Optional

def append_list(a_list: list, e: Any, inplace=False) -> Optional[list]:
    """Illustrate error""".
    if inplace:
        a_list.append(e)
        return None
    out = a_list.copy()
    append_list(out, e, inplace=True)
    return out


result = append_list([], 'item')
# to my surprise, if we include the next (commented) line, the error goes away:
# assert result is not None
result.append('another item')  # highlighted with error
assert result == ['item', 'another item'], f"got {result}"
```

## Repro Steps
1. Enable Pylance and set type checking level to "basic" in Pylance Extension settings.
2. Write the above code snippet into a Python file in VSCode  

## Expected behavior

There is no error highlighted because the function call returned a `list`, which is what is hinted.

## Actual behavior

The `result` variable is expected to be None and Pylance generates an error. The line commented (15th) generates the following report in VSCode problems tab:
```json
[{
	"resource": "/home/lenhart/Desktop/example_optional_return.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportOptionalMemberAccess",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalMemberAccess",
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportOptionalMemberAccess"
		}
	},
	"severity": 8,
	"message": "\"append\" is not a known member of \"None\"",
	"source": "Pylance",
	"startLineNumber": 13,
	"startColumn": 8,
	"endLineNumber": 13,
	"endColumn": 14
}]
```

## Logs

My log file is huge. I'm happy to deliver with requests for specifics.

**Comment by erictraut** [comment]
Pylance's behavior is correct here.

You've enabled static type checking, so pylance will report any type inconsistencies (potential bugs due to type mismatches) in your code. Your function `append_list` has an annotated return type of `Optional[list]` which means that it may return a `list` or `None`. That means a caller cannot assume that the returned value is a list. This is a common code error in Python, and Pylance is helping to identify a potential bug.

If you're certain that the value returned by `append_list` will never be `None` in a particular usage, you can add an assert statement (as you've done in your commented-out code). That documents your assumption, adds runtime validation, and tells the static type checker that it can now safely assume that the value of `result` is never `None`.

Your function `append_list` returns `None` only under certain circumstances — namely, when `inplace` is True. In other words, `append_list` a "polymorphic" function. The Python static type system provides a way to annotate polymorphic functions through the use of `typing.overload`. Here's how that would look:

```python
@overload
def append_list(a_list: list, e: Any, inplace: Literal[False] = False) -> list:
    ...
@overload
def append_list(a_list: list, e: Any, inplace: Literal[True]) -> None:
    ...
def append_list(a_list: list, e: Any, inplace=False) -> Optional[list]:
    # The implementation of the function goes here
```

If you add the overloaded signatures, you can omit the `assert` statement because Pylance will now know that `append_list` does not return `None` unless `inplace` is True. For more details about how to use `typing.overload`, you can refer to [PEP 484](https://peps.python.org/pep-0484/#function-method-overloading).

**Comment by philosofool** [comment]
Thanks for the explanation, Eric. That all makes sense. The issue here actually emerged because Pandas has numerous polymorphic functions. Possibly, Pandas is recently up to date, but due to a number of complicated dependency issues, my team is currently on a relatively old version of Pandas.
