### ISSUE TITLE
Auto import quick fix list becomes too unwieldy

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pylance-release#4968]
I'm on Pylance v2023.10.20

In an empty Python file with strict checking enabled, enter the following:

```python
time.perf_counter()
#^
```

Request a quick fix above `^`.

Notice how long the quick fix list is for `time`:

![image](https://github.com/microsoft/pylance-release/assets/972891/63a7cc57-e492-40d6-8259-52bc31fe04fe)

My expectation would be that if anything matches on an exact name, those are the only items shown - especially if the identifier is used on the left side of an attribute access.

My experience is admittedly based on TypeScript's, where fuzzy matches are enabled by auto-import completions, not the quick fix menu itself. As I understand it, Pylance turns off auto-import completions by default.

Alternatively, you could use a nested menu to organize the quick fixes into more-certain quick fix items, and less certain ones.

```
Add "import time"
Add "from datetime import time"
Add "from time import time"
See other possible imports for "time"...
├── Add "import timeit"
├── Add "from asynctimeout import timeout_at"
├── Add "from asynctimeout import timeout"
└── ...
```

**Comment by rchiodo** [comment]
See this discussion item:
https://github.com/microsoft/pylance-release/discussions/3873

**Comment by heejaechang** [comment]
we had feedbacks from both sides. someone who likes current behavior and someone who doesn't. unlike typescript, we do not enable `auto import` on `completion` by default. 

so, instead we have `python.analysis.addImport.exactMatchOnly` option for someone, who enable `auto import on completion` and use only exact match on `code action`.

unlike `typescript`, `python` doesn't have concept of `package.json`, `symbol accessibility` nor `export` so, `auto import` is 10x more than what `typescript` would suggest, so we decide not to enable it by default on `completion` since perf impact is way higher then `typescript` case.

**Comment by heejaechang** [comment]
we do have work item in `backlog` to use `requirements.txt` or `pyproject.toml` to see whether we can reduce number of dependencies to consider in `auto import` (basically direct dependency and not dependency or dependencies since `python` puts all dependencies in flat list and no easy way to figure out which one is 1st level dependencies) 

also, many python users (even if they have `requirements.txt`) uses dependency of dependency in their source files (since nothing blocks it) without adding it to `requirements.txt`, so we can't simply force it even if we implement it.
