### ISSUE TITLE
Please, don't jump to stub files!

### ISSUE THREAD

**Issue by cangyin** [microsoft/pylance-release#5044]
For python 3.8.10, with pylance v2023.1.10
```python
#!/usr/bin/python3

import sys

from unicodedata import category
```

`Ctrl+Click` on `unicodedata` jumps to the damn stub file, that's frustrating and drives me crazy.

Issues I read:
- https://github.com/microsoft/pylance-release/issues/65
- https://github.com/microsoft/pyright/issues/795
- https://github.com/microsoft/pylance-release/issues/3227

But none of them actually solves the problem.

What in the end is the meaning for creating such stub files? Python is not C/C++, it does not need a header file!

**Comment by erictraut** [comment]
Where would you expect it to take you in this case? There is no `unicodedata.py` file. This module is [implemented in C](https://github.com/python/cpython/blob/main/Modules/unicodedata.c) and compiled as part of the Python interpreter. That means there is no source code on your system that can be displayed. Pylance is falling back to the type stubs in this case because they at least provide you with the interface definitions for this module.

**Comment by cangyin** [comment]
Well, that sounds completely reasonable to me. But I suggest adding a heading comment for such stub files, telling for why the stub file is chosen to shown up.

So there will be less persons be confused by pylance not carrying them to the actual .py files.

**Comment by cangyin** [comment]
Thanks.
