### ISSUE TITLE
Pylance didn't honor return type from `__new__` in special cases

### ISSUE THREAD

**Issue by Brainor** [microsoft/pylance-release#5057]
## Environment data

-   Language Server version: v2023.10.50
-   OS and version: 
    1. Windows 11 Pro, 22H2, 22621.2506
    2. Ubuntu 22.04.2 LTS
-   Python version & distribution: 
    1. 3.11.6, Anaconda
    2. 3.10.11, Anaconda

## Code Snippet

```python
class TestClass:
    def __new__(cls, message="") -> str:
        return "stub"


a1 = TestClass(12)  # typing: (variable) a1: TestClass
a2 = TestClass()  # typing: (variable) a2: str
```
![image](https://github.com/microsoft/pylance-release/assets/5477995/831007f0-d4f6-4e81-8266-f069f5cfd624)

## Expected behavior

`a1` and `a2` are both string `stub`,  and `a1` and `a2` should both be typed as `(variable) a2: str`

## Actual behavior

`a1` is typed as `typing: (variable) a1: TestClass`  
`a2` is typed as `(variable) a2: str`

According to #1092 , `pyright` checks return type from `__new__` since `version 2021.3.4`, so I guess it might be a pylance issue.

**Comment by erictraut** [comment]
Pyright is working as intended here, so I don't consider it a bug.

The call expression `TestClass(12)` results in a type error because the `message` parameter has an inferred type of `str` based on the default argument value of `""`. Since pyright couldn't find any constructor signature that was compatible with the provided arguments, it emitted a type error and assumed that the return type of the constructor was `TestClass`.

If you want your constructor to support both `str` and `int` arguments for the `message` parameter, you can provide an explicit type annotation.

```python
class TestClass:
    def __new__(cls, message: str | int="") -> str:
        return "stub"
```

**Comment by Brainor** [comment]
> The call expression `TestClass(12)` results in a type error because the `message` parameter has an inferred type of `str` based on the default argument value of `""`. Since pyright couldn't find any constructor signature that was compatible with the provided arguments, it emitted a type error and assumed that the return type of the constructor was `TestClass`.

Thank you for your detailed explanation, and you are right, default argument value causes inferred type.
```python
class TestClass:
    def __new__(cls, message: str | int="") -> str:
        return "stub"


a1 = TestClass('12')  # typing: (variable) a1: str
a2 = TestClass()  # typing: (variable) a2: str
a3 = TestClass(12) # typing: (variable) a3: str
```
gets the expected typing result. Lesson learned here. Closing this.
