### ISSUE TITLE
Python cannot code navigate some libraries.

### ISSUE THREAD

**Issue by jaepil-choi** [microsoft/pylance-release#508]
## Environment data

-   VS Code version: 1.50.1 (user setup)
-   Extension version (available under the Extensions sidebar): v2020.9.1143
-   OS and version: Windows_NT x64 10.0.19041
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda3 python=3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: requests 2.24
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance v2020.10.1
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behavior & outcome

The only way to access the source file is by going into the `site-packages/` directory and directly opening the file. 
In my case, `~/Anaconda3/envs/webscraping37/lib/site-packages/urllib3/util/retry.py`

My thoughts are that this happens because of how the backward compatibility code is written in `requests` module. 

When you go to `~/Anaconda3/envs/webscraping37/lib/site-packages/requests/util/packages.py`, it looks like the below. 

```python
import sys

# This code exists for backwards compatibility reasons.
# I don't like it either. Just look the other way. :)

for package in ('urllib3', 'idna', 'chardet'):
    locals()[package] = __import__(package)
    # This traversal is apparently necessary such that the identities are
    # preserved (requests.packages.urllib3.* is urllib3.*)
    for mod in list(sys.modules):
        if mod == package or mod.startswith(package + '.'):
            sys.modules['requests.packages.' + mod] = sys.modules[mod]

# Kinda cool, though, right?
```

Would it be possible for VSCode to find out the real source of the imported libraries? 
I think it should at least tell the user that the library is importable but not reachable in code navigation. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Try to code navigate 

```python
from requests.packages.urllib3.util.retry import Retry
```

2. See that it is only accessible to .pyi, not the source code .py itself. 

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

</p>
</details>

**Comment by jakebailey** [comment]
This behavior is so dynamic that I don't think we're ever going to be able to support it... This involves 1) a for loop over specific values, 2) importing via some dynamic value, not via `import`, 3) assigning dynamically to the local scope, 4) string manipulation where the output matters to future behaviors, and 5) assigning values directly into the global module table (which affects all modules in the program as a side effect).

If I'm reading this correctly, this doesn't prevent you from using `requests` from other code (as we will pull info from stubs), only that you can't navigate around the real code, correct? One of the main reasons for having stubs is that they can hide this sort of dynamic behavior by providing the intended interface, rather than forcing an analyzer to figure out the hacks.

**Comment by jakebailey** [comment]
It's been over 30 days since we added "waiting for info" without a reply; I'm going to close this issue to keep the issues clean, but it can be reopened if needed.
