### ISSUE TITLE
I wonder why `Pylance` override the default value of `formatOnType`

### ISSUE THREAD

**Issue by EeyoreLee** [microsoft/pylance-release#5094]
I think most users prefer `formatOnSave`. Could we change the default value back to false.

**Comment by EeyoreLee** [comment]
Related issue [vscode-extension-yapf/issues/76](https://github.com/EeyoreLee/vscode-extension-yapf/issues/76). Also for me

**Comment by debonte** [comment]
Our auto-indentation feature, which indents/dedents your code as you type, is based on `formatOnType`. I believe that most users want the editor to provide smart, language-specific auto-indentation as they type, so that's why we've enabled it by default for `[python]`.

Enabling `editor.formatOnType` will cause VS Code to notify any extension that supports format-on-type when that extension's "trigger characters" are typed. If a user wants `formatOnType`-based behaviors to work in any extension, they need to enable this setting. So I would argue that extensions that provide possibly unwanted behavior on format-on-type should disable that behavior by default and provide a config setting so users can enable it if desired.

Pylance does not currently provide a config setting to turn off auto-indent separately from `editor.formatOnType`, but I've considered it since we are experimenting with implementing other features based on the format-on-type mechanism and it would be nice for users to be able to enable/disable those features independently. However, I believe that we would still want `editor.formatOnType` enabled by default.

**Comment by EeyoreLee** [comment]
@debonte - Thanks for you clarifying. And I noticed if I set `formatOnType` on workspace settings.json, it not works for my formatter extension like `yapf`. I must restart the extension by reloading window or other way. I think this may be a bug here ?

**Comment by debonte** [comment]
> I think this may be a bug here ?

I'm not sure. If that's a bug it would be a [vscode](https://github.com/microsoft/vscode/issues) bug, not a Pylance bug.
