### ISSUE TITLE
Incorrect autocompletion for child class overriding parent class's class attribute

### ISSUE THREAD

**Issue by ribeirompl-soldersmith** [microsoft/pylance-release#5115]
## Environment data

`Pylance language server 2023.11.10 (pyright 088ebaa5) starting`

-   Language Server version: 2023.11.10
-   OS and version: Windows 10
-   Python version: Python 3.10.10

## Code Snippet

```python
from dataclasses import dataclass


# Define Parent class with MyModel class attribute that will be overridden by Child class
class Parent:
    @dataclass
    class MyModel:
        my_attribute_ignored: int

    def __init__(self):
        self.my_model = self.MyModel(1234)


# Define Child class that inherits from Parent and overrides the MyModel class attribute
class Child(Parent):
    @dataclass
    class MyModel:
        my_overridden_attribute: int

    def __init__(self):
        # Call Parent initialisation, which will initialise this Child's MyModel into self.my_model
        super().__init__()


my_child = Child()
print(my_child.my_model.my_overridden_attribute)  # prints 1234, as expected
print(my_child.my_model.my_attribute_ignored)  # raises AttributeError, as expected
```

## Expected behavior

At runtime, the code functions as expected, the `self.my_model` instance attribute is an instance of `Child.MyModel` and therefore has the `my_overridden_attribute`, and will print out the value 1234
Then it will, as expected, raise an AttributeError on the next line.

When I type `my_child.my_model.`, I am expecting Pylance to suggest `my_overridden_attribute` for autocompletion.

## Actual behavior

Pylance suggests `my_attribute_ignored` for autocompletion.
Also, the syntax highlighting suggests that `my_overridden_attribute` is invalid.

![image](https://github.com/microsoft/pylance-release/assets/97503920/412d1250-075e-4230-ad8e-13b8732fc87c)

**Comment by erictraut** [comment]
This is working as designed. The `my_model` attribute has no type annotation, so its type is inferred based on assignments. In this case, it is assigned a value only in the `Parent` class. If you want this to work with completions, you would need to add explicit attribute annotations.

```python
class Parent:
    my_model: "Parent.MyModel"
    ...

class Child(Parent):
    my_model: "Child.MyModel"
    ...
```

From a typing perspective, your override is unsafe because it violates the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). The `Child` class is overriding the `Parent` class in a way that makes the `Child` incompatible with `Parent`. If you enable type checking and enable the optional `reportIncompatibleVariableOverride` check, you will see that pylance reports this coding error.
