### ISSUE TITLE
autocomplete for plotly.graph_objs not working

### ISSUE THREAD

**Issue by timovp** [microsoft/pylance-release#512]
Pylance seems to not understand the "lazy import" method used when:
`import plotly.graph_objs as go`

when then refering to `go.Scatter(...)` , resulting in an `"Scatter" is not a known member of modulePylance (reportGeneralTypeIssues)` 
now I understand that I can set Pylance to not show these errors, but it would be great if I could still use the docs-strings and other autocomplete comforts. 

Is there a workaround for this?

**Comment by judej** [comment]
@timovp, thanks for the report.

Clarification question: what does "lazy import" mean in this case? Is this an internal detail of how plotly does imports?

**Comment by timovp** [comment]
Sorry, wasn't that clear indeed.
`import plotly.graph_objs as go` refers to: [plotly graph_objs on github](https://github.com/plotly/plotly.py/tree/master/packages/python/plotly/plotly/graph_objs)
which invokes just `from plotly.graph_objs import *`. The functions needed such as `Scatter` are then found inside subfolder from there. Maybe nested is a better term than lazy. 

Oh I see I made a typo, edited that above.

**Comment by JP-Ellis** [comment]
It appears that Plotly makes use of their own import procedure using the [`relative_import`](https://github.com/plotly/plotly.py/blob/063eb06176b067a533f88c90e72bbae6ad76f248/packages/python/plotly/_plotly_utils/importers.py#L4).  I'm not sure whether that is something Pylance could/should ever be able to resolve?

Over on the Plotly side, there is an open issue about possibly adding typing annotations (plotly/plotly.py#1103), so perhaps this might be fixed by a Plotly contributor?

**Comment by jakebailey** [comment]
I don't think we'd ever want to attempt to support these sorts of import hacks; they're not specified in any PEP and there are a few projects which do different variants of this (like tensorflow, who has "fixed" this already in latest versions).

If plotly needs to use these sorts of import tricks, then that would be a motivator for having type stubs which write things the "normal" way.

**Comment by anton164** [comment]
What is the recommended way of dealing with this issue in pylance? (i.e. a library which has incorrect type annotations).

Currently I need to scatter `# type: ignore` all over the code which is not ideal...

**Comment by erictraut** [comment]
@anton164, I presume that you have enabled type checking within pylance? This issue was initially about autocomplete, not about type checking. The two are related (since autocomplete functionality leverages type information), but type checking requires more accurate and complete type information.

If you enable type checking, then I recommend disabling the `useLibraryCodeForTypes` option. When this feature is enabled, pylance attempts to infer types from the library code. These inferred types are good enough for autocomplete but are often not good enough for type checking. That explains why you're seeing all of these false positive errors. If you disable this feature, pylance will assume that all symbols imported from a library are "unknown" if it does not include type annotations.

It looks like the maintainers of plotly are open to [adding type information](https://github.com/plotly/plotly.py/issues/1103). If you're so inclined, you could contribute PRs to that project to add type information (in the form of inlined types or stub files). That would benefit everyone in the community who use plotly.
