### ISSUE TITLE
Returned type does not correctly resolve for overloaded methods

### ISSUE THREAD

**Issue by treforevans** [microsoft/pylance-release#5130]
## Environment data

-   Language Server version: 2023.11.10
-   OS and version: linux x64
-   Python version: Python 3.9.17 (Anaconda distribution)
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

## Code Snippet

```python
class A:
    def foo(self, x: int):
        return self.bar(x=x)

    def bar(self, x: int) -> int:
        return x + 1


class B(A):
    def bar(self, x: int) -> float:
        return x + 1.0


result_int = A().foo(x=1)  # type is int; pylance correctly shows "int" on hover
result_float = B().foo(x=1)  # type is float; pylance incorrectly shows "int" on hover
```

## Expected behavior

`result_float` should be inferred as type float.

## Actual behavior

`result_float` is inferred as type int.

**Comment by rchiodo** [comment]
Thanks for the issue but I'm guessing this isn't something we can compute. At least in a reasonable amount of time. When computing the return type for 'foo', it's cached for the `A` class. To know that it needs to be recomputed for the `B` class would require knowing how we computed the return type for `foo` - meaning it was inferred instead of coming from a type annotation.

@erictraut do you think this is something we could reasonably figure out?

**Comment by erictraut** [comment]
Pyright is doing the right thing here based on the Python typing standards, so this isn't something we would change.

If your intent is for the return type of `bar` to be overridable by a subclass in a covariant manner (i.e. the return type can be a subtype of the parent class's method), then its return type should be generic on type `T`, and the base class should indicate that `bar` returns `T` rather than `int`. That's what generics are for.
