### ISSUE TITLE
Files to analyze count is wrong for notebooks

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5173]
1. Create a notebook with 1000 cells, with each cell having a bunch of imports so it takes a while to analyze
2. Close VS code
3. Reopen
4. Look at the 'Files to Analyze' count = It says 1000s of files to analyze, not 1.

**Comment by StellaHuang95** [comment]
For now, I plan to update the message to something like `xxx files to analyze`, `xxx cells to analyze`, and `xxx files and xxx cells to analyze`, but it may cause confusion for multiple workspace cases since the status doesn't stack, see https://github.com/microsoft/pyrx/issues/5214. That will be handled in a separate PR.

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.5.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20245102-23-May-2024-PreRelease)
