### ISSUE TITLE
Can not resolve Type Hint in Class, ReportUndefinedVariable

### ISSUE THREAD

**Issue by Zrealshadow** [microsoft/pylance-release#522]
When I write a class and use Type hints in class, for example:

```python

class EvalUnit(object):
    def __init__(self, tn, fp, fn, tp, name = None) -> None:
        super(EvalUnit,self).__init__()
        self.name = name
        self.tp = tp
        self.fp = fp
        self.fn = fn
        self.tn = tn
    
    def __add__(self,other:EvalUnit) -> EvalUnit:
        return EvalUnit(
            self.tn + other.tn,
            self.fp + other.fp,
            self.fn + other.fn,
            self.tp + other.tp,
            )
    
    def __iadd__(self,other:EvalUnit) -> EvalUnit:
```

In Line 11 and Line 19, pylance will raise a warning that "EvalWarning is not defined (reportUndefinedVariable)"

**Comment by AEFeinstein** [comment]
What was the resolution?

**Comment by erictraut** [comment]
The code above will result in runtime exceptions because `EvalUnit` is evaluated by the Python interpreter prior to `EvalUnit` being declared. There are two ways to work around this.

1. Enclose the `EvalUnit` annotations in quotes. A type checker will treat them as forward declarations. The Python interpreter will see them simply as strings, so it won't generate exceptions at runtime.
2. Add `from __future__ import annotations` to the top of the file. This tells the interpreter that it should defer the evaluation of type annotations.

**Comment by AEFeinstein** [comment]
Thanks for the quick response! Quotes worked wonders.
