### ISSUE TITLE
Editable installs not resolving

### ISSUE THREAD

**Issue by pxl9588** [microsoft/pylance-release#5227]
Around the same time I updated my Pylance version, editable installs stopped working. I am using a virtual environment and suspect it may be an issue with clashing namespaces. My editable install shares the same namespace as other packages in the environment, and it appears that pylance is only able to resolve one.

<h3> Environment data </h3>

-   Language Server version: 2023.11.102
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

**Comment by pxl9588** [comment]
I created a repo to test this and I am more convinced now that its the namespaces being the same. [Here is a repo to test it](https://github.com/pxl9588/python_editable_installs).
Steps to reproduce:

1. Create a virtual environment in test2
2. Run `pip install -e ../test1`

**Comment by pxl9588** [comment]
I tried this with my working repo and it didn't work. What I noticed is that the virtual environment had `__init__.py` files under each namespace that was shared with the editable installs. Once I deleted those files it was able to resolve the modules in the namespace and the editable one.

**Comment by pxl9588** [comment]
That made it work for the test repo. But not the repo I was working with originally. But I think that's due to the init files being there.

**Comment by rchiodo** [comment]
Not sure why `__init__.py` files would break anything. Oh wait. That changes the priority on which import path we pick. Packages with `__init__.py` have higher? (wait maybe lower, I don't remember). So that likely means we have both import paths being resolved and one of them is prioritized over the other because of the init files.

See the logic here:
https://github.com/microsoft/pyright/blob/5dd7564c4634dea33b55b9d0a72dbd69816e7f0f/packages/pyright-internal/src/analyzer/importResolver.ts#L1713

Yeah it looks like the one with `__init__.py` takes precedence.

**Comment by pxl9588** [comment]
That was added 7 months ago so not sure why I'm only seeing this now. However, only one of our packages had these init files, so I removed them and republished and now everything looks good.

**Comment by rchiodo** [comment]
Thanks for the information. Closing for now. Feel free to reopen if you think there's something else we should do.
