### ISSUE TITLE
Unexpected behaviour if a class has a property whose name matches that of another class

### ISSUE THREAD

**Issue by colinRawlings** [microsoft/pylance-release#523]
## Environment data

-   Language Server version: 2020.10.2
-   OS and version: Win10 20175
-   Python version: CPython 3.6.8

## Expected behaviour

When having a module `lib` inside a package `my_lib` defining a class `MyClass` an instance of which is composed into a second class (`MyBigClass`).  `MyBigClass` has a property named `MyClass` as well as a method that returns an instance of `MyClass`.  When the typing is supplied in a separate file the method's return type should be correctly understood.

For the `lib.py` file in the `my_lib` package:
```python
class MyClass:
    def __init__(self):
        pass

    def get_a_number(self):
        return 42

class MyBigClass:
    def __init__(self):
        self._my_class = MyClass()

    def get_my_class(self):
        return self._my_class

    @property
    def MyClass(self):
        return self._my_class
```

For the `lib.pyi` file (in the `my_lib` package alongside a `py.typed` file):
```python
class MyClass:
    def __init__(self) -> None: ...

    def get_a_number(self) -> float: ...

class MyBigClass:
    def __init__(self) -> None: ...

    def get_my_class(self) -> MyClass: ...

    @property
    def MyClass(self) -> MyClass: ...
```

For this scenario no errors should be detected in the following script:
```python
from my_lib.lib import MyBigClass

b = MyBigClass()

a = b.get_my_class()

a.get_a_number()
```
## Actual behaviour

Pylance reports that the variable `a` has a type `property` and that the final line of `script.py` is an error:
```
Cannot access member "get_a_number" for type "property"
  Member "get_a_number" is unknown
```

This error is not reported if:
- The property `MyClass` is removed from the py and pyi file.
- The type annotations are placed directly in the py file (and the pyi file is removed).

My use case is a large set of `pyd` files produced by `boost::python` whose user interface cannot be changed for reasons of backward compatibility.  So I cannot remove properties and my modified version of `pybind11-stubgen` must put the typing information into a separate file.

Thanks as ever for your excellent work on this extension and apologies if this is intended behaviour!

**Comment by erictraut** [comment]
This is correct behavior. PEP 484 indicates that all type annotations within a type stub file are assumed to be forward references — i.e. you don't need to enclose these annotations in quotes like you would within a ".py" file. Forward references do not use code flow order for resolution. Instead, they use scope-based lookups, starting with the scope in which they are used. In your case, the return type for `get_my_class` uses the annotation `MyClass`. Since this is within the scope of the `MyBigClass` class declaration, this symbol resolves to the `MyClass` function, not the outer class `MyClass`.

Not all type checkers handle this situation according to the spec, so I'm not surprised that the type stub contains this bug.

Name collisions like this occur in a few places within the typeshed type stubs, and the way they work around it is to create a temporary type alias to the outer symbol. Here's how that would look in your example. Note the use of the underscore, since the alias is not available at runtime.

```python
class MyClass:
    def __init__(self) -> None: ...
    def get_a_number(self) -> float: ...

_MyClassAlias = MyClass

class MyBigClass:
    def __init__(self) -> None: ...
    def get_my_class(self) -> _MyClassAlias: ...
    @property
    def MyClass(self) -> _MyClassAlias: ...
```

**Comment by colinRawlings** [comment]
Ok thanks for the clarification, I had wondered about that but was not aware of the relevant PEP.  Hmm creating these aliases programmatically could be a bit cumbersome ...
