### ISSUE TITLE
Ignore inlay hints for parameters starting with `__`

### ISSUE THREAD

**Issue by singhalmradul** [microsoft/pylance-release#5242]
There should be a setting to ignore inlay hints for parameters starting with `__` such as `__obj`  in `len(obj)` function.

**Comment by debonte** [comment]
Am I correct in understanding that in the following code, when calling `foo` you wouldn't want to see the `__x/` inlay hint for the argument?

![Screenshot 2023-12-11 123401](https://github.com/microsoft/pylance-release/assets/12820898/c6d2089d-9729-486c-a691-a272f5d8558f)

If so, this is already possible. You can set `python.analysis.inlayHints.callArgumentNames` to `partial` instead of `all`.

**Comment by singhalmradul** [comment]
thanks, it resolved my issue.
