### ISSUE TITLE
Type checking fails to recognize ‘any’ function with ‘is None’

### ISSUE THREAD

**Issue by Nevrai** [microsoft/pylance-release#5244]
Pylance is reporting a type error when I use the `any` function with `is None` to check if any of several variables are `None`. Despite the logic being correct and the runtime behavior as expected, Pylance raises a type issue. I’m using the `basic` type-checking mode.

## Environment data

- Language Server version: 2023.11.104
- OS and version: Windows 11 Home 22H2
- Python version: 3.12.1

## Code Snippet

```python
def main(user_id: int, user_username: str, user_display_name: str):
    print(user_id, user_username, user_display_name)

user_id = None
user_username = 'johndoe'
user_display_name = 'John Doe'

if any(x is None for x in [user_id, user_username, user_display_name]):
    raise ValueError('user_id, user_username, or user_display_name is None!')

main(user_id, user_username, user_display_name)
```

Error:

```
Argument of type "Unknown | None" cannot be assigned to parameter "user_id" of type "int" in function "store_embedding"
  Type "Unknown | None" cannot be assigned to type "int"
    "None" is incompatible with "int"
```

## Repro steps

Copy the code provided above into Visual Studio Code with Pylance installed and type-checking enabled.

## Expected behavior

There should not be a type error.

## Actual behavior

There is a type error.

## Logs

- `Python`: https://pastebin.com/raw/BnScDQT9
- `Python Language Server`: https://pastebin.com/raw/UZ31PmLw

**Comment by erictraut** [comment]
This behavior is as designed. You're attempting to use a type guard pattern that is not supported. For a full list of supported type guards, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). Each type guard pattern is very specific and requires special-case handling in a type checker. It's unlikely that we would ever add something specifically for the complex pattern that you're using here (`any(x is None for x in [a, b, c])`) because this specific pattern would be rare.

For complex type guard patterns like this, you have the option of writing a "user-defined type guard function" as described in [PEP 647](https://peps.python.org/pep-0647/).

You could also modify your code so it uses the supported type guard patterns. Here's an example:

```python
if user_id is None or user_username is None or user_display_name is None:
    raise ValueError("user_id, user_username, or user_display_name is None!")
```

If you'd prefer not to see type checking errors, you also have the option of setting the typeCheckingMode to "off".
