### ISSUE TITLE
Diagnostics not showing up for files opened but not displayed in the editor

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#5249]
## Code Snippet
In my workspace folder, I have 3 files sitting side by side.

```python
# a.py
from b import add_numbers
from c import multiply_numbers

# b.py
def add_numbers(a, b):
    return a + b

# c.py
def multiply_numbers(a, b):
    return a b
```

## Repro Steps

1. Open the workspace in vscode, open all 3 files, with a.py displayed in the editor.
![image](https://github.com/microsoft/pylance-release/assets/100439259/b57c58b0-aaa3-4b85-b8db-f63c677ca442)

2. Set `"python.analysis.diagnosticMode"` to `"openFilesOnly"`
3. Save and close window.
4. Open vscode again and observe the error list.
## Expected behavior

Diagnostics for `c.py` show up in the error list.

## Actual behavior

Diagnostics for `c.py` doesn't show up in the error list until clicking on the `c.py` file tab to switch to display `c.py`

**Comment by erictraut** [comment]
This is a VS Code behavior, and I think it's by design. When VS Code starts, it restores any tabs that were previously open, but it treats only the frontmost one as "open". It doesn't not send an "open file" command to language servers for any of the background tabs. Pylance therefore doesn't know that these background tabs are open. If you bring one of these tabs to the foreground, VS Code will send the "open file" command to Pylance, and it will then treat it as though it's open.

**Comment by StellaHuang95** [comment]
Thanks, that makes sense:)
