### ISSUE TITLE
Support hiding "private" variables/attributes for auto complete 

### ISSUE THREAD

**Issue by marsfan** [microsoft/pylance-release#5281]
While Python does not technically have private variables, it is a standardized in PEP8 that single and double underscores at the start of a variable name means that the variable is for internal use only. Some Python IDEs support this, and do not display variables with such prefixes outside of their scope. It would be nice if there was a setting in VS code to enable this behavior. 

Source: https://www.python.org/dev/peps/pep-0008/#id36

**Comment by debonte** [comment]
> Any way to achieve either hiding private methods in intellisense or at least showing them last rather than first?

They are currently sorted last. I'm not sure when this changed.

If you'd prefer that they be omitted from the suggestion list, please up-vote this enhancement request: https://github.com/microsoft/pylance-release/discussions/4258

**Comment by idan22moral** [comment]
I'm facing a similar problem with private attributes in pydantic:

![image](https://github.com/microsoft/pylance-release/assets/19193227/8c7f5a20-91f9-4d5c-b27a-a270d76120dc)
As you can see, I define a model (class, dataclass to be more specific) consisting of public and private fields.  
When Pylance hints me with the function's signature, I see the private attributes in the signature too.

But when I got to get the fields auto-completion, I now see public fields only:

![image](https://github.com/microsoft/pylance-release/assets/19193227/f53cc02b-e243-49fc-b511-09e81428bb9f)

![image](https://github.com/microsoft/pylance-release/assets/19193227/62612f4f-c393-4d84-b2af-a63430ef1e3b)



There is one place where this verbose fields list is acceptable, and it is the class-preview block on hover:

![image](https://github.com/microsoft/pylance-release/assets/19193227/9f6ab84b-8da7-472f-9f71-87143a8e6589)
That's because it shows a preview of what the model actually consists of, and it is not a function parameter list.

@debonte would you say this example is related to the discussed enhancement request? or should I open a new separate issue?

**Comment by debonte** [comment]
> @debonte would you say this example is related to the discussed enhancement request? or should I open a new separate issue?

@idan22moral, please open a separate issue. It's not clear to me that we should ever hide parameters in signature help. You're welcome to argue for your desired behavior in a separate issue though.

> There is one place where this verbose fields list is acceptable, and it is the class-preview block on hover:
> ![image](https://github.com/microsoft/pylance-release/assets/12820898/0766666e-0e08-4f18-9529-6ff9af3a32cd)

That hover info isn't for the class, but rather for the generated `__init__` method. And there again, I don't believe we should be hiding any parameters. The hover info for the `Magic` class just looks like this:

![image](https://github.com/microsoft/pylance-release/assets/12820898/c65a9752-b35b-4dc1-9271-c1e796d24c74)

Btw, Pylance's support for pydantic's data classes comes via [their use of `dataclass_transform`](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_model_construction.py#L59) where `PrivateAttr` is not listed as a [field specifier](https://peps.python.org/pep-0681/#field-specifiers). The only field specifier listed is `Field`.

If you switch from `PrivateAttr` to `Field` as shown below, you will get the signature help behavior that you're looking for even if the private field doesn't have a leading underscore. With this change, Pylance isn't hiding the `_private_field` parameter in signature help. It actually doesn't believe that there is a `_private_field` parameter on `__init__` at all -- that's what `init=False` is specifying.

```python
from pydantic import BaseModel, Field

class Magic(BaseModel):
    _private_field: str = Field(init=False, default="blabla")
    regular_field: str
```

Signature help:
![image](https://github.com/microsoft/pylance-release/assets/12820898/f1187771-49ef-4d35-a37d-0b00a42c2a16)

Hover on `__init__` usage:
![image](https://github.com/microsoft/pylance-release/assets/12820898/8042d5b1-5beb-4d37-91a8-d0d01c1ee436)

**Comment by idan22moral** [comment]
@debonte I've just finished writing my [proposal](https://github.com/pydantic/pydantic/issues/9234#issuecomment-2067494038) to Pydantic regarding the discussed behavior, and now I see your comment. Funny timing 🤭 

After some digging (since Pydantic internals, dataclasses and Pylance+Pyright are new areas for me),
I came to the understanding of exactly what you described. So thank you for the validation.

As you said, the problem is not with Pylance/Pyright, but the field specifiers listed by Pydantic.

Thanks again for your informative comment!
