### ISSUE TITLE
Folder Level Suppression for Predefined Set Of Variables Injected Using setattr

### ISSUE THREAD

**Issue by sushantshah-dev** [microsoft/pylance-release#5286]
Injection:
```python
def initialize(context_name):
    for tag in paired_tags:
        setattr(sys.modules[context_name], tag, type(tag, (Element,), {"name": tag, "paired": True}))
        
    for tag in paired_textonly_tags:
        def __init__(self, content="", **kwargs):
            self.attributes = []
            self.children = [content]
            self.styles = kwargs.pop("styles", [])
            for key, value in kwargs.items():
                self.attributes.append(f'{key}="{value}"')
                
        setattr(sys.modules[context_name], tag, type(tag, (Element,), {"name": tag, "paired": True, "__init__": __init__}))
        
    for tag in unpaired_tags:
        setattr(sys.modules[context_name], tag, type(tag, (Element,), {"name": tag, "paired": False}))
```

Usage:
```python
from modules import html_py

html_py.initialize(__name__)

page = html(lang="en", children=[ 

])
```

I have arrays consisting of all HTML5 tags. This will be used in multiple files.

Any way to suppress errors on a specific directory for specific variables (reportUndefinedVariable)?

Maybe creating a file at root just like .gitignore?

**Comment by debonte** [comment]
You can change the severity (or suppress) a particular diagnostic at the workspace level using `python.analysis.diagnosticSeverityOverrides` or in a `pyrightconfig.json` file. Or you can do so at the file level using [comments](https://microsoft.github.io/pyright/#/comments?id=file-level-type-controls). Or suppress them at the [line level](https://microsoft.github.io/pyright/#/comments?id=line-level-diagnostic-suppression).

But there isn't a way to change the severity or suppress diagnostics for particular subdirectories.

**Comment by sushantshah-dev** [comment]
I would assume the workspace and folders are the same. Am I wrong?

**Comment by debonte** [comment]
> Any way to suppress errors on a specific directory for specific variables (reportUndefinedVariable)?

> Also, how would I modify pyrightconfig.json to act the same as # type: ignore[html,head,...]

Oh, I misunderstood what you were asking. You could suppress `reportUndefinedVariable` globally or at the file level, but not for particular variable names.

> I would assume the workspace and folders are the same. Am I wrong?

If your workspace looks like this:

```text
root
    subdir1
        file1.py
    subdir2
        file2.py
```

You can use VS Code settings or `pyrightconfig.json` to control the severity of diagnostics across the entire workspace, but you couldn't, for example, have different severities for all files within `subdir2` since the VS Code settings are global and `pyrightconfig.json` is only supported at the root level.

If you're talking about a multi-root workspace (see `Add Folder to Workspace...`), I believe we support having separate `pyrightconfig.json` files for each root of the workspace.

**Comment by judej** [comment]
@sushantshah-dev, if this does not resolve the issue, please reopen.
