### ISSUE TITLE
How to ignore "Cycle detected in import chain" so vscode stops showing in on problems

### ISSUE THREAD

**Issue by fried** [microsoft/pylance-release#531]
In my package I have a `__init__.py` several of the modules import each other in `if TYPE_CHECKING` blocks because they need to reference each others types.   My tests pass but pylance will not stop telling me about the cycle on the first line of my `__init__.py` file.  How do I silence pylance about this particular occurrence of this error.  Is there a # noqa: equivalent for pylance?

**Comment by erictraut** [comment]
There's no way to disable the "reportImportCycles" diagnostic rule on a file-by-file basis because (unlike other diagnostic rules) this one applies to multiple files. Since it's a cycle, the file where this diagnostic is reported is somewhat incidental. It could be reported in any file within the cycle.

I presume that you have typeCheckingMode set to "strict"? The "reportImportCycles" diagnostic rule is not enabled by default if you use "basic" mode. If you're not interested in detecting or fixing cycles, you can disable this particular diagnostic rule.

If two files need to reference each others types, that's an indication that you have improper architectural layering in your code. If you're able to refactor the code to address the problem, that's preferable to silencing this diagnostic. I added the cycle check because my team's code base had several nasty cycles. We refactored the code and eliminated them, and that diagnostic check has prevented new cycles from appearing.

**Comment by dsuch** [comment]
Hello @erictraut,

I am in exactly the same position as @fried who originally reported it.

Please remember that we are talking about type checking hints guarded by "if 0:" or "if typing.TYPE_CHECKING" conditions.

There are no "architectural issues" here. There are no cyclical imports here - the imports are added purely for the type checker. They never existed until I wanted to add a type hint. They never execute in runtime either.

Note that I am quite interested in warnings about real import cycles and I generally run pylance in a mode that is much stricter than the default strict mode. But this here is simple false positive, nothing else.

While I like the fact that you tend to educate a lot of people here or in the pyright tracker, which I understand is based on your experience with leading a team at Microsoft, please also note that that are plenty of experienced people who know what they are doing and they add hints to already existing codebases, well designed and well working, just without type hints.

Also, this is yet another manifestation of the fact that a feature that pylance really needs are per-line ignores for specific conditions. This keeps resurfacing in many tickets, I notice the lack of it on a regular basis myself and this is a genuine need.

Regards.

**Comment by erictraut** [comment]
If you are importing types (whether or not under a TYPE_CHECKING conditional) for type checking purposes, then you are clearly using those types within the module. That means the module is depending on those types. And if the module that defines those types depends on the module in question, then you have an import cycle from an architectural standpoint. If you care about architectural layering, you should refactor so you can eliminate the cycle. If you do not care about architectural layering, then you should leave the `reportImportCycles` check disabled.

This check is extremely strict by design. Perhaps it should not be enabled by default in "strict" type checking mode. I think it would be reasonable to leave it disabled unless it's specifically requested in the configuration. Would that address your concern?

When you say "real import cycles", I presume you mean "cycles that will result in a runtime exception"? Those are very difficult to detect deterministically because they sometimes depend on dynamic (temporal) ordering of imports that are almost impossible to model statically.

The cyclical import check isn't reported on a particular line because it's performed on full modules. It's reported on the first line a one of the modules in the cycle. So there's no way to `# type: ignore` this particular diagnostic. I guess that's further reason to consider disabling it by default.

**Comment by dsuch** [comment]
Hi Eric,

all that I am saying is that I have a large codebase that is well designed and that works very well. There is nothing that needs to be changed as far as its architecture is concerned.

I keep adding type hints to it and there are plenty of places where I need to change the logic purely to satisfy the type checker. I can agree with many of such occurrences but this is not one of them.

This is a very simple case of a false positive. There were no cyclical imports, runtime or not, until I added the type hint guarded through an "if 0:" which for the past 20+ years of my using Python has been the idiom to use to exclude code from various processes, type checking including.

I am not asking for checking complex things. I am simply saying that putting things in blocks under "if 0:" or "if TYPE_CHECKING" is self-evidently not going to result in any runtime cyclical imports and that should not really result in any lengthy architectural discussions. To me, this is obvious and I just do not know how else to present the same point again.

You are the architect of this product, I think, so it is your right to develop in any direction you see fit. I am just a person who offers feedback of how your product is used in practice, where it can be improved, what its deficiencies or strengths are, and how to better it. I do it because it is in our mutual interest for me to do it.

Naturally, for each one person that does offer you feedback you can assume there will be more who keep quiet and do not bother contacting you at all, as is always the case with product feedback.

**Comment by erictraut** [comment]
The `reportImportCycles` diagnostic check is intended to detect architectural layering violations in a code base. It is implemented by building a graph of cross-module dependencies — as seen by the static type analyzer — and reporting cycles within that graph. 

All features in pyright are implemented through the lens of _what the static type analyzer sees_. `TYPE_CHECKING` conditionals are the prescribed way to "lie" to the type analyzer about what it should see relative to what the Python interpreter sees as runtime. I recommend using `TYPE_CHECKING` sparingly because it leads to fragility when the type checker isn't analyzing the code that runs at runtime. Of course, you're free to use `TYPE_CHECKING` in any way you see fit within your code base, but please be aware that it has some major downsides. The same advice applies to `if 0:`.

What I'm hearing from you is that you don't value architectural layering. That's fine. You are welcome to disable this check if you don't want to enforce layering in your code base. I do value architectural layering because, in my thirty years of experience as a professional software developer, I've found that code bases that don't honor architectural layering are more fragile and more difficult to maintain. Layering is something I want to enforce in my team's code base, and this diagnostic check is designed to do that. Viewed through this lens, these are not false positives. The check is doing exactly what it was designed to do.

I'm hearing that the `reportImportCycles` check doesn't meet your needs. You (and potentially other pyright users) want to disable it. How are you enabling it currently? Are you explicitly enabling `reportImportCycles`, or are you implicitly enabling it by setting `typeCheckingMode` to "strict"? I assume the latter. I suggested above that we should maybe not enable `reportImportCycles` as part of the "strict" rule set. This would allow you and other users to enable "strict" type checking without being forced to opt in to `reportImportCycles`. I'm interested in your thoughts on this proposal.

**Comment by adam-grant-hendry** [comment]
> I'm interested in your thoughts on this proposal.

I would call the error `reportArchitecturalLayeringViolation` and explain what that means. You will confuse normal python users by calling it an "import cycle" because what you are talking about is not that (importing happens at runtime).

If the code runs without error when `typing.TYPE_CHECKING` is used, that is a clear indication what is being described isn't an import cycle:

- If a module needs something from another module, it must import the module first. Otherwise, at runtime, the module would throw an `AttributeError` (or equivalent) that it `cannot access item`, not an `ImportError`. If an import is under `typing.TYPE_CHECKING`, the python runtime will not import it.

- If instead you move the import outside the `typing.TYPE_CHECKING` check, you will get an `ImportError` if the python runtime sees the two modules are trying to import each other.

As a user, I want to catch _actual_ import cycles, so I don't want to turn `reportImportCycles` off. I second @dsuch 's [comment](https://github.com/microsoft/pylance-release/issues/531#issuecomment-1088287562). I think this tool is wonderful because you see in your editor with linting where a cycle is occurring (I want this on).

> What I'm hearing from you is that you don't value architectural layering....I added the cycle check because my team's code base had several nasty cycles. We refactored the code and eliminated them, and that diagnostic check has prevented new cycles from appearing.

- What is "architectural layering"? If you mean "import cycle", that is not what it is in python.
- What specific kinds of problems did having this report issue when an import was under a `typing.TYPE_CHECKING` if statement?

> You are welcome to disable this check if you don't want to enforce layering in your code base.

It is a mistake to ask users to turn off the `reportImportCycles` because this will hide actual import cycles.

> When you say "real import cycles", I presume you mean "cycles that will result in a runtime exception"? Those are very difficult to detect deterministically because they sometimes depend on dynamic (temporal) ordering of imports that are almost impossible to model statically.

Importing is a runtime concept, hence ALL import cycles yield a runtime exception; @dsuch is right.

What I'm hearing from you is your tool is unable to differentiate true import cycles from those hidden under a `typing.TYPE_CHECKING` check. That is fine, but then I would call the error `reportPotentialImportCycle`.

> This is a very simple case of a false positive.

Couldn't agree more. If the tool is unable to detect actual import cycles, the report should be `reportPotentialImportCycle` and 
we need to add per-line ignores so we can distinguish real import cycles from false positives.

**Comment by blakeNaccarato** [comment]
I landed on this topic while Googling my issue with a false-positive `reportImportCycles`. I have `__init__.py` perform a wildcard import from an `api.py` module in a certain package structured as follows:

```plaintext
package
  __init__.py  (with `from package.api import *`)
  api.py (with `__all__` defined to constrain the wildcard import)
  <other modules which don't import anything from the above>
```

The `api` module only imports from other modules, and no other modules import from `api`. Still, this triggers a `reportImportCycles` error in `__init__`, presumably due to the package importing part of itself the first time it is imported. I guess this is technically a cycle, but this is a common pattern for simple packages which only have a few functions defined at the top level, imported from a submodule that is really just the API.

In any case, I wanted to point to the workaround mentioned in https://github.com/microsoft/pyright/issues/3489#issuecomment-1133481764 because it's not discussed here. And the documentation that covers this over at https://github.com/microsoft/pyright/blob/main/docs/comments.md#file-level-type-controls is not easily discoverable (apparently the "documentation" is just the `docs` folder in the repo with no discernible index?). Basically, you can ignore `reportImportCycles` at the file level  by putting `# pyright: reportImportCycles=none` or `# pyright: reportImportCycles=false` at the top of the module, in my case `__init__.py`. It's not the perfect solution, because you can't toggle it at the line-level, but it works alright.

**Comment by mateenkasim** [comment]
I think it's pretty common to have type cycles that don't imply architectural problems when using databases. In my case, this happens all the time in Django:

```python
if typing.TYPE_CHECKING:
    from users.models import User

class Project(Model):
    owner: 'User' = ... # reference to user
```

```python
if typing.TYPE_CHECKING:
    from projects.models import Project

class User(Model):
    # this reverse relation is auto-generated by Django,
    # but having the type here makes development easier and auto-complete better
    projects: 'Project' # list of all owned projects
```

It would be strange to call a bidirectional DB relation an "architectural problem." This would be a great situation to ignore cycles if the imports are under `typing.TYPE_CHECKING`.
