### ISSUE TITLE
newest pyright 1.1.344 into pylance? (current has 1.1.336)

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/pylance-release#5329]
## Problem
We are upgrading our repositories to python 3.12 and pyright 1.1.344.

We are group of mixed people some just use python from time to time, others daily.

I personally don't use vscode daily but fits the needs of most people in several languages including python,
to avoid having to support internally several IDEs we decided ourselves a while ago for vscode, thus we kept saying: 
_"if you don't want to setup your editor for python just use vscode, if you want to use something else you are on your own"_.

Now during the upgrade we are in the situation where vscode reports different problems than the latest pyright used inside the venv.
At the time of writing (5 Jan 2024)
- Pylance is at v2023.12.1 (using pyright 1.1.336 under the hood)
- pyright is at 1.1.344 
- numpy is at 1.26.2

If there are mismatches between the editor and ci it makes makes people that are not very close to python say something in this line 
_"you see, I told you python is not a good language to work with"_

### Reprex
```py
# myfile.py
import numpy as np
x = np.float64(4.2) / 2.1
```
![image](https://github.com/microsoft/pylance-release/assets/6558089/562fd597-da05-4ddf-ad91-ab8aada58da1)
But when pyright (1.1.344) is called over the cli won't report any errors.

### Question 1
How often can we expect pyright to be merged into pylance? Sometimes is more than once a month sometimes takes longer

	* 2023-11-15 a78e2b10f - [PylanceBot] Pull Pylance with Pyright 1.1.336 (#6457) [GitHub] E
	| * 2023-11-01 64c9c3ff9 - [PylanceBot] Pull Pylance with Pyright 1.1.334 (#6287) [GitHub] E
	| | * 2023-07-14 8e021d2ae - [PylanceBot] Pull Pylance with Pyright 1.1.317 (#5505) [GitHub] E
	| | | * 2023-04-19 5b6a1d3b7 - [PylanceBot] Pull Pylance with Pyright 1.1.304 (#4975) [GitHub] E
	| | | | * 2023-04-12 50d44cf9d - [PylanceBot] Pull Pylance with Pyright 1.1.303 (#4946) [GitHub] E
	| | | | | * 2023-03-01 93a4ef878 - [PylanceBot] Pull Pylance with Pyright 1.1.296 (#4716) [GitHub] E

### Question 2
Is there a way to instruct pylance to use pyright from current activated environment?
  If is not possible how should we approach the problem of the editor reporting different problems than e.g. ci, or pyright being called over the cli?

### Question 3
Would it be possible to get the pyright version to be reported in vscode too? Currently only the commit hash is being shown
  
  ![image](https://github.com/microsoft/pylance-release/assets/6558089/1722f873-e54b-4676-a7b1-d1288e969c15)

   
## Notes

My vscode experience is limited I just find myself in the situation of not using vscode daily but need to take care of the python dev experience for non-daily-python coders.

Any hints or advice are appreciated

**Comment by debonte** [comment]
> How often can we expect pyright to be merged into pylance? Sometimes is more than once a month sometimes takes longer

Great question. I added a [wiki page](https://github.com/microsoft/pylance-release/wiki/Release-process) with a high-level overview of our release process/schedule. Our release schedule changed recently and we didn't advertise that to our users.

Currently Pylance is lagging behind Pyright more than usual. In an effort to better support virtual file systems, symlinks, remote files, etc, we recently [changed Pyright](https://github.com/microsoft/pyright/pull/6519) to track files via URI rather than file path. Making this change in Pyright was quite time consuming. We're now making the same type of changes in Pylance, and that effort is even more complex. Ingestion of new Pyright builds is blocked until that work finishes.

> Is there a way to instruct pylance to use pyright from current activated environment?

No. [This comment](https://github.com/microsoft/pylance-release/issues/5207#issuecomment-1839339926) provides some details on why that's not possible.

> If is not possible how should we approach the problem of the editor reporting different problems than e.g. ci, or pyright being called over the cli?

See [our current guidance](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md#pyright-version-and-pylances-underlying-pyright-version-are-different). If this won't solve your issues, we'd be interested in better understanding your needs.

> Would it be possible to get the pyright version to be reported in vscode too? Currently only the commit hash is being shown

That's a good idea. I opened a separate issue to track it: https://github.com/microsoft/pylance-release/issues/5331

**Comment by FrancescElies** [comment]
> Currently Pylance is lagging behind Pyright more than usual. In an effort to better support virtual file systems, symlinks, remote files, etc, we recently https://github.com/microsoft/pyright/pull/6519 to track files via URI rather than file path. Making this change in Pyright was quite time consuming. We're now making the same type of changes in Pylance, and that effort is even more complex. Ingestion of new Pyright builds is blocked until that work finishes.

Thanks for the detailed explanation

> See [our current guidance](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md#pyright-version-and-pylances-underlying-pyright-version-are-different). If this won't solve your issues, we'd be interested in better understanding your needs.

I guess we will wait for the newest pyright to be included in pylance, there are improvements in pyright we definitely would like to have.

> That's a good idea. I opened a separate issue to track it: https://github.com/microsoft/pylance-release/issues/5331

👍


Everything is now clear, closing.

Hopefully, one day, business interests will merge with the goal of open-sourcing more of Pylance, and the division between Pylance and Pyright will gradually blur

**Comment by DetachHead** [comment]
> I guess we will wait for the newest pyright to be included in pylance, there are improvements in pyright we definitely would like to have.

you could use my pyright fork, [basedpyright](https://github.com/detachhead/basedpyright). we've solved this problem by making the vscode extension use the same version of the pyright package that's installed in your venv.

> Hopefully, one day, business interests will merge with the goal of open-sourcing more of Pylance, and the division between Pylance and Pyright will gradually blur

we've re-implemented some of pylance's exclusive features such as semantic highlighting, inlay hints and quick fixes for import suggestions. though there's still quite a few features we don't have yet, which is why [we support using both pylance and basedpyright](https://github.com/DetachHead/basedpyright?tab=readme-ov-file#using-basedpyright-with-pylance-not-recommended)

**Comment by FrancescElies** [comment]
@DetachHead thanks for posting about basedpyright, didn't know about that project.

The project seems to address two of our main pain points, not being able to use same pyright version in our venv and the vscode monoculture problem where only features like inlay hints are avaiilable, we wished similar suff for other editors too (e.g. #4169).

We will definitely give it a try!
