### ISSUE TITLE
Extract variable shouldn't work on assignments

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#5339]
## Code Snippet

```python
x = 1
```

## Repro Steps

1. Select  `x = 1` and do "extract variable"

## Expected behavior

Extract variable code action shouldn't show up.

## Actual behavior

We get
```python
new_var = x = 1
new_var
```

**Comment by StellaHuang95** [comment]
Copied the issue from https://github.com/microsoft/pylance-release/issues/5277#issuecomment-1861531993

**Comment by soorajaryan007** [comment]
how should i fix this issue,i am newcomer on github

**Comment by debonte** [comment]
> how should i fix this issue,i am newcomer on github

Hi @soorajaryan007, I'm not sure what you're asking. If you're asking if you can submit a PR (code change) to fix this issue, the answer is no -- Pylance is closed source. If you're asking how to find a release of Pylance with this issue already fixed, there is no such release yet. Subscribe to this issue. When a fix is available we will comment here to tell you what build it is fixed in.

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.3.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20243102-27-March-2024-PreRelease)
