### ISSUE TITLE
Inconsistent type inference for class based decorator for ParamSpec

### ISSUE THREAD

**Issue by E5presso** [microsoft/pylance-release#5342]
## Environment data

-   Language Server version: v2023.12.1
-   OS and version: macOS Sonoma 14.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11 (Poetry 1.7.0)

## Code Snippet

```python
from typing import Generic, TypeVar, Callable, ParamSpec

P = ParamSpec("P")
R = TypeVar("R")


class ClassDecorator(Generic[P, R]):
    def __call__(self, func: Callable[P, R]) -> Callable[P, R]:
        ...


@ClassDecorator()
def func1(name: str, age: int) -> tuple[str, int]:
    return name, age


def func2(name: str, age: int) -> tuple[str, int]:
    return name, age


func2 = ClassDecorator()(func2)


assert func1(name="John", age=30) == ("John", 30) # (function) def func1(...) -> Unknown
assert func2(name="John", age=30) == ("John", 30) # (function) def func2(name: str, age: int) -> tuple[str, int]
```

## Repro Steps

1. When I type `func1` to call that, type annotation is Unknown
2. When I type `func2` to call that, type annotation is keyword argument-like Parameter Spec

## Expected behavior
I heard that `@decorator` syntax is just a syntax-sugar for closure.
So, inferred type annotation for `func1` and `func2` must be same. (From what I understand)

## Actual behavior
But actual inferred type of `func1` is just unknown.

## Logs

```
-
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is doing the right thing here.

The problem is that you've defined `P` and `R` as class-scoped type variables in your `ClassDecorator` protocol definition. That means they are specialized at the time you construct `ClassDecorator` — as part of the expression `ClassDecorator()`. Since there's no `__init__` or `__new__` method and you don't provide any explicit specialization (e.g. `ClassDecorator[[str, int], tuple[str, int]]()`), the type variables take on the value of `...` and `Any`. This is the behavior dictated by the typing spec, and pyright is following the spec correctly here.

You can fix this by changing `P` and `R` to be scoped to the `__call__` method. That is, change your protocol definition to:

```python
class ClassDecorator:
    def __call__(self, func: Callable[P, R]) -> Callable[P, R]:
        ...
```
