### ISSUE TITLE
False positive for unbound variable assigned in sequence match statement

### ISSUE THREAD

**Issue by Keating950** [microsoft/pylance-release#5352]
## Environment data

-   Language Server version: v2023.12.1
-   OS and version: OpenSUSE Tumbleweed
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.7

## Code Snippet

```python
def match_list(values: list[str]):
    match values:
        case []:
            raise ValueError("A list with one element is required")
        case [elem]:
            value = elem
        case [elem, *rest]:
            raise ValueError("Too many arguments")
    return value  # "value" is possibly unbound (reportUnboundVariable)
```
And to show that the code works as intended:

```python
try:
    match_list([])
except ValueError:
    pass
else:
    raise RuntimeError("Expected ValueError")

try:
    match_list(["a", "b", "c"])
except ValueError:
    pass
else:
    raise RuntimeError("Expected ValueError")

assert match_list(["a"]) == "a"
```

## Expected behavior

Pylance does not consider the variable to be possibly unbound at the end of `match_list`, since it is assigned to the first element of `values` in the the only code path through which it can be reached.

## Actual behavior

Pylance reports the variable as possibly unbound.

**Comment by erictraut** [comment]
Pyright is working as intended here. This isn't a bug.

Type exhaustion detection within a match statement is implemented via a technique called "type narrowing". If you're interested, you can read more information [here](https://microsoft.github.io/pyright/#/type-concepts-advanced).

In this example, the type of the subject expression (`values`) cannot be narrowed by the first case statement. It remains `list[str]`. That's because `list` in the Python type system has no notion of length, so there's no way to express the type "`list[str]` where the length is greater than 0 elements". The second and third case statements likewise cannot narrow the type. That means the static type checker must conclude that the match statement is not exhaustive, and it's possible to fall through without any pattern matches.

Other static type checkers like mypy do the same thing here, so this isn't unique to pyright.

You can work around this limitation by adding a catch-all case statement:

```python
        case _:
            raise ValueError("Shouldn't get here")
```
