### ISSUE TITLE
Advice on fixing attrs import quick-fix

### ISSUE THREAD

**Issue by Tinche** [microsoft/pylance-release#5388]
Howdy.

I'm one of the maintainers of the _attrs_ library and avid VS Code user. When attempting to auto-import the `define` _attrs_ function, the quick fix popup suggests importing it from the `attr` package, instead of from `attrs`.

The _attrs_ library contains two packages, `attr` and `attrs`. The `attr` package, while not deprecated, is legacy at this point. `define` is part of our next-gen API, and ideally the suggestion would be to import it from `attrs` instead. (The same goes for some other symbols, like `frozen` and `field`.)

What can we do to make this better, either on our side (maybe it's a packaging issue?) or on yours?

**Comment by debonte** [comment]
@heejaechang is the expert here, and may correct me. But I believe that this is because when our indexer finds aliases, it will deduplicate them down to the one "best" location. We'll choose the one with the shortest module path (shortest in terms of levels). When the length is the same, as in this case where `attr` and `attrs` have the same number of levels (1), we choose the non-alias declaration, which in this case is `attr`.

Assuming I'm correct, you could fix this on your side by making `attr.define` an alias of `attrs.define` instead of the other way around. But I'm guessing that inverting that relationship would not be trivial.

We [recently](https://github.com/microsoft/pylance-release/issues/3318) special-cased the symbols that are both in `typing` and `collections.abc` so both are shown. I don't think we want to do that for 3rd party packages though, as it would be a maintenance headache.

It would be nice if package authors could control this somehow, but I don't have any good ideas.

**Comment by Tinche** [comment]
> Assuming I'm correct, you could fix this on your side by making attr.define an alias of attrs.define instead of the other way around. But I'm guessing that inverting that relationship would not be trivial.

Interesting. I'm going to talk to Hynek and see if we can do this.

Thanks for the info @debonte !

**Comment by Tinche** [comment]
I got the boss to accept this change!

> Ok, but I want to clarify that this deduplication approach is just Pylance's convention. Other language servers (ex. PyCharm) may behave differently.

Sure, but I use VS Code and I really wanted to scratch this itch ;)
