### ISSUE TITLE
Suggest __future__ module as import option

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#539]
## Environment data

-   Language Server version: 2020.10.3
-   OS and version: macOS
-   Python version: 3.9

## Expected behaviour

Typing `from __` or `import __` I would expect to see the `__future__` module as an option.

## Actual behaviour

Only the Code snipped `__main__` (which makes no sense in the context of an import) and modules with one leading underscore are suggested.
**Note**: Although not displayed in the screenshot, `__future__` is not even suggested in the scroll list.

<img width="785" alt="Screen Shot_Future_import" src="https://user-images.githubusercontent.com/30130371/97515126-a0e0bc80-1990-11eb-86bb-b4859efc7d24.png">

## Logs

```
XXX
```

## Code Snippet / Additional information

**Example usage**
```python
from __future__ import annotations
```

**Comment by jakebailey** [comment]
`__future__` is handled specially in the parser and type checker, but it's likely not being added as a valid module choice in the completion provider. Would make sense to include.


Regarding The `__main__` import, that's a snippet; those are provided by the Python extension and we don't have much control over those. (Personally, I disable snippets altogether because they simply aren't powerful enough to understand the code context. They're basically loose regex.)

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020112-18-november-2020
