### ISSUE TITLE
Is there a way to use type assertion as a type hint?

### ISSUE THREAD

**Issue by TotallyNotChase** [microsoft/pylance-release#541]
There are many times when I have a variable and type hint like so-
```py
foo: Union[str, None] = None
```
Essentially a `Union` of two types (not necessarily `None`).

At a later time, the variable may have changed in a scope not immediately visible to the type checker but visible to the programmer. Now, when this variable is passed to a function expecting an `str`. The typechecker would raise an error saying `Union[str, None]` is not assignable to type `str`. Which is correct - however is there a way to force the variable to be interpreted as a specific type? Something akin to typescript's `as`?
```ts
bar(foo as str)
```

I know this is more of a python question rather than pylance, but I'm not entirely sure where else to ask where people would be focusing on type checking.

**Comment by erictraut** [comment]
There are several ways that the type checker can "narrow" a type. Most of these involve standard conditional expressions that verify the type. Supported narrowing expressions include, for example:

```python
if foo is not None:
   ...

if isinstance(foo, str):
    ...

if foo:
    ...
```

In my team's Python code base, we typically insert `assert` statements in cases where we are confident that a type can be narrowed. This technique is self-documenting, and it results in runtime errors in the rare case where our assumption is incorrect.

```python
assert foo is not None
bar(foo)
```

Python doesn't offer any downcast operator like the `as` operator in TypeScript. It does offer a `cast` method, but I recommend using it as a last resort because it completely disables all type checks, leaving you vulnerable to bugs.

```python
bar(cast(str, foo))
```

**Comment by TotallyNotChase** [comment]
I see. `assert` is a bit tedious but I suppose it's the only way right now.
