### ISSUE TITLE
Python does not discover new value when subclassing flask config

### ISSUE THREAD

**Issue by Zenthae** [microsoft/pylance-release#5450]
## Environment data

-   Language Server version: 2024.1.104
-   OS and version: Windows 11 23h2
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.12.1

## Code Snippet

```python
class CustomConfig(flask.Config):
    TEST = ""


class Flask(flask.Flask):
    config_class = CustomConfig


app = Flask(__name__)

app.config.TEST
```

## Repro Steps

Basic flask install

## Expected behavior

`app.config.TEST` type should be detected

## Actual behavior

Type of "TEST" is unknown

## Logs

```
XXX
```

**Comment by heejaechang** [comment]
Hi. thank you for reporting the issue!

unfortunately, such dynamic behavior is not something static analysis tool can provide. 

`flask` is `py.typed` (https://github.com/pallets/flask/blob/main/src/flask/py.typed) package and their code has this (https://github.com/pallets/flask/blob/main/src/flask/sansio/app.py#L319) for `app.config` and `make_config` (https://github.com/pallets/flask/blob/main/src/flask/sansio/app.py#L486) returns `Config`

and that's why we don't know about `CustomConfig`

...

for this kind of behavior to work, `App` probably need to be made as `generic` type that track what type `make_config` would return. but probably it could be considered as a breaking change so `flask` package might not want to make such changes. 

anyhow, this is not something static analysis tool can provide.

you probably need something like notebook which actually run the code to get this kind of dynamic behavior support in IDE.
