### ISSUE TITLE
Cannot import sklearn.preprocessing.TargetEncoder

### ISSUE THREAD

**Issue by memeplex** [microsoft/pylance-release#5454]
## Environment data

-   Language Server version: v2023.12.1
-   OS and version: macOS Sonoma 14.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.7
- sklearn 1.4.0

## Code Snippet

```python
from sklearn.preprocessing import TargetEncoder
```
## Expected behavior

Recognize that TargetEncoder is installed and provide docstrings, autocompletion, etc.

*Note: it works as expected for many other classes in the same module.*

## Actual behavior

<img width="614" alt="image" src="https://github.com/microsoft/pylance-release/assets/2845433/429a67d4-76bf-4ff3-8118-3422761169b9">

**Comment by rchiodo** [comment]
I believe this is because TargetEncoder is not exported from the preprocessing module in the stubs. The stubs we use come from here:

https://github.com/microsoft/python-type-stubs/blob/e328827329a072baac06e287bd6146ff80796e5e/stubs/sklearn/preprocessing/__init__.pyi#L36

TargetEncoder should be in that list (as it is exported from the real __init__.py in the library).

**Comment by memeplex** [comment]
Thanks, I've reported the issue to that repo, feel free to close this if you think it's better to track it there.
