### ISSUE TITLE
Type check only working if constant is on the right

### ISSUE THREAD

**Issue by DJJo14** [microsoft/pylance-release#5470]
Why is the first check statement incorrect and the second one correct? 

![image](https://github.com/microsoft/pylance-release/assets/5787161/3386f282-9fe3-4f90-9b05-d3c137904382)

```python
from datetime import datetime
from typing import Optional

var_1: Optional[int]
var_2: Optional[int]

if datetime.now().hour % 2 == 0:
    var_1 = None
else:
    var_1 = 2

if datetime.now().second % 2 == 0:
    var_2 = None
else:
    var_2 = 2

if None != var_1 and None != var_2:
    if var_1 > var_2:
        print("stuf")

if var_1 != None and var_2 != None:
    if var_1 > var_2:
        print("stuf")
```

I get
Operator ">" not supported for types "Literal[2] | None" and "Literal[2] | None"
  Operator ">" not supported for types "None" and "None"
  Operator ">" not supported for types "None" and "Literal[2]"
  Operator ">" not supported for types "Literal[2]" and "None"
```
[{
	"resource": "/c:/Projects/Mobyyyou/mobyyou-bus-coordinator/temp3.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportOperatorIssue",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportOperatorIssue"
		}
	},
	"severity": 8,
	"message": "Operator \">\" not supported for types \"Literal[2] | None\" and \"Literal[2] | None\"\n  Operator \">\" not supported for types \"None\" and \"None\"\n  Operator \">\" not supported for types \"None\" and \"Literal[2]\"\n  Operator \">\" not supported for types \"Literal[2]\" and \"None\"",
	"source": "Pylance",
	"startLineNumber": 18,
	"startColumn": 8,
	"endLineNumber": 18,
	"endColumn": 21
}]
```

this is means the same?

```
>>> baba = None
>>> None != baba
False
>>> None == baba
True
>>> baba == None
True
>>> baba != None
False
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working correctly here, so this isn't a bug.

Pyright supports a large number of "type guard forms". These are conditional expression forms that act to "narrow" the type of variables they act upon. Each type guard form requires specialized logic within the type checker. For a complete list of supported type guards, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-guards). You'll notice that `x is None` and `x == None` are supported forms but `None == x` is not.

We occasionally add support for new type guard forms, but each new addition requires special logic and maintenance and tends to slow down overall type analysis, so the bar for supporting new forms is relatively high. In this case, the workaround is straightforward — use the more common expression form `x != None` rather than `None != x`. The former is arguably more readable than the latter anyway.
