### ISSUE TITLE
warnings.simplefilter rejecting str as action

### ISSUE THREAD

**Issue by memeplex** [microsoft/pylance-release#5478]
## Environment data

-   Language Server version: v2024.2.2
-   OS and version: macOS Sonoma
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.7

## Code Snippet

```python
import warnings

actions = {UserWarning: "ignore"}
for warn_cls, warn_action in actions.items():
    warnings.simplefilter(action=warn_action, category=warn_cls)
```

## Repro Steps

Copy the code above, set `"python.analysis.typeCheckingMode": "basic"`

## Expected behavior

The definition of `simplefilter` is:

```
def simplefilter(action, category=Warning, lineno=0, append=False):
    assert action in ("error", "ignore", "always", "default", "module",
                      "once"), "invalid action: %r" % (action,)
    ...
```

I don't see any reason why the code above shouldn't be accepted as valid. Specially in basic mode.

## Actual behavior

```
Argument of type "str" cannot be assigned to parameter "action" of type "_ActionKind" in function "simplefilter"
  Type "str" cannot be assigned to type "_ActionKind"
    "str" cannot be assigned to type "Literal['default']"
    "str" cannot be assigned to type "Literal['error']"
    "str" cannot be assigned to type "Literal['ignore']"
    "str" cannot be assigned to type "Literal['always']"
    "str" cannot be assigned to type "Literal['module']"
    "str" cannot be assigned to type "Literal['once']"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

I don't know where `_ActionKind` is coming from. It's certainly not part of the warnings module.

**Comment by debonte** [comment]
If you right-click on `simplefilter` and select `Go to Declaration` (not `Go to Defintion`), you'll find the following stubs. These are bundled in Pylance, but come from [`typeshed`](https://github.com/python/typeshed/blob/main/stdlib/warnings.pyi#L38).

```python
_ActionKind: TypeAlias = Literal["default", "error", "ignore", "always", "module", "once"]
# snipped several lines here
def simplefilter(action: _ActionKind, category: type[Warning] = ..., lineno: int = 0, append: bool = False) -> None: ...
```

So from the type checker's perspective, the `action` parameter of `simplefilter` is limited to accepting the `_ActionKind` strings. But Pylance infers the type of your `actions` dictionary as `dict[type[UserWarning], str]` so the type of `warn_action` is seen as `str` which could be any string, not just the valid `_ActionKind` strings.

For most cases, widening the value type of the `dict` from `Literal["ignore"]` to `str` is a good thing. But not in this case.

You can fix this in several ways. One is to explicitly annotate `actions` as `dict[type[Warning], warnings._ActionKind]`:

```python
actions: dict[type[Warning], warnings._ActionKind] = {UserWarning: "ignore"}
for warn_cls, warn_action in actions.items():
    warnings.simplefilter(action=warn_action, category=warn_cls)
```

You could also `cast` `warn_action` to `_ActionKind`. But the annotation approach is better/safer, since then if you typo one of the action values in your dictionary, Pylance will warn you. Whereas with the `cast`, Pylance just trusts that you know what you're doing, even when your action value is something random.

```python
from typing import cast
import warnings

actions = {UserWarning: "ignore"}
for warn_cls, warn_action in actions.items():
    warnings.simplefilter(action=cast(warnings._ActionKind, warn_action), category=warn_cls)
```

**Comment by memeplex** [comment]
Thanks for the explanation. I still find it weird that this code is rejected, but maybe it's so in order that wrong literals can be statically rejected, and the price is this redundant cast, even in a case where there is no type annotation in the original and moreover there is a dynamic check in place. Perhaps using literals here is the more frequent use case.
