### ISSUE TITLE
Support variable substitution in python.analysis settings

### ISSUE THREAD

**Issue by emonette123** [microsoft/pylance-release#548]
You currently do not support variable substitution for your settings. I am talking about ${workspaceFolder} or ${env:SOMEVARIABLE} substitutions. While the VS Code documentation states these substitutions are only supported for tasks.json and launch.json, many settings of python do also support it, like "python.pythonPath" or "python.linting.mypyPath". It feels weird "python.analysis.stubPath" would not support it...

**Comment by jakebailey** [comment]
See also #384.

These are implemented directly by the core Python extension within their configuration system, but VS Code sends us the raw data, so we'd have to reimplement it again and get all of the same data over. If we support these, it will likely have to be a subset unless VS Code itself better improves the configuration system (or we figure out a cross-extension API for all settings).

Note that we already support replacements in pythonPath (as we've hacked that in for environment selection), but that setting doesn't really exist anymore due to the Python extension moving it out of the config to avoid leaking machine info into a committable file.

**Comment by jakebailey** [comment]
Some of these variables (`workspaceFolder` and `env:HOME`) should be supported in the next version for the settings which are paths. It's likely we're going to support more, but these are the preliminary ones we can start with.

**Comment by benlindsay** [comment]
Thanks for the update @jakebailey ! I'd love to see `${fileDirname}` supported as well so PyLance could properly handle a situation like this:

```
| - dir1
| | - utils.py
| \ - script.py
|
\ - dir2
  | - utils.py
  \ - script.py
```

Where each `script.py` would be run from within its own directory and have something like `import utils` inside of it

**Comment by jakebailey** [comment]
That's what `"python.analysis.importHeuristic": true` does, if you want to try it out: https://github.com/microsoft/pylance-release/issues/68#issuecomment-811618343

**Comment by benlindsay** [comment]
Wow, looks like that does exactly what I want, thank you so much!!!

**Comment by DachuanZhao** [comment]
> That's what `"python.analysis.importHeuristic": true` does, if you want to try it out: [#68 (comment)](https://github.com/microsoft/pylance-release/issues/68#issuecomment-811618343)

I set it at ```settings.json``` , and It reminds me that ```Unknown Configuration Setting
No quick fixes available``` ...

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
