### ISSUE TITLE
Why is no type or autocomplete present in test function despite pytest fixture having  type hint on mouseover

### ISSUE THREAD

**Issue by Evan0000000000** [microsoft/pylance-release#5510]
Again searched around for this but didn't see anything that looked like what I'm seeing, but might not be using the right terms.

Using pytest and pytest-mock to write test cases, I have:
```
import pytest

@pytest.fixture
def test_method_fixture(mocker):
   pass
   #mocker.patch('some.func') or similar goes here
```
Mousing over `mocker` (which is a fixture supplied by pytest-mock) in the test case signature shows it to be `Generator[MockerFixture, None, None]`. which I believe is correct?  But in the test case `mocker` is regarded as type `Any` and has no autocomplete.

Would appreciate some help understanding if this is by design, a bug, or if I should take it up with the pytest or pytest-mock folks.

edit-  also discovered that changing this slightly:
```
import pytest

# removed fixture decorator
def test_method_fixture(mocker):
   pass
   #mocker.patch('some.func') or similar goes here
```
Then mocker is type `Any` in the signature and inside the method, as I'd expect without adding a type hint of my own

**Comment by erictraut** [comment]
This is by design. 

Pylance is built on an open-sourced, standards-compliant type checker called pyright. By design, pyright has no specialized knowledge of any third-party libraries like pytest. This is a principle we've established for pyright, and it's unlikely that we'd violate it. That would be akin to the typescript compiler having intrinsic knowledge of (and specialized behavior for) specific third-party libraries.

Pylance provides language server features on top of pyright. This includes limited support for completion suggestions within pytest test functions, which explains why you're seeing type information in the hover text for the pytest fixture.

If you want pyright to perform full type checking on your test function, you'll need to supply explicit type annotations for the parameters just like with other functions or methods.

**Comment by Evan0000000000** [comment]
Thanks Erik that helps a lot -- I'm (very, very broadly) familiar with pyright, I think what threw me was the seemingly different behaviors in adjacent parts of the code. But if pylance is able to add features on top of it that makes a lot more sense.

**Comment by rchiodo** [comment]
This should actually be working in pylance. Heejae added support for first level fixtures in this issue here:
https://github.com/microsoft/pylance-release/issues/4590

**Comment by KacieKK** [comment]
closed as by design, if completion for test parameters doesnt work as expected in pylance please reopen

**Comment by Evan0000000000** [comment]
My apologies for leaving this so long. If I understand #4590  correctly then it seems this should work for me but it doesn't.

![image](https://github.com/microsoft/pylance-release/assets/160069225/d1c5dcf5-869c-428f-a233-03f001802af1)

Since the type here is a Generator would that break this feature? Or could some other aspect of pytest-mock cause it to not work?
