### ISSUE TITLE
Be able to change type checking log level

### ISSUE THREAD

**Issue by IGLADI** [microsoft/pylance-release#5512]
(please don't mind the does not return a value: the function has ->None when it actually returns smth)

This is a documentation code I received from a teacher here is what I have with type checking strict:
![image](https://github.com/microsoft/pylance-release/assets/128155180/fdc0fd84-e707-47b6-b030-766205873aee)
And this with it disabled (like default):
![image](https://github.com/microsoft/pylance-release/assets/128155180/8c20d741-7ef5-486d-a80c-9a58e1d75b88)

From 1 I got some false positive but don't really know why but my real problem is that it's all errors, I would like to be able to change the logging level of type checking to warning, especially for type checking as I like to first code a bit loosely and then come back over it and type hint everything and it helps me be more strict about my code but here I can't even concentrate anymore, it just looks like my code will crash everywhere and won't see real errors if there are any.

Also OOC question but is there some timeout on edit in pylance? I have found a couple of other extensions with a timeout they wait after typing before kicking in and could lower it to make it more snappy but didn't find it in pylance and it feels like pylance is slow especially when I type function parameters and it shows call arguments
(per this parameter:)
![image](https://github.com/microsoft/pylance-release/assets/128155180/51764b10-c65a-464e-9547-eacf693a087e)

**Comment by debonte** [comment]
There is no single setting that will change all diagnostics to warnings, but you can specify a severity (error, warning, or none) for each diagnostic rule using `python.analysis.diagnosticSeverityOverrides` or at the file level as described [here](https://microsoft.github.io/pyright/#/comments?id=comments).

Strict mode is intentionally very opinionated, so if you're writing code in a mode/mindset where you don't care about type checking, strict is probably the wrong choice. You might consider "off".

Note that you can quickly switch between "basic" and "off" via the language status button (`{}`) in VS Code's status bar:
![image](https://github.com/microsoft/pylance-release/assets/12820898/9ad37522-b502-4f79-8be6-64e46c95578e)

> it feels like pylance is slow especially when I type function parameters and it shows call arguments

Inlay hints are intentionally computed on our background thread for performance reasons, so I'm guessing that's why there's a brief delay before they appear. If you feel their behavior should be improved, please file a separate issue. Using a single issue to track multiple unrelated requests is awkward for us.

**Comment by IGLADI** [comment]
> There is no single setting that will change all diagnostics to warnings, but you can specify a severity (error, warning, or none) for each diagnostic rule using python.analysis.diagnosticSeverityOverrides or at the file level as described [here](https://microsoft.github.io/pyright/#/comments?id=comments).

Yeah I see, didn't knew "python.analysis.diagnosticSeverityOverrides" exist but it's still pretty annoying to modify them one by one, ik strict mode is to be strict but I'm more using it as hints to teach me to write better code than anything else.

> Strict mode is intentionally very opinionated, so if you're writing code in a mode/mindset where you don't care about type checking, strict is probably the wrong choice. You might consider "off".
Note that you can quickly switch between "basic" and "off" via the language status button ({}) in VS Code's status bar:

I actually care about type checking as I try to write better code and want to learn more but have found that it's a bit distracting while coding getting your whole IDE in red especially when this is not your code (from libraries, documentation,team members,...), but didn't knew the position of this button nice tip will try to switch it off while coding and then switching it on for every last push although I prefer extensions just being there and I don't have to worry about them and it seem to only have this quick shortcut for basic and not other levels.

>Inlay hints are intentionally computed on our background thread for performance reasons, so I'm guessing that's why there's a brief delay before they appear. If you feel their behavior should be improved, please file a separate issue. Using a single issue to track multiple unrelated requests is awkward for us.

No worries it's probably not the most important thing for you guys rn, I was just asking as some other extensions had a little delay you have to stop typing before actualizing (to prevent to run on every char ig) and setting it to 0 made them wayyyy more snappy and I was just wondering if this was the same here and it's kinda logical being slower as you have to find the called function ig? Whatever this was just a quick extra question as it would improve a bit my ux
