### ISSUE TITLE
Pylance module is not accessed

### ISSUE THREAD

**Issue by UnknownFX02** [microsoft/pylance-release#553]
I am get some issue about pylance:

1. When i `from flask_restplus import fields` i get "fields is not accessed"
2. My pylance does not suggestions argument of function
3. I dont have  Words suggestions in python file

I was enable my .venv. Tks

**Comment by judej** [comment]
@UnknownFX02, thanks for the issue report. In order to address these issues individually, would you please create separate issues for each of the questions above. Also, if you would use the template and add sample code, we would be able to resolve your questions quicker.

Regarding the issues above:
1. Are you using `fields `some where in your code? If you are not, then the warning is expected
2. Could you please send more information on problem? Which function? Could you send a code snippet with expected and observed behaviors?
3. Again, if you could send a code sample, it would be easier to help.

thanks!

**Comment by UnknownFX02** [comment]
> @UnknownFX02, thanks for the issue report. In order to address these issues individually, would you please create separate issues for each of the questions above. Also, if you would use the template and add sample code, we would be able to resolve your questions quicker.
> 
> Regarding the issues above:
> 
>     1. Are you using `fields `some where in your code? If you are not, then the warning is expected
> 
>     2. Could you please send more information on problem? Which function? Could you send a code snippet with expected and observed behaviors?
> 
>     3. Again, if you could send a code sample, it would be easier to help.
> 
> 
> thanks!

So sorry about my shortcomings D.
I think all 3 questions relate to pylance
**My vscode(1.51.0-insider) use all default cofig just install pylance and python ( i was disable some other ), and was active .venv **

1&2&3. here my code

`from flask_restplus import fields, Namespace`
`api = Namespace[1]('api', description='apiv2')`
`user = api.model[2]('user', {`
    `'id': fileds.Integer[3](required[4]=True, description[5]='User id')`,
    `...`
`})`

Note: [num] are not suggestions ( include words ), code was run success, and i don't know pylance have this function


`

**Comment by judej** [comment]
There is a typo on that last line:
```
'id': fileds.Integer[3](required[4]=True, description[5]='User id')
```
I think you meant
```
fields.Integer()
```

**Comment by UnknownFX02** [comment]
> There is a typo on that last line:
> 
> ```
> 'id': fileds.Integer[3](required[4]=True, description[5]='User id')
> ```
> 
> I think you meant
> 
> ```
> fields.Integer()
> ```
> 
> Does that fix the problem?

Thank you for your time, but no
```'id': fileds.Integer[3](required[4]=True, description[5]='User id')```
`[3]` mean pylance not suggestion here and other point

**Comment by UnknownFX02** [comment]
I was find a problem here
```
from flask_restplus import fields, Namespace

api = Namespace('api', description[1]='apiv2')

fileds.Integer[3](required[4]=True, description[5]='User id') <== But here pylance can work out site of api.model

user = api.model[2]('user', {
'id': fileds.Integer[3](required[4]=True, description[5]='User id'), <== fileds.Integer here not accept by pylance
...
})
```

**Comment by jakebailey** [comment]
You have a typo "fileds" versus "fields", so the import is not being referenced.

**Comment by UnknownFX02** [comment]
> You have a typo "fileds" versus "fields", so the import is not being referenced.

oh sorry, but this typo is only in my post, i was write it again not copy and paste from my project

**Comment by jakebailey** [comment]
Can you take a screenshot of the code with the diagnostics shown?

**Comment by UnknownFX02** [comment]
Here is my issue
![image](https://user-images.githubusercontent.com/32718930/99347632-2093e400-28ca-11eb-887c-60afd3767a84.png)
pylance not work in this case

![image](https://user-images.githubusercontent.com/32718930/99347708-491bde00-28ca-11eb-8340-5464580c90d9.png)
pylance work but not right way

**Comment by cdewansh** [comment]
Do some python modules like os, webbrowser not work on Big Sur?? (I have tried changing the path. Some modules work while others don't.)
![image](https://user-images.githubusercontent.com/84150629/118262673-f1ef7280-b4d4-11eb-9cce-a50f4da6ad14.png)

**Comment by jakebailey** [comment]
I'm not sure what you mean, the above is showing you that the modules are unused, not that they won't work. If you use the module in your code, then the graying out will go away. This issue is about some different bug.

**Comment by cdewansh** [comment]
> I'm not sure what you mean, the above is showing you that the modules are unused, not that they won't work. If you use the module in your code, then the graying out will go away. This issue is about some different bug.

Thank you so much. This solved my issue.

**Comment by jakebailey** [comment]
In the above screenshots, I'm not seeing the "fields not accessed" message at all, nor is the text grayed out (which is what happens when that diagnostic is emitted). I'm not entirely certain Pylance is running in the most recent screenshot either; semantic highlighting appears to be off, but maybe that's an artifact of the theme you're using.

It seems like there's a second issue where `fields.' doesn't give any completions in that nested context; that could be a bug, but if I try to do it myself, it works fine:

![image](https://user-images.githubusercontent.com/5341706/131746845-59abef81-a044-4cc6-bdec-5a6dae72fbe9.png)

I'm going to close this, but if you can provide us with the trace Python Language Server logs and a reproduction repo, we can take a look.
