### ISSUE TITLE
Code if marked as unreachable. Can someone please explain why?

### ISSUE THREAD

**Issue by zeeshansayyed** [microsoft/pylance-release#554]
I have seen a few issues where a similar question was asked, but couldn't find an example like the one I am facing. I was perusing some code in an opensource project and lot of lines were marked as unreachable. Consider this file: https://github.com/yzhangcs/parser/blob/main/supar/parsers/parser.py#L75-L88

Here, the following lines are marked as unreachable: L75-L88, L109-L113 and L131-L140. I don't understand why this would be the case.

I would really appreciate if someone can point out what is going on. This code is fairly straightforward and looks like it shouldn't raise that flag.

Thanks

EDIT: I am using Pylance v2020.10.3

**Comment by erictraut** [comment]
This occurs because the code is calling a method (self._evaluate) and all three of these conditions exist:
1. The method has no return type annotation, which means that the code analyzer must infer the return type of the method based on the implementation
2. The implementation of that method raises an exception on all code paths
3. The method is not decorated with an @abc.abstractmethod, so there's no indication to the code analyzer that it is intended to be overridden in all cases

Fixing any one of these three conditions will address the problem. And all three of these are good ideas because they make the code more readable, robust, and self-documenting.

**Comment by zeeshansayyed** [comment]
Thanks for the quick reply. Appreciate it.
