### ISSUE TITLE
Pylance makes the syntax highlighting in my VSCode theme (Tokyo Night Storm) become unbalanced

### ISSUE THREAD

**Issue by LifeAdventurer** [microsoft/pylance-release#5570]
Original
![image](https://github.com/microsoft/pylance-release/assets/108756201/a2f5a437-7ba4-46cf-87a4-9c2c8e460cb6)

Pylance enabled
![image](https://github.com/microsoft/pylance-release/assets/108756201/369a5238-3e0a-4794-8a30-57908bb74cb3)

**Comment by debonte** [comment]
I'm unable to repro this behavior. The colors are likely changing due to semantic token data that Pylance is providing after analyzing your code.

Can you provide a complete example that repros this behavior as text (not an image)? And also run the `Developer: Inspect Editor Tokens and Scopes` command from the command palette, click on the tokens that you feel are not colored correctly, and send us screenshots of the info that it displays.

For example:
![image](https://github.com/microsoft/pylance-release/assets/12820898/9366b01e-bad1-4cc4-a63d-ddfb44f47935)

**Comment by debonte** [comment]
Thanks, can you also provide the source file that you used to reproduce this? As text?

**Comment by LifeAdventurer** [comment]
Sure, the code I referenced in the screenshot can be found [here](https://github.com/LifeAdventurer/Moonafly/blob/main/src/command/translate.py#L1C1-L34)

**Comment by KacieKK** [comment]
I can repro this  
![image](https://github.com/microsoft/pylance-release/assets/35987382/3435cf4e-0183-49d0-8f3b-cea7d97a25eb)

**Comment by debonte** [comment]
Pylance's behavior here is correct. You're seeing the colors that are defined by the theme. If you're unhappy with the colors, please file an issue on the theme at https://github.com/enkia/tokyo-night-vscode-theme/issues.

For example, on `HELP_FLAG` which is a constant, when semantic highlighting is off you'll see color `#ff9e64` as defined here in the theme:

```json
{
    "name": "Number, Boolean, Undefined, Null",
    "scope": [
        "variable.other.constant",
        "punctuation.definition.constant",
        "constant.language",
        "constant.numeric",
        "support.constant",
        "constant.other.caps" // Python global
    ],
    "settings": {
        "foreground": "#ff9e64"
    }
},
```

However, since Pylance provides semantic tokenization, if you have Pylance installed and semantic highlighting enabled, VS Code honors the theme's `semanticTokenColors` and you get a different color `#bb9af7` as defined here in the theme:

```json
"semanticTokenColors": {
    ...
    "variable.declaration": {
        "foreground": "#bb9af7"
    },
```

The theme currently does not provide a semantic token color for readonly variable declarations (constants), but it could by adding a value like the following:

```json
"semanticTokenColors": {
    ...
    "variable.declaration.readonly": {
        "foreground": "#ff9e64"
    }
```
