### ISSUE TITLE
The functionality of "Go to Definition" is missing

### ISSUE THREAD

**Issue by nixingyang** [microsoft/pylance-release#5594]
## Environment data

-   Language Server version: ms-python.python v2024.2.1, ms-python.debugpy v2024.2.0, ms-python.vscode-pylance v2024.2.3
-   OS and version: Arch Linux with the latest packages
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.12.2 installed using conda

## Code Snippet

```python
import torch

torch.nn.Conv2d()
```

## Repro Steps

1. Right-click on the function of interest or use CTRL+Click

## Expected behavior

There should be the `Go to Definition` option that allows one to inspect the implementation of that function.

## Actual behavior

There is no `Go to Definition` option.

## Screenshots

![Screenshot from 2024-03-07 12-47-49](https://github.com/microsoft/pylance-release/assets/15064790/f086c40f-a0aa-4892-b0de-5218211ced07)
![Screenshot from 2024-03-07 12-48-28](https://github.com/microsoft/pylance-release/assets/15064790/6f14cdcc-3ea8-4f87-8082-144fe923193e)

**Comment by debonte** [comment]
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

Are you using an official build of VS Code?

**Comment by nixingyang** [comment]
I followed the guide and set `python.analysis.logLevel` to `Trace`. For some reason, the log of `Python Language Server` is meaningless. I might have missed something.
![image](https://github.com/microsoft/pylance-release/assets/15064790/e5229124-9661-4d04-a6bb-19e44cb5acaa)

I am not using the official build of Visual Studio Code. I am using the `code` package provided in Arch Linux. The snippets [here](https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/tree/c0a47db7) show how the package is compiled.

@debonte Are you able to reproduce this issue in your environment? Which extension package implements the support of "Go to Definition" in Python?

**Comment by debonte** [comment]
> Which extension package implements the support of "Go to Definition" in Python?

Pylance by default. You can also configure the Python extension to use Jedi as the language server by setting `python.languageServer` to `Jedi`.

> For some reason, the log of Python Language Server is meaningless. I might have missed something.

Actually, that's what I expected to see. You're not getting go to definition support because Pylance is failing to start. And it's failing to start because it detected that it is being run in an unsupported environment. Pylance is only supported on official builds of VS Code. If Arch Linux is building VS Code itself, Pylance won't work there.

Instead of Pylance you could use Jedi (as described above) or the Pyright extension. If you choose Pyright, you  should set `python.languageServer` to `None` and uninstall/disable Pylance.

**Comment by nixingyang** [comment]
Thanks for your help.
I managed to solve this issue by replacing the `code` package with the `visual-studio-code-bin` package. The latter one is the proprietary Microsoft-branded release.

**Comment by beliaev-maksim** [comment]
same for me, used snapped version and did not work, switched to deb from the official site and F12 is there :)
