### ISSUE TITLE
Typed decorator will result in no docstring for method

### ISSUE THREAD

**Issue by Scrat94** [microsoft/pylance-release#5613]
## Environment data

-   Language Server version: v2024.2.3
-   OS and version: Windows 11/10
-   Python version: 3.12

## Code Snippet

Does not work
```python
def log(func: Callable) -> Any:
    """Wrapper function to log function calls and exceptions."""

    @functools.wraps(func)
    def wrapper(*args, **kwargs) -> Any:
        ....
    return wrapper

@log
def test():
    """Sample docstring"""
    return "Hello World"

# Hovering over test() does not show the docstring
test()
```

Works (look at the missing typing of the parameter and return:
```python
def log(func):
    """Wrapper function to log function calls and exceptions."""

    @functools.wraps(func)
    def wrapper(*args, **kwargs) -> Any:
        ....
    return wrapper

@log
def test():
    """Sample docstring"""
    return "Hello World"

# Hovering over test() shows the docstring
test()
```

## Repro Steps

1. Create a decorator method
2. Add typing for decorator method (e.g. Callable) and return type

## Expected behavior

The method where the decorator is used, should show the docstring when used

## Actual behavior

No docstring is shown for method which are using the decorator

**Comment by erictraut** [comment]
This is by design. In the "doesn't work" case, you have explicitly indicated that the return type of the decorator is `Any`. That means it obscures any type information (including associated doc strings) for the functions it is decorating. In your "works" case, pyright (the type checker upon which pylance is built) is inferring the type of the decorator's return type.

If you want to provide type annotations for your decorator function, the correct way to do so is:

```python
T = TypeVar("T", bound=Callable)
def log(func: T) -> T: ...
```

**Comment by Scrat94** [comment]
@erictraut thanks for the quick response. This works. Thank you very much.
