### ISSUE TITLE
PyLance intellisence doesn't show closure's docstring

### ISSUE THREAD

**Issue by wvolkov** [microsoft/pylance-release#5617]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

Language Server version: Pylance language server 2024.2.3
Python version: Python 3.10.13
WSL: Ubuntu 20.04
VS Code: 1.83.1
OS: Windows_NT x64 10.0.19045

## Code Snippet

```python
from typing import Callable

def outer_func(**kwargs) -> Callable[[str], int]:
    '''Outer constructor
       ## Args
       -- outer kwargs doc
    '''

    def inner_func(input: str) -> int:
        ''' Inner Function
            ## Args
            - input string of inner func'''
        input = kwargs.get('foo', 'bar')
        return 1 if input != 'bar' else 0

    return inner_func

just_outer = outer_func

inner_closure = outer_func(foo='bar')
```

## Repro Steps

PyLance doesn't show a doc string when hovering over a var resulted as initiated closure function, while it correctly defines the signature of closure's input/output args:

![20240310_130108](https://github.com/microsoft/pylance-release/assets/49549154/2e36194f-986d-4557-90e1-794d99950447)

## Expected behavior

It seems that it should have shown inner function docstring while hovering over `inner_closure` variable.

## Actual behavior

It doesn't show a doc string, while signature of inner function is correct at this variable:  [str] -> [int]

**Comment by debonte** [comment]
This is by design. `just_outer` is an alias of `outer_func` and therefore has the same docstring. However, `inner_closure` could be anything that `outer_func` is capable of returning. Pylance is only aware that `outer_func` returns a `Callable[[str], int]`. It doesn't track the possible values of that type that might be returned by the current implementation of `outer_func`. Since we see `inner_closure` as simply a `Callable[[str], int]`, there's no associated docstring.
