### ISSUE TITLE
list[MagicMock] is incompatible with function parameter type

### ISSUE THREAD

**Issue by fievelk** [microsoft/pylance-release#5633]
Hi everyone. While testing, I'm trying to mock the parameters of a method that uses type hints, but I'm getting an error.
Here's some code to reproduce:
```py
from typing import List
from unittest.mock import MagicMock

class MyObject:
    def some_expensive_method(self):
        # Do some expensive operation
        pass


def run_all(my_objects: List[MyObject]):
    return [obj.some_expensive_method() for obj in my_objects]


def test_run_all():
    object_mocks = [MagicMock(), MagicMock()]
    run_all(my_objects=object_mocks)  # <-- Here I get the error from pylance

    for obj_mock in object_mocks:
        obj_mock.some_expensive_method.assert_called_once()
```

In the `run_all(my_objects=object_mocks)` code I get this error from Pylance:
```
Argument of type "list[MagicMock]" cannot be assigned to parameter "my_objects" of type "List[MyObject]" in function "run_all"
  "list[MagicMock]" is incompatible with "List[MyObject]"
    Type parameter "_T@list" is invariant, but "MagicMock" is not the same as "MyObject"
    Consider switching from "list" to "Sequence" which is covariantPylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

I understand that a MagicMock is not a MyObject. However, that's what mocks are for: replacing other objects. So what would be the best way to mock objects when using python type hints?

**Comment by debonte** [comment]
`MagicMock` indirectly derives from `Any`. If `object_mocks` is annotated as `list[Any]`, the error goes away. 

@erictraut, should `list[SomethingDerivedFromAny]` behave like `list[Any]` in this scenario?

**Comment by debonte** [comment]
Ok, in that case, this scenario is similar to the `list[int | None]` scenario discussed [in the Pyright docs](https://microsoft.github.io/pyright/#/type-concepts?id=generic-types).

`object_mocks` is inferred as a `list[MagicMock]`, but `run_all` expects a `list[MyObject]`. So the diagnostic is warning you that by passing `object_mocks` to `run_all`, the list could be modified to include `MyObject` elements, which would be a violation of the `list[MagicMock]` type.

Here are two ways to eliminate this diagnostic:
1. Change the annotation for `my_objects` parameter of `run_all` from `list[MyObject]` to `Sequence[MyObject]` as suggested by the diagnostic text. This works because `Sequence` is immutable, so the type checker trusts that your `list[MagicMock]` won't be modified within `run_all`.
```python
def run_all(my_objects: Sequence[MyObject]):
```
2. Annotate `object_mocks` as `list[MyObject]`.
```python
object_mocks: list[MyObject] = [MagicMock(), MagicMock()]
```

**Comment by fievelk** [comment]
Thank you, this clarifies the issue 👍 :)
