### ISSUE TITLE
Pylance extension changes how newlines are formatted

### ISSUE THREAD

**Issue by sobolevn** [microsoft/pylance-release#5635]
Hi! 👋 

When I activate Python extensions in VSCode it stars to interferire with my code by adding extra spaces everytime when I press "enter" in a function signature.

Here's the demo, let's start with how it is now (with Python extension):

https://github.com/microsoft/pylance-release/assets/4660275/1c4d9452-f0eb-4f90-8ef1-612fcb4ee39e

Here's how it should be (without Python extension):

https://github.com/microsoft/pylance-release/assets/4660275/01a2f646-5b62-4077-8dfe-acf1bb192dc0

I've noticed it for like several months now, it used to work correctly before.
Is there anything I can help fixing? Or is there something to switch it off?

I really care about IDE not touching stuff that I write.

Thanks!

**Comment by debonte** [comment]
Thanks for the issue. You can disable Pylance's auto-indent feature by setting:

```json
    "[python]": {
        "editor.formatOnType": false
    },
```

There's open issue to add a more granular config setting: https://github.com/microsoft/pylance-release/issues/5592

**Comment by sobolevn** [comment]
It solves this case, but other newlines are now placed at the beginning of the file, not semantically as it used to be.

**Comment by debonte** [comment]
Can you provide code that repros the behavior that you're seeing?

**Comment by debonte** [comment]
Earlier you said:

> I really care about IDE not touching stuff that I write

Can you clarify what you meant by that?

My impression was that you were saying, "I don't want Pylance trying to figure out the correct indentation here." In fact, I had wondered if you meant, "I want zero indenting when I press Enter. I'll add all indenting manually." If that's the case you can achieve that with:

```json
"[python]": {
    "editor.formatOnType": false,
    "editor.autoIndent": "none"
}
```

Disabling `editor.formatOnType` turns off our auto-indent feature so you get the much simpler behavior that is baked into VS Code. It basically looks at the previous line and keeps that indent unless it sees particular keywords (`class`, `def`, etc) followed at some point by a colon (`:`), in which case the new line gets indented one more level.

Pylance's auto-indent feature is smarter than that. Neither one is configurable though. The goal is to make it easy for you to generate valid code and stay in the flow while typing. We're not a formatter. If you care about precise formatting rules, we assume that you'll run a formatter like black, autopep8, Ruff, etc.

We currently aim to follow PEP 8, and in your first scenario (Enter after `def __init__(`) it looks like we're doing the correct thing. PEP 8 actually [specifically calls out a scenario like this](https://peps.python.org/pep-0008/#indentation) and says that the indentation you're requesting is undesirable because the it makes the parameter list and the statements within the function indistinguishable:

```python
# Wrong:
#...

# Further indentation required as indentation is not distinguishable.
def long_function_name(
    var_one, var_two, var_three,
    var_four):
    print(var_one)
```

You could argue that we should follow black's indentation rules instead since PEP 8 is antiquated. But again we're not trying to be a formatter, and especially not a configurable formatter. There are awesome tools out there to do that already. That's not where we see Pylance providing value.

What are your thoughts on all this?

**Comment by charlierix** [comment]
That was driving me nuts

When pushing enter into a new indentation block, it was doing the standard 4 space tab, then one extra space

For example.  Pushing enter from the colon
```python
def test():
```

Put the curser 4+1 spaces
```python
def test():
     cursor_starts_here
    instead_of_here
```

Unchecking pylance's Auto Indent property fixed that extra space getting added

**Comment by debonte** [comment]
@charlierix, I'm unable to reproduce that behavior. Can you share your `settings.json` and your Pylance version?

**Comment by charlierix** [comment]
Pylance v2024.9.2

Computer with issue
[settings.json](https://github.com/user-attachments/files/17101187/settings.json)

It may be a combination of settings, I'm not seeing it on my newer computer (same version of pylance)
[settings.json](https://github.com/user-attachments/files/17101224/settings.json)

**Comment by debonte** [comment]
> I just rechecked that checkbox to verify time and it's not doing the extra space anymore

Hmm, ok. I wasn't able to repro the issue with your settings, for what that's worth.

Maybe you have another extension installed that is also doing "format on type" on new lines?

Did this just start happening recently? Did it start immediately after installing/upgrading Pylance?

If this starts happening again, please file a new issue.

**Comment by charlierix** [comment]
Sure, thanks

I don't remember there being an issue, but I do very little with python.  I've been doing more python on the newer computer, felt like making some scripts on the older computer a couple days ago and kept seeing that issue

I didn't pay attention to which extensions wanted updates, I just update whatever prompts for it.  I haven't installed any new extensions in quite a while

**Comment by debonte** [comment]
Thanks. Btw, the only scenario where I was able to repro this was if the file already had 5-space indents elsewhere. Pylance uses the editor indent settings for new files, but for existing files it uses the "predominant" indent style. So if you happened to have 5-space indents in one of your files that would explain it.

**Comment by Jongbin-kr** [comment]
I experienced the same issue with OP.
When I linebreak, the editor automatically puts 4+1 spaces.

And I fixed it by turning off `Auto Indent` option in Pylance extension.
I think there are some crash b/w Python extension and Pylance extension.

**Comment by debonte** [comment]
@Jongbin-kr can you share the Python file where you were seeing this and your `settings.json`?

**Comment by Jongbin-kr** [comment]
> @Jongbin-kr can you share the Python file where you were seeing this and your `settings.json`?

I caught the point of the issue and editted the comment.

The issue was not from Pylance, but other extentsion Python Indent.
After un-installing and refresh VSCode, the python indetation works correctly whether `Auto Indent` option is on or not

**Comment by LeventCelik** [comment]
Just wanted to confirm that I had the same issue. I use tabs for indentation, I would see the correct amount of tabs + 1 extra space.

Disabling [Python Indent](https://marketplace.visualstudio.com/items?itemName=KevinRose.vsc-python-indent) (an extension with 14.3M installs) fixed the issue.

**Comment by mkf62** [comment]
I am having this issue today after updating VSCode to the latest.  On pressing enter after `def func(x):` it indents with 4 spaces + 1 extra space. I do not have and have never had Python Indent installed. If I turn off auto-indent with Pylance, the issue goes away (it returns to indenting 4 spaces). Strange solution considering I've always had auto-indent turned on for and it never did this until today.

My new `settings.json` (it had nothing in it until I changed the setting):
```
{
    "python.analysis.autoIndent": false
}
```

My VSCode version: 1.101.2 (Universal)
My Pylance version: 2025.6.2

**Comment by debonte** [comment]
@mkf62, please open a new issue. The OP's issue was about our auto indent system not matching their preferred formatting style, whereas your issue is actually unexpected formatting.

So far I'm unable to reproduce the behavior that you are seeing. When filing the issue, please cover the following:
- Are you typing `def func(x):<enter>` in an otherwise empty file, or was there existing content in the file?
- Do you really have nothing in your `settings.json` files? Both user and workspace settings?
- Provide a list of extensions that you have installed.

**Comment by kaczmm** [comment]
I have the same issue, and I do not (and never had) "Python Indent" installed. In the meantime I have uninstalled Pylance to resolve the issue.
