### ISSUE TITLE
Pylance error in try/except block

### ISSUE THREAD

**Issue by fievelk** [microsoft/pylance-release#5671]
I'd like to ask a question (or clarification) that might be quite simple to answer. I have this code which is causing an error in Pylance:
```py
hostname = parse.urlparse("https://some-url.com").hostname
try:
    hostname = hostname.split(".")[0]  # <-- This line gives the error
except AttributeError as ex:
    hostname = "default"
```
The error is the following:
> "split" is not a known member of "None"Pylance[reportOptionalMemberAccess](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalMemberAccess)

I can understand that `hostname` can be `None`, so using `.split()` would fail and Pylance complains. However, I'm using the try/except block exactly to catch this kind of issue. If I substitute the try/except with an `if` check, the error disappears:
```py
hostname = parse.urlparse("https://some-url.com").hostname
if hostname:
    hostname = hostname.split(".")[0]  # <-- No error
else:
    hostname = "default"
```
- Is this the expected behaviour due to how static type checking works? Why is the `if` version accepted, while the `try/except` version is not?
- What's the recommended practice in this case? Should I ignore the warning, or should I refactor the code to use the `if` version? Is this somehow an opinionated decision from Pylance about not using try/except as a flow control strategy?

**Comment by erictraut** [comment]
This is how static typing works. Type checking is not disabled inside a `try` block, so type violations like this will still be reported.

The second example doesn't contain any type violations because you've guarded the use of `hostname` with an appropriate conditional check.

`try/except` statements are meant to be used for _exception handling_, not for normal code flow. If it's a condition that you expect, it is preferable to use an `if` statement to guard against the condition, as you're doing in your second code sample. So if you want your code to be more robust and readable _and_ work well with static type checking, you should always use `try/except` statements only for true exceptions, not for normal (expected) code flow.

**Comment by Yay295** [comment]
> `try/except` statements are meant to be used for _exception handling_, not for normal code flow. If it's a condition that you expect, it is preferable to use an `if` statement to guard against the condition, as you're doing in your second code sample. So if you want your code to be more robust and readable _and_ work well with static type checking, you should always use `try/except` statements only for true exceptions, not for normal (expected) code flow.

You are objectively wrong. https://docs.python.org/3/glossary.html#term-EAFP
