### ISSUE TITLE
highest level of strict static type checking is not strict enough

### ISSUE THREAD

**Issue by beauxq** [microsoft/pylance-release#569]
I set
`"python.analysis.typeCheckingMode": "strict"`
to the most strict setting.

That is how I would expect to enable this functionality. If there is some way to enable this, then consider this question instead of a feature request.

This code should not be ok in the most strict setting, nor in the 2nd most strict setting:
```python3
banana = 3
banana = "three"
```

The most strict setting should require that all identifiers have a type annotation.
```python3
banana = 3  # error here because no type annotation
banana = "three"
```

Another less strict setting should see that `banana` is `int` and should not allow the string assignment.
```python3
banana = 3
banana = "three"  # error here because banana is int
```

If you want to write this code without any errors:
```python3
from typing import Any
banana: Any = 3
banana = "three"
```
or better for this case:
```python3
from typing import Union
banana: Union[int, str] = 3
banana = "three"
```
(I also would like to have available a setting that disallows `Any`, so you have to specify all the possible types with `Union`.)

But that's 3 different strictness settings that pylance doesn't have available.
Right now I can't find any way to get pylance to see any problem with this code.
```python3
banana = 3
banana = "three"
```

**Comment by erictraut** [comment]
These cases should not generate an error because the type is known in all cases. The type can be deterministically and accurately inferred in all of your examples, and the type checker can validate that no type rules are being violated. 

Take the following example:

```python
banana = 3
banana += 1 # This is fine because banana is type `int` at this point
banana = "three"
banana += 1  # Generates an error because banana is type `str` at this point
```

Forcing a programmer to declare a type for every variable would be onerous and would do very little if anything to increase the correctness or robustness of the code.

If a type cannot be inferred (i.e. it's type is "Unknown"), you will receive an error in strict mode.

If you want to declare the type of a variable, the type checker will validate and enforce that type declaration.

```python
banana: int = 3
banana = "three" # Generates an error
```

**Comment by beauxq** [comment]
> Forcing a programmer to declare a type for every variable [...] would do very little if anything to increase the correctness or robustness of the code.

This sentence is false.

In reality this two lines of code wouldn't be right next to each other, so the programmer wouldn't even realize they're changing the type. And then someone else comes along to modify the code and can't even see which version of the variable they're dealing with.

**Comment by erictraut** [comment]
>And then someone else comes along to modify the code

Can you outline a concrete scenario where this would lead to a bug?

**Comment by beauxq** [comment]
People using pylance will write libraries that they distribute to people that are not using pylance.

```python3
class C:
    my_number = 1

    @staticmethod
    def get_int():

        # lots of code here that obfuscates things

        banana = 3

        # lots of code here that obfuscates things

        if C.my_number == 50:
            # someone else writes this section of code not realizing the name is already used
            banana = Fraction(5, 2)
            # use banana for other things
        
        # lots more code to obfuscate things here
        
        banana += 1  # the fact that pylance doesn't give me an error here makes me confident that banana is still int

        return banana
    
    @staticmethod
    def change_my_number():
        C.my_number += 1

```

Then we distribute this library to someone that isn't using pylance.
They might be able to use this function for a while, test it with their system, see that it works, put it in something critical, then one day it crashes because banana isn't an `int`.

This crash could have been avoided if pylance told the original developers that there was a problem with:
```python3
banana = 3
banana = Fraction(5, 2)
```

**Comment by erictraut** [comment]
If you're developing a library that is distributed to others, I highly recommend that you annotate return types of the functions and methods that comprise your library's public interface. In the example above, if you annotate `get_int` to return an `int`, then pyright will emit an error when you attempt to return a value that is not an `int`. There's no need to annotate all local variables to detect an error like this.

**Comment by beauxq** [comment]
So you're highly recommending something that pylance could provide a setting for, and doesn't.

**Comment by erictraut** [comment]
There are many coding practices I would recommend that are not (and should not be) enforced by pylance.

In this particular case, there's no way for pylance to know if a function is part of a library that is going to be distributed, nor is it possible for it to know that it's part of a library's public interface contract. Only the programmer knows that. If a programmer adds a return type annotation to a function, pylance will enforce it as long as type checking mode is not "off".

**Comment by beauxq** [comment]
I'm not talking about enforcing anything. I already pointed out I'm not recommending this for any default setting.

**Comment by beauxq** [comment]
I'm talking about the highest levels of strictness.

**Comment by erictraut** [comment]
Thanks for submitting the feature request. We can leave this issue open and see if others upvote it or provide additional feedback.

**Comment by beauxq** [comment]
Note that mypy with default settings reports a typing problem with this code:
```python3
banana = 3
banana = "three"
```

**Comment by erictraut** [comment]
Mypy's type inference uses different rules that pylance/pyright. In cases where a variable does not have a declared type, mypy infers the type based on the first assignment — that is, the assignment with the smallest line number in the file. Mypy's approach results in many false positive errors. Other type checkers (including pyre, pytype and pyright) don't use that approach for good reason. In particular, pyright infers a variable's type based on _all_ assignments of that variable. It unions all of the types of the assigned expressions. This approach creates way fewer false positives and is still perfectly type safe because of type narrowing. In your example above, the type checker knows that the type of `banana` is `Union[int, str]`, but the _narrowed_ type is `int` after the first assignment and `str` after the second assignment. For this reason, there's no benefit to adding explicit type annotations for most local variables.

If your request is specific to the public interface of a library, then I agree that there's need for additional strictness. A library author shouldn't rely on type inference for variable types and function return types because different type checkers implement type inference rules differently. The pyright command-line tool now offers an option `--verifytypes` that verifies whether all exported symbol from a library are fully typed. For more details about this feature, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md#verifying-type-completeness). If you are a library author, please give this a try and let us know if it meets your needs.

**Comment by beauxq** [comment]
> Mypy's approach results in many false positive errors.

The question of whether the approach results in any false positives is dependent on the amount of strictness desired.
This whole argument is completely irrelevant to a request for more strictness.
