### ISSUE TITLE
Pyright does not work with full sync textDocument/didChange

### ISSUE THREAD

**Issue by gpanago** [microsoft/pylance-release#5751]
I am using emacs lsp-mode. It contains a parameter that enforces sending full text updates instead of incremental, even when the server implements incremental updates. Other servers (ruff and clangd tested) work fine with that option, but pyright does not, and the content goes out of sync. Does pyright not support full text updates?

If I understand correctly, the LSP specification requires the server to support both types of updates. To give some insight as to why I need this: it is to space out requests to pyright. I would like to only send didChange updates to pyright every few seconds to speed up autocomplete, as lsp-mode does not currently support file-based cancellation, nor does it support spaced out incremental updates (but it does support spaced-out full updates).

**Comment by rchiodo** [comment]
Looking at our [source ](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/languageServerBase.ts#L662) I believe we specify only incremental in our capabilities. Meaning we don't support full sync. It was changed in this commit:
https://github.com/microsoft/pyright/commit/2d90df325fd9ffb6bd72e727ec59039b50cdf537

Since the server specifies this capability, I don't believe we can support both. We tell the client one or the other. And I believe that's how the LSP [spec defines](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#serverCapabilities) it.
