### ISSUE TITLE
Extra blank lines appear when I rename symbols

### ISSUE THREAD

**Issue by HwangWentian** [microsoft/pylance-release#5756]
Type: <b>Bug</b>

As the title suggests.
Man, what can I say?
This question has been bothering me for long.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by debonte** [comment]
> I confirmed that `python.languageServer` is set to `Default`.

@HwangWentian, can you also check if you have the Pylance extension installed and enabled? Default means that Pylance will be used, but only if it is installed and enabled. Otherwise Jedi is used.

When we've seen this sort of behavior in the past it was due to either:

1. Jedi was being used as the language server instead of Pylance. There's a Jedi bug that can cause extra lines to be inserted -- https://github.com/pappasam/jedi-language-server/issues/159
2. Pylance was the language server, but there was another Python-related extension installed that was also handling the rename request -- see https://github.com/microsoft/pylance-release/issues/2367#issuecomment-1069406952

So if you have Pylance installed, can you please try disabling all of your extensions except Python and Pylance and see if the issue still happens?

**Comment by HwangWentian** [comment]
@debonte , I have not installed Pylance. But the problem was fixed when I installed Pylance and set it to languageServer. Thanks for the tip.
