### ISSUE TITLE
Unable to detect the output type of the function

### ISSUE THREAD

**Issue by parsasabbar** [microsoft/pylance-release#5760]
Imagine this part of code:
```
def method(num: int) -> str:
    return ""

result = method(12)
```

As you know, the **result** type is string:
![Screenshot from 2024-04-13 18-04-16](https://github.com/microsoft/pylance-release/assets/62116286/f38f658a-aa5f-447e-9614-73e897a9d9f8)

But when I put the function in a class, the Pylance can not recognize the output type of the function!
![Screenshot from 2024-04-13 18-04-40](https://github.com/microsoft/pylance-release/assets/62116286/94126dec-afa4-4e66-81df-504e5626b030)

I tried this case in Pycharm and there was no problem

**Comment by erictraut** [comment]
This is because your code has a bug. You've defined an instance method here (as opposed to a static method). The first parameter of an instance method must accept an implied "self" argument. You've omitted the "self" parameter, so your code will not run without crashing.

The fix is to simply add a "self" parameter as follows:

```python
class MyClass:
    def method(self, num: int) -> str:
        return ""

result = MyClass().method(12)
```

Alternatively, if your intent is for the method to be static, you can decorate it with `@staticmethod`.

```python
class MyClass:
    @staticmethod
    def method(num: int) -> str:
        return ""

result = MyClass().method(12)
```

If you enable basic type checking, pylance will tell you about this type of bug (and more).
