### ISSUE TITLE
reportArgumentType error for matplotlib.cm.ScalarMappable.to_rgba

### ISSUE THREAD

**Issue by HoseynAAmiri** [microsoft/pylance-release#5769]
Hello,

I can plot my graphs properly but I don't know why I am getting a type error:
plt.plot(x, y, color=sm.to_rgba(t1d))

Argument of type "float" cannot be assigned to parameter "x" of type "ndarray[Unknown, Unknown]" in function "to_rgba"
  "float" is incompatible with "ndarray[Unknown, Unknown]"Pylance[reportArgumentType]
(variable) t1d: float

**Comment by HoseynAAmiri** [comment]
So I noticed that it will be fixed if I use this:
T1_D = [1.0, 2, 3]
for t1d in T1_D:
    plt.plot(x, y, color=sm.to_rgba(t1d)

instead of T1_D = [1, 2, 3] or [1.0, 2.0, 3.0], which seems weird to me..

**Comment by debonte** [comment]
Thanks for your issue.

I pieced together the following repro based on your comments. I'm assuming that you are using a recent matplotlib build, or at least 3.8.0. Please try to provide a complete code sample with imports and package versions when filing future issues. That makes it much easier for us to reproduce and investigate what you're seeing.

```python
import matplotlib.pyplot as plt
import matplotlib.cm as cm

x = y = True
sm = cm.ScalarMappable()

T1_D = [1, 2, 3]
for t1d in T1_D:
    plt.plot(x, y, color=sm.to_rgba(t1d)) # Argument of type "int" cannot be assigned to parameter "x" of type "ndarray[Unknown, Unknown]" in function "to_rgba"
#  "int" is incompatible with "ndarray[Unknown, Unknown]"


T1_Db = [1.0, 2, 3]
for t1d in T1_Db:
    plt.plot(x, y, color=sm.to_rgba(t1d)) # No diagnostic
```

Pylance is behaving correctly here.

The difference in behavior happens because `T1_D` contains only ints and therefore its type is inferred as `list[int]` but `T1_Db` contains both ints and floats so it's type is inferred as `list[Unknown]`. The Pyright docs explain [our rules for inferring the types of list expressions](https://microsoft.github.io/pyright/#/type-inference?id=list-expressions).

So in the second loop, `t1d` is of type `Unknown` which is equivalent to `Any`. The presence of `Any` effectively blinds the type checker, so no diagnostic is reported.

If you explicitly annotate `T1_Db` as `list[int | float]`, you'll see the same diagnostic on the second call to `to_rgba`

```python
T1_Db: list[int | float] = [1.0, 2, 3]
```

If you Go to Declaration on `to_rgba` you'll see that the `x` parameter in matplotlib's stubs is annotated as `np.ndarray`. So Pylance is correct to flag your attempt to pass an `int` or `float` for `x` as an error.

If you believe that `x` should accept types other than `np.ndarray`, please file an issue on matplotlib at https://github.com/matplotlib/matplotlib/issues.
