### ISSUE TITLE
Rename of a derived method renames the base method even if not an override

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5806]
Have code like so:

```python
class Base:
    def method(self):
        pass

class Derived(Base):
    def method(self):
        return super().method()
```

Rename the derived method. 

## Expected result:
It only renames the derived method.

## Actual result:
It renames Base.method as well. 

This seems off to me. Shouldn't it only rename the base method if the derived method is marked with `override`?

**Comment by heejaechang** [comment]
that's not how override work in general? `@override` is from `typing` module that doesn't affect runtime. it helps static analysis tool the method is actually overriding a method in its super type?

at runtime, things should work same with or without `override` decorator.

now, if you change method at certain type only but not its parents that it is overriding, then any existing call now has a chance to have semantically different behavior.

```python
class A:
    def method(self):
        pass

class B(A):
    def method(self):
        pass

def foo() -> A:
    return B()

a = foo()

a.method()
```
now, if you only rename `method` in `B` but not in `A`, `a.method()` will call `A.method()` instead of `B.method()` . it is easy to spot in this example since everything is in same place, but if `a` is passed around a few times, impossible to find out code's runtime behavior just changed.

that said, it might be good idea to show diagnostics or code action to add `override` if it is missing?

**Comment by heejaechang** [comment]
and it looks like `override` is added with `3.12`?

**Comment by rchiodo** [comment]
Moving to triage to discuss. I'd be okay with just closing this given Heejae's explanation of override.
