### ISSUE TITLE
Pylance hangs after using "Go to Definition" on PySide6 objects

### ISSUE THREAD

**Issue by myuanz** [microsoft/pylance-release#5847]
## Environment data

-   Language Server version: Pylance language server 2024.4.106 (pyright version 1.1.360, commit 4bc8428d)
-   OS and version: Windows 10 20H2 19045.4291
-   Python version: Python 3.11.3
-   PySide version: 6.7.0

## Code Snippet

```python
from PySide6.QtCore import Signal, QObject


class MyObject(QObject):
    t1 = Signal()

o = MyObject()

```

## Repro Steps

1. Open a Python project in VSCode that uses the PySide6 library
2. Hover over QObject or any other PySide6 class/function and press F12 to go to its definition
3. Try to go to the definition of another class/function by pressing F12 again

https://github.com/myuanz/pylance-pyside-hang/assets/25359546/578d6f25-0d52-49b6-a3ce-ee4e4b658537

## Expected behavior

F12 should smoothly switch between different class/function definitions without freezing.

## Actual behavior

1. After using F12 to go to a definition in PySide6 for the first time, subsequent uses of F12 cause Pylance to hang and become unresponsive for dozens of seconds. This also affects other VSCode functionalities such as creating new files.
2. When working in an SSH Remote environment, this issue also cause the SSH connection to drop. Remote system is `Ubuntu 23.10`, other softwares version is same to this issue. 

## Logs

log link: https://github.com/myuanz/pylance-pyside-hang/blob/master/test2.log

## Demo Repo

https://github.com/myuanz/pylance-pyside-hang

This issue has been present for about two or three months. I kept hoping that it would disappear after an update, which is why I didn't come to submit the issue.

**Comment by heejaechang** [comment]
it looks like it is happening because someone server got shutdown and restart and command sent during that time is not served.

your log contains multiple these entries.

```
2024-05-05 18:30:53.223 [info] (41020) WorkspaceFactory 0 clear
2024-05-05 18:30:53.261 [info] [Info  - 18:30:53] Server process exited successfully
```

something is sending `Shutdown` request to us.

we probably need live repro to figure this out. 

https://github.com/myuanz/pylance-pyside-hang

is this only thing we need? or there are other extensions or packages we need to install as well? I am asking since it doesn't repro for me. and I can see from log bunch of other packages installed.
