### ISSUE TITLE
"requests" is not accessed Pylance. I am getting this problem when trying to import requests,it is already installed in the system but the word get coloured to green instead of white and when l click on it that is the info it shows

### ISSUE THREAD

**Issue by SreyaChivukula** [microsoft/pylance-release#5859]

**Comment by heejaechang** [comment]
can you include some screenshot for us to understand the issue?

**Comment by KacieKK** [comment]
Thanks for reporting, to help us investigate, Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by Drjacky** [comment]
<img width="710" alt="Image" src="https://github.com/user-attachments/assets/3afa7e3f-cdde-4684-b966-bc61049cc547" />

```bash
➜  ~ pip install requests

Requirement already satisfied: requests in /opt/homebrew/lib/python3.13/site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.13/site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.13/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.13/site-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.13/site-packages (from requests) (2025.1.31)
```

**Comment by rchiodo** [comment]
@Drjacky we'd need to see your output log as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

The most common cause of your problem is you need to pick the python interpreter in VS Code. The interpreter you're using in your terminal may not match the default being used by VS code. 

This spot here:

![Image](https://github.com/user-attachments/assets/5b42a873-bd39-4a56-ba9e-10641658f395)
