### ISSUE TITLE
`"python.analysis.autoImportCompletions": false` not working.

### ISSUE THREAD

**Issue by ivanlen** [microsoft/pylance-release#5907]
- VS code: Version: 1.89.1 Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
-  Language Server version: Pylance async client (2024.5.1) started with python extension (2024.6.0)
-  OS and version: MacOs 14.4.1 (23E224)
-  Python version (& distribution if applicable, e.g. Anaconda): 3.11.5 anaconda

I have 
`"python.analysis.autoImportCompletions": false` in my settings and still I got auto imports

For example
1. I create a new file
2. I type sin
3. I press tab
the output is the following:

```
from math import sin


sin
```
I would expect that auto import completition works only for imported packages and does not auto import packages.

How can I disable this behaviour?

**Comment by heejaechang** [comment]
I can't repro it. 

can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs) so we can confirm that you do have the setting set to `false`?

you might have other settings that re-enable it since settings in `vscode` is hierarchical.
