### ISSUE TITLE
Pylance is analyzing something forever (profile included)

### ISSUE THREAD

**Issue by ibobak** [microsoft/pylance-release#5934]
Type: <b>Bug</b>

Attached is the profiling of pylance:
[profiling.zip](https://github.com/microsoft/pylance-release/files/15475829/profiling.zip)

Steps which I did:

![image](https://github.com/microsoft/pylance-release/assets/8807043/9e92534d-f15e-45b8-8059-622a215d42fb)
![image](https://github.com/microsoft/pylance-release/assets/8807043/fa1d3d9e-343d-4730-91dd-05d853934a4e)

Extension version: 2024.5.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 1197)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|251.76GB (229.55GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
a69g1124:31058053
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by heejaechang** [comment]
if this issue is reproducible, can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs) as well?

so, according to the profile info, completion is cancelled properly

![image](https://github.com/microsoft/pylance-release/assets/1333179/b919ab77-e3a3-4892-bab7-f01d059adfad)

I dont see `completion + intellicode` taking forever.

but `checker` (getting errors) is busy running in `BG`

![image](https://github.com/microsoft/pylance-release/assets/1333179/85e0c6f7-7687-41ca-a972-4f7a262d6464)

providing the log as the instruction says will let us to find out what files/settings are causing perf issue. if we can narrow it down to a file, we might be able to narrow it down to a symbol.

**Comment by bschnurr** [comment]
Can you provide a code sample and package versions? that might help too.

**Comment by ibobak** [comment]
I need some time to catch this situation again.   It doesn't reproduce each day, but once per week - for sure. Please, don't close the issue.  As soon as I reproduce, I will provide all the details.

**Comment by ibobak** [comment]
Let us close for now.  In the new version I cannot reproduce it.   As soon as I reproduce, I will report again, with correct logs following the troubleshooting guide.

**Comment by heejaechang** [comment]
sounds like our fix in the latest release fixed the issue.
