### ISSUE TITLE
python autocompletion doesn't change on __dir__ overwrite

### ISSUE THREAD

**Issue by Koncopd** [microsoft/pylance-release#5974]
Is it possible to change autocompletion on vs code jupyter for a python class.
For example this works in jupyter
![image](https://github.com/microsoft/vscode-jupyter/assets/3065736/7a0acabf-d216-4074-a28b-faae74a46dfd)
As you see changing `__dir__` of the metaclass changes the autocompletion (`.instance_method` is not shown).

However, this doesn't work on vs-code jupyter
![image](https://github.com/microsoft/vscode-jupyter/assets/3065736/7431b6c9-f61e-4241-b3f2-e50139c47e38)
`.instance_method` is still shown.

**Comment by rchiodo** [comment]
Thanks for the issue. I believe this is by design. 

Pylance (the language server for Python code in VS code) is a static analyzer. Meaning Pylance doesn't actually run your Python code to analyze it.

Changing the `__dir__` method to forward to the Meta class isn't something that Pylance can figure out. It's dynamic behavior.

**Comment by falexwolf** [comment]
Makes sense!

The bigger issue, though, is that instance methods should **not** appear in the class namespace because they are not callable for the class.

This information is statically available.

**Comment by erictraut** [comment]
Instance methods are callable from the class if you provide the class instance as an explicit argument for the `self` parameter.

```python
u = UseMeta()
UseMeta.instance_method(u)
```

**Comment by falexwolf** [comment]
It's _possible_ (apologies for being imprecise), but I don't think any developer uses it. In your example, the idiomatic use is `u.instance_method()`.

When I auto-complete on the class `UseMeta` (1), I'd love to auto-complete class methods, when I auto-complete on the instance, I'd love to auto-complete on the instance methods (2).

(2) is _already observed_ by pylance when constructing class methods via `metaclass` rather than the `@classmethod` decorator.

(1) is, I'd say, a question of developer experience. If developers who'd like to use `Class.instance_method(instance)` exist, they'd be unhappy. All other developers will be happier because they get a more targeted auto-complete experience.

This is in particular relevant when working with ORMs , which map on static SQL tables. Hence, the static namespace is much more important than in conventional OOP where class methods are typically only used as alternative constructors.
