### ISSUE TITLE
"Find All References" does not show results in notebook files unless the notebook is explicitly opened 

### ISSUE THREAD

**Issue by epicwhale** [microsoft/pylance-release#6022]
In a normal .py file when I right click a function declaration to use the "Find All References" feature, I expect it to show me all references across the entire project/workspace. But what I noticed is it that **the results exclude my notebooks (.ipynb files)**. But if I my notebook is open in a tab, then it shows it as a result. Is this working as intended?

## Environment data

-   VS Code version: Version: 1.88.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2024.3.2024032701 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v2024.3.10871011 (pre-release)
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Show references across all files in project, including notebook files

## Actual behaviour

Always excludes notebook files unless open.

## Steps to reproduce:

1) "Find all references" for a function (WITHOUT any notebook files are open in tabs)
<img width="304" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/670655/9e76909c-2c35-4d1e-8503-1f4ad2fc3d51">

1 result in 1 file
<img width="185" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/670655/8abd9a32-d815-430e-9bfd-946a0e88ee46">

2) Now, if I open a notebook using that same function, and run the same Find all references, as you can see here, it shows 2 results.

<img width="239" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/670655/a1667043-0644-44e5-bac4-e31f95102397">

**Comment by rchiodo** [comment]
Thanks for the issue. This is known limitation and is discussed more in this item here:
https://github.com/microsoft/pylance-release/issues/5175

The root cause is we can't _guess_ what the URI of a notebook cell is going to be as VS code generates that ID at runtime. So although we could look on disk for notebook references, we can't generate the correct URI so that when VS code opens the notebook it matches what we found. 

The current thinking is we have to open all of the notebooks in memory inside of VS code in order to return references to them, but we haven't tried that tactic yet.
