### ISSUE TITLE
Type hints for `**kwargs: Unpack[T]` not working correctly when using `TypeVar`

### ISSUE THREAD

**Issue by el1s7** [microsoft/pylance-release#6110]
Current behaviour:
![image](https://github.com/microsoft/pylance-release/assets/53352199/6000fa58-69cc-4c8a-afb7-e837f60783f2)

I expected it to work like this:
![image](https://github.com/microsoft/pylance-release/assets/53352199/7600d376-0cc4-4ff1-97e1-ed9d783ef9d9)

**Comment by erictraut** [comment]
The typing spec allows you to use an unpack operator with `**kwargs` only if the type argument is a TypedDict class. A type variable (like you've attempted in your code) is not permitted. For details, refer to [this section of the typing spec](https://typing.readthedocs.io/en/latest/spec/callables.html#unpack-for-keyword-arguments).

If you enable type checking errors, pyright (the type checker upon which pylance is based) will report this illegal usage:

![image](https://github.com/microsoft/pylance-release/assets/7040122/3cdac52d-b081-4905-879c-48736d0c1af0)

If you want to use an unpacked TypedDict in your `__init__` signature, you'll need to write the `__init__` method directly in each child class.

```python
from typing import TypeVar, TypedDict, Unpack

T = TypeVar("T")

class Parent:
    def __init__(self, *args, **kwargs) -> None:
        pass

class ExampleTypes(TypedDict):
    id: int
    email: str

class Child(Parent):
    def __init__(self, *args, **kwargs: Unpack[ExampleTypes]) -> None:
        super().__init__(args, kwargs)
```

Pyright is a standard-compliant type checker and it follows the typing specification. If you would like to suggest changes or additions to the typing spec, you can follow the process outlined [here](https://github.com/python/typing-council#decisions). The process would start with a post to the [Python typing forum](https://discuss.python.org/c/typing/32).

For future questions or bug reports, it would be appreciated if you'd provide the code text in place of (or in addition to) screen shots. This makes it easier to repro the issue.

**Comment by el1s7** [comment]
Thanks for the quick response @erictraut! I wasn't getting that error.

I understand that only `TypeDict` is allowed, but I don't see why `TypeVar` shouldn't be allowed, since `TypeVar` is a method for referring/linking to types.

Isn't this a problem of the type checker, which it's not correctly detecting that the `TypeVar` is actually a `TypeDict` in this case?

**Comment by erictraut** [comment]
No, that's not how TypeVars work. The class `Parent` must type check independent of how it is specialized. Normally, you'd be able to specify an "upper bound" constraint on the TypeVar (e.g. `T = TypeVar("T", bound=int)`), but you can't do this with `TypedDict` because `TypedDict` isn't a valid type and cannot be used in a type expression. It's a special form used to define a structural type. It's similar to the `Protocol` special form, which is also illegal to use in a type expression.

Even if it were possible to specify that a type variable `T` must be a `TypedDict`, there would still be problems if the typing spec were to allow `**kwargs: Unpack[T]`. It would work in cases where `T` was explicitly specialized, as in your example. But it wouldn't work in cases where `T` needed to be solved by a constraint solver when calling a function that uses this construct. Consider the following:

```python
def func[T](**kwargs: Unpack[T]) -> T:
    ...

func(a=1, b="hi")
```

There's no way for a type checker to "solve for" `T` in this case. For this reason, the authors of [PEP 692](https://peps.python.org/pep-0692/) (which introduced unpacking for TypedDicts) made it illegal to use a TypeVar in this case. When we expand the type system to add new features, we need to make sure that new capabilities compose well with all existing capabilities. That sometimes places limits on what the new capabilities can do, as in this case.
