### ISSUE TITLE
simultaneous view of incoming and outgoing calls

### ISSUE THREAD

**Issue by Elia-Sh** [microsoft/pylance-release#613]
Hi falks, 

You are awesome!
I was wondering about the python call hierarchy feature and when it would land in vs code,
after digging into documentation and publications -
https://code.visualstudio.com/updates/v1_33#_call-hierarchy
and https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/

I'm able to utilize in the call hierarchy for python - incoming and outgoing calls,
cool, thank you for this nice addition to vscode capabilities. 

Maybe it's possible to setup the view of call hierarchy in a manner that the user will be able to see both incoming and outgoing calls **simultaneously**?
For example split the view/panel into two sections: incoming and outgoing. 
Thank you very much

Elia.

versions details - 
```
VS Code Version: 1.49.2
ms-python.python@2020.11.358366026
ms-python.vscode-pylance@2020.11.1
```

**Comment by jakebailey** [comment]
This is entirely on VS Code to implement; we'll respond to any request given to us by the editor and there's nothing stopping is from answering both. It's just that VS Code's UI is written in a specific way where it's one panel. You'd need to suggest this change on their repo.

Unfortunately, we don't have the permission to transfer the issue there, but opening a new feature request there (or maybe finding an existing one) would be the best idea anyway because their templates ask for different information than ours.
