### ISSUE TITLE
Code is unreachable error

### ISSUE THREAD

**Issue by joshdavham** [microsoft/pylance-release#6131]
## Environment data

-   Language Server version: v2024.7.1
-   OS and version: macOS 14.5
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.4

## Code Snippet

```python
from datetime import datetime

def my_function(my_datetime: datetime = None):

    if my_datetime is None:
        
        # according to Pylance, the below code is unreachable
        return 'my_datetime is none'
    
    return 'my_datetime is not none'

# a simple invocation demonstrates the code is actually reachable
my_function()
"""
> my_datetime is none
"""
```

## Repro Steps

Copy the above code snippet into VSCode and hover your cursor above the first return statement to see the Pylance message that the return message is unreachable.

## Expected behavior

There should be no message from Pylance that the return statement is unreachable.

## Actual behavior

There is a message from Pylance stating incorrectly that the return statement is unreachable.

## Logs

Too lazy to get logs :D

**Comment by debonte** [comment]
Pylance is behaving correctly here. `my_datetime` is annotated as type `datetime` and therefore the type checker's understanding is that it can never be `None`. From a type checking perspective the code within the `if my_datetime is None` block is unreachable.

If you enable type checking by setting `"python.analysis.typeCheckingMode"` to something other than `"off"` (ex. `"basic"`), you'll see a diagnostic error on your attempt to set the default value of `my_datetime` to `None`, because `None` is not compatible with the annotated type of the parameter (`datetime`).

![image](https://github.com/user-attachments/assets/21303f90-4b20-480b-b18b-ebd2573d4c2e)

If you change the type annotation of `my_datetime` to `datetime | None`, Pylance will behave as you expected:

![image](https://github.com/user-attachments/assets/7de8c0af-afae-400e-9fa9-93dccccc0d56)

**Comment by joshdavham** [comment]
Ah I see! Thanks, I feel like I learned something 👌
