### ISSUE TITLE
Pylance Infinite "Files to Analyze" Slowing Other Features like Quick Fix - VSCode

### ISSUE THREAD

**Issue by AetherBreaker** [microsoft/pylance-release#6207]
## Environment data

-   Pylance version: v2024.7.1
-   OS and version: Microsoft Windows 11 Pro 10.0.22631 Build 22631
-   Python version: 3.12.4

## Explanation

Ever since my Pylance extension updated in VSCode on 7/7/24, across multiple different repositories, I've been getting an infinite "Files to Analyze" notifier on the bottom of my screen. It usually starts with around ~3000 files, and after a few minutes sitting drops to around ~2500 and remains there indefinitely.

This has been causing various other Pylance features to be non-functional, such as quick fixes, and I haven't been able to make heads or tails of a cause of this issue from my language server logs.

This occurs even without any files actually open, simply loading into a workspace results in this.

## Logs

Log file was too big to paste here, so I've provided it as a text file.

[Language Server Log.txt](https://github.com/user-attachments/files/16417969/Language.Server.Log.txt)

**Comment by heejaechang** [comment]
I think your workspace setup is broken. can I see your vscode `settings.json` file?

also, take a look at this on how to set up workspace - https://github.com/microsoft/pylance-release/wiki/Opening-Large-Workspaces-in-VS-Code#manually-configure-your-workspace

**Comment by AetherBreaker** [comment]
[settings.json](https://github.com/user-attachments/files/16429445/settings.json)
I know at one point I enabled the indexing of third party libraries, but I don't recall ever turning off any other workspace related features. And I had enabled that feature _months_ ago, and this issue didn't pop up until two weeks ago...

**Comment by AetherBreaker** [comment]
My workspaces usually aren't very big, maybe even three files at most (lots of smaller projects). I often swap between type checking modes based on the size of the project and generally keep most of my settings in a "one size fits all" setup. 

As for the exclude setting, should I just remove that line from my settings file to let it go back to default? I have no idea how it got changed since I never bothered to manually exclude anything from Pylance analysis.

**Comment by heejaechang** [comment]
you can remove the `exclude` so you use our `auto setup logic` or you can put all folders you want to exclude in `exclude` such as `.git`, `venv` and etc. you just can't mix those. you need to choose one to use. see the [doc](https://github.com/microsoft/pylance-release/wiki/Opening-Large-Workspaces-in-VS-Code#manually-configure-your-workspace)

> My workspaces usually aren't very big, maybe even three files at most (lots of smaller projects). I often swap between type checking modes based on the size of the project and generally keep most of my settings in a "one size fits all" setup.

If you're aware of what you're doing and accept the performance cost, using `diagnosticMode: workspace` should be fine. This mode causes `Pylance` to reanalyze all files that are transitively related to the file you've modified. Many people get confused when, let's say, 100 files are reanalyzed after changing just one file. This happens because those 100 files have direct or indirect dependencies on the changed file. As long as you're aware of this and are willing to accept the associated cost, it should be fine.

**Comment by AetherBreaker** [comment]
Okay yep. That change fixed the problem. Cheers!
