### ISSUE TITLE
Error when there is a derived class extending "cls" in a classmethod with return type "Self'.

### ISSUE THREAD

**Issue by abforce** [microsoft/pylance-release#6216]
<h3> Environment data </h3>

-   Language Server version: 2024.7.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: standard

<h3> Code Snippet </h3>
In the following code, Pylance generates an error.

```python
from typing import Self

class Foo:
    @classmethod
    def create(cls) -> Self:
        class FooImpl(cls):
            pass

        return FooImpl()
#              ~~~~~~~~~ <- red line here
```

Error:

> Expression of type "FooImpl" is incompatible with return type "Self@Foo"
  Type "FooImpl" is incompatible with type "Self@Foo"Pylance([reportReturnType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportReturnType))

**Comment by erictraut** [comment]
This error is correct, so this isn't a bug. A value of type `FooImpl` isn't compatible with `Self`. For details, refer to section about [Self](https://typing.readthedocs.io/en/latest/spec/generics.html#self) in the Python typing spec.

To eliminate this type error, you need to change the return type annotation from `Self` to `"Foo"`. Note the quotes here, which are required because this is a forward reference.
