### ISSUE TITLE
Pylance not working with pixi editable packages

### ISSUE THREAD

**Issue by clement-chaneching** [microsoft/pylance-release#6218]
## Environment data

-   Pylance version: 2024.7.1
-   OS and version: WSL2 linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.14

## Code Snippet

A reproducible example and description is done here:
https://github.com/clement-chaneching/pixi-pylance-test

It s a minimal example with 2 packages, 1 depending on the other on pixi as editable.

## Repro Steps

1. Create 2 packages as above with pixi and hatch/setuptools build, with one depending on the other as **editable**
2. Navigating from package 1 to package 2 with pylance doesnt work.
![image](https://github.com/user-attachments/assets/00d9a05a-1698-48aa-be7d-34857c392b81)

## Expected behavior
Having pylance to work with pixi editable paths.

## Actual behavior
- Currently it works fine without "editable".
- Going into pixi shell and manually running `pip install -e . --config-settings editable_mode=compat` also doesnt help. 
- This also has also been raised in [pixi repo](https://github.com/prefix-dev/pixi/issues/1633)
- I tried using both hatch and setuptools and doesnt make any difference.

## Logs

Happy to get any help or redirection on this topic.

Edit : @baszalmstra, Thanks for your PR on [adding pixi on vscode python](https://github.com/microsoft/vscode-python/issues/22978). Is this something you could have a look on?

**Comment by debonte** [comment]
This is working for me. Do you have the Pixi environment selected within VS Code?

![image](https://github.com/user-attachments/assets/f7dc4ab3-dc7e-42c9-829d-4d2e1dd74a66)

Btw, when I first tried this I couldn't get Pixi support to work within vscode-python. The Pixi environment was not shown in the environment selector list. I think this is because I was in an experiment that changed my VS Code to use https://github.com/microsoft/python-environment-tools (which doesn't have Pixi support) rather than the environment locators in vscode-python. If you're not seeing the Pixi environment in the list of options, try setting the following VS Code setting and see if that helps:

```json
    "python.locator": "js"
```

**Comment by clement-chaneching** [comment]
Hello,

Indeed, it looks like it works for me now as well!
Not sure what was happening last friday...

**Comment by oliver-batchelor** [comment]
I'm just getting into pixi now and having the same problem, I used to have to install my ediable packages with "editable_mode=compat" to make this work. 

I have the pixi environment selected, all seems well but the local packages aren't recognised like before?

**Comment by debonte** [comment]
> I used to have to install my ediable packages with "editable_mode=compat" to make this work.

Are you saying that you're not using compat mode anymore?

**Comment by oliver-batchelor** [comment]
@debonte Hi thanks for reply. 

Through pixi I'm not sure how to install with compat mode. Though I discovered I can enter the shell, then re-install with compat mode in pip as a workaround, and that works as usual.
