### ISSUE TITLE
BUG: `Code is unreachable` false positive

### ISSUE THREAD

**Issue by lucascolley** [microsoft/pylance-release#6220]
## Environment data

-   Pylance version: 2024.7.1
-   OS and version: Ubuntu 22.04.4
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.12.4 from conda-forge

## Code Snippet

```python
def get_array_special_func(f_name, xp, n_array_args):
    spx = scipy_namespace_for(xp)
    f = None
    if is_numpy(xp):
        f = getattr(_ufuncs, f_name, None)
    elif spx is not None:
        f = getattr(spx.special, f_name, None)

    if f is not None:
        return f

	# XXX

    # if generic array-API implementation is available, use that;
    # otherwise, fall back to NumPy/SciPy
    if f_name in _generic_implementations and spx is not None:
        _f = _generic_implementations[f_name](xp=xp, spx=spx)
        if _f is not None:
            return _f

    _f = getattr(_ufuncs, f_name, None)
    def f(*args, _f=_f, _xp=xp, **kwargs):
        array_args = args[:n_array_args]
        other_args = args[n_array_args:]
        array_args = [np.asarray(arg) for arg in array_args]
        out = _f(*array_args, *other_args, **kwargs)
        return _xp.asarray(out)

    return f
```

## Expected behavior

The whole function is reachable.

## Actual behavior

The lines from `#XXX` down are falsely reported as unreachable.

## Logs

```
XXX
```

**Comment by debonte** [comment]
Can you provide a complete, standalone code sample that repros the problem? Your code above is missing the definitions of `scipy_namespace_for`, `is_numpy`, etc.

Maybe the issue is that the return type annotation of `scipy_namespace_for` does not include `None`?

**Comment by lucascolley** [comment]
```python
def is_numpy(xp: ModuleType) -> bool:
    return xp.__name__ in ('numpy', 'scipy._lib.array_api_compat.numpy')

def scipy_namespace_for(xp: ModuleType) -> ModuleType | None:
    """Return the `scipy`-like namespace of a non-NumPy backend

    That is, return the namespace corresponding with backend `xp` that contains
    `scipy` sub-namespaces like `linalg` and `special`. If no such namespace
    exists, return ``None``. Useful for dispatching.
    """

    if is_cupy(xp):
        import cupyx  # type: ignore[import-not-found,import-untyped]
        return cupyx.scipy

    if is_jax(xp):
        import jax  # type: ignore[import-not-found]
        return jax.scipy

    if is_torch(xp):
        return xp

    return None
```

**Comment by debonte** [comment]
Thanks. The issue is that you've declared `f` to be a function (effectively a type annotation) but then you're also trying to assign values of `None` and `Any | None` (from `getattr`) to it. If you set `python.analysis.typeCheckingMode` to some value other than `off`, you'll see Pylance reports errors for those assignments.

By default, our unreachability hints include code that the type checker believes to be unreachable based on type analysis. Since it believes that `f` will always be a function, as defined at the bottom of your sample, it doesn't see any legal way for `f` to be `None` and therefore the code after the `f is not None` check is unreachable from its perspective.

Here's a simplified repro:

```python
f = None # Expression of type "None" is incompatible with declared type "() -> None"

if f is not None:
    raise ValueError("f is not None")

def f(): ... # Unreachable
```

Or consider this:

```python
f = None # Expression of type "None" is incompatible with declared type "int"

if f is not None:
    raise ValueError("f is not None")

f: int = 1 # Unreachable
```

There's been a lot of discussion in the Pylance and Pyright issue trackers lately about whether type analysis should impact unreachability hints, so a new setting has been added to control this behavior. If you don't want Pylance to mark code as unreachable when it is only unreachable based on type analysis, you can set the following in your `pyrightconfig.json`. This will be exposed as a VS Code config setting in the near future.

```json
{
    "enableReachabilityAnalysis": false
}
```

**Comment by lucascolley** [comment]
Thanks for the quick and thorough response! So it looks like we can fix if by using a different variable name at the bottom. Fair enough, this is by design and reasonable. Thanks again!
