### ISSUE TITLE
Code not marked as unreachable (but it is)

### ISSUE THREAD

**Issue by Craftman2868** [microsoft/pylance-release#6222]
<h3> Environment data </h3>

-   Language Server version: 2024.7.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

When I use `from sys import platform`, Pylance doesn't detect that the first block (`if platform == "win32":`) is unreachable (I'm on linux).
```python
from sys import platform


if platform == "win32":
    from msvcrt import kbhit, getch
    from colorama import init

    init()
    _UNIX = False
else:
    import tty
    import termios
    from sys import stdin
    import signal
    from select import select

    _UNIX = True
```
![image](https://github.com/user-attachments/assets/c67d7350-b320-4bed-abdc-37933b90754d)

But when I use `import sys` and then `sys.platform`, Pylance does.
```python
import sys


if sys.platform == "win32":
    from msvcrt import kbhit, getch
    from colorama import init

    init()
    _UNIX = False
else:
    import tty
    import termios
    from sys import stdin
    import signal
    from select import select

    _UNIX = True
```
![image](https://github.com/user-attachments/assets/85c82663-7e77-49fe-8bd5-ad9dac56b9a0)

<h3> Expected behavior </h3>

Mark the code as unreachable even when `from sys import platform` is used.

<h3> Actual behavior </h3>

When I use `from sys import platform` instead of `import sys`, the code isn't marked as unreachable when it is.

**Comment by erictraut** [comment]
This is by design. Static type checkers are required by PEP 484 and the [python typing spec ](https://typing.readthedocs.io/en/latest/spec/directives.html#version-and-platform-checking)to support certain specific tests for platforms. It specifically includes tests of the form `sys.platform == "<literal>"` but not `platform == "<literal>"`. If you want pyright (the type checker upon which pylance is built) to honor these directives at static analysis time, please switch to the supported form.
