### ISSUE TITLE
Attribute docstrings are ignored when defined inside indented blocks

### ISSUE THREAD

**Issue by kc0506** [microsoft/pylance-release#6253]
## Environment data

-   Pylance version: v2024.7.1
-   OS and version: windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.1

## Code Snippet

```python
class A:
    if typing.TYPE_CHECKING:
        a: int
        """a docstring"""

        def f():
            """f docstring"""
        
class B:
    a: int
    """a docstring"""

    def f():
        """f docstring"""
```

## Expected behavior

Currently Pylance supports class attribute docstring as discussed in #1576 and this screen shot shows:

![螢幕擷取畫面 2024-08-10 231808](https://github.com/user-attachments/assets/0a62326b-1a2b-4ce8-a4a1-e2ad38b54f8d)

Therefore, I expect the docstring also works for `A.a` which is defined inside an `if typing.TYPE_CHECKING` block. I come across this type of usage in `pydantic`:
https://github.com/pydantic/pydantic/blob/07b7f64072376922f8e40b22b8af2c5ebb353687/pydantic/main.py#L110-L120

## Actual behavior

The docstring for `a` is not working, while docstring for `f` still works, which seems inconsistent.
![螢幕擷取畫面 2024-08-10 231726](https://github.com/user-attachments/assets/78c680e6-633c-485f-a00b-831bf79c7144)
![螢幕擷取畫面 2024-08-10 231716](https://github.com/user-attachments/assets/915380f9-d253-4352-88fb-9951dd861bc7)

**Comment by erictraut** [comment]
This behavior is by design. Attribute docstrings were never formally specified, but they were discussed in detail in [PEP 528](https://peps.python.org/pep-0258/#attribute-docstrings), which was ultimately rejected. The implementation in Pylance is based on that specification. It is clear that the string after a variable declaration should be considered an attribute docstrings only if the statement is in the top level of a class suite and not within a conditional block. 

I don't know why this attribute is defined within a `TYPE_CHECKING` conditional block. These statements are not assigning a value to the attribute, so they should have no deleterious runtime effect. I suggest that you contact the maintainers of `pydantic` and see if they are willing to move this attribute declaration outside of the conditional block.

**Comment by kc0506** [comment]
Thx for your explanation!

**Comment by Viicos** [comment]
@kc0506, I've reorganized type annotations in https://github.com/pydantic/pydantic/pull/10104.
