### ISSUE TITLE
Support type hint for for-loop variable (using typeHintComment)

### ISSUE THREAD

**Issue by sabbyX** [microsoft/pylance-release#627]
It would be great to have type hint support for `for-loop` variable like
```python
for i in someNonTypedIterator:  # type: SomeType
```
now the `i` 's type become `SomeType`

It is actually possible currently but through _somewhat not_ good looking workaround as shown
```python
i: SomeType
for i in someNonTypedIterator:
```

This comes very handful when working with 'not type-hinted' libs.

**Comment by erictraut** [comment]
There is no way to annotate a type in a for loop using PEP 484 syntax. Old-style type comments are supported in limited form for backward compatibility only, so we don't have any plans to add support for them in other contexts.

The correct way to annotate a `for-loop` variable is the way you've suggested above. However, it's extremely rare that an explicit type declaration is required for a `for-loop` variable because its type can be inferred from the iterable expression in almost all cases. My team's code base has a quarter million lines of Python code (most of it strictly typed), and I don't think there's a single instance where we've needed to annotate a for loop variable.

**Comment by sabbyX** [comment]
> There is no way to annotate a type in a for loop using PEP 484 syntax.

Yeah, I know, I saw other IDEs support type-hint for `for-loop` variables. (ref: https://stackoverflow.com/a/45063497/13595571)

>it's extremely rare that an explicit type declaration is required for a for-loop variable because its type can be inferred from the iterable expression in almost all cases.

I am working with MongoDB's [motor](https://github.com/mongodb/motor) lib, it's not typed :(

**Comment by judej** [comment]
Closing issue. Please reopen if necessary.
