### ISSUE TITLE
Problems configuring Pylance

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#6326]
From the marketplace ratings and reviews.
> Do you want to spend more time configuring Pylance then coding? Go ahead and install this and enjoy your non stop fiddling with JSON config files in an endless loop.
If it works for you out of the box, start playing Bingo as you are very lucky person.

Amir, to understand the problem you are facing, would you please add more information on repro steps and the experience. 

thanks!

**Comment by olafurnielsen** [comment]
Came across this issue in yet another attempt to get Pylance to just work.

I've been using VSCode with Pylance and Pyright extensively for the past three years, and the amount of time I've spent dealing with out-of-memory crashes, unstable indexing behavior, and high CPU load is simply ridiculous.

It typically works fine in small, newly created Python projects, but as soon as a project matures with additional dependencies and an increased symbol count, performance takes a nosedive. This is when weird behavior starts to kick in, often requiring a full VSCode reload.

I'm constantly tweaking analysis exclusions, ignore settings, and package indexing depth, yet the only feedback you get is an overly verbose debug trace log. The [configuration documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) is unhelpful—parameters are vaguely described, with little to no examples provided, and there's no clear guidance on how one parameter might affect another.

I've remained a loyal user because it's a great product when it works, but it feels like there's a growing disconnect between the maintainers and users regarding the overall experience. Despite Pyright having 13k stars, there are only 13 open issues—not because there are so few issues, but because reports are frequently dismissed with arrogance and closed.

**Comment by debonte** [comment]
@olafurnielsen, can you provide access to a project (or projects) that reproduce any of these behaviors? We are aware that users are encountering out-of-memory issues, for example, but without a repro case it's difficult to fix them.

**Comment by heejaechang** [comment]
just in case you didn't see this, we have a wiki that explains how to setup a large workspace - https://github.com/microsoft/pylance-release/wiki/Opening-Large-Workspaces-in-VS-Code 

also, we have wiki that explains how to use `pylance` is glorified text editor - https://github.com/microsoft/pylance-release/wiki/Pylance-Configuration-Tips
