### ISSUE TITLE
Show comments describing a field as a docstring

### ISSUE THREAD

**Issue by mrkam2** [microsoft/pylance-release#6355]
As mentioned in https://github.com/microsoft/pylance-release/issues/1576#issuecomment-1259457589, currently supported by the plugin field docstrings were rejected https://peps.python.org/pep-0224/.

```python
    self.foo = "bar"
	""" This is what foo does """
```

Two more popular ways are to use the class docstring to describe arguments as requested in https://github.com/microsoft/pylance-release/issues/4711 or by simply commenting inline or in the preceeding lines as in:
```python
    # This is what foo does
    self.foo = "bar"
```
or
```python
    self.foo = "bar" # This is what foo does
```

It would be great to have such comments appear in the popup which currently shows nothing:
![image](https://github.com/user-attachments/assets/5f0c0c78-ae50-490f-856b-c614d9bd4f66)
or only the rejected form of a docstring:
![image](https://github.com/user-attachments/assets/d435880a-af66-4f44-8313-30d11fb131fa)

**Comment by heejaechang** [comment]
so, the ask is considering comment as a docstring?

on top of official support?

```
class A:
    def __init__(self):
        self.field = 1
        """ field doc string """

    def foo(self):
        self.field
```

**Comment by mrkam2** [comment]
> on top of official support?

According to https://peps.python.org/pep-0224/, this isn't supported officially, and is actually rejected.

Support these comments as docstrings:
```
class C:
    "class C doc-string"

    # attribute C.a doc-string (1)
    a = 1

    b = 2 # attribute C.b doc-string (2)
```

**Comment by heejaechang** [comment]
so, the rejection (https://peps.python.org/pep-0224/) is on 2000 and the PEP257 (https://peps.python.org/pep-0257/#what-is-a-docstring) is 2001. so I believe it is the official form.

otherwise, PEP 257 should be revised to remove it from PEP
> String literals occurring immediately after a simple assignment at the top level of a module, class, or __init__ method are called “attribute docstrings”.

**Comment by mrkam2** [comment]
Interesting, that looks like it was indeed approved. Thanks for the pointer!

**Comment by erictraut** [comment]
There are other active discussions on this topic. If you'd like to add your opinion and try to push one of the proposals forward, here are a few links:

1. A relatively [recent thread](https://discuss.python.org/t/revisiting-attribute-docstrings/36413) in the Python forums. It includes a bunch of proposals including string literals above or below the attribute assignment. A comment on the same line is also proposed. There are various pros/cons to these different approaches.

2. Draft [PEP 727](https://peps.python.org/pep-0727/) proposes to use `Annotated` metadata for this purpose. [Feedback on this PEP](https://discuss.python.org/t/pep-727-documentation-metadata-in-typing/32566) from the community was relatively negative, so its future is unclear. It's likely to be withdrawn or rejected.

There has also been some talk of formalizing and specifying the format (or multiple formats) of function and class docstrings. These can include parameter and attribute documentation.

If thinking coalesces on this topic and an official standard emerges, pyright (and therefore pylance) will almost certainly support it. Absent such a standard, it would be risky to add support for a non-standard convention because it will set us up for backward compatibility issues if and when such a standard does emerge.
