### ISSUE TITLE
unknownPylance[reportFunctionMemberAccess] error on attributes added by decorators in newest vscode/pylance releases

### ISSUE THREAD

**Issue by alasdairwilson** [microsoft/pylance-release#6403]
So pylance is not correctly linting methods/attributes added by decorators since the most recent release of vscode.

## Environment data

-   Pylance version: v2024.9.1 (also occurs with prerelease v2024.9.100)
-   OS and version: win10
-   Python version (& distribution if applicable, e.g. Anaconda): py310 and py312 tested

## Code Snippet

```python
def add_repr(func):
    func.func_repr = repr(func)
    return func

@add_repr
def add(x, y):
    return x + y

print(add.func_repr)
```

## Repro Steps

Copy and paste the snippet into a python file in vscode and watch it show linting errors.

## Expected behavior

Pylance used to not highlight an attribute added by a decorator as invalid and this code obviously executes no problem.

## Actual behavior
```
Cannot access attribute "func_repr" for class "function"
  Attribute "func_repr" is unknownPylance[reportFunctionMemberAccess](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportFunctionMemberAccess)
  ```

**Comment by rchiodo** [comment]
Thanks for the issue but this is by design. Pylance is a static analyzer and doesn't execute the code that adds 'func_repr' to the func.

My guess why you're seeing this is that you have a pyrightconfig.json and you're hitting this issue:
https://github.com/microsoft/pylance-release/wiki/Settings.json-overridden-by-Pyrightconfig.json-or-Pyproject.toml

Release 2024.9.1 changed how pyrightconfig.json settings are applied.

**Comment by alasdairwilson** [comment]
Ah yeah that is very tangential behaviour, moving the settings to corresponding settings.json does indeed fix it.

For the record, I knew it would not be able to find that method, it just never used to throw a linting error on it till this update. 

Thanks.
