### ISSUE TITLE
"Search for additional import matches" is shown when zero matches are found

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#6421]
## Environment data

-   Pylance version: 2024.9.101
-   Python version: 3.12.6

## Code Snippet

```python
chdir
nonsense
```

## Repro Steps

1. Trigger the light bulb on `chdir`. You'll see options to add imports from `contextlib` and `os`, plus a "Search for additional import matches" code action.
![image](https://github.com/user-attachments/assets/4b09f856-5269-4b7b-b557-809af56b09ac)
2. Trigger the light bulb on `nonsense`.

## Expected behavior

Since no "add import" code actions are listed, we also don't show "Search for additional import matches".

IIRC, there's a maximum number of "add import" code actions that we'll show in this list. My guess is that "Search for additional import matches" should only appear if the number of available matches exceeds that maximum.

## Actual behavior

We only show "Search for additional import matches"

![image](https://github.com/user-attachments/assets/9e0f5541-d419-4543-bd63-97c5ec815a1d)

**Comment by heejaechang** [comment]
this is not how it is designed. regular add import code action only list `exact match`, `search for additional import` shows prefix match (same way `auto import` works)

are you saying we should only show when we know `search for additional import` will have result? that would be expensive though since we need to do full prefix search on every key stroke and any cursor changes.

**Comment by debonte** [comment]
I see. I thought that based on UX feedback from vscode, we'd changed the code action list to only show the first few (5?) matches and additional matches needed to be selected from the pick list.
