### ISSUE TITLE
IntelliSense doesn't work in some third-party packages. But when Pylance is disabled, the IntelliSense can work.

### ISSUE THREAD

**Issue by Zionshang** [microsoft/pylance-release#6556]
## Environment data

-   Pylance version: v2024.10.1
-   OS and version: Ubuntu20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Editor: vscode
## Code Snippet

I installed the package `mujoco` via pip.
```bash
pip3 install mujoco
```
In python,  the following code can be run successfully

```python
import mujoco

xml = """......"""  # value has been ignored
model = mujoco.MjModel.from_xml_string(xml)
```

But neither autocomplete nor IntelliSense work
![Image](https://github.com/user-attachments/assets/c849379c-9183-4608-92a9-6b0af55e11f7)
![Image](https://github.com/user-attachments/assets/a82f0e26-ef78-4c68-b284-f191ae85c4c4)

## Repro Steps

I've tried a few methods
1.  Choose the right interpreter
![Image width="40%"](https://github.com/user-attachments/assets/1a747d34-ec12-42c7-a01e-488f54095f0f)
All the interpreters have tried, but nothing works
2. Edit the file `settings.json` in User environmet.
```json
    "python.languageServer": "Pylance",
    "python.analysis.extraPaths": [
        "~/.local/lib/python3.8/site-packages"
    ],
    "python.autoComplete.extraPaths": [
        "~/.local/lib/python3.8/site-packages"
    ]
```
I've determined the package is installed at `~/.local/lib/python3.8/site-packages` via `pip3 show mujoco`. But still not working.
## Expected behavior
**I found out when I disable the Pylance by**
```json
    "python.languageServer": "Jedi",
```
![Image](https://github.com/user-attachments/assets/dba5a905-0b6c-4947-b9f5-d6ce4509aab3)

**the  autocomplete and IntelliSense can work normally.**
![Image](https://github.com/user-attachments/assets/1d7530d3-c2ab-4859-8c91-1e14fa7fa4d8)
![Image](https://github.com/user-attachments/assets/7fab658e-4c35-4ddf-b9cd-c6d85e4ee598)
![Image](https://github.com/user-attachments/assets/d1c6a02f-5d9e-464f-beff-45a9bd6444e1)

## Actual behavior
What is strange to me is that some packages like `numpy` are installed in the same path with `mujoco`, but `numpy` 's autocomplete and intellisense can work normally.
![Image](https://github.com/user-attachments/assets/24882e31-174d-4883-8191-b515c5776d3e)

## Summary
Is this a problem with the `mujoco` package or a problem with Pylance? 
- If it is a problem with the package, why does the IntelliSense work after Pylance is disabled? 
- If it is a problem with Pylance, why does `numpy`'s IntelliSense work?

I would be very grateful if you could answer that question, because I spent a long time on it.

**Comment by rchiodo** [comment]
Thanks for the issue. The "problem" here is that Mujoco is a wrapper around native code. Pylance cannot read native code in order to find the necessary information to display your intellisense. This is because Pylance doesn't run python code. It's a static analyzer.

You can tell that by looking at the install of Mujoco:

![Image](https://github.com/user-attachments/assets/efd83540-97a1-4737-8ba8-7cfde5597823)

A good portion of the public interface is in `.pyd` files (native python modules).

Mujoco would have to provide [type stubs](https://microsoft.github.io/pyright/#/type-stubs?id=importance-of-type-stub-files) in order for Pylance to find the necessary information. 

See this issue from Mujoco where people had similar problems with Pycharm:
https://github.com/google-deepmind/mujoco/issues/244

Jedi, on the other hand, is a python app. It actually loads Mujoco into a python runtime and can inspect the native parts that way.

**Comment by Zionshang** [comment]
@rchiodo Thank you for the answer, very thorough and concise!
