### ISSUE TITLE
Custom dataclass gets no arguments in tooltip

### ISSUE THREAD

**Issue by mskrip** [microsoft/pylance-release#656]
## Environment data

-   Language Server version: 2020.11.2
-   OS and version: Arch Linux 5.9.10-arch1-1
-   Python version: 3.8.6

## Expected behaviour

When creating a custom dataclass decorator, I'd expect the LS to act the same way as using the base decorator:

![image](https://user-images.githubusercontent.com/17459600/100437615-4c208680-30a1-11eb-82f9-14bd9d069ae6.png)

## Actual behaviour

In the tooltip for instance of the custom-annotated dataclass, there are no arguments displayed:

![image](https://user-images.githubusercontent.com/17459600/100437764-868a2380-30a1-11eb-9c72-ea96ef622f23.png)

**Comment by erictraut** [comment]
The static analyzer needs to evaluate the values of the arguments to the `dataclass` call (e.g. `frozen`) at the time it's used as a decorator. If you call `dataclass` outside the context of a decorator, the information about these argument values is lost. The workaround is to not use the "custom dataclass" technique and always call `dataclass` directly within the decorator.

**Comment by mskrip** [comment]
Yes I can live with not using the "custom dataclass" approach for the sake of IDE clarity but since the instantiation of a dataclass outside of decorator context works the same in Python but not in static analyzer, it seems to me like a bug regardless of user's preference.

Moreover, the dataclass call arguments are irrelevant here, this bug pertains to typing for the generated constructor when the "custom dataclass" approach is used. I just used the `frozen` example to show a simple use case for the approach.

**Comment by gvanrossum** [comment]
I don't want to put words in the mouth of the pyright developers, but basically your code is "too dynamic for static checkers". Just because it works doesn't mean it should be acceptable to a static checker (there are many examples of this). Perhaps a better excuse (which also applies to mypy, BTW) is that the type checker has to special-case the `dataclass` decorator to make it work, and the current implementation only recognizes the special case when it's in used as a class decorator. If your usage were common I would recommend adding support for it in the type checker; but I've never seen this usage before.

**Comment by mskrip** [comment]
OK, I understand. If it's not as common as I thought it is, then I agree, it wouldn't be worth supporting.

**Comment by judej** [comment]
Closing issue. Please reopen if necessary.
