### ISSUE TITLE
Pylance extension providing less than useful error messages.

### ISSUE THREAD

**Issue by nicolasnoble** [microsoft/pylance-release#6565]
Today, I got greeted with the following error message from Pylance's visual studio code extension:

![Image](https://github.com/user-attachments/assets/1e0f0d8e-e7d5-49f3-be49-cd825a52a263)

Which, obviously, is a bit problematic that these haven't been replaced by whichever error printer is used. I am not sure where the actual repository for the extension is, but this repository is the one linked from the extension marketplace page, so feel free to move it if this isn't the right location.

**Comment by rchiodo** [comment]
I'm not sure if you're reporting that the error message is bad or that the error message itself is happening?

The error message has a bug in it (which has since been fixed).

This error itself means you're using a Python extension that is either newer or older than the Pylance extension. Since they share an API they have to be kept in sync or things could not work. I would hazard a guess your Pylance extension is older because we've since fixed this error in our latest bits.

**Comment by nicolasnoble** [comment]
I was reporting the fact the error message has a bug, yes. If it's been fixed in the meantime, great!
