### ISSUE TITLE
No programmatic way to silence `reportUnknownMemberType` coming from 3rd-party code

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#662]
## Environment data

-   Language Server version: 2020.11.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.9.0

## Expected behaviour

Not to complain about a partially unknown type which I explicitly cast.

## Actual behaviour

When calling `yaml.load()` from PyYAML, I am getting a `reportUnknownMemberType` error even with a cast (since I'm loading YAML data):

```python
config = cast(dict[str, Any], yaml.load(file, Loader=yaml.FullLoader))
```

Specifying the variable's type didn't solve it either.

PyYAML is 3rd-party, so I can't directly fix it. I ended up using `# type: ignore` to silence the issue.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment]
I presume that you're using "strict" typeCheckingMode. 

The reason you're seeing this is because the typeshed stub file for this package is incomplete. It's missing a type annotation for the `Loader` input parameter on this method. 

You can submit a PR to typeshed that addresses the issue. Pylance & Pyright frequently pick up new snapshots of typeshed.

In the meantime, there are a few ways to silence this:
1. Use `# type: ignore`
2. Use a cast to Any: `cast(Any, yaml).load(file, Loader=Yaml.FullLoader)`
3. Use `# pyright: reportUnknownMemberType=false` within the file in question
4. If the problem is widespread, use settings or pyrightconfig.json to disable the `reportUnknownMemberType` for your entire workspace

Did you have some other approach in mind here? I'm not sure what you mean by "programmatic way".

**Comment by brettcannon** [comment]
Thanks, Eric, for the details! And you're right, I was trying out "strict" mode.

As for "programmatic", I didn't want to silence the entire line of type checks, just that one function call (it was an expression as part of several other in a statement). So I was figuring either an explicit specification of the resulting type from just that function call (e.g. `var: T = yaml.load(...)`) would work, or an explicit cast.

But it looks like casting the module itself was the solution I was looking for. Thanks!
