### ISSUE TITLE
The Optional object should be checking everywhere to prevent type hint erors.

### ISSUE THREAD

**Issue by xiaojiuwo1993** [microsoft/pylance-release#6624]
I use type checking : basic strategy in my project.
```python
class ParentClass:
    is_save: bool
    request: str
    data: Optional[str]

    def __init__(self, request: str) -> None:
        self.is_save = False
        self.request = request
        self.data = None

    def handle(self):
        self.parse()
        self.check_data()
        self.save_data()

    def parse(self):
        if "#" in self.request:
            self.is_save = True
            self.data = self.request[1:]
        else:
            self.is_save = False

    def check_data(self):
        if self.data is None:
            raise Exception("data is none")

    def save_data(self):

        # self.check_data()
        if self.data is None:
            raise Exception("data is none")
        if self.is_save:
            save_data(self.data) # <- type hint error here
        else:
            print("do nothing")


def save_data(data: str):
    print(f"saving {data}")

```
If i write none check before using of this object it will not show any error
![Image](https://github.com/user-attachments/assets/df4a106a-4c35-451b-affe-af129d0df6fa)

if I wrap none check into a function the type hint error occurs
![Image](https://github.com/user-attachments/assets/3e34b4c7-25d0-46ed-be5b-60ca1f81d207)

if I raise exception before using of the optional object, theoritically, the type hint should known self.data should never be None, but it just can not detect the self.data status, so the type hint present an error here.
Would this be an bug or am I wrong?

**Comment by rchiodo** [comment]
Thanks for the issue but I believe what you're asking for isn't possible to support. Pylance/Pyright would have to keep track of the fact that the type of self.data was verified to not be None as a result of calling `check_data`. I don't believe that's something we can reasonably keep track of. 

@erictraut do you think my analysis is correct? Could the constraint solver remember type narrowing?

**Comment by erictraut** [comment]
This has nothing to do with constraint solving since there are no type variables involved. This question relates to the concept of type narrowing. Static type checkers narrow expressions only within an execution context (e.g. a function) not across functions. That means calling a function like `check_data` narrows the type of the expression `self.data` locally, but it has no affect on the type of `self.data` outside of its own context.

The TypeScript type system has something called an [assertion function](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions), which enables this pattern. There is currently no analogous feature in the Python type system.

The recommended pattern for Python if you're interested in writing type-safe code is to replace the type assert function with a function that returns the validated object. Here's how that would work:

```python
    def get_data(self):
        if self.data is None:
            raise Exception("data is none")

        return self.data

    def save_data(self):
        data = self.get_data()
        if self.is_save:
            save_data(data)
        else:
            print("do nothing")
```
