### ISSUE TITLE
Allow import of type aliases using Quick Fix

### ISSUE THREAD

**Issue by bedapisl** [microsoft/pylance-release#6645]
Hello,
I am using VSCode with Pylance. When a class is not defined, it is possible to add corresponding import with a Quick Fix. This does not work for type aliases. For example consider the following files:

definitions.py
```
MyInt = int

class MyClass:
    pass
```
main.py
```
MyInt
MyClass
```
In main.py a Quick fix on MyClass automatically generates the import, but this does not work on the MyInt.

![Image](https://github.com/user-attachments/assets/3f2d5131-525b-4e9f-a029-c20fa71aa779)

![Image](https://github.com/user-attachments/assets/bf5b27f4-3bcf-42f2-ba47-2bb4ba6d591b)

**Comment by jadamwilson2** [comment]
Is there a way to modify or fork pylance locally to let this work? That would probably be faster for us than manually adding and maintaining hundreds of NewTypes and variables to __all__ across dozens of files. We thought that our dev environment wasn't working, and just found out this is actually by design.
