### ISSUE TITLE
An wrongly inferred value generates a false positive report message

### ISSUE THREAD

**Issue by Questionsdenombres** [microsoft/pylance-release#6695]
## Environment data
- Pylance version: v2024.11.3 - mode strict
- OS and version:  Windows-11-10.0.22631-SP0
- Python version: 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]

## Code Snippet
```python
def test():
    count = 0

    def DFS():
        nonlocal count
        count = 1
        return

    DFS()
    if count == 1:  # Condition will always evaluate to False since the types "Literal[0]" and "Literal[1]" have no overlap
        print(count)
    return

test()
```
## Expected behavior
No report.
Pylance doesn't see that variable ```count``` can be modified by the internal function.

## Actual behavior
Report is wrong: Condition will always evaluate to False since the types "Literal[0]" and "Literal[1]" have no overlap"
False positive.

Thank you for your great job and tools.
Patrick - Paris - France

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working correctly here, so I don't consider this a bug.

Static analysis tools like pyright, mypy, pyre, etc. perform code analysis locally, not globally. They assume that function calls do not have side effects that modify local state. This assumption is necessary because, in general, static analyzers cannot determine the runtime order of function calls. Even in cases where such order can be determined, it is computationally infeasible to perform global analysis to discover all possible side effects.

If you want your code to work with static analysis tools, you should avoid design patterns that involve non-local side effects.

**Comment by Questionsdenombres** [comment]
Ok, I understand and fully agree. So I close the issue.
Is there a place where the design philosophy and limitations of the static analysis tools is outlined ?
