### ISSUE TITLE
Type checker does not respect unittest assertion methods

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/pylance-release#6727]
Type: <b>Bug</b>

If I am inside of a unittest test case, and I write some code as such:

```python
from typing import cast
from unittest import TestCase


class TestMyTest(TestCase):
    def test_simple(self):
         testvar: int | None = cast(int | None, 1)
        self.assertIsNotNone(testvar)
        reveal_type(testvar)
        x = testvar.to_bytes()
```

At the `reveal_type`, I get `Type of "testvar" is "int | None" Pylance`. However, the line below says `"to_bytes" is not a known attribute of "None" Pylance(reportOptionalMemberAccess)`.

In contrast, this code:

```python
from typing import cast
from unittest import TestCase


class TestMyTest(TestCase):
    def test_simple(self):
         testvar: int | None = cast(int | None, 1)
        assert testvar is not None
        reveal_type(testvar)
        x = testvar.to_bytes()
```

At the `reveal_type`, I get `Type of "testvar" is "int" Pylance`, and no more error on the line below. I think the type checker should be able to equate the `assert*` methods with the `assert` statement.

Extension version: 2024.11.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin x64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.77GB free)|
|Process Argv|--crash-reporter-id 1eb59a8f-a777-446b-b97e-fe7c3d092446|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by erictraut** [comment]
There's currently no mechanism in the Python type system to support this scenario. What we'd need to support this is a feature found in TypeScript called a "type assert". There has been some discussion in the Python typing forums about adding something like this, but they haven't materialized into anything concrete. If you'd like to champion such a feature, [here](https://github.com/python/typing-council#decisions) is the process for amending and extending the Python type system.

In the meantime, the best solution is to use the built-in `assert` statement rather than library calls that perform similar functions. The built-in `assert` statement is understood by type checkers, and most unit test frameworks also understand `assert` statements.
