### ISSUE TITLE
Unable to access `__name__` property of a class(aka. type) after type-check

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#747]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5(Anaconda)

## Expected behavior

```python
from typing import Type

def foo(arg):
    if isinstance(arg, Type):
        # Type of `arg` is `type[object]` or just `type`, and `arg` holds a `__name__` property.

        name = arg.__name__
        # Type of `name` is `str`.
```

## Actual behavior

```python
from typing import Type

def foo(arg):
    if isinstance(arg, Type):
        # Type of `arg` is `type[Unknown]`.

        name = arg.__name__
        # Type of `name` is `Unknown`.
```

or

```python
from typing import Type

def foo(arg):
    if isinstance(arg, Type[object]):  # Error in this line because `isinstance` doesn't support generic type.
        # Type of `arg` is `type[object]`.

        name = arg.__name__
        # Type of `name` is `str`.
```

**Comment by Azureblade3808** [comment]
Maybe I'm wrong about the usage of `Type[object]`. But I think a value of `type[Unknown]` should still hold all properties declared in class `type`.

**Comment by erictraut** [comment]
The behavior in this case changed between Python 3.8 and 3.9. If you configure Pylance to assume that it's using Python 3.8 and change `Type` to `type`, it will produce the `str` result you expect. But with Python 3.9, the typing rules changed thanks to [PEP 585](https://www.python.org/dev/peps/pep-0585/).

PEP 585 indicates that `Type` and `type` are now supposed to be treated interchangeably. That means `type` is a generic class that has a single type parameter. If you don't provide a type argument for that type parameter, it is assumed to be `Any` (or `Unknown`, which is a variant of `Any` used by pyright). 

Let's consider the following code:
```python
def foo(arg: Type[Any]):
    reveal_type(arg) # Any
    x = arg.value # No type error should be reported here
    reveal_type(x) # Any
```

A type checker should not generate an error here because it has been told that `arg` is "any" class. Whenever `Any` appears, the type checker must assume that the use of that expression is allowed. The type of the expression `arg.value` is also `Any` in this case.

If the type argument is not provided for `Type`, it is assumed to be `Unknown`, and this `Unknown` propagates.

```python
def foo(arg: Type):
    reveal_type(arg) # Unknown
    x = arg.value # No type error should be reported here
    reveal_type(x) # Unknown
```

Going back to your example, the `isinstance` type narrowing applied to `arg` gives it the type `Type[Unknown]`, which is effectively the same as `Unknown`. And that means any member accessed from it will be `Unknown`.

So the behavior you're seeing is a direct consequence of the changes in PEP 585.

**Comment by Azureblade3808** [comment]
I understand the interchangeability between `Type` and `type` in Python 3.9. It still confuses me why `type[Any]` would be interpreted as `Any`.

We can all agree that a `list[Any]` is a `list` instead of an `Any`.
```python
a: list[Any] = []
b: dict[Any, Any] = {}

a = b  # Type incompatible.
#### or ####
b = a  # Type incompatible, too.
```

And `type[object]` is still a `type` instead of an `object`.
```python
a: type[object] = type(str)   # `a` can be any subclass of object, so basically any class.
b: object = None

a = b  # Type incompatible.
#### or ####
b = a  # Type compatible, as `object` is the root class.
```

So how can it be that `type[Any]` is an `Any` instead of a `type`?

**Comment by Azureblade3808** [comment]
It still bugs me that

```python
a: type = type(int)
a.__subclasses__  # Type: Unknown

b: type[Any] = type(int)
b.__subclasses__  # Type: Any

c: type[object] = type(int)
c.__subclasses__  # Type: () -> List[Type[object]]
```

While

```
a: frozenset = frozenset()
a.__iter__  # Type: () -> Iterator[Unknown]

b: frozenset[Any] = frozenset()
b.__iter__  # Type: () -> Iterator[Any]

c: frozenset[object] = frozenset()
c.__iter__  # Type: () -> Iterable[object]
```

I'd like to know why `type[Unknown]` is treated like `Unknown` and `type[Any]` like `Any` for member accessing. Is there some special parts of `type` that make it behave so differently from other generic classes?

**Comment by erictraut** [comment]
The Python language is full of inconsistencies. This is one of many examples.

The type expression `list[int]` refers to "a list that contains `int` objects". The type expression `frozenset[int]` refers to "a frozenset that contains `int` objects". However, the type expression `Type[int]` doesn't refer to a type that contains `int` objects. Instead, it refers to "the class that implements an `int` object" (or some subclass thereof).

What does `Type[Any]` mean? It means "the class that implements an `Any` instance", which is still `Any`.

Prior to Python 3.9, `Type` was distinct from `type`, but PEP 585 indicates that `type` and `Type` need to be aliases of each other. So now `type` is a generic class, and `Type[int]` and `type[int]` mean the same thing.

I know this answer is not satisfying, but I think it's the logical result of PEP 585.

Here's a thought. Perhaps rather than treating `Type` and `type` the same, the type checker should continue to treat them as distinct, but special-case the subscripted `type` expression as a `Type`. That would allow us to continue to treat `type` as a non-generic class, and the `isinstance` type narrowing would still work as you would like if you pass `type` as the second argument.

Also, I think one could make a good argument that the type checker should evaluate the type of the expression `type(int)` to be `Type[int]` rather than `Type[Unknown]`.

**Comment by Azureblade3808** [comment]
> What does Type[Any] mean? It means "the class that implements an Any instance", which is still Any.

Good point. I got it.

I tended to think `Type[Any]` means "an undetermined class" instead of in such way. What makes the difference is that `Any` is vacant. In python, everything is an instance of `object` and every type is an instance of `type[object]`, but it may not be the same case for `Any` as it isn't a real type and its instances don't really exist. It could be both right to treat `type[Any]` as some undetermined subclass of `type[object]` or just `Any`, depending on how we think about it.

Thank you for the detailed explanation @erictraut .

**Comment by tapetersen** [comment]
@erictraut 
I may be missing a point here but isn't the case slightly different for `Any` vs `Unknown`?
`Any` is in python typing a bottom value which is assumed to support any operation which means that `Type[Any] = Any` since it's type object can also be arbitrary.
Unknown is treated different on higher strictness levels and feels more like a top value where less or nothing is assumed which means that narrowing it to `Type[Unknown]` is meaningful since now we can infer that at least it supports the interface of a type object.

```
def foo(a:Any):
   a.__name__ # Works since it's Any
   type(a).__name__ # Works since we have to assume that the class of an Any value can also support anything
   
def bar(a):
    a.__name__ # Complains on higher strictness since A is Unknown
    type(a).__name__ # Should probably work since Type[Unknown] is at least some kind of type
```

Of course also relevant in https://github.com/microsoft/pyright/issues/1288

**Comment by erictraut** [comment]
`Unknown` is an internal alias of `Any` used within Pylance. The only difference is that `Any` is explicitly generated, and `Unknown` is generated implicitly when there is missing type information. Other than that, they are treated the same. 

So just as `Type[Any] = Any`, `Type[Unknown] = Unknown`.

**Comment by marcospgp** [comment]
I'm getting a type error when accessing the `__name__` attribute of a class:

```
Cannot access member "__name__" for type "MyClass"
```

This is not an instance of a class, it's the class itself.

I was able to fix the issue by typing the class correctly as the class itself, as opposed to an instance of the class:

```python
# Instance of a class
my_instance: MyClass

# A reference to the class itself
my_class: type[MyClass]
```
