### ISSUE TITLE
Pylance always says module does not exist although it pop-up module's docstring

### ISSUE THREAD

**Issue by alexanderluiscampino** [microsoft/pylance-release#760]
Pylance cannot resolve any of my imports, although if I click on F12 it always finds them. It even pops-up the docstring of the module. But on the import statement always shows the red squiggly line underneath, on all imports, no matter what. 

![image](https://user-images.githubusercontent.com/32500355/102824099-05b50380-4391-11eb-9527-3d2a2f822a77.png)

**Comment by jakebailey** [comment]
Where is `test.py` relative to that file?

Are you getting go-to-def and docstrings when you work with that file with the unresolved import?

**Comment by alexanderluiscampino** [comment]
The `test.py` is at the root. So all the import paths are correct.

I get the definitions (F12) if I use the go-to-def functionality, which is what is weird.

**Comment by jakebailey** [comment]
Can you hover over `event_validator`?

**Comment by alexanderluiscampino** [comment]
![image](https://user-images.githubusercontent.com/32500355/103582799-6b29e980-4e93-11eb-8db9-d9257fbc84f8.png)

**Comment by jakebailey** [comment]
Oh, I'm silly. I didn't see that it says "pylint" in the tooltip. This is pylint failing to analyze the code, not Pylance. We're resolving this module correctly and that's why tooltips and navigation work. You'd see a diagnostic associated with Pylance if it were coming from us.

I don't think we can do anything about pylint failing to resolve an import; maybe it has its own config for special paths.

You can disable pylint if it bothers you, or just that one rule.

**Comment by alexanderluiscampino** [comment]
Ha! yup, also on me, should have read better it was coming from pylint, for some reason I thought pylance took over pylint when enabled. 

I have disabled it here, for future reference.
![image](https://user-images.githubusercontent.com/32500355/103586382-d4146000-4e99-11eb-9d66-fd2154714096.png)

Just for my reference, and maybe others, is there anything pylint does that pylance doesn't?

Thank you for the help Jake, we can close this now.

**Comment by jakebailey** [comment]
Pylint does a number of things that pylance doesn't, though most differences are due to pylint doing a lot of style checks in addition to a few non-style checks.

Typically, the Python extension disables pylint altogether when a language server is enabled, though, as the default settings the Python extension uses are minimal and only cover a couple things that LSs do natively (syntax checks, import checks, etc).
