### ISSUE TITLE
incorrect autoImportCompletions: from os import sep

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/pylance-release#770]
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

pylance: v2020.12.2
```
I have some code containing `sep`:
```
pd.read_csv(path, sep='\t')
```
and then, the following import was added every time.
```
from os import sep
```

**Comment by judej** [comment]
@StevenLi-DS, thanks for the report. The issue is that when you are typing `sep` there is a completion dropdown that offers several options the top one results in the `from os import sep`. The second choice `sep=` is what you need.

Hope that helps, please let me know if you have another question

![image](https://user-images.githubusercontent.com/547753/103246443-488a5480-4918-11eb-85ad-af0802fad7ad.png)

**Comment by StevenLi-DS** [comment]
Hi @judej, I think it is a bit weird to have a completion without `=` if I'm already inside a function and typing params. right?

**Comment by erictraut** [comment]
You are typing arguments, and any expression can be used as an argument. In other words, `sep` is a valid argument expression. `sep=` is also valid because the function that you're calling supports a keyword argument with that name. So it's reasonable that both of these would be presented as completion suggestions.

Arguably, if you have already typed at least one keyword argument within a function call expression, the completion suggestion logic should know that all subsequent arguments must be keyword arguments too. But that's not the case you've shown in your code sample, and it's a situation that will come up rarely in practice.

**Comment by StevenLi-DS** [comment]
@erictraut If I already define a variable `sep` and arguably it makes sense that it shows up in the completion. However, in my case, I didn't have a variable named `sep` at all. Meanwhile, this issue isn't about what completion I should get, but an import was added incorrectly. 

I wonder if there is a toggle to turn this feature off.

**Comment by erictraut** [comment]
Identifiers used in expressions can refer to more than just local variables. They can also refer to local functions, local classes, or (quite frequently) symbols imported from other modules. If you had a local symbol `sep`, that would have been listed as the first completion suggestion in the list. Since there was no such local symbol, Pyright offered two other suggestions: 1) use the symbol `sep` from the os module (and insert an import statement since it is not already imported), or 2) use a keyword argument name. Those were the first and second options in the completion suggestion list, and both are reasonable suggestions to offer in this circumstance.

I'm not sure what you mean by "import was added incorrectly". You selected an "auto import" suggestion from the completion suggestion list, so Pylance added the import for you since `sep` was not yet imported in your file. If you didn't want to complete your expression with the `sep` auto-import suggestion, you could have pressed the down arrow to go to the next suggestion (`sep=`) and chosen that one instead. Pylance tries to do its best to sort the completion suggestions based on the most likely choice, but there are times when you will find that you need to select the second or third option in the list.

If you never want Pylance to offer auto-import suggestions, you can disable the feature by setting `python.analysis.autoImportCompletions` to false.

**Comment by StevenLi-DS** [comment]
Hi, @erictraut I don't have local symbol `sep`. In this case, if you are using this pandas function, you have to specify a separator, so I don't know how this is reasonable. The point is that I didn't use `sep` module at all, but it is imported. I think this is bug since Pylance incorrectly identified what should be imported. 

However, if this is an expected behavior, then I guess I just gotta close this issue. Thanks @erictraut.
