### ISSUE TITLE
Code outside context manager falsely reported as unreachable

### ISSUE THREAD

**Issue by andersea** [microsoft/pylance-release#773]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5

## Expected behaviour

Code outside a context manager should never be assumed unreachable.

Context managers can catch exceptions that happen inside the code block that the context manager wraps. This allows programming constructs such as infinite loops (`while True:` for example) to be broken out of by raising exceptions inside the loop, without interupting the code outside of the context manager.

## Actual behaviour

Raising an exception or starting an infinite loop inside a context manager, marks ensuing code as unreachable.

## Code Snippet / Additional information

```python
from contextlib import contextmanager

class MyException(Exception):
    ...

@contextmanager
def catcher():
    try:
        yield
    except MyException:
        pass

with catcher():
    raise MyException()

print('This code is reachable.')
```

**Comment by erictraut** [comment]
By default, context managers are assumed not to catch exceptions. Therefore, any code after a `raise` statement will be treated by a type checker as unreachable. This is the "as designed" behavior.

A small subset of context managers (like the one in your example) do catch exceptions. To tell a type checker that your context manager catches exceptions, you need to annotate its `__exit__` method with a `bool` return type. This is the convention that was initially implemented by mypy and later adopted by other type checkers like pyright/pylance.

Since you're relying on the `@contextmanager` decorator, you aren't explicitly defining an `__exit__` method, so there's no opportunity for you to annotate it correctly. You would need to take some other approach, such as using the `contextlib.suppress` context manager, which annotates its `__exit__` method appropriately. Alternatively, you could create your own custom context manager class that defines an `__enter__` and `__exit__` method and annotates the latter with a `bool` return type.

**Comment by andersea** [comment]
Thank you for having a look at this.

Here is an example from the popular async framework [trio](https://trio.readthedocs.io/en/stable/index.html).

```python
import trio

async def main():
    async with trio.open_nursery() as nursery:
        while True:
            await trio.sleep(0)
            nursery.cancel_scope.cancel()
    
    print('This code is reachable')

trio.run(main)
```
This I would consider normal trio code. Are you saying that there is a bug in trio here? Should modify their context managers somehow, in order for the print statement not to be marked as unreachable by trio?

**Comment by erictraut** [comment]
I'm not familiar with `trio`, but from a quick look at the github code repo for this library, it looks like it's untyped — i.e. it doesn't contain a `py.typed` file as per PEP 561, and it doesn't include type annotations or type stubs.

In the absence of type information, pylance will do its best to understand the library's interface and behaviors, but there's only so much that can be determined through static analysis.

If you are a frequent user of `trio`, I recommend that you encourage the maintainers of this library to add type information in their next release. They can refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md) for details.

If they don't want to add full type information, they (or you, through a PR) could add a `bool` return type annotation to the `__exit__` and `__aexit__` methods for their context managers that catch exceptions at runtime. This would be a quick and simple fix, and it would address the specific issue that you're seeing here.

You can try it out locally on your installed copy of `trio` if you'd like. Here's the line you'd need to change: https://github.com/python-trio/trio/blob/d18eb18fbe57075a68133404e44985573d4306a0/trio/_core/_run.py#L801. Simply add `-> bool` before the colon. I think that should work. If not, let me know, and I'll investigate further.

**Comment by erictraut** [comment]
Ah, I just noticed that you're also using a `while True` loop within the context manager block, and you're relying on one of the calls to raise an exception to get out of that loop. That's also not possible for a static type checker to understand without additional knowledge. From the perspective of the static analyzer, this looks like an infinite loop that will never exit.

There is a way to annotate a method that always raises an exception, but there's no way to annotate a method that _sometimes_ raises an exception.

If the grayed-out "unreachable code" bothers you, there are ways you could modify your code to avoid this (e.g. by changing `while True` to `while 1`). Otherwise, you can just ignore the fact that some of the code is grayed out.

The pattern you're using is unfortunately difficult for static analysis to handle. You're using exceptions for (non-error) control flow, which is not what exceptions were designed for.

**Comment by njsmith** [comment]
@erictraut Here's an idea for a compromise: assume that any `await` might raise an exception. `await`s are explicitly the point where async frameworks can inject cancellation exceptions, and this is commonly used for control flow in async programs.

(Same for `yield` and `yield from`, I guess – especially since the interpreter likes to inject exceptions in those on its own: https://www.python.org/dev/peps/pep-0342/#new-generator-method-del)

**Comment by erictraut** [comment]
That would require us to introduce the notion of "a statement that might raise an exception to effect control flow". There's no such notion in pyright's static analyzer today. The control flow engine in pyright is already very complex, so I'm reluctant to add more complexity to it unless there's a really good reason to do so. I'll need to think about this more.

**Comment by njsmith** [comment]
@erictraut Fair enough.

On further thought, I'm not sure that's the best fix anyway. Maybe the ideal solution would actually be to notice when an infinite loop has some kind of error handler around it, and in that case treat the code after the error handler as reachable. This isn't even specific to context managers, e.g.:

```python
try:
    while True:
        ...
finally:
    print("exiting")  # Probably this code should be considered reachable!

try:
    while True:
        ...
except KeyboardInterrupt:
    pass

print("Exiting")  # This should also be treated as reachable
```

And then the case reported here would be handled automatically by the logic you mention where typing `__exit__(...) -> bool` causes a context manager to be treated like a `try` block.

**Comment by erictraut** [comment]
That's a good point. The code flow engine already treats a context manager like a `try` block if it claims to suppress exceptions. So as long as the `__exit__` method is properly annotated, it will work fine. I just confirmed that pyright does the right thing if there is a `while True:` loop within such a context manager block.

**Comment by njsmith** [comment]
Ah cool, so it sounds like the only issue is that trio needs to add proper type annotations, and this can probably be closed :-)

@andersea as a quick workaround, it sounds like installing `trio-typing` might solve your problem immediately...

**Comment by andersea** [comment]
@njsmith and @erictraut Again, thanks for looking at this.

I am using poetry as my main package handler for my projects. I tried to add trio-typing as a dev dependency, with `poetry add --dev trio-typing`, but it doesn't work immidiately.

Assuming adding type annotations to trio will eventually fix this, I am fine with closing it. Thanks again guys.

**Comment by lordmauve** [comment]
Isn't this the wrong way around? If the context manager's __exit__() isn't annotated, we have to assume it may suppress the exception and the code after the context may be reachable. If it is annotated as `-> None` then we know it doesn't suppress the exception. (And if it doesn't contain `return expr` statements you can infer that return type).

I think I agree that context managers are less likely to suppress exceptions than suppress them, but isn't the purpose of a static analyser to describe what the code can be proven to do/not to do?

It certainly looks like a bug when code gets highlighted as not reachable when it is clearly being reached.
