### ISSUE TITLE
Add inference to enhance typing check.

### ISSUE THREAD

**Issue by wuyudi** [microsoft/pylance-release#778]
I just read this:

https://github.com/google/pytype#how-is-pytype-different-from-other-type-checkers

```py
def f():
    return "test"


def g():
    return f()+1


a = "1"
b = 4
a + b
```

Pylance doesn't warn this.

**Comment by erictraut** [comment]
Pylance does report errors in these cases if you enable type checking. By default, the `python.analysis.typeCheckingMode` is set to `off` because many Pylance users are not interested in seeing these errors. If you change this setting to `basic`, you will see errors reported in the above code sample.
