### ISSUE TITLE
Adding an extra path causes Pylance to miss-interpret sys.version_info

### ISSUE THREAD

**Issue by guysz** [microsoft/pylance-release#785]
## Environment data

-   Language Server version: v2020.12.2
-   OS and version: CentOS7.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.8

## Expected behaviour

Adding an extra path shouldn't affect sys.version_info analysis

#### My code:
    import sys
    if sys.version_info != (3, 6):
        pass    # Should be unreachable in my environment
    else:
        pass
When I don't add extra path to `python.analysis.extraPaths` the analysis works as expected - the line inside the `if` block is unreachable since I use python 3.6.

But when I add an extra path:
`{
    "python.analysis.extraPaths": ["./foo"]
}`
I see that the line inside the `else` block is unreachable.
It seems that PyLance think in this case that I have Python 3.9 althogh vscode shows that I am using Python 3.6

**Comment by erictraut** [comment]
Hm, I can't think of any explanation for what you're seeing. I'm not able to repro it. I'd appreciate some extra help from you in narrowing down the problem.

If you quit and restart VS Code, then open the same code file, does the problem persist?

If you remove the extraPath, does the behavior revert back to what you are expecting?

If you add something other than "./foo" as an extra path (e.g. "."), does the same thing happen?

Could you post a screen shot of the code in the editor before and after you make the extraPaths change?

**Comment by guysz** [comment]
**If you quit and restart VS Code, then open the same code file, does the problem persist?**
Yes.

**If you remove the extraPath, does the behavior revert back to what you are expecting?**
Yes

**If you add something other than "./foo" as an extra path (e.g. "."), does the same thing happen?**
Yes, no matter what path I add the same thing happen, also with non-existing path.

**Expected behavior:**
![Good](https://user-images.githubusercontent.com/34423130/103277864-9f546480-49d2-11eb-9e74-c654598fbb6d.PNG)

**Problem:**
![Bad](https://user-images.githubusercontent.com/34423130/103277875-a8453600-49d2-11eb-94e1-9efc55379aa7.PNG)

**Comment by jakebailey** [comment]
@guysz Is there any chance you can retest this with the latest version of Pylance?

There was a change in the last release to the way we handled extraPaths and execution environments, where the default environment is now modified (rather than creating a new environment to have extraPaths). I'm thinking that change may have fixed this behavior.

**Comment by savannahostrowski** [comment]
I'm going to close this issue because it's been open for a long time. If you retest and still experience this behaviour on the newest version of Pylance (2021.4.2), please tag me and I can reopen the issue.

**Comment by SandyChapman** [comment]
I recently hit this issue and in case anyone else stumbles on this problem, my solution was to update my `"pythonVersion"` field in my pyrightconfig.json file to actually match the version that I was using (in my case, it wasn't picking up `StrEnum` because we had the value set to `3.10` instead of `3.11`).
