### ISSUE TITLE
pylance can't recognize defaultdict

### ISSUE THREAD

**Issue by wuyudi** [microsoft/pylance-release#797]
## Environment data

-   Language Server version: pylance v2020.12.2
-   OS and version: win10
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8.5 32bit

## Expected behaviour

It ought to give me `from collections import defaultdict`

## Actual behaviour

![image](https://user-images.githubusercontent.com/30024051/103473051-49672e80-4dcf-11eb-9b01-2d5ab26c17b3.png)

when I click the quick fix, it only gives me

![image](https://user-images.githubusercontent.com/30024051/103473069-6439a300-4dcf-11eb-9a69-a50a843169c6.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
res = defaultdict(int)
```

**Comment by judej** [comment]
Thanks for the report. Could you please try the insiders edition and see if that works? Please see #623 on how to do that. The indexer feature that is in the insiders build should fix this issue.

**Comment by jakebailey** [comment]
It's been over a month since we asked the above and added the "waiting for info" label. If you believe this is still an issue, we can reopen this.

I believe this is fixed when the indexer is enabled, i.e. with the hidden setting `"python.analysis.indexing": true` (or some insiders builds as noted above, though that is not guaranteed).

**Comment by asukaminato0721** [comment]
![Image](https://github.com/user-attachments/assets/4bd73d93-9ff3-46db-bb08-e5d465a8ad59)

fixed.
