### ISSUE TITLE
Django code navigation using strings

### ISSUE THREAD

**Issue by casab** [microsoft/pylance-release#836]
Add code navigation and auto-complete when writing Django models/views/modules as strings.

Typical Django development includes writing the name of many objects in string such as;
```python
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]
```
Or as in
```python

class Reporter(models.Model): ...

class Article(models.Model):
    reporter = models.ForeignKey("app_name.Reporter", on_delete=models.CASCADE)
```
Pycharm with Django plugin seems to handle this pretty well by providing code navigation, type hints, and auto-complete when typing a string.

**Comment by southwood** [comment]
I just hit this too - I think the bundled stub definitions are outdated or incorrect.

`.vscode-server/extensions/ms-python.vscode-pylance-2021.1.1/dist/bundled/stubs`

Switching back to `"python.languageServer": "Microsoft"` fixed it.

It would be nice to keep using Pylance without the stubs tho - is there any way to remove the stubs so that pylance reads sources instead? If not I'd like to request a feature where we can fully disable the use of stubs. This will keep happening any time backing packages are updated.

**Comment by jakebailey** [comment]
The original issue is titled for code navigation, but the issue seems to be intending to suggest the strings on that array, which is a bit different.

The stubs are up to date and come from [this repo](https://github.com/typeddjango/django-stubs). This kind of string-based behavior is not a part of the typical python type system and a static analyzer may not figure out. Maybe part of the mypy plugin they use helps in terms of type checking, but type checkers typically do not offer editor features (pylance/pyright are different in that they power editors).

Reading the sources would be worse; any analysis we're doing is type analysis and reading the original source will provide less information (as django is written with a lot of dynamic behavior in mind), and wouldn't offer the string completion for that list.

I'm not sure what aspect of this switching to "Microsoft" is fixing, though. It has no knowledge of this dynamic behavior either and would not be providing code completions for that list. What differences are you seeing? Can you give an example?

**Comment by southwood** [comment]
Maybe my issue is separate, sounds like it could have a similar root cause. I first noticed here with `AsyncClient`:

- https://github.com/typeddjango/django-stubs/blob/2a732fd2573bcddabb7dc284467481b040d26944/django-stubs/test/__init__.pyi
- https://github.com/django/django/blob/master/django/test/__init__.py#L4

But then realized a few other things were also not picked up correctly by pylance. Switching the language server fixed it.
