### ISSUE TITLE
Pylance deactivate and I lose Go to Definition. 

### ISSUE THREAD

**Issue by tchaton** [microsoft/pylance-release#841]
Dear people from PyLance.

Here is my settings.json
```
{
    "python.pythonPath": ".venv/bin/python",
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.languageServer": "Pylance",
    "python.linting.pylintEnabled": true,
    "python.linting.pylintArgs": [
        "--enable=W0614"
    ]
}
```

For some reason, Pylance deactivate and I have no idea how to put it back. Tried to re-install, reload, etc.. nothing works.

**Comment by jakebailey** [comment]
You seem to have used the question template rather than the bug template; can you provide info about what version of VS Code you have, pylance version, logs from the Python extension, the language server output, etc? Do other features work or does everything break? There isn't much to go off of here.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
It's been a month since this was opened and I asked for more info; we can reopen this if needed but without some more info as requested in our template or troubleshooting, there isn't anything we can do to investigate.
