### ISSUE TITLE
Type hinting through docstrings

### ISSUE THREAD

**Issue by keenfoong** [microsoft/pylance-release#854]
Hi, not sure if this is possible, but I'm attempting to get type hinting defined through docstrings, specifically the Sphinx docstrings. I'm coming from PyCharm and defining the type through the docstring works wonderfully there:

Pycharm: (It works here)
![pycharm](https://user-images.githubusercontent.com/31301148/105125772-47bc9b00-5b31-11eb-95b6-9e43ec5b8f6b.gif)

While here it is in VS Code (All extensions disabled):
![vscode_2](https://user-images.githubusercontent.com/31301148/105125793-5440f380-5b31-11eb-8a5b-647d3bf1d3e0.gif)

As you can see a_var doesn't appear at all here.

Any idea on how to get this to work?

**Comment by judej** [comment]
Have you tried annotating the parameters on the function signature? Would that be an option?

**Comment by keenfoong** [comment]
Unfortunately no, I'm using Maya which is stuck on 2.7x for a while yet. I can use the type annotations in comments as a work around like so

```python
def method(self, aparam): # type: (A) -> None
    pass
```

But the # type annotation doesn't work for non-imported modules unlike PyCharm. For example:

```python
# This is pycharm, even if zoo.ui.ZooWindow hasn't been imported, parent autocompletes properly
class ToolWindow(object):
    def __init__(self, parent):
        """ Initialize

        :param parent: The parent window
        :type parent: zoo.ui.ZooWindow
        """
```
zoo.ui.ZooWindow has not been imported but parent shows everything in ZooWindow because it is in the same workspace in PyCharm.

**Comment by jakebailey** [comment]
Type comments are a bit underspecified. When we process them, we treat them as annotations and as such need to have `zoo` in scope such that we know what it refers to. If you import `zoo.ui`, then we'll know what the annotation refers to and will be able to process it. Otherwise, it's ambiguous and we aren't in the business of trying to guess as to what `zoo.ui` is. Maybe it's obvious in this case that it's a module, but maybe it came from `from foo import zoo`, or is a class, etc.

**Comment by keenfoong** [comment]
I think it would be specific enough though. The `zoo.ui.Window` module sits as an absolute python path relative to the root directory. So `zoo` sits in the source root directory. If the paths are defined in `python.autoComplete.extraPaths`, I think it's fair to say that we know where `zoo` came from. 

Would be great for people coming from PyCharm, as people in my team has expressed concerns for me using vs code as opposed to PyCharm since I may not keep up with the specs of our Sphinx documentation. So it would be great, even as a setting that you could toggle.

**Comment by keenfoong** [comment]
Any update on this? Is this a feature that will happen at any point? Would be great to have, pretty much the main reason why I'm stuck on PyCharm is this feature.

**Comment by jakebailey** [comment]
Our view on this hasn't changed, no, and this issue hasn't gotten much traction. As a point of comparison, JS has JSDoc with type comments to use as an alternative to TypeScript (and the TS analysis can make use of them; they are well specified), but Python has type annotations already built into the language, which is superior.

I guess I'm still not seeing why you'd want to be using docstrings for this; IIRC sphinx is happy to generate docs from the type annotations, and type annotations have wide type-checker support and can be the one source of truth to fully replace the comments.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by skewballfox** [comment]
> I guess I'm still not seeing why you'd want to be using docstrings for this 

It's not just for users coming from pycharm, it's for user using code written in pycharm.

Is it preferable, no. The primary argument I can make is that it's occasionally necessary for handling libraries which aren't ours to control, that were written in this style(and probably written using pycharm).

**Comment by e-sp** [comment]
Libraries like [disnake](https://github.com/DisnakeDev/disnake) simply work correctly in PyCharm. They use this kind of annotations for type hinting and have probably been written with PyCharm. They've admittedly use even a bit more magic. Using those with VSCode is uncomfortable, as using them requires to cast to the right types manually. The same is true for libraries like [pyrogram](https://github.com/pyrogram/pyrogram).

Despite this issue might not get a lot of traction, I'm sure users simply go to use the tool that works best for them, instead of researching why it doesn't work and providing a detailed report about it. 

As I also don't know for sure if the type of documentation/type hinting is the real cause here or not. But I'm certain about users using the tools that work for them, especially when there's a free version available.

**Comment by Bladieblah** [comment]
I fully agree with @henridb's comment, people should just use proper type annotations but sometimes libraries simply don't because this is not a perfect world. Example: this piece of junk: https://github.com/kubernetes-client/python 

Supporting return types in docstrings would simply make lives easier.

**Comment by skewballfox** [comment]
@jakebailey Is this something your team would be open to PRs for? the last few commentators summed up why it would be a useful addition fairly well.

**Comment by rchiodo** [comment]
Pyright (where most of this code is located) is open for PRs, but I'd hazard a guess that you'd need to make a PEP describing in detail how types from docstrings apply first (as Pyright attempts to follow the [Python Typing Spec](https://typing.readthedocs.io/en/latest/spec/index.html) to the letter).
