### ISSUE TITLE
Class imported from same-named module in __init__.py is marked as Module instead of Class

### ISSUE THREAD

**Issue by vishwa-raj** [microsoft/pylance-release#867]
<h3> Environment data </h3>

-   Language Server version: 2021.1.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.typeCheckingMode: strict

<h3> Actual behaviour </h3>

In the following example:
1. In Class_B.py, `Class_A` is  correctly marked as class (red) in `from .Class_A import .Class_A.`
2. But in __init__.py, `Class_B` is marked as module in ```from .Class_B import Class_A, Class_B``` 

![image](https://user-images.githubusercontent.com/22815753/105500162-7fba0e80-5ce8-11eb-975b-6b90af85e517.png)

**Comment by erictraut** [comment]
Thanks for the bug report.

This is a bit of an edge case in Python. The symbol `Class_B` is both a module and a class in this file. That's because there's a special-case rule in the loader for imports of the form `from .A import B` if that import is within an "__init__.py" file. In this case, the local symbol `A` is assigned the module object. In the case of `from .A import A`, that local symbol is then immediately overwritten with the value of the imported symbol. So technically, `A` in this context is both a module and a class. The hover provider currently uses the first declaration to display the type of a symbol. That works best in most cases, but it's not great in this case. I've added some special-case logic to handle this particular situation better.

**Comment by vishwa-raj** [comment]
@erictraut Thanks. Looking forward to the fix.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.1.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202113-27-january-2021
