### ISSUE TITLE
Cannot access member XXX of type "object"

### ISSUE THREAD

**Issue by albireox** [microsoft/pylance-release#880]
## Environment data

-   Language Server version: pylance 2021.1.2
-   OS and version: macOS 22.1
-   Python version (& distribution if applicable, e.g. Anaconda): pyenv 3.9.1

## Actual behaviour

The following snippet of code

```python
done_commands = await asyncio.gather(*commands)
if not all([cmd.succeeded() for cmd in done_commands]):
    for cmd in done_commands:
        if not cmd.succeeded():
            raise ArchonError(f"Failed sending line {cmd.raw!r}")

```

raises errors `Cannot access member XXX of type "object"` on `.raw` and `.succeeded()`. `commands` is a `List[ArchonCommand]`, and `done_commands` is correctly assigned a type `Tuple[ArchonCommand]`. In the loop, `cmd` is correctly assigned type `ArchonCommand`. The class `ArchonCommand` does have the members `.raw` and `.succeeded`.

**Comment by erictraut** [comment]
Could you please provide a full, self-contained source sample? I don't know where the symbol `ArchonCommand` is being imported from. Also, please specify whether you're using type stubs for this package.

**Comment by albireox** [comment]
This seems to be a complete example that causes the problem.

```python
import asyncio
import sys

if sys.version_info >= (3, 9):
    FutureType = asyncio.Future["ArchonCommand"]
else:
    FutureType = asyncio.Future

class ArchonCommand(FutureType):
    def __init__(self, cmd_str: str):
        super().__init__()
        self.cmd_str = cmd_str
        self.set_result(self)

    @property
    def raw(self):
        return self.cmd_str

    def succeeded(self):
        return True


async def main():
    commands: list[ArchonCommand] = []
    commands += [ArchonCommand("hello"), ArchonCommand("world")]
    done_commands = await asyncio.gather(*commands)
    if not all([cmd.succeeded() for cmd in done_commands]):
        for cmd in done_commands:
            if not cmd.succeeded():
                raise ValueError(f"Failed sending line {cmd.raw!r}")
```

Apparently the issue is with

```python
FutureType = asyncio.Future["ArchonCommand"]
```

If I do `class ArchonCommand(asyncio.Future["ArchonCommand"]):` then `pyright` doesn't issue any error.

**Comment by erictraut** [comment]
The problem here is that the type alias `FutureType` refers to the type `ArchonCommand` which is defined in terms of `FutureType`. You have a cyclical definition that pyright is not able to resolve. I confirmed that mypy (another type checker) also emits an error in this case.

Pyright does have some special-case logic to deal with cyclical definitions in a limited form — in particular, if the cycle is contained within the class declaration itself. That's why it works when you do `class ArchonCommand(asyncio.Future["ArchonCommand"]):`.

It's unfortunate that versions of Python prior to 3.9 generate a runtime exception when you subscript the `asyncio.Future` type.

Here are some other potential workarounds:
1. Use `asyncio.Future[Any]`
2. Consider ways to refactor your code so ArchonCommand doesn't derive from a future of itself

**Comment by albireox** [comment]
Hi @erictraut,

Thanks for the explanation. Using `asyncio.Future[Any]` certainly does work and it seems it doesn't prevent me from annotating output variables with `tuple[ArchonCommand]`. So, while it breaks the automatic type inference, it's a workaround until I can restrict the version to 3.9+.

**Comment by jakebailey** [comment]
This issue has been open with the "waiting for info" label for over a month, so I'm going to close it. I don't know if there's any work to be done here.

**Comment by albireox** [comment]
Yes, sorry, this could have been closed then, it was already answered.
