### ISSUE TITLE
reportUndefinedVariable for recursive class/method

### ISSUE THREAD

**Issue by amogorkon** [microsoft/pylance-release#898]
Hello,

I have a class which has a method which returns a list of instances of itself, which pylance doesn't recognize as such. Here is a minimal example:

```
class Task:
    def __init__(self, requires: Task):
        self.requires = requires

    def requires(self) -> list[Task]:
        return [self.requires]
```

which gives me "'Task' is not defined" with the mentioned Exception.

**Comment by erictraut** [comment]
If you try running your sample in the Python interpreter, you will receive a runtime exception "NameError: 'Task' is not defined". That's because you're using the `Task` annotation within the class itself.

There are two ways to work around this:
1. Add `from __future__ import annotations` to the top of your source file. This tells the interpreter to defer its evaluation of annotations. (It's a "future" feature in that this will be the default behavior in a future version of Python.)
2. Enclose `Task` in quotes. This is the approach documented in PEP 484 for annotations that use forward references.
