### ISSUE TITLE
Using pylance with pytest.raises

### ISSUE THREAD

**Issue by Kylebrown9** [microsoft/pylance-release#915]
I'm looking for a way to use pylance with `pytest.raises` without getting undesirable error diagnostics.

Here is a minimal example of the two error diagnostics I don't want to see.

```python
class FooBar:
    def __init__(self, name: str):
        if not isinstance(name, str):
            raise ValueError('FooBar names must be strs')
        
        self.name: str = name

def test_foobar():
    with pytest.raises(ValueError): # issue 1
        a = FooBar(1) # issue 2
```

# Issue 1
It appears that `pytest.raises` is inferred to return `RaisesContext | ExceptionInfo` and since `ExceptionInfo` is not a valid context manager pylance will tell me that this is bad.
> Object of type "ExceptionInfo" cannot be used with "with" because it does not implement __enter__

# Issue 2
In this case pylance is completely correct, but also completely unhelpful.
I am deliberately checking that doing this the wrong way does what I intend.
> Argument of type "Literal[1]" cannot be assigned to parameter "name" of type "str" in function "__init__"

**Comment by erictraut** [comment]
Which version of the pytest package are you using? With the latest version, I'm not able to repro the first issue. I suspect it has been fixed in the pytest code.

For the second case, that is expected behavior. The type checker is telling you that you are passing a value that does not match the declared type. There are a few options here:
1. If `FooBar` is a mocked type, you can define its constructor signature to take an `object` rather than `str`, since you're testing that it behaves correctly when sending in values other than `str`.
2. If `FooBar` is the real type you're testing, then you can suppress the errors that the type checker finds in your tests by using `# type: ignore` comments. Or you can suppress classes of errors in the file using a `# pyright: reportGeneralTypeIssues=false` comment at the top of the file.

**Comment by Kylebrown9** [comment]
I was able to solve issue 1 by updating pytest (to 6.2.2) as you suggested.
For issue 2, I am in the second case and the file-level suppression is a sufficient solution.
Thanks!

**Comment by eklunko** [comment]
Given pytest 8.3.2 and pyright 1.1.377 I have "Issue 1" pyright errors today:
Object of type "ExceptionInfo" cannot be used with "with" because it does not implement __enter__

**Comment by rchiodo** [comment]
> Given pytest 8.3.2 and pyright 1.1.377 I have "Issue 1" pyright errors today: Object of type "ExceptionInfo" cannot be used with "with" because it does not implement **enter**

@eklunko, I recommend entering a new issue on Pyright. I can't reproduce your problem with pytest 8.3.2 and this code here:

```
class FooBar:
    def __init__(self, name: str):
        if not isinstance(name, str):
            raise ValueError('FooBar names must be strs')
        
        self.name: str = name

def test_foobar():
    with pytest.raises(ValueError): # works fine
        a = FooBar("1")
```

**Comment by eklunko** [comment]
> @eklunko, I recommend entering a new issue on Pyright. I can't reproduce your problem with pytest 8.3.2 and this code here:

There might be a difference in how pyright and pylance process this code.
You're right, I should open a new issue. Thank you!
