### ISSUE TITLE
PEP 585 errors should always be enabled

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#916]
<h3> Environment data </h3>

-   Language Server version: 2021.2.0
-   OS and version: darwin x64
-   Python version: **3.8**
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off / basic

<h3> Expected behaviour </h3>

PEP 585 errors should always be enabled, even if `typeCheckingMode: off`. Similar to how PEP 604 errors are handled.

<h3> Actual behaviour </h3>

**typeCheckingMode: off**
Only PEP 604 errors are shown.

![Screen Shot 2021-02-04 at 23 16 48](https://user-images.githubusercontent.com/30130371/106962576-9d9f5e80-673f-11eb-9bb0-51c5141d597d.png)

**typeCheckingMode: basic**

![Screen Shot 2021-02-04 at 23 17 33](https://user-images.githubusercontent.com/30130371/106962654-b7d93c80-673f-11eb-9ccd-4c64b4d1cb3d.png)

<h3> Logs </h3>

--

<h3> Code Snippet / Additional information </h3>

```py
var1: list[int]

var2: int | str
```

**Comment by erictraut** [comment]
Generally, we display parser errors unconditionally, but semantic errors that depend on type information are controlled by the `reportGeneralTypeIssues` diagnostic rule, which is off by default when typeCheckingMode is "off". We want to avoid showing any type-related errors that are potentially false positives when type checking is disabled.

In this particular case, I think an exception to this rule may be justified because the types in question are builtin types, and I can't think of any circumstance under which we'd generate a false positive error.

@jakebailey do you agree with that assessment?

**Comment by jakebailey** [comment]
I agree in general. Syntax errors are definite, but I am trying to think of some false positives. I suppose that this is no worse than getting an operand of `|` wrong, as it too requires type analysis, right? I'd think we are more likely to infer things as instance types and then hide the error than we are to infer variables to types themselves and then throw this error even in `off` mode...

**Comment by erictraut** [comment]
Thanks for the suggestion. This will be addressed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.2.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202121-10-february-2021
