### ISSUE TITLE
Statements passed in mypy but failed in pylance.

### ISSUE THREAD

**Issue by TheNightmareX** [microsoft/pylance-release#927]
## Environment data

-   Language Server version: 2021.2.0 (pyright e278f28d)
-   OS and version: Windows 10 Work Station 1909
-   Python version: Python 3.9.0 64-bit

## Actual behaviour

```Python
from typing import Protocol


class Base:
    ...


class Sub(Base):
    ...


class AClass:
    class Meta(Protocol):
        attr: dict[str, type[Base]] = {'str': Sub}


class SubOfAClass(AClass):
    class Meta:
        attr = {'str': Sub}
    """
    (variable) attr: dict[str, Type[Sub]]
    "Meta" overrides symbol of same name in class "AClass"
      Type "Type[Meta]" cannot be assigned to type "Type[Meta]"
        "attr" is an incompatible type
          TypeVar "_VT@dict" is invariant
            "Sub" is incompatible with "Base"PylancereportIncompatibleVariableOverride
    test.py(13, 11): Overridden symbol
    """
```

**Comment by erictraut** [comment]
I presume that you have enabled "strict" type checking mode because the "reportIncompatibleVariableOverride" diagnostic rule is disabled by default in "basic" type checking mode. 

The problem is that you have not declared the type of `attr` with the second declaration of `Meta`, so its type is inferred from its assignment. In this case, the inferred type is `dict[str, type[Sub]]`. The type parameters for the `dict` class are invariant so a `type[Sub]` is not compatible with `type[Base]`.

You have several options:
1. Add a type annotation to `attr` in the second `Meta` class:
```python
        attr: dict[str, type[Base]] = {"str": Sub}
```

2. Change the annotation for `attr` in the first `Meta` class to a `Mapping` rather than a `dict`:
```python
        attr: Mapping[str, type[Base]] = {"str": Sub}
```

3. You can disable the `reportIncompatibleVariableOverride" rule for this file using a `# pyright: reportIncompatibleVariableOverride=false` comment at the top. Or disable it for your entire project in the settings.

**Comment by TheNightmareX** [comment]
> I presume that you have enabled "strict" type checking mode because the "reportIncompatibleVariableOverride" diagnostic rule is disabled by default in "basic" type checking mode.
> 
> The problem is that you have not declared the type of `attr` with the second declaration of `Meta`, so its type is inferred from its assignment. In this case, the inferred type is `dict[str, type[Sub]]`. The type parameters for the `dict` class are invariant so a `type[Sub]` is not compatible with `type[Base]`.
> 
> You have several options:
> 
> 1. Add a type annotation to `attr` in the second `Meta` class:
> 
> ```python
>         attr: dict[str, type[Base]] = {"str": Sub}
> ```
> 
> 1. Change the annotation for `attr` in the first `Meta` class to a `Mapping` rather than a `dict`:
> 
> ```python
>         attr: Mapping[str, type[Base]] = {"str": Sub}
> ```
> 
> 1. You can disable the `reportIncompatibleVariableOverride" rule for this file using a `# pyright: reportIncompatibleVariableOverride=false` comment at the top. Or disable it for your entire project in the settings.

Thanks.
