### ISSUE TITLE
Do not show 'Literal' in tooltips

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#928]
I suggest to not show 'Literal' in tooltips, or at least add the option to disable them and show the underlying non-Literal type.

Current:
![image](https://user-images.githubusercontent.com/5028956/107287145-33056000-6a6a-11eb-9eca-d85985ed5228.png)
Suggested:
![image](https://user-images.githubusercontent.com/5028956/107287674-f25a1680-6a6a-11eb-9783-d40b862a2888.png)

The information about the literal value is unneeded to me and at times confusing. I just want the type when I hover. Was it a conscious decision to put Literal in the tooltip or just a side effect of supporting Literals? Can pyright un-narrow the type back to its non-Literal value, just for displaying in the tooltip?

Note that if I hold down the Cmd key, I can already see the literal value anyway.
![image](https://user-images.githubusercontent.com/5028956/107287729-056ce680-6a6b-11eb-8aa3-523ba88f3fdb.png)
(Admittedly not in all cases of Literal the value would be shown this way.)

**Comment by erictraut** [comment]
For developers who are interested in type checking, displaying the actual type (which includes the literal value) is important. I presume that you have not enabled type checking (i.e. you've left the value of the "python.analysis.typeCheckingMode" to its default "off"). Is that a correct assumption?

We'll need to discuss your suggestion and get back to you. In general, we try to avoid changing the behavior when type checking is off vs on, but we have made a few exceptions to this rule when it comes to displaying types in hover text or error messages. So adopting your suggestion would not be unprecedented.

**Comment by matangover** [comment]
Thanks for your prompt answer! In fact I am very interested in type checking and I have typeCheckingMode on.

**Comment by jakebailey** [comment]
The only heuristic I can imagine here would be to hide Literals unless they are inside of another type being printed (e.g., inside of a function overload, a tuple, etc.).

**Comment by erictraut** [comment]
If you have type checking enabled, then I think it's important to display the type without "sanitizing" it. Otherwise it will lead to apparent inconsistencies and make it difficult to diagnose type-related errors. If the type evaluator knows that a value contains a literal value at a certain place within the code flow, you should be able to see that in the type information presented in the hover text.

**Comment by matangover** [comment]
There is merit to that, I agree. I just think that in 90% of the cases it is not useful and mildly confusing (especially for users who don't understand the internals of the type system and don't know what Literal is), and suggest adding an option to disable it.

**Comment by hoechenberger** [comment]
An alternative could be to simply display the type and current value, omitting the `Literal`?

**Comment by jakebailey** [comment]
I don't quite know what you mean; isn't that what `Literal` is, the current value (where the type is inferred from what the literal says)?

**Comment by erictraut** [comment]
It would be incorrect to think of this as the "current value". It's the "current type". It's a subtle but important distinction. For example, the type might be `Literal[1, 2, 3, "a"]`.

**Comment by hoechenberger** [comment]
I absolutely agree with you and I do like the current behavior. I was just trying to figure out a potential compromise with @matangover 😊 Thanks for taking your time to respond and explain the background!

**Comment by CodeCrazy-ywt** [comment]
My suggestions:
when the user uses type hinting to declare the `Literal[...]`  , then show `Literal[...]`. Otherwise don't. e.g.
```python
foo = 1  # show "foo: int" or "foo = 1" or "foo: int = 1"
bar: Literal['yes', no'] = 'yes'  # show "bar: Literal['yes', 'no']"
def func(x: Literal[0, 1]):
    x  # show "x: Literal[0, 1]"

**Comment by CodeCrazy-ywt** [comment]
My suggestions:
when the user uses type hinting to declare the `Literal[...]`  , then show `Literal[...]`. Otherwise don't. e.g.
```python
foo = 1  # show "foo: int" or "foo = 1" or "foo: int = 1"
bar: Literal['yes', no'] = 'yes'  # show "bar: Literal['yes', 'no']"
def func(x: Literal[0, 1]):
    x  # show "x: Literal[0, 1]"
```

**Comment by erictraut** [comment]
Consider the following:
```python
def send_request(action: Literal["POST", "GET"]):
    ...

def func(x: str):
    send_request(x) # Type error

    x = "GET"
    send_request(x) # No type error
```

The first call expression generates a type consistency error whereas the second call expression does not. That's because the assignment expression narrows the type of `x` from `str` to `Literal["GET"]`. Tool tips always display the _current type_ of a symbol (with type narrowing applied) rather than the _declared type_. So if you hover over the first usage of `x`, you'll see `str`. If you hover over the second usage of `x`, you'll see `Literal["GET"]`.

When type checking is enabled, the distinction between types `str` and `Literal["GET"]` is important. Obscuring the fact that the type is a literal would be confusing and make it difficult to understand a certain class of errors.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
