### ISSUE TITLE
Unpacking tuple with asterisk causes "Tuple size mismatch error"

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/pylance-release#930]
## Environment data

-   Pylance: 1.054.404
-   Language Server version: Pylance language server 2021.2.0 (pyright e278f28d)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Expected behaviour

```python
l1: List[int] = [1, 2, 3]
l2: List[str] = ['test', 'test2', 'test3']
res: List[Tuple[int, str]] = list(zip(*[l1, l2]))
```

The return type of `list(zip(*[l1, l2]))` should be List[Tuple[int, str]].

## Actual behaviour

The return type of `list(zip(*[l1, l2]))` is detected as `list[Tuple[Unknown]]`
This results in the following type warning:

> Expression of type "list[Tuple[Unknown]]" cannot be assigned to declared type "List[Tuple[int, str]]"
  TypeVar "_T@list" is invariant
    Tuple size mismatch; expected 2 but received 1 
       Pylance(reportGeneralTypeIssues)

For pyright a similar (same title) issue already existed in the past: https://github.com/microsoft/pyright/issues/627

## Additional failing MWE:

```python
l1: List[int] = [1, 2, 3]
l2: List[str] = ['test', 'test2', 'test3']

def test() -> List[List[Any]]:
    return [l1, l2]

res: List[Tuple[int, str]] = list(zip(*test()))
```

> Expression of type "list[Tuple[Any]]" cannot be assigned to declared type "List[Tuple[int, str]]"
  TypeVar "_T@list" is invariant
    Tuple size mismatch; expected 2 but received 1

**Comment by erictraut** [comment]
The code above is not unpacking a tuple; it's unpacking a list. If you change the operand of the upack operator to a tuple, it will type check as expected.

```python
l1: List[int] = [1, 2, 3]
l2: List[str] = ['test', 'test2', 'test3']
res: List[Tuple[int, str]] = list(zip(*(l1, l2)))
```

Likewise, you can make the second example work as follows:
```python
from typing import List, Tuple

l1: List[int] = [1, 2, 3]
l2: List[str] = ["test", "test2", "test3"]

def test() -> Tuple[List[int], List[str]]:
    return (l1, l2)

res: List[Tuple[int, str]] = list(zip(*test()))
```

Neither of your samples type check within mypy either. If you look at the type signature for `zip` in `builtins.pyi`, you can figure out why.

I think Pyright is doing the right thing here.

**Comment by Spenhouet** [comment]
Thanks for the fast reply. I had a more complicated case. I will check tomorrow if your suggestion also would fix that case.
I will come back to this as soon as possible.

**Comment by Spenhouet** [comment]
@erictraut This does not seem to be sufficient. My MWE was not an appropriate representation of my use-case.

The method implemented is generic and can return any type of list and also any number of lists.

Still trying to give a simplified MWE here:

```python
def test(*args: List[Any]) -> Tuple[List[Any], ...]:
    # Complicated logic here
    return tuple(args)


l1: List[int] = [1, 2, 3]
l2: List[str] = ['test', 'sfd', 'sfds']

res: List[Tuple[int, str]] = list(zip(*test(l1, l2)))
```

The MWE is now returning a Tuple but it is still not working.
The length (number of elements) is dynamic but the parameters supplied are static. So it can be possible to infer that exactly two object are applied.
I would have expected this to work. At least it would be nice. Don't you think?

> Expression of type "list[Tuple[Any]]" cannot be assigned to declared type "List[Tuple[int, str]]"
   TypeVar "_T@list" is invariant
    Tuple size mismatch; expected 2 but received 1

**Comment by erictraut** [comment]
The problem here is that your `test` method is returning an unknown number of `List[Any]` values (as indicated by the `...`). The function `zip` is defined in builtins.pyi using a series of overloads. Each overload uses a different number of input arguments, corresponding to the number of iterables being zipped together. In your sample, the type checker doesn't know how many iterables are being passed to `zip` because of the `...`.

You can see the problem by deconstructing the expression in the last line of your sample:
```python
v1 = test(l1, l2)
reveal_type(v1) # Type of "v1" is "Tuple[List[Any], ...]"
v2 = zip(*v1)
reveal_type(v2) # Type of "v2" is "Iterator[Tuple[Any]]"
v3 = list(v2)
reveal_type(v3) # Type of "v3" is "list[Tuple[Any]]"
res: List[Tuple[int, str]] = v3 # Error: Type "list[Tuple[Any]]" cannot be assigned to type "List[Tuple[int, str]]"
```

If you modify `test` to return a specified number of iterables, the sample will type check:
```python
def test(*args: List[Any]) -> Tuple[List[Any], List[Any]]: ...
```

One potential solution is for you to use overloads in your implementation:
```python
@overload
def test(v1: List[Any]) -> Tuple[List[Any]]:
    ...
@overload
def test(v1: List[Any], v2: List[Any]) -> Tuple[List[Any], List[Any]]:
    ...
@overload
def test(v1: List[Any], v2: List[Any], v3: List[Any]) -> Tuple[List[Any], List[Any], List[Any]]:
    ...
def test(*args: List[Any]) -> Tuple[List[Any], ...]:
    # Complicated logic here
    return tuple(args)
```

**Comment by Spenhouet** [comment]
Thanks for the suggestion. You always learn something new. I actually wasn't aware that method overloading is possible in python. Thanks for that hint.

Nonetheless, I don't think that is reasonable here. For a generic method that can take an unspecified amount of input variables this is just not feasible.

Since the problem here seems to be the implementation of the build-in `zip`, I switched to `itertools.zip_longest` which outputs `Iterable[Any]`. This does resolve the type warning.

```python
from itertools import zip_longest


def test(*args: List[Any]) -> List[List[Any]]:
    # Complicated logic here
    return list(args)


l1: List[int] = [1, 2, 3]
l2: List[str] = ['test1', 'test2', 'test3']

res: List[Tuple[int, str]] = list(zip_longest(*test(l1, l2)))
```

I guess that is a workaround I can live with. I'm going to close this issue. Again, thank you for your time and suggestions!

**Comment by jakebailey** [comment]
@erictraut Is this something that will be improved by variadics? E.g., make `*args` be variadic in the number of lists it takes, then the return type unpacks it into a tuple.

**Comment by erictraut** [comment]
@jakebailey, yeah, kind of. With Python 3.10 and PEP 646, we could define `test` as follows:
```python
_Ts = TypeVarTuple("_Ts")

def test(*args: *_Ts) -> Tuple[*Ts]:
    ...
```
The problem is that `TypeVarTuple`  (at least in the current draft of the PEP) doesn't support `bound`, so there's no way to specify that each parameter passed to `*args` must be a `list` or an `Iterable`. That means the implementation of `test` would need to include some ugly `cast` calls. So it's not great, but it's probably better than what can be done in Python 3.9.

**Comment by jakebailey** [comment]
That's what I feared when I tried to write out an example... I couldn't figure out where the `List` was supposed to go. Darn.

**Comment by erictraut** [comment]
@gvanrossum, @mrahtz, you might find this thread interesting as it pertains to PEP 646.

**Comment by gvanrossum** [comment]
So the crux is that we need TypeVarTuple to take a bound=... argument. Or we could go back to using my proposal, TypeVar(bound=Tuple), because then we could just use bound=Tuple[Iterable, ...] in this example.

**Comment by mrahtz** [comment]
Thanks for the heads up, Eric.

I'd prefer not to add `bound=` to PEP 646 itself because I suspect we might want finer-grained control when using `TypeVarTuple` for array typing (e.g. bounds for individual types in the `TypeVarTuple`), and a) I want to get PEP 646 wrapped up, and b) I'd prefer to wait until we've used `TypeVarTuple` in the wild a bit more before making a decision on this.

What I have done is start a doc [here](https://docs.google.com/document/d/1h3vFD_XElis8ZAwO0CgQeKvvaIifuSClEeTfCpiTCvk/edit) on notes for a potential future PEP detailing how bounds and variance should work for `TypeVarTuple` referencing this issue so we have an example use-case.
