### ISSUE TITLE
Pylance support for Jupyter

### ISSUE THREAD

**Issue by ATIRU-001** [microsoft/pylance-release#942]
Issue Type: <b>Feature Request</b>

It would be great if Pylance would work with Jupyter notebooks.

Extension version: 2021.2.2
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by jakebailey** [comment]
Can you clarify what you mean? The Jupyter extension uses Pylance to offer completions, hovers, etc, already.

**Comment by ATIRU-001** [comment]
It does?
Does the Jupyter or Pylance expansion need to be configurated for it to work?
![image](https://user-images.githubusercontent.com/43970101/107696092-ce3c4680-6cb1-11eb-91ea-bcdf2accca0e.png)

My current notebook doesn't seem to use it, at least not like .py files.

**Comment by jakebailey** [comment]
I know that the Jupyter extension has a few bugs around this that will be fixed in their next release (unsure when that is). It could be that hover is broken.

Can you try performing a completion, like in `pd.` and showing the output? If Pylance is working, the stubs we ship for pandas should mean type info shows in the tooltip that gets generated.

If you enable trace logging, you should also see activity as you perform certain actions in Jupyter.

**Comment by ATIRU-001** [comment]
The completion seems to work, but the hover text and colour coding seems to be broken in Jupyter for now.
![image](https://user-images.githubusercontent.com/43970101/107699654-a8fe0700-6cb6-11eb-981e-36cb55d7af07.png)

**Comment by jakebailey** [comment]
As far as I am aware, to get those features you need to enable their new "native notebooks" preview, where VS Code provides all of the different features natively and things work.

**Comment by ATIRU-001** [comment]
Yea, that seems to have done the trick.
Thank you for the help.
