### ISSUE TITLE
pylance seems to expect a typing syntax for some types such as 'dict' - e.g. x = (dict,)

### ISSUE THREAD

**Issue by PatrickBourdon** [microsoft/pylance-release#944]
## Environment data
-   Windows-10-10.0.18362-SP0
-   python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
-   Visual Code Studio: 1.53.2
-   extension pylance: v2021.2.1
-   type checking mode: strict

## Expected behaviour
x: tuple[type] = (dict,) -> no problem
y: tuple[type] = (dict[str, str],) -> a problem

## Actual behaviour
The exact reverse.
But maybe my expectations are wrong.
Thank you for your great tool!

## Code Snippet / Additional information
```python
import re
import typing

x: tuple[type] = (dict,)
    # pylance reports a problem: reportUnknownVariableType
    #   Type of "x" is partially unknown
    #       Type of "x" is "tuple[Type[dict[Unknown, Unknown]]]"
print(type(x[0]))
    # output is: <class 'type'>

y: tuple[type] = (dict[str, str],)
    # Here pylance does not report a problem.
    # But the created variable is quite different and cannot be used in e.g. isinstance(myvar, y)
print(type(y[0]))
    # output is: <class 'types.GenericAlias'>

# pylance also reports the problem for types such as 'list', 're.Pattern', 'collections.Counter', but not for 'tuple' and 'set'

# Is there a proper way to avoid the problem? Without hiding it such as: 

z = typing.cast(tuple[type], (dict,))
t: tuple[type] = (dict,) # type: ignore
w: typing.Any = (dict,) # A local bandage, since it will reappear later when w is argument of a function expecting a tuple[type, ...] parameter  

# Pattern behaves more strangely:

a: typing.Any = 'x'
b = isinstance(a, re.Pattern)
    # pylance reports a problem: reportUnknownMemberType
    #   Type of "Pattern" is partially unknown
    #       Type of "Pattern" is "Type[Pattern[Unknown]]"

c = isinstance(a, typing.Pattern)
    # pylance reports a problem: reportUnknownMemberType
    #   Type of "Pattern" is partially unknown
    #       Type of "Pattern" is "Type[Pattern[Unknown]]"

from typing import Pattern
d = isinstance(a, Pattern)
    # but surprisingly not here.

e = isinstance(a, re.Pattern[str])
    # Neither here, where execution fails:
    #   Traceback (most recent call last):
    #       File "test-typing.py", line 76, in <module>
    #           e = bool(isinstance(a, re.Pattern[str]))
    #   TypeError: isinstance() argument 2 cannot be a parameterized generic    

```

**Comment by jakebailey** [comment]
I'm a bit confused by your expectations.

```python
x: tuple[type] = (dict,) -> no problem
```

In the above, this is "fine", but you appear to be in strict mode, so it's telling you that you have `dict` (which is generic) and have not specified its type vars, so they are inferred as "Unknown" and a warning appears. I believe that in basic mode, this code would type check without error. Strict is more strict about this.

```python
y: tuple[type] = (dict[str, str],) -> a problem
```

In the above, why is there a problem in this case? This is a type, and in newer versions of python, `dict` is subscritable just like `typing.Dict` (as the intent is for everyone to start using the builtin types).

The same goes for the other types; in strict mode, we warn about "Unknown", and those types are generic. I can see how `isinstance(a, re.Pattern)` may be odd, though, since that's a real class, but I think this is to be expected in strict mode.

**Comment by PatrickBourdon** [comment]
Let's try this way:
I am adding 'types' to a bunch of python code lines.
'strict mode' generates a lot of pylance problems that I am progressively solving. 
I discover real bugs that I am fixing too: this is the actual goal together with improving future maintenance.

Let's start with these non-typed 3 lines:
```python
def check(v, t):
    return isinstance(v, t)
b = check('x', (dict,))
```
The function becomes:
```python
def check(v: typing.Any, t: tuple[type, ...]) -> bool:
    return isinstance(v, t)
```
but pylance reports UnknownArgumentType (not in basic mode) with this:
```python
b = check('x', (dict,)) 
```
and python fails with this: 
```python
b = check('x', (dict[str, str],))
```
However I know that I can put dust under the carpet with this:   
```python
b = check1('x', (dict,)) # type: ignore
```
I understand from your answer that there is no bug in here.
So what is the correct way to solve the pylance problem and that does not make python fail?
Do you mean I have to wait for newer versions of python (3.10)?

**Comment by jakebailey** [comment]
I see, yes, to be able to subscript I think you may need 3.10 (I had thought 3.9 was sufficient).

I can see how trying to use types in isinstance calls and seeing the Unknown type warning is a little strange. @erictraut may have a better piece of guidance when he is around.

This isn't totally related, but `check` would be cleanly represented with a TypeGuard (likely coming in 3.10 too: https://www.python.org/dev/peps/pep-0647/), but that doesn't address the Unknown messages.

**Comment by erictraut** [comment]
Yeah, it's unfortunate that `isinstance` doesn't support subscripted forms. I specifically disable the `reportUnknownVariableType` check for the second argument passed to `isinstance`. That approach doesn't work in your code because you're not passing `dict` directly as an argument; you're instead adding it to a tuple and iterating over that tuple when calling `isinstance`.

Here are the options I can suggest:
1. Use a different pattern within your code so you don't use a tuple of generic types.
2. Disable the `reportUnknownVariableType` by adding a comment to the top of this source file: `# pyright: reportUnknownVariableType=false`
3. Disable the diagnostics on specific lines using `# type: ignore`.
4. Disable strict type checking mode.

**Comment by erictraut** [comment]
I just noticed that your example demonstrates that you're seeing the problem for `isinstance` when you pass `Pattern` as the second argument. That looks like a bug to me. I'll investigate further.

I also noticed in your comments that the "missing type arguments" diagnostic is not appearing for `tuple` and `set`. That's another apparent bug that needs investigation.

**Comment by PatrickBourdon** [comment]
The answer suits me very well
Thanks to both of you.
