### ISSUE TITLE
Pylance type resolution for base class and derived classes does not seem to be working

### ISSUE THREAD

**Issue by smeznaric** [microsoft/pylance-release#955]
```
from typing import List


class BaseClass(object):
    def what_am_i(self):
        return "BaseClass"


class Derived(BaseClass):
    def what_am_i(self):
        return "Derived"


def some_func(class_list: List[BaseClass]) -> List[str]:
    return [x.what_am_i() for x in class_list]


some_list = [Derived()]
some_func(some_list) #Not OK


some_base_list = [BaseClass()]
some_func(some_base_list) #OK

some_mixed_list = [BaseClass(), Derived()]
some_func(some_mixed_list) #OK

some_mixed_list = [Derived(), BaseClass()]
some_func(some_mixed_list) #OK

some_mixed_list = [Derived(), Derived()]
some_func(some_mixed_list) #Not OK

some_func([Derived()]) #OK
```

As above, it seems to correctly recognise some of the cases but not others. In particular it seems to encounter an issue when a variable is involved where all of the instances in the list are of a derived type. I have type checking set to basic.

It displays the following message:
Argument of type "list[Derived]" cannot be assigned to parameter "class_list" of type "List[BaseClass]" in function "some_func"
  TypeVar "_T@list" is invariant
    "Derived" is incompatible with "BaseClass"PylancereportGeneralTypeIssues

**Comment by erictraut** [comment]
The errors are due to the fact that the input parameter for `some_func` is annotated as a `List`. Lists are mutable, and their type arguments are therefore invariant. If a function is expecting a `List[int]`, you can't provide an argument of type `List[float]` even though `float` is a subtype of `int`. The same thing is true in your example above. For more details about this, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#generic-types).

You can avoid the type errors by changing the `List[BaseClass]` to `Sequence[BaseClass]`. Sequences are immutable, and their type arguments are covariant.

**Comment by smeznaric** [comment]
I am still a bit confused as to why in some cases (like some_mixed_list = [Derived(), BaseClass()]) it doesn't seem to flag an issue but in others (like some_mixed_list=[Derived(), Derived()]) it does.

I can see from the example in the documentation that the issue is that a variable's declared type could be changed later on in the code due to mutability, thus no longer respecting the type. I am a bit confused about why this is an issue with function arguments though.

**Comment by erictraut** [comment]
If you hover over `some_mixed_list`, you'll see why. Pylance is inferring its type to be `List[Any]`. That's because the types of the elements in the list are heterogeneous. To learn more about how pylance/pyright infer the types of list expressions, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#list-expressions).

**Comment by erictraut** [comment]
If you enable "strict list inference", you will see more errors reported. You can do this by adding the following line to the top of your source file:
```python
# pyright: strictListInference=true
```

**Comment by smeznaric** [comment]
OK, I see, so it's more lenient when it infers List[Unknown], because it assumes Unknown could be the type we want. But I still don't understand why it triggers at all given that mutability is, as far as I understand, not going to affect what you're passing as a function argument. Otherwise why would you expect that this works fine?

```
some_mixed_list:` List[BaseClass] = [Derived(), Derived()]
some_func(some_mixed_list)
```

**Comment by smeznaric** [comment]
@erictraut On reflection I realize now what you were trying to tell me with the "mutable" vs "immutable". I am starting to understand why this works the way it does. My apologies, I am not a computer scientist and it took me some time to figure this out.
