### ISSUE TITLE
SupportsRound does not seem to work

### ISSUE THREAD

**Issue by hudcap** [microsoft/pylance-release#958]
## Environment data

-   Language Server version: 2021.2.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1

## Expected behaviour

I have a custom number class that overrides `__round__` (among other methods) to return my custom class. When I use `round` on an instance of my class, it correctly returns another instance of said class and should be considered as such by `pylance`.

I included a MWE below.

## Actual behaviour

`pylance` error reported:
```
Expression of type "float" cannot be assigned to declared type "MyNumber"
  "float" is incompatible with "MyNumber"
```

## Logs

I don't think this is relevant, but I can add if necessary.

## Code Snippet / Additional information

I'm not sure if the `SupportsRound["MyNumber"]` should even be necessary, but I get the error both with and without it. I can't rule out that I'm doing something wrong, but google has yielded close to nothing on this topic...

```python
from typing import SupportsRound


class MyNumber(float, SupportsRound["MyNumber"]):
    def __new__(cls, value: float):
        return super().__new__(cls, value)

    def __round__(self, ndigits: int = 0):
        return MyNumber(super().__round__(ndigits))


n: MyNumber = round(MyNumber(3.14), 0) # pylance error here

assert isinstance(n, MyNumber) # no problem here
```

**Comment by erictraut** [comment]
The problem here is that `MyNumber` inherits from `float`, so it is matching on this overload for `round`:
```python
@overload
def round(number: float, ndigits: int) -> float: ...
```

You were expecting it to match on this overload, which is below:
```python
@overload
def round(number: SupportsRound[_T], ndigits: None) -> int: ...
```

But overloads are evaluated in the order they were declared, so it's correct for pyright to select the first one.

One potential workaround:

```python
class MyNumber(SupportsRound["MyNumber"]):
    def __init__(self, value: float):
        self._value = value

    def __round__(self, ndigits: int = 0):
        return MyNumber(round(self._value, ndigits))

    def __float__(self):
        return self._value
```

**Comment by hudcap** [comment]
Ah, I see what you mean. I have to think about whether I really need to inherit from `float`...  
Thank you!

I think I was expecting it to match this one:

```python
@overload
def round(number: SupportsRound[_T], ndigits: int) -> _T: ...
```

I'm assuming that order of overloads is specific?
I can't reason out the logic that would dictate the order...

**Comment by erictraut** [comment]
Yes, the ordering of overloads is sometimes very important. Other times it's not. 

Arguably, the first of the two overloads (the one with the `float`) is unnecessary because the `float` class implements the `SupportsRound` protocol. So maybe the right answer here is to delete the unnecessary one. If you'd like, you could file a bug (or a PR) in the typeshed repo. That's the source of the stdlib type stubs that we ship with Pyright and Pylance.

**Comment by jakebailey** [comment]
Given this is in typeshed, there's not really much we can do here; we're just following the stubs. I'll close this, but feel free to cross link this if you do open a bug or PR.
