### ISSUE TITLE
Union Type not correctly resolved

### ISSUE THREAD

**Issue by hanpari** [microsoft/pylance-release#966]
This is the code in question:

```python

from typing import Generic, Optional, TypeVar, Union, cast

T = TypeVar("T")

ValueOrError = Union[T, BaseException]


class Result(Generic[T]):
    value: Optional[T]
    error: Optional[BaseException]

    def __init__(self, result: ValueOrError) -> None:
        (self.value, self.error) = (
            (None, result) if isinstance(result, BaseException) else (result, None)
        )
```

Pylance in VS Code reports:

```
Cannot assign member "value" for type "Result[T@Result]"
  Expression of type "T@ValueOrError | None" cannot be assigned to member "value" of class "Result[T@Result]"
    Type "T@ValueOrError | None" cannot be assigned to type "T@Result | None"
      Type "T@ValueOrError" cannot be assigned to type "T@Result | None"
        Type "T@ValueOrError" cannot be assigned to type "T@Result"
        Cannot assign to "None"

```

![obrazek](https://user-images.githubusercontent.com/7354817/108512727-eddefa80-72c1-11eb-98fa-151738cb4825.png)

While mypy reports  (IMHO correctly) no issue :

![obrazek](https://user-images.githubusercontent.com/7354817/108512875-1cf56c00-72c2-11eb-9a22-47b54cc51e75.png)

**Comment by erictraut** [comment]
The problem here is that you have defined a generic type alias `ValueOrError`, but you are not providing a type argument for it when you use it. TypeVar `T` in the type alias is a different instance than TypeVar `T` that you use in the `Result` class. 

The fix is simple:
```python
    def __init__(self, result: ValueOrError[T]) -> None:
```

If you enable the `reportMissingTypeArgument` diagnostic check (or enable "strict" type checking mode), pylance will emit errors if you attempt to use a generic type alias and mistakenly omit the type argument(s).

I'm not sure why mypy allowed this. It could be a bug in mypy. Or maybe it interpreted your code to mean `ValueOfError[Any]`, which is probably not what you intended.

**Comment by hanpari** [comment]
OK. Thank you.
