### ISSUE TITLE
Two borderline situations that look simple and confuse Pylance

### ISSUE THREAD

**Issue by PatrickBourdon** [microsoft/pylance-release#976]
## Environment data
-   Windows-10-10.0.18362-SP0
-   python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
-   Visual Code Studio: 1.53.2
-   extension pylance: v2021.2.3
-   type checking mode: strict

## Expected behaviour
no typing problem reported.

## Actual behaviour
See the two examples below.

## Code Snippet / Additional information

# Situation 1:

```python
from typing import TypedDict, Any, Union

W1: list[Union[None, int]] = [None, 1, None, 2]
W2: list[int] = [ w for w in W1 if (w is not None) ]
# There is no problem here, pylance correctly excludes 'None' as a possible type for w.

# Adding some complexity:
X1: list[tuple[Any, Union[None, int]]] = [
    (37, 1),
    ('b', None),
    (None, 2),
]
X2: list[int] = [ x[1] for x in X1 if (x[1] is not None) ]
# Expression of type "list[int | None]" cannot be assigned to declared type "list[int]"
#   TypeVar "_T@list" is invariant
#     Type "int | None" cannot be assigned to type "int"
#       Type "None" cannot be assigned to type "int"
```

The issue: 
  - The surprising point is that pylance error message shows that it correctly deduces 
    that the type of `x[1]` is `Union[None, int]`,
  - However it does not exclude 'None' from the `X2` final list, as it did for `W2`.

``` python
# Workaround: remove the index:
X3: list[int] = [ x1 for (_, x1) in X1 if (x1 is not None) ]
```

# Situation 2:

```python
class TD_required(TypedDict):
     a: int
     b: str
class TD(TD_required, total=False):
     c: float
     d: list[int] 
# So from the typing perspective, `a` et `b` keys are required keys,
# while `c` and `d` are optional keys.

td1 = TD(a=1, b='z', c=0.5)
td2 = TD(a=3, b='y', d=[1, 2])
td3 = td1 | td2
# Operator "|" not supported for types "TD" and "TD"
print(str(td3))
# {'a': 3, 'b': 'y', 'c': 0.5, 'd': [1, 2]}
```

The issue:
  - It's a bit disappointing since the union of two instances of a given `TypedDict` class `TD` is stable, 
    i.e. result is a `dict` which keys comply with the mandatory/optional of the `TD` definition.

**Comment by jakebailey** [comment]
I've edited your post to make it more readable. Cramming two issues into a single code box does not render well on GitHub. It's best to only put code in code blocks (and preferably, make one issue per issue, not two issues in one issue...)

Your first case is likely to be fixed by microsoft/pyright#1494 (which will be pulled into the next Pylance release).

Your second case uses the `|` operator, but it's not clear to me that `|` is a supported operator according to the stub for `TypedDict`; it doesn't list `__or__` as a method: https://github.com/python/typeshed/blob/97f9acf4eee019d4ca8d179f33ebd11f09452045/stdlib/typing.pyi#L658 Have I missed something?

**Comment by erictraut** [comment]
Jake is correct on both accounts.

The first issue is fixed in pyright already.

For the second issue, TypedDict does not support `__or__`. As evidence, mypy emits the same error here. I'm not sure what the rationale was for not supporting `__or__` for compatible TypeDict instances. Perhaps it was just an oversight? @gvanrossum might know since he was involved in the TypedDict spec.

**Comment by gvanrossum** [comment]
I think it's because TypedDict was specified before `dict.__or__` existed. Nothing deep.

**Comment by erictraut** [comment]
I can't think of any TypedDict semantic or type safety violations that would result from supporting `TypedDict.__or__` and `TypedDict.__ior__` as long as the `__value` parameter is the same TypedDict type (or a subtype thereof). 

I'll submit a PR to typeshed that adds the following to the `typing._TypedDict` class. That should make this work across all type checkers.

```python
        def __or__(self: _T, __value: _T) -> _T: ...
        def __ior__(self: _T, __value: _T) -> _T: ...
```

**Comment by jakebailey** [comment]
FWIW, the above change will be in the next Pylance release, so your `|` case will typecheck.
