### ISSUE TITLE
type issue when list str + list literal

### ISSUE THREAD

**Issue by smartlei24** [microsoft/pylance-release#98]
## Environment data
Pylance Version:  2020.7.1
Python:  3.8.2

-   Language Server version: Pylance language server 2020.7.1
-   OS and version:   WSL Ubuntu-20.04 on Windows 10
-   Python version: 3.8.2

## Expected behaviour

No issue when append str list to literal list. 

## Actual behaviour

There is a  `reportGeneralTypeIssue`, but these code works fine.

![image](https://user-images.githubusercontent.com/21335160/87275640-23905980-c511-11ea-9752-787e25f02850.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
literals = (
    "1",
    "2"
)

final_str_list = list(literals) + [
    "3"
]
```

**Comment by erictraut** [comment]
This behavior is intended.

When a type checker encounters a statement like `("1", "2")`, it needs to decide the type of this expression. If type annotations are present (e.g. you're assigning it to a variable with an annotated type), it uses the provided type information as a hint. Absent any hints, it needs to infer the type. All of the following are arguably correct for the expression in your example above.
```
Tuple[Literal["1"], Literal["2"]]
Tuple[str, str]
Tuple[Literal["1", "2"], ...]
Tuple[str, ...]
Tuple[Any, Any]
Tuple[Any, ...]
```

Which type should it infer? In the case of tuples, Pylance/Pyright uses the most specific type possible, which is the first item in the list. That makes sense because tuples contain ordered information, and if that information can be preserved in the inferred type, it will improve type checking. For example, this allows the type checker to know that the type of `literals[0]` is `Literal["1"]` rather than `str`.

If `literals` now has an inferred type of `Tuple[Literal["1"], Literal["2"]]`, how does that lead to the error you're seeing? The `list` constructor, as defined in `builtins.pyi` is annotated as follows:
```
def __init__(self, iterable: Iterable[_T]) -> None: ...
```

The type `Tuple[Literal["1"], Literal["2"]]` matches the `Iterable` protocol, and TypeVar `_T` is given the value of `Literal["1", "2"]`. This results in a type of `List[Literal["1", "2"]]`.

The `+` operator for the list class is defined as follows:
```
def __add__(self, x: List[_T]) -> List[_T]: ...
```

This means that the type of list that's being appended (the RHS) must match the type of the list it's being added to (the LHS). In your case, the type of the LHS is `List[Literal["1", "2"]]`, and the type of the RHS is `List[Literal["3"]]`, so there is a type mismatch.

There are a few workarounds to silence the error:
1. Provide an annotated type for your tuple:
```
literals: Tuple[str, ...] = ("1", "2")
```

2. Provide an annotated type for the list:
```
str_list: List[str] = list(literals)
final_str_list = str_list + ["3"]
```

**Comment by smartlei24** [comment]
@erictraut thx for your comment, that's solved my problem.
