### ISSUE TITLE
Why does Union of types not resolve to this generic function definition?

### ISSUE THREAD

**Issue by smeznaric** [microsoft/pylance-release#983]
I have the following example. 

```
from typing import Union, TypeVar, Dict, Sequence

IdentifierSymbol = TypeVar("IdentifierSymbol", str, int)

def f(ids: Sequence[IdentifierSymbol]) -> Dict[int, IdentifierSymbol]:
    return dict(zip(range(len(ids)), ids))


def g(ids: Union[Sequence[int], Sequence[str]]) -> int:
    x = f(ids) # Problem here
    return 1

```

PyLance complains with the following in the line `x=f(ids)`:
```
Argument of type "Sequence[int] | Sequence[str]" cannot be assigned to parameter "ids" of type "Sequence[IdentifierSymbol@f]" in function "f"
  Type "Sequence[int] | Sequence[str]" cannot be assigned to type "Sequence[IdentifierSymbol@f]"
    TypeVar "_T_co@Sequence" is covariant
      Type "str" is not compatible with constrained type "int" PylancereportGeneralTypeIssues
```

I am not sure how to interpret this, but it sounds like the problem is that int is not compatible with str. But why is this an issue in this case? I have either a sequence of strs or a sequence of ints, where does the compatibility between int and str come in?

Using overload instead of generic types still doesn't resolve. Any hints as to how to do this correctly?

**Comment by erictraut** [comment]
The type constraint solver needs to solve for `IdentifierSymbol`, and it does so by considering all of the assignments to it. In your example, the type of `ids` is `Sequence[int] | Sequence[str]`, so both `int` and `str` are being assigned to `IdentifierSymbol`. When multiple distinct types are assigned to a TypeVar, the constraint solver needs to find a common type that satisfies both. Pylance/pyright solve this by creating a union of the two types, so in this example, `IdentifierSymbol` is solved as `str | int`. Mypy takes a different approach and "joins" the two by finding a common ancestor. In this case, the common ancestor is `object`. Both Pylance/pyright and Mypy emit an error because the type determined by the constraint solver (`int | str` or `object`) do not match the constraints imposed by `IdentifierSymbol`, which says that the type must be either a `str` or an `int`.

I know this is a bit unintuitive, but it's how constraint solving works in the Python type system.

I can see a few workarounds:
1. Remove the constraints `int` and `str` from `IdentifierSymbol`. This workaround works in both Pylance/pyright and in Mypy.
2. Replace the constraints `int` and `str` with a `bound=Union[int, str]`. This works fine in Pylance/pyright, but Mypy doesn't seem to like it for reasons I don't understand.

Here's one more potential workaround that uses a new type feature that will appear in Python 3.10. It's documented in PEP 647.

```python
from typing import Any, Type, TypeGuard, Union, TypeVar, Dict, Sequence

IdentifierSymbol = TypeVar("IdentifierSymbol", int, str)
T = TypeVar("T")

def is_sequence_of(ids: Sequence[Any], type: Type[T]) -> TypeGuard[Sequence[T]]:
     return len(ids) == 0 or isinstance(ids[0], type)

def f(ids: Sequence[IdentifierSymbol]) -> Dict[int, IdentifierSymbol]:
    return dict(zip(range(len(ids)), ids))

def g(ids: Union[Sequence[int], Sequence[str]]) -> int:
     if is_sequence_of(ids, int):
         x = f(ids)
     elif is_sequence_of(ids, str):
         x = f(ids)
     return 1
```

**Comment by smeznaric** [comment]
Thanks! We're currently still on an older version of Python, but hope to be able to explore this feature when we migrate.

It seems that it also works if I try to define g as `def g(ids: Sequence[IdentifierSymbol]) -> int`, but then PyLance doesn't like that I am using the TypeVar only once (presumably because it's not happy that I am making it seem like a generic).

**Comment by jakebailey** [comment]
I'm not sure there's any other work to be done here; this is a product of how the type system works.
