### ISSUE TITLE
Extrapaths doesn't discriminate path of imported file relative to importing file

### ISSUE THREAD

**Issue by chrissyast** [microsoft/pylance-release#988]
## Environment data

-   Language Server version: 2021.2.3
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.7

## File Structure

Bar
|__main.py
|__utilities.py
Foo
|__main.py
|__utilities.py

```
    "python.analysis.extraPaths": [
        "./Bar",    
        "./Foo",
    ],
```

### foo/main.py

```
import utilities
...
```

## To reproduce
Click on `utilities` and press F12 for definition

## Expected behaviour

VSCode jumps to `foo/utilities.py`

## Actual behaviour

VSCode jumps to `bar/utilities.py`, because this is the first defined path in `python.analysis.extraPaths` with a file called `utilities`

![import](https://user-images.githubusercontent.com/31564153/109138933-d2a53c80-7752-11eb-86a8-a3eda1b571f8.gif)

**Comment by erictraut** [comment]
Extra paths are searched in the order in which they are specified. You have listed `./Bar` first, so that will be searched prior to `./Foo`.

If you would like each subproject to act like its own program, you can use the "execution environments" feature within the pyrightconfig.json configuration file documented [here](https://github.com/microsoft/pyright/blob/master/docs/configuration.md). (Pylance is built upon the pyright type checker and supports the more advanced configuration features of pyright.)

**Comment by chrissyast** [comment]
@erictraut Thanks for your reply. Execution environments seems perfect for what I need. Would I just need to create a pyrightconfig.json in the project root and configure it there?

**Comment by chrissyast** [comment]
@erictraut Sorry, just had a closer look and saw that it said that 

> @erictraut Thanks for your reply. Execution environments seems perfect for what I need. Would I just need to create a pyrightconfig.json in the project root and configure it there?

Sorry, just had a closer read and saw that it says that very thing on the first paragraph 🤦
