### ISSUE TITLE
Dictionary keys set to 'Unknown' when entered with 'dict()' syntax

### ISSUE THREAD

**Issue by PatrickBourdon** [microsoft/pylance-release#989]
## Environment data
-   Windows-10-10.0.18362-SP0
-   python(3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)])
-   Visual Code Studio: 1.53.2
-   extension pylance: v2021.2.4
-   type checking mode: strict

## Expected behaviour
no typing problem reported.

## Actual behaviour
see example below

## Code Snippet / Additional information
```python
x: dict[str, int] # line added to help pylance, but it doesn't
for x in (
    dict(a=1, b=2),
    dict(c=3, d=4),
):
    ...
# Type of "x" is partially unknown
#  Type of "x" is "dict[Unknown, int]"


# no issue when swapping syntax
for a in (
    { 'a': 1, 'b': 2 },
    { 'c': 3, 'd': 4 },
):
    ...

```

**Comment by erictraut** [comment]
This is intended behavior. Here's what's happening.

The `dict` constructor is defined in the `builtins.pyi` stub as follows:
```python
    @overload
    def __init__(self, **kwargs: _VT) -> None: ...
    @overload
    def __init__(self, map: SupportsKeysAndGetItem[_KT, _VT], **kwargs: _VT) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Tuple[_KT, _VT]], **kwargs: _VT) -> None: ...
```

The first overload is the one that applies in your example. It doesn't provide any way for the type checker to determine the `_KT` type argument because this type variable doesn't appear in the overload. Pylance therefore must assume an `Unknown` type. The `Unknown` type is a special alias of `Any`. That particular form of dict construction is problematic for strict type checking.

You have annotated `x` to be `dict[str, int]`. When a value is assigned to a variable, type narrowing is applied. When a value of `dict[Unknown, int]` is assigned to a variable whose declared type is `dict[str, int]`, its narrowed type becomes `dict[Unknown, int]`.

There are a couple of easy workarounds:
```python
for x in (
    {"a": 1, "b": 2},
    {"c": 3, "d": 4},
):
```
or
```python
for x in (
    dict({"a": 1, "b": 2}),
    dict({"c": 3, "d": 4}),
):
```

Both of those avoid the unfortunate `dict` constructor overload.

**Comment by PatrickBourdon** [comment]
Ok, thank you. I'll try look to pyi files before reporting an issue.
